### ISSUE TITLE
Demo binary as AppImage (Linux)

### ISSUE THREAD

**Issue by Symbian9** [ocornut/imgui#1005]
Add binary Demo for Linux  as AppImage package.
* https://github.com/probonopd/AppImageKit

Cast @probonopd

**Comment by ocornut** [comment]
I don't have Linux and maintaining binaries is lots of work. The demo should be trivial to compile under a Linux system using the GLFW based demos.

If you want to step in a as Linux demo binary maintainer we can do it otherwise I will close it.

**Comment by Symbian9** [comment]
> If you want to step in a as Linux demo binary maintainer we can do it otherwise I will close it.

@ocornut, Please, wait for answer from probonopd. Hi can make AppImage

**Comment by probonopd** [comment]
[AppImage](http://appimage.org) is a format that enables upstream application authors to distribute binaries directly to end users without intermediaries. I am happy to help upstream application projects that want to provide (and support) AppImages. Is this the case here?

**Comment by ocornut** [comment]
I the maintainer I am personally not willing to engage in anything non necessary for this project. The project is a library rather than an application - so, targetted at deva - and compiling the samples under Linux has traditionally been very easy.

I don't think this is any necessary. @symbian9 has just been requesting various things without showing the signs of being a user of imgui.

**Comment by ocornut** [comment]
To be clear, if anyone such as @symbian9 wants to step in to maintain it I won't mind and would support it. But I can't be thinking about it myself.
