### ISSUE TITLE
ImGui Tabs issue

### ISSUE THREAD

**Issue by emilo0212** [ocornut/imgui#1022]
So I'm trying to get these damn tabs to work, but each time I fail, rip.

I've managed to make 5 buttons aligned horizontally, but when I press on a button, nothing of the code I attached to that case appears.

http://pastebin.com/7gHun0kh

**Comment by ocornut** [comment]
The imgui part of that code should work. You are missing break statements here.

**Comment by emilo0212** [comment]
I'm telling you, these buttons or whatever, doesn't work when it comes to tabs. I found out that Selectable works. Either I'm retarded and can't get it to work, or something is actually messing with the code, I've also seen many posts about it here, and people simply can't get these tabs to work with buttons. I personally think you should take a look at it, and see if you can get it to work, if you can, then just reply that it works, no need for the code.

**Comment by ocornut** [comment]
I know it works.  Looking at the code the Button() will return turn when pressed.
You are showing incomplete code (not saying how you are drawing the tabs), and I am pointing out a bug in the code you posted (the missing break).
The only other similar post was from someone also confused with the C++ language. While I am happy to help and doing more than I should, please be considerate that the burden of proof is on your side. If you can provide me with a piece of code that I can paste within ImGui example that showcase a bug I will fix it, but here it is probable that the bug is in yours. Right now you are providing incomplete code and ignored the fact that there is a bug in your code that I pointed.

**Comment by emilo0212** [comment]
I understand... Well, I can tell you that there is no bug in my code, since instead of showing tabs, when I pressed the buttons it would show a new window called "Debug", so the buttons did do "something" and that was to open a Debug window with the features inside it. 

But I've fixed it now, thanks for your information, I will keep it all in mind.

**Comment by ocornut** [comment]
The implicit "Debug" appears if you submit widgets/items outside the scope of a Begin/End pair.
Basically ImGui surrounds your frame with a Begin("Debug")/End() and hides the window at the end if it hasn't been used.
