### ISSUE TITLE
SDL-based Samples should not force ShowCursor() calls

### ISSUE THREAD

**Issue by Klaim** [ocornut/imgui#1027]
Not sure how to handle this case generally so I'm asking here:

This is about this line:

https://github.com/ocornut/imgui/blob/master/examples/sdl_opengl3_example/imgui_impl_sdl_gl3.cpp#L389

And the same line in the SDL2 example.

Basically, this is forcing a call to `SDL_ShowCursor()` but totally ignores the previous mouse cursor state or the intent of the user code: if the game code previously dit `SDL_ShowCursor( 0 )` to hide the OS mouse cursor, then the `ImGui_ImplSdlGL3_NewFrame()` call will force display it `SDL_ShowCursor( 1 )` as long as `io.MouseDrawCursor` is false. So the previous setup for OS mouse cursor display is always overwritten by the example code.

Ideally, making IMGUI draw the cursor should be totally independent to the OS cursor display state, so that the user code can change one or the other at will.

I can fix it for my specific case of course, by removing this line in my copy; and it's just the example code, so it's not a big issue.

I was considering providing a patch fixing it "in general" but I'm not sure of the approach. The simplest way that works (I tried) without removing the line is to never call `SDL_ShowCursor( anything );` if we didn't ask imgui to draw the cursor.
In this case, the user code is totally in control of the OS cursor and imgui example code isn't impacting it.
This seem to work for me but I didn't test it in all cases yet (replacing the pointed lines):

    // Hide OS mouse cursor if ImGui is drawing it and it is visible
    if (io.MouseDrawCursor)
        SDL_ShowCursor(SDL_DISABLE); // not sure if it's ok to call it each frame

This is still hiding the OS cursor if you set `io.MouseDrawCursor = true`, to keep previous behaviour, but in other cases it do not do anything. Frankly I think it would better to just remove the line and let the user code decide, but it is an example code, so both removing and this change are fine to me.

What do you think?

**Comment by ocornut** [comment]
Hello @Klaim,

Sorry for my late answer. This issue has been on the back of a my mind for a while.

A few things:

- In 1.60 we added a `ImGuiConfigFlags_NoMouseCursorChange` flag (set `io.ConfigFlags`) to request the backend to never touch the cursor.
- Additionally, if the backend is taking care of the cursor, your user code may call `ImGui::SetMouseCursor(ImGuiMouseCursor_None)` to request hiding the cursor, which may or not be adequate depending on your use case.
- For the GLFW backend, we have an extra check to reduce the need for `ImGuiConfigFlags_NoMouseCursorChange` which is that we check the case where the cursor is already disabled. This only works because in GLFW the InputMode is a tri-state thing and we don't use `GLFW_CURSOR_DISABLED`.

If it's a 100% perfect situation but at the moment I cannot think of something better to do. With the `ImGuiConfigFlags_NoMouseCursorChange` flag you can easily take control. I will make this flag more prominent in the documentations/comments now

Note that that refactored examples were pushed this week-end, so now all the SDL code is in a single spot, in imgui_impl_sdl.cpp.

Reference, current SDL code:
```
static void ImGui_ImplSDL2_UpdateMouseCursor()
{
    ImGuiIO& io = ImGui::GetIO();
    if (io.ConfigFlags & ImGuiConfigFlags_NoMouseCursorChange)
        return;

    ImGuiMouseCursor imgui_cursor = ImGui::GetMouseCursor();
    if (io.MouseDrawCursor || imgui_cursor == ImGuiMouseCursor_None)
    {
        // Hide OS mouse cursor if imgui is drawing it or if it wants no cursor
        SDL_ShowCursor(SDL_FALSE);
    }
    else
    {
        // Show OS mouse cursor
        SDL_SetCursor(g_MouseCursors[imgui_cursor] ? g_MouseCursors[imgui_cursor] : g_MouseCursors[ImGuiMouseCursor_Arrow]);
        SDL_ShowCursor(SDL_TRUE);
    }
}
```

Current GLFW code:
```
static void ImGui_ImplGlfw_UpdateMouseCursor()
{
    ImGuiIO& io = ImGui::GetIO();
    if ((io.ConfigFlags & ImGuiConfigFlags_NoMouseCursorChange) || glfwGetInputMode(g_Window, GLFW_CURSOR) == GLFW_CURSOR_DISABLED)
        return;

    ImGuiMouseCursor imgui_cursor = ImGui::GetMouseCursor();
    if (imgui_cursor == ImGuiMouseCursor_None || io.MouseDrawCursor)
    {
        // Hide OS mouse cursor if imgui is drawing it or if it wants no cursor
        glfwSetInputMode(g_Window, GLFW_CURSOR, GLFW_CURSOR_HIDDEN);
    }
    else
    {
        // Show OS mouse cursor
        // FIXME-PLATFORM: Unfocused windows seems to fail changing the mouse cursor with GLFW 3.2, but 3.3 works here.
        glfwSetCursor(g_Window, g_MouseCursors[imgui_cursor] ? g_MouseCursors[imgui_cursor] : g_MouseCursors[ImGuiMouseCursor_Arrow]);
        glfwSetInputMode(g_Window, GLFW_CURSOR, GLFW_CURSOR_NORMAL);
    }
}
```

Let me know if there's something more you think we could do, otherwise I am going to close this.

**Comment by Klaim** [comment]
Unfortunately I can't test these changes for the moment so I can't comment on practice.

From what you describe, this seems reasonable at least in theory, so I will close this ticket and if in the future I see an issue linked to that setup I'll either create another ticket or open this one.
No need to worry more I think.
