### ISSUE TITLE
Premultiplied alpha/alternate blendmodes

### ISSUE THREAD

**Issue by Alloyed** [ocornut/imgui#1035]
I'm actually working with a premade integration, and if this an integration-specific problem, I apologize in advance.

Anyways, I'd like to use `imgui.Image()` with canvases/render-textures to create complex widgets. The problem is that in the framework I'm using, love2d, rendering produces images with premultiplied alpha, which looks incorrect when you render them inside imgui. Top is the intended result, bottom is what I actually get:
![2017-02-22-115635_394x230_scrot](https://cloud.githubusercontent.com/assets/137977/23222475/01af757a-f8f6-11e6-921a-ccf3e2b3def9.png)

I can manually ask for premultiplied alpha, which renders my canvas correctly, but ruins everything else:
![2017-02-22-115608_397x176_scrot](https://cloud.githubusercontent.com/assets/137977/23222474/01aee6fa-f8f6-11e6-8be7-8049620c1969.png)

I looked around a bit in the source, but I couldn't find anything related to blendmodes at all, so I'm assuming imgui as it exists doesn't handle this for me. What would be the best approach here? Should this be handled on the integration layer (always render X texture as premultiplied), or should I be able to specify the blendmode through imgui?

**Comment by ocornut** [comment]
Hello,

Usually what you would do in this context is change ImTextureId to pass a higher-level primitive. The default OpenGL example are passing the raw GL Gluint texture identifier in ImTextureId, but say, if Love has a `LoveTexture*` type (just making that up) you could decide that ImTextureId is `LoveTexture*` and then in your renderer you can apply render state (such as blending) depending on your render state.

Alternatively, you could hardcode in your renderer loop that when the texture id is == `ImGui::GetIO().Fonts->TexID` then you could set blending that for non-premultiplied alpha and otherwise set them for premultiplied alpha.

Alternatively, after calling `GetTexDataAsRGBA32()` you could modify the ImGui pixel data to be premultiplied alpha. (we should perhaps add an option to automatically have ImGui do it for you, but the code should be straightforward)

**Comment by slages** [comment]
Yep it's definitely something managed on the LÖVE implementation side, I'll have a look on how to properly handle it!

**Comment by Alloyed** [comment]
Thanks for your help, this has been resolved downstream~
