### ISSUE TITLE
Characters input problem

### ISSUE THREAD

**Issue by Artalus** [ocornut/imgui#105]
GitHub's interface is pretty unusual for me, so please forgive me if this is not the correct place to ask a question of help.

I've encountered a problem with inputing characters to ImGui. When I try to input a single 'a' into a ImGui::InputText, instead inputs several "aaaa", up to 10-20. Same happens with inputing values to ImGui::SliderFloat and any other control that allows keyboard input.

I thought that there might be something wrong with my KeyPress callback (maybe it was called continuously multiple times while I hold the key for ~2-3 ms) so i put a simple printf("%c",key) into it - and the callback works fine; when I press 'a', there is 'a' in my console output window, but still "~aaaaaaaaaa" in ImGui.

My last assumption was that I messed somewhere with ImGui::IO::DeltaTime, so I copied the corresponding code from the example (and also moved from GLUT to GLFW because of its glfwGetTime) and the problem still occurs. Now I am completely out of ideas how to fix this, since in example programs everything works just fine and I can not find any other differences that might apply this effect.

I would be very glad to hear an idea of how to fix this bug, or at least what else can cause it. While I don't plan to use keyboard input somewhere in my app, only process some buttons and checkboxes, it still puzzles me since I can't understand it's nature and so predict if it won't occur with any other system.

**Comment by ocornut** [comment]
Hello,

- Characters are being added when calling ImGui::GetIO().InputCharacters
- Characters are read/used by e.g. ImGui::InputText() when it get focus.
- Characters are currently consumed when calling ImGui::Render()

So at the moment if you are rendering your interface multiple times (calling NewFrame() multiple times essentially) between each call to ImGui::Render() then the characters will be incorrectly input multiple times.

It would be more correct if ImGui "consumed" the input characters as they were used, because they can't be used multiple times. I'll do this change shortly.
However if you are doing 1 render for multiple frames there will likely be others sort of problems (which I am not against to try eliminating).

**Comment by ocornut** [comment]
I have committed a patch which fixes the issue you were seeing.
My intuition however is that there might be other bugs depending on how your main loop is set-up, but I couldn't find one in my quick test yet. Let me know if you find anything!

**Comment by Artalus** [comment]
>>calling NewFrame() multiple times essentially between each call to ImGui::Render()
>>
Exactly the situation I have - calling App::Render() once on a several App::Update() ... Guess I have to take a more attentive look at the internals of ImGui. Mighty thanks for your answer and operative hotfix!

**Comment by ocornut** [comment]
I think it is fine using it as is (and I wouldn't mind the extra testing it brings!)
But every frame of UI you are generating and not rendering is essentially wasting CPU time, which may or not be a worry for you.
