### ISSUE TITLE
API Change: BeginWithWindow

### ISSUE THREAD

**Issue by emoon** [ocornut/imgui#106]
Hi,

I have made some local changes to the API was curious if this is something you would like to have (also makes merging for me easier :)

```
imgui.h

namespace ImGui
{
  ...
   // Window
	IMGUI_API bool 			BeginWithWindow(ImGuiWindow* window, const char* name = "Debug", bool* open = NULL, ImVec2 size = ImVec2(0,0), float fill_alpha = -1.0f, ImGuiWindowFlags flags = 0);
}
```

Implementation is like this (my code is currently 1.18 so might not match ~100% with HEAD)

```
// Push a new ImGui window to add widgets to. This can be called multiple times with the same window to append contents
bool ImGui::Begin(const char* name, bool* open, ImVec2 size, float fill_alpha, ImGuiWindowFlags flags)
{
   ImGuiWindow* window = FindOrCreateWindow(name, size, flags);
   return BeginWithWindow(window, name, open, size, fill_alpha, flags);
}

// Push a new ImGui window to add widgets to. This can be called multiple times with the same window to append contents
bool ImGui::BeginWithWindow(ImGuiWindow* window, const char* name, bool* open, ImVec2 size, float fill_alpha, ImGuiWindowFlags flags)
{
   // this works just as regular old Begin expect it takes in the window
   // ...
}
```

The purpose of this change is that I can create (using FindOrCreateWindow) windows from the outside as it makes the life much easier for me when changing attributes of the windows (size, pos, etc)

I never expose the ImGuiWindow struct also and so all calls that changes something in ImGuiWindow are just function calls an no code from the outside knows about the internals.

**Comment by ocornut** [comment]
Daniel,

I am not sure how creating windows from the outside (or in advance) makes a difference there ?
Are you changing the pos/size attributes by poking into ImGuiWindow structure or using the SetNextWindowsPos() and variants api ? With the later you shouldn't need to know about ImGuiWindow.

There is a guaranteed 1 to 1 match between a pointer to ImGuiWindow and a name* so this should be enough of an identifier.

So typically in your case the usage pattern may be

SetNextWindowPos()
SetNextWindowSize()
Begin()
...
End()

So right now I am hesitant to merge your change if I don't see a requirement for it. Also just noticed that ImGuiWindow was forward declared in imgui.h which wasn't intentional.

Then the other difference if that you are caching the result of search-by-name (which ImGui could easily optimize, will do) but I assume that isn't much of a concern for you at the moment.

Let me know.

(*) note that you can hide unique identifier in a name string by using the "ActualName##HiddenPart" syntax in a name.

**Comment by emoon** [comment]
The way it works is that I use it like this:

```
void pluginUpdate(pluginData* data)
{
    ImGui::BeginWithWindow(data->window, data->name, &data->showWindow, ImVec2(0, 0), true, 0);

    instance->plugin->update(instance->userData, uiInstance, reader, writer);

    ImGui::End();
}
```

The plugins never call ImGui directly but using a C API (a struct with function pointers) to make sure ImGui or whatever API one uses is never exposed to the plugins.

Later on I can also use the data->window pointer to set sizes and such.

**Comment by ocornut** [comment]
That should work as well. SetNextWindowPos() etc do not take a window parameter but refer to the next call to Begin().

So I don't see what your code here wouldn't work with just a normal ImGui::Begin() and removing the first parameter.

**Comment by emoon** [comment]
Alright. I guess I have to move my code around as I don't set the size in that update as it was cleaner to have it elsewhere.

**Comment by ocornut** [comment]
I could add API to set the pos/size by name/id as well.

**Comment by emoon** [comment]
I think it should be fine as is. I will try it out now. Cheers!

**Comment by emoon** [comment]
Got this working with latest version.

**Comment by samuell-0** [comment]
> I could add API to set the pos/size by name/id as well.

That would be nice.
