### ISSUE TITLE
Detection hovering your mouse over a nonstandard figure (Slider in the form of a triangle)

### ISSUE THREAD

**Issue by colesnicov** [ocornut/imgui#1067]
Hi Omar. Please, try to create sliders in the form of a triangle but can not always figure out how to capture if the mouse cursor is located above the slider.
Rendering the triangle looks like this:

```
ImRect bbMin(ImVec2(64, 114), ImVec2(64 ,114));
ImRect bbMax(ImVec2(222, 89), ImVec2(222, 114));
ImDrawList* dl = ImGui::GetWindowDrawList();
dl->AddQuadFilled(bbMin.Min, bbMin.Max, bbMax.Min, bbMax.Max, ImColor(0, 0, 255, 255));
```

How can I tell if the mouse cursor is over the triangle?

Thanks!

**Comment by ocornut** [comment]
I'm not sure I understand your question. Please clarify, provide more context and look at existing widgets, they all use similar code to detect mouse overlapping a given rectangle.

**Comment by ocornut** [comment]
@colesnicov Have you found a solution to your problem? Shall this issue be left opened?

**Comment by colesnicov** [comment]
Hi Omar. This theme for me is not acute. So I have not resolved yet.
Basically, I want to create a slider for volume control.
I really want something similar to the VLC or how it is on this picture
https://lh5.ggpht.com/wfZl4Jz87L5niTyS4dgah2hgGXDlUb7kTTQIkBaBT45zUIlN5HH9GJ5tvDvDI2kC2w=h900
But now that I think about it, I probably do it this way
https://petegoodman.com/assets/images/labs/mac-php-js-volume-control/desktop-home.jpg
Using "histogram plot"

----------------------------------------------------------------------------
I'm not going to deal with it yet. You can calmly close it. I will find the solution, publish it + screenshots

**Comment by ebachard** [comment]
@colesnicov 

If I correctly understand your question, in imgui.cpp, there is maybe something. More precisely a bool named ImIsPointInTriangle() taking p, a, b and c points as arguments (lines around 879 and 885) be an answer ?

bool ImIsPointInTriangle(const ImVec2& p, const ImVec2& a, const ImVec2& b, const ImVec2& c)
{
    bool b1 = ((p.x - b.x) * (a.y - b.y) - (p.y - b.y) * (a.x - b.x)) < 0.0f;
    bool b2 = ((p.x - c.x) * (b.y - c.y) - (p.y - c.y) * (b.x - c.x)) < 0.0f;
    bool b3 = ((p.x - a.x) * (c.y - a.y) - (p.y - a.y) * (c.x - a.x)) < 0.0f;
    return ((b1 == b2) && (b2 == b3));
}

If I'm not wrong, p.x and p.x are mouse cursor coordinates, a, b and c are the 3 points making the triangle.

I didn't test it yet (was busy), but I just verified the demonstration in one case, and if I'm not wrong, it is based on the vector product between, respectively  cb and cp (e.g.) giving a result oriented along -z axis. You can verify for other cases, doing the same 3 times, by permutation with other points.

I don't know whether this result can be generalized to more points (I'd use the convex hull instead), nor whether this is the best way to be sure the mouse cursor is over a triangle, but I trust @ocornut  ;-)
Please anyone correct me if I'm wrong, because I'd like to learn more about this method.
thanks

-- 
ericb

**Comment by ocornut** [comment]
Closing this @colesnicov .
Note that the function Eric mentioned is now exposed in `imgui_internal.h` as `bool ImTriangleContainsPoint(const ImVec2& a, const ImVec2& b, const ImVec2& c, const ImVec2& p);` so you may use it if you want to pursue further experiment toward this.
