### ISSUE TITLE
How to remove chars from input?

### ISSUE THREAD

**Issue by funbiscuit** [ocornut/imgui#1069]
I just found out, that pressing backspace while doing input text (or other input) does nothing. I'm using glfw gl3 example.  I tried to find any built in function to tell imgui to delete chars but found nothing. Only function to clear whole input but that's not what I need.
So how to make backspace and delete keys to work?

**Comment by ocornut** [comment]
You are mixing up two things here.
If backspace doesn't work you have a problem. Is your backend passing the correct key and has it mapped in the KeyMap[] array? KeyMap[ImGuiKey_Backspace] should contains the index of KeyDown[] that contains your value for backspace, etc.

FYI
You can filter characters inputs using the callback mechanism of InputText(),
You can also delete characters from the content also using the callback mechanism of InputText().
However if you are only trying to get Backspace to work, none of those are appropriate answers so that problem. Backspace should be working in the first place.

**Comment by ratchetfreak** [comment]
you need to fill io.KeyMap so that  `io.KeysDown[io.KeyMap[ImGuiKey_Backspace]]` corresponds with the state of the backspace key. Same for ImGuiKey_Delete.

**Comment by funbiscuit** [comment]
Yes, I'm just trying to get backspace to work. I use default file from examples (opengl3) that is using glfw. In the init function:


    io.KeyMap[ImGuiKey_Delete] = GLFW_KEY_DELETE;
    io.KeyMap[ImGuiKey_Backspace] = GLFW_KEY_BACKSPACE;

**Comment by ocornut** [comment]
You may check in `ShowTestWindow()` at the bottom if imgui is receiving your key correctly, or maybe you have another issues in your code.

Try to create a simple repro within your codebase perhaps, and double-check that it works with the provided imgui examples.

**Comment by funbiscuit** [comment]
Oh, I found the problem. I'm using my own key callback to do my stuff. And it turns out I can't have two callbacks (one in imgui glfw file and one in my code).
Using one callback in my code and calling from there imgui backend helped.
Thanks for the help. And this library is just pure awesome!

**Comment by ocornut** [comment]
Solved :)
