### ISSUE TITLE
Cmake on Linux: Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by QuantScientist** [ocornut/imgui#1092]
Hi,
Yes, I do know you do not advocate the use of Cmake, but this is how all my projects are configured and its easy for cross compiling. 

I have been trying to use this Cmake based demo project: https://github.com/morizotter/imgui-opengl-glfw-glew-cmake-demo/issues/3 
(I know you did not write this, of course)

It works great on OSX. out of the box, but not on Ubunto. After hours of playing with teh Cmake file and I still get "(interrupted by signal 11: SIGSEGV)" when the it runs, 

Any help would be geratly appreciated, 

Best,

**Comment by ocornut** [comment]
> Yes, I do know you do not advocate the use of Cmake, but this is how all my projects are configured and its easy for cross compiling.

I don't because this isn't how everyone have their project configured. The library is designed so that just compiling the .cpp files would work. You can copy them in your project along with your other sources files, or you can give yourself extra work by creating extra "cmake" or "project" files as you see fit, you are free to do so. I would assume that compiling .cpp files should be a trivial action with any build system including cmake.

Compiling the _samples_ is harder because they have dependencies, but the makefile provided in examples/ should work under OSX. 

As you pointed out this question has nothing to do with imgui or my work, if you are using morizotter's cmake file please discuss it with that person. I can't possibly be helping you to convert a Makefile into a cmakefile as I don't know neither cmake neither osx.

**Comment by ocornut** [comment]
Feel free to post solution here for reference if you have one, although I am guessing that if you search for such cmakefile on the internet you'd find some. I'm just pointing out that it isn't something I can help with myself and it isn't really the place to ask.

**Comment by ocornut** [comment]
> It works great on OSX. out of the box, but not on Ubunto. After hours of playing with teh Cmake file and I still get "(interrupted by signal 11: SIGSEGV)" when the it runs,

If you get a crashing executable you should use a debugger to find out what's crashing, to obtain and provide more information about the crash.

**Comment by QuantScientist** [comment]
Thanks for the detailed response. The first thing I did was to try and debug. But  ... it crashes even before teh debuger has an attempt to load:

![dl__tf_0__-_vnc_viewer](https://cloud.githubusercontent.com/assets/18743986/24831879/935cbb80-1cab-11e7-97d2-77f8b6f7238a.png)

Here is the breakpoint: 
![dl__tf_0__-_vnc_viewer2](https://cloud.githubusercontent.com/assets/18743986/24831885/c8fa4956-1cab-11e7-88fa-81019c6ed94d.png)

**Comment by QuantScientist** [comment]
This is the line causing the crash on Ubuntu:
![dl__tf_0__-_vnc_viewer3](https://cloud.githubusercontent.com/assets/18743986/24832105/f13c23b2-1cb0-11e7-9f01-e6a2fc4f2c9f.png)

**Comment by ocornut** [comment]
The problem doesn't appear to be related to imgui but related to whatever mumbo-jumbo you have built with that project file, perhaps related to dynamic library bindings.

**Comment by ebachard** [comment]
@QuantScientist :  with some minor changes, everything seems to work on Linux too. I have attached a diff under .txt format to the issue you mentionned ( https://github.com/morizotter/imgui-opengl-glfw-glew-cmake-demo/issues/3 ).  First OpenGL 4 is not common under Linuxes boxes, and limit to OpenGL 3.3 or 3.2 fixed the first issue. Secondly, some environment variables must be set in order to use glew without an instant crash. 

HTH

**Comment by mmahdisafari** [comment]
i had some variables which they were not initialized yet then i got "Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)" error
i commented them and the error was gone
