### ISSUE TITLE
ImGuiWindowFlags_AlwaysAutoResize and empty window

### ISSUE THREAD

**Issue by andreyugolnik** [ocornut/imgui#1104]
Hello,

Seems Window title size ignored when window content is empty.

`ImGui::Begin(SomeDynamicTitle_With_WindowId, nullptr, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_AlwaysAutoResize);`
`ImGui::End();`
`ImGui::Render();`

**Comment by andreyugolnik** [comment]
Does anyone know a workaround?

**Comment by ocornut** [comment]
Hello,

So you mean that you would like the width of the title text to be fed back into the window size?

We decided to exclude it from auto-width calculation as it was more desirable for most use cases. 

A)
However we could possibly add a custom flag to handle it, requiring a patch in the code that calculates `size_auto_fit.x` in Begin (a little more annoying than expected because it'll require to add the size of collapsing and close buttons and there's no helpers to provide their width, so either hardcode their width either add the helpers).

B)
Otherwise you can calculate the text width yourself (with `font->CalcTextSizeA()`) and then use `SetNextWindowSize()` or `SetNextWindowSizeConstraints(ImVec2(width,-1), ImVec2(FLT_MAX,-1))`; to enforce a minimum width.

**Comment by andreyugolnik** [comment]
Hello,

In case where title used as FPS indicator without any modules (I mean no window content added) auto size flag is extremely useful.

Application developer may decide which content should be visible at this moment on ImGui window.

Only one title: auto size affects window size and window title become cropped.
```
Fps: 60.0
```

Title and modules: auto size work's fine and title readable.
```
Fps: 60.0
Update time: 2 ms
Render time 3 ms
```

Very long title and modules: title cropped.
```
Fps: 60.0 , Some Useful Information
Update time: 2 ms
Render time 3 ms
```

**Comment by ocornut** [comment]
I'll close this old issue. It's still valid but I don't think we'll be making a change to it. (Interestingly it hasn't been requested since).
Using SetNextWindowSize() or SetNextWindowSizeConstraints() is still a viable workaround.
