### ISSUE TITLE
IMGUI breaks app geometry when using VAO

### ISSUE THREAD

**Issue by sasmaster** [ocornut/imgui#1108]
Hi.I am using IMGUI to debug stuff in OpenGL ES2.0 bases app.Now,I started using VAO objects.I assume that IMGUI doesn't draw using VAOs for GLES.In my case,I try to optimize redundant calls to the driver by not unbinding the last drawn VAO,because it will be replaced by the next VAO anyway.When I do this,in the second frame some meshes get blown apart and all that sort of screwed geometry artifacts...If I do unbind the last VAO in my app,then all is good.Now,obviously I wouldn't want to keep that logic inside the renderer only to fit the cases when MGUI is used.
Thanks.

**Comment by ocornut** [comment]
The question doesn't really pertain to Dear ImGui itself, so the subject line is misleading. As described it is a rendering problem on your side, that afaik isn't exhibited by any of the example application.

There is most likely a problem with your code or usage of OpenGL (OpenGL because totally obscure and confusing doesn't help :).

**Comment by ratchetfreak** [comment]
at the start of callback to render the ImGui geometry, bind a VAO that you created specifically for ImGui to use during init.

**Comment by sasmaster** [comment]
You're 100% correct.I have checked and see the problem is on my side,The last time we implemented our rendering logic for IMGUI it didn't include VAOs.Sorry for bothering ))

**Comment by ocornut** [comment]
No worry, glad it is fixed!
