### ISSUE TITLE
Popup with rounded corners?

### ISSUE THREAD

**Issue by hamoid** [ocornut/imgui#1112]
Popups get closed when clicking outside them, and modals have rounded corners. Is there a way to get both features? Click outside to close, and rounded corners?

**Comment by ocornut** [comment]
Sorry, it is currently hardcoded that BeginPopup() pushes a zero rounding. We could add another variable in the Style structure, but I was hoping to reduce the complexity of styling data whenever possible, because everything we add, we generally cannot remove. It is something that matters so much to you? How does your style looks like?

**Comment by hamoid** [comment]
No worries. I will manage by using normal windows, in which I can get rounded corners. I'll post a screenshot soon when our app is ready :)

**Comment by ocornut** [comment]
@hamoid: This is now supported via the `style.PopupRounding` setting!
