### ISSUE TITLE
Padding on last column

### ISSUE THREAD

**Issue by itamago** [ocornut/imgui#1138]
Hello,
When drawing columns, I see there is some padding on the last column (please take a look a the screenshot).
I obviously searched in the closed issues, but didn't find my answer.
I don't remember why, and I don't remember how to retrieve the remaining space...
Could someone please explain again ?
Thanks.
<img width="480" alt="screen shot 2017-05-08 at 14 31 31" src="https://cloud.githubusercontent.com/assets/16628136/25804616/dc3cdb2e-33fc-11e7-9a1b-8e50f1916b42.png">

**Comment by ocornut** [comment]
This is because the code has some subtle issues with dynamically toggling the scrollbar on and off, so I always kept that space available in case the scrollbar would appear and it fixed a few things.

If you never need a scrollbar, you can pass the `ImGuiWindowFlags_NoScrollbar` flag to your child window and it'll fix that issue.

Otherwise we still need to find that resizing to be done properly as part of the Columns API rewrite (#125) sometimes in the future :)

**Comment by itamago** [comment]
Thanks, now I remember !
It works like a charm :)
