### ISSUE TITLE
Including stb_truetype

### ISSUE THREAD

**Issue by xythobuz** [ocornut/imgui#114]
I'm already using stb_rect_pack and stb_truetype elsewhere in my project, and I'd like to only include each once in my project.

What do you think of adding an option to imconfig.h to set an alternative include path for the stb headers, like this:

    // imconfig.h
    #define IMGUI_STB_TRUETYPE "stb/stb_truetype.h"
    
    // imgui.cpp
    #ifdef IMGUI_STB_TRUETYPE
    #include IMGUI_STB_TRUETYPE
    #else
    //  ...
    #endif

**Comment by ocornut** [comment]
We could (and should) but that the moment the version of stb_truetype.h I am using is modified from the original one. So that would have to wait until stb_truetype.h hopefully.include my modifications

**Comment by ocornut** [comment]
I have modified stb_truetype to be static so it shouldn't conflict with yours
https://github.com/ocornut/imgui/commit/f1ccd32cb1549736aef7433c9ea5f39adc3e650a

And added define to disable the implementation as well (but that wouldn't work right now because my stb_truetype is modified from the original)

Both changes were submitted as PR to the origin

**Comment by ocornut** [comment]
Btw the optional define are:

// Optionally put stb stuff in their own namespace
#define IMGUI_STB_NAMESPACE     ImStb

// Disable implementations
#define IMGUI_DISABLE_STB_RECT_PACK_IMPLEMENTATION
#define IMGUI_DISABLE_STB_TRUETYPE_IMPLEMENTATION

It doesn't do exactly your suggestion but I assume it should be ok. Closing this for now.
