### ISSUE TITLE
MenuItem doesn't open popUp

### ISSUE THREAD

**Issue by q-depot** [ocornut/imgui#1143]
Hi,

The MenuItem doesn't seem to open a pop up, I'm trying to open a PopUpModal, but I noticed the same issue with the stacked PopUp.
I tried to replicate the issue with the stacked pop up example in the demo window (imgui_demo.cpp #1203), if you replace the button with a menu item, the stacked popup doesn't open anymore.

**Comment by ocornut** [comment]
There's an unsolved issue/confusion, see #331 for details.
(Which incidentally shows up when you search for "menuitem popup" https://github.com/ocornut/imgui/search?q=menuitem+popup&type=Issues&utf8=%E2%9C%93 )

> if you replace the button with a menu item, the stacked popup doesn't open anymore.

This is due to the fact that the button doesn't close the current popup. It would however cause similar issues in other configuration.

Closing this as duplicate. I'm keeping a watching on #331 and would like to find an elegant answer to it eventually.

**Comment by q-depot** [comment]
sorry about the duplicate :]
