### ISSUE TITLE
SliderFloat with steps

### ISSUE THREAD

**Issue by itamago** [ocornut/imgui#1183]
Hello,
I was convinced that SliderFloat supported "steps" (or "ticks"), but I cannot find this implementation..
So, starting from the current StepFloat implementation, I have this one which partially match the needs:

```
bool ImGui::SliderFloatWithSteps(const char* label, float* v, float v_min, float v_max, float v_step, const char* display_format)	
{
	if (!display_format)
		display_format = "%.3f";

	float v_f = *v;
	char value_buf[64] = {};
	const char* value_buf_end = value_buf + ImFormatString(value_buf, IM_ARRAYSIZE(value_buf), display_format, *v);

	bool value_changed = SliderFloat(label, &v_f, v_min, v_max, value_buf, 1.0f);
	float remain = fmodf((v_f-v_min), v_step);
	*v = (v_f - remain);
	return value_changed;
}
```
For instance, with if you want to have a slider allowing values from 0.5 to 20.5 with a step of 10.0, you would allow the 3 following step-values : 0.5, 10.5, 20.5.

The intermediate ImFormatString is required to avoid drawing the intermediate numbers while the slider is being dragged.

This implementation works fine, except one thing : the "grab bar" doesn't have the good width..
With the previous example (0.5 to 20.5 with a step of 10.0), allowing 3 step-values, we would expect the `grab_sz` of `ImGui::SliderBehavior` to be a third of the total size. That's obviously not the case here.
So, I need to modify `ImGui::SliderBehavior` too, in order to compute the `grab_sz` according to the number of allowed step-values.

I'm ending with 2 forked functions... Do you know a better way to obtain a slider with steps ?
Thanks for your help.

**Comment by itamago** [comment]
Ok, I could fake the steps by using a SliderInt behind, and recomputing the float values in the end..

**Comment by ocornut** [comment]
Hi Pacome,

I don't have a real answer yet, but throwing some thoughts out:
As you understand the problem isn't really about making the 2 changes but passing down the parameters and what to do with those API. So I don't have an immediate answer but I agree the feature would be useful.

We could move those concepts lower-down as you did. We'd have to break the signature of SliderBehavior() (which was to be expected at some point), perhaps refactor it.

We should massage SliderFloat()+SliderBehavior() some more, in particular to make the frontend SliderFloat() much simpler to "allow" copying it. The Tabbing/CTRL-Clicking part of it probably needs to be extracted into a helper. 

Short-term, instead of modifying those 2 functions you may want to _copy_ them both into your code with new names?

(As a side node I assume that feature would be incompatible or confusing when using power != 1.0f.?)

**Comment by ocornut** [comment]
> Ok, I could fake the steps by using a SliderInt behind, and recomputing the float values in the end..

Oh yes, you can do that if you override the label to include your own displayed value indeed.

We should still aim to massage those functions. Among other things support for types other than float will be desirable later - not the same feature, but another reason so have a big pass at those functions.

**Comment by itamago** [comment]
Here is the code by using SliderInt : 
```
bool ImGui::SliderFloatWithSteps(const char* label, float* v, float v_min, float v_max, float v_step, const char* display_format)
{
	if (!display_format)
		display_format = "%.3f";

	char text_buf[64] = {};
	ImFormatString(text_buf, IM_ARRAYSIZE(text_buf), display_format, *v);

	// Map from [v_min,v_max] to [0,N]
	const int countValues = int((v_max-v_min)/v_step);
	int v_i = int((*v - v_min)/v_step);
	const bool value_changed = SliderInt(label, &v_i, 0, countValues, text_buf);

	// Remap from [0,N] to [v_min,v_max]
	*v = v_min + float(v_i) * v_step;
	return value_changed;
}
```

The only thing I needed to modify in the existing API is to add a `default_precision` parameter to SliderFloat (used by SliderInt) : 
```
SliderFloat(const char* label, float* v, float v_min, float v_max, const char* display_format = "%.3f", float power = 1.0f, int default_precision=3);
```
in order to forward the parameter to 
```
int decimal_precision = ParseFormatPrecision(display_format, default_precision);
```
because it was using `3` by default.

It works like a charm.
Thanks!

**Comment by ocornut** [comment]
Understood. I'll keep note of this thread for later rework of the slider internals.

**Comment by Reedbeta** [comment]
Apologies for bringing up this old thread, but I also just ran into a case where I would like a stepped float slider. itamago's solution using an int slider with a custom label text is interesting, but if I'm not mistaken this doesn't handle the case where you ctrl+click to turn the slider into a textbox, right? (It would still show the underlying integer value in the text box.)

I think a useful and backward-compatible way to handle this would be to extend the sliders with an optional callback which would allow to modify/constrain the slider value while dragging, much like ImGuiSizeCallback does for window sizing.

**Comment by ocornut** [comment]
>  but if I'm not mistaken this doesn't handle the case where you ctrl+click to turn the slider into a textbox, right? (It would still show the underlying integer value in the text box.)

That's correct.

My current stance is that instead of promoting a single does-everything API, I would rather like to work toward facilitating the creation of custom widgets and custom API. We're never going to be able to fit every possible slider types in a single sane API and I feel it's been constraining us more than anything. We should actually be starting a few experiments about it this month.

That's to say, I don't have a good answer right now. Some thoughts:

Considering the call flow:
`SliderFloat()` -> `SliderScalar()` -> `SliderBehavior()` -> `SliderBehaviorT<>()`

I would be ok adding the feature in lowest-level private API `SliderBehavior()` and `SliderBehaviorT<>`, which mean that if you made a copy of SliderScalar (currently ~75 lines) into your own code you can access it. That's not ideal but will work.

Note that I don't even know how would the interaction look like when CTRL+Click: we're not going to swap numbers under the text edit cursor as they are input, so the Step would be applied on the actual value and differ from input value until pressing Enter (which coincidentally relates to the fact that a NoLiveEdit flag described in the other thread would be perfect here!). Adding a flag to disable the CTRL+Click is also possible.

The spirit of "few experiments" described above would be try closely mimicking variety of sliders types, e.g. modeled after known UI frameworks, and then redesigning internals with helpers so that entry point expressing the unique properties of a slider can become a ~20 lines function to copy and tweak into of a ~75 lines function.

(Linking to #1815)

**Comment by Jonathhhan** [comment]
Here my hack for a step slider. Should work for floats, too:
```
		static int i1 = 3;
		int sliderStep = 128;
		std::string s1 = std::to_string(i1 * sliderStep + sliderStep);
		ImGui::SliderInt("Width", &i1, 0, 7, s1.c_str());
		width = i1 * sliderStep + sliderStep;
```

**Comment by EthanRutherford** [comment]
I know this is an old issue, but I came here looking for a step size arg as well, and came up with my own simple workaround:
```
void Slider(const char* label, float* value, float min, float max, float step = 0.0f) {
	float innerValue = *value;
	ImGui::SliderFloat(label, &innerValue, min, max);
	if (innerValue != *value) {
		if (step > 0.0f) {
			innerValue = std::round(innerValue / step) * step;
		}

		*value = innerValue;
	}
}
```
