### ISSUE TITLE
Rendering issues (Opengl3, Windows 7, mingw 4.7, IntelHD GPU)

### ISSUE THREAD

**Issue by stawrocek** [ocornut/imgui#1189]
Hi!
I am trying imgui examples (sdl2+opengl3 && glfw3 + opengl3) and both of them have "glitches"
(sdl2+opengl2 works fine for me).
I use imgui 1.5, most recent release
[example 1](http://imgur.com/a/GV6XG)
[example 2](http://imgur.com/a/m8pzM)
I have changed examples a bit (I use glew instead of gl3w), 
[here is zip with code I used](https://github.com/ocornut/imgui/files/1082561/imgui_loaders.zip)

This blinking rendering bugs occurs when imgui's windows are overlaping or when I move mouse over "clear color" area.

I also had to add
```
if(g.IO.DeltaTime <= 0.0f)
        g.IO.DeltaTime = 1.0/60.0f;
IM_ASSERT(g.IO.DeltaTime >= 0.0f);
```
to imgui.cpp beceause of io.DeltaTime assertion gets firing (which is strange)
Is there a way to limit Imgui fps to maximally 60? Beceause such a "patch" seems stupid

**Comment by stawrocek** [comment]
I've tried adding sampler [restoring](https://github.com/ocornut/imgui/pull/1145/commits/ad3c1e68ab8dcb44a6f5602fd9f5e149323b7398) but it didn't helped at all

**Comment by ocornut** [comment]
Hello @stawrocek,

Please use two threads for two different questions in the future. Also please use the github attachment systems instead of imgur, because imgur uploads will be available in the future and so questions are not being as useful to future readers.

A) Rendering issues.

Could you check if the precompiled binaries works for you?
http://www.miracleworld.net/imgui/binaries/imgui-demo-binaries-20161113.zip
You may also try older versions of the binaries, would be good to confirm if they exhibit the same bug or not.
http://www.miracleworld.net/imgui/binaries/

Also see https://github.com/ocornut/imgui/issues/1172 for a similar mystery issue.

B) 
> to imgui.cpp beceause of io.DeltaTime assertion gets firing (which is strange)
> Is there a way to limit Imgui fps to maximally 60? Beceause such a "patch" seems stupid

Dear imgui doesn't control your application loop, it's up to your application if you want to limit FPS to 60. Note that setting `io.DeltaTime` won't change your application FPS, it will merely change imgui owns perception of time (as time calculate are need for things such as double-click, blinking cursors, keyboard repeat rate, etc.).

The assert is here for a reason. Passing a negative value is incorrect. I think this is the same issue as discussed here: (still unclosed) 
https://github.com/ocornut/imgui/issues/996

**Comment by stawrocek** [comment]
Ok, I' ve checked the binaries:
imgui-demo-binaries-20150321.zip 	2015-03-22 01:02 	391K	 works fine
imgui-demo-binaries-20150531.zip 	2015-05-31 15:48 	432K	 works fine
imgui-demo-binaries-20150708.zip 	2015-07-08 21:20 	455K	 works fine
imgui-demo-binaries-20150716.zip 	2015-07-17 04:59 	475K	 works fine
imgui-demo-binaries-20150909.zip 	2015-09-09 15:24 	504K	 opengl3 demo doesn't work
imgui-demo-binaries-20151226.zip 	2015-12-26 09:59 	515K	 opengl3 demo doesn't work
imgui-demo-binaries-20160410.zip 	2016-04-18 16:31 	534K	 opengl3 demo doesn't work
imgui-demo-binaries-20161113.zip 2016-11-13 21:39 	588K	 opengl3 demo doesn't work (rest is ok)

So it looks like bug happened between 2015-07-17 04:59 and 2015-09-09 15:24

**Comment by stawrocek** [comment]
I've checked it on another computer and it works fine on it :<
It fails (4 newest builds, previous post) on HP laptop with Windows7, Intel HD 4600 GPU
It works fine on Windows7 PC with NVidia GeForce 8600 GT GPU

**Comment by dpethes** [comment]
Can you try different drivers? I'm on HD4600 + Windows 10 and I don't have this problem.

**Comment by stawrocek** [comment]
Thanks! @dpethes 
I've updated my drivers and now it works!
