### ISSUE TITLE
Revert & Save buttons for colors get clipped out in ShowStyleEditor demo

### ISSUE THREAD

**Issue by geneotech** [ocornut/imgui#1211]
I'm running imgui_examples_msvc2010:

![2017-07-03_17-00-32](https://user-images.githubusercontent.com/3588717/27798353-38777ff8-6011-11e7-8c95-af1796820d57.gif)

Revert button gets clipped, and it is completely impossible to save some of the options when the ref argument is non-null. Resizing the window does not help.

Perhaps a good idea would be to decrease widths of the R, G, B, A value bars?

**Comment by ocornut** [comment]
Yeah it's a bit crappy. In a real application I would use icons and put them before the label, fixed size, greyed out or hidden when unavailable, but imgui doesn't rely on icons-font at the moment.

I'll put that on hold for now because I may revamp the styling system.

**Comment by ocornut** [comment]
@geneotech : I made some improvements to the style editor and among other things this is now fixed.

I also added a comment in that code explaining how in this case I would suggest use Icons from an icon font (but we can't in the demo code because we don't have guarantee of which fonts are loaded), so hopefully.
