### ISSUE TITLE
Multiline text input scrollbar query & horizontal scrollbar

### ISSUE THREAD

**Issue by paladin-t** [ocornut/imgui#1224]
Hi,

I've got two requirements, execuse me if I'm asking silly questions.

1. I need to get the scroll bar value of a multiline text input widget. I'm able to get it by adding `ImGui::GetScrollY()` in `ImGui::InputTextEx`, it works, but I'm just wondering, is there any no-hacking way to do it?
2. To use a horizontal scroll bar when some line(s) on a multiline text input widget is too long to present? Is there any way to add it?

TIA. And this is an extraordinary lib.

**Comment by ocornut** [comment]
1. Why do you need it, what are you trying to do? Knowing always help.

**Comment by paladin-t** [comment]
1. Because I'd like to scroll something else synchronized with it.

**Comment by ocornut** [comment]
I'm not in front of my pc but you can BeginChild() into the same window created by InputTextMultiline() to query its scrolling value, which would get you the same result without modifying imgui.cpp

So something like `if(IsItemActive()) { BeginChild, GetScrollY(), EndChild() }`

**Comment by paladin-t** [comment]
Thanks! I'll try it and let you know the result.

**Comment by paladin-t** [comment]
It adds a inspectable scroll bar, but encapsulating an input widget with a dummy child only responds to mouse wheel scrolling when you hover it right above the child's scroll bar. Can I scroll a child when hover on a child's child?

**Comment by ocornut** [comment]
> It adds a inspectable scroll bar, but encapsulating an input widget with a dummy child only responds to mouse wheel scrolling when you hover it right above the child's scroll bar. Can I scroll a child when hover on a child's child?

I don't quite understand that last paragraph you posted, neither I know if it relate to 1) or 2).

Answer to the second part:

> 2) To use a horizontal scroll bar when some line(s) on a multiline text input widget is too long to present? Is there any way to add it?

Unfortunately it is a little tricky at the moment.
Note that we already support horizontal scrolling as you move the cursor BUT we don't have an horizontal scrollbar. This is filed as a bug/todo in #383, so if you are happy with 1) I will close this issue because #383 is still open.

Basically a scrollbar needs to know the text width, and we do not calculate it at all. This is to make things faster for large amount of text, and because we don't yet keep things up to date in a stateful iterative manner (lots of things are recalculated for the active InputTextMultiline widget).

If you change
`if (!BeginChildFrame(id, frame_bb.GetSize()))`
to
`if (!BeginChildFrame(id, frame_bb.GetSize(), ImGuiWindowFlags_AlwaysHorizontalScrollbar))`
You will see by yourself that the scrollbar thinks that the text size is the width of the widget.

We calculate the text height only in a loop above and store it in this block:
```
// Store text height (note that we haven't calculated text width at all, see GitHub issues #383, #1224)
if (is_multiline)
     text_size = ImVec2(size.x, line_count * g.FontSize);
```
(size.x == widget size, not text size)

The code above this loop is rather tricky and un-obvious to understand because it was written to support large amount of text in a stateless way and this is why I ignored text width. 

I would like to eventually rewrite InputText() and fixing this issue by maintaining more internal state will be among of desirable changes. Unfortunately it is a rather large amount of work and I don't have an ETA for it yet.

Forcing the code to calculate text width is possible, I just wrote a simple patch below (note that there's two different paths depending if the text is active or not). Unfortunately this make InputTextMultiline() too slow to casually handle 10k-lines files so I can't push it at the moment.

inputtext_multiline_calc_width.diff
```
diff --git a/imgui.cpp b/imgui.cpp
index e3c6f1a..baa116f 100644
--- a/imgui.cpp
+++ b/imgui.cpp
@@ -7704,7 +7704,7 @@ bool ImGui::InputTextEx(const char* label, char* buf, int buf_size, const ImVec2
     ImGuiWindow* draw_window = window;
     if (is_multiline)
     {
-        if (!BeginChildFrame(id, frame_bb.GetSize()))
+        if (!BeginChildFrame(id, frame_bb.GetSize(), ImGuiWindowFlags_HorizontalScrollbar))
         {
             EndChildFrame();
             EndGroup();
@@ -8133,7 +8133,7 @@ bool ImGui::InputTextEx(const char* label, char* buf, int buf_size, const ImVec2
 
             // Store text height (note that we haven't calculated text width at all, see GitHub issues #383, #1224)
             if (is_multiline)
-                text_size = ImVec2(size.x, line_count * g.FontSize);
+                text_size = InputTextCalcTextSizeW(edit_state.Text.Data, edit_state.Text.Data + edit_state.CurLenW);
         }
 
         // Scroll
@@ -8221,7 +8221,10 @@ bool ImGui::InputTextEx(const char* label, char* buf, int buf_size, const ImVec2
         // Render text only
         const char* buf_end = NULL;
         if (is_multiline)
-            text_size = ImVec2(size.x, InputTextCalcTextLenAndLineCount(buf_display, &buf_end) * g.FontSize); // We don't need width
+        {
+            buf_end = buf_display + strlen(buf_display);
+            text_size = g.Font->CalcTextSizeA(g.FontSize, FLT_MAX, 0.0f, buf_display, buf_end);
+        }
         draw_window->DrawList->AddText(g.Font, g.FontSize, render_pos, GetColorU32(ImGuiCol_Text), buf_display, buf_end, 0.0f, is_multiline ? NULL : &clip_rect);
     }
 
```

**Comment by paladin-t** [comment]
Alright, that's cool, I'll follow #383. Thanks again.

**Comment by hdclark** [comment]
@ocornut Can you please elaborate how your suggestion to use `if(IsItemActive()) { BeginChild, GetScrollY(), EndChild() }` works? I can't figure out how to get IDs to match.

    const auto id = ImGui::GetID("xyz");
    ImGui::PushID(id);
    ImGui::InputTextMultiline("xyz", buf, 1000);
    ImGui::PopID();
    
    ImGui::BeginChild(id);     // <------ Creates a new window
    auto vert_scroll = ImGui::GetScrollY();
    ImGui::EndChild();

I've tried using '###'-preceded labels but it also doesn't seem to work. The Dear ImGui Metrics show two separate windows:

    Window '075F5441'
    Window 'xyz_075F5441'

What am I doing wrong here?

**Comment by hdclark** [comment]
@ocornut Any comment?

`BeginChild(id)` does not work because it seems to prepend an underscore. `Begin(str)` does seem to work when `str` contains the full ID stock, including the ID at the end (e.g., `"Script Editor/#script_editor_active_content_9CF9E0D1"`), but this is a kludge and the ID-to-str function is not accessible in the public interface.

I don't think the `if(IsItemActive()) { BeginChild, GetScrollY(), EndChild() }` is possible by pushing/popping IDs. Do you know if there are any examples using this idiom?
