### ISSUE TITLE
Memory leak within the test windows

### ISSUE THREAD

**Issue by pnunes** [ocornut/imgui#1240]
We've found a memory leak when making use of the test windows (by disabling #define IMGUI_DISABLE_TEST_WINDOWS).

If you try one of the following demo features from the menu, you should be able to trigger it:
- Console
- Log
- Long text display

Thanks for the work on imgui, it's being incredibly useful!

**Comment by ocornut** [comment]
The demo code and those sections you noted in particular use buffers referenced locally as static variables for convenience and to make the demo code shorter.  They aren't really leaks, it's just memory that those features are using (the console and log are evidently storing text...). The static variables would be destroyed upon exiting main() anyway.

Also: please do not define IMGUI_DISABLE_TEST_WINDOWS during development, it's harmful since essentially you are removing the documentation from your users/programmers.

**Comment by pnunes** [comment]
Gotcha.

We won't be defining IMGUI_DISABLE_TEST_WINDOWS during development, as you say the debug windows are very useful.

Thanks for the lightning fast reply.
