### ISSUE TITLE
PVS Studio analyst errors

### ISSUE THREAD

**Issue by drillsar** [ocornut/imgui#1243]
Here is the following from PVS Studio:

V630 The '_alloca' function is used to allocate memory for an array of objects which are classes containing constructors. imgui_draw.cpp 438
V630 The '_alloca' function is used to allocate memory for an array of objects which are classes containing constructors. imgui_draw.cpp 619
V557 Array underrun is possible. The value of 'i - 1' index could reach -1. imgui_demo.cpp 431
V557 Array overrun is possible. The value of 'i + 1' index could reach 16. imgui_demo.cpp 432
V557 Array underrun is possible. The value of 'i - 4' index could reach -4. imgui_demo.cpp 433
V557 Array overrun is possible. The value of 'i + 4' index could reach 19. imgui_demo.cpp 434
V575 The potential null pointer is passed into 'memcpy' function. Inspect the first argument. imgui_demo.cpp 1963

**Comment by ocornut** [comment]
Thanks for the report. I went through them and it looks like none of them requires a change/action.

> V630 The '_alloca' function is used to allocate memory for an array of objects which are classes containing constructors. imgui_draw.cpp 438
> V630 The '_alloca' function is used to allocate memory for an array of objects which are classes containing constructors. imgui_draw.cpp 619

We don't need the constructor for ImVec2, it's better that it's not constructed in that case since we are overwriting them anyway.

> V557 Array underrun is possible. The value of 'i - 1' index could reach -1. imgui_demo.cpp 431
> V557 Array overrun is possible. The value of 'i + 1' index could reach 16. imgui_demo.cpp 432
> V557 Array underrun is possible. The value of 'i - 4' index could reach -4. imgui_demo.cpp 433
> V557 Array overrun is possible. The value of 'i + 4' index could reach 19. imgui_demo.cpp 434

Those are false positives, the code is:
```
for (int i = 0; i < 16; i++)
{
  [...]
  int x = i % 4, y = i / 4;
  if (x > 0) selected[i - 1] ^= 1;
  if (x < 3) selected[i + 1] ^= 1;
  if (y > 0) selected[i - 4] ^= 1;
  if (y < 3) selected[i + 4] ^= 1;
}
```

> V575 The potential null pointer is passed into 'memcpy' function. Inspect the first argument. imgui_demo.cpp 1963

`static char* Strdup(const char *str) { size_t len = strlen(str) + 1; void* buff = malloc(len); return (char*)memcpy(buff, (const void*)str, len); }`

This is the best place to crash in case of allocation failure. We wouldn't have a proper fallback higher up in the stack. If ImGui can't allocate a a buffer for window name then we can crash or exit or exception which are pretty much equivalents in the usage context (except exception are no-no for various reason).
Also, this is demo code, so the least of our concerns.
