### ISSUE TITLE
Threat detected in imgui-demo-binaries-20161113.zip

### ISSUE THREAD

**Issue by liorda** [ocornut/imgui#1246]
Hi,

We're using Cisco AMP, and it detected a potential threat from http://www.miracleworld.net/imgui/binaries/imgui-demo-binaries-20161113.zip (the link in the main readme.md right now)

The threat name is "w32.dfb4799b30-100.sbx.vioc". The page at https://www.talosintelligence.com/amp-naming gives no useful information.

I downloaded this zip in the past, and it didn't detect any threats then. Was that file changed? I think it's better to host a clean version of it in github so we'll be able to know when it changes.

Thanks.

**Comment by ocornut** [comment]
The files haven't changed since uploaded. I just downloaded and compared with my local copy.
The .exe were compressed with UPX to save on ZIP file (I was using an old 2010 version back then). Lazy anti-viruses software are likely get confused by UPX executables.

We can't include executable on the git repository because they are too big and would be included with everyone's checkout. The binaries are merely for quick reference but it is expected that people can compile the example applications.

This package doesn't use UPX:
[imgui-demo-binaries-20170723-noncompressed.zip](https://github.com/ocornut/imgui/files/1167951/imgui-demo-binaries-20170723-noncompressed.zip)

This package uses exe compressed by a 2013 version of UPX:
[imgui-demo-binaries-20170723-upx2013.zip](https://github.com/ocornut/imgui/files/1167953/imgui-demo-binaries-20170723-upx2013.zip)

Do you get any alert there?

**Comment by liorda** [comment]
Neither triggered it - Tested download and execution of all exe's. I guess you're right and Cisco AMP is just lazy, or has bad experience with UPX 2010. We use Windows Defender as well, and it's ok with them as well (yes I know, double protection :-))

BTW, I just compressed the uncompressed binaries with 7zip, and the resulted files size is 394KB. I think 7-zip is pretty ubiquitous, and can serve you well if bandwidth is a main concern.

Thanks.

**Comment by liorda** [comment]
And regarding hosting the package on github, IMO 400KB is very reasonable and allowed.

**Comment by ocornut** [comment]
I will reupload a new package (right now I can't seem to connect to my webhost, presumably because I am travelling and it is freaking out that I am connecting from Hong Kong?!)

>  I think 7-zip is pretty ubiquitous

Since those binaries are provided for quick evaluation/convenience, any barrier to access is undesirable. Afaik OS don't support 7-zip by default.

> And regarding hosting the package on github, IMO 400KB is very reasonable and allowed.

The problem is not github but end-users having to download and store every version of every executables in their local git clone.

**Comment by liorda** [comment]
Thanks for your help!

**Comment by ocornut** [comment]
Updated README with new binaries, including Vulkan binaries as well.
https://github.com/ocornut/imgui/commit/6e04cedd5f972ae00a5a6c8719eec5e4015849e8
