### ISSUE TITLE
Why does the SDL example handle keyboard and mouse input so differently?

### ISSUE THREAD

**Issue by pdJeeves** [ocornut/imgui#1263]
I don't understand why the keyboard state is stored directly in the ImGuiIO structure, but the mouse state is in a copy until the custom newframe was called, why isn't it both one way or both the other way?  I'm also pretty unsure about why '(mouseMask & SDL_BUTTON(SDL_BUTTON_LEFT))' is used for the mouse input, but the keyboard isn't similarly queried.

**Comment by ocornut** [comment]
The value stored in g_MousePressed[] isn't the mouse state but the record of a _button pressed_ event. It is a little workaround to reduce missing clicks if the pressing duration is shorter than an imgui frame, as imgui currently reads levels and not events.

See the comment:

`// If a mouse press event came, always pass it as "mouse held this frame", so we don't miss click-release events that are shorter than 1 frame.`

The same problem affects keyboard _keys_ (not _characters_) and in theory we should do the same as you suggested, but in practice it is less important because of the kind of interaction we do with the keyboard. Note that keyboard _characters_ (= text) are stored using `io.AddInputCharacter` from the corresponding event, so no keys are missed when typing text.

I would eventually like to re-overhaul some of the internals to more thoroughly process timestamped mouse/keys events and be more friendly to low framerate, but it's not a trivial task and surprisingly it hasn't been a much noticed issue at all (even if in theory it's completely wrong, practically no one complained, the only complains are from people reading the code)

Hope it answers your question?

**Comment by pdJeeves** [comment]
yes but if g_MousePressed stores that the button was pressed, and '(mouseMask & SDL_BUTTON(SDL_BUTTON_LEFT))' is true, then the button must have been pressed in the past. Meaning that gMousePressed being false and '(mouseMask & SDL_BUTTON(SDL_BUTTON_LEFT))' being true should be impossible. 

Meaning that the mouse mask is essentially testing if the mouse is held down, and was pressed before this frame started.  But nothing in imgui seems to use for anything, right?

**Comment by ocornut** [comment]
> yes but if g_MousePressed stores that the button was pressed, and '(mouseMask & SDL_BUTTON(SDL_BUTTON_LEFT))' is true, then the button must have been pressed in the past. Meaning that gMousePressed being false and '(mouseMask & SDL_BUTTON(SDL_BUTTON_LEFT))' being true should be impossible.
> Meaning that the mouse mask is essentially testing if the mouse is held down, and was pressed before this frame started. But nothing in imgui seems to use for anything, right?
[...]
> Oh i see, the mouse mask is testing if the mouse was pressed 2 or more frames ago, and not released.

No, it is testing for case where the mouse buttons was pressed THEN released immediately between the previous frame and the current frame, aka the mouse buttons was held for a shorter time than the frame time.

**Comment by ocornut** [comment]
If we don't do that and your application runs at slow frame-rate, then it it would be possible to "miss" some fast mouse-clicks. That's the reason.

In fact, the idea of changing imgui IO format to take on proper events could technically be handled at application level as well, by queuing changes made to inputs and only submitting a limited amount per-frame. E.g. if both button press and release events were received, only forward the press, then wait until next frame to forward the release. That would be a neat workaround to generally support low framerate all across the board. But more reasonably the imgui IO should be revamped to not put that burden on the application.

Closing this now, I hope this answered your question?
