### ISSUE TITLE
First column is actually way wider than others

### ISSUE THREAD

**Issue by devsaider** [ocornut/imgui#1266]
```ImGui::Text("%d", ImGui::GetColumnIndex());
ImGui::Text("%f", ImGui::GetColumnWidth());
ImGui::Text("%f", ImGui::GetContentRegionAvailWidth());
ImGui::Text("%f", ImGui::GetContentRegionMax().x);
ImGui::Text("%f", ImGui::GetColumnOffset());
```

I've inserted this code to imgui_demo.cpp (line 1357). Result:
![nz8w6ek](https://user-images.githubusercontent.com/5224397/28994374-673e9370-79d5-11e7-9143-9f1925d68c9d.png)

First column always shows bigger ImGui::GetContentRegionAvailWidth(). Why and how to fix?

**Comment by ocornut** [comment]
I'm looking into it, the reason is that columns after the first one have a bit of space between the border, whereas the first column doesn't have it. It makes sense because we don't display the left border. In your case since you don't use borders it's even weirder to see it like that.

Adding this spacing for the first column would offset the text in your picture a little on the right which would be odd. There are different solutions (perhaps different depending on if a border is enabled or not) and I am not sure which one is right. Since columns are a bit of a mess it is possible that I may defer the fix until I have time to spend serious time on columns in general.

**Comment by ocornut** [comment]
OK that difference (which was worth `style.ItemSpacing.x`) is now fixed.

Note that:

- Because we currently need to pixel-align all sizes, some column may have still differing width by +/- pixel. E.g. with your test case after the fix I got 159, 160, 160.

- The column system currently always expect for the possibility of a Vertical Scrollbar (because it currently as issues transitioning when the scrollbar toggles), which make the last columns appears wider while that space is generally empty. If you never need a scrollbar you can use the `ImGuiWindowFlags_NoScrollbar` flag to claim that space back. If you use `ImGuiWindowFlags_AlwaysVerticalScrollbar` as well you won't notice that space because it will always be filled.
