### ISSUE TITLE
One MenuItem at a time

### ISSUE THREAD

**Issue by SandSt0rm** [ocornut/imgui#1274]
Hey,
I made a main menu for my window as follows:

if (ImGui::BeginMainMenuBar())
{
    if (ImGui::BeginMenu("Main"))
    {
        ImGui::MenuItem("Application Info", NULL, &showApplicationInfo);
        ImGui::EndMenu();
    }
    if (ImGui::BeginMenu("Camera"))
    {
        ImGui::MenuItem("Camera Info", NULL, &showActiveCameraInfo);
        ImGui::MenuItem("Load Camera Config", NULL, &loadCameraConfig);
        ImGui::MenuItem("Save Camera Config", NULL, &saveCameraConfig);
        ImGui::EndMenu();
    }
    ImGui::EndMainMenuBar();
}

the only issue is that i can pick more than one menu at a time, i would like that when I choose one menu item, the others will automatically shuts down, is there any way of doing this?

thanks

**Comment by ocornut** [comment]
> the only issue is that i can pick more than one menu at a time, i would like that when I choose one menu item, the others will automatically shuts down, is there any way of doing this?

I don't understand what you mean at all. 
What does "Pick more than one menu at a time" means?
What does "shutdown" in the context of a menu means?

**Comment by SandSt0rm** [comment]
for example:
1) i choose "Application Info" then an application window pops up
2) i choose "Camera Info", and the application info window still stays up
is there a way of preventing this of happening?
i mean, when i choose another option, the first one that i picked will close

**Comment by ocornut** [comment]
Then close it yourself.... those functions are just manipulating your bool variables. You can manipulate your bool variables however you want.

`MenuItem()` returns true when the item was clicked.
So you can either do `if (MenuItem("...", NULL, &mything) { if (mything) myotherthing = false; }`

Or if all those bool are exclusive, use an int/enum and the MenuItem overload that takes a `bool` parameter (instead of a `bool*`).
```
if (MenuItem("Feature 1", NULL, currentfeature==Feature1) { currentFeature=Feature1; }
if (MenuItem("Feature 2", NULL, currentfeature==Feature2) { currentFeature=Feature2; }
```

You can also pass the same `bool*` to your `Begin` calls for those windows and clicking the Close button of the window will set the bool to false.

I suggest studying the example code more in detail. Your question doesn't really pertain to imgui but is more of a general programming question, so you may get help on general programming forums as well.
