### ISSUE TITLE
Some thoughts about Push/PopXXX APIs.

### ISSUE THREAD

**Issue by zwcloud** [ocornut/imgui#1275]
Hi, @ocornut 
I'm reading your code. And I just realized that `Push/PopXXX` APIs are quite useful.

Here are some of my thoughts:
* Adding paramters to control functions will definitely bloat the parameter list as the development goes on. And it will also add many overloads for a single control. Instead, via `Push/PopXXX`, we push the parameters when needed, then access them in the control functions, which makes the control functions clean and simple. This also leads to more maintainable APIs and less API breaking changes.
* `Push/PopXXX` APIs keep styles or other states in a hierarchical system. And then, hierarchical styles or other states results in hierarchical appearance and behaviours of controls. At this point, `BeginXXX`/`EndXXX` APIs have the same advantages or features.

`SetNextXXX` functions are similar. But they just have conditional effect on the next control according to the `ImGuiSetCond` parameter.

The thoughts behind those APIs should be related to the principle of immediate mode GUI. I'm not sure if I have fully understood the purpose of Pop/PushXXX APIs. Did I miss something? I'd appreciate it if you can talk about the consideration and design target when you create them. I'm also curious about the furture improvement about them.

And, are there any articles or blogs about the implementation consideration, thoughts or details of _Dear ImGui_?

Thanks!

**Comment by ocornut** [comment]
Hello, most of what you wrote is correct. The Push/Pop API are generally related to generic state/settings that apply to multiple widgets, whereas the widget argument are more specific and unique to a single call.

I don't think either are directly related to the core principle of Immediate Mode GUI, they are more how I choose to design dear imgui and there are probably very different way to design an IMGUI library. There's no articles about how specifically I designed dear imgui but the homepage has links to various articles/video related to IMGUI concepts and many of the ideas were discussed or even formalized there. dear imgui is merely a very developed and easy to share implementation of those base ideas. My implementation was influenced by a much simpler implementation by Atman Binstock who worked at RAD and was likely exposed to the ideas of IMGUI from Casey Muratori.

A lot of the choices behind dear imgui were also made as I was using and needing the library to quickly make things, and because of that there are quite some inconsistencies in API and things that could be made or design better in there.

**Comment by zwcloud** [comment]
Thanks for your reply! That's clear enough. 🤝
