### ISSUE TITLE
sliderFloatN weird behaviour

### ISSUE THREAD

**Issue by elect86** [ocornut/imgui#1276]
Hard to screenshot, but you can reproduce it easily

Under the demo window, `Help -> Style Editor ->Settings`, try to drag very slowly one slider of the first parameter, `WindowPadding`

It will jump like forth and back continuosly in between values

**Comment by ocornut** [comment]
Those sliders are resizing/moving the whole interface so using makes them move on the screen, creating a feedback loop in some cases because sliders are updating the value when holding the mouse button.

I wouldn't really call that a bug, more like a funny side-effect of editing those specific values.
