### ISSUE TITLE
SameLine issue/bug

### ISSUE THREAD

**Issue by darkgnostic** [ocornut/imgui#1330]
If I have SameLine right after CollapsingHeader like:

    if (ImGui::CollapsingHeader("Header", ImGuiTreeNodeFlags_DefaultOpen )) {
	    ImGui::SameLine();if(ImGui::Button(UID(k,"Select"))) {}
    }

I will have button inside the header, on which I cannot click.

I don't know if this is intended behavior or not (possibility to place buttons inside the collapsing header).

**Comment by ocornut** [comment]
You cannot at the moment because the CollapsingHeader consume all the horizontal space.

What are you expecting to do? Where would you like the button to appear?

**Comment by darkgnostic** [comment]
It's not about expectation, that's a fact. I accidentally invoked behavior I reported.

Button **IS** rendered inside the header. I just asked if buttons placement like that is intended or not.

If it is not intended, then it is bug.

If it is intended, then again it is bug, as I can't click on button.

**Comment by darkgnostic** [comment]
[Here is an example](https://imgur.com/f5jyQCG)

**Comment by ocornut** [comment]
> If it is not intended, then it is bug.
> If it is intended, then again it is bug, as I can't click on button.

It's actually sort of intended and mimic the layout behavior of TreeNode().
When items are overlapping by default the first item receives the focus. You may call `SetItemAllowOverlap()` after `CollapsingHeader()` to allow the upcoming button to overlap so you can use this sort of pattern.

SetItemAllowOverlap isn't a default properly because it adds a latency of one-frame on detecting Hovering of a given widget, but I expect to expose this as a global flag for people who'd codebase who's prefer this behavior.

PS: Please use Github attachment system and not imgur for attachment, as they will delete them, making those threads less useful for future readers.

**Comment by darkgnostic** [comment]
Ok, if there is no needed change in the code, please close this issue.

**Comment by ocornut** [comment]
Cool,
I took note in the TODO list that auto-allow-overlap should be exposed as part of the upcoming flag stack. 
You can also pass `ImGuiTreeNodeFlags_AllowOverlapMode` directly to the `CollapsingHeader` function.
