### ISSUE TITLE
BeginChild() make its area loose the ability to move a window

### ISSUE THREAD

**Issue by djdeath** [ocornut/imgui#1337]
Hi,

I'm trying to layout a window so that there is a top part that doesn't scroll, and the bottom part is a list that can be scrolled : 
![screenshot from 2017-09-27 01-42-53](https://user-images.githubusercontent.com/434333/30890485-36ac2b2c-a325-11e7-9968-eac55301bf32.png)

This can be implemented by using BeginChild()/BeginChildFrame() for the scrolling part.
The slightly annoying problem with this is that previously the entire window would be reactive to click-and-drag (so you can move it by clicking anywhere), but now only the part outside of BeginChild/EndChild has that ability.

Is there a way around this?

Thanks!

**Comment by ocornut** [comment]
Looks like this commit broke it:
https://github.com/ocornut/imgui/commit/313d388bba42e0634a02b976dcdbae238d25eddc
It needs to be looked at.

(Btw I'm not sure why you are using `BeginChildFrame` and not `BeginChild` here, and your UI looks really hard to read).

**Comment by djdeath** [comment]
Thanks, indeed, BeginChild() looks much better.
I was just trying out all possibilities.

**Comment by ocornut** [comment]
Should be fixed now!
Note that you can use the `ImGuiWindowFlags_NoMove` flag on a child window to explicitly disable this if needed.

**Comment by djdeath** [comment]
Wow thanks you so much! All good now :+1:

**Comment by ocornut** [comment]
Please note that `BeginChildFrame()` now has been obsoleted in favor of using `BeginChild()` with the `ImGuiChildFlags_FrameStyle` flag. See commit cdbc21a.

I have currently made `ImGuiChildFlags_FrameStyle` automatically set the ImGuiWindowFlags_NoMove flag but since the API changed I may backtrack on this. However it seems more consistent for user experience to do it.

Those functions were merely PushStyle/PopStyle helpers and custom versions are easy to create.

(The removal isn't so much motivated by needing to add the feature in BeginChild(), but by the necessity to avoid `BeginChildFrame()` signature mismatching `BeginChild()` newer signature and features.)
