### ISSUE TITLE
How to check/uncheck Menu Items without closing a Menu

### ISSUE THREAD

**Issue by Flix01** [ocornut/imgui#1379]
I've quickly found an easy way to do it:
```c++
            // Just a test to check/uncheck multiple checkItems without closing the Menu (with the RMB)
            static bool booleanProps[3]={true,false,true};
            static const char* names[3]={"Boolean Test 1","Boolean Test 2","Boolean Test 3"};
            const bool isRightMouseButtonClicked = ImGui::IsMouseClicked(1);    // cached
            for (int i=0;i<3;i++)   {
                ImGui::MenuItem(names[i], NULL, &booleanProps[i]);
                if (isRightMouseButtonClicked && ImGui::IsItemHovered()) booleanProps[i]=!booleanProps[i];
            }
```
... just in case someone is interested...

@ocornut: you can close this issue at any time, since I've solved it.

**Comment by ocornut** [comment]
This is a rather commonly asked question, but I don't think I have answered it on the github.
As part as some refactor/merging from last month (where I have merged bits from the Nav branch), you can use this which is exposed in `imgui_internal.h`:

`ImGui::PushItemFlag(ImGuiItemFlags_SelectableDontClosePopup, true);`
`ImGui::PopItemFlag()`

I envision it will be moved to `imgui.h` at some point, perhaps with some renaming/tidying up of some of the available flags. e.g Here the naming `Selectable` may be confusing (MenuItem is a Selectable).

The reason it's not exposed directly by `MenuItem()` is because that API doesn't have room for flags at the moment. I think I could however add flags to `BeginMenu()` soonish, as menu-wide flags will be definitively used for other things. e.g.
`BeginMenu(const char* label, bool enabled = true, ImGuiMenuFlags flags = 0)`
w/ `ImGuiMenuFlags_MenuItemDontCloseMenu`

**Comment by ocornut** [comment]
It is now possible using public API:

```cpp
ImGui::PushItemFlag(ImGuiItemFlags_AutoClosePopups, false);
ImGui::MenuItem(....);
ImGui::PopItemFlags();
```
