### ISSUE TITLE
Changes for use in a console

### ISSUE THREAD

**Issue by Skylark13** [ocornut/imgui#140]
Hello,

I've been using imgui for a while and have recently implemented a console (based on the one in the example code, but with substring command completion, history, ...). I had to make a few small modifications to imgui, but before submitting them as a pull request I'd like to know if there's a better way to do what I wanted.

I needed a function to set the contents of the input text field. Here's what I came up with, after looking at the code of the ImGui::InputText() function:

    void ImGui::SetEditStateText(const char* text)
    {
        ImGuiState& g = GImGui;
        ImGuiTextEditState& edit_state = g.InputTextState;
        ImTextStrFromUtf8(edit_state.Text, IM_ARRAYSIZE(edit_state.Text), text, NULL);
        edit_state.ScrollX = 0.0f;
        stb_textedit_initialize_state(&edit_state.StbState, true);
        edit_state.StbState.cursor = (int)ImStrlenW(edit_state.Text);
        edit_state.CursorAnimReset();
        edit_state.LastCursorPos = ImVec2(-1.f, -1.f);
    }

As you can see, this sets the text and also sets the cursor location at the end of the line.

The second modification I made was to comment out the following lines in ImGui::InputText()

        //else if (IsKeyPressedMap(ImGuiKey_UpArrow))             edit_state.OnKeyboardPressed(STB_TEXTEDIT_K_UP | k_mask);
        //else if (IsKeyPressedMap(ImGuiKey_DownArrow))           edit_state.OnKeyboardPressed(STB_TEXTEDIT_K_DOWN | k_mask);

It's not clear from this code, but the result (with it uncommented) was that the up-arrow and down-arrow keys moved the cursor to the left and right, respectively (by calling into stb_textedit I think). I don't understand why we would need that since the left-arrow and right-arrow keys already do that. But in my case, when pressing up and down, I wanted to be able to invoke the history and completion functionality, respectively, and wanted the cursor to stay at the end of the line, so I removed it. Perhaps another way to go would have been to add a function that resets the cursor to a given position, or to the end of the line. That way I could have gotten the behaviour I wanted without modifying ImGui::InputText().

So, what is your opinion on those changes? When we agree on the way to go I'll prepare a pull request. Thanks in advance,

J-S

**Comment by ocornut** [comment]
Hello J-S,

Which version of ImGui are you basing your work on?

- The current example code for a console handle completion and history, so if you implemented them independently you may want to check what's being done already with callback.
- The second modification was applied quite a long time ago into ImGui.

If the InputText is being focused you should be able to modify its content via the callback. Otherwise whatever string you pass to InputText is the one displayed so they shouldn't be a need but such function. 

Your implementation of SetEditStateText() doesn't take account for multiple text edit inputs but it would work if called with if (ImGui::IsItemActive()) ImGui::SetEditStateText(...) after calling InputText().

**Comment by Skylark13** [comment]
Ah yes, thanks for pointing that out. I'm using ImGui that dates from 11 nov. 2014 so a bit old :-)

I'll get the latest and see if I can get it all done without any modifications now. Thanks!

**Comment by Skylark13** [comment]
Thanks, this way with callbacks is much cleaner. I should be able to do what I want this way. Thanks again for your work on this!
