### ISSUE TITLE
About Autoresize Windows Abnormal Show

### ISSUE THREAD

**Issue by Ghost-yc** [ocornut/imgui#1417]
```C++
if (bShaowDebugTestWnd)
	{
		ImGui::SetNextWindowSize(ImVec2(450.0f, 500.0f), ImGuiCond_FirstUseEver);
		if (ImGui::Begin("TestWnd", &bShaowDebugTestWnd, ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoCollapse))
		{
			ImGui::BeginChild("##TestDesc", ImVec2(0, 0), true, ImGuiWindowFlags_HorizontalScrollbar);
			ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(1.0, 1.0, 0.0, 1.0));
			ImGui::TextUnformatted("..........Test Text..........");
			ImGui::PopStyleColor();
			ImGui::EndChild();


			static float arrColor[4];
			ImGui::ColorEdit4("##Color", arrColor);

			ImGui::End();
		}
	}
```
When using the above code to create a window will display an exception，The window will be first along the length of the vertical side then horizontal length.(ImGui v1.52)

**Comment by Ghost-yc** [comment]
ImGui v1.52
![testwnd](https://user-images.githubusercontent.com/8528210/32473351-2d48c7c8-c3a2-11e7-81e5-4389fe593ff2.gif)

**Comment by ocornut** [comment]
This pattern doesn't work. Child windows are currently always explicitly sized.
Passing ImVec2(0,0) creates a child window to take all the available space:
`ImGui::BeginChild("##TestDesc", ImVec2(0, 0)`

Then this adds another bit of contents so it grows the space:
`ImGui::ColorEdit4("##Color", arrColor);`

You can see it at the bottom:
![image](https://user-images.githubusercontent.com/8225057/32486837-22e62e3c-c3a8-11e7-8d3a-f3b626a15a0c.png)

You currently either need to chose a size for the child window (e.g. host window height minus something) or disable the `ImGuiWindowFlags_AlwaysAutoResize` flag on the host window. In the future I would like to add bottom-to-left/right-to-left layout so you could submit your ColorEdit4 and then request the child to use the remaining space, but it's not possible without you doing the calculation at the moment.

_However_ there is one bug here that makes it grow on the X axis instead of just grow on the Y axis, introduced in c0547d358d746699f8d46a4996e49fdac8c55748. This is the code path that handle auto-sizing windows when the contents is bigger than the screen dimensions. I fixed it now so your window will only grow vertically.

Standalone repro code:
```
        ImGui::SetNextWindowSize(ImVec2(450.0f, 500.0f), ImGuiCond_FirstUseEver);
        if (ImGui::Begin("Test #1417", NULL, ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoCollapse))
        {
            ImGui::BeginChild("##TestDesc", ImVec2(0, 0), true);// , ImGuiWindowFlags_HorizontalScrollbar);
            ImGui::TextUnformatted("..........Test Text..........");
            ImGui::EndChild();

            static float arrColor[4];
            ImGui::ColorEdit4("##Color", arrColor);
        }
        ImGui::End();
```

**Comment by Ghost-yc** [comment]
Thanks
