### ISSUE TITLE
Drag'n drop support

### ISSUE THREAD

**Issue by damqui** [ocornut/imgui#143]
hi, I'm considering using ImGui (to convert ooold mfc game tool),
but one lacking thing is the support for drag'n'drop.
Is this feature planned ?
If no, I'll try to hack something in..

thanks for your work !

Ps: Side Question : concerning the uniqueness of Ids, err.. relying on a string crc32 seems weak to me. If I use ImGui for editing data, collisions might occur, and if so, I have no way of knowing if it happened.
Am I missing something ?

**Comment by ocornut** [comment]
1)
Do you mean drag and dropping of files into your application window?
That's OS dependant and not likely to be part of core imgui. On Windows you only need to call DragAcceptFiles() and implement the WM_DROPFILES message.

I suppose we can consider to add helpers for common known platforms (such as Windows) to help setting up drag'n drop if there was an easy way to do so. But ImGui doesn't know about concept of windows messages. So it'll probably be a little convoluted for what's essentially replacing 10 lines of code.

2)
If you are asking from the angle of "I may have two widgets with same string", the ID are built from a stack of strings that include the window, tree nodes, and which you can push into. So typically when creating repeated widgets in a loop you need to use PushID/PopID to manipulate the ID stack and make the sub-elements unique.

If you are asking from the angle of "what if even with the precaution above, CRC32 collision occurs ".
It's not strong if you are thinking of long-lived data or are thinking of cryptography. But in practice for the purpose of UI i don't think you'll ever see a problem. 
- Genuine collision are very unlikely in the first place.
- ID are used to store which widget is active and information about active widget. We are dealing with short-lived live data rather than persistent data, the collision would have to be among *two visible widgets*, which is a magnitude less likely. And then IF that ever happen, the problem with amount to "when I click button B it clicks button A instead", not very damaging.

In fact, if anything, CRC32 is too slow and we should try to replace it with a faster hash function.

**Comment by damqui** [comment]
1) No I mean dragging a widget into another widget, like during edition, for connecting things (putting a file from a file list widget into a file slot of struct widget)

2) " the ID are built from a stack of strings that include the window, tree nodes, and which you can push into". from the code, the stack of strings is actually a stack of 32 bits values used as the crc seed. I am not really familiar with that "32bit crc as a unique identifier", but the fact that in a editing context, a collision may occur at random without knowing it (except than keeping a list of generated ids for this frame, and testing for collisions at each new id generation), makes me feel it could - randomly - cause edition errors. If such a collision occurs, what happens ? the widget becomes unselectable ? (the first one with same id is selected instead ? in that case, we have a feedback, and that's okay)

**Comment by ocornut** [comment]
1) That's be interesting. Some ideas for a simple version:

- User pass some information to the draggable object. The information could as simple as a void* associated to a widget. However as a constraint it needs to be able to persist for an extra frame.

The draggable object can behave as a button, but when active it draws itself following the mouse cursor. That needs to be be done by pushing a fullscreen clipping rectangle. 

Along with setting g,ActiveId it can set g.DraggingId and g.DraggingData.

(Bonus: It also need to be in a front-most ImDrawList. There's no explicit mechanism for that yet. Things like Tooltip are implicitly high-up in the draw order. Need to improve on explicitly deciding of a sort order. But for a start you don't need that anyway because the parent window of the draggable object will front-most already as soon as you click it. That is, until we implement "hold dragged object on another window to bring it to top". )

- Drag target can be implemented with something like:

Pseudo-code
```
bool  IsDraggedInto(void** out_user_data)
{
if (IsItemHovered() && g.DraggingId && mouse_released)
{
   out_user_data = g.DraggingId; 
    return true;
}
return false;
}
```
 
- That needs to be organized with storage so it works regardess of the submission order of draggable object and drag object.

2) I don't think there will be a problem. The values in the stack are CRC32 themselves (CRC32 are often seeded this way). The widgets needs to be visible to meaningfully collide. Yes one will be unselectable or clicking on one will trigger the others. The detail may vary depending on the exact widget type. You can easily test by doing:

    ImGui::Button("hello");
    ImGui::Button("hello");

See what happens.
But I don't think you'll stumble on a accidental / random collision. The only collision you'll realistically fall into which be the typical "duplicate label" type of collision which can be solved using ##prefix in strings or PushID/PopID.

**Comment by ocornut** [comment]
About CRC32 collision:
http://stackoverflow.com/questions/14210298/probability-of-collision-crc32
  294 hash values : probability of collision 1 in 100000
I think it's a fair risk to take. You rarely have 300 widgets on screen. I haven't seen a collision happen yet. I've used CRC32 to identify data in games and collision happens rarely - we are talking dozens/hundreds of thousands of persistent, long-lived identifiers.

For persistent storage such as TreeNode open/close state and Column offsets they are stored per-window so won't collide accross windows, and could potentially be stored in separate maps per usage (e.g. tree nodes vs columns). This is all a non-problem really.

**Comment by damqui** [comment]
For drag'n drop : yes, it might be something as you propose. 
Drag'ndrop is really at the heart of some editors ( unity3d, unreal engine 4).
But, if not available, there is still a poor-man way of making "connections" whithout true drag'n drop, using copy-pasting.

For crc, okay, i'll try (though I don't like voodoo :) )

Thanks for your answers. 
When I have time, I'll try to convert the generic editor that uses our own data type information to imgui, to see if it is viable.

**Comment by ocornut** [comment]
FYI with IsItemActive() and GetMouseDragDelta() there's a few stuff that can already be done now.

I did a quick hacky test for someone who wanted to know if re-ordering was possible:

![imgui_dragging](https://cloud.githubusercontent.com/assets/8225057/7123149/efcdae54-e217-11e4-90cc-e26c0fb5889b.gif)

```
// User state
const int COUNT = 5;
static const char* items_data[COUNT] = { "Item One", "Item Two", "Item Three", "Item Four", "Item Five" };
static int items_list[COUNT] = { 0, 1, 2, 3, 4 };

// Render + dragging
for (int n = 0; n < COUNT; n++)
{
    int item_no = items_list[n];
    ImGui::Selectable(items_data[item_no]);

    if (ImGui::IsItemActive() && !ImGui::IsItemHovered())
    {
        float drag_dy = ImGui::GetMouseDragDelta(0).y;
        if (drag_dy < 0.0f && n > 0)
        {
            // Swap
            items_list[n] = items_list[n-1];
            items_list[n-1] = item_no;
            ImGui::ResetMouseDragDelta();
        }
        else if (drag_dy > 0.0f && n < COUNT-1)
        {
            items_list[n] = items_list[n+1];
            items_list[n+1] = item_no;
            ImGui::ResetMouseDragDelta();
        }
    }
}
```

That could be done in a nicer and more sturdy way within the core library eventually.

**Comment by Extrawurst** [comment]
these sort of things shouldn't be buried inside of tickets but be a listed in some kind of wiki

**Comment by ocornut** [comment]
Yes definitively, but it's still experimental here.
I really want to do a wiki with lots of demos. I wlll eventually.

**Comment by ocornut** [comment]
@Roflraging posted his own use of dragging to reorder widgets:
https://www.youtube.com/watch?v=pmx4fltxTKg
https://gist.github.com/Roflraging/f4af1d688237a7d367f9

In spite of the extra faff with the copying of his data structures, his approach of recording the index of the hovered fields is more robust and flexible. There's actually very little ImGui code too. I'll rewrite an example using this technique. 

I think the post-it could be moved to match the original widget position pretty easily. In one of my test (not published) I actually pushed a no-clipping-rectangle and redrawn the same widget following the mouse, which can also work.

**Comment by Extrawurst** [comment]
awesome. showing the widget at the mouse is a must-have for drag/drop imho

**Comment by Roflraging** [comment]
I noticed in the code I copied into the gist that one of the comments was wrong, sorry if anybody was confused!  https://gist.github.com/Roflraging/f4af1d688237a7d367f9#file-gistfile1-cpp-L93

**Comment by Extrawurst** [comment]
@ocornut did you rewrite that example that you mentioned ?

**Comment by ocornut** [comment]
Sorry I haven't got around to write an example for that (that's why I kept the issue opened for now)

**Comment by Extrawurst** [comment]
I just implemented drag and drop using that concept:
![2016-02-13 dragdrop](https://cloud.githubusercontent.com/assets/776816/13027390/12acf822-d24e-11e5-98d9-64f320d7971d.gif)

**Comment by ftsf** [comment]
I'm curious how do you do something on a "drop"?

**Comment by ocornut** [comment]
Right now you would have to track the dragging state, and then on mouse release test for item overlapping the mouse cursor. Something like `if (WasDragging && MouseRelease(0) && IsItemHovered())`

It could/should probably be wrapped into a helper function but we haven't got a standard way of storing the dragging state yet, so this is left to you to do the test above.

**Comment by paniq** [comment]
+1 for a working example similar to the GIF above, with perhaps a more complex drag object that demonstrates layouting as well?

**Comment by xaxxon** [comment]
Adding something more interesting to the examples would be nice.   Currently the only thing I can find is the "dragging" example under "keyboard/mouse/focus" which seems pretty buried.

**Comment by ocornut** [comment]
Will do eventually. Some recent links:

LumixEngine
https://twitter.com/mikulasflorek/status/740545248359813121
https://github.com/nem0/LumixEngine/blob/master/src/editor/asset_browser.cpp#L251

Paniq using his crazy language
https://twitter.com/paniq/status/741170371504799745
implementation https://gist.github.com/paniq/4bf7848fc33ccf24ec1c39a114897da1
usage https://gist.github.com/paniq/d120eba2cf757c71d3e9ba191fad2c60

**Comment by VinnyVicious** [comment]
@Extrawurst, are you going to share that snippet? Seems very useful for the imgui community!

**Comment by Extrawurst** [comment]
It is not a snippet, it's buried in NY engine but it was based on the gist above

**Comment by ocornut** [comment]
Everyone: I will maybe be able to look at drag'n drop in the upcoming weeks/months, or at least just enough to contemplate using a standard drag'n drop api for Tabs and Docking. Maybe the early versions of course feature won't use a standard drag'n drop api but ultimately this may be the ideal goal so I'll keep that in mind.

If anyone has feedback or request on drag'n drop features please voice them!
Also happy to see your usage (gif, code, etc. whatever you are happy to share or link to).
Tagging for potential feedback @Extrawurst @Roflraging @paniq @nem0.

**Comment by ocornut** [comment]
If you are using drag'n drop idioms in your codebase, please read this thread: https://github.com/ocornut/imgui/issues/1382

**Comment by Bonicx** [comment]
Hi I have a problem with using `ImGui::TreeNodeEx` together with 
`if (ImGui::IsItemActive() && !ImGui::IsItemHovered())` in my loop.
I converted your example code of array into std::list style
I loop through std::list that is of my GameObject pointers
![image](https://user-images.githubusercontent.com/32429706/31923100-7f32b5be-b8ab-11e7-86b5-c03f7b5e624e.png)

[https://youtu.be/mq94qBWaHrk](url)
As you can see that the reordering only works per item active, hover over, and then drag it down.
I am not sure is it because of my game loop update that causes this issue where I can only move up/down of 1 item per drag and click around.

**Comment by ocornut** [comment]
FYI there is a public Drag and Drop branch
https://github.com/ocornut/imgui/tree/drag_and_drop
With the current Drag and Drop API that I've been using in my other WIP branches (docking).

There's no example for it yet, but e.g you can try this.
In `ColorButton()` (source)
```
if (g.ActiveId == id) // Optional micro-optimization you can do if you are in a low-level context where you already have access to this stuff (e.g. own widget), otherwise prob not worth bothering
{
    // With default flags (= no flags) to BeginDragDropSource(), by default it will Begin a tooltip with a transparent background so you can display a "preview" of your drag source.
    // For assets it could be just a filename, or a thumbnail, etc.
    // - Optional flag: ImGuiDragDropFlags_SourceNoAutoTooltip: disable the default tooltip if you want to do something custom.
    if (BeginDragDropSource())
    {
        // - Type is a user defined string of maximum 8 characters. Data is copied and held by imgui.
        // - Function returns true if someone is currently accepting our payload, which may be useful to react visually in the preview
        SetDragDropPayload("_COL4F", &col, sizeof(col), ImGuiCond_Once);

        ColorButton(desc_id, col, flags);
        SameLine();
        TextUnformatted("Color");

        EndDragDropSource();
    }
}
```
In `ColorEdit4()` (target)
```
if (window->DC.LastItemRectHoveredRect) // Optional micro-optimization you can do if you are in a low-level context where you already have access to this stuff (e.g. own widget), otherwise not worth bothering
    if (BeginDragDropTarget())
    {
        // - We can accept multiple payload
        // - Optional flag: ImGuiDragDropFlags_AcceptBeforeDelivery to peek into payload prior to delivery (~mouse release) so you can preview something.. Then test payload->IsDelivery() before copying data.
        // - Optional flag: ImGuiDragDropFlags_AcceptNoDrawDefaultRect to disable the default yellow highlight rectangle (NB: needs some better styling anyway, color currently hardcoded)
        if (const ImGuiPayload* payload = AcceptDragDropPayload("_COL4F"))
        {
            IM_ASSERT(payload->DataSize == sizeof(ImVec4));
            memcpy((float*)col, payload->Data, sizeof(ImVec4));
            value_changed = true;
        }
        EndDragDropTarget();
    }
```

GIF of that in action
![drag and drop colors](https://user-images.githubusercontent.com/8225057/32828092-80cd0d4e-c9ee-11e7-81af-3cc4047de2a4.gif)

Current API:
```
// Drag and Drop
bool          BeginDragDropSource(ImGuiDragDropFlags flags = 0, int mouse_button = 0);                      // Call when the current item is active. If this return true, you can call SetDragDropPayload() + EndDragDropSource()
bool          SetDragDropPayload(const char* type, const void* data, size_t data_size, ImGuiCond cond = 0); // Type is a user defined string of maximum 8 characters. Strings starting with '_' are reserved for dear imgui internal types. Data is copied and held by imgui.
void          EndDragDropSource();
bool          BeginDragDropTarget();                                                                        // Call after submitting an item that may receive an item. If this returns true, you can call AcceptDragDropPayload() + EndDragDropTarget()
const ImGuiPayload* AcceptDragDropPayload(const char* type, ImGuiDragDropFlags flags = 0);                  // Accept contents of a given type. If ImGuiDragDropFlags_AcceptBeforeDelivery is set you can peek into the payload before the mouse button is released.
void          EndDragDropTarget();
```
Current flags:
```
// Flags for ImGui::BeginDragDropSource(), ImGui::AcceptDragDropPayload()
enum ImGuiDragDropFlags_
{
    // BeginDragDropSource() flags
    ImGuiDragDropFlags_SourceNoAutoTooltip          = 1 << 0,       // By default, a successful call to BeginDragDropSource opens a tooltip so you can display a preview or description of the dragged contents. This flag disable this behavior.
    ImGuiDragDropFlags_SourceNoDisableHover         = 1 << 1,       // By default, when dragging we clear data so that IsItemHovered() will return true, to avoid subsequent user code submitting tooltips. This flag disable this behavior so you can still call IsItemHovered() on the source item.
    ImGuiDragDropFlags_SourceNoHoldToOpenOthers     = 1 << 2,       // Disable the behavior that allows to open tree nodes and collapsing header by holding over them while dragging a source item.
    ImGuiDragDropFlags_SourceAllowNullID            = 1 << 3,       // Allow items such as Text(), Image() that have no unique identifier to be used as drag source, by manufacturing a temporary identifier based on their window-relative position. This is extremely unusual within the dear imgui ecosystem and so we made it explicit.
    // AcceptDragDropPayload() flags
    ImGuiDragDropFlags_AcceptBeforeDelivery         = 1 << 10,      // AcceptDragDropPayload() will returns true even before the mouse button is released. You can then call IsDelivery() to test if the payload needs to be delivered.
    ImGuiDragDropFlags_AcceptNoDrawDefaultRect      = 1 << 11,      // Do not draw the default highlight rectangle when hovering over target.
    ImGuiDragDropFlags_AcceptPeekOnly               = ImGuiDragDropFlags_AcceptBeforeDelivery | ImGuiDragDropFlags_AcceptNoDrawDefaultRect  // For peeking ahead and inspecting the payload before delivery.
};
```

I have improved and iterated this code based on the need of my (yet unpushed) docking/tabs code and it handles some subtleties such as nested drop targets, or drag source/target without known identifiers.

I think the API is fairly stable but can probably only be finalized once I can look at those two use cases:

- Testing drag and drop patterns of "moving" nodes, e.g. moving tree nodes.
In particular to be able to differentiate "drag node A into node B to parent it" vs "drag node A below or above node B to make it an ordered sibling", it would be helpful if imgui provided helpers so you don't have to poll every possible target slots.

- Testing drag and drop between multiple imgui windows or a same application, and between windows different applications. It is possible to use the current API to easily transport data across apps? Perhaps it is, but until I tried I don't know.

**Comment by ocornut** [comment]
I have merged the drag_and_drop branch into master now.

I consider the feature Beta (and marked it as such in imgui.h) as it is missing a few thing:
A) There's no real demo yet (but the color widgets now support drag and drop). That's easy to fix, will work on demo code soonish.
B) I haven't established that the api will be good enough to handle re-ordering/moving nodes, in a list or in a tree.
C) I haven't established that the api will be good enough to build a bridge with OS native drag'n drop.

When we have proof-on-concepts to confirm that both B and C are faisible I'll mark the api as non-beta.
If someone is interested in tackling either for their project let me know.

**Comment by heroboy** [comment]
Cool! I think it is interesting if I can copy a draw list as the content of dragging source. Currently clone a draw list is hard.
![default](https://user-images.githubusercontent.com/54468/33921193-395742a2-dffd-11e7-8424-77455aee1558.png)

**Comment by ocornut** [comment]
To clone a ImDrawList you need to deep copy the fields, I think ImVector is missing a = operator we could add one.

But may I ask why are you trying to do that?

**Comment by heroboy** [comment]
`_Channels[0]` should use `memcpy`. Looklike `_ClipRectStack` should not be copied.

> But may I ask why are you trying to do that?

Make an effect that dragging a chrome or firefox tab.

**Comment by evan-gordon** [comment]
Hey @ocornut 
Is there an ETA on drag and drop support for the navigation branch?
I'm trying to use this for item swapping inside the player inventory for my game. For now I've been tinkering with your code to get it working on my end, but as it is now a lot of your code is pretty heavily tied to mouse use.

**Comment by ocornut** [comment]
@evan-gordon It's already merged into the navigation branch, but isn't the point of drag and drop to a be mouse thing? Most of the api makes no sense with keyboard. 

You can use custom code if you need custom control, which is likely if you want the way of using dear imgui for in-game stuff. Humble reminder that dear imgui isn't designed for that use case at all.

**Comment by evan-gordon** [comment]
Okay fair enough, I'm not against writing the new code myself as i already started.

**Comment by sherief** [comment]
I have been spending some time on drag-and-drop and I think a write up is in order.

I think I can split interest in drag-and-drop into two categories:
- "Good Enough" drag-and-drop, for lack of a better name. Just to be clear, I don't mean this in a derogatory way whatsoever - I just use that to refer to the case where drag and drop is only used within the same app, process, and address space. Things like dragging from a color picker to a scene object or attribute, basically only from imgui to imgui and within the same app.
- "First Class" drag-and-drop where you interact with the system just like a native app. You work with clipboard trackers and "drawer" apps like Yoink on macOS (which lets you drag things into a "shelf" that you can drag them out of later). This needs platform dependent code and idioms, and needs to support a level of complexity that most users of Good Enough DnD neither need nor care about - things like multiple formats for the same drag (dragging text as plain and rich text for example) and drag "promises" where the drag source doesn't have the data ready, but only creates it on drop due to the creation being expensive.

Both cases outlined in the First Class DnD description above are concrete things that I ran into - in one tool I support dragging objects within the same instance and across instances, and also to other external editors (paint.exe for textures, etc.). In the former case I need multiple drag formats (I drag the object as both an in-process pointer and a "promise" to generate a serialized version, for whether the drag ends inside or outside the same process), and the drag also exposes a filesystem path that's used when it's dropped on paint.exe. I absolutely _need_ First Class DnD support, and prior to this branch / API I had it hacked into an earlier version of imgui. I can go on forever about NSPasteboard and IDataObjects in a multithreaded app but it'd probably be overkill.

The Good Enough case seems to be sufficiently covered by the current API, but for First Class DnD support I think some changes need to be made:
- Make payload setting optional. Right now I set a dummy payload to make the API happy, but I think the API could still work while assuming the payload setting can be omitted. In my case I directly trigger an OS drag and drop, and that works with the current API, but the drag target begin APIs don't play nicely when you have a drag with no payload.
- Have some way to know when a drag begins, that triggers exactly once for every drag. Right now BeginDragDropSource() returns true every frame that the drag is active, and it's up to the app to detect whether the drag did begin this frame or not. This is a bit of a mismatch between how the OS DnD APIs work in "retained mode" vs imgui's immediate mode. I think it'd be an acceptable break from immediacy for imgui to track this state, in the same way it tracks double clicks and triggers them for a single frame (IIRC).

I'm interested in hearing any comments and answering any questions you might have. First Class DnD support is extremely important to me and the tool I'm working on exercises some less frequently used paths (including running the OS DnD code async in a separate thread).

**Comment by ChugunovRoman** [comment]
> Do you mean drag and dropping of files into your application window?
> That's OS dependant and not likely to be part of core imgui. On Windows you only need to call DragAcceptFiles() and implement the WM_DROPFILES message.

Hi.
Is dropping of files into a app window does support?
How to implement this?

**Comment by rokups** [comment]
@ChugunovRoman this is backend-specific. For example SDL sends `SDL_DROPFILE` when file is dropped on to window. You have to handle this event. You most likely also want to check mouse cursor at the time event is sent in order to detect on which control it was dropped.

@ocornut shouldnt this issue be closed? Drag & drop is implemented.

**Comment by ocornut** [comment]
I tend to keep issue opens when some of the posts are discussing interesting/useful ideas that are still yet to implement and not covered elsewhere.

There are a few things discussed here that are still unfullfilled:

- @sherief's post https://github.com/ocornut/imgui/issues/143#issuecomment-380361637: payload promise (+ the need to honor that promise on the drop is perhaps the tricky part), multiple payload types (tdb), trigger on drag start (easy).
- @s-ol's post https://github.com/ocornut/imgui/issues/143#issuecomment-426584757 which is now covered by #1725 (I have an idea of how to solve that)
- we are lacking a "reorder items in a list" demo (and eventually "in a tree")

I'll close this issue as **the points raised above are all listed in TODO.txt,** when there is an impulse/attempt to solve them it we can open a new issue to discuss them.

Thanks all!

**Comment by rokups** [comment]
> we are lacking a "reorder items in a list" demo (and eventually "in a tree")

I implemented exactly this in my engine editor by adding extra few pixel high drop areas between list items. For this however i had to modify imgui to have smaller drop area border margins. I should make a PR for this margin to be configurable via style..

**Comment by ocornut** [comment]
>> we are lacking a "reorder items in a list" demo (and eventually "in a tree")

> I implemented exactly this in my engine editor by adding extra few pixel high drop areas between list items. For this however i had to modify imgui to have smaller drop area border margins. I should make a PR for this margin to be configurable via style..

PR of a small demo would be helpful, I can think of two ways to do it:
- immediate reordering like how it looks in https://github.com/ocornut/imgui/issues/143#issuecomment-92464274 which is relatively easy to get done
- reordering with proper drag payload which as you said may need in-between elements (and for trees both "over" and "between" would be valid): we need to explore those and maybe see if/how imgui can provide facilities to avoid having to submit dummy items everywhere.

Feel free to open an issue/PR to discuss this further.
