### ISSUE TITLE
Disable ALL scrollbars in InputTextMultiline 

### ISSUE THREAD

**Issue by FredrickV** [ocornut/imgui#1432]
I need to disable both vertical and horizontal scrollbars, i can only find a flag for "ImGuiInputTextFlags_NoHorizontalScroll"

Is there a workaround ?

**Comment by ocornut** [comment]
Hello,

Before considering adding a feature I would prefer to know why do you actually need it.

InputTextMultiline() currently doesn't have an horizontal scrollbar, so vertical is the only one you could disable if we added an extra flag for it.

**Comment by FredrickV** [comment]
I understand, so i am using it for the left line counting bar, adding a photo to illustrate, notice i have extended this specific window height to avoid getting the scrollbar, but as you say, i probably can get away with it using a normal TextInput widget ?


![clipboard02](https://user-images.githubusercontent.com/11610494/32737528-9d356580-c89a-11e7-923b-b5d0a2592e4c.png)

**Comment by ocornut** [comment]
Why would you want an InputTextMultiline() for that? Are you generating a single string with those numbers to display? Do you expect the user to edit those lines numbers as text at all? I'm failing to understand what `InputTextMultiline()` would have to do with it at all..

Are you aware that you can use e.g. the ImDrawList API to draw whatever you want?

**Comment by FredrickV** [comment]
I guess my quest for glory started when i noticed that the scroll behavior of InputTextMultiline did scroll half Font height, not full (line by line) as its typical of text editor. So i am doing some adjustments in the callbacks, and at the same time...

Since i am only re-drawing those few characters (when right window is changed/scrolled), i am fine with it, but i can use another widget type.

**Comment by ocornut** [comment]
It doesn't scroll by "half font height" but adjust the scrolling so that the current line is visible (tho I can understand other variations may be desirable).

If you are going to modify imgui.cpp locally (which I'd advise against), you can achieve that scrollbar disabling by adding the `ImGuiWindowFlags_NoScrollbar` flag in this block of `InputTextEx()`:

```
if (is_multiline)
{
    ItemAdd(total_bb, id, &frame_bb);
    if (!BeginChildFrame(id, frame_bb.GetSize()), ImGuiWindowFlags_NoScrollbar)
```

> Since i am only re-drawing those few characters (when right window is changed/scrolled),

I still fail to understand why you would use a `InputTextMultiline()` if all you need to do is display some line numbers. You can use BeginChild/TextUnformatted/EndChild for that or come up with a more manual solution.

**Comment by FredrickV** [comment]
Fantastic, i will look into the tips you gave me, just need to write a million lines of rendering code first.
(Just needed something quick and dirty)

![image](https://user-images.githubusercontent.com/11610494/32738945-badaeee4-c89e-11e7-84f0-c3fac4001a32.png)

![image](https://user-images.githubusercontent.com/11610494/32739066-22c8e416-c89f-11e7-9147-b9ad89ddc36f.png)

**Comment by ocornut** [comment]
Cool :)
May I suggest looking at https://github.com/BalazsJako/ImGuiColorTextEdit/ which may provide just what you need (I haven't tried it myself but heard good feedback from other users)

I would like to eventually rewrite `InputText` since it became one of the most confusing part of imgui codebase, but it isn't a top priority just yet.

**Comment by byteIock** [comment]
how can you make the scroll bar follow with your number lines?
