### ISSUE TITLE
Makefile issues

### ISSUE THREAD

**Issue by clankill3r** [ocornut/imgui#1437]
Is anyone here using VSCode as their editor?
And if so, can someone help me how to set it up in such a way that I can step through with the debugger.

After a 2 hour struggle I get this:

> ERROR: Unable to start debugging. Unexpected LLDB output from command "-exec-run". Command 'exec-run'. Invalid process during debug session
> The program '/Volumes/DATA/imgui/examples/opengl3_example/main.o' has exited with code 42 (0x0000002a).

**Comment by ocornut** [comment]
Hello,

That’s not really a dear imgui question, but rather a question to ask in VSCode communities.

Omar

**Comment by clankill3r** [comment]
Ok, to get a bit more imgui related.
What does the cmake file execute:

I get this:

`g++ -o opengl3_example main.o imgui_impl_glfw_gl3.o ../../imgui.o ../../imgui_demo.o ../../imgui_draw.o ../libs/gl3w/GL/gl3w.o -I../../ -I../libs/gl3w -I/usr/local/include -Wall -Wformat -framework OpenGL -framework Cocoa -framework IOKit -framework CoreVideo -L/usr/local/lib -lglfw`

But I can't figure out this part:

```
.cpp.o:
	$(CXX) $(CXXFLAGS) -c -o $@ $<
```
I would expect:

`c++ -I../../ -I../libs/gl3w -I/usr/local/include -Wall -Wformat -c -o .cpp.o opengl3_example`

But that gives me warnings.

> clang: warning: opengl3_example: 'linker' input unused [-Wunused-command-line-argument]
> clang: warning: argument unused during compilation: '-I ../../' [-Wunused-command-line-argument]
> clang: warning: argument unused during compilation: '-I ../libs/gl3w' [-Wunused-command-line-argument]
> clang: warning: argument unused during compilation: '-I /usr/local/include' [-Wunused-command-line-argument]
> clang: warning: argument unused during compilation: '-Wall' [-Wunused-command-line-argument]
> clang: warning: argument unused during compilation: '-Wformat' [-Wunused-command-line-argument]

**Comment by ebachard** [comment]
The line you mentionned cannot compile, because the order of the arguments is not (imho) correct, and I'm not surprised with what happened when you tried. 

If I can help,  line 1 of the Makefile), one can read :
``CXX = g++``'

=>maybe you could replace g++ with c++ and retry ?

To verify what happens with the (apparently) wrong order, you should have a look at : https://www.gnu.org/software/make/manual/make.html#Loading-Objects ). IMHO, g++ takes all the .cpp to produce .o, and "understands" the command line as:

g++ $(output binary file, $EXE here)  -c -o  (dependencies symbolized by $< ) followed by the includes  then the CXX_FLAGS , and at the end the linking options ( + static libs always at the end). 

=> finaly, what happens seems to be correct, but maybe -last but not least- Apple modified something ?

HTH

**Comment by clankill3r** [comment]
I noticed if I make a change to imgui_demo.cpp and then call make from the opengl3_exaple folder it would spit out:

> c++ -I../../ -I../libs/gl3w -I/usr/local/include -Wall -Wformat -c -o ../../imgui_demo.o ../../imgui_demo.cpp
> c++ -o opengl3_example main.o imgui_impl_glfw_gl3.o ../../imgui.o ../../imgui_demo.o ../../imgui_draw.o ../libs/gl3w/GL/gl3w.o -I../../ -I../libs/gl3w -I/usr/local/include -Wall -Wformat -framework OpenGL -framework Cocoa -framework IOKit -framework CoreVideo -L/usr/local/lib -lglfw
> Build complete for Mac OS X

Instead of:

> Build complete for Mac OS X

If I concatenate those commands with a `;` then it does work for changes made in main.cpp.
But it does not work for changes made in imgui_demo.cpp. Those have no effect.
Strange...

**Comment by ocornut** [comment]
Closing this as old/stall.
