### ISSUE TITLE
Main menu bar isn't affected by DisplaySafeAreaPadding

### ISSUE THREAD

**Issue by ldecarufel** [ocornut/imgui#1439]
The main menu bar ignores the DisplaySafeAreaPadding style and is always drawn at (0,0).
On TVs with overscan, the main menu can be unusable because it is drawn above the visible area.

**Comment by ocornut** [comment]
Hello Louis, I think a PR is coming for that and I will look at it. My concern is/was that the padding within the menu bar will almost necessarily always look asymmetrical in that situation.

Out of curiosity, which sorts of value and/or range do you typically use for safe area padding? And what’s the font size?

**Comment by ocornut** [comment]
Ought to clarify: the reason the asymmetry is problematic is because we have a non-zero default value of ImVec2(4,4) for `DisplaySafeAreaPadding`, and we probably don't want an asymmetrical menu bar when used on a computer with default settings. So perhaps will change the default value to (0,0) and/or use Max(DisplaySafeAreaPadding, FramePadding) which would be ok unless FramePadding.y is smaller.

**Comment by ocornut** [comment]
Louis, this should be fixed now (see 2 commits above). I also made a third commit to improve handling of the safe area for popups/tooltips/menus.

In the future viewport branch this setting will evolve a little, as safe area may be defined on a per-monitor basis. I'm not touching it right now because I don't have much visibility on this but ideally viewports could be used across two machines.

**Comment by ocornut** [comment]
@ldecarufel Are you still using `DisplaySafeAreaPadding` ?
AFAIK all current platforms apart from Xbox One have safe area data pulled from OS settings, unless Xbox One was improved since (last checked in 2017). Do you remember the context for using this?

Tagging @dougbinks as I vaguely remember (might be wrong) that you allow used safe area?

**Comment by dougbinks** [comment]
I know of no way on PC Windows to set the safe area for a TV, so I would have thought this was still required.
