### ISSUE TITLE
ImGui DX9 /CLR problem

### ISSUE THREAD

**Issue by tuddor23** [ocornut/imgui#1449]
Hello, I use ImGui DX9 and a DirectX 9 hook made in 10 minutes. Everything works fine until I want to compile with /CLR extension and inject into process.
If I compile with /CLR extension I receive many warnings from imgui and when I try to inject into process it instantly close without any assert or something.

**Comment by ocornut** [comment]
You need to provide clearer and information in order to hope to receive an answer. This is not a place for people to guess what's in your mind or on your computer and then help you! Especially if you are have just spent 10 minutes on it. 
Your issue is also likely unrelated to imgui and a general MSVC/Build/C++ related question, so maybe this isn't the place to ask, sorry.
