### ISSUE TITLE
Drawing not antialiased lines and rectangles

### ISSUE THREAD

**Issue by sawickiap** [ocornut/imgui#1461]
I wanted to draw a rectangle that would be pixel-perfect, just vertical and horizontal lines having width of 1 pixel of intended color. After using `ImDrawList::AddRect` I got these lines blurred/antialiased, rendered by some complex geometry `DrawIndexed(48)`. I noticed that I can achieve my goal by rendering polyline because there I have parameter `anti_aliased` that I can set to `false`, but this is quite a workaround.

```cpp
//drawList->AddRect(dstRect.Min, dstRect.Max, 0xFF80FF80);
ImVec2 points[] = {
    ImVec2(dstRect.Min.x, dstRect.Min.y),
    ImVec2(dstRect.Max.x, dstRect.Min.y),
    ImVec2(dstRect.Max.x, dstRect.Max.y),
    ImVec2(dstRect.Min.x, dstRect.Max.y),
};
drawList->AddPolyline(points, 4, 0xFF80FF80, true, 1.f, false);
```

I would like to request possibility to render un-anti-aliased lines and rectangles as well. Possible implementations:

- Add parameter `anti_aliased` to `AddLine`, `AddRect` etc.
- Add separate functions for drawing un-anti-aliased objects.
- Add anti-aliased state to `ImDrawList` with some Push/Pop functions.

**Comment by berkay2578** [comment]
You can use `ImGui::PushStyleVar()/ImGui::PopStyleVar()` to enable/disable anti-aliasing runtime. You have `AntiAliasedLines` and `AntiAliasedShapes`.

**Comment by ocornut** [comment]
Adam,

If your rectangle coordinates are perfectly aligned to the pixel, the output should visually be pixel perfect. That's your solution, and imgui does it everywhere.

You are correct there is no fast-path for axis-aligned pixel-aligned rectangle outline (regular filled rectangle has it), so it consumes 12 vertices, 48 idx (=16 triangles). It could be 8 triangles instead of 16. As styling evolution put more emphasis on borders we may add it (will also transition rounded borders to use textures).

> Add anti-aliased state to ImDrawList with some Push/Pop functions.

As pointed above there is a `AntiAliasedLines` global flag.
It's in my task list to completely remove the dependencies on ImGui from ImDrawList, currently it reads a global flag ImGui::GetIO().AntiAliasedLines. I'm not exposing those two booleans as `ImGuiStyleVar_XXX` as suggested, because they should be moved to e.g. `ImDrawListFlags` for finer control. In the meanwhile you can backup/restore those values if you want the additional performance for those rectangles. 

If you don't draw tens of thousands rectangle, you can just round your coordinates and use the normal AA path. 

PS:
> 0xFF80FF80

You can use the `IM_COL32(255,128,255,128)` macro.

**Comment by sawickiap** [comment]
Thank you Omar. Doing `floor()` on my coordinates fixed the issue - rectangle is now pixel-perfect. Performance was not an issue here, just the looks.

It would still be nice to have option to disable antialiasing, but if you already have it on your TODO list, then I'm closing this issue.

PS: I consider `0xFF80FF80` to be more compact and convenient for me than `IM_COL32(255,128,255,128)` :)
