### ISSUE TITLE
Delayed tooltips

### ISSUE THREAD

**Issue by alexanderbock** [ocornut/imgui#1485]
Couldn't find a previous issue or tip on it.  I want to only show the tooltip after i number of seconds, rather than immediately.  Am I missing some function to do that or is there a better way rather than to keep a timer based on `IsItemHovered()` for each item?

**Comment by ocornut** [comment]
Hello Alexander,

I added a timer a while ago to track an internal timer along with the `g.HoveredId` field, however `IsItemHovered()` specs allow for a few more things including testing items that have no identifiers (such as `Text()` items).

If you want to only use it on items that have identifiers (typically items that react to clicks), as a workaround for know you may do this:

```
#include <imgui_internal.h>

if (IsItemHovered() && GImGui->HoveredIdTimer > MY_TIME_THRESHOLD)
{
 //..
}
```
Which you'd probably wrap as a custom helper e.g. `IsItemHovered(flags, timer)` for now.

But this won't work on Text and other items because the timer isn't tracked for them.
In `ShowMetricsWindow() > Basic State` you can watch the HoveredIdTimer if you need to check.

I'll have to think about how we can provide a more general solution to this problem. The drag and drop branch had to solve similar issues to allow every item to be used as a drag source/target, and there are solution that may be viable for this use case as well.

**Comment by alexanderbock** [comment]
Awesome!  That workaround worked  Thanks a bunch.

If you get around to implementing a general-ish solution for this, I was originally looking for a sister function to `IsItemHovered()` that returns the hover timer for the current object.

**Comment by ocornut** [comment]
Now added the following, long-awaited helper.

```
// IsItemHovered() hovering delays for tooltips
ImGuiHoveredFlags_DelayNormal                   = 1 << 11,  // Return true after io.HoverDelayNormal elapsed (~0.30 sec)
ImGuiHoveredFlags_DelayShort                    = 1 << 12,  // Return true after io.HoverDelayShort elapsed (~0.10 sec)
ImGuiHoveredFlags_NoSharedDelay                 = 1 << 13,  // Disable shared delay system where moving from one item to the next keeps the previous timer for a short time (standard for tooltips with long delays)
```
IO:
```
float HoverDelayNormal; // = 0.30 sec  // Delay on hovering before IsItemHovered(ImGuiHoveredFlags_DelayNormal) returns true.
float HoverDelayShort;  // = 0.10 sec  // Delay on hovering before IsItemHovered(ImGuiHoveredFlags_DelayShort) returns true.
```

It works on items that have no identifier (e.g. `Text()` calls).

I consider this a low-level helper.
Technically I envisioned and still want a high-level helper in the form of flags passed to Tooltip functions.
The reason is that that are more features desirable for Tooltips: priority (for override/conflict resolution, e.g. system/lib tooltip on an item, overridden by user tooltip), and variety of behavior may want to be configurable. There are so many different applications and OS behaviors.

e.g.
- "Tooltip appear when mouse is still" vs "Tooltip appear as long as in area"
- "Tooltip disappear when leaving item area" vs "Tooltip disappear when making a small move"
- "Tooltip reappear again after same timer" vs "Tooltip never reappear until leaving/reentering  to item"
- Varying rules/defaults/timer for when keyboard navigation is active and triggers IsItemHovered().

I've seen all of those. I am not yet sure what are the desirable default and desirable amount of configuration (less configuration would be good). I was tempted to use names carrying more semantic e.g. `ImGuiHoveredFlags_TooltipDelay` instead of `ImGuiHoveredFlags_DelayNormal` but this being the lower-level part it may be good as-is, and the current name can more naturally be mirrored in hypothetical Tooltip flags. 

Feedback welcome!
May rework this before tagging next release, and I don't know when we'll introduce higher-level tooltip layers, probably not soon.

**Comment by MBilderbeek** [comment]
For a special case, I was trying to (temporary) modify the `HoverDelayNormal` style variable to something even larger than the default long delay. But I found no way to do this. Although this is part of the Style struct, there is no style Id for it to set it with `PushStyleVar`. Or: what am I missing?
