### ISSUE TITLE
Can change checkbox color?

### ISSUE THREAD

**Issue by Christian8814** [ocornut/imgui#1486]
Im using ImGui::ShowTestWindow() to change the colors of my menu and can't change the color of the checkbox. kthxbye

**Comment by ebachard** [comment]
Hi,

Sure you can, like you can define your own customized style. The lines below are limited to your question, but you can do whatever you want.
  
```
ImGuiStyle & style = ImGui::GetStyle();
// below is just a random color, as example
style.Colors[ImGuiCol_CheckMark] = ImVec4(0.184f, 0.407f, 0.193f, 1.00f);

```
Other suggestions:
+ grep for ImGuiCol_CheckMark in ImGui sources
+ try to search in the issue list using the style keyword should give you an overview of what you can do.

Last but not least, you can test using the demo window, provided in the ImGui examples (SDL, GLFW and so on)

**Comment by ocornut** [comment]
Thanks for your answer @ebachard, much appreciated. Closing this as answered. 

PS: I'll now be blocking lazy/impolite users because it's too destructive for this project. We've got an influx of new users from cheating sites (http://smef.pw/pasting, https://blast.hk/threads/19292/ and the likes). Anyone behaving lazy and entitled will be blocked. Please solve those programming issues on your own community/forums.
