### ISSUE TITLE
Font not loaded assert/crashing on reload

### ISSUE THREAD

**Issue by marbuser** [ocornut/imgui#1492]
I recently decided to integrate ImGui into my engine, and for the most part it was doing great!
However, upon using a new font (tahoma), some strange stuff started happening.
If I completely unload ImGui from the engine and then reload it, there is about a 1 in 3 chance this error happens. 
![](https://i.imgur.com/MBejhPg.png)

Just to clarify, the font rendering DOES work, but the crashing makes me wonder if I should even bother, since with stock font it doesn't do this.

I call AddFontFromFileTTF as well as GetTexDataAsRGBA32 BEFORE my main loop, and then call PushFont after ImGui_ImplDX9_NewFrame.

I did a bit of debugging and figured that it might be caused by something getting left behind, so I also call ImGui_ImplDX9_Shutdown when I unload from my engine.

Tried to figure this one out on my own but have to say this has truly stumped me.
If anyone from this Git could give me an idea of what's going on, or even better an idea of how to fix it, that would be pretty awesome.

**Comment by ocornut** [comment]
Could you provide a repro / MCVE for it? (https://stackoverflow.com/help/mcve)
That would probably help you narrow the bug.

You essentially need to clarify all of this:
"However, upon using a new font (tahoma), some strange stuff started happening.
If I completely unload ImGui from the engine and then reload it, there is about a 1 in 3 chance this error happens."
Because it is a little too vague. How do you load, how to do "unload imgui from the engine" (not even sure what that means). Providing a MCVE will be the fastest way towad finding a solution for your problem.

**Comment by marbuser** [comment]
Sorry for the late reply. 
We do it via DLL and hook our engine functions. We do this for certain internal reasons. So we load it that way and then unload it via FreeLibraryAndExitThread.

Do you wish for me to include the hooking code we use as well as a demo D3D9 project for you to inject the dll into? Or do you want specifically ImGUI code only?

**Comment by ocornut** [comment]
Hello,

I would prefer the Minimal possible example that reproduce the error. If you can strip something and still repro the error then it should be stripped. The process of working toward that MCVE (https://stackoverflow.com/help/mcve) will likely allow you to narrow down the issue so what is actually causing it, and perhaps even fix it before you have a chance to submit it. e.g. probably the issue has nothing to do with D3D9 itself.
