### ISSUE TITLE
Listbox bugs

### ISSUE THREAD

**Issue by attilaz** [ocornut/imgui#151]
- Listbox() label not included in declared size (similar to https://github.com/ocornut/imgui/issues/149)
- Tooltip doesn't display

repro: https://gist.github.com/attilaz/db3b5357e650edd0d385#file-gistfile1-txt-L37

**Comment by ocornut** [comment]
Thanks, will look into it. The fix is not as trivial as the combo box one because of how list box create a child window, but it's a perfect good reason to clean this up.

Tooltip, out of curiosity how would you use a tooltip appearing when hovering the box? Would you display data based on the selected item? (instead of the hovered item).

**Comment by attilaz** [comment]
In that particular case I would like to show tooltip that is not based on selected/hover item: info about keyboard shortcut.

**Comment by ocornut** [comment]
Both fixed now.

I also added another example:
![horizontally_layed_out_lists](https://cloud.githubusercontent.com/assets/8225057/6537749/ddd6edc0-c451-11e4-8bbe-12a023871ced.PNG)

Note that this doesn't show a label on the list but that works as well.

**Comment by attilaz** [comment]
wow!  thanks :+1:
