### ISSUE TITLE
controlling the vertical scroll of a multiline text input

### ISSUE THREAD

**Issue by onqtam** [ocornut/imgui#1523]
so I have a ```InputTextMultiline``` in a read only mode, and I append from elsewhere to the string that gets displayed.

At some point a scroll bar appears - is there a way to control the scroll of the multi line text field?

I managed to get what I want by putting ```ImGui::SetScrollY(ImGui::GetScrollMaxY());``` inside of ```InputTextEx()``` but thats not the way

**Comment by ocornut** [comment]
You can "enter" the child window after calling `InputTextMultiline()` by doing:
```
BeginChild(GetId(my_input_text_label))
SetScrollHere();
EndChild();
```
It's not really documented because you are relying on the fact that InputText opened a child window with this identifier. Not that you can't call `BeginChild(const char*)` variation that you wouldn't get the same id as the child window used by the input text.

It's not ideal, right now in imgui it's easier and more natural to have a normal `Text`/`TextUnformatted` directive + a `Copy to clipboard` button.

**Comment by onqtam** [comment]
thanks for the quick reply! this fixed my problem - you can close the issue if you want :)

**Comment by onqtam** [comment]
I just wanna say that I discovered this great project: [ImGuiColorTextEdit](https://github.com/BalazsJako/ImGuiColorTextEdit) - and it's precisely what I was looking for! - this is what I needed a multi-line text field for :)

**Comment by KulaGGin** [comment]
```
BeginChild(GetId(my_input_text_label))
SetScrollHere();
EndChild();
```
Doesn't work.

```
BeginChild(GetId(my_input_text_label))
ImGui::SetScrollY(ImGui::GetScrollMaxY());
EndChild();
```
Doesn't work either.
