### ISSUE TITLE
SetScrollHere and one-frame delays

### ISSUE THREAD

**Issue by franciscod** [ocornut/imgui#1526]
When using SetScrollHere (example: Demo Window -> Layout -> Scrolling -> drag the "Line = 50") the scrolled content has a ~1frame delay compared with the color highlight. Is there any way to remove this delay?

**Comment by franciscod** [comment]
I'm really interested in making this work, even if it's a lot of work. I don't have a clue of where to start, I'm looking at the rendering code but I'm quite lost :)

**Comment by franciscod** [comment]
49b7a8e61f828ee6fcc01e463b650eebf70a4c14

This is the first commit with the scrolling demo in it. Hopefully it will be easier to experiment in a simpler version of imgui :)

For visualization puposes, this reproduces the one-frame delay:

```c++
for (int line = 0; line < 100; line++)
                {
                    if (track && line == track_line) {
                        ImGui::Text("Line %d ====", line);
                        ImGui::SetScrollPosHere(i * 0.50f); // 0.0f,0.5f,1.0f
                    } else {
                        ImGui::Text("Line %d", line);
                    }
                }
```

I tried changing where the Cursor variables are updated (i.e. tried to do it soon as SetScrollPosHere is called) but had no success.

**Comment by franciscod** [comment]
v1.11 repros this if you backport the scrolling demo :)
24028911e350c1ac81bfd715f2357cdc56b1c9d2

paste this around line 6033
```c++

    if (ImGui::CollapsingHeader("Scrolling"))
            {

                static bool track = true;
                static int track_line = 50;
                ImGui::Checkbox("Track", &track);
                ImGui::SameLine(); ImGui::SliderInt("##line", &track_line, 0, 99, "Line %.0f");

                    ImGui::BeginChild("asd", ImVec2(ImGui::GetWindowWidth() * 0.25f, 200.0f), true);
                    for (int line = 0; line < 100; line++)
                    {
                        if (track && line == track_line) {
                            ImGui::Text("Line %d ====", line);
                            ImGui::SetScrollPosHere();

                        } else {
                            ImGui::Text("Line %d", line);
                        }
                    }
                    ImGui::EndChild();
            }

**Comment by ocornut** [comment]
@franciscod `SetScrollHere` being a function call in the middle of rendering of the window, it's not possible for it to apply the new scrolling immediately. It would require disabling clipping anything ahead of time, or reprocessing from the window another time entirely, etc.

What are you trying to solve exactly? Which problem do you have with that?

It's more likely that the more natural solution would be to adjust the user code. What the demo code does (altering the look of the output based on expected scroll value) is actually quite unusual, in a way the demo is faulty here.

Another possible solution is to have `SetNextWindowScroll()` function that could be called ahead of Begin. I would like that but right now not sure it is worth exposing more API if you can solve it your problem otherwise. 

(I'd like to rework the SetNextWindow/SetWindow entry points to be more flexible. Right now we have too many of them including some using `const char* name` as input. If I were to redesign the API from stratch today I would maybe consider a more consistent way of identifying windows e.g. ` SetWindowPos("My Tool", pos); / SetWindowPos(IMGUI_CURRENT_WINDOW, pos); / SetWindowPos(IMGUI_NEXT_WINDOW, pos);` .)

**Comment by franciscod** [comment]
Scrollbars seem to have this 'one-frame scroll' ability, though...

**Comment by ocornut** [comment]
Just create yourself a function for that:
```
void SetWindowScrollY(const char* name, float scroll_y)
{
    if (ImGuiWindow* window = ImGui::FindWindowByName(name))
    {
        window->DC.CursorMaxPos.y += window->Scroll.y;
        window->Scroll.y = scroll_y;
        window->DC.CursorMaxPos.y -= window->Scroll.y;
    }
}
```

> Scrollbars seem to have this 'one-frame scroll' ability, though...

Because they are processed in Begin() before the scrolling is locked.

**Comment by ocornut** [comment]
Variant, this will also work:

```
void SetWindowScrollY(const char* name, float scroll_y)
{
    if (ImGuiWindow* window = ImGui::FindWindowByName(name))
    {
        ImGuiContext& g = *GImGui;
        ImGuiWindow* backup_window = g.CurrentWindow;
        g.CurrentWindow = window;
        ImGui::SetScrollY(scroll_y);
        g.CurrentWindow = backup_window;
    }
}
```

The problem from my point of the view (or, the API point of view) is that there are several issues with scrolling and SetXXXWindow functions and I probably need to tackle them together, so I can't just add this entry point in the API. But this function (using `imgui_internal.h`) will work for your use case.

**Comment by franciscod** [comment]
Awesome! I'll try that as soon as I can and comment on how it worked on my usecase. Thank you Omar, for the in-depth explanations and suggestions :)

**Comment by franciscod** [comment]
That `SetWindowScrollY` did wonders! I even got it to snap perfectly by scrolling in increments of `(rowHeight + ImGui::GetStyle().ItemSpacing.y)` :) Thank you again, Omar!

Not sure if you want to leave this issue open. Maybe open another one for improving the scrolling API?

**Comment by franciscod** [comment]
FindWindowByName gets tricky on child windows... see #1698

**Comment by ocornut** [comment]
@franciscod I have added a `SetNextWindowScroll()` in imgui_internal.h.
It's in internal because I don't have much use cases nor tests for it, but I envision it will probably eventually be moved to imgui.h

**Comment by franciscod** [comment]
Interesting! I'll check that out. Thanks!

**Comment by franciscod** [comment]
I can confirm `SetNextWindowScroll()` solves the one-frame delays!

**Comment by ocornut** [comment]
With commit 7380b98 I have moved `SetNextWindowScroll()` to imgui.h now.
