### ISSUE TITLE
Load in ImGui all Systems Fonts

### ISSUE THREAD

**Issue by aiekick** [ocornut/imgui#1527]
Hello, 

im able to create a font designer with imgui.

and when i load all my systems fonts to imgui, (over 2300 font, outch ), the app crash at the font 337 :)

i thinck, im out of memory for the atlas texture.

i would like to display a list of font, displayed with each font :)

is there a way you thinck for doing that , maybe without loading all font in memory

**Comment by ocornut** [comment]
Hello,

> i would like to display a list of font, displayed with each font :)

It's not an easy problem to solve. 

First, if you say something is crashing you ought to say where and how (with a callstack).
But loading 2300 fonts synchronously, even just the file from file system (without any rendering) is not reasonable anywhere.  

What I would do:

- File system loads needs to be processed asynchronously on demand, based on what's visible. You can use the clipper functionality to test what's visible and queue loading/rendering requests for the visible items.

- Once a font file is loaded, a ImFontAtlas, add the font in the FontAtlas with _only_ the glyphs you need to use to render the name. You can use `ImFontAtlas::GlyphRangesBuilder` for that. There's no need to register all glyphs, and there's no need for you to pollute your main imgui font atlas with the font at all.

- Use ImFont::RenderText() to render that name into a custom texture that serves as a cache of rendered _names_ of each font, keyed by the font name. You'll need a render target, or you may decide that you can software rasterize it since you know RenderText() will only output pairs of triangles forming axis-aligned quads, it's easy to rasterize that yourself (blitting horizontal blocks from the ImFontAtlas texture to your texture to form the text). 

- Get rid of the font file data and ImFontAtlas.

- In your main imgui/render thread you can render straight from that cache texture.

Again this isn't a trivial problem to solve but you've got the steps here if that's really what you want to achieve.

**Comment by aiekick** [comment]
thanks for your suggest, i better understand what i can do without overload the memory.

if you wnat know just what i do and where it crash :

I load all font like that before the call to ImGui_ImplGlfwGL3_NewFrame() :

```cpp
io.Fonts->AddFontDefault(); 

for (std::map<std::string,std::string>::iterator it=m_Fonts.begin(); it!=m_Fonts.end();++it)
{
	io.Fonts->AddFontFromFileTTF(fontPath.c_str(), 13.0f);
}
```

if i stop after 100 loaded font, i have this crash :

![getrgbaerror](https://user-images.githubusercontent.com/1434736/34454513-5adf2e3a-ed6d-11e7-9ce2-6df890117b75.png)

if i not stop i have that

![out_of_memory](https://user-images.githubusercontent.com/1434736/34454512-5ac27830-ed6d-11e7-8270-4343aba0ee3b.png)

I not posted these screenshot before because for me its just due to a bad use of memory for my needs :)

**Comment by ocornut** [comment]
The malloc for the texture probably failed. What are the values of TexHeight and TexWidth?
Also, create ImFontConfig to pass to `AddFontFromFileTTF()`, set Oversamping parameters to 1 on both axis, your texture will be 6 times smaller.

If you are making a font tool using imgui_freetype would yield better quality results especially at size 13.0f.

**Comment by aiekick** [comment]
TexWidth = 4096 and TexHeight = 27

**Comment by aiekick** [comment]
i have tried to load a custom range here :

```cpp
ImFontConfig config;
config.OversampleH = 1;
config.OversampleV = 1;
config.GlyphExtraSpacing.x = 1.0f;

ImVector<ImWchar> ranges;
ImFontAtlas::GlyphRangesBuilder builder;
builder.AddText("Choose Me !");
builder.BuildRanges(&ranges);

io.Fonts->AddFontFromFileTTF(fontPath.c_str(), vFontSize, &config, ranges.Data);
```

but when i go to style editor, i get 0 glyphs loaded.

progggyclean has 225 glyphs, but not the others fonts ..

![fontnotloaded](https://user-images.githubusercontent.com/1434736/34455855-5454a44e-ed88-11e7-9b23-b43f099cfa03.png)

maybe i do something wrong ?

**Comment by ocornut** [comment]
The range needs to persist until Build() is called.

**Comment by aiekick** [comment]
it works thanks :)

**Comment by aiekick** [comment]
when i have uploaded a font in the font atlas. when i switch to the next font, can i replace the glyphs of the last font by this new in the font atlas, instead append glyphs ?

**Comment by aiekick** [comment]
i successfully loaded a font on demand and regenerated the font texture for using it. but i failed to delete the last loaded font.

i seen in the imgui code, the clearFonts method, so i tried to do this beofre load the new font

```cpp
IM_DELETE(io.Fonts->Fonts[1]);
```

after that i load the new font, and again after that i regenerate the texture font

but this time the call to 
```cpp
io.Fonts->GetTexDataAsRGBA32(&pixels, &width, &height)
```

crash and i get this error :

![crash](https://user-images.githubusercontent.com/1434736/34456807-9a698ff4-eda0-11e7-9340-70e44436f747.png)

do you know where im wrong ?

**Comment by ocornut** [comment]
You can’t remove a font from an atlas you need to clear the atlas. 

Sorry I can’t be answering all those questions you need to figure it out from the code and comments.

**Comment by aiekick** [comment]
ok i understand. no problem.

for the moment all works, its not efficient, but it work :)

but some times, some ttf font crash the app.
and i dont know how can i avoid that

i thinck its a bad font format, you see the callstack on right

![somefontcrash](https://user-images.githubusercontent.com/1434736/34457034-d8cd78a0-eda5-11e7-86f7-0fc8edc49da8.png)

the problem is assert in stb_truetype file, but i dont know what i can do for avoid that :

![assert_stb](https://user-images.githubusercontent.com/1434736/34457062-617fa36c-eda6-11e7-97e1-390a143de138.png)

but maybe im on the wrong thread if the bug is on the stb_truetype side :)

**Comment by aiekick** [comment]
i have found a font (Son_of_.ttf) who is always crashing ImGui. here the link if you want test. 
https://ufile.io/lslu1
i hope we can find a way for avoid crashing on some fonts :) who are valid, because i can visualise it in windows font preview

it fail here :

![crash2](https://user-images.githubusercontent.com/1434736/34457201-18d3d7f6-edaa-11e7-8633-03aa58f56c1b.png)

**Comment by ocornut** [comment]
1) stb_truetype is failing to load the font, you may report to the nothings/stb/ repo if you need.

Basically if you step in a debugging, stbtt_InitFont() returns false here:
```
        const int font_offset = stbtt_GetFontOffsetForIndex((unsigned char*)cfg.FontData, cfg.FontNo);
        IM_ASSERT(font_offset >= 0);
        if (!stbtt_InitFont(&tmp.FontInfo, (unsigned char*)cfg.FontData, font_offset))
        {
            atlas->TexWidth = atlas->TexHeight = 0; // Reset output on failure
            ImGui::MemFree(tmp_array);
            return false;
        }
```

2) I changed the code to fail more gracefully in that case (the RGBA codepath would indeed crash as you pointed one). In return you'll get a NULL pointer for `pixels` and zero `width`/`height`, so your code may handle the loading failure and ignore that font.

**Comment by aiekick** [comment]
Super nice. thanks :)

**Comment by ocornut** [comment]
Closing this as solved.
