### ISSUE TITLE
Disable movement of popup_context_window

### ISSUE THREAD

**Issue by Shadowblitz16** [ocornut/imgui#1533]
Hello I am using a gamemaker port of this library and I was wondering how to make a rightclick context menu while disallowing it to be dragged around.
could you show me a example on how to do this in c++?

**Comment by ocornut** [comment]
You cannot at the moment.

You'd essentially need to pass the `ImGuiWindowFlags_NoMove` flags to the `Begin()` call, but for various reasons you can't yourself since flags are not exposed to `BeginPopup()` and `BeginPopupContextItem()`, unless you use and rely on the `imgui_internal.h` private API.

May I ask what is the reason you want to disable dragging around?

**Comment by Shadowblitz16** [comment]
thankyou for your time
ya thats what I was thinking but I couldn't find a way to pass that flag in
I want it like this so its more like a window7 context strips where its not able to be dragged around.
not much of a reason behind it besides the feel and looks, but I feel that these things should be able to be done.

**Comment by ocornut** [comment]
@Shadowblitz16 
With recent planned work I have exposed flags to `BeginPopup()` so it is possible to pass the `ImGuiWindowFlags_NoMove` flag to it now.
