### ISSUE TITLE
Automatic leaf flag for tree item

### ISSUE THREAD

**Issue by ejulien** [ocornut/imgui#1534]
Having something like `ImGuiTreeNodeFlags_AutoLeaf` would be extremely useful when visualizing a tree that can be filtered.

With the current API the decision to filter out an entry from the tree can conveniently be done on the spot. But in order to determine if the current item is a node or a leaf one needs to recursively explore all children until at least one child item is found to be not filtered out. Or ideally pre-filter the input structure prior to displaying it.

I suspect that Dear ImGui does not even cache anything related to a tree hierarchy when dealing with tree items but, if it does that would be a nice feature. If not, close the issue, this is just me getting used to being lazy ;).

**Comment by ocornut** [comment]
Emmanuel, as you suggested ImGui doesn't track anything related to the tree hierarchy.

Supposedly if you are searching a tree it would beneficial on your side to cache your search results and tag tree nodes leading to a result. If you have 1 view it can be trivially done by storing the information in your node. If you need to handle multiple views, hmm, I haven't thought about it so much but instead of storing a complete tree duplicate per view, you could store the "cut off" nodes only. So you'd be storing only the list of node that needs to NOT be displayed.

**Comment by ejulien** [comment]
Yes, the "cut off" approach is what I am using now.
It wasn't even that much work. Closing the issue then.
