### ISSUE TITLE
ImVector::push_back(...) check

### ISSUE THREAD

**Issue by Flix01** [ocornut/imgui#1577]
Hi, well, actually I'm not sure if this is really an issue or not...

I'm working on a completely different code that implements a custom vector class, and I had issue when calling something like:
```c++
MyVector<int> a;
[...] // Fill a with 100 integers here
a.push_back(a[65]);
```
Now, since push_back(...) takes the argument by reference, it happens that if Size==Capacity we clear the old memory that a[65] was pointing at before appending it.

I'm not sure if this problem can happen in ImVector too. If this is the case, probably something like this can fix it:
```c++
inline void                 push_back(const value_type& v)  {
    if (Size == Capacity) {
        const value_type v_val = v;
        reserve(_grow_capacity(Size + 1));
        Data[Size++] = v_val;
    }
else {
        reserve(_grow_capacity(Size + 1));
        Data[Size++] = v;
}
}    
```
Otherwise we can just pass the argument by value.

If this was not useful, sorry in advance... 😒 

P.S. I had constructor/destructor in my custom vector class: the issue I had was only reported by Valgrind (the program didn't crash).

**Comment by ocornut** [comment]
The correct fix would probably to test if `&v` lies between Data and Data+Size and Size == Capacity, to avoid the local copy otherwise. 

I think for now even though this is a legit issue if we wanted to mimic `std::vector<>`, imgui codebase doesn't rely on it and we could state this is a forbidden.

**Comment by Flix01** [comment]
I think that adding an assert would be too expensive in this case.

So it's OK for me, even if I don't think that the performance drop of deep copying an item (twice, but only when Size == Capacity) is very big... 

...well, it depends on the "grow capacity" strategy how often this occurs.

**Comment by ocornut** [comment]
> So it's OK for me, even if I don't think that the performance drop of deep copying an item (twice, but only when Size == Capacity) is very big...

No you are right it isn't, but I also use ImVector<> to store large structures (especially in my docking branch). I think I will want to revisit this topic once I decide if/how to rework ImVector to be more constructor/destructor aware, because at the moment we're not and some code is relying on it in dubious way (and the fix isn't trivial, sometimes we want to deep copy things, sometimes we don't).
