### ISSUE TITLE
Presumed memory leak in function ImLogToFile

### ISSUE THREAD

**Issue by Wallby** [ocornut/imgui#1584]
After running a static analysis tool on my project I noticed that on line 6595 inside the function 
`void ImGui::LogToFile(int max_depth, const char* filename)` memory is allocated in the statement `g.LogFile = ImFileOpen(filename, "ab");` which is never de-allocated.

**Comment by ocornut** [comment]
Could you post your static analysis report?
g.LogFile is closed both in `LogFinish()` (which is called in `End()`) and in `Shutdown()` so I believe this is an incorrect report.

**Comment by Wallby** [comment]
Right, I see. I believe it might be the `g.LogEnabled` variable which is getting it confused. My report is not much more helpful than my own description.

**Comment by ocornut** [comment]
I added some extra assets to convey the intent, I agree this code is a little odd and probably hard to track down for a static analyzer, in particular because we use `g.LogFile` for both created files and `stdout` the later we don't close. Might rework it. Out of curiosity which analyser are you using? Even if the report isn't so helpful I could refer to it if I attempt to make changes to silence it.

**Comment by Wallby** [comment]
I am currently trying out CppDepend (https://www.cppdepend.com/), which has a really rich feature set for tracking down structural issues such as dependencies.
