### ISSUE TITLE
Tabs on left?

### ISSUE THREAD

**Issue by bogdaNNNN1** [ocornut/imgui#1589]
Hey, i can't put tabs on the left side.. maybe you can help me. I'm using imgui.  
 I've uploaded the code of the tabs and the menu. Thanks and keep up with imgui 👍 
![screenshot_2](https://user-images.githubusercontent.com/36056169/35707820-efa8c7aa-07b3-11e8-88fc-6707512ad48a.png)
![image](https://user-images.githubusercontent.com/36056169/35707834-fce063ce-07b3-11e8-8464-e44656004036.png)

**Comment by ocornut** [comment]
Sorry but #1586

**Comment by Frionx99** [comment]
Ok.. Hold hold hold here.. buddy...  I get it you made something open sourced, but as a C++ developer. You can't just shit this reply. This shows you're unproffesional, not that you do a good thing. Man clearly isn't pasting because half of the stuff here can't even be pasted. Also, he's asking for help with something you made. if it was "How to cheat csgo pls help 2019 I need help" I would understand. But this is lack of interest and lack of support. I am referencing this the same way as overdev did on the other person (WHO DID NOT EVEN STATE IT WAS A CHEAT OR SHOWN IT WAS A CHEAT) got the same response. Just because we can't word replies as well as you can means you ban us? The fuck? Are you out of your mind? OPEN SOURCE.. LEARN WHAT IT MEANS... Anyone can use it for free. Not "because u use it for csgo i give ban hammer". That is a childish reply. I'm not looking forward to make skidded cheats. But knowning how to make it look different than A total shit bag would be helpful. I barely play csgo and just need to know how the hell I add an image in the background. Does that make me a cheater now?

**Comment by p1pS** [comment]
He's under no obligation to help you, even if it is open source. That's a service in its own right. I have no idea where this entitlement comes from- but he is no way, shape or form in debt to you, meaning he has the choice to help or not. He's made it clear that he's not willing to help people that have malicious and/or unethical intent. Respect that, and move on.
