### ISSUE TITLE
API Request: ImGui::PushID(wchar_t* WideString)

### ISSUE THREAD

**Issue by sherief** [ocornut/imgui#1590]
... and ImGui::PushID(wchar_t* WideStringBegin, wchar_t* WideStringEnd).

**Comment by ebachard** [comment]
Are you sure wchar_t is really OS agnostic ?

For the record, I found this link, with an interesting discussion about wchar_t portability :  https://stackoverflow.com/questions/4588302/why-isnt-wchar-t-widely-used-in-code-for-linux-related-platforms

**Comment by ocornut** [comment]
Well it doesn’t matter what we are hashing really, we could have a `void* start-end` range as well. 
It’s a little surprising because wide string don’t play really well in dear imgui land, often for string id if they aren’t literal strings they end up being displayed somehow.

@sherief do you mind clarifying your use case?
Do you need both functions or the later would do? (They are different, as the first one would need to be specialized to stop at the u16 zero terminator whereas the second one can use our existing code.)

**Comment by ocornut** [comment]
@sherief Any update on the later question, namely the fact that casting and usnig `PushID(const char* str_id_begin, const char* str_id_end);` will work just as well provided the end marker is not NULL. 

I have to be a little conservative here just because I'd prefer to not add extra entry points for one-off cases. Not excluding adding the `(const void*, const void*)` entry points (both PushID and GetID) to avoid the user casting there but it feels not strictly necessary.

The one parameter version `(const wchar_t*)` would be little more noisy internal wise, depending how much you already use those strings it may be acceptable to add a wstrlen() on your side? (Or you might even have a hash ready in which case you could even push the hash..)

**Comment by ocornut** [comment]
Closing this as answered and stale.

You can easily add this function in your sources, without modifying dear imgui sources, using:

```
void ImGui::PushID(const wchar_t* str_id_begin, const wchar_t* str_id_end)
{
    ImGuiContext& g = *GImGui;
    ImGuiWindow* window = g.CurrentWindow;
    ImGuiID seed = window->IDStack.back();
    ImGuiID id = ImHashData(str_id_begin, (str_id_end - str_id_begin) * sizeof(wchar_t), seed);
    window->IDStack.push_back(id);
}
```

With the namespace+function declaration in your header file.
