### ISSUE TITLE
Off-By-One-Pixel Issues in ImRect

### ISSUE THREAD

**Issue by JoshParnell** [ocornut/imgui#1615]
Version: 1.60WIP (pulled last night, February 12)
    Using SDL & GL2 unmodified impl test / Ubuntu 14.04.

Was noticing off-by-one pixel problems with detecting hover on rect elements. Dug into the rect code, found what struck me as some minor edge cases in ImRect. Have confirmed on my end that the following changes significantly improve hit detection of rectangular elements, most of which are now pixel-perfect to my eye (there are some special contexts with more complex layouts where there still appear to be off-by-one issues that were off-by-two+ before this change).

Apologies for not having a clue how to use git & pull requests and such :/

    /* imgui_internal.h : 324-326 / ORIGINAL */
    ImVec2      GetSize() const             { return ImVec2(Max.x - Min.x, Max.y - Min.y); }
    float       GetWidth() const            { return Max.x - Min.x; }
    float       GetHeight() const           { return Max.y - Min.y; }

As best I can tell, both the docs and the rendering code suggest that the rect is inclusive, meaning Min is indeed top-left and Max is bottom-right *in pixel space* (this is the key, if that's not correct then it's a happy coincidence that this fixed my issues). Hence, a box [1, 1] -> [3, 2] spans a 3 x 2 pixel area, not 2 x 1 (as best I can tell, the rendering code agrees, but it is difficult to follow since I am new to the codebase and dealing with pixel perfection is always a bear). So:

    /* imgui_internal.h : 324-326 / NEW */
    ImVec2      GetSize() const             { return ImVec2(Max.x - Min.x + 1.0f, Max.y - Min.y + 1.0f); }
    float       GetWidth() const            { return Max.x - Min.x + 1.0f; }
    float       GetHeight() const           { return Max.y - Min.y + 1.0f; }

Is the expected code for size of something measured in discrete rather than continuous units. This change alone helps, but also:

    /* imgui_internal.h : 331-333 / ORIGINAL */
    bool        Contains(const ImVec2& p) const     { return p.x     >= Min.x && p.y     >= Min.y && p.x     <  Max.x && p.y     <  Max.y; }
    bool        Overlaps(const ImRect& r) const     { return r.Min.y <  Max.y && r.Max.y >  Min.y && r.Min.x <  Max.x && r.Max.x >  Min.x; }

Here again we need to be careful and should be using inclusive checks on both sides due to dealing with discrete units (rects [1,1] -> [2,2] and [2,2] -> [3,3], for example, should be considered overlapping, and the point (2, 2) is overlapping either of them).

    /* imgui_internal.h : 331-333 / NEW */
    bool        Contains(const ImVec2& p) const     { return p.x     >= Min.x && p.y      >= Min.y && p.x     <=  Max.x && p.y     <=  Max.y; }
    bool        Overlaps(const ImRect& r) const     { return r.Min.y <=  Max.y && r.Max.y >=  Min.y && r.Min.x <=  Max.x && r.Max.x >=  Min.x; }

This made the most QOL difference for me with splitters and other such things that use invisible buttons (docking add-on in particular).

Apologies if I have misunderstood anything about the space in which layout is performed. I have done my best to verify that this only improves functionality and have found no cases where it causes problems, but again, I am new to the d-imgui world and it is possible that something else is going on with GL, drivers, AA, etc.

**Comment by ocornut** [comment]
Hello,

Thanks for the detailed report. 
Could it also be that your mouse cursor itself is off?

> As best I can tell, both the docs and the rendering code suggest that the rect is inclusive, 

So that's misleading. AFAIK there's no explicit mention of inclusive/exclusive but we could add some?

I tried to render 5x5 rectangles, also showing both Windows Native cursor and ImGui Software Cursor (confirmed both cursor are exactly aligned):

```
        ImGui::Begin("Test #1615");
        ImVec2 p = ImGui::GetCursorScreenPos();
        ImDrawList* draw_list = ImGui::GetWindowDrawList();

        ImRect r1;
        r1.Min = ImVec2(p.x + 10, p.y + 10);
        r1.Max = ImVec2(p.x + 15, p.y + 15);
        draw_list->AddRect(r1.Min, r1.Max, IM_COL32_WHITE);

        ImRect r2;
        r2.Min = ImVec2(p.x + 10 + 20, p.y + 10);
        r2.Max = ImVec2(p.x + 15 + 20, p.y + 15);
        draw_list->AddRectFilled(r2.Min, r2.Max, IM_COL32_WHITE);

        ImGui::Text("%d", r1.Contains(ImVec2(p.x + 10, p.y + 10)));
        ImGui::Text("%d", r1.Contains(ImVec2(p.x + 14, p.y + 14)));
        ImGui::Text("%d", r1.Contains(ImVec2(p.x + 15, p.y + 15)));

        if (io.KeyAlt)
            io.MousePos = r1.Max;
        io.MouseDrawCursor = true;
        ImGui::Text("m%d (at %.f,%.f)", ImGui::IsMouseHoveringRect(r1.Max, r1.Max), io.MousePos.x, io.MousePos.y);

        ImGui::End();
```

![image](https://user-images.githubusercontent.com/8225057/36202620-d3fe61e2-1184-11e8-8185-d703aa711fcf.png)

![rects](https://user-images.githubusercontent.com/8225057/36202626-d65b577e-1184-11e8-9ad5-ff1be9cfd95c.PNG)

So I think both `GetSize()`, `GetWidth()`, `GetHeight()` are what we want.
It's important to be exclusive on one side so that packed items (imagine some code handling interactions for a grid with no spacing between element) works properly.

As per this definition I think `ImRect::Contains(ImVec2)` is correct.
For `ImRect::Contains(ImRect)` (which you didn't mention), note this recent commit:
https://github.com/ocornut/imgui/commit/8bf0c89c0daa1189faccb7ff1c77d32180bf7bd7

For `ImRect::Overlap(ImRect)` I'm not sure exactly what's right, we don't have a clear definition (nor a need) for zero-size rectangles, but this seems alright to me. 
```
ImGui::Text("Overlap %d", ImRect(10, 10, 15, 15).Overlaps(ImRect(10, 10, 15, 15))); // true
ImGui::Text("Overlap %d", ImRect(10, 10, 15, 15).Overlaps(ImRect(14.99f, 14.99f, 15, 15))); // true
ImGui::Text("Overlap %d", ImRect(10, 10, 15, 15).Overlaps(ImRect(9, 9, 10, 10))); // false
ImGui::Text("Overlap %d", ImRect(10, 10, 15, 15).Overlaps(ImRect(10, 10, 10, 10))); // false
ImGui::Text("Overlap %d", ImRect(10, 10, 15, 15).Overlaps(ImRect(10, 10, 10, 10.1f))); // false
ImGui::Text("Overlap %d", ImRect(10, 10, 15, 15).Overlaps(ImRect(15, 15, 15, 15))); // false
```

> This made the most QOL difference for me with splitters and other such things that use invisible buttons (docking add-on in particular).

I would prefer if you clarified _this problem_ which is the problem you have. Essentially your change is equivalent to growing those shapes by 1 pixel. If 1 pixel makes a difference, the hit surface is probably too small in the first place or has an issue.

I've seen docking add-ons that had splitters that were tedious to use, because of subtleties with overlapping windows that were not handled correctly or changed across versions of imgui.

For example, my work in progress Docking code use SplitterBehavior (from imgui_internal.h) this way:

```
float HOVER_EXTEND = 4.0f; // Extend in both direction, so at minimum we are 8 pixels large
if (ImGui::SplitterBehavior(window->GetID("##Splitter"), bb, node->SplitAxis, &w1, &w2, min_size, min_size, HOVER_EXTEND))
```
The visuals and hit test are decorrelated, which is necessary for very thin items. The splitter cover a largish surface and then SplitterBehavior() uses ImGuiButtonFlags_AllowItemOverlap+SetItemAllowOverlap() to allow subsequent items to detect a hit if they overlap the splitter.

**Comment by JoshParnell** [comment]
Thanks very much Omar for the information!

Your test case + screenshots are elucidating and clear up for me the confusion about the coordinate system of imgui. So the coordinate system is such that, for example, full-screen would be the rect from (0, 0) to (res.x, res.y), in particular, it is *not* a 'pixel index' / pixel center coordinate system. Makes sense and I think that's the right choice! Sorry for the confusion, I retract the suggested changes above.

I will dig into it more today, but seems like it must be driver/os or potentially the SDL/gl2 backend, either way, not a core imgui problem :)

And yes, the docking addon I use (https://github.com/BentleyBlanks/imguiDock) is not doing the desirable thing for splitters as you outlined, making it frustrating at times to grab the splits. I am *very* much looking forward to your official docking impl!! So far every impl I've tried has a separate set of issues :|

**Comment by ocornut** [comment]
Correct :) Closing this as answered. Please don't hesitate to raise that sort of question in the future, it's often healthy as it often allows me to look into and clarify old issues.
