### ISSUE TITLE
Array accessing out of bound on MacOS X with Unicode IME

### ISSUE THREAD

**Issue by paladin-t** [ocornut/imgui#1618]
(With SDL backend)

https://github.com/ocornut/imgui/blob/024e23c4d701a943c91fb838c36c01270af8261d/examples/sdl_opengl3_example/imgui_impl_sdl_gl3.cpp#L181

`key` at this line is not always in the range between `0` to `countof(io.KeysDown)-1`:

![default](https://user-images.githubusercontent.com/2062224/36249751-a053da5a-1276-11e8-99a1-cd69cc366619.png)

I think the reason is that on OSX, the keycode is re-mapped by [`UCKeyTranslate`](https://developer.apple.com/documentation/coreservices/1390584-uckeytranslate), when a Unicode IME is actived:

https://github.com/SDL-mirror/SDL/blob/e465610bd49c983183ad1419895f5e8108a68ae2/src/video/cocoa/SDL_cocoakeyboard.m#L547

Adding guard code instead of assertion would solve the problem:

```
if (key >= IM_ARRAYSIZE(io.KeysDown))
	return false;
```

However Windows doesn't have this issue, but I'm not sure about other ones.

**Comment by ocornut** [comment]
Hello,

I should have clarified that since this is a recent change, but the SDL example were reworked recently to use scancodes everywhere.

In fact if you look closely at the code you linked to:
https://github.com/ocornut/imgui/blob/024e23c4d701a943c91fb838c36c01270af8261d/examples/sdl_opengl3_example/imgui_impl_sdl_gl3.cpp#L179
It differs from the code on you screen.
And there is an assert in that code now.

Also note that in `ImGui_ImplSdlGL3_Init()` we entirely fill the KeyMap[] array with SDL_SCANCODE_xxx values.

Perhaps try to update your copy of the backend first.
I should start adding a changelog to them..

**Comment by paladin-t** [comment]
Uh, I'm working with v1.53 right now, and will move on to new version till next stable release. Thanks for the information!

**Comment by ocornut** [comment]
You can grab the imgui_impl_sdl_gl3.cpp input code from current master, just remove the _Space key from the list. (1.60 WIP is fairly stable btw)

**Comment by paladin-t** [comment]
Great, as always you did! Close this issue if there's no more necessity of its existence.

**Comment by ocornut** [comment]
Closing. Onward e be adding changelog to the bindings to this type of issues it easier to spot.
Basically you want to apply this commit: 60fb7d31fde0dad94c48e5a2839acf09a10c5cf0

Onward I am also considering splitting the renderer (e.g. OpenGL) from the platform parts (SDL) so more code is reusable across back-ends, but there are subtleties that makes it not as trivial as it sounds.
