### ISSUE TITLE
Popup context void closes existing modal window

### ISSUE THREAD

**Issue by towerpark** [ocornut/imgui#1636]
Hello,

I'm using `BeginPopupContextVoid()` to make a context menu for 3D scene area that is not covered by any Imgui window. When there's already an Imgui model window popped up, I want to make the window prevent context menu from being created. `BeginPopupContextVoid()`, however, returns true no matter where you click except inside the modal window, and hence close the window and shows the menu. (`BeginPopupContextItem()` and `BeginPopupContextWindow()` don't.)

I'm using the newest version (master: 9c20a40), and you can simply add the following code to demo to reproduce it:
```
    if (ImGui::BeginPopupContextVoid()) {
        ImGui::Selectable("abc");
        ImGui::EndPopup();
    }
```  

Is this behavior by design?
Thanks for your great work.

**Comment by ocornut** [comment]
I confirm this is a bug, `BeginPopupModal()` essentially clear the internal `g.HoveredWindow` which makes `BeginPopupContextVoid()` think we never hovering anything.

The correct behavior should either be that `BeginPopupContextVoid()` always fails, or only work if it is being called with the modal below it in the window stack.

**Comment by towerpark** [comment]
Thank you for confirming this issue.
I will just close the context menu manually if a modal window has already been popped as a workaround for now.

**Comment by ocornut** [comment]
Pushed a fix for this today. I apologize for taking so much, in particular considering how simple the issue was.

As suggested in my first answer, I think we could potentially decide to make `BeginPopupContextVoid()` also work when clicking on the area made unavailable by a modal, but it would be a specific flag (I'm currently looking at popup functions and considering adding flags to them)
