### ISSUE TITLE
Show window only when mouse is over?

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#1647]
Hi,

How could I show a window (used as transport control) only when mouse is over it?

Thanks,
victor bombi

**Comment by ocornut** [comment]
I don't understand the question. Please clarify and explain the context.

**Comment by sonoro1234** [comment]
Having a transparent window that gets drawed only when mouse is over
I have tried
```
ig.PushStyleVar(imgui.ImGuiStyleVar_Alpha,0)
if ig.Begin("Transport",nil,imgui.ImGuiWindowFlags_NoTitleBar + imgui.ImGuiWindowFlags_NoResize) then
		if ig.IsWindowHovered(imgui.ImGuiHoveredFlags_RectOnly) then
			ig.PushStyleVar(imgui.ImGuiStyleVar_Alpha,1)
		end
```
But window mouse over is not detected with alpha==0

**Comment by sonoro1234** [comment]
alpha == 0.0001 works!! and it is almost invisible.
Still I would like the window to be visible and not only the items inside when style alpha changes.

**Comment by ocornut** [comment]
As you just found out, Alpha==0.0 clips elements at a higher-level.

> Still I would like the window to be visible and not only the items inside when style alpha changes.

Sorry I don't understand this sentence either.

**Comment by sonoro1234** [comment]
In the solution I tryed when alpha changes to 1 ( on ,ouse over ) it is applied only to the items that follow, but the window background remains transparent.

**Comment by ocornut** [comment]
> the window background remains transparent.

The window background is drawn by `Begin()`. Here you are querying IsWindowHovered() after Begin. You'll probably need to track state in your application to remember which window is hovered and apply that Alpha before Begin.

(This is because there's no way to use `IsWindowHovered()` on a different window than the current at the moment)

I have no idea what "transport window" mean. Please provide code and screenshots (as explained [here](https://github.com/ocornut/imgui/blob/master/.github/CONTRIBUTING.md)). It's hard to understand your use case right now, and I can't be spending time to guess what you want in order to help you. 

Popups inhibit inputs behind them. Check the flags for IsWindowHovered().

**Comment by sonoro1234** [comment]
![transporte](https://user-images.githubusercontent.com/1795930/36645330-37611690-1a67-11e8-89d8-45bbc8d00642.png)

when doing click on any item of this window  IsWindowHovered returns false and window dissappears. 

```
function transport:draw()
		
		local height = ig.GetItemsLineHeightWithSpacing() + ig.GetStyle().WindowPadding.y*2
		ig.SetNextWindowPos(ig.ImVec2(0, ig.GetIO().DisplaySize.y - height),0);
		ig.SetNextWindowSize(ig.ImVec2(ig.GetIO().DisplaySize.x,height),0);
		
		local numpops = 1
		ig.PushStyleVar(imgui.ImGuiStyleVar_Alpha,0.0001)
		
		if ig.Begin("Transport",nil,imgui.ImGuiWindowFlags_NoTitleBar + imgui.ImGuiWindowFlags_NoResize) then
			if ig.IsWindowHovered(imgui.ImGuiHoveredFlags_RectOnly) then
				ig.PushStyleVar(imgui.ImGuiStyleVar_Alpha,1)
				numpops=2
			end
	
			if ig.Button(play_but_text) then 
				transport.play()
			end
			
			ig.SameLine()
			ig.Text("(%05.1f FPS)", ig.GetIO().Framerate)
			
			ig.SameLine()
			if ig.Button("next") then 
				GL.timeprovider:set_time(GL.globaltime[0] + 1/GL.fps)
			end
			ig.SameLine()
			if ig.Button("prev") then 
				GL.timeprovider:set_time(GL.globaltime[0] - 1/GL.fps)
			end
			ig.SameLine()
			
			if ig.Button("save") then  save_image_browser.open() end
			save_image_browser.draw()
			ig.SameLine()
			
			if ig.Button("tools") then imgui.igOpenPopup("toolbox") end
			ToolBox(GL):draw()
			ig.SameLine()
			
			ig.PushItemWidth(-1)
			if ig.SliderFloat("", GL.globaltime, 0, GL.timeprovider.totdur, "%.3f", 1.0) then
				GL.timeprovider:set_time(GL.globaltime[0])
			end
			ig.PopItemWidth()
		end
		
		ig.End()
		ig.PopStyleVar(numpops)
	end
```

Thanks for your patience
victor

**Comment by ocornut** [comment]
According to this section of the Demo window, it should work with RectOnly:
![image](https://user-images.githubusercontent.com/8225057/36645570-37e96e56-1a6b-11e8-875a-c841fee6594a.png)

(you can try the demo)

RectOnly is a shortcut:
`ImGuiHoveredFlags_RectOnly = ImGuiHoveredFlags_AllowWhenBlockedByPopup | ImGuiHoveredFlags_AllowWhenBlockedByActiveItem | ImGuiHoveredFlags_AllowWhenOverlapped,`

Make sure your value for `ImGuiHoveredFlags_RectOnly` is the correct value that C++ imgui expects. Those define values change from time to time, if you have a language wrapper it should be using values from imgui.h.

(This is == 104 in current imgui.. maybe your back-end copied from values instead of reading them from imgui.h?)

**Comment by sonoro1234** [comment]
I am using cimgui.h for imgui 1.53 and the value is 52.

**Comment by ocornut** [comment]
It is == 52 with in imgui 1.53 you are right. 
Does that area of the Demo works correctly with your version? Click "Item" and check the value next to "AllowWhenBlockedByActiveItem".

Actually, the `ImGuiHoveredFlags_AllowWhenOverlapped` flag is not supported by IsWindowHovered() and therefore `ImGuiHoveredFlags_RectOnly` isn't either:
```
bool ImGui::IsWindowHovered(ImGuiHoveredFlags flags)
{
    IM_ASSERT((flags & ImGuiHoveredFlags_AllowWhenOverlapped) == 0);   // Flags not supported by this function
    ImGuiContext& g = *GImGui;
```
This shouldn't concern you here, but you should maybe only use `ImGuiHoveredFlags_AllowWhenBlockedByActiveItem`, depending on how you want this to work.

**Comment by sonoro1234** [comment]
Demo works ok.
I found error in cimgui implementation!!
Thanks

**Comment by ocornut** [comment]
Nice. Please report issue or a PR to the cimgui repo ideally :)
