### ISSUE TITLE
App with editor and runtime mode

### ISSUE THREAD

**Issue by hinxx** [ocornut/imgui#1654]
I'm wondering if there exists a project/app that uses Dear ImGUI and can act in two modes: editor and runtime. In editor mode one would be able to place widgets and define properties (similar to Qt UI Designer), then save the result in some (text). In runtime mode the saved text file is loaded and widgets instantiated. Ideally one could switch the modes on-the-fly or have multiple instances of the app, some in editor some in runtime mode..

**Comment by ocornut** [comment]
Hello @hinxx; it's not a simple question to answer. 

There's no such tool. But also it wouldn't make much sense to have one in the dear imgui ecosystem. The paradigm exist to simplify data binding and data synchronization. Widgets don't exist independently of your data and code. If you create a tool to setup layout/position, you still need a way to bind all those interactions with your actual data and code and the amount of glue may defeat the purpose of the library and put you back in a position similar to more traditional UI toolkits.

It's perfectly possible for a user of the library to build their own tool to edit layout info which would make sense if the tool also had a way to connect to whatever data structure you are making. In the current context, a generic tool wouldn't make as much sense imho.

That said, I think in the far future we would imagine a way to easy access stored position/size and use them in an otherwise very code-driven UI. But it's not really what you are asking/expecting at the moment.

**Comment by hinxx** [comment]
Thanks for explaining @ocornut. I'm still catching up on (Dear) ImGUI awesomeness hence the silly views.

My use case is that each 'widget' (label, field, checkbox) gets/sends data by interacting with the remote server, where application logic is. In my case UI would not contain any logic, only render what was obtained from server 'data' channel. There is user interaction, but changes are propagated to the server, too. Imagine a remote app that is reading temperature and controlling fan speed where i.e. temperature readout, status of the fan, fan speed would be 'data' channels to display information about. In real use case number of 'data' channels available is in thousands and hence the need to allow user to define and build a display as opposed to have to change C++ code to modify a display itself.

Users would be allowed to create (save, load, modify) their own displays (sets of widgets), and also specify data channel that would feed the 'widget' with fresh data. I would like to allow users to change other properties like position, size, color, font, .. of a given 'widget'.

Since I made this issue, I noticed ShowExampleAppPropertyEditor() in the demos. It is exactly what I imagined as an editing tool for users dealing with the 'widget's properties. After reading your answer I think I could even get away without having two distinct modes (edit, runtime), say by just poping up settings window if user clicks on the 'widget' while holding Alt key, for example. Changes would be noticeable instantaneously which sounds perfect. To retain the changes to the display definition would be stored in the file and loaded on user request.

**Comment by ocornut** [comment]
It seems like most of your work involve figuring out a communication protocol between your server and your client to expose the data types and the values on demand, and program an UI (driven by that data) for the user to browse, filter, edit values. That's all work on your side, so I am having a hard time really understanding what you expect of this issue/thread.

(Note that it's technically perfectly possible to run imgui directly on your server and send the vertices data through the wire to the client, so the client can be the equivalent of a dumb graphic terminal. This has various implications and is quite unusual. It may work perfectly for your use case or be completely not appropriate. If your server isn't shared by too multiple clients, and on the local network it may be appropriate. See e.g. https://github.com/JordiRos/remoteimgui for an implementation of this idea)

**Comment by hinxx** [comment]
> That's all work on your side, so I am having a hard time really understanding what you expect of this issue/thread.
I agree, I needed to get my bearings about how is it possible and if someone already tried something similar.

Remoteness of the UI is inherent to the server-client architecture of the control system I'm dealing with so I'm fine with that UI is dumb.

Thank you and feel free to close this issue.

**Comment by ocornut** [comment]
Cool :) let us know if you stumble on other things.
Hopefully the demo gives enough examples but dear imgui is sufficiently unusual compared to traditional retained-mode ui that it takes a bit of practice to clear out the confusion about what it is and what it does.
