### ISSUE TITLE
Column sizing becomes corrupted when window/region size becomes too small

### ISSUE THREAD

**Issue by JSandusky** [ocornut/imgui#1656]
When visible columns are resized to small extremes the scaling becomes brittle. In the demo it appears to always go to the extremes while in some live-code it looks like signs are wrapping around (columns start to size off into the wrong direction).

Reproducing:

- Make the columns examples in the Demo visible
- Resize the window to an extremely small size (ie. as small as it will go)
- Expand window back to a reasonable size

Image of results (from demo):

![imguirepro](https://user-images.githubusercontent.com/5519639/36935413-806169b4-1ec5-11e8-8a54-3090c5e10949.png)

**Comment by ocornut** [comment]
Oh wow, I think I broke something serious in my pass on columns (a few months ago). Will look at this at this is pretty bad.

**Comment by ocornut** [comment]
@JSandusky this should be fixed now. 

fyi @ggtucker: 
The OffsetNorm clamp introduced by #913 was ok as it didn't write back into the storage, which the refactor commit b016215c80f64fef17b8aaad843167c3c8d3855b (for #1499) started doing, making it a destructive operation. Right now I don't think the clamp is needed at all. It nicely hid the padding issue fixed by bf7481e, what else? You probably won't have an exact answer at the moment, but if you have a chance to update let me know if you find any regression in there.

**Comment by JSandusky** [comment]
Confirmed as fixed in my live-case and the imgui demo. Since you've referenced this from other issues I'll leave it to you decide when to close the issue.

**Comment by ocornut** [comment]
Closing this as solved.
(Been looking at columns a little to try to spec full-featured columns/table..)
