### ISSUE TITLE
[Feature request] Native support for wchar_t (and std::wstring)

### ISSUE THREAD

**Issue by data-man** [ocornut/imgui#1659]
This will be useful especially for Windows.

**Comment by ocornut** [comment]
Hello Dmitry,
This is unlikely to happen, but mostly I don’t understand why you would need this globally. Use of Utf-8 vs wchar_t has nothing to do with Windows. What are you trying to achieve that not doable or convenient using utf-8 strings?
You can easily convert utf-16 to utf-8 if you need it occasionally.

**Comment by data-man** [comment]
Hello Omar!
And thanks for the **great** library!
> This is unlikely to happen

Very sorry.
> Use of Utf-8 vs wchar_t has nothing to do with Windows.

Most system functions work with wchar_t (with suffix *W(...)).
> What are you trying to achieve that not doable or convenient using utf-8 strings?

When intensive work with strings, then converting strings strongly affects the performance.
In addition, I'm using a lot of libraries that work only with wstring.

**Comment by ocornut** [comment]
> Most system functions work with wchar_t (with suffix *W(...)).

But what is the overlap between the strings passed to Win32 functions and the strings passed to imgui? (Btw you can use the *A(...) variants if you need)

> When intensive work with strings, then converting strings strongly affects the performance.

I agree it’s undesirable. I am still not sure I understand the exact overlap between your use of wstring and the strings you use for imgui, since it is expected that many of your imgui stings would be sourced from literal constants.

We could in theory add a few helper calls like ImGui::Text() that would convert on the fly, but that would be very incomplete support. Adding wchar_t everywhere would essentially double the api entry count :/

**Comment by data-man** [comment]
>We could in theory add a few helper calls like ImGui::Text() that would convert on the fly, but that would be very incomplete support.
> ...
> Adding wchar_t everywhere would essentially double the api entry count

Yes, no need to increase the code.

Thanks!
I'm still going to bother you! :-)
