### ISSUE TITLE
Move ShowTestWindow function away

### ISSUE THREAD

**Issue by mmozeiko** [ocornut/imgui#169]
I'm trying to modify Imgui library without any dependency on C library (no strcpy/printf/.. & other friends) and I try to stay as close as possible to master version. But this test function gets in my way. And it is really not needed for apps using imgui. How about separating it?

One option would be to move it to separate file like "imgui_example.h". Other would be to put the code inside "#ifndef IMGUI_DISABLE_TEST_WINDOW". I'm OK with any option. Which one people would prefer? I can create pull request for any option.

**Comment by ocornut** [comment]
I am not sure how you are going to remove those dependency from the rest of the file though? Helpers like ImFormatString() are implemented using vsnprintf, etc.

I suggest the easiest would be to add a #define, IMGUI_DISABLE_TEST_WINDOW sounds good. I prefer not to add another file at the moment (may do at some point for other things and then example may be dragged out as well, but I'd rather not put a end-user in a situation when they cannot access the example for reference because they were removed by someone or themselves during integration). For both reason the define is preferable at the moment.

Out of curiosity why are you trying to remove those dependency? I'

**Comment by mmozeiko** [comment]
I will replace all std functions with macros similar to IM_ASSERT. For vsnprintf and similar functions I am using my own implementation to avoid differences between gcc and MSVC (%lld vs %I64d, %p, ...).

I'm trying to avoid dependency on C runtime because rest of my code doesn't use C runtime. Most of functions are trivial to replace (math & string stuff), and sometimes you can implement them more efficiently because you can use better SIMD instructions than generic case. It will be more painful to implement replacement for malloc/free because Imgui uses them as generic heap (I would prefer to pass preallocated buffer to Imgui and then it could manage it in whatever way it wants). But for now I'll simply allocate 1MB buffer and implement simple malloc/free replacements for Imgui to use this buffer.

Ok, I'll put #ifdef around ShowTestWindow functionality.

**Comment by ocornut** [comment]
I have merged it but made a subtle change.
In your version the ifdef are in imgui.h I have moved them to imgui,cpp
The function exists but they are empty. The reasons are:
- I want to keep imgui.h as sane as possible (avoid ifdef)
- Mainly I want to avoid tempting people who integrate the library to disable those functions. They are really useful as reference to the user, to be able to call ShowTestWindow() anytime for reference/demo. So by making the feature visibility a little less prominent it is less tempting.

ImGui shouldn't allocate in the main loop if you don't interact or add new stuff, so it's only allocating to "grow". But yeah, otherwise it'd be too much work to handle managing allocation on the library side.

Out of curiosity which is your implementation of vsnprintf() ? I don't think the subtle difference between gcc and msvc matters, but I've always wanted to use a more customized and optimal vsnprintf for imgui and other projects, and never took the time to find or write one.

**Comment by mmozeiko** [comment]
Yeah that is fine.

For vsnprintf I'm using this one: https://github.com/weiss/c99-snprintf
It doesn't have wchar_t support but I have no need for it (utf-8 for everything!). And if you don't include locale support (HAVE_LOCALE_H, HAVE_LOCALECONV) it doesn't depend on any C runtime function.

A bit problematic for memory management are few globals used in Imgui: GImDefaultState, GDefaultFontAtlas and draw_list (in Render). I want to manage memory myself using MemAllocFn/MemFreeFn functions, so they will reference my memory manager. I must be sure my memory manager is alive when these three objects are destroyed. The problem is these objects are destroyed after main exits from global C++ destructor list. And as we all know order in which global constructors and destructors are called is unspecified. So if my memory manager is already destroyed, everything blows up...  Currently I'm using Imgui for debugging so I don't care about freeing memory on exit, I can simply do no-op when memory from Imgui is freed. Not nice, but it works. I think fixing it will involve making some kind Init function for Imgui that will initialize memory hooks and allocate global memory. And updating Shutdown function to free all the memory (also for globals).

**Comment by ocornut** [comment]
It could be fixed by making sure Shutdown() calls everything in GImDefaultState and GDefaultFontAtlas to free heap memory. So by the time the destructor run nothing is left to free.

**Comment by ocornut** [comment]
Freeing 5 more allocations that were previously left to destructor.

**Comment by ocornut** [comment]
I tried putting a breakpoint on free() after ImGui::Shutdown() and didn't find a call that came from an ImGui destructor now.

**Comment by mmozeiko** [comment]
Awesome! That is much better. Thanks.

**Comment by mmozeiko** [comment]
Code doesn't compile if IMGUI_DISABLE_TEST_WINDOWS is defined. This fix is needed:
https://github.com/mmozeiko/imgui/commit/4f6119fdd2c51fedfa9c0bc17a618edab9725190

**Comment by ocornut** [comment]
My bad sorry, should have tested.
