### ISSUE TITLE
Why do childs have _<id hash> appended in their name?

### ISSUE THREAD

**Issue by franciscod** [ocornut/imgui#1698]
(not an issue, more of a question)

Just noticed named child windows are windows called "<parent_name>/<child_name>_<child_id>".

Why is the hexa representation of the id (`window->GetID(str_id)`) required at the child window name? Isn't parent_name/child_name enough? (Why?)

**Comment by franciscod** [comment]
(I get it on the anonymous child case)

**Comment by ocornut** [comment]
Good question @franciscod, I looked into it and the commit history and couldn't find any valid reason for doing that, so I changed it. Thanks!

**Comment by franciscod** [comment]
Wheeeee, glad I asked it :D You're welcome!

**Comment by jadwallis** [comment]
I think the ID hash might be necessary for child windows to respect the ID stack. Consider the following example:
```
for (int i = 0; i < 4; ++i)
{
	ImGui::PushID(i);
	ImGui::BeginChild("foo", ImVec2(100, 100), true);
	ImGui::Text("bar %d", i);
	ImGui::EndChild();
	ImGui::PopID();
}
```

I'd expect that to create four separate child windows, since although the child windows share a name they are each in their own ID scope. Instead, currently* the above code comes out like this:
![image](https://user-images.githubusercontent.com/31036241/46089199-e75a0080-c1a5-11e8-85be-fdc8d7a5272d.png)

If I revert 84fbc49 then it looks like I'd expect:
![image](https://user-images.githubusercontent.com/31036241/46089296-1a03f900-c1a6-11e8-80b3-8e9f9930d132.png)

Is my expectation of how this code should behave wrong, or is the original code actually useful after all?

*I'm currently on revision d69b2a1 (v1.63 WIP from 1st August 2018), but I don't think this particular code has changed since then from a quick look.

**Comment by ocornut** [comment]
Thanks @jadwallis.
You are right and this is indeed a breaking change.
I think the change _might_ be acceptable as is however, because you can always use `BeginChild(GetID("blah")...);` if you need the unique ID scope.

Additionally, there are two other documentation issues:
- The change was documented as part of 1.53 where in reality it was part of 1.60 (it was a mistake when I added the line in the Changelog).
- If it stays as such (give me some time to think about it and decide) it should be documented as a breaking change in 1.60.

**Comment by ocornut** [comment]
@jadwallis I have now undoed the change done in 84fbc4940, it was an error on my part. Thanks for pointing it out. The change was explicitly introduced in 1.50 (see #894, #713) and accidentally reverted following the discussion on this thread. It should now be fixed again. My bad!

**Comment by jadwallis** [comment]
Thanks @ocornut! :)
