### ISSUE TITLE
Add a color flag for symbols

### ISSUE THREAD

**Issue by aiekick** [ocornut/imgui#1706]
I need to have a color for symbol, like triangle or bullet different of text, for this particular theme i use :

![sdfmesher_msvc_x64_debug_2018-03-28_23-37-47](https://user-images.githubusercontent.com/1434736/38057872-17c7370a-32e1-11e8-9fb0-db6737153ba6.png)

because the white color with orange bg is not readable, so i need different color for text and symbol in this particular theme.

but i think, this color flag for symbol may be cool and not useless :)

for the moment i have created a color flag "ImGuiCol_Symbol" i used in the two function : 
* RenderTriangle
* RenderBullet

because for the moment the color used for symbol is the color flag of the text.

what do you think of it ?

**Comment by ocornut** [comment]
I think the request (_as you define it_) is undesirable, Your picture shows the word "Console" in black and that suggests that the change you/we want has nothing to do with Symbols, but rather being able to redefine the main text color depending on the background color.

This is discussed in #1223, #511, #1055 

I apologize that I've been delaying this, I believe the style/coloring system needs a focused rework rather than incremental addition of extra enums because the addition of new enums may never end _and_ has the unobvious side-effect that it would actually break code.

If I naively add e.g. `ImGuiCol_ButtonText` then `PushStyleColor(ImGuiCol_Text)` here would break. While I'm not against occasional breakage, the amount of possible enums would potentially skyrocket. My intended solution is to have an implicit inheritance tree, where undefined colors inherit from their parent. I may be able to tackle that in the following few months, in the meanwhile you'll need to either use PushStyleCol(ImGuiCol_Text), either use background colors that are usable with the same single text color, add patch your local copy of imgui adding ImGuiCol_ButtonText, ImGuiCol_HeaderText, etc.

**Comment by aiekick** [comment]
i not speak baout the text color, but about what i suppsoed to be a symbol.

here the triangle in the combo. if i define a text color as white, the text in the combo with gray bg will be white ( ok) but the traingle on the bg orange will be also white and here its my problem.

so i have defined a color flag for symabol, like that i can separate text and symbols :)

i have not the problem for button, i modified the color with a pushStyleColor, but for combo, he cant work as i explained because, the color falg use for render triangle is the text color flag :)

**Comment by ocornut** [comment]
> i not speak about the text color, but about what i supposed to be a symbol and not a char.

We are trying to avoid this distinction as icon fonts are commonly used. You can see in your screenshot that you have exactly the same problem with the word "Console" and you manually solved it with PushStyleCol.

> Here the triangle in the combo. if i define a text color as white in the combo, the text in the combo with gray bg will be white ( ok) but the traingle on the bg orange will be also white and here its my problem.

I understand, but your problem is that you want to change the color used when displaying something over the orange/button background. Your problem is unrelated to "symvols". `ImGuiCol_Symbol` doesn't solve the problem in a general manner since you could have a different background for headers and for buttons and then which color should symbol uses?

> i have not the problem for button, i modified the color with a pushStyleColor, but for combo, he cant work as i explained because, the color flag used for render triangle is the text color flag :)

You are offering to solve half of the problem for a certain use case and leave other use cases either unsolved either requiring manual intervention. I'm just saying we need to solve this in a more general way, and will solve it eventually.

**Comment by aiekick** [comment]
ok ok :)

**Comment by ocornut** [comment]
Closing this now. It's a useful use case to keep in mind when redesigning the colors/styles system. Thanks!

**Comment by aiekick** [comment]
maybe you can define a function callback pointer of the method RenderBullet and RenderArrow. like that we can implement our function ?

**Comment by aiekick** [comment]
in fact the other issue i opened some days ago (https://github.com/ocornut/imgui/issues/3798) is related to this (i forgot the original post haha)
