### ISSUE TITLE
directx10 example drawing font error

### ISSUE THREAD

**Issue by codz01** [ocornut/imgui#1733]
Hi
i just noticed that directx10 example has a font drawing error after resize the window 
note that it doesn't happen if i use the default embedded font , but only if i load it from file .
try uncomment the line (io.Fonts->AddFontFromFileTTF("../../misc/fonts/DroidSans.ttf", 16.0f);)
then resize the window ,  you'll get this 
![imgui](https://user-images.githubusercontent.com/10813427/38472505-e54c67dc-3b78-11e8-83dd-c40526b150b9.png)

**Comment by ocornut** [comment]
The reason it crashes it that the DX10 back-end still have a call to `Fonts->ClearInputData()`. Even though removing this line would fix the example (and I will remove this line), there's a more general issue to fix.

This is related to #1731

With the current code is creates a discrepancy between the Fonts[] array keeping hold old fonts and the source `ConfigData[]` between emptied. Looking into it.

**Comment by ocornut** [comment]
OK so it's not that bad, basically in 6cee2fca94ff308762d0d183cd93ddb62bf40435 I removed this call every back-end but accidentally left in the DX10 back-end. It would create an extra copy of the CPU-side ImFont on every rebuild of the texture and that array would grow. It isn't noticeable with the default font because all our copies of the fonts are perfect match (so old UV matches new UV).

The reason it's not that bad is that this `ClearInputData()` in the other example is so old I don't imagine many would have it in their copy nowadays. Right now if you call some of the individual ImFont functions manually you can screw yourself over but there's nothing surprising here. I may rename/obsolete those functions later, as supporting DPI and dynamic atlas will want the input data to stay CPU side. Those functions are mostly for low-end devices to free RAM if they know the font isn't going to change any more.
