### ISSUE TITLE
First time with imgui

### ISSUE THREAD

**Issue by lostspirit1** [ocornut/imgui#1762]
I created a project with imgui archives
but i got this error :  
Severity    Code    Description    Project    File    Line    Suppression State
Error    LNK2019    unresolved external symbol _WinMain@16 referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)    Img    C:\Users\Spirit\Pictures\imgui-master\MSVCRTD.lib(exe_winmain.obj)    1

please help .

**Comment by ocornut** [comment]
Hello! Sorry this question/problem isn’t really related to dear imgui at all. Look it up and the internet, and if you ask that sort of question elsewhere you need to provide people with more information (which compiler, maybe a zip of your project?).

**Comment by lostspirit1** [comment]
i use visual studio 
sorry  
this is my zip 
[imguispirit.zip](https://github.com/ocornut/imgui/files/1934246/imguispirit.zip)

**Comment by smourier** [comment]
I hit the same error and for information, this is probably due to the fact you had created a Windows project instead of a Console project using Visual Studio. A Windows project expects a `WinMain `implementation (while a Console expects a `main`).

The easiest way to fix this is to add the following to the end of your file:

```
int APIENTRY wWinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPWSTR lpCmdLine, int nCmdShow)
{
    main(0, NULL);
}
```
