### ISSUE TITLE
Load image with Vulkan

### ISSUE THREAD

**Issue by zuEE** [ocornut/imgui#1764]
Version/Branch of Dear ImGui:  v1.60 WIP

I'm trying to load an icon image with stb_image lib to make a imageButton, but I  don't know what to pass to the creation function as texture_id parameter.

I try to use the raw image data returned by stbi_load function but failed, I try to use VkImage, VkImageView and VkDeviceMemory data but all failed.

The original image will be like this:
![image](https://user-images.githubusercontent.com/16697607/39086835-e7127ffa-45ca-11e8-9f12-a2cb4b51808d.png)

The result I got is:
![image](https://user-images.githubusercontent.com/16697607/39086808-8ae6ab16-45ca-11e8-8405-d33691369b77.png)

I've read the demo file but I still don't understand what to pass.

I've read the imgui_impl_glfw_vulkan file but I got 
"// Missing features:
//  [ ] User texture binding. Changes of ImTextureID aren't supported by this binding! See https://github.com/ocornut/imgui/pull/914
"

I'm sorry that i am new to both vulkan and imgui, I would appreciate that if anyone can help me.

**Comment by ocornut** [comment]
> The result I got is:

This is the imgui font atlas scaled down.

As noted in the comment you noticed under "Missing features", the Vulkan binding doesn't currently support changing textures in the rendering loop so everything is drawn using the imgui font atlas.

It's actually a very rather change, but we couldn't agree on which way/type to use and this issue has been stalled forever because of that. 

See https://github.com/ocornut/imgui/pull/914 for the discussion, you may merge the commit/branch from #914 to get the feature (which uses `VkDescriptorSet` here), or use whatever type makes more sense in your code base.

**Comment by zuEE** [comment]
Thanks for helping ^ ^
