### ISSUE TITLE
Drag and drop target does not work properly when the target is a window.

### ISSUE THREAD

**Issue by SSStormy** [ocornut/imgui#1771]
**Version/Branch of Dear ImGui:**
master, 7b6b7038

**My Issue/Question:**
I'm in a situation where I need to have an entire window accept a drag&drop target. What I've tried is calling `BeginDragDropTarget()` immediatelly after `End()` but in that situation `BeginDragDropTarget` returns false.

Repro code (note that the dnd sources are the windows themselves):

```cpp
void DndBegin(const char* label)
{
    using namespace ImGui;

    Begin(label, 0, ImGuiWindowFlags_NoMove);

    if(BeginDragDropSource())
    {
        SetDragDropPayload("window", label, sizeof(const char*));
        TextUnformatted("Window");
        EndDragDropSource();
    }
}

void DndEnd()
{
    using namespace ImGui;
    
    if(BeginDragDropTarget())
    {
        const ImGuiPayload* payload = AcceptDragDropPayload("window");
        EndDragDropTarget();
    }
    End();
}

void DndTest()
{
    DndBegin("wnd 1");
    DndEnd();

    DndBegin("wnd 2");
    DndEnd();

}
```

![animation](https://user-images.githubusercontent.com/10726335/39169385-2007fdae-4787-11e8-883d-e522911c5983.gif)

I did find a workaround by using window children. Immediatelly after `Begin`, I'd call `BeginChild`. Then just before calling `End()`, I call `EndChild` and `BeginDragDropTarget` returns true and I can access the expected payload.

Hacky code:
```cpp
void DndBegin(const char* label)
{
    using namespace ImGui;
    Begin(label, 0, ImGuiWindowFlags_NoMove);
    BeginChild("abc");

    if(BeginDragDropSource())
    {
        SetDragDropPayload("window", label, sizeof(const char*));
        TextUnformatted("Window");
        EndDragDropSource();
    }
}

void DndEnd()
{
    using namespace ImGui;
    
    EndChild();
    if(BeginDragDropTarget())
    {
        info("begin target");
        const ImGuiPayload* payload = AcceptDragDropPayload("window");
        if(payload)
        {
            info("accepted");
        }

        EndDragDropTarget();
    }
    End();
}

static inline
void DndTest()
{
    DndBegin("wnd 1");
    DndEnd();

    DndBegin("wnd 2");
    DndEnd();

}
```

![animation2](https://user-images.githubusercontent.com/10726335/39169467-72ba1730-4787-11e8-9ae4-a720b8a404eb.gif)

I'd like to know if this is something that can be fixed any time soon. 
Thanks.

**Comment by ocornut** [comment]
Hello,

`BeginDragDropTarget()` uses the last item in the current window, so while a `BeginChild`/`EndChild` pair counts as an item from the parent window point of view, this is not the case with `Begin/End`.

The fact that BeginDragDropSource() works at all is a little accidental here, Begin() is supposed to setup information for an item corresponding to the title bar (so it is possible to detect hovering/click on the title bar or query its bounding box), but the code in Begin() actually does `window->DC.LastItemId = window->MoveId;` which allow the drag source to function (drag source doesn't rely on the bounding box, it only checks the ID).

Depending on what you are trying to do you may be able to use e.g. `Dummy` or `InvisibleButton` in the target window followed by `BeginDragDropTarget()`.

Otherwise you can use:
```
#include "imgui_internal.h"
IMGUI_API bool BeginDragDropTargetCustom(const ImRect& bb, ImGuiID id);
```

If you are trying to build a docking system, be mindful that there are several of them (see https://github.com/ocornut/imgui/wiki) and I am working on an official one, which I hope to move to a public branch this quarter.

**Comment by SSStormy** [comment]
Thank you for linking me to the wiki. I was working on a tiling window system but after a quick look at the wiki I realized Flix01's [imguidock](https://github.com/Flix01/imgui/tree/2015-10-Addons/addons/imguidock) suits my needs.

The issue has been resolved on my end.
