### ISSUE TITLE
ImGui::Image with GL_TEXTURE_RECTANGLE

### ISSUE THREAD

**Issue by hateom** [ocornut/imgui#1779]
Hi,

Is there a way to draw a rectangle texture using ImGui::Image?
I think I need to create custom UserCallback for that?
Any tips?

Thanks.

**Comment by ocornut** [comment]
I am not sure what `GL_TEXTURE_RECTANGLE` is in OpenGL world, and how it differs from `GL_TEXTURE_2D` and if it is compatible. If it works the same as `GL_TEXTURE_2D` for the shader you use then you should be able to use them with `ImGui::Image()`, `ImDrawList->AddImage()`, etc.

Please see the examples and read about ImTextureID if you are not sure how it works (which is basically an opaque type passed to your renderer).

**Comment by ocornut** [comment]
If you can way a way with OpenGL to query the texture type from the texture ID you should change the renderer to do it.

Otherwise you can just add a callback to change the texture type, and change the renderer accordingly.
So your renderer instead of doing:
`glBindTexture(GL_TEXTURE_2D, (GLuint)(intptr_t)pcmd->TextureId);`

Would do:
`glBindTexture(g_CurrentTextureType, (GLuint)(intptr_t)pcmd->TextureId);
And you use callback to change that value.

**Comment by hateom** [comment]
Looks like there's one more problem.
One more difference in the shader program.
Instead of Samler2D it needs to be Sampler2DRect... So trying to also modify the shader now.

**Comment by ocornut** [comment]
Closing this now. You can tweak the renderer and use callback however you see fit.
