### ISSUE TITLE
Change font at runtime

### ISSUE THREAD

**Issue by kolyden** [ocornut/imgui#181]
I need to customize my editor, something like standard font selection dialog.
Trying to loading fonts at runtime, but failed.

Do I need to call GetTexDataAsRGBA32 and create texture after AddFontFromFileTTF?
Where is the place I can load new font, does it legal between ImGui::NewFrame() and Draw?
What is the best way to do that?

**Comment by ocornut** [comment]
If you want to load new fonts without corrupting your render for a frame, you need to do it between Render() and NewFrame().
If you delete/replace fonts during the frame you need to immediately call SetFont() with the new font pointer else ImGui will have a dangling pointer (*).

You can call .e.g io.Fonts->Clear(), io.Fonts->AddFont***, io.Fonts->GetTexDataAsRGBA32().
Everytime you call Clear() ot AddFont***() functions the texture data will be invalidated and rebuild the next time you call GetTexDataAsRGBA32().


(*) I will make it so that Fonts->Clear() actually clear that ImGui pointer so you'll get a more obvious crash.

**Comment by ocornut** [comment]
I have realised that SetFont() isn't exposed so you can't delete fonts during the frame (you can however change font, just not delete the default one).

**Comment by kolyden** [comment]
Thanks for the answer, now everything works perfect.
But SetFont is static private in imgui.cpp is it subject to change or other workaround?

**Comment by ocornut** [comment]
Well, you should not need it if you change delete old font between Render and NewFrame which is the only correct timing to do it to guarantee no graphic glitch  
Do you presently need SetFont() ?

Note there is a PushFont / PopFont API and you can perfectly *change* between loaded font during the frame and use multiple fonts. What you can't do presently is to delete or new load font during the frame.

**Comment by kolyden** [comment]
Ok. Move code in between Render and NewFrame is appropriate solution.

**Comment by ocornut** [comment]
Good. Closing this now. In the future we could have a dynamic font cache like fontstash ( https://github.com/memononen/fontstash ), among other things that would make it easier to just zoom things dynamically.
