### ISSUE TITLE
What does these magic numbers mean in DirectX11 exmaple

### ISSUE THREAD

**Issue by isbdnt** [ocornut/imgui#1849]
in examples/directx11_example/imgui_impl_dx11.cpp, I dont know what these magic numbers mean. I replaced them by 0, and it seemed everything was still working well.
original:
![image](https://user-images.githubusercontent.com/26591233/40820910-02b55bde-6596-11e8-952a-d4d2ea1c9807.png)
![image](https://user-images.githubusercontent.com/26591233/40820919-0d78036e-6596-11e8-8865-321b8c500c11.png)
![image](https://user-images.githubusercontent.com/26591233/40820922-153562ea-6596-11e8-8c82-674065d49394.png)
replaced:
![image](https://user-images.githubusercontent.com/26591233/40820965-4e16a826-6596-11e8-976e-e12096b347e1.png)
![image](https://user-images.githubusercontent.com/26591233/40820949-337dfab4-6596-11e8-9e1c-55f15afe05fe.png)
![image](https://user-images.githubusercontent.com/26591233/40820954-3b8258d6-6596-11e8-938d-b997c40cceee.png)

**Comment by ocornut** [comment]
Hello,

We are allocating more than the currently needed size, so we don't have to allocate again so often. This is a classic cost amortizing strategy. If you create the buffer exactly for the needed size, on the following frames if the number of polygon increase by even 1 triangle you will need to recreate the buffer. By allocating a bunch ahead, we made the buffer recreate a much rarer occurrence.

For example, `std::vector` implementation typically allocate x1.5~x2.0 ahead of the current size if `push_back()` needs an allocation, to avoid repeated allocation and copies. It needs to be more aggressive than we are with pre-allocating because functions like push_back() and often frequently called, and copy are expensive. This is also why it's recommended to call `reserve()` ahead on a vector, to avoid this extra work.

**Comment by isbdnt** [comment]
Thanks, makes total sense.
