### ISSUE TITLE
ImGui::getFramecount() gives continous increasing integer??strange?!

### ISSUE THREAD

**Issue by coderboyisongithub** [ocornut/imgui#1855]

**Comment by ocornut** [comment]
That’s what the frame count is, it increase every frame.

**Comment by coderboyisongithub** [comment]
But I remember that it returned frame per second.

**Comment by ocornut** [comment]
It never did, you must be mistaking it with Framerate.

There's a field in the IO structure `float io.Framerate` that gives an indication of Framerate (rolling average over the last 120 frames), based on the values provided every frame in IO.DeltaTime. `1.0f/io.Framerate` would give you the average DeltaTime over those last 120 frames.

Instead of saying "strange?!" please state what you expect when reporting a bug. This is fourth issue you are submitting without respecting the issue template, in spite of being asked. This is your last warning, you will be blocked next time. It is harsh but it is harsher for me to be on the receiving end.
