### ISSUE TITLE
Combo Box does not work with Modal (or any) Popups

### ISSUE THREAD

**Issue by wrinch** [ocornut/imgui#1865]
ImGui Version: v1.61
Backend: DirectX11 sample (as well as our own DirectX12)

It seems if I create a popup (modal or otherwise) I cannot use a combo box in the popup.  Clicking the down arrow on the combo box flickers for a frame and then disappears.  This works just fine with a regular window.

Thanks so much for writing ImGui by the way!  It's great!  I'm going to get our company to send you a donation here soon, as looks like we will be using ImGui more and more.

Cheers,

-Steve

```
ImGui::OpenPopup("BrokenComboBoxes");
if (ImGui::BeginPopupModal("BrokenComboBoxes", nullptr, 0)) {
	static int loggingLevel = 0;
	static const char* logLevels[] = {
		"Trace",
		"Debug",
		"Info",
		"Warn",
		"Error",
		"Critical"
	};
	ImGui::Combo("Logging Level", &loggingLevel, logLevels, IM_ARRAYSIZE(logLevels));
}
ImGui::EndPopup();
```

<img width="947" alt="brokencomboboxes" src="https://user-images.githubusercontent.com/23868468/41052550-edcd46a6-696d-11e8-8808-42e22fa79129.png">

**Comment by wrinch** [comment]
Gah, OK, I fail,

I didn't realize that I shouldn't call the OpenPopup all the time.  This code works just fine:

```
static bool opened = false;
if (!opened) {
	opened = true;
	ImGui::OpenPopup("BrokenComboBoxes");
}	
if (ImGui::BeginPopupModal("BrokenComboBoxes", nullptr, 0)) {
	static int loggingLevel = 0;
	static const char* logLevels[] = {
		"Trace",
		"Debug",
		"Info",
		"Warn",
		"Error",
		"Critical"
	};
	ImGui::Combo("Logging Level", &loggingLevel, logLevels, IM_ARRAYSIZE(logLevels));
	ImGui::EndPopup();
}

```

**Comment by ocornut** [comment]
This is a common mistake unfortunately.

As part of #1497 I actually had introduced a measure to alleviate the issues caused by this, and it was incomplete. I have now pushed a fix that will also prevent the child popups from being closed. (See commit above to understand). So you actually reported a bug :) Thanks!

The thing is, it is useful to call `OpenPopup()` again (the most common use case being that right-click context menus are typically reopened when you right-click again) and that means closing the child popups. So we have a special case were we catch when the user calls it every frame.
