### ISSUE TITLE
TreeNode double clicked

### ISSUE THREAD

**Issue by SuperWangKai** [ocornut/imgui#1872]
I found we can use `ImGui::IsItemClicked()` to handle tree node clicked event. Can we handle mouse double click event on the tree node? (e.g double click on the tree node to open the file related to it)

Edit: should we have `ImGui::IsItemDoubleClicked()` function?

**Comment by ocornut** [comment]
This is IsItemClicked():

```
bool ImGui::IsItemClicked(int mouse_button)
{
    return IsMouseClicked(mouse_button) && IsItemHovered(ImGuiHoveredFlags_Default);
}
```

Therefore you can easily call IsMouseDoubleClicked() && IsItemHovered().
The problem is that as is, a tree node will unfold on the first click.

**Comment by SuperWangKai** [comment]
Thanks, that solves my problem. IMHO, I still think we can have IsItemDoubleClicked. It will be IsItemDoubleClicked returns true and also the tree node toggled. There is still no logic confliction.

**Comment by SuperWangKai** [comment]
Since there is a solution I would like to close this issue.

**Comment by ocornut** [comment]
> IMHO, I still think we can have IsItemDoubleClicked.

Hmm, at the moment I'd prefer to resist adding many extra API entry points. We have reusable and combinable blocks so that may be enough for now? May reconsider this later. For now I'll add a comment to `IsItemClicked()` in the header file to suggest that it is no other than a shortcut to `IsMouseClicked() && IsItemHovered()` so it would be more understandable that you could dig one level lower (and merely 2 obvious calls instead of 1) to get extra flexibility.
