### ISSUE TITLE
Selected / Highlighted TreeNode

### ISSUE THREAD

**Issue by Extrawurst** [ocornut/imgui#190]
spin off issue of: https://github.com/ocornut/imgui/issues/189#issuecomment-91229101

using `TreeNode` for a tree structure and Bullet()+Selectable() for the leafs leaves open the possibility to highlight the currently selected TreeNode aswell.

**Comment by ocornut** [comment]
FYI I have never answered to that (but I think we have discussed it).
The problem here is simply that how the API is constructed I can't add an additional flag. I'm gathering other tree related request and we might introduce a new entry point in the feature to provide for how other features (e.g. a way to specify how to size the hit-box to cater for full-width hitbox vs small hit-box and other items on same line, and the equivalent of ImGuiSelectableFlags_SpanAllColumns).

For now you can essentially render a background yourself prior to calling TreeNode() using something like,
```
ImVec2 pos = ImGui::GetCursorScreenPos();
ImU32 col = ImColor(ImGui::GetStyle().Colors[ImGuiCol_HeaderHovered]);
ImGui::RenderFrame(pos, ImVec2(pos.x + ImGui::GetContentRegionMax().x, pos.y + ImGui::GetTextLineHeight()), col, false);
```

Here I am using the internal API RenderFrame() which is a glorified version of draw_list->AddRect(). Doing this reminded how the current color types/api are very inconsistently messed up and need rework. Essentially the internal helper window->Color() need to be made public somehow.

**Comment by krys-spectralpixel** [comment]
Thanks,

But how to detect the mouse click on the TreeNode ?

**Comment by krys-spectralpixel** [comment]
Hi,

I need a tree with selectable nodes. The current tree does not allow this. I have try using "Selectable+Indent" as leaf and normal tree node for inner nodes but:
- only the selectable are "selectable"
- the selectables (even with Indent) are not well aligned with the tree node.

So, I think to create my own TreeNode like widget, here is my current code:

bool SelectableTreeNode(const char* label, bool isSelected, bool hasChildren)
{
	// Selection
	if (isSelected)
	{
		ImU32 col = ImColor(ImGui::GetStyle().Colors[ImGuiCol_HeaderHovered]);
		/*x += os.x;
		y += os.y;
		ImGui::RenderFrame(ImVec2(x, y), ImVec2(x + itemFullWidth, y + itemFullHeight), col, true, 3.f);
		x -= os.x;
		y -= os.y;*/
	}

	ImGui::PushID(label);
	const bool opened = ImGui::CollapsingHeader(label, "", false);
	ImGui::PopID();

	if (opened)
		ImGui::TreePush(label);

	return opened;
}

But how can I :
- know the area of the treenode (see RenderFrame)
- Hide the Triangle/Arrow based on the "hasChildren" parameter

Any idea ?

**Comment by krys-spectralpixel** [comment]
About the double click, the following code does not work very well, I don't know why ?

if (hovered && ImGui::IsMouseDoubleClicked(0))

**Comment by ocornut** [comment]
Yeah, following your post in #431 i was about to suggest the best way is to make a copy of the code and modify it (but you'll have to maintain that).

Note that here you can remove PushID/PopID, and the str_id parameter just use label, that would well in this situation.



> About the double click, the following code does not work very well, I don't know why ?
> if (hovered && ImGui::IsMouseDoubleClicked(0))

Could you clarify how it doesn't work very well?

**Comment by krys-spectralpixel** [comment]
It looks random, even the tree selection sometimes looks random !

**Comment by ocornut** [comment]
Is your double click working well in other imgui context? Do you have your DeltaTime setup correctly because each call to NewFrame?

**Comment by krys-spectralpixel** [comment]
io.DeltaTime = 1.0f / 60.0f;

**Comment by krys-spectralpixel** [comment]
I also need to collapse when clicking the arrow, how can I do this please ?

**Comment by ocornut** [comment]
Well is your application running at this framerate? If it's running at 500 fps and you've passing 1.0f/60.0f then ImGui notion of time will be skewed and it can't measure a double-click time

I'm sure you can figure out the rest..

**Comment by krys-spectralpixel** [comment]
Real code is here
'''
    double current_time =  glfwGetTime();
    io.DeltaTime = (g_Time > 0.0) ? min((float)(current_time - g_Time), 1.f/60.f) : (float)(1.0f / 60.0f);
    g_Time = current_time;
'''

**Comment by ocornut** [comment]
Have you tested that double-click works in general?
ImGui::Text("%d", ImGui::IsMouseDoubleClicked(0));

**Comment by krys-spectralpixel** [comment]
No :-(

**Comment by ocornut** [comment]
You haven't tested this code or you have tested and it doesn't show a 1 ever? (Also try with a printf on true only to not miss it). Please be more clear with your answers because it's making it hard to help you. If double-click isn't detected you have a problem with your imgui integration and it could be related to the aforementioned DeltaTime. What sor of framerate is your application running at?

**Comment by krys-spectralpixel** [comment]
Something else, how can I detect the click on the "collapse arrow" only ?

**Comment by ocornut** [comment]
It's all in the code you posted above, change the bounding box passed to ButtonBehavior().

**Comment by enigmagame** [comment]
Hi,
is there any news about this feature?

**Comment by vivienneanthony** [comment]
Hi,

How is this code working out?

**Comment by ocornut** [comment]
Today added TreeNodeEx() with a bunch of new flags and a simple demo of tree selection / mulit-selection.
I am certain there is more work to do. Let's move further discussion (if any) to the other topic #581.
