### ISSUE TITLE
MenuItem Padding Issue on 1.62 ?

### ISSUE THREAD

**Issue by aiekick** [ocornut/imgui#1909]
Hello,

i deployed today the 1.62 release in my editor. and there is some space between the frame and the last item of the last menu : 

![2018-06-28_01-18-09](https://user-images.githubusercontent.com/1434736/42004842-00a624cc-7a72-11e8-8e5e-3789736e144e.gif)

you seen on the last item "VertexShadertArt" > "Base", we have some space at bottom of "base" item.

with the last version i dont have the problem.

**Comment by ocornut** [comment]
This is due to `style.WindowMinSize` being applied to the menu so it has a minimum size (which is incorrect). AFAIK it's been the case for a very long time. 

> with the last version i dont have the problem.

Please specify which version didn't have the problem.

**Comment by aiekick** [comment]
it was the 1.60 version i had on my three softwares like sdfmesher

**Comment by aiekick** [comment]
its weird in some menu i have the space but not on alls

in the menu edit on right i have the problems when i deploy
in settings => shaders => hide warnings i have but not in the lists of menu items 
it seems appearing only when we have only  one items in a menu. if we have more items there is no problems...

![2018-06-28_12-54-42](https://user-images.githubusercontent.com/1434736/42030268-800dd948-7ad2-11e8-8621-e9c3e8fa435e.gif)

**Comment by ocornut** [comment]
> it seems appearing only when we have only one items in a menu.

This is what I implied in my message above. There is a minimum width/height size for the window, and the default WindowMinSize value is (32,32) which is slightly taller than a menu with 1 entry.

However the code was the same in 1.60 so I am surprised that your GIF above doesn't exhibit the issue (perhaps your version of imgui.cpp was previously modified and your changed WindowMinSize in imgui.cpp instead of changing it from user code?)

It should be fixed now, let me know if it works for you.

**Comment by aiekick** [comment]
ok i will check by re use the version 1.60 from github again tonight

the settings i set are : 

```
ImGuiStyle& style = ImGui::GetStyle();

                style.WindowPadding = ImVec2(7, 5);
                style.WindowRounding = 0.0f;
                style.FramePadding = ImVec2(5, 4);
                style.FrameRounding = 3.0f;
                style.ItemInnerSpacing = ImVec2(6, 4);
                style.IndentSpacing = 12.0f;
                style.ScrollbarSize = 20.0f;
                style.GrabMinSize = 9.0f;
                style.GrabRounding = 16.0f;
                style.AntiAliasedLines = false;
                style.ScrollbarRounding = 16.0f;
```

**Comment by ocornut** [comment]
> its weird that its not work because in the BeginmainMenuBar() you do 
> PushStyleVar(ImGuiStyleVar_WindowMinSize, ImVec2(0,0));
> in 1.62 and 1.60
> so like that its not normal to have this 32 height issue.

OK I understand better, since 09ea376a6a0119eceab620fda421fbeb7f20ee15 the `PopStyleVar()` is done immediately after `Begin()`, This was intentional to not spread those settings to windows created from within the menu stack (e.g. a popup created from the menu) but it created this side effect with small menus. In 1.60 the `PopStyleVar()` was done in `EndMainMenuBar()` so the fix I just pushed wasn't necessary.

It should be fixed now! Let me know.

**Comment by aiekick** [comment]
yes its solved. thanks :+1:

**Comment by ocornut** [comment]
FYI I have committed a small amendment to this fix to extend it to auto-resized popups (especially as popups can freely be used as menus).

**Comment by aiekick** [comment]
ok thanks :+1:

**Comment by aiekick** [comment]
i have the same problem with a combo of one item :) i know its useless to have a combo of one item.
but a i have a combo for select shaders to use, and some time there is only one shader :)
