### ISSUE TITLE
SDL input handler

### ISSUE THREAD

**Issue by MayorZero** [ocornut/imgui#1911]
Hi! At this moment I am watching imgui sdl process event method and I cannot find any information about for example B, D, F, G, L letters and key down handling (it is empty case). 
Where I should check to find it?

**Comment by aiekick** [comment]
maybe its not in the doc of imgui you will find the solution but in the sdl2 documentation

**Comment by MayorZero** [comment]
I mean, I know how SDL scancodes/events work, but I do not know where in this code I can find my knowledge. I have found some of scancodes, but there were not for example 'b', 'd' and `case SDL_KEYDOWN` is empty, so how does it know when we click on b?

**Comment by ocornut** [comment]
@MayorZero Please explain clearly what you are trying to solve.

You can access the SDL keys stored in imgui using the SDL scancode, e.g.
`ImGui::IsKeyPressed(SDL_SCANCODE_B);` 
(this is taking its data by reading into the `io.KeysDown[SDL_SCANCODE_B]` array which filled by the SDL_KEYDOWN/SDL_KEYUP handlers).

The `ImGuiKey_XXX` enums (which as you have noticed do not cover all keys) are only for imgui to tell where you keys are located in the io.KeysDown[] array because imgui needs to use those few keys. You don't need to use them.

**Comment by MayorZero** [comment]
Oh, now I see. 

Why in `bool ImGui_ImplSDL2_ProcessEvent(SDL_Event* event)` method `case SDL_KEYDOWN:` is empty and you are doing ` io.KeysDown[key] = (event->type == SDL_KEYDOWN);` in here

```cpp
    case SDL_KEYUP:
        {
            int key = event->key.keysym.scancode;
            IM_ASSERT(key >= 0 && key < IM_ARRAYSIZE(io.KeysDown));
            io.KeysDown[key] = (event->type == SDL_KEYDOWN);
            io.KeyShift = ((SDL_GetModState() & KMOD_SHIFT) != 0);
            io.KeyCtrl = ((SDL_GetModState() & KMOD_CTRL) != 0);
            io.KeyAlt = ((SDL_GetModState() & KMOD_ALT) != 0);
            io.KeySuper = ((SDL_GetModState() & KMOD_GUI) != 0);
            return true;
        }
    }
```

**Comment by ocornut** [comment]
This is a C/C++ question. Please read about switch/case and == operator. This isn't the place to discuss it sorry.

**Comment by MayorZero** [comment]
I know about switch/case and == operator... . Why you are doing keydown in keyup case if it is a completely different statement, though.
