### ISSUE TITLE
Draw windows before ImGui::Render()

### ISSUE THREAD

**Issue by kolyden** [ocornut/imgui#192]
For our editor we use GWEN for dock logic and ImGui windows to draw everything inside. But have some trouble with that ImGui draws in one layer. Need some solution to draw ImGui inside GWEN code.
I can change source code to retrieve ImDrawList  array, save its count before ImGui::Begin() and another count after ImGui::End() then immediate draw all ImDrawList beneath that indexes.
Is that good solution?
Image of our editor for clarity.
![image](https://cloud.githubusercontent.com/assets/6959057/7085620/b3305d62-df78-11e4-9b24-58ad2e7875f0.png)

**Comment by Extrawurst** [comment]
wouldn't it be better to add docking and tabs support to imgui directly ?

**Comment by ocornut** [comment]
Interesting use :)

I'm not exactly sure to understand what you want to achieve and how the rendering needs to be changed. What is wrong with this screenshot? Inside the Begin() you can do GetWindowDrawList() to retrieve the ImDrawList* pointer. At render time you can use this information to render them in the order you want perhaps and ignore the provided order.

The problem with your approach if I understand it clearly, is that the child windows won't be sorted at the point of End(). ImGui allows for multiple Begin/End pairs to append to same window so sorting of childs doesn't happens in End() but when Render() is first called. 

If you can access GImGui->Windows (via imgui_user.inl because it is private) you can get the fully sorted list but that'll be the result from the last Render() call.

(It'd be better to have docking into ImGui, will eventually happens but that's not a trivial feature (can probably leverage some of the work Daniel has done on ProDBG)).

**Comment by kolyden** [comment]
Window can have ChildWindow/Frame is it have another ImDrawList ore share it with parent?

**Comment by ocornut** [comment]
It is another ImDrawList.

**Comment by ocornut** [comment]
You can add that in imgui_user.inl

```
void ImGui::GetWindowDrawListWithChilds(const char* window_name, ImVector<ImDrawList*>& out_draw_lists)
{
    ImGuiWindow* window = FindWindowByName(window_name);
    if (!window)
        return;
    ImVector<ImGuiWindow*> windows;
    AddWindowToSortedBuffer(windows, window);
    for (size_t i = 0; i < windows.size(); i++)
        out_draw_lists.push_back(windows[i]->DrawList);
}

```

To get the sorted drawlist.
Or you can replace FindWindowByName(window_name); with GetCurrentWindow() if you call it just before your final End().

**Comment by kolyden** [comment]
That why I need to store start and end indexes of ImDrawList array.
I need possibility to draw some GWEN dock then ImGui window in it, then another pair of dock and window, for solve overlapping issues. And I not need sorting of windows order because it is done on GWEN side.
On ImGui::End call is everything is ready to render and I can draw in immediately?

**Comment by kolyden** [comment]
GetWindowDrawListWithChilds will get list of all childs too?

**Comment by ocornut** [comment]
Yes you can render after or before an End() call.

**Comment by kolyden** [comment]
Ok, works great. Need to add SetWindowFocus for windows to input is works properly.
![image](https://cloud.githubusercontent.com/assets/6959057/7086612/48c9d966-df83-11e4-82be-6a187308562f.png)

**Comment by ocornut** [comment]
Nice :)
