### ISSUE TITLE
How can I get default display size of the pc? and how can I make imgui.ini consist with the pc's display size.

### ISSUE THREAD

**Issue by Bobyuan1015** [ocornut/imgui#1942]
You may use the Issue Tracker to ask for help and submit bug reports, feature requests or suggestions. 

PLEASE CAREFULLY READ THIS DOCUMENT before doing so:
[CONTRIBUTING.md](https://github.com/ocornut/imgui/blob/master/.github/CONTRIBUTING.md).

SELECT "PREVIEW CHANGES" TO TURN THE URL ABOVE INTO A CLICKABLE LINK.

(Delete everything above this section before submitting your issue. Please read the CONTRIBUTING.md file!)

----

**Version/Branch of Dear ImGui:**

XXX

**Back-end file/Renderer/OS:** _(if the question is related to inputs/rendering/build, otherwise delete this section)_

XXX

**My Issue/Question:** _(please provide context)_

**Standalone, minimal, complete and verifiable example:** _(see CONTRIBUTING.md)_
```
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Screenshots/Video** _(you can drag files here)_

**Comment by ocornut** [comment]
Hello,

This question is out of the scope of dear imgui, the answer depends on your underlying platform/engine.

Nevertheless, the examples/ folder are answering this question for variety of commonly used librairies (SDL, GLFW, SDL2). Search for `io.DisplaySize` within the examples/ folder. Otherwise, please ask and find your answer from a different community (maybe related to the tech/os you are using).

Regards,
-Omar

**Comment by Bobyuan1015** [comment]
Dear ocornut, many thanks for your response.  I am very appreciate.
Currently, I am working a project which is an android container project, which requires a control to monitor each android screen in ubuntu.

How can I modify imGUi.ini file in coding way? Any APIs

**Comment by ocornut** [comment]
You can't modify imgui.ini directly but it reflect the state of windows which you can adjust with SetNextWindowPos() SetNextWindowSize() api.

**Comment by Bobyuan1015** [comment]
thanks for these apis.
how can I set window size for multiple windows?
