### ISSUE TITLE
Handling input manually within imgui window

### ISSUE THREAD

**Issue by mankeli** [ocornut/imgui#1960]
I'm currently using ImGui::IsMouseHoveringRect() && ImGui::IsMouseDown() to do manual input handling within a window. I wonder if it's possible to tell imgui that I do that manual handling?

Context: I draw a gui manually, and would like to manipulate circles, lines and other graphical elements with mouse (and possibly keyboard).

Thanks!

**Comment by ocornut** [comment]
Do you mean you want to avoid moving the underlying window?

You can use ImGui::InvisibleButton() for that purpose, along with IsItemHovered, IsItemActive() etc.

**Comment by mankeli** [comment]
InvisibleButton() is probably okay for little circles, but maybe not for lines. (unless one spawns a ton of those buttons to roughly approximate the shape).

I also saw CaptureMouseFromApp() mentioned in some other thread. (Doesn't work). I also tried changing WindowFlags to NoMove for the next frame, but this doesn't work either. It seems that when the window movement has started, changing window to nomove has effect anymore.

**Comment by ocornut** [comment]
> InvisibleButton() is probably okay for little circles, but maybe not for lines. (unless one spawns a ton of those buttons to roughly approximate the shape).
> 
The idea is to use a single invisible button to encompass the zone within which you will handle picking/selection however you want.

> I also saw CaptureMouseFromApp() mentioned in some other thread. (Doesn't work).
> 
This only sets a flag in the IO structure which tells the user application whether it should direct mouse inputs to the non-imgui side of the app (eg: an underlying game display). It shouldn’t relate to your current situation.
> I also tried changing WindowFlags to NoMove for the next frame, but this doesn't work either. It seems that when the window movement has started, changing window to nomove has effect anymore.
> 
Correct, this is intentional (for various other reasons).

**Comment by mankeli** [comment]
Okay. Thanks for explanation and tips. :)

For the record, it seems that I found an another solution to this:
1. Normally do Begin() with NoMove flag
2. Do the manual input handling, see if mouse is hovering over any of the custom stuff
3. If mouse is not over any custom thing, don't set the NoMove flag on next frame.

**Comment by ocornut** [comment]
I’m not sure I can visualize your situation well enough to understand why not using InvisibleButton() be enough and simpler.

You can take advantage of the fact that the first widget submitted gets the mouse to create intentional overlap: if you submit a large InvisibleButton() over and after a bunch of regular widgets it will only receive inputs when not hovering those widgets.

Feel free to close the issue if you are satisfied with the resolution.

**Comment by mankeli** [comment]
InvisibleButton is surely enough for my use case too. Only difference is probably that with InvisibleButton() you can't fill a window with custom area, that still allows user to move the window by clicking any part of it that's not covered by a widget (custom in this case).

**Comment by ocornut** [comment]
I haven’t tested it, but I think if you called StartMouseMovingWindow() from imgui_internal.h manually as a fallback it would work. May be interesting to see if this can become an accepted usage pattern.
