### ISSUE TITLE
Loop rendering of ImGui::Selectable-s

### ISSUE THREAD

**Issue by andrewsmith1551** [ocornut/imgui#1966]
**Version/Branch of Dear ImGui:** 1.49.

**Back-end file/Renderer/OS:** DirectX 9.

Back-ends: imgui_impl_dx9.cpp (Win32 + DirectX9 binding)
OS: Windows 10

**My Issue/Question:** I need to loop rendering selectables and then store which one is selected in one variable, but it won't render those selectables, I guess it's because of loop. Is there any other way of doing this?

**Standalone, minimal, complete and verifiable example:**
```
`for(int i = 0; i < sizeof(selectables); i++;)
{
     if(ImGui::Selectable(selectables[i]))
        selected = i;
}
`
```

**Comment by ocornut** [comment]
Hello,.

Please provide a full repro including the actual variables and data involved. This looks like a C++ question rather than an imgui question

Your use of sizeof() is most likely wrong (sizeof returns the size in bytes, if “selectables” is an array you’ll get its total size in bytes, if “selectables” is a pointer to something you’ll get the size of a pointer aka 4 or 8 bytes)

**Comment by ice1000** [comment]
Retry

```cpp
for(int i = 0; i < (sizeof selectables / sizeof selectables[0]); i++;)
{
     if(ImGui::Selectable(selectables[i]))
        selected = i;
}
```

**Comment by andrewsmith1551** [comment]
Thanks, @ice1000 
It worked.

**Comment by ocornut** [comment]
Thank you @ice1000 . One commonly used pattern in old style C/C++ is to create a macro e.g. ARRAYSIZE which does this division of the total array size by the element size to obtain the count. There is such a macro in imgui.h called IM_ARRAYSIZE() so you can use IM_ARRAYSIZE(selectables) here.

`#define ARRAYSIZE(_ARR)          (sizeof(_ARR)/sizeof(*_ARR))`

This type of macro is error-prone / dangerous because if you accidentally pass in a pointer instead of an array, you won't get the expected value. It is possible to create a templated version of this using a trick that will make the compiler error if you don't pass it an array.

I suspected your `selectables` was a pointer because you said "it won't render those selectables", suggesting your loop count was zero or _smaller_ than expected. By the look of the solution that worked for you, your loop count was too high so the old code probably either rendered extra garbage after the correct data, either crashed.
