### ISSUE TITLE
Enabling GL_LIGHTING with freeglut+opengl2 makes the ui components black 

### ISSUE THREAD

**Issue by EldarZ** [ocornut/imgui#1996]
**Version/Branch of Dear ImGui:** 
1.63 WIP

**Back-end file/Renderer/OS:** 
Nvidia 1060
Back-ends: imgui_impl_freeglut.cpp + imgui_impl_opengl2.cpp
OS: Win10 
Compiler: VS2017 

**My Issue/Question:** 
I'm running the freeglut + opengl2 example, I used it to integrate imgui to my existing project, written in opengl 1.1 (unfortunately this version is required), whenever I enable GL_LIGHTING the ui components turn to black, I googled this issue + searched this repository's issues, but got nothing. 
To my understanding this is because there's no glMaterial definition to the ui component, but I'm not sure how to fix it.

Is this a known issue with opengl? I have't seen any lighting related code in imgui to maybe override it. 
**Standalone, minimal, complete and verifiable example:** 
```
//anywhere in the freeglut + opengl2 example code
glEnable(GL_LIGHTING);
```

**Screenshots/Video** 
![capture](https://user-images.githubusercontent.com/11643762/43562241-0fca4730-9624-11e8-93c2-7925853f26de.PNG)

**Comment by ocornut** [comment]
Don’t enable lighting while rendering imgui with this setup? You can still enable it elsewhere.

**Comment by EldarZ** [comment]
my project requires lighting, how do I exclude imgui ui components from the global glEnable(GL_LIGHTING) state in freeglut + legacy opengl?

**Comment by jarikomppa** [comment]
Simply disable lighting while rendering imgui, then enable it.

**Comment by EldarZ** [comment]
right... I just wrapped  ImGui_ImplOpenGL2_RenderDrawData(ImGui::GetDrawData()); with disable and enable lighting, sorry about the newbie question. Thanks!!

**Comment by ocornut** [comment]
No worry @EldarZ . As it turns out, our rendering back-end aim to explicitly enable/disable all the OpenGL states they needs, then restoring the changes when it finish rendering. It's just tricky to do it exhaustively for OpenGL. So few people actually use those legacy OpenGL features and you are the first person to report something with GL_LIGHTING conflicting so imgui_impl_opengl2.cpp didn't explicitly disable it.

I've know pushed a change to disable GL_LIGHTING and GL_COLOR_MATERIAL so it should work even if you don't disable it on your end.

**Comment by EldarZ** [comment]
@ocornut great!, awesome library! 👍
