### ISSUE TITLE
[Question] Time on title bar, flickers

### ISSUE THREAD

**Issue by Bawabawa01** [ocornut/imgui#2007]
Hello. Is it possible to print current time on the title bar of ImGui window without flickering?
Whenever I do like:

`std::string` title = "Name" + to_string(GetCurrentTime());
ImGui::Begin(title.c_str(), &b_Opened, `window_flags);`

it is flickering everyframe when reaching ImGui::Begin line.

**Comment by ocornut** [comment]
Hello,

This is because Windows are uniquely identified by their title screen.
If you include the current in the title string, it will create a new window every time, hence the flicker.

To achieve what you want you need to use the `###` imgui string operator to enforce a stable identifier for the same while the displayed strings changes.

Please check the Demo in Examples->"Manipulating window titles"
And read the FAQ `How can I have multiple widgets with the same label or without a label? A primer on labels and the ID Stack.`.

So e.g.
 `"Name (12:35)###Name"`
Will share the same identifier as
 `"Name (11:11)###Name"`

**Comment by Bawabawa01** [comment]
Thank you very much!
