### ISSUE TITLE
Separate render and mouse input processing

### ISSUE THREAD

**Issue by hateom** [ocornut/imgui#2008]
Hello,

I'm trying to use imgui for drawing some user interface inside a graphics plugin.
Unfortunately the API creates some constraints and I'm wondering if I can overcome them somehow.

The plugin has 4 callbacks: **render, mouse_move, mouse_up and mouse_down**.
The problem I'm facing is that I can only respond to some action (button press, checkbox selection) in mouse_up or mouse_down methods and **not in render** method. I can draw a checkbox in render function but I need to somehow _know if it was pressed in mouse_up function_.

The general code:

    void render()
    {
        ImGui_ImplGL3_NewFrame(...);

        ImGui::Checkbox("Something", &something_checked);

        ImGui::Render();
        ImGui_ImplGL3_RenderDrawLists(ImGui::GetDrawData());
    }

    void mouse_up()
    {
        ImGui_ImplGL3_MouseButtonCallback(...);

        // TODO: check if "Something" checkbox was selected
        // if(ImGui::CheckBox("Something", &something_checked))
        // {
        //     some_action(); // <- can only be called inside mouse_up
        // }
    }

Any suggestions?

**Comment by ocornut** [comment]
1) You didn't provide the information asked when opening an issue.

2) The mouse move/up/down callback only need update the io.\* fields. In this case all your ImGui ui and logic would be in the Render(), so I don't really understand your question. There's no point in calling CheckBox from those events.

**Comment by ocornut** [comment]
Adding to this since I probably misunderstood the intent of the question. It's hard to see what the exact constraints of your setup are. What it is that you have to communicate outside from mouse_up that you cannot communicate in render() ? Could the main UI processing store those information so they can be communicated outside from the other handlers?

One weird workaround would be to run your full UI frame (NewFrame/widgets/EndFrame) within each mouse events, and only calling the Render() functions in Render(). That's possible but evidently costly and a little silly but it'll work and if you don't have thousands of items it may be work well enough.

The better solution is probably tied to understanding your application and the constraints associated to your setup, which only you know.

**Comment by hateom** [comment]
Well, to give one example (a very simplified code):

    void mouse_up(FILE * file_out)
    {
        ImGui_ImplGL3_MouseButtonCallback(...);

        // need to write to the file on checkbox selection
        fprintf(file_out, "checkbox was selected")
    }

mouse_up function in my plugin is called by the host application and only in this function I have access to the file_out handle. So after calling ImGui mouse button callback I need to know right away if the checkbox was pressed and selected, before the render function will be called by the host application - where I don't have the file_out handle. Storing the handle for render function is not possible (cause it can be closed and reopened in the meantime).
