### ISSUE TITLE
Renderer imgui_impl_opengl2.cpp memory leak

### ISSUE THREAD

**Issue by AIG-Livny** [ocornut/imgui#2011]
**Dear ImGui:** 1.63

Back-ends: imgui_impl_opengl2.cpp + imgui_impl_glfw.h
OS: Win7 x64
Compiler: VC17

Hi,
memory leak in ImGui_ImplOpenGL2_RenderDrawData

`// Restore modified state`
  ` ...`
   ` glPopMatrix();`
  `  glMatrixMode(GL_PROJECTION);`
  `  glPopMatrix();`
`    glPopAttrib();                                 // here memory leak !
`
I do not know whether this is a OpenGL problem or ImGui, but i tried comment out glPushAttrib and glPopAttrib and the leak has stopped.
![image](https://user-images.githubusercontent.com/29213991/43805995-b55a1f1a-9aaa-11e8-97d4-5b59f43d1454.png)

**Comment by ice1000** [comment]
Are you running the default main.cpp/

**Comment by AIG-Livny** [comment]
Screenshot? No it's my part, but I compiled the default example and there is the same thing.
![image](https://user-images.githubusercontent.com/29213991/43817543-af927d92-9ae2-11e8-8ee3-fa4d139229f0.png)

**Comment by AIG-Livny** [comment]
May be it is a "Intel Express 965" driver problem? Although before run example, i installed latest drivers.

In my case: i can delete this?
`glPushAttrib(GL_ENABLE_BIT | GL_COLOR_BUFFER_BIT | GL_TRANSFORM_BIT);`
`...`
`glPopAttrib();` 

I'm not an OpenGL expert. But if I remove these lines, then there are no visible changes. Memory does not leak. I understand that this is not correct, and I need to read the OpenGL manual to understand what these lines mean... and yet at least somehow solves my problem

**Comment by ocornut** [comment]
It looks like a driver problem to me.
Generally, it is not recommended to use the old imgui_impl_opengl2.cpp code as the drivers are not well used to deal with this type of legacy GL any more. Why not using imgui_impl_opengl3.cpp ?

> In my case: i can delete this?

You can delete those lines, but it means if you have other application code that relied on current GL attributes without resetting them every frame, they would be affected. Those lines are mostly here to increase compatibility with user applications without them having to worry about the GL state. Large engine rarely have a problem since they tend to set things explicitly. Small quick and dirty code-bases are a little more likely to rely on global state persisting across frames.

**Comment by AIG-Livny** [comment]
My graphic drivers "Intel Express 965" support only OpenGL 2.
Ok, thank you very much!
