### ISSUE TITLE
IMGUI_VERSION additional definitions in header?

### ISSUE THREAD

**Issue by eliasdaler** [ocornut/imgui#2025]
Hello. Currently we have `IMGUI_VERSION`  in imgui.h header, but it's not easy to work with.

## Proposal

Replace this:

```cpp
#define IMGUI_VERSION "1.63 WIP"
```

with

```cpp
#define IMGUI_VERSION_MAJOR 1
#define IMGUI_VERSION_MINOR 63
#define IMGUI_VERSION_PATCH 0 // semver some day...? Can stay 0 forever if you want
#define IMGUI_WIP 1 // not defined or defined to 0 when stable
```

If you want to have a version string as well, you can either define it as previously, but this can lead to inconsistency between version string and new macro definitions. Well, you can use some macro stuff, e.g.:

```cpp
// macro hacks...
#define TO_STRING2(s) #s
#define TO_STRING(s) TO_STRING2(s)

#if IMGUI_WIP
#define IMGUI_VERSION TO_STRING(IMGUI_VERSION_MAJOR) "." TO_STRING(IMGUI_VERSION_MINOR) " WIP"
#else
#define IMGUI_VERSION TO_STRING(IMGUI_VERSION_MAJOR) "." TO_STRING(IMGUI_VERSION_MINOR)
#endif
```

## Motivation

1) Much easier to parse, especially via CMake. (for example I want to write a script which checks that ImGui version requirements are met... it's not easy to do it now, need to write more stuff that I want)

2) Can be used in #if blocks for backward compability in libraries which use ImGui, e.g.

```cpp
#if IMGUI_VERSION_MAJOR == 1 && IMGUI_VERSION_MINOR < 63
... // old code
#else
... // new code
#endif
```

**Comment by ocornut** [comment]
Out of curiosity:

> Can be used in #if blocks for backward compability in libraries which use ImGui

What are you trying to test against?
I would prefer to use the approach used by branch of creating defines for specific features.

I am going to add a version value, will probably add a single integer.

**Comment by eliasdaler** [comment]
For example, ImGui-SFML can support older ImGui versions, for example ones which didn't have gamepad/keyboard navigation. 

If there are more breaking changes, I can make them work with ImGui-SFML too.

As for the single number - does this mean that ImGui will always be 1.xx? Won't you use semver starting from some point?

**Comment by ocornut** [comment]
> For example, ImGui-SFML can support older ImGui versions, for example ones which didn't have gamepad/keyboard navigation.

Shouldn't people be incentivized to just update? If for some reason we need to keep using an old version of imgui then it is reasonable that they use the matching imgui-sfml wrapper. Up to you, but it seems like you are creating more work for yourself.


A single number can express all the version fields. Libraries that have separate values generally have a macro to reassemble then into 1 value so it can be used easily:

```
// Integer encoded as XYYZZ for use in #if preprocessor conditionals. 
// Work in progress versions are typically XYY00 then bounced to XYY01 when release tagging happens
#define IMGUI_VERSION_NUM           16300 
```

While we could expose _MAJOR _MINOR + a macro to reassemble them into a single integer, since we don't support semantic versioning if would be misleading. Also in practice preprocessor defines are often used to check if a feature is available, which requires testing for a combination of at least MAJOR _AND_ MINOR so your test becomes `#if (MAJOR == 1 && MINOR >= 63 || MAJOR > 1)` instead of `#if (just VER >= 163`

**Comment by ocornut** [comment]
Added something now!

**Comment by eliasdaler** [comment]
Thanks a lot. :)
