### ISSUE TITLE
Add api to check the Begin/End Push/Pop functions are balanced.

### ISSUE THREAD

**Issue by heroboy** [ocornut/imgui#204]
for example:
```cpp
for(GameObject * go : AllGameObjects)
{
     auto tag = ImGui::BeginCheckBalanced();
     go->OnGUI();
     if (!ImGui::EndCheckBalanced(&tag))
     {
          assert(0);
     }
}
```

**Comment by ocornut** [comment]
It could be done automatically on a per-scope basis (e.g. per windows/tree node)
Per-window I suppose I could add an assert.

**Comment by ocornut** [comment]
Out of curiosity which piece of state did you most commonly have problem with ?
I can do a counter == check but that wouldn't catch underflows, and will only catch problems with data that are stacked. I suppose it will catch 95% of the problems so that should be good enough.

**Comment by ocornut** [comment]
Now automatically checking if those values are matching between Begin/End

window->IDStack.size();      
window->DC.GroupStack.size();
g.ColorModifiers.size();     
g.StyleModifiers.size();     
g.FontStack.size();          

It is a bit flaky to just check sizes instead of settings limits that but that's simple and should catch the majority of bad use cases.
