### ISSUE TITLE
Debian package - please adjust how you want it (if you are ok with it)

### ISSUE THREAD

**Issue by smoe** [ocornut/imgui#2084]
Hello,

**Version/Branch of Dear ImGui:**

master

**Back-end file/Renderer/OS:** _(or specify if you are using a custom engine back-end)_

Back-ends: *
OS: Linux (Debian+Ubuntu)
Compiler: g++

**My Issue/Question:** _(please provide context)_

I would like to create a package of OpenBoardView for Debian and dear imgui is a build dependency for it. So, I also need a package for your work, then :) I hope you are fine with that.

If you agree to Debian redistributing your work, this now leaves me a bit overwhelmed with my understanding that apparently it is just .cpp source code files that this package would offer - no .so library, correct? Would you then prefer these in /usr/include/imgui oder rather in /usr/share/imgui? I opt for the latter but happily follow what you so desire.

**Standalone, minimal, complete and verifiable example:** _(see CONTRIBUTING.md)_

Once done, which seems straight forward, I suggest to name the installable package along Debian's principles
"lib"${packagename}-dev
-dev since your files are not needed at runtime.

```
apt-get install libdear-imgui-dev
```
Many thanks and kind regards,

Steffen

**Comment by ocornut** [comment]
Why don’t you include the imgui cpp files inside the openboardview repository? That’s the general intent of imgui’s design.

**Comment by smoe** [comment]
Thank you for your swift reply - even when the answer was a bit unexpected, but that is why I had asked in the first place :) The idea on my side was that as many packages as possible should share the very same source code and not maintain some approximate copy of it. Problems would then be communicated more quickly (so one hopes) and there would be less redundancy in the binaries executed. But - upstream is the boss. Just ping me if you change your mind.

**Comment by ocornut** [comment]
I don't know the minutia of Debian packaging rules and I assume the situation would be unusual here, but I can't really answer your questions (`/usr/include/imgui` vs `/usr/share/imgui` etc.) without more context. Nor do I understand why/how problems would be communicated more quickly with a Debian package, or why a local copy locked to a version of your choice is "some approximate copy" ? (I would say it is exactly the opposite since you know exactly which version you are using).

Dear ImGui doesn't use semantic versioning (because it is fast moving, has a wide api contact surface and limited development resources means things aren't designed with as much foreseeing as more popular open-source project, semantic versioning would aggressively up the version numbers so frequently it would make targetting-by-major-version unpractical). This is one reason why it is recommended you carry your own copy of it. 

Another reason is that it is recommended to build imgui with a custom configuration file (either modifying imconfig.h either using defines to use your own configuration file) and because of this distributing binaries is not recommended, nor is distributing sources in a way that don't put this possibility at the forefront.

**Comment by smoe** [comment]
I am fine with not performing the packaging :) You may have a point. The advent of git+github and submodules has changed the world quite a bit.  And Debian et al. have not found the ultimate answer to that trend, yet.

**Comment by ocornut** [comment]
I don't know if there _is_ a ultimate answer. On a personal level I'm not particularly fond of exposing imgui/myself to wider and more casual audiences. Dear ImGui is fine being a specialized thing growing slowly :)
