### ISSUE TITLE
Simulate native windows GUI looking

### ISSUE THREAD

**Issue by dhiahassen** [ocornut/imgui#2106]
I am trying to convince my partners at work to use Imgui, they like the intermediate mode concept, what "bothers" them is that they think it is hard to make an application that uses Imgui look like a native Windows application
Is there any theme/configuration that can be used to make Imgui look close to native windows apps ( example like the default looking of wxWidget ) , have anyone done such thing before ? 

Thanks for your time 
[ Example ]

![nativegui](https://user-images.githubusercontent.com/17810558/46172205-30dc4580-c2a3-11e8-9e38-6fc278277e08.PNG)

**Comment by ice1000** [comment]
https://github.com/ocornut/imgui/issues/707#issuecomment-362574409

**Comment by ocornut** [comment]
The answer is Maybe, With some Effort and Time.

This is how you might expect things to reach in several (six?) months with more colors available in style, gradient, shadows: https://github.com/ocornut/imgui/issues/1329#issuecomment-413712814

It's never going to be exactly a native UI and there are different pros and cons using dear imgui compared to a traditional framework. I don't really have a fuller answer.

**Comment by Clocktown** [comment]
If you want that native look, you should use the respective GUI frameworks. Really. However, many people take on much pain exactly because they do not want that native look, but their own look that looks the same across all platforms. And ImGui achieves that, at much less cost compared to something like Electron, albeit without the fancy website-as-a-gui stuff.

I'd say: convince your parents of the benefits of a non-native look.

**Comment by niutech** [comment]
Have a look at [imgui-win98](https://github.com/JakeCoxon/imgui-win98).
