### ISSUE TITLE
Feature request: scrollbar rounding

### ISSUE THREAD

**Issue by petrihakkinen** [ocornut/imgui#212]
Could you please add configurable rounding to scrollbars? I would need them for a style/theme I have in mind.

**Comment by ocornut** [comment]
Would you like it to be a different parameter or just frame the same value as FrameRounding ?

You can give it a quick try by modifying the last line of the Scrollbar() function:
```
static void Scrollbar(ImGuiWindow* window)
{
....
--    window->DrawList->AddRectFilled(ImVec2(bb.Min.x, ImLerp(bb.Min.y, bb.Max.y, grab_y_norm)), ImVec2(bb.Max.x, ImLerp(bb.Min.y, bb.Max.y, grab_y_norm) + grab_h_pixels), grab_col);
++    window->DrawList->AddRectFilled(ImVec2(bb.Min.x, ImLerp(bb.Min.y, bb.Max.y, grab_y_norm)), ImVec2(bb.Max.x, ImLerp(bb.Min.y, bb.Max.y, grab_y_norm) + grab_h_pixels), grab_col, style.FrameRounding);
}
```

**Comment by petrihakkinen** [comment]
Separate value for ScrollbarRounding would be ideal. I'd like to have a theme that is mostly rectangular, except for scroll bars.

**Comment by ocornut** [comment]
OK. It is style.ScrollbarRounding.
I initially added it as a more general GrabRounding to apply to sliders grab as well but then decided they were better separate. I didn't add an ImGuiStyleVar_ definition because I imagine it isn't something you would want to alter so much post-init. (or, I should probably go and add all the missing ImGuiStyleVar_ definitions..).

![scrollbar_rounding](https://cloud.githubusercontent.com/assets/8225057/7549597/5eac4cb0-f634-11e4-8cdb-21fab5d5c1de.PNG)

Note that it is affecting the grabbable part but not the scrollbar box itself, is that what you wanted? I don't really want to add too much options there.

**Comment by petrihakkinen** [comment]
Sweet! I'll post pics when I get the theme done next week. Many thanks!
