### ISSUE TITLE
Possibilities to create a precompiled library

### ISSUE THREAD

**Issue by TeeEmJee** [ocornut/imgui#2128]
**Version/Branch of Dear ImGui:**

v1.65

**Back-end file/Renderer/OS:** 

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
OS: Linux x64 
Compiler: gcc/g++

**My Issue/Question:**

I wonder if it would be possible to add a precompiled library to the CMake project.

I am currently using **Dear ImGui** using the ["ExternalProject_Add()"](https://cmake.org/cmake/help/latest/module/ExternalProject.html) function and downloading the project directly with Git.
Unfortunately it is a bit difficult to include all necessary source and header files in my project.

Sure, I could customize the CMake project to my needs, but I'd like to always use the latest version of the library and changes from outside are a bit cumbersome.

Maybe I'm not the only one who would want such a feature.

**Comment by ice1000** [comment]
Take a look at #1713

**Comment by ocornut** [comment]
> I wonder if it would be possible to add a precompiled library to the CMake project.

Your message is a little bit confusing because you are implying there's already a CMake project in the main repository, which there isn't.

As pointed by ice1000, you can use the cmake patch linked above.

> Unfortunately it is a bit difficult to include all necessary source and header files in my project.

Can't you just add \*.h and \*.cpp files from the imgui/ folder as part of your project to compile?
