### ISSUE TITLE
ShowDemoWindow takes 12+ seconds to compile in release mode in VS 2017

### ISSUE THREAD

**Issue by nem0** [ocornut/imgui#2152]
----

**Docking & master branch, almost any revision, I tried the latest and 5 months old**

OS: Windows
Compiler: VS 2017, I've not tested any other

**My Issue/Question:** imgui takes 12+ seconds to compile in Release mode, ```ShowDemoWindow``` alone takes 12 seconds. I can't use ```IMGUI_DISABLE_DEMO_WINDOWS``` since that disables style editor too and I'm using that. If I remove just the body of ```ShowDemoWindow```, compile time is normal.

**Comment by ocornut** [comment]
Are you trying about compile or linking or both?
Because "ShowDemoWindow alone takes 12 seconds" suggests compilation alone.

Here with VS2015:

64-bit Release: Compiling imgui_demo.cpp takes <0.5 second ish.
32-bit Release: Full Rebuild examples_directx11 takes ~2/3 seconds without linking.
32-bit Release: Full Rebuild examples_directx11 takes ~4 seconds including linking, with `IMGUI_DISABLE_DEMO_WINDOWS`.
32-bit Release: Full Rebuild examples_directx11 takes ~10 seconds including linking.
64-bit Release: Full Rebuild examples_directx11 takes ~10 seconds including linking.
32-bit Debug: Full Rebuild examples_directx11 takes ~3 seconds including linking.
64-bit Debug: Full Rebuild examples_directx11 takes ~3 seconds including linking.

Not sure what to say. Linking optimization are heavy but I'm not sure how abnormal it is. Do you have a suggestion of what to look at?

I am sure it is `ShowDemoWindow()` itself but more the fact that when demo is compiled most of imgui functions are linked?

**Comment by ice1000** [comment]
12 secs looks reasonable to me.

**Comment by nem0** [comment]
I use ```d2cgsummary``` flag (https://aras-p.info/blog/2017/10/23/Best-unknown-MSVC-flag-d2cgsummary/) 
```
Anomalistic Compile Times: 1
1>		?ShowDemoWindow@ImGui@@YAXPEA_N@Z: 21.824 sec, 37627 instrs
```
so it should be just compile time. I'm trying to pinpoint exact cause.

**Comment by nem0** [comment]
I tried to comment different parts of ```ShowDemoWindow```, there seems to be no single culprint.

**Comment by ocornut** [comment]
By splitting the code of `ShowDemoWindow()` into 4-5 distinct functions it seems to halve the link time in Release mode.

**Comment by ocornut** [comment]
@nem0 Pushed those changes, how does it perform for you with same settings?

**Comment by thevaber** [comment]
For me, the split took the time down from ~4s to ~0.5s; FWIW, wrapping `ImGui::ShowDemoWindow` inside `#pragma optimize("", off)`/`#pragma optimize("", on)` also seems to do the trick (down to 0.044s for the unsplitted version), but I'm not sure whether that's an acceptable tradeoff

**Comment by nem0** [comment]
```
?ShowDemoWindowWidgets@@YAXXZ: 1.923 sec, 18089 instrs
1>		?ShowDemoWindowLayout@@YAXXZ: 1.375 sec, 13657 instrs
1>		?ShowDemoWindowMisc@@YAXXZ: 0.638 sec, 6682 instrs
```

**Comment by ocornut** [comment]
Well that looks much better!
(Btw those are essentially linking times)

We could do better but it’d be more rework of the demo, I think we may be good enough here?

I’ll remember to watch out for very long functions from now on, it does makes sense that the compiler/linker may want to agressively optimize things within the scope of a function.
