### ISSUE TITLE
invalid mouse position in NavCalcPreferredRefPos

### ISSUE THREAD

**Issue by dcourtois** [ocornut/imgui#2168]
Configuration:
- docking branch @ 5f8c9ae0efd17afcd9e39cc0cc0df3c51e994285
- GLFW / OpenGL3 back-end (unmodified)
- Windows 10 / Visual Studio 2017 (up-to-date)
- Compiled in Debug / Win64

I triggered the assert in ImGui::NavCalcPreferredRefPos with a comment stating "This will probably trigger  at some point, please share your repro!", so here it is :)
With the following code in debug, run, then hit Alt+Tab (or basically do anything that will lose the ImGui window's focus) It should assert every time.

```
ImGui_ImplOpenGL3_NewFrame();
ImGui_ImplGlfw_NewFrame();
ImGui::NewFrame();

ImGui::SetNextWindowSize(ImVec2(200, 200));
ImGui::OpenPopup("foo");
if (ImGui::BeginPopupModal("foo"))
{
	ImGui::EndPopup();
}

ImGui::Render();
ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
```

Edit: tracked it back to `imgui_impl_glfw.cpp`, in `ImGui_ImplGlfw_UpdateMousePosAndButtons` function: if the window does not have the focus, the mouse pos is set to `-FLT_MAX`.
The fix is pretty straightforward. I just added this before rendering my UI:

```
if (glfwGetWindowAttrib(m_Window, GLFW_FOCUSED) == 0)
{
	return;
}
```

But I don't know how you would want to fix this directly in ImGui... maybe an option to not render anything when the window is not focused / visible ? Do this in each back-end or in the core of ImGui ?

**Comment by ocornut** [comment]
Thank you @dcourtois @Alzathar this should be fixed now.

(FYI @dcourtois : note that although there is code to mitigate it, calling `OpenPopup()` every frame is technically illegal. What's strange is that the whole OpenPopupXXX shenenigan should not be necessary for Modal window, this design is only to allow imgui owning and manipulating the visible state of the window which is required for regular popups (but not modal). Because modal appears to be a specialization of popups they follow the same scheme for consistency.)

**Comment by dcourtois** [comment]
@ocornut First of all, thanks for the fix (my workaround was a bit annoying since whenever the window was losing focus while still being visible, the whole interface was disappearing :p)
As for the modal popups, I totally missed the "con't call every frame!" :D thanks for pointing that out !
