### ISSUE TITLE
Viewports user data extension

### ISSUE THREAD

**Issue by rhard** [ocornut/imgui#2190]
**Version/Branch of Dear ImGui:**

viewport

**Back-end file/Renderer/OS:** 

X-Plane Flight Simulator engine(OpenGL2 based)
OS: Windows

**My Issue/Question:**

Hi @ocornut. I'm trying to use viewport feature to create custom GUI in X-Plane flight simulator. 
I started to create a GUI C++ class and don't know how to avoid next problem:

I don't know how to supply PlatformIO callback functions with the instance of my main class:
```c++
void ImgX::initPlatformInterface() {
    auto &platform_io = ImGui::GetPlatformIO();
    platform_io.Platform_CreateWindow = createWindow;
    platform_io.Platform_DestroyWindow = destroyWindow;
    platform_io.Platform_SetWindowSize = setWindowSize;
    platform_io.Platform_GetWindowSize = getWindowSize;
    platform_io.Platform_DestroyWindow = destroyWindow;
    platform_io.Platform_SetWindowSize = setWindowSize;
    platform_io.Platform_GetWindowPos = getWindowPos;
    platform_io.Platform_SetWindowPos = setWindowPos;
}
``` 
I know that every callback has '''ImGuiViewport*''' argument with ```PlatformUserData``` and ```              PlatformHandle```, but first time I can set this data is in Platform_CreateWindow callback only. In this callback I don't have an access to the instance of the main class.

Is it possible to provide a general way to set the viewport user data before callbacks are being executed?
Or add user data member to the GetPlatformIO structure?
Something like this:
```c++
if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable)
    initPlatformInterface((void *)this);
...

void ImgX::initPlatformInterface(void *userData) {
    auto &platform_io = ImGui::GetPlatformIO();

    // set platform data here
    platform_io.SetPlatformUserData(userData);

    platform_io.Platform_CreateWindow = createWindow;
    ...
}

void ImgX::createWindow(ImGuiViewport *viewpor, void *platformUserData) {
    // now I can use my class instance here
    auto myGui = (ImgX *)platformUserData;
...
}
```

Sorry, if such possibility could be done in other way.. I just didn't find it...

**Comment by ocornut** [comment]
You may use `io.UserData` or any of your own global, since essentially your imgui instance pointer is global already. I don't mind adding an extra `void*` in platformio but it'll essentially just be religion-compatible sugar for people who would rather use globals that they didn't add themselves.

**Comment by ocornut** [comment]
I'm not sure I understand all of your post, it is a little abstract (e.g. I have no idea what `MyGuiClass` is meant to represent).

Basically there is a "current" ImGui context pointer which is a global. If you have multiple imgui contexts you need to use `ImGui::SetCurrentContext()` to change it. Since you need to be altering a global to change imgui context you may be altering multiple globals.
 
Combining multiple-imgui context + multiple-viewports is going to be guaranteed **maximum confusion** and I would advise against doing both together.

In your back-end (`Platform_CreateWindow` handler) you may filter based on the `ID` field. `ID == window->ID = ImHash(window->Name, 0);` So you maintained a list of windows that needs to be decorated differently, your `Platform_CreateWindow` handle can search for the ID in this list and act accordingly.

**Comment by rhard** [comment]
Sorry, I know how difficult is to understand my writing) But you gave me good tip. If I can find ImGui window from Platform_CreateWindow handler, it will solve my problem.

**Comment by ocornut** [comment]
You can by doing:

```
#include "imgui_internal.h"

return (ImGuiWindow*)GImGui->WindowsById.GetVoidPtr(viewport->id); // may be NULL
```

Will extract this into a `FindWindowByID()` function in the meanwhile you can do just that.

**Comment by rhard** [comment]
I also find that I can access viewport after Begin function by ```GetWindowViewport``` direct.

Unfortunately, I stumbled with another problem which is related to the X-Plane engine itself. The API they provide is very limited. It looks like I can use more ImGui features by switching context, than using viewports. I will close the issue for now.

Big thanks for your help!
