### ISSUE TITLE
What is the name of the anti-aliasing used in dear im gui?

### ISSUE THREAD

**Issue by Eklaron** [ocornut/imgui#2223]
What is the name of the anti-aliasing used in dear im gui? I'd like to read a bit about it.

**Comment by ocornut** [comment]
You can enter “anti aliasing” into Google to read about it.

**Comment by Eklaron** [comment]
Yes, but there are like 1000 argorithms. I tried MSAAx16 but it does not work as good as which you used.

**Comment by ocornut** [comment]
Apologies, i misunderstood your question i thought you wanted to learn about AA in general. I don’t know if the algorithm we use has a specific name. It’s not comparable to fullscreen AA techniques like MSAA, we’re generating polygons that have AA fringes instead of post processing a buffer. It’s based on the work of mikko on nanovg. You may ask over there.
