### ISSUE TITLE
ReadOnly InputFloat allows to change its value.

### ISSUE THREAD

**Issue by Remist0** [ocornut/imgui#2257]
**Version/Branch of Dear ImGui:**

Version: 1.61

**My Issue/Question:** _(please provide context)_

Seems that InputFloat with ImGuiInputTextFlags_ReadOnly flag allows to changing its value with "-" and "+" widgets.

```
ImGui::Begin("Imgui ReadOnly InputFloat bug");
static float testValue = 0.0f;
ImGui::InputFloat("Test", &testValue, 0.1f, 1.0f, "%0.2f", ImGuiInputTextFlags_ReadOnly);
ImGui::End();
```

**Screenshots/Video** 
![2f32ff789774ade86914349fec26](https://user-images.githubusercontent.com/2908998/50535743-f8ccf300-0b6e-11e9-8ae2-9375b4ba5336.gif)

**Comment by ocornut** [comment]
Thank you @Remist0 this is fixed.
To be fair I didn't expect most of the `ImGuiInputTextFlags` flags to ever be useful with `InputFloat()`/`InputInt()`. I think this was exposed for a few cases such as `ImGuiInputTextFlags_CharsHexadecimal` turning `InputInt()` or `InputScalar()` into hex display.

For now the button will be disabled but without visual feedback (not greyed out). The `ImGuiItemFlags_Disabled` facility is not exposed in the public API because we don't have that overall visual feedback yet.

**Comment by Remist0** [comment]
Thank you!
