### ISSUE TITLE
How to dynamically add items with listbox

### ISSUE THREAD

**Issue by Chaos192** [ocornut/imgui#2259]
Hello I am trying to write a simple app with imgui. I was wondering how to dynamically add items via user input.

 const char* listbox_items[] = { "Apple", "Banana", "Cherry", "Kiwi", "Mango", "Orange", "Pineapple", "Strawberry", "Watermelon" };
            static int listbox_item_current = 1;
            ImGui::ListBox("listbox\n(single select)", &listbox_item_current, listbox_items, IM_ARRAYSIZE(listbox_items), 4);

I saw this only and did a lot of googling but couldn't find any solution. Any help would be appreciated.

I'd like to be able to have a plus and minus imgui button that would add the item to the listbox or remove selected item from listbox.

i.e
ImGui::Button("+")
{
    // get data from textbox and add to listbox
}

ImGui::Button("-")
{
    // get selected item from listbox and remove it.
}

I know how to code this in C# with windows forms but not sure how to do it in C++ with imgui.. any help would be appreciated.

**Comment by DoctorGester** [comment]
This is not directly related to dear imgui.
You are providing 3 variables into the ImGui::ListBox call:
listbox_item_current
listbox_items
IM_ARRAYSIZE(listbox_items)

Since that code is called every frame all you need to do is make that container dynamic. You can use any kind of a dynamic container like std::vector.

**Comment by ocornut** [comment]
Hello @Chaos192, see DoctorGester answer. (Thank you Kirill!).

Please note that it is preferable and actually simpler to use ListBoxHeader/ListBoxFooter instead of `ListBox()` as you will be able to format your data without being stuck with the forced `char* []` signature of ListBox(). So your code would probably end up looking like:

```
ImGui::ListBoxHeader(...)
for (item : my_vector_containing_my_items)
{
   std::string& item_name = item.Name;
   if (ImGui::Selectable(s.c_str(), item.IsSelected))
   {
     // handle selection
   }
}
ImGui::ListBoxFooter()
```

(Info: ListBoxHeader/ListBoxFooter are essentially super early name for what now be called BeginListBox/EndListBox. I will proceed to rename them at some point but would have to reevaluate the API first).
