### ISSUE TITLE
gradients

### ISSUE THREAD

**Issue by codz01** [ocornut/imgui#234]
is it possible to draw gradient widgets  with frame color ?
like this
<img src='http://s4.postimg.org/vme4lphsd/imgui.png' border='0'  />

**Comment by ocornut** [comment]
Well it is possible as you've just done it :)
(I also done it as a test in one codebase a while ago, by hardcoding a Value alteration in HSV space)

I am not sure what would be the use for it and how it can be integrated in trunk. My intuition is that is it too short sighted to be used for quality and expressive re-skinning, I'd prefer to start from a quality theme/mockup and see if gradients are desirable and how to parametrize them. Do each object have multiple colors? Do we apply a modification in HSV-ish space? How are those modification parametrized? How do we decide what has a gradient and what hasn't? What happens when drawing objects of differents or non-standard sizes?

**Comment by codz01** [comment]
>> Well it is possible as you've just done it :)
its just a modified picture with gimp ;)
>> I am not sure what would be the use for it 
well its just an idea , but as you said  seems not easy to integrate such feature .

**Comment by ocornut** [comment]
When I work on the new design down the line I will re-evaluate how we can integrate gradients in a way that makes sense.

If you want to quickly hack something, in the AddRectFilled() function you can convert the color to HSV, modify it and create a second color to use for bottom-left and bottom-right.
