### ISSUE TITLE
How draw on main window?

### ISSUE THREAD

**Issue by letarg0** [ocornut/imgui#2342]
library is great. I compiling it on mac os x
sdl2 and Opengl

How I can draw directly on main window, for example line.
Where i must put this to example sdl opengl 
?
(i undestand the gui will draw on my draw in main window, but gui windows are movable)

```
        glLineWidth(20);
        glColor3f(0.80, 0.0, 1.0);

        glBegin(GL_LINES);
         glVertex2f(50, 80);
         glVertex2f(20, 20);
        glEnd();

        glLineWidth(12);
        glColor3f(1, 0.0, 0.0);
        glBegin(GL_LINES);
        glVertex2i(10,10);
        glVertex2i(200,320);
        glEnd();
```

**Comment by ice1000** [comment]
ImGui has API to do drawing, see the demo window -> Examples -> Custom rendering.
![image](https://user-images.githubusercontent.com/16398479/52597066-e3124500-2e1f-11e9-9636-97b24acefe5d.png)

Codes:
https://github.com/ocornut/imgui/blob/169e3981fdf037b179f1c7296548892ba7837dae/imgui_demo.cpp#L3871-L3978

**Comment by letarg0** [comment]
This draw on gui image not on main window
not background 
bottom all gui windows

**Comment by texrg** [comment]
Meybe normal SDL_ function working?
But where is SDL_Surface?

**Comment by ocornut** [comment]
Sorry this is an OpenGL question, not a dear imgui question.

**Comment by texrg** [comment]
imgui not have any way to draw on canvas=main window?

**Comment by dnotq** [comment]
You are looking for the foreground and background drawing lists.  They support some drawing primitives too, like lines, rects, circles, etc.  Check out the "Canvas" part of the imgui_demo.cpp, around line 7305 (version 1.84 WIP).  It is something like this:

`
ImVec2 window_pos = ImGui::GetWindowPos();
ImVec2 window_size = ImGui::GetWindowSize();
ImVec2 window_center = ImVec2(window_pos.x + window_size.x * 0.5f, window_pos.y + window_size.y * 0.5f);
ImGui::GetBackgroundDrawList()->AddCircle(window_center, window_size.x * 0.6f, IM_COL32(255, 0, 0, 200), 0, 10 + 4);
ImGui::GetForegroundDrawList()->AddCircle(window_center, window_size.y * 0.6f, IM_COL32(0, 255, 0, 200), 0, 10);
`

You can also implement your own drawing on the window using OpenGL.  Using the IMGUI bg/fg lists is nice though, since it is built-in and there is nothing to do but add your drawing code and render the UI as usual.

Look in imgui.h around line 2404 for the provided drawing functions.
