### ISSUE TITLE
Square/Block characters

### ISSUE THREAD

**Issue by kle622** [ocornut/imgui#235]
Hey guys,

I'm trying to render text but they are appearing in block characters. I'm using the example code from header file imgui_impl_glfw.h, anyone have any idea why this is? The code in my render loop is simply

        ImGui::Begin("abc");
        ImGui::Text("a\nb\nc");
        ImGui::End();

I feel really silly asking this but I couldn't find any issues on this. Any help would be great.

**Comment by ocornut** [comment]
It looks like your render state isn't set up to sample the texture that was created in ImGui_ImplGlfw_CreateDeviceObjects().  Assuming you are using vanilla imgui_impl_glfw.cpp and your OpenGL version is 3+ you may need to alter some states that are not reset by imgui_impl_glfw.cpp, most probably:
```
glUseProgram(0);
```
It is commented out in imgui_impl_glfw.cpp because that wouldn't compile with a classic OpenGL2 set of includes.

If it's not that, could you post a screenshot of your output to see the rest of the shapes?

**Comment by ocornut** [comment]
I'll close that now, let me know if you still have a problem.
