### ISSUE TITLE
Trouble creating a default docked layout

### ISSUE THREAD

**Issue by PetorSFZ** [ocornut/imgui#2357]
Cross-posting from discourse: [https://discourse.dearimgui.org/t/trouble-creating-a-default-docked-layout/204](https://discourse.dearimgui.org/t/trouble-creating-a-default-docked-layout/204)

I recently switched to the Docking branch of ImGui (currently running `09c9bf2edb1742941aeb2676a8198210b529059b`, i.e. the latest commit), and now I’m trying to create a default layout where windows are docked into each other. The only documentation I could find for doing this was [this post](https://github.com/ocornut/imgui/issues/2109#issuecomment-426204357). But when I try to follow it I trigger assertions inside ImGui.

I’m essentially doing something like this:

```cpp
bool dockSpaceCreated = ImGui::DockBuilderGetNode(mConsoleDockSpaceId) != nullptr;
if (!dockSpaceCreated) {
    mConsoleDockSpaceId = ImGui::GetID("ConsoleDockSpace");

    ImGui::DockBuilderRemoveNode(mConsoleDockSpaceId);
    ImGuiDockNodeFlags dockSpaceFlags = 0;
    dockSpaceFlags |= ImGuiDockNodeFlags_PassthruDockspace;
    ImGui::DockBuilderAddNode(mConsoleDockSpaceId, dockSpaceFlags);

    ImGuiID dockMain = mConsoleDockSpaceId;
    ImGuiID dockLeft = ImGui::DockBuilderSplitNode(dockMain, ImGuiDir_Left, 0.40f, NULL, &dockMain);

    // ...
}
```

At the call to `ImGui::DockBuilderSplitNode()` I get the assertion `IM_ASSERT(target_node->LastFrameAlive < g.FrameCount);` inside `ImGui::DockContextProcessDock()`, row `10628`.

So I guess my question is am I doing this correctly or is this a bug in the current version of ImGui? Also is there any documentation or examples I have missed for doing this?

**Comment by ocornut** [comment]
Hello Peter,

Thank you for the repro.

(A)
There was indeed an issue where creating a non-dockspace node would assert at the time of the split. The assert was modified as it was incorrect. 

Note that you may want to call `DockBuilderAddNode()` with the `ImGuiDockNodeFlags_Dockspace`. This flag didn't exist at the time I wrote the post you mentioned as it was implicit. Also check this newer post: https://github.com/ocornut/imgui/issues/2109#issuecomment-459409449.

In the current naming convention, a dockspace is hosted within a host window and will be explicitely submitted in code, whereas a normal node creates its own host window. May need to rework naming and/or documentation. If you don't pass the `ImGuiDockNodeFlags_Dockspace` flag your node will be floating.

(B)
Another issue is that `DockBuilderSplitNode()` didn't work if the node doesn't know its size.
In the previous API you had to pass a size to `DockBuilderAddNode()` and as you noticed that parameter was removed, but you can now call `DockBuilderSetNodeSize()`. Those are separate call because they are times where the programmer may want to preserve size/pos from stored settings (persistent or not).

At the time of fa0ce4b7d I came to the conclusion that initiating the split without knowing the size ahead was not possible, There maybe was a tricky/subtle reason maybe related to cross-session persistance into the .ini file. but unfortunately I forgot to write those details in the commit logs and I don't remember the reason anymore - perhaps it was a faulty reason? I am allowing it again and we'll see what happens. TL;DR; with the second commit you should NOT need to call `DockBuilderSetNodeSize()` and code above should now work.

**Comment by PetorSFZ** [comment]
With the latest commit I have now managed to create an initial docked layout. Thank you! :)
