### ISSUE TITLE
Cannot reorder docking tab (z-order issue?)

### ISSUE THREAD

**Issue by r-lyeh** [ocornut/imgui#2363]
At some point one of my tabs went out of focus even if no other tab was overlapping at all. Couldnt give that bar any kind of focus with mouse. Fixed it by reordering layout of surronding tabs. Cannot give repro steps for this.

_Originally posted by @r-lyeh in https://github.com/ocornut/imgui/issues/2353#issuecomment-464394136_

**Comment by r-lyeh** [comment]
I dunno if it is related to this very same issue but I found another tab of mine which, once docked, won't move or detach anymore. I suspect the two issues are related maybe?

PS: I'd like to create a small test case for this, but it may be just much easier if you just recompile my editor and give it a go? the tab that wont undock is the 'log' tab :D

**Comment by ocornut** [comment]
I cannot take the first bug without more information (screenshot/repro).

The second one we established your code was stealing the active widget every frame.

**Comment by r-lyeh** [comment]
Got a tab that was auto stealing focus and preventing from undocking. Thx Omar :D

**Comment by r-lyeh** [comment]
The issue persists after disabling all auto-focus code.
Oddly enough, these are the lines that prevent Log tab from undocking, ideas?

```C++
static ImGuiTextFilter filter;

ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, ImVec2(0,0));
filter.Draw("", -1);
ImGui::PopStyleVar();
```

**Comment by ocornut** [comment]
OK.

So, by using an empty ID `""` at the root of the window you are currently conflicting with the window itself which uses "window_name" as an ID for the tab. Your InputText will use "window_name" + "" which is the same.

You should always use an ID for your element, e.g
`filter.Draw("##blah", -1);`

I have an ongoing task to make tabs use a different ID e.g. ("window_name" + "##TAB") to make this kind of error less problematic.

Been also considering changing my mind on #1414 because even though there are legit use, people make this error of using empty ID too frequently.
