### ISSUE TITLE
Custom text rasterization

### ISSUE THREAD

**Issue by kg** [ocornut/imgui#2365]
**Version/Branch of Dear ImGui:**

Version: N/A
Branch: master

**My Issue/Question:**

Is there a standard/endorsed way for me to use a custom text layout/rasterization solution in imgui? I see that there is existing freetype integration, which is great - my underlying source of glyph bitmaps is freetype - but I have a full text layout & rendering stack with custom shaders and atlas generation I'd like to reuse w/imgui and I don't see a way to do it. This isn't mentioned in the FAQ anywhere. The main obstacle I see to using imgui directly is it seems like everything is built around having a single atlas (or a single atlas per font), which is incompatible with large font sizes and/or massive unique glyph counts for ideographic languages, etc. My existing system already handles this so it would be great to pipe everything through it.

The (generally inferior to dear imgui) imgui library I'm using right now has an internal command buffer representation that contains 'draw string' commands, so I intercept its command buffers and draw them directly through my graphics stack instead of having it hand me vertex/index buffers and textures. This lets me tap into all the existing rasterization work I've done for consistency with the game, and once I get harfbuzz/pango working it'll pick up on proper support for things like ligatures. Is it reasonable for me to try to do something similar with imgui, where I handle text rasterization (or even all rasterization operations, if necessary) myself instead of having imgui do it?

I know one obstacle is having accurate text metrics so things like the texteditor component work - the library I'm using has callbacks for that, so I implement the callbacks.

I'm open to having to make some changes to support this if you think it's reasonable to expect it of the library, but it's not clear to me whether dear imgui's design is remotely compatible with working this way.

**Comment by ocornut** [comment]
I think it would be rather difficult to implement. You may look into replacing the code in ImDrawList. However if your layout isn't extra cheap you are going to be bottleneck with harfbuzz/pango layout cost and you'll probably need to be caching lots of info (keyed by text contents + text settings). I believe that cost would be non-negligeable.

Dear ImGui relies on being able to draw many interleaved text and shape in a single draw call otherwise render performance will be mediocre, so whatever back-end you have probably needs to keep that feat available. At that point you would be better off completely replacing ImDrawList by a custom implementation (which could easily store high-level e.g. DrawString commands and geometry commands). 

I would generally advise against it right now, but if you are willing and fork and hack why not. It'll probably be even harder to get it in a mergeable state into mainline (past the potential runtime cost or even offering the option, the guaranteed cognitive and maintainance costs for me would likely be too redibitory), but may constitute a useful proof of concept. [tear imgui](https://github.com/jonvaldes/tear_imgui) did something like that I assume.

I am not ruling out transitioning toward a more high-level ImDrawList representation in the far-sh future (maybe 2.0). Though in my experience there's probably enough subtle coupling involved everywhere that a higher-level ImDrawList system would be mainly to facilitate e.g. network transport.

**Comment by kg** [comment]
High-level ImDrawList at least sounds closer to what I'd want to do. Gives me a place to start looking. I already have layout caching &c for the reasons you stated. I at least already have sorting and batching to merge draw calls, so that should help too as long as I can get the right info out of the draw list.

Not something I expect dear imgui to support, but I appreciate having some guidance on where to look.

**Comment by ocornut** [comment]
> Not something I expect dear imgui to support, but I appreciate having some guidance on where to look.

Look at imgui_draw.cpp this is where ImDrawList is implemented.

**Comment by ocornut** [comment]
@kg closing this as afaik there's nothing to do on dear imgui's side for now.

If you reimplement ImDrawList, consider the particular case of the `ShadeVertsXXX` function declared in imgui_internal.h. 

- From their point of view there's no distinction between text and non-text so this may be problematic. However in the current master and docking branch we curently only use them non-text vertices. (The old, not released docking v1 had a third shade function which worked on text)
- Their current api uses vertex index as a way to "tag" a position within the ImDrawList timeline. If the ImDrawList gets unpacked at render time we'll need to find a different way to identify that location.

We only use those twice in the codebase for fairly esoteric purpose so you probably don't need to focus on that aspect, just letting you know this will be something to solve if you want 100% compatible ImDrawList replacement.
