### ISSUE TITLE
Multiple selection and drag and drop

### ISSUE THREAD

**Issue by tanis2000** [ocornut/imgui#2390]
Is there a way to have multiple selection for items like buttons in a grid and drag and drop support?
Something along the lines of the drag and drop demo in the showcase window but with multiple selection would be exactly what I'm looking for. Is this achievable?

**Comment by ocornut** [comment]
Hello @tanis2000,

It is a bit of a ill defined problem and question, because selection patterns can be achieved in so many ways at the moment.
Based on the demo (e.g. Grid) you may just be able to implement your multi-selection storage and drag and drop pattern. What have you tried so far?

(Aside from your question, note that if you are deeply interested in the topic there is a experimental https://github.com/ocornut/imgui/tree/features/range_select branch which support a way to handle range-select (shift-click, shift-keyboard) along with clipping. I haven't posted anything about this branch yet and I expect the API to change, so it comes as-is, mostly if you feel like digging into selection patterns)

**Comment by tanis2000** [comment]
So far I've only got basic drag and drop working with single buttons, just like in the demo.

I could probably come up with a storage solution to keep the IDs of the selected buttons, but I would also like to do things like dragging over a couple of buttons and make them the selected ones all at once so that I can move them around my grid altogether. 

As far as I can understand the `BeginDragDropSource` function is working on the current ID so that means that it's the source of a single button.

**Comment by ocornut** [comment]
> but I would also like to do things like dragging over a couple of buttons and make them the selected ones all at once so that I can move them around my grid altogether.

This is the sort of stuff that the branch aim to solve but it doesn't handle rectangle-mouse-select. However it handle shift-plus-mouse-click-to-range-select.

> As far as I can understand the BeginDragDropSource function is working on the current ID so that means that it's the source of a single button.

The source doesn't matter, it is the payload which matter. You probably want to store your selection inside the payload and then use that data when handling the drop.

I haven't tried this very far yet so maybe there is a quirk or an issue but I think it should work.

**Comment by tanis2000** [comment]
I've sort of got selection by dragging a rectangle with a simple intersection check between the buttons on the grid and the area I've been dragging on. The code is simply the following:

```
          ImVec2 min = igGetItemRectMin();
          ImVec2 max = igGetItemRectMax();
          if (!(min.x > drag_selection_start.x + drag_selection_delta.x ||
              max.x < drag_selection_start.x ||
              min.y > drag_selection_start.y + drag_selection_delta.y ||
              max.y < drag_selection_start.y)) {
            binocle_log_info("selected %s", op->name);
          }
```

I still need to find out how to draw a nice highlight around those buttons.

And yeah, I also need to prevent the default drag & drop of the single selection fire up when I start dragging while the mouse is on top of a button.

**Comment by tanis2000** [comment]
I’m postong a quick update about my experiments.
So far I managed to get basic multi selection by dragging mouse working, even though I haven’t yet taken care of making it work with reversed starting point and dragging direction.

I also managed to carry around the IDs of the selected objects into the drag and drop paylod.

I had some troubles with telling the drag source to be active while I had a selection active and sometimes it bugs off. I still have to find out why.

Dropping the selection has some issues as you have to make copies of all the cells moving, otherwise you end up overwriting those that you still have to move :-P

Overall it’s coming along though
All in all it’s progressing

**Comment by ocornut** [comment]
The "Assets Browser" demo now merged as part of multi-select features allows box-selection and drag and drop of multiple selection, see https://github.com/ocornut/imgui/wiki/Multi-Select
![Multi-Select](https://github.com/ocornut/imgui/assets/8225057/442d5689-3e91-4771-9e25-498fbeb9ea32)

As your issue is one and rather wide I'll close it now but hopefully you should be able to achieve things closes to what you initially mentioned it.

**Comment by tanis2000** [comment]
Thanks @ocornut. I really appreciate all you are doing with this library. It's saved me countless times in the past few years. I will have a look at the new demo and see if there is something I can port into my editor when I have the chance. Cheers!

**Comment by 0x41337** [comment]
@ocornut and @tanis2000  image lasso select  is possible with imgui ?

**Comment by tanis2000** [comment]
@0x41337 you can achieve that but you will have to keep track of the widgets you are enclosing in the lasso yourself. At least that would be how I would do it as I have not yet looked into the latest changes mentioned by @ocornut
