### ISSUE TITLE
Draw graphics in the background

### ISSUE THREAD

**Issue by Riccsson** [ocornut/imgui#2391]
Hi.

Have used:
```
auto globalDrawlist = ImGui::GetOverlayDrawList();
globalDrawlist->AddRectFilled(pos1, pos2, ThemeColors.WindowBackground, 8.0f);
```

and so on to draw some loading progress bar and status in front of everything.

But now I am trying to draw some rectangles and circles in the main background but have no clue how to do that. I was trying something like this:
```

ImDrawList drawList(ImGui::GetDrawListSharedData());
drawList.AddRectFilledMultiColor(ImVec2(), ImGui::GetIO().DisplaySize, ThemeColors.MainBackground1, ThemeColors.MainBackground2, ThemeColors.MainBackground3, ThemeColors.MainBackground4); ImGui::AddDrawList(&drawList);
```

But I cant get it to work. Is there anyone how know how to do that? Thanks

**Comment by ocornut** [comment]
There's no function called `ImGui::AddDrawList(&drawList);` in imgui so you seem to be omitting information from your use case.

Indeed you need to be rendering this draw list in your render function.
You may just construct a ImDrawData structure and call your render function twice, that would be the easiest way at the moment.

This is a fairly common request so I may just go and add a helper `GetBackgroundDrawList()` function. I was hesitant with adding it because the `GetOverlayDrawlist()` function doesnt' have a trivial 1-to-1 equivalent in the multi-viewport branch, but think this already needs to be solved for GetOverlayDrawlist I may add the new function anyway.

**Comment by ocornut** [comment]
@Riccsson I have added a `GetBackgroundDrawList()` function now.
And `GetOverlayDrawList()` was renamed to `GetForegroundDrawList()` for consistency.

**Comment by Riccsson** [comment]
Work greats! Thanks!
