### ISSUE TITLE
Font character spacing settings

### ISSUE THREAD

**Issue by bagobor** [ocornut/imgui#242]
You are using hardcoded character spacing constant:
const int character_spacing_x = 1;
and then, when building font glyphs:
glyph.XAdvance = (signed short)(pc.xadvance + character_spacing_x);

That makes text blocks looks too spare.
So please move it to config :+1:

**Comment by ocornut** [comment]
Out of curiosity with what sort of font 1 isn't a good value?

I can move that number to the font atlas settings but it'll still be baked into glyphs (so as to maximize the speed of text size calculation which is a bottleneck for big, unclipped interfaces). So if there is a call to change it that call will have to go through glyphs.

**Comment by bagobor** [comment]
![spacing](https://cloud.githubusercontent.com/assets/708235/8067160/8ae6acf2-0ef4-11e5-883c-377702fc731a.png)

for me 0 looks _much_ better with default embeded font. win32/opengl
(but still suck with lack of hinting. )

**Comment by ocornut** [comment]
The AA branch now support this with the new ImFontConfig* settings.
All the AddFont**() functions now have a ImFontConfig* pointer. If you pass one you can alter settings. 

Incidentally you were correct about the spacing. The extra +1 spacing was more of a bug on my side that intentional, so the AA branch now include the default font with that +1 spacing.

Alter with:
```cpp
ImFontConfig font_cfg;
font_cfg.GlyphExtraSpacing.x = 2.0f
io.AddFontFromFileTTF("...tf", 20.0f, &font_cfg);
```

**Comment by ocornut** [comment]
This is now merged in master along with the entire new AA-branch. Note that it is a rather big update and you'll need to update your render function to use indexed vertex rendering.

**Comment by bagobor** [comment]
Nice work!
