### ISSUE TITLE
How to render video frame from ffmpeg or simple video without ffmpeg.

### ISSUE THREAD

**Issue by gdeverlant** [ocornut/imgui#2422]
I started this topic earlier inside of the screenshots thread and I apologize again for that @ocornut. This is a redirect of that thread which can be found here. Please do not post anything there furthermore.

Is it possible to render video either from ffmpeg decoded frames or just a plain mp4 file inside if ImGui?
If anyone achieved this it would be informative if he/she could share it with the community.

Best regards

**Comment by ocornut** [comment]
See FAQ entry:

https://github.com/ocornut/imgui/blob/master/imgui.cpp#L570

`Q: How can I display an image? What is ImTextureID, how does it works?`

Anything other than that is not a dear imgui question.
Getting individual frames from a video decoding library is a question for your video decoding library.
Upload those to a texture used by your 3D API (e.g OpenGL) is a question related to your 3D API.

There's not a simple answer unfortunately. 
Playing video in C++ land is not a trivial problem with a oneliner solution. There are variety of free solution e.g. libtheora each with their own complication. Either way, this question is best asked on a different place since 99% of the difficulty on this topic is not related to dear imgui.
Look up for e.g. "video player c++ library" on Google.

**Comment by ebachard** [comment]
@gdeverlant  : FYI, yes, it is possible to render video frame with and / or without ffmpeg using Dear ImGui. 
As example,  https://framagit.org/ericb/miniDart (I'm the author) or projects like imvlc and pbo-streaming, or even Pangolin

**Comment by gdeverlant** [comment]
Ohh that's really interesting! Thank you for your input it is really appreciated.

Do you have any other links for the projects you mentioned? I cannot find them on the web.

How advanced is this project of yours? Which problems did you encounter while trying to implement FFMPEG with Imgui?

Do you have a blog where you are detailing your evolution for this project?

**Comment by gdeverlant** [comment]
For:  https://framagit.org/ericb/miniDart

Is it possible right away to launch Visual Studio C++ and run your code?
Do we need to adapt it to a visual studio project by myself?
