### ISSUE TITLE
Adding some kind of DISPLAY LIST architecture with MouseEvents and KeyboardEvents for a hierarchy of visual object similar to the Stage in Flash.

### ISSUE THREAD

**Issue by gdeverlant** [ocornut/imgui#2427]
I was wondering why aren't we creating on top of the opengl mouse events and keyboard events some kind of event API in which we can register and unregister for each objects something like UIComponent.addEventListener(Event.EVENT_NAME, pointer * functionWhichHandlesTheEvent);

I think we should inspire ourselves from the Display list paradigm. I'm big fan of the Flash Event mechanism which was really well designed and it makes total sense. The events can be something like : 

The API description can be found on : 
https://help.adobe.com/en_US/as3/dev/WS9b644acd4ebe5999-600e9b8c122146b2fc5-8000.html

https://help.adobe.com/en_US/as3/dev/WS5b3ccc516d4fbf351e63e3d118a9b90204-7e3e.html

It can be a 2D and 3D display list with Keyboard and MouseEvent like : 

Event.MouseMove
Event.MouseWheel
Event.MouseReleaseOutside
Event.MouseOver
Event.MouseOut
Event.MouseClick
Event.MouseDoubleClick
Event.MouseUp
Event.MouseDown
Event.RollOut
Event.RollOver

Inspiration : https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/MouseEvent.html

and for the Keyboard events : 

https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/KeyboardEvent.html

**Comment by gdeverlant** [comment]
There will be an EventDispatcher which will be responsible of the event bubbling. More informations can be found at : 

![image](https://help.adobe.com/en_US/as3/dev/images/dp_stage_parent_Node.png)



https://help.adobe.com/en_US/as3/dev/WS5b3ccc516d4fbf351e63e3d118a9b90204-7dfb.html

**Comment by ocornut** [comment]
I am not sure why you are asking that at all and unfortunately I don’t really have the time and patience to be answering some random and somehow vague design suggestion that’s not clearly motivated by solving an issue.

**Comment by gdeverlant** [comment]
I'm asking that because I see that something is missing which should be the basic of any UI framework. Right now the handling of events are maybe causing many problems because there is no way to decide which UI component should receive events and which one should not be managed. It would be easier to think about the architecture of the code once there is an easy way to interact with the UI independently instead of seeing it as one flat plane.

**Comment by ocornut** [comment]
> I'm asking that because I see that something is missing which should be the basic of any UI framework

Dear ImGui is not "any UI framework" is a semi-experimental framework which turns many rules and expectation upside down compared to traditional frameworks.

> Right now the handling of events are maybe causing many problems

You are not being specific, I can't receive such vaguely formulated request for changing everything without a carefully constructed message that suggest you understand the design pillars of this library and you are a user of it. Your other messages on other threads suggest you are not yet a user of dear imgui and you are confused by it. This is fine, but this is probably not a good position to be throwing wide-reaching requests using "maybes" and "any UI framework" to make your point.

I have to close this now because I expect this is going nowhere.
