### ISSUE TITLE
How to change background and button and text color?

### ISSUE THREAD

**Issue by RaresM03** [ocornut/imgui#2440]
Pls help me.

**Comment by ocornut** [comment]
Sorry but #1586

**Comment by overdev** [comment]
Impressive how these people are creating fake repos only to create the impression they are interested programmers. As you mentioned in issue 1586, it is really easy to spot them. At this point you probably don't even have to care to answer them because I believe most supporters/contributors would gladly do it for you once or twice. I would.

(Sorry, I don't intend to extend the conversation. I'm just thinking with my hands on the keyboard.)

**Comment by WeskerPower** [comment]
Bro, hackers can program already, they dont need to ask questions about silly color changes, you know who does ? MEEEEEEEEEEEEEEEEEEEEEEE

Im trying to make a game and learning to code and all this posts do is bash on new users, im sorry i didnt wake up with the skill to change colors this morning, not like i didnt try it

![image](https://user-images.githubusercontent.com/15333431/82980399-fc0c1e80-9fae-11ea-8a12-282a3bb9c5a8.png)

+ google sent me to a hacking site because they had a layout of how to change some colors, sadly im trying to change 1 button to test it, not columns

+ im from Mexico, you guys should know better, you know theres people from all over the world that might not know english or how to scope headers, i got like 3 months of c++ doing Suraj tutorials with sfml, do i need to enter a secret discord for imgui questions or something, if i do just send me the link

hope i find something on google, also i got another question since im already posting i dont expect and answer just a #1586, but maybe ..... can i do a rpg inventory with imgui i just need a simple yes or no if you can be so kind, i doubt that helps me hack anything
