### ISSUE TITLE
imgui error 0xc000007b

### ISSUE THREAD

**Issue by uttam47** [ocornut/imgui#2444]
Hello everyone i am newbie to imgui and i was trying it for the very first time, That is why i tried to build the example(opengl3 and glfw), i got few errors about gl3w.h so i removed that file inclusion macro and  everything was fine on compilation but i got this crash program error 0xc000007b.(i am using glew for opengl initialization)

this is my linkng library order for glfw and other opengl stuff ..
libglew32.a
libglew32.dll.a
libglfw3.a
libopengl32.a
libgdi32.a
FreeImage.lib

i am building this thing on windows 10 64bit and i am using codeblocks.
i just tried for example but when it will be working i will use it in my game
![Untitled](https://user-images.githubusercontent.com/42665165/54864570-0dd8ad00-4d7f-11e9-8750-44509bd17510.jpg)which is not game yet.

i tried the opengl version 2 it worked for me but i really want to do it with opengl 3+(actually 4+).

**Comment by nicolasnoble** [comment]
Without a reproduction case that we can run ourselves, it'll be impossible to tell you what the problem is.

**Comment by ocornut** [comment]
Hello,

The one change you made is related to your error.
If you are using Glew you need to let the binding knows. This information is well documented if you read the binding.

In addition, you didn’t provide a callstack whereas the issue template is clearly requesting one.

O.

**Comment by uttam47** [comment]
Ok i will try to build against gl3w and see Will the error persists then I will Let you know. If get solved In that  case I would be doing something wrong with glew only rather then building against some wrong libraries.

**Comment by ocornut** [comment]
There’s no right or wrong library, you can keep using glew but you need to let imgui_impl_opengl3 know you are using glew.

I added more comments about it in a recent post 1.69 update.

Also note you have not filled the requested template with version number. All those factors suggest you are asking for help while not reading what is asked to you to ask for help. If you spent more time looking at the information already laid out in those files you’ll have solved your problem already.

**Comment by uttam47** [comment]
Ok i am sorry, i guess I just have to do some more digging in the documentation and as you suggest.

**Comment by uttam47** [comment]
i just did this (and linked the glew libraries)
#define IMGUI_IMPL_OPENGL_LOADER_GLEW
instead of this 
#define IMGUI_IMPL_OPENGL_LOADER_GL3W
in the imgui_impl_opengl3.h file
(sorry if i get this too simple)

do i have to do more stuff instead of what i did( ya i did read all those documentation you suggested to,so now i am looking up to you),
the very reason i am not posting the callstack here because, the application is not starting at all, i don't have anything in the name of segmentation fault in the debugger  or anything not a single variable value.

ya i am able to run the gl3w example(which simply shows that glew ruins it).

i am newbie here it means that i don't know whether this is going to be read by you people since it is a closed topic. So bare with me for now.

i read an issue in which you summoned someone by putting @ocornut  this so i am doing same for you, sorry if i am annoying you.(Because this kind of thing won't let me sleep in the night when i now that i am only one step away from my goal(in this case getting imgui in my game project))

**Comment by nicolasnoble** [comment]
The best way would be for you to create a repository on github where you put your project files and source code.

Ideally, we need to be able to clone the repository, open the project file using visual studio, build and see the error ourselves.

**Comment by uttam47** [comment]
ok this https://github.com/uttam47/imguiError is my repository on which i have uploaded all the files related to the project(The one in which i am having error) which is basically the demo of imgui glfw3 with glew, i don't know  this would work or not because i made my first ever repository for this purpose only and uploaded file using drag and drop option. I am using code::blocks you said that you would be testing it on visual studio as i know visual studio won't allow .a lib files and i am using .a files for glew in this project and my in game project(They worked there).  i have also uploaded all the libraries files and my project file too.

not related but i thought this would help just for  it worked with glad too but its only giving error with glew.

**Comment by uttam47** [comment]
here it is https://github.com/uttam47/imguiError i hope .a library files wouldn't give some error thing to visual studio(i am using code::blocks).

**Comment by nicolasnoble** [comment]
Right, I missed the part where you were saying this is a Code::Blocks project.

I am getting the same error on startup when using both Code::Blocks and Visual Studio. The error actually isn't coming from imgui. It's from Microsoft Windows, saying that the program failed to load that is, because it doesn't have the proper dependencies attached to it on your system. For instance, it may require a certain runtime to be installed, and the project settings aren't specifying any. The problem most likely comes from the prebuilt libraries you have chosen to download and use with your application. This may also be a discrepancy between the headers you are compiling with and the actual prebuilt libraries you are using. Your project has a slew of header files that are supposed to come from your system instead.

In all cases, this is basically a program build failure, not an imgui failure.

Few hints on how to get started:

- [Visual Studio Community Edition](https://visualstudio.microsoft.com/vs/community/) is a great, free tool. Its only gotcha is that you can only use it to work on open source projects. Code::Blocks at that point is a bit outdated, and hasn't managed to keep up very well.
- It's much more convenient to build all of the dependencies in your project instead of using prebuilt libraries. Both glfw and gl3w are fairly easy to build within your project files, and this will guarantee a consistent behavior across the board. In fact, the source for gl3w is [inside the imgui repository](https://github.com/ocornut/imgui/tree/master/examples/libs/gl3w/GL) directly, and it provides [prebuilt libraries](https://github.com/ocornut/imgui/tree/master/examples/libs/glfw) for glfw for Visual Studio.

Good luck!

**Comment by uttam47** [comment]
Thank you very much now I get it. I might spending my day on porting my project to visual Studio
