### ISSUE TITLE
Why is mouse position updated only on focused windows?

### ISSUE THREAD

**Issue by tomasiser** [ocornut/imgui#2445]
**Version/Branch of Dear ImGui:**

Branch: master, docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp, imgui_impl_win32.cpp

**My Issue/Question:**

Typically, at least on Windows, applications handle mouse interactions even when they are not focused. You can easily try it out with e.g., Calculator, Chrome, Total Commander. When you hover your mouse over buttons of these applications, they interactively change colors even if a completely different window is focused. (Yes, there are exceptions, for example Microsoft Paint, which does not handle mouse movements when not focused.)

The example ImGui implementations for GLFW and Win32 do not behave like this (I did not check others). When they are not focused, they completely ignore the mouse position.

It can easily be verified in the source codes:

[imgui_impl_glfw.cpp, line 233 (master)](https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_glfw.cpp#L233)
[imgui_impl_glfw.cpp, line 259 (docking)](https://github.com/ocornut/imgui/blob/docking/examples/imgui_impl_glfw.cpp#L259)
[imgui_impl_win32.cpp, line 143 (master)](https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_win32.cpp#L143)
[imgui_impl_win32.cpp, line 174 (docking)](https://github.com/ocornut/imgui/blob/docking/examples/imgui_impl_win32.cpp#L174) - this is more complicated

Now I would like to remove this behavior in my own implementation, but before I do that, I want to ask if there maybe was a specific reason why the focus checking is done in ImGui? I tried to remove the `if(focused)` check in the GLFW docking implementation and I did not notice any problems so far. I tried checking `git blame` history but could not find any specific bug that this would be linked to.

**Comment by ocornut** [comment]
I've been asking myself the same question recently.

The early version of the multi-viewport feature used coordinates relative to each viewports, which caused lots of complication, and I believe this logic and the subsequent iterations on viewports are a result of that. Since we switched to absolute coordinates it is probably not necessary and I can't recall of another reason at the moment.

Will need to investigate this a little more but if it works out and I see no issue I will probably remove that logic.

**Comment by tomasiser** [comment]
Thanks! I can do that change in my implementation in GLFW and let you know if I encounter any bugs caused by that. :-)

**Comment by kudaba** [comment]
I was doing a UX pass and also ran into this issue, so I just wanted to vote up for removing the focus test. It feels much nicer when you can mouse over and get a response even when the app isn't focused.

**Comment by tomasiser** [comment]
@kudaba I just compiled the code with the `if` check removed (glfw) and I did not run into any problems so far. If you are not developing anything serious that absolutely cannot ever have bugs, I guess you may try it as well. :) If we find any bugs related to that, I guess we can report them to @ocornut so he knows it is not safe to remove.

**Comment by ocornut** [comment]
I'd like to get back at fixing this soon.
(for ref, this was added in e.g. 25349b31d7ba93c6c1cab121696b71e1efc16e7c)

One of the other underlying reason is the support of drag and drop accross application.
Typically when clicking and dragging from SomeExternalApp over SomeImGuiApp window (even if our imgui app doesn't care about it), we need the imgui widgets to not react as hovered.. unless the dragged thing is a drag and drop payload that may be accepted. It may be possible for the application to use `BeginDragDropSource(ImGuiDragDropFlags_SourceExtern)` if the mouse is captured by another window which would be an extra responsibibity for the back-end.

The general, simpler problem if we ignore the possibility that mouse is being captured by another app, because we tend to query global mouse position directly. If we relied more on the mouse move events of different back-ends it would work more naturally as they tend to honor the possibility that another application may be capturing inputs, but then we get other troubles to solve with supporting multi-viewports. That's probably the easiest direction to fix..

**Comment by kudaba** [comment]
I've been running with it for a while and I haven't noticed an issues. However I'm on a one man project and my use case isn't that complex yet. Personally I tend to switch windows a lot and got accustomed to apps updating hover states when not in focus and clicking through.

I get the concern about not updating when dragging so the user doesn't think the app will accept it. I did a quick test among a few different apps with various mouse over and drag states and it seems about 60% or so (i.e. 3 out of 5) actually seem to adjust their behavior based on whether a drag action is happening or not. I suppose fixing imgui to globally adjust it's mouse behavior based on external drag state isn't a simple task.

Personally I would prefer to remove the if and have the app able to react to mouse movement over trying to protect against users thinking it can accept a drag drop. I feel the second would be a more rare case where the first makes the app feel unresponsive if it ever loses focus.

**Comment by tomasiser** [comment]
I noticed one issue last week but I do not have my laptop with me now so I cannot debug the problem. When there was a second viewport (a separate window popped out of the main window) placed *behind* the main window, the mouse actions for some reason got propagated towards the back window. Maybe it was already reported, I just noticed that a few days ago and it might be related to me removing the if(focused) in glfw. Sorry, I have no way of reproducing it now without my laptop. :-(

**Comment by ocornut** [comment]
It’s not just a matter of drag and drop. Literally activating anything else in any other window and moving the mouse while holding the button held is going to make imgui items react as hovered, or even react to presses on other buttons.

**Comment by kudaba** [comment]
Updated the PR to only set mouse position when windows is actually hovered. Thought the previous version would activate the hover when imgui was behind another window, it wouldn't react to clicks.

**Comment by ocornut** [comment]
I have pushed three commits to address this consistently in master branch:

SDL 1cdd110
GLFW 044fd0c
Win32 db686ad

- mouse pos is correct when clicking on our host window and dragging outside
- mouse pos is correct when not focused but hovered
- mouse pos is disabled when another window is focused and has capture
- when our window is focused we always report mouse coordinates (that's debatable).

Note that they won't work/merge with docking branch merge (will work on that tomorrow).

**Comment by ocornut** [comment]
This is now fixed for SDL, GLFW and Win32 in both single and multi-viewport mode. Finally closing! :)
