### ISSUE TITLE
Docking: issue with simultaneous setting of window and text input field focus

### ISSUE THREAD

**Issue by wolfpld** [ocornut/imgui#2453]
Version: 5a665e423c5a6dd4d7a327f1a85eaca299d343ef
Branch: docking

In [Tracy Profiler](https://bitbucket.org/wolfpld/tracy) I have a keyboard shortcut handling system, which is currently only used to open and/or focus a particular window and set the input focus on the text entry box:

```c++
if( shortcut ) ImGui::SetNextWindowFocus();
ImGui::Begin( ... );
if( shortcut ) ImGui::SetKeyboardFocusHere();
ImGui::InputTextWithHint( "###id", ..., ImGuiInputTextFlags_EnterReturnsTrue );
...
```

When this window is a floating one and it's not currently active, it becomes active and the entry field is focused, as expected.

When this window is a part of a tab-group and it is not the currently displayed tab ("tab" window focus doesn't seem to matter here), the shortcut action has to be taken twice, due to the following behavior:

1. The first time a shortcut is executed, the tab-group switches to the window tab (as a result of calling `SetNextWindowFocus()`), but the entry field does not become active.
2. The second time a shortcut is executed, the window is already the active tab and the text entry gains keyboard focus, due to `SetKeyboardFocusHere()` function call.

I would expect that both the tab becomes active and the text entry field gains focus at the same time, like in the floating window case.

**Comment by ocornut** [comment]
Hello @wolfpld and thank you for the report.

TL;;DR; Should be fixed.

Notes:
Because the selected tab is locked down early (when the tab bar is submitted), a newly focused window effectively only become visible in the next frame. In this case the window being hidden during its initial focus frame led to items being ignored, so `InputText()` wouldn't execute. 

This was incorrect: we have different reasons for hiding a window and in this situation items should not be ignored during the initial focus-request frame where the window is still hidden. This already worked when focusing via the tab bar interface but not via the programmatic path. I fixed that and clarified some of the underlying code.

Test code (added to WIP testing framework)

```
// Test setting focus on a docked window, and setting focus on a specific item inside. (#2453)
// In particular, while the selected tab is locked down early (causing a frame delay in the tab selection), 
// the window that has requested focus should allow items to be submitted (SkipItems==false) during its hidden frame,
// mimicking the behavior of any newly appearing window.
t = REGISTER_TEST("docking", "docking_focus_1");
t->Flags |= ImGuiTestFlags_NoAutoFinish;
t->GuiFunc = [](ImGuiTestContext* ctx)
{
    ImGuiTestGenericState& gs = ctx->GenericState;
    if (ctx->FrameCount == 0)
        gs.DockId = ctx->DockSetupBasicMulti(0, "AAAA", "BBBB", "CCCC", NULL);

    if (ctx->FrameCount == 10)  ImGui::SetNextWindowFocus();
    ImGui::Begin("AAAA");
    if (ctx->FrameCount == 10)  IM_CHECK(ImGui::IsWindowFocused());
    if (ctx->FrameCount == 10)  ImGui::SetKeyboardFocusHere();
    ImGui::InputText("Input", gs.Str1, IM_ARRAYSIZE(gs.Str1));
    if (ctx->FrameCount == 10)  IM_CHECK(!ImGui::IsItemActive());
    if (ctx->FrameCount == 11)  IM_CHECK(ImGui::IsItemActive());
    ImGui::End();

    if (ctx->FrameCount == 50)  ImGui::SetNextWindowFocus();
    ImGui::Begin("BBBB");
    if (ctx->FrameCount == 50)  IM_CHECK(ImGui::IsWindowFocused());
    if (ctx->FrameCount == 50)  ImGui::SetKeyboardFocusHere();
    ImGui::InputText("Input", gs.Str2, IM_ARRAYSIZE(gs.Str2));
    if (ctx->FrameCount == 50)  IM_CHECK(!ImGui::IsItemActive());
    if (ctx->FrameCount == 51)  IM_CHECK(ImGui::IsItemActive());
    ImGui::End();

    if (ctx->FrameCount == 60)
        ctx->Finish();
};
```

(I also went and fixed another trickier bug, where in the case a docked window stops being submitted, focus would be given back to the remaining top-most window one frame later than necessary, creating a behavior discrepency between docked and non-docked window. Not happy with the fix yet, but I identified a small network of smelly code that should be reworked.)

**Comment by ocornut** [comment]
Ping @wolfpld 
Let me know if you have time to check the fix, otherwise I'll probably close this, expecting it to be fixed. Feel free to comment if you still not into an issue (then I can re-open if needed). Thanks!

**Comment by wolfpld** [comment]
Confirming to be working as intended.
