### ISSUE TITLE
Mouse Wheel Smooth Scrolling 

### ISSUE THREAD

**Issue by Erfan-Ahmadi** [ocornut/imgui#2462]
I want to implement a simple smooth scrolling effect (same as the scrolling in Chrome and Mozilla browsing)

I've read imgui.cpp and the code that got my attention is: 
`window->Scroll = CalcNextScrollFromScrollTargetAndClamp(window, true)`

I know the scrolling  with mouse wheels happens here : 
`ImGui::UpdateMouseWheel()`

My question is how can I alter `window->ScrollTarget` to apply this effect, or is this the right way?

and I've seen an smooth scrolling happen with Joystick axis and It's nice but that's floating point axis and I don't think It's related.

**Comment by ocornut** [comment]
Hello Erfan,

Scrolling using the gamepad is more naturally continuous because you can hold the stick in a given direction, while a mouse wheel is a single event. Some OS/applications are turning mouse event into smooth scrolling which I agree is something we may want to add to dear imgui.

Because the code that uses e.g. `window->Scroll` `window->ScrollTarget` etc is used in many situation, including programatic scroll (which should be immediate), if you want to achieve smooth mouse wheel scroll I think the best way is to do it in `UpdateMouseWheel()` or in in your own application code.
In `UpdateMouseWheel()` instead of turning the mouse delta directly into a call to e.g. `SetWindowScrollY()` maybe store that amount of energy in a variable and trickle it over the scrolling over multiple frames.

Polish may involve:
- a way to ease in and ease out the velocity.
- a way to adjust velocity so it never feels like scroll is lagging behind (repeated/large amount of scrolling should always probably always finish in a same amount of time from the last user action)
- while allowing the scrolling to be interrupted immediately (change direction)

**Comment by Erfan-Ahmadi** [comment]
I've Implemented It by adding `ImVec2 ScrollNext` to `ImGuiWindow` Class

Edited the ImGui::UpdateMouseWheel()` function : 
```
if (!g.HoveredWindow || g.HoveredWindow->Collapsed)
		return;

ImGuiWindow* window = g.HoveredWindow;
while ((window->Flags & ImGuiWindowFlags_ChildWindow) && (window->Flags & ImGuiWindowFlags_NoScrollWithMouse) && !(window->Flags & ImGuiWindowFlags_NoScrollbar) && !(window->Flags & ImGuiWindowFlags_NoMouseInputs) && window->ParentWindow)
window = window->ParentWindow;

const float scroll_speed = ImFloor(window->CalcFontSize() * 100 * g.IO.DeltaTime + 0.5f);

if (window->ScrollNext.y > window->Scroll.y)
{
	const float next_scroll = window->Scroll.y + scroll_speed;
	SetWindowScrollY(window, (next_scroll <= window->ScrollNext.y) ? next_scroll : window->ScrollNext.y);
}
else if (window->ScrollNext.y < window->Scroll.y)
{
	const float next_scroll = window->Scroll.y - scroll_speed;
	SetWindowScrollY(window, (next_scroll >= window->ScrollNext.y) ? next_scroll : window->ScrollNext.y);
}

if (g.IO.MouseWheel == 0.0f && g.IO.MouseWheelH == 0.0f)
	return;
.
.
.
// Vertical Mouse Wheel Scrolling (hold Shift to scroll horizontally)
if (g.IO.MouseWheel != 0.0f && !g.IO.KeyShift)
{
	float scroll_step = ImFloor(ImMin(8 * window->CalcFontSize(), max_step.y));
	window->ScrollNext.y = window->Scroll.y - g.IO.MouseWheel * scroll_step;
	//SetWindowScrollY(window, window->Scroll.y - g.IO.MouseWheel * scroll_step);
}
```

It works quite nice unless when you want to scroll fast meaning scroll speed should increase by rapid scroll requests.
so there is going to be a timer to check how much time has passed since the last scroll and if it is larger than min_release_time (in this example 300 ms) the speed should be reset and otherwise with each iteration if scrolling it should be increased.

In this example I used std::chorno timer : 
```
if (!g.HoveredWindow || g.HoveredWindow->Collapsed)
	return;


if (wheel_is_scrolling)
{
	ImGuiWindow* window = g.HoveredWindow;
	while ((window->Flags & ImGuiWindowFlags_ChildWindow) && (window->Flags & 	ImGuiWindowFlags_NoScrollWithMouse) && !(window->Flags & ImGuiWindowFlags_NoScrollbar) && !		(window->Flags & ImGuiWindowFlags_NoMouseInputs) && window->ParentWindow)
	window = window->ParentWindow;
        auto duration = std::chrono::duration_cast<std::chrono::milliseconds>
		(std::chrono::high_resolution_clock::now() - last_scroll).count() / 1000.0f;

	if (duration > min_scroll_release_time)
	{
		//Refresh Scroll Speed
		scroll_speed = ImFloor(window->CalcFontSize() * 100 * g.IO.DeltaTime + 0.5f);
		wheel_is_scrolling = false;
	}

	if (window->ScrollNext.y > window->Scroll.y)
	{
		const float next_scroll = window->Scroll.y + scroll_speed;
		SetWindowScrollY(window, (next_scroll <= window->ScrollNext.y) ? next_scroll : window->ScrollNext.y);
	}
	else if (window->ScrollNext.y < window->Scroll.y)
	{
		const float next_scroll = window->Scroll.y - scroll_speed;
		SetWindowScrollY(window, (next_scroll >= window->ScrollNext.y) ? next_scroll : window->ScrollNext.y);
	}
}

if (g.IO.MouseWheel == 0.0f && g.IO.MouseWheelH == 0.0f)
	return;
.
.
.

if (g.IO.MouseWheel != 0.0f && !g.IO.KeyShift)
{
	float scroll_step = ImFloor(ImMin(8 * window->CalcFontSize(), max_step.y));
	window->ScrollNext.y = window->Scroll.y - g.IO.MouseWheel * scroll_step;

	wheel_is_scrolling = true;

	scroll_speed += scroll_speed_step;

	if (scroll_speed > max_scroll_speed)
		scroll_speed = max_scroll_speed;

	last_scroll = std::chrono::high_resolution_clock::now();
}
```

And It works perfectly, Exactly what I wanted :)

I'm open to suggestions for optimizing since I only wrote it to work.

**Comment by HackerDaGreat57** [comment]
Is there a PR for this or is it not implemented in Dear Imgui "Vanilla" aka the official release?
