### ISSUE TITLE
Empty buffer InputText

### ISSUE THREAD

**Issue by qE6** [ocornut/imgui#2487]
`char buf[15] = { 0 };
			ImGui::InputText("Name", buf, IM_ARRAYSIZE(buf));
			if (ImGui::Button("Load", ImVec2(80, 23)))
			{
				//anything do
			}
			ImGui::SameLine();
			if (ImGui::Button("Save", ImVec2(73, 23))) {
				//anything do
			}`

My variable buf every time is empty. Why?
Im need copy text from InputText to my buf.

**Comment by NexSqaud** [comment]
try this 
ImGui::InputText("Name", &buf, IM_ARRAYSIZE(buf));

**Comment by qE6** [comment]
@NexSqaud Are you kidding me? See constructor.

**Comment by DJLink** [comment]
Was just trying your sample code 
```
char buf[15] = { 0 }; ImGui::InputText("Name", buf, IM_ARRAYSIZE(buf));
```

and after putting text on the input box "buf" has the text i wrote in it too. Could you debug or print the buf contents when InputText() returns true? 

![image](https://user-images.githubusercontent.com/423769/56019600-feed7680-5cfc-11e9-88fe-009c2953aaf3.png)

Also keep in mind that next time frame loops buf will be empty again because it's being declared every single frame. if you wanna save what user wrote in InputText persistently either save buf contents somewhere else or make buf a static var.

**Comment by ocornut** [comment]
> Also keep in mind that next time frame loops buf will be empty again because it's being declared every single frame. if you wanna save what user wrote in InputText persistently either save buf contents somewhere else or make buf a static var.

This, exactly.
And as per our long standing rule, sorry but #1586.
