### ISSUE TITLE
SliderFloat3 2nd Parameter

### ISSUE THREAD

**Issue by calioranged** [ocornut/imgui#2488]
`ImGui::SliderFloat3(const char* label, float v[3], float v_min, float v_max, const char* display_format, float power)`

What should go into the second parameter? Unfortunately there doesn't appear to be any explanation of this function ImGui files so I am unsure of what float v[3] should represent.

**Comment by ocornut** [comment]
imgui.h about this says:

> // - For all the Float2/Float3/Float4/Int2/Int3/Int4 versions of every functions, note that a 'float v[X]' function argument is the same as 'float* v', the array syntax is just a way to document the number of elements that are expected to be accessible. You can pass address of your first element out of a contiguous set, e.g. &myvector.x

More-over, imgui_demo.cpp demonstrates `SliderFloat3` and similar functions in multiple spots.

**Comment by calioranged** [comment]
I am just simply rendering a square via a _vertices_ and _indices_ array:

`		// Positions:
		std::array<float,8> vertices
		=	{
			1.0F,-1.0F,
			1.0F, 0.0F,
			0.0F, 0.0F,
			0.0F,-1.0F
			};

		// Indices:
		std::array<unsigned short int,6> indices
		=	{
			0,1,2,
			2,3,0
			};`

What syntax will allow me to adjust the position of the square?

**Comment by ocornut** [comment]
This is a C++ question not a dear imgui question.

Probably either `vertices.pointer()` or `&vertices[0]` would work.

**Comment by calioranged** [comment]
I tried both of those and neither work.

`ImGui::SliderFloat3("Slider",&vertices[0], -1.0F, 1.0F);`

Is there anything visibly wrong with this code?

**Comment by calioranged** [comment]
> This is a C++ question not a dear imgui question.

But surely you want people to understand how to use the tool that you must have spent a lot of time developing? Especially seeming as though the documentation is so limited.

**Comment by ocornut** [comment]
> Is there anything visibly wrong with this code?

I think it is correct, but since you are not providing any more information (actual compiler errors, compiler type, OS) you are leaving us to guess what is happening on your side.

I do want people to understand but I can't micro manage and hold the hands of everyone who is learning C++. There's plenty of examples of what you are asking for and the fact you haven't stumbled on them and you are not providing compiler error messages mostly suggest that you are not reading and searching the information readily available, not reading what is being explicitely asked of you when creating a new issue.

**Comment by calioranged** [comment]
> There's plenty of examples of what you are asking for and the fact you haven't stumbled on them

I always search Google for as long as possible before posting on forums because I know that experienced programmers often get upset with beginner questions. I genuinely haven't found a single thing online that properly explains how to use this function.

If there are plenty of examples that properly explain how to use this function then can you at least point me towards one and I will read through that and not bother you again. I just want to learn how to use this one function and then I will be happy. 

> you are not providing compiler error messages

There are no compiler error messages, if there were I would have provided one. 

> I do want people to understand but I can't micro manage and hold the hands of everyone who is learning C++.

Okay I understand that and I'm sorry if my questions came across in a way that made you feel you were micro managing me.

**Comment by ocornut** [comment]
> If there are plenty of examples that properly explain how to use this function then can you at least point me towards one and I will read through that and not bother you again. I just want to learn how to use this one function and then I will be happy.

You must be kidding me, because I answered exactly this above.

"imgui_demo.cpp demonstrates SliderFloat3 and similar functions in multiple spots."

In addition, the FAQ explicitely says to look at imgui.h and imgui_demo.cpp and you are telling me you are using Google.

> There are no compiler error messages, if there were I would have provided one. The only issue I am having is that when I move the slider, it doesn't move the square that I have rendered.

Then imgui is working and the fault is somewhere else, it is a problem in your own app. Those values you are editing are not mapping to your actually displayed vertices. Making this thread more than closed.

**Comment by calioranged** [comment]
Your notion of a proper explanation has been severely distorted my friend. I'm sure that ImGui is brilliant for those who have at least intermediate experience but for beginners the 'documentation' is so limited and brief that you have to resort to this site to get any kind of understanding of how it works. Also the demo.cpp file is again so brief that I don't even know how to use it. It says 'you can call ImGui::ShowDemoWindow() in your code to learn about various features of ImGui' but when I called ImGui::ShowDemoWindow() I get an exception on the line - "window->DrawList->PushTextureID(g.Font->ContainerAtlas->TexID);" 

Like I say, your notion of a proper explanation is incompatible with that of the average beginner. 

Yes I used Google and I also looked through the ImGui files as well (you can do both, not necessarily one or the other). Like I said the explanations are incredibly brief and not suitable for beginners. 

All that said, I think ImGui is a great tool and with some more thorough documentation it could be accessible to all. Thanks for making it and have a good weekend.

**Comment by nicolasnoble** [comment]
Because antagonizing the author is definitely going to produce results.

The explanations are not needed in the sense that you can see the code in action, and tweak it to understand what happens. You can even do it in real time using visual studio's edit and continue system. The demo covers absolutely every single usage of the code. 

Now, all of this being said, imgui is definitely a complicated product due to its nature. It's not necessarily geared towards C++ beginners. And if you can't figure out what things do by simply using the demo and toying with it, maybe this isn't the product you want. I personally haven't read a single line of documentation about imgui, and I was able to just use it as is just by including the demo in my code. So your anecdotal experience doesn't match my anecdotal experience.

**Comment by calioranged** [comment]
> Because antagonising the author is definitely going to produce results.

That is definitely not my intention.  I can only apologise if this is how it comes across. I just think that his definition of a 'proper explanation' is completely different to mine. 

> The explanations are not needed in the sense that you can see the code in action, and tweak it to understand what happens. You can even do it in real time using visual studio's edit and continue system. The demo covers absolutely every single usage of the code.

Well as I said in my previous message I'm not even sure how to use the demo. The only instruction on how to use is - "you can call ImGui::ShowDemoWindow() in your code to learn about various features of ImGui". When I called ImGui::ShowDemoWindow(), it threw an exception on the line - "window->DrawList->PushTextureID(g.Font->ContainerAtlas->TexID);". 

> if you can't figure out what things do by simply using the demo and toying with it, maybe this isn't the product you want

You are probably right but I think it's a really useful tool and I obviously aspire to be able to use it.

> your anecdotal experience doesn't match my anecdotal experience

Well I am not sure how experienced you are so a comparison between our anecdotal experiences may be worthless unless you have been learning for under a year (as I have). If you have been learning for under a year then fair enough you have understood this much quicker and easier than I have.

Reading back through my comments I see that I have perhaps come across as a bit ungrateful. As I said at the start of this message I am sorry for this.

**Comment by ocornut** [comment]
> When I called ImGui::ShowDemoWindow(), it threw an exception on the line - "window->DrawList->PushTextureID(g.Font->ContainerAtlas->TexID);".

You haven't integrated dear imgui properly in your app or you aren't calling it from within your main loop.

There are many examples of how to integrate imgui in the examples/ folder and you should first try to build and run those. Those examples are calling ShowDemoWindow().

There are even precompiled binaries of the demo linked in the Readme for people who want to have a quick look at the result of the demo without compiling it. But you should really aim to build one of those examples/ application. We don't even know which OS/compiler you are working with in order to assist you with building the demos. In your three posts here you haven't answered the questions requested by the Issue Template (that alone as clearly stated in the Guidelines Issue Template should be a motive for me to block you, it means you don't value our time as much as yours).

Most of your issues (including other posts) stem from being unfamiliar with C/C++. Every one of us had to start somewhere so we understand and appreciate your situation. However even in good faith, many of the questions you are asking aren't dear imgui specific questions but questions that could be asked and answered on any programming forums catered to help people learning the language.

**Comment by calioranged** [comment]
> We don't even know which OS/compiler you are working with in order to assist you with building the demos. In your three posts here you haven't answered the questions requested by the Guidelines & Issue Template (that alone as clearly stated in the Guidelines & Issue Template should be a motive for me to block you, it means you don't value our time as much as yours).

I think a lot of what you have said there is harsh. None of the questions that I have asked have been about errors, they have all been asking for further (or initial) explanations on ImGui functions. If my questions were in relation to errors then I could understand your complaint. If you want to block me that is fine but I have to say that it would be a pretty baffling response to somebody who is simply trying to learn how to use a tool you developed.

> Most of your issues (including other posts) stem from being unfamiliar with C/C++.

Again I disagree. They stem from a lack of ImGui documentation and (what I would regard as) proper explanations. You go to function definitions and declarations and there is just no explanation most of the time (hence why all three of my posts have been requesting further information rather than asking for assistance with debugging errors). What limited explanations are given are scattered throughout many different files and I have a hard time believing that you honestly regard the documentation as ideal or frankly anything close to ideal. I understand that your time is most likely stretched and that if you had the time to provide better documentation I'm sure you would so please don't think I am being ungrateful, I am simply responding to your assertion that I can't use ImGui due to unfamiliarity with C/C++. This is absolutely not the core reason that I have to post on here asking for further explanations of ImGui functions.

This will be my last message here as I feel I'm beating a dead horse, so allow me to just thank you for the time you have spent developing ImGui and for the time you have spent on this issue (and others) trying to steer me towards understanding how to use this tool. I am grateful and hopefully that isn't lost on you.

**Comment by ocornut** [comment]
> None of the questions that I have asked have been about errors, they have all been asking for further (or initial) explanations on ImGui functions. If my questions were in relation to errors then I could understand your complaint.

You are right, this was an unfair statement given nature of the questions asked. 

The first question of the FAQ explicitely state:

"
**Frequently Asked Question (FAQ)**
_Where is the documentation?_
This library is poorly documented at the moment and expects of the user to be acquainted with C/C++.
"

Then goes on to say you have to run examples and the demo code. If you didn't succeed in doing so, your first question maybe should have been to ask for help on those specific matters, as running the interactive demo is key to ease understanding of most of dear imgui. Instead it tooks three threads and various messages for you to admit you didn't run the demo code. You can't ask for other explanation if you skip the essential first step.

The SliderXXX function take a pointer to `float` and your question was worded suggesting you couldn't get a pointer out of an `std::array<float>`. Then it turns out your problem is probably something completely different - as is, in your case seemingly ImGui is doing his job, but you are not seeing a link between the values you are editing and your expected result, probably because they are not the same value and then your problem is not a dear imgui problem. 

It's hard to waddle through that given how vague some messages are, until your third message we would just assume your code wouldn't even compile where apparently it did and imgui worked.

**Comment by calioranged** [comment]
You are right I should have made my first issue about getting the demo up and running. I now have the SliderFloat function working so I will try and get the demo working and then hopefully won't need to badger this site with questions. Thanks again.
