### ISSUE TITLE
ComboBox is showing weird current item text

### ISSUE THREAD

**Issue by RarePotato8DE** [ocornut/imgui#2499]
(Click "Preview" to turn any http URL into a clickable link)

1. PLEASE CAREFULLY READ:
https://github.com/ocornut/imgui/issues/2261

2. IF YOU ARE HAVING AN ISSUE COMPILING/LINKING/RUNNING/LOADING FONTS, please post on the "Getting Started" Discourse forum:
https://discourse.dearimgui.org

3. PLEASE MAKE SURE that you have: read the FAQ in imgui.cpp; explored the contents of `ShowDemoWindow()` including the Examples menu; searched among Issues; used your IDE to search for keywords in all sources and text files; and read the link provided in (1).

4. Be mindful that messages are being sent to the e-mail box of "Watching" users. Try to proof-read your messages before sending them. Edits are not seen by those users.

5. Delete points 1-5 and PLEASE FILL THE TEMPLATE BELOW before submitting your issue.

Thank you!

----

_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**

Version: XXX
Branch: XXX _(master/viewport/docking/etc.)_

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_XXX.cpp + imgui_impl_XXX.cpp _(or specify if using a custom engine/back-end)_
Compiler: XXX _(if the question is related to building or platform specific features)_
Operating System: XXX

**My Issue/Question:**

XXX _(please provide as much context as possible)_

**Screenshots/Video**

XXX _(you can drag files here)_

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// Please do not forget this!
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```
Hey, so I am trying to implement configs in a program of mine.
For that I wanted to make a comboBox with configs, my problem is that it shows something weird.
I used https://github.com/ocornut/imgui/issues/1658 for the "base".
This is my current code:
`
if (ImGui::BeginCombo("##combo", current_item)) // The second parameter is the label previewed before opening the combo.
				{
					for (int n = 0; n < items2.size(); n++)
					{
						bool is_selected = (current_item == items[n]); // You can store your selection however you want, outside or inside your objects
						if (ImGui::Selectable(items[n], is_selected))
						{
							current_item = items2.at(n).c_str();
							//current_item = items[n];
							std::cout << current_item << std::endl;
							std::cout << items[n] << std::endl;
							std::cout << items2.at(n).c_str() << std::endl;
						}
						if (is_selected)
							ImGui::SetItemDefaultFocus();   // You may set the initial focus when opening the combo (scrolling + for keyboard navigation support)
					}
					ImGui::EndCombo();
				}
`
items2 is 3 in this case (its a vector<std::string> that included all of my config(names)).
But we focus on the relevant code:
`	
						current_item = items2.at(n).c_str();
							//current_item = items[n];
							std::cout << current_item << std::endl;
							std::cout << items[n] << std::endl;
							std::cout << items2.at(n).c_str() << std::endl;
`
All of these couts are printing the right values, current_item is right, but the preview is just.. weird.
I have literly no clue whats wrong.
Attached a video of the problem.
![github](https://user-images.githubusercontent.com/39445589/56166181-31d18c00-5fd5-11e9-9b72-676e3664fb71.gif)
Thanks for reading.

**Comment by ocornut** [comment]
Hello,

Before I block you for blatantly ignoring the issue template, the issue guidelines as well as being a cheater (sorry but #1586), I will make an exception because you put a little bit of effort showing code and making a gif.

When you get the raw pointer from a std::string using c_str(), this pointer is only valid as long as the string doesn’t move in memory and as long as it is not being modified. In your case, we can’t tell from the code extract what the lifetime of items2[n] is but given the result you get you are making a mistake with understanding the lifetime of your objects.

The simplest way to deal with that is to copy whole std::string instead of just holding on raw pointers to std::string that may move. Replacing current_item by a string may do the job. 

However it would also be more correct and less error prone to not take a pointer nor make a copy of the string, but rather remember your selection via another mean, eg: storing the **index** of current selection, and at the ComboBox call site retrieving the string pointer from the index.

Please note that none of this is a dear imgui problem but rather a C++ issue. You can ask more questions and maybe get more answers on general programming forums, this is not really the place.

Regards.
