### ISSUE TITLE
Horizontal scrollbar when using ListBoxHeader

### ISSUE THREAD

**Issue by timweckx** [ocornut/imgui#2510]
Version: 1.68 WIP
Branch: docking
Back-ends: glfw_opengl3
OS: Windows

I'm trying to get a horizontal scrollbar when using ListBoxHeader/ListBoxFooter so I can scroll horizontally when items inside the listbox are wider then the actual listbox window. (I'm not using the standard ListBox because I don't want selectable items and I want to control the listbox width/height myself.)

I've been able to get the desired behavior, by adding ImGuiWindowFlags_HorizontalScrollbar flag to the BeginChildFrame call inside the ListBoxHeader method (imgui_widgets.cpp). But I'd rather not modify any of the core imgui code. 

Is there a other / better way to accomplish this?

Modification:
`BeginChildFrame(id, frame_bb.GetSize(), ImGuiWindowFlags_HorizontalScrollbar);`

Example using it (modified from imgui_demo.cpp)
```
const char* listbox_items[] = { "A fruit with a very long name so it makes sense to have a scrollbar", "Banana", "Cherry", "Kiwi", "Mango", "Orange", "Pineapple", "Strawberry", "Watermelon" };
if (ImGui::ListBoxHeader("listbox\n(horiz scroll", ImVec2(200, 60))) {
    for (int i=0; i<IM_ARRAYSIZE(listbox_items); i++){
        ImGui::Text(listbox_items[i]);
    }
    ImGui::ListBoxFooter();
}
```
![image](https://user-images.githubusercontent.com/12955400/56599257-6e901b00-65b3-11e9-9684-84e11b152cc9.png)

**Comment by ocornut** [comment]
Hello,

This makes sense. 

I don't have a good answer for you, other than the fact that ListBoxHeader/ListBoxFooter are old api and I am aiming at replacing them with properly named functions e.g. `BeginListBox()`. So knowing about this use case would help designing those new functions. I haven't renamed them yet because I sensed switching to new named API would be a good occasion to improve their api.

Most of the overhead in `ListBoxHeader()` is solely to allow to use `IsItemXXX` function on the whole listbox, but note that you can use `BeginChildFrame`+`SameLine`+`Text` with essentially the same effect, and then you can freely pass that flag to the function. In other word, you may as well give up using ListBoxHeader and rely on the lower level functions.

**Comment by timweckx** [comment]
That makes sense. I'll look into using BeginChildFrame directly for now.

Thank you, and I'm really enjoying the library!

**Comment by ocornut** [comment]
Please note that `BeginChildFrame()` now has been obsoleted in favor of using BeginChild() with the `ImGuiChildFlags_FrameStyle` flag. See commit cdbc21a191e4d3622881ed9d9da29e3a463f0a35.

Also note that `ListBoxHeader()` was renamed to `BeginListBox()` on 2023-05-31 and is now merely a thin helper to call `BeginChild()` with `ImGuiChildFlags_FrameStyle` + display a label. You may be tempted to use `BeginChild()` directly in some use cases.
