### ISSUE TITLE
Correct use of ImGui_ImplGlfw_NewFrame with multiple ImGui contexts, and g_Time

### ISSUE THREAD

**Issue by Jarreddebeer** [ocornut/imgui#2526]
**Version/Branch of Dear ImGui:**

Version: 7e67aba286b21acb802ffbdc0b32c1f86e1f4122
Branch: Docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp 
Operating System: OSX

**My Issue/Question:**

This may be related to #2004, but I am unsure. 

In my application I have pointers to two ImGui contexts. In the main loop I call ```ImGui_ImplGlfw_NewFrame()``` once for each context. Perhaps I should not be doing that, but I assumed it would be needed since it sets up ```ImGuiIO``` properties and ```ImGuiIO``` is taken from the context.

I noticed in ```imgui_impl_glfw.cpp``` ```g_Time``` is static and overwritten by each ```ImGui_ImplGlfw_NewFrame()``` with the following code:

```
// Setup time step
double current_time = glfwGetTime();
io.DeltaTime = g_Time > 0.0 ? (float)(current_time - g_Time) : (float)(1.0f/60.0f);
g_Time = current_time;
```
When ```io.DeltaTime``` is set using ```current_time - g_time``` the value of ```g_Time``` has been mutated by the previous context  with ```g_Time = current_time```.

Because of this each context's ```g.Time``` values are sliced. If my app runs for 10 seconds the first context will clock up 9.8 seconds while the second context clocks up 0.2 seconds. The time accumulation is done in ```ImGui::NewFrame()``` with ```g.Time += g.IO.DeltaTime;```.

The problem is that ```g.Time``` events like double click are distorted:

```imgui.cpp``` ```ImGui::UpdateMouseInputs()```:
```if ((float)(g.Time - g.IO.MouseClickedTime[i]) < g.IO.MouseDoubleClickTime) {```

```g.IO.MouseDoubleClickTime``` is 0.3, which can take a long time to elapse for ctxB and so mostly every second click becomes a double click.

I think my understanding of using multiple contexts is incorrect. Am I doing it wrong? Should I be editing the static variables in imgui_impl_glfw.cpp to cater for context?

Thanks,

**Comment by ocornut** [comment]
You are correct this is similar to #2004 and the example back-ends should be reworked to support multi-context better. 

Right now much of the work has been instead put oh multi-viewports which in common scenario (but not all) is a better solution that multi-context.

I think you could consider fixing the back-end but it would also be worthwhile to explain your need for multi-contexts in order to make sure you are not using them in a situation where another solution would work better.

**Comment by Jarreddebeer** [comment]
Thanks,

> it would also be worthwhile to explain your need for multi-contexts in order to make sure you are not using them in a situation where another solution would work better.

I have a feeling multi-viewports might be the better solution (though at this point I still need to understand how they work).

In the app I have a layout context with Dockable ImGui windows. Then there is a scene context which is a little world created using the ImGui::DrawList api. There are multiple 'viewports' into the scene. These viewports are ImGui Windows from the layout context.

The scene context is isolated because of its own world coordinates. It is tricked into this by transforming mouse positions, enlarging the display size so ImGui Widgets can be IsItemHoverable(), etc. It is generated once per loop and bounding box ImRects are kept for each 'viewport'. A render method uses the ImRects to set the orthographic projection matrix and render on top of the respective layout context's windows.

Isolating the contexts as i have done has felt hacky but it works. Perhaps multi-viewports is better? If you think a fix to g_Time would be useful i'd be happy to look into it.

**Comment by romenhurst** [comment]
> I think you could consider fixing the back-end but it would also be worthwhile to explain your need for multi-contexts in order to make sure you are not using them in a situation where another solution would work better.

As per your suggestion on [Stack Overflow](https://stackoverflow.com/a/57465207/9516968) I am posting my specific use-case for multiple Dear ImGui contexts in GLFW.

I have a program that must detect one or more GigEVision cameras and open windows for each of them. Each window has its own ImGui context and due to other requirements these windows are created on separate threads with their own event loops. Therefore I needed ImGui to handle input per-thread as well.

My (hacky) solution was to modify `imgui_impl_glfw.h` and `imgu_impl_opengl3.h` to use `thread_local` storage for all of the variables found in those files. Then I defined `GImGui` as a `thread_local` context pointer in `imconfig.h`. This solution appears to be OK for my specific case, since each window is entirely independent and the GLFW and ImGui functions are only called from the threads managing those windows.

**Comment by ocornut** [comment]
FYI with 70c6038 + 4cec3a0 all backends are now storing and pulling their state from the main imgui context so it should now be solved.
