### ISSUE TITLE
How do I set the next  window position and size, but still be able to move/scale it?

### ISSUE THREAD

**Issue by ChrisMGeo** [ocornut/imgui#2554]
**Version/Branch of Dear ImGui:**

Version: Latest
Branch: master

**My Issue/Question:**
Hello I'm pretty new to ImGui and C++ in general, so please do forgive me if this question is irritating. Also I am not sure whether this is the correct place to ask this question., so please do tell me if this isn't the place to ask a question like this.

I'm making windows in ImGui and am trying to make some windows for a basic demo, and found the `ImGui::SetNextWindowPos()`&`ImGui::SetNextWindowSize()` functions and am using them. The actual resizing and positioning works however after they are rendered I can't change them i.e.resize or move them. I am guessing this is because the rendering is being done in a while loop, but what should I do for changing it's pos and size using these functions but still be able to move/resize them?

Sorry again for this irritating question.

**Comment by nicolasnoble** [comment]
Try the `ImGuiCond_FirstUseEver` flag on these functions.

**Comment by ocornut** [comment]
If you call those functions with a default/zero `ImGuiCond cond` parameter, you will overwrite the pos/size every time you make the call, so that naturally prevents you from moving or resizing them.

If what you want to do is to set a "default" you may use those condition parameter when making the call:

`ImGuiCond_FirstUseEver` = if window has not data in .ini file
`ImGuiCond_Once` = once per session

**Comment by ChrisMGeo** [comment]
@ocornut and @nicolasnoble  Thanks so much for the quick answers, and sorry for the late answer. It indeed works! Thanks!
