### ISSUE TITLE
Very slow with large sets of data

### ISSUE THREAD

**Issue by newagelightbulb** [ocornut/imgui#2580]
**Version/Branch of Dear ImGui:**

Version: master
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: custom GL
Compiler: Visual Studio 2019
Operating System: Windows 10

Hello, I am having an issue with large datasets. Specifically I create >80 vertical items that each contain >1000 checkboxes. The program becomes unusable because so much data is thrown to ImGui.

I began looking into a way to clip that data and found the list clipper. But in addition to the fact that there doesn't appear to be a version for horizontal clipping, the vertical clipping doesn't seem to work well with scrolling. Code mimicking the demo use of it just draws the first N, and as I am only adding DisplayStart->DisplayEnd items the scroll bar does doesn't grow, you can't scroll to adjust the start item.

What would be the best way to speed up such a large collection of data?

**Comment by ocornut** [comment]
Hello,

A screenshot of the layout or more context on what the data are may allow to provide a better answer. 

> and as I am only adding DisplayStart->DisplayEnd items the scroll bar does doesn't grow, you can't scroll to adjust the start item.

The clipper also move the cursor to the position past the last item to address this, so you should be able to repro the clipper logic. 

But I agree it should be made easier. Since the clipper is a little old and requires some work, including horizontal clipping in an update would make sense.

**Comment by ocornut** [comment]
> the vertical clipping doesn't seem to work well with scrolling. 

In case it wasn't clear from my answer, this should be working well with vertical scrolling, so it would appear you have a problem in your code. Writing down a repro and more details would help.

**Comment by newagelightbulb** [comment]
My apologies, I forgot about this because vertical clipping isn't really necessary for my use case - I just tried it while investigating whether horizontal clipping was available.

Do you think horizontal clipping is something you might look into in the near future?

**Comment by ocornut** [comment]
Probably not in my near future as I am currently busy with too many tasks, but redesigning and rewriting the clipper is definitively something in the horizon.
It's a small block of code you can easily copy and tweak for yourself in the meanwhile.

**Comment by ocornut** [comment]
If we were to add an optional ImGuiAxis parameter (defaulting to ImGuiAxis_Y) to ImGuiListClipper, CalcListClipping, SetCursorPosYAndSetupDummyPrevLine etc. and indexing all ImVec2 with it instead of using .y it would easily allow support for clipping in the other coordinate. But I would like to clipper to get a larger redesign for other reasons.

**Comment by newagelightbulb** [comment]
Thanks for the pointers, I'll look into it.

**Comment by ocornut** [comment]
I'll post here to let you know when I eventually rewrite the clipper.

(it's currently a bit overcomplicated because it essentially supports two different api)
