### ISSUE TITLE
MinGW support IME

### ISSUE THREAD

**Issue by actboy168** [ocornut/imgui#2590]
MingGW disabled IME support, because #738. I don't think MinGW can't use imm.h/imm32.lib.

I want MinGW to enable IME support, only by modifying `imgui.cpp`.

Can you add a macro IMGUI_ENABLE_WIN32_DEFAULT_IME_FUNCTIONS to enable IME support?

**Comment by ocornut** [comment]
Please design and submit the PR that could make it work with MinGW. I don't know how MinGW works and how Microsoft IME api can be used with it.

**Comment by actboy168** [comment]
I think it only needs to remove `!defined(__GNUC__)` and add ldflag `-limm32` to the link.

https://github.com/ocornut/imgui/blob/cb7ba60d3f7d691c698c4a7499ed64757664d7b8/imgui.cpp#L9699

**Comment by ocornut** [comment]
You just said above "I don't think MinGW can't use imm.h/imm32.lib."

**Comment by actboy168** [comment]
Eh, I mean MinGW can use imm.h / imm32.lib.

**Comment by ocornut** [comment]
@actboy168 I apologies it took me so long to review this. A few days ago I was setting up some better mingw build script here and looked at this (previously was mostly running mingw builds without backends). You were absolutely right. I merged the fix here edf135c18de82aa4112ef561ecfc1ed824b8859b
Thank you again!

**Comment by ocornut** [comment]
I pushed 30d164eb2 to undo the change made in 1.82 to enable IME support by default with non-Visual Studio compilers, since in master this is part of the core library rather than the win32 backend it seems reasonable to require explicit enable.
Non Visual Studio users who want IME support in their app need to compile with `#define IMGUI_ENABLE_WIN32_DEFAULT_IME_FUNCTIONS`.
