### ISSUE TITLE
First time user: Clicks go through the ImGui windows

### ISSUE THREAD

**Issue by constantinbogdan** [ocornut/imgui#2615]
Hello,

I'm trying to create a control panel for the admins for a game server but I'm encountering some issues:

1. I'm able to show the Windows cursor (white arrow) when an ImGui window is selected by using some "hacks":
	-- it must be first dragged by the title first
	-- after the window is dragged, the Windows cursor is shown when clicking buttons/textfields of the window
	-- if the background of the dragged window is clicked, then the Windows cursor is not shown anymore

* What I'm trying to achieve here:
	-- when the ImGui is hovered I want the Windows cursor to be displayed all the time (or the game's cursor)

2. I'm able to click the components from the ImGui window but the click event is also sent to the component under the window  and the game responds to those clicks.

* What I'm trying to achieve here:
	-- when the ImGui window is clicked (or a component --button, slide, text field--) the click must be consumed ONLY by the ImGui window/component and the click shouldn't reach the game components under the window

Another problem is (since the game can run in window mode):
	-- the ImGui windows respond to clicks in the first game instance, but in the second instance the ImGui doesn't react to the clicks

I didn't have these problems when combining ImGui with the OpenGL tutorials from: https://learnopengl.com/ but then I had complete control of the rendering loop.
The problem with this server is that I'm trying to be the man-in-the-middle and I'm still figuring out how to do that with ImGui.

PS: This is my first time using Detours, OpenGL and ImGui so the code is a complete mess (until I figure out the issues above).

PPS: I've also read this:
	_"If you are involved in cheating schemes (e.g. DLL injection) for competitive online multi-player games, please don't try posting here.
	We won't answer and you will be blocked. We've had too many of you."_
but since I'm on the other side of the barricade (the admin and not a player) I figured I can still ask for help. :D

ImGui version: 1.70
Detours version: 4.0.1

Back-ends:
- imgui_impl_opengl2
- imgui_impl_win32

Operating System:
	- Windows 10

IDE, SDK, Platform Toolset:
	- Visual Studio 16.1.2 / 10.0 / v142

Attached files:
    [only-working.txt](https://github.com/ocornut/imgui/files/3268810/only-working.txt)    // the code that 'kinda' works at the moment
    [complete_code_test_mess.txt](https://github.com/ocornut/imgui/files/3268812/complete_code_test_mess.txt)    // some other things I've tried

![2nd-problem](https://user-images.githubusercontent.com/3704732/59150852-a0115880-8a32-11e9-9316-766de4aff282.png)

![1st-problem](https://user-images.githubusercontent.com/3704732/59150853-a0115880-8a32-11e9-9e38-88fb7044b638.png)

Thanks.

**Comment by ocornut** [comment]
(1) Stop messing around with `io.MouseDrawCursor`, leave it to false and the native OS window cursor will always be displayed.

(2) You need to read the `io.WantCaptureMouse` flag and when it is true don't pass the input data to the rest of your application. This is described in the FAQ as well as in every examples/ app, which you can check as reference.

Judging by elements in your code your issues stems from general lack of programming experience, rather than pointers of what function/data to check. Unfortunately this is not the purpose of this github issue tracker to be covering this and I myself certainly cannot be. Please use the Discourse forum or any general programming forum (e.g. StackOverflow) for any future communication.

**Comment by thedogmah** [comment]
Looking at your response here, "You need to read the io.WantCaptureMouse flag and when it is true don't pass the input data to the rest of your application. This is described in the FAQ as well as in every examples/ app, which you can check as reference."

I was wondering, since imgui is drawn last, wont this io.wantcapturemouse flag be 1 frame behind?
