### ISSUE TITLE
[multi-viewport] SetWindowPos issue for centered Popup on a screen with negative coordinate value

### ISSUE THREAD

**Issue by Vin789** [ocornut/imgui#2674]
Hi !

**Version/Branch of Dear ImGui:**

Version: 1.70
Branch: viewport (but custom)

Window 10 Pro / Visual Studio 2017

I have 3 screen setuped like this:

[ 1 ] [ 2 ] [ 3 ] 
Screen 1 abs X coordinates: [ -1920 / 0 ]
Screen 2 abs X coordinates: [ 0 / 1920 ]
Screen 3 abs X coordinates: [ 1920/ 3840 ]

I'm working with a custom version of ImGui 1.70 that used multi viewport setup (and so mouse position is using absolute coordinates). I'm opening a popup using the ImGui::BeginPopupModal function. It's works fine on screen 2 and 3 but not on screen 1 (the popup X position is wrong).

Debugging the code to this piece of code:

```
        const bool window_pos_with_pivot = (window->SetWindowPosVal.x != FLT_MAX && window->HiddenFramesCannotSkipItems == 0);
        if (window_pos_with_pivot)
            SetWindowPos(window, ImMax(style.DisplaySafeAreaPadding, window->SetWindowPosVal - window->SizeFull * window->SetWindowPosPivot), 0); // Position given a pivot (e.g. for centering)
```
Here window->SetWindowPosVal - window->SizeFull * window->SetWindowPosPivot will be negative on my first screen (the coordinate are ok) which seems normal but the ImMax will put back the coordinate to the value of DisplaySafeAreaPadding.

So is ImGui not handling negative coordinate value (at least for this case) ? Am I supposed to only have positive values for my monitors or should this piece of code handle negative values ? 

Thx for your time.

**Comment by ocornut** [comment]
This looks like a bug indeed.
This should probably use `g.DrawListSharedData.ClipRectFullscreen + style.DisplaySafeAreaPadding` as the first parameter of `ImMax()`. (Maybe that rectangle should be stored as a ImRect inside ImGui instead of relying on the ClipRectFullscreen which is a little confusing here)

(Linking to #2176, even though the specific bug you are pointing out here is a different one)

**Comment by ocornut** [comment]
Turns out this `ImMax(style.DisplaySafeAreaPadding, ...)` was just plain wrong and unnecessary. Plain wrong because as you pointed out it would break with negative coordinates. Unecessary because correct per-monitor clamping was applied a few lines below. Removed that code now in the Master branch, it will be merged in the Docking branch shortly and then I'll close this.

**Comment by Vin789** [comment]
Make sense. Thx for your time and for making ImGui such a great tool.
