### ISSUE TITLE
Render .GIF using ImGui

### ISSUE THREAD

**Issue by rraggerr** [ocornut/imgui#2680]
Hello, can you make a sample how to render .gif file in my ImGui Begin(s) ?
It will be cool if you add a new feature that allows you to do .gif rendering much easier.

**Comment by aiekick** [comment]
its not the purpose of dear imgui. why you want to do that ?

**Comment by ocornut** [comment]
You can use any gif loader and then use imgui to render individual textures.

**Comment by ocornut** [comment]
For example you can use stb_image.h (https://github.com/nothings/stb/) to load animated gif,s using `stbi__fopen`+`stbi__start_file`+`stbi__gif_load_next`apis.

Displaying a texture in dear imgui can be done with the `ImGui::Image()` or `ImDrawList::AddImage()` api, make sure to read the FAQ and all comments about ImTextureID.

It is tricky to provide an example within the imgui demo because (1) we don't want to embed an image loader in imgui and (2) we can't assume what's the renderer back-end is. Perhaps there would be room in the future for a separate repository providing more complete demos.

**Comment by MegaBlax** [comment]
I was able to do the animation.
I uploaded a texture with a few frames. I used ImDrawList->AddImage and manipulated the parameters uv_a and uv_b

That's what I did: https://gyazo.com/42e3ee25535c62969a57cb849190e707

**Comment by MorrisRichie** [comment]
Very good IMGUI, I am an amateur C++ learning enthusiast. Since my mother tongue is not English, it is difficult for me to learn C++. I have started to use IMGUI in all my projects, but because I don’t understand how GIF frames are processed, I don’t know where to start now. I need a translator to understand him. Who can help me write an example? thank you very much

**Comment by avetharun** [comment]
> Very good IMGUI, I am an amateur C++ learning enthusiast. Since my mother tongue is not English, it is difficult for me to learn C++. I have started to use IMGUI in all my projects, but because I don’t understand how GIF frames are processed, I don’t know where to start now. I need a translator to understand him. Who can help me write an example? thank you very much

What you would want to do first is define a gif as an array of your backend's texture pointers, (in my case, OpenGL texture IDs), and check the framerate of the gif. Step it using ImGui::GetIO().DeltaTime; (use a float as an offset, and cast to int. Rounding will do the rest for you) and that should do it.

That's how most sprite animations are done, except using a UV as a step.

**Comment by rap1dyaRRa** [comment]
> > Very good IMGUI, I am an amateur C++ learning enthusiast. Since my mother tongue is not English, it is difficult for me to learn C++. I have started to use IMGUI in all my projects, but because I don’t understand how GIF frames are processed, I don’t know where to start now. I need a translator to understand him. Who can help me write an example? thank you very much
> 
> What you would want to do first is define a gif as an array of your backend's texture pointers, (in my case, OpenGL texture IDs), and check the framerate of the gif. Step it using ImGui::GetIO().DeltaTime; (use a float as an offset, and cast to int. Rounding will do the rest for you) and that should do it.
> 
> That's how most sprite animations are done, except using a UV as a step.
> 
> Edit: you could also bake the gif into a texture atlas, and use the UV0, UV1 parameter of the ImGui::Image() function

### **Greetings,**
**(Apologies for any potential language inaccuracies; English is not my native tongue. Nevertheless, I shall endeavor to compose this with a more formal and appropriate grammatical style.)**

Apologies for reviving an older discussion, but I have successfully implemented the UV method you provided, and it works impeccably. However, I have encountered a predicament. As I utilize a 2048x2048 image divided into 16 equal parts, I have noticed that the speed of my GIF animation is directly reliant on the FPS value. To overcome this limitation and achieve more consistent and precise results, I am seeking insights into incorporating delta time into my implementation.

I want you to help me modify the code below:

```
                static int i = 0;
                static int j = 0;

                float uv0 = 0.25f * ((i / 8) % 4);
                float uv1 = 0.25f * ((j / 8) % 4);

                SetCursorPos(ImVec2(0, 0));
                Image((ImTextureID*)ImageSource, ImVec2(GetContentRegionMax()), ImVec2(uv0, uv1), ImVec2(uv0 + 0.25f, uv1 + 0.25f));
                i++;
                if (i % 4 == 0) j++;
```

Thank you for your valuable assistance, and I am eager to receive insights and feedback on incorporating delta time effectively.

**Comment by PathogenDavid** [comment]
@rap1dyaRRa

You want to keep track of how long the current frame has been displayed. Update the timer using `ImGuiIO::DeltaTime`, and only go to the next frame when the timer runs out.

This might look something like this. I am hard-coding 10 FPS in this example. You will want to read the real frame rate from your GIF. (Assuming you're reading a literal `.gif` file, the library you're using to load the GIF probably tells you. It might vary from frame to frame due to how `.gif` works.)

```cpp
static int i = 0;
static int j = 0;
const float frameLength = 1.f / 10.f; // In seconds, so 10 FPS
static float frameTimer = frameLength;

float uv0 = 0.25f * ((i / 8) % 4);
float uv1 = 0.25f * ((j / 8) % 4);

SetCursorPos(ImVec2(0, 0));
Image((ImTextureID*)ImageSource, ImVec2(GetContentRegionMax()), ImVec2(uv0, uv1), ImVec2(uv0 + 0.25f, uv1 + 0.25f));

frameTimer -= ImGui::GetIO().DeltaTime;
if (frameTimer <= 0.f)
{
    frameTimer = frameLength;
    i++;
    if (i % 4 == 0) j++;
}
```

**Comment by rap1dyaRRa** [comment]
![image](https://github.com/ocornut/imgui/assets/41791280/2b865cf8-2efb-4877-b6a6-e53901379162)
In my current implementation, I import the specified image and subsequently transfer it to the subsequent frame in a sequential manner.
