### ISSUE TITLE
Is it possible to use imgui in c++ console application?

### ISSUE THREAD

**Issue by ejamshidiasl** [ocornut/imgui#2714]
Hello
i want to use imgui in c++ console application.
is it possible?how?

**Comment by jarikomppa** [comment]
Not out of the box, no.

It would be possible to make some kind of bitmap to ascii art renderer
which would make this possible (using something like libcaca or aalib for
instance), but quite honestly, outside of curiosity, why would you want to?

**Comment by ejamshidiasl** [comment]
ohhh so bad
imgui is too easy and nice graphics
i want to make a ui application in c++ (like simple calculator) with imgui

**Comment by ocornut** [comment]
Please note that we interpreted your question as “can imgui render to an ascii terminal?” Is that actually what you meant?

**Comment by ejamshidiasl** [comment]
no
my mean is that:
i want to create new console application or empty win32 application and add imgui to it (not to console window)

**Comment by ocornut** [comment]
Yes you can. This is not really an imgui related question.

**Comment by duongbaoquy** [comment]
> Please note that we interpreted your question as “can imgui render to an ascii terminal?” Is that actually what you meant?

I'm trying to do that - can you tell how to make it?

**Comment by ocornut** [comment]
> I'm trying to do that - can you tell how to make it?

Look at wiki and search for "terminal"
https://github.com/ocornut/imgui/wiki

**Comment by VilotStar** [comment]
https://github.com/ggerganov/imtui

I mean

**Comment by zokrezyl** [comment]
Is this what you want? 
(from https://github.com/ocornut/imgui/issues/9342). I know it is an old post, but very much related :)

**Yetty Unchained** is a GPU-accelerated new generation terminal that breaks the text-only chains: ImGui draw lists, MSDF text, vector plots and PDFs all render inline as first-class scrolling content. Because the wire format ships primitives instead of frames, you can run your ImGui demo on a remote machine over plain ssh and have it composite onto your laptop's GPU — vector-sharp at any zoom, no X11, no latency tax.  The short imgui demo towards the end of: https://raw.githubusercontent.com/zokrezyl/yetty/refs/heads/main/docs/pres.gif Repo:  https://github.com/zokrezyl/yetty


<img width="900" height="604" alt="Image" src="https://github.com/user-attachments/assets/52e0b2b6-7875-4f6c-9aed-d68c8edfaeb4" />
