### ISSUE TITLE
Combos inside menus not working

### ISSUE THREAD

**Issue by thevaber** [ocornut/imgui#272]
I just ran into a possible bug - ImGui::Combo inside a menu (similar to the Options menu in ShowExampleMenuFile() function) doesn't quite work, it closes the entire menu when you try to use it. 

My use case for this is rather experimental for now, trying to move some things directly into the menus, as seen on this screenshot:
![imgui_menu_popup](https://cloud.githubusercontent.com/assets/7255954/8662852/7352c0c2-29c4-11e5-91d0-759fe12d8704.png)
(This seems to be an interesting way to make windows that are usually modal feel subjectively a little bit more "natural" while also reducing necessary mouse travel, though it has some different usability issues)

I'm not completely sure whether this is a bug or just a necessary limitation, or whether I'm perhaps doing something wrong? I apologize if this has been discussed before and I missed it. (I'm currently using the antialiased branch, not sure whether that's relevant)

**Comment by ocornut** [comment]
Thanks, it was indeed a bug. Should be fixed now.

Details:

------

The behaviour in CloseInactivePopups() looks incorrect. It is normally closing popup stacks when a window not in the popup stack is focused. But those lines that are causing the bug seems fishy to me:
```cpp
if (popup.Window->Flags & ImGuiWindowFlags_ChildWindow)
{
    if (g.FocusedWindow->RootWindow != popup.Window->RootWindow)
        break;
}
```
A break here leads to truncating the popup stack. The popup stack is:
```
EditMenu (popup)
   SubMenu (popup,child)
     ComboContents (popup) // <- focused
```
If I comment the test it that case work, see screenshot:
(NB: The windows are anonymous and don't have proper names in this situation.)
![popup stack](https://cloud.githubusercontent.com/assets/8225057/8676695/423e93a0-2a08-11e5-81ba-08b6856aac68.PNG)

Because of the test above when we reach SubMenu it breaks and truncate the popup stack.
The test was added in ecda785cbcb5933ae1bf80fb6934e4f52d08faa2 
"Popups: fix to allow child popups to be opened from a normal window without an intermediate popup window."

And then i realised there is no test for that!
One possible test is: add a MenuItem() entry in a normal window. Done that:

![menu items](https://cloud.githubusercontent.com/assets/8225057/8676492/143c6e1a-2a07-11e5-85ef-e896f30d07e5.JPG)

That actually works even if I commented the test above which is confusing. There's a bug where you can't come back the parent window by hovering without clicking in this specific situation, but it's not related to those two lines we just commented.

I'm starting to think that the test was needed at some point was I was developing menus (their logic changed a few times) and may be not correct anymore. Running all the tests I can't find a bug if I comment the two lines. Doing that now.

**Comment by thevaber** [comment]
Thank you very much! It's great that you describe the cause of the bug(s) in great detail, I'm sure this will prove useful in the long run, especially for such tricky cases.
