### ISSUE TITLE
Parameters of ImDrawList::AddImage()

### ISSUE THREAD

**Issue by WhoseTheNerd** [ocornut/imgui#2740]
Version: master
Branch: master

**Back-end/Renderer/Compiler/OS**
opengl3 glfw3 arch linux gcc-9.1

Back-ends: imgui_impl_glfw3.cpp + imgui_impl_opengl3.cpp 
Compiler: gcc-9.1
Operating System: Arch-Linux

**My Issue/Question:**
Function has crpytic names. https://github.com/ocornut/imgui/blob/3fb5cf3541c745b1a655f78ae593e665d4c4b6eb/imgui_draw.cpp#L1135
What do the parameters do?

**Comment by ocornut** [comment]
There are examples in the code, but you are right they could be better names.
For all the rectangle functions in that api, `a` and `b` represent the upper-left (min) and lower-right (max) corners. I will work on those parameters name.

`UV coordinates` are the standard way of pointing to a location in a texture, they are normalized values so typically (0,0) point to one corner of the texture and (1,1) to the opposite corner. This is fairly standard in computer graphics and you'll probably find various other explanations if you google for it. So by default those parameters are (0,0) and (1.1) which means the entirety of the textures will be display within the rectangle going from `a` to `b`.

For ImTextureID read the faq and read the demo code that is calling `AddImage()`.

**Comment by ocornut** [comment]
I have updated the headers in `imgui.h` and functions in `imgui_draw.cpp` to use more descriptive names (`p_min` `p_max` instead of `a` `b`, with more descriptions in comments stating that they represent the upper-left and lower-right corners) + added more references to the `ImTextureID` FAQ and short explanation of UV coordinates in the `AddImage` section of imgui.h

**Comment by WhoseTheNerd** [comment]
Thank you!

**Comment by davemoore22** [comment]
I know this is a bit of a necro post, but IMHO the FAQ instructions aren't 100% clear on what the parameters p_min, p_max are, and this issue is seemingly the only place on the internet where this is even tangentially mentioned. So after a bit of fiddling, I've added a comment to my own code which should help anyone else who has this issue and whose searches come here. This following code draws a custom mouse cursor at the current mouse cursor:

```
// Get the current mouse position
ImGuiIO &io{ImGui::GetIO()};
const auto pos{ImVec2(io.MousePos.x, io.MousePos.y)};
if (ImGui::IsMousePosValid()) {

		// We only want to a part of the source texture where the cursor gfx
		// is; this is [5, 80, 24, 31] in an overall source texture of 256x124
		const auto cur_min{ImVec2(5.0f, 88.0f)};
		const auto cur_sz{ImVec2(24.0f, 31.0f)};
		const auto tx_sz{ImVec2(256.0f, 124.0f)};

		// Normalise the top left and bottom right positions of this rect to
		// [0..1]
		const auto uv_0{ImVec2(cur_min.x / tx_sz.x, cur_min.y / tx_sz.y)};
		const auto uv_1{ImVec2((cur_min.x + cur_sz.x) / tx_sz.x,
							   (cur_min.y + cur_sz.y) / tx_sz.y)};

		// Note that in the AddImage call below,
		//
		// p_min - the position in your window where you want the top left of
		// the selected source texture rect; this and p_max are in pixels
		// p_max - the position in your window where you want the bottom right
		// of the selected source texture rect; this does not need to be the
		// same size as the source rect! (this is how you scale the output)
		// uv_0/uv_1 - the normalised top left and bottom right corners of the
		// source rect
		ImGui::SetMouseCursor(ImGuiMouseCursor_None);
		ImGui::GetForegroundDrawList()->AddImage(
			(intptr_t)((*imagestore)[UI_TEXTURE]).texture, ImVec2(pos.x, pos.y),
			ImVec2(pos.x + cur_sz.x, pos.y + cur_sz.y), uv_0, uv_1);
}
```
**Thank you for implementing this feature, its rather splendid!**
