### ISSUE TITLE
tabbar resize issue after bump on 1.72

### ISSUE THREAD

**Issue by Zangetsu38** [ocornut/imgui#2768]
My ask and issue for me, is after i update one project on imgui 1.72, i get broken tab size, and no idea why

This is before
![image](https://user-images.githubusercontent.com/5261759/63259965-12e34f00-c280-11e9-8cdc-03cbb51e0dac.png)
and this is after with get broken like you see and off course, code gui not have changed
![image](https://cdn.discordapp.com/attachments/442344583293304833/616465471583289355/unknown.png)
you can see code relate this here
https://github.com/Zangetsu38/Vita3K/blob/patch/vita3k/gui/src/settings_dialog.cpp

like you can see is caused directly with problem on tab, if i select other tab with very more element no get issue
![image](https://user-images.githubusercontent.com/5261759/63940393-aaf3ec00-ca69-11e9-83f9-114bff00271d.png)

**Comment by ocornut** [comment]
Which version did you update from?

**Comment by Zangetsu38** [comment]
from here
https://github.com/ocornut/imgui/tree/ebe79bbed00a13fd4455f04131b63d49c28ebd5d

**Comment by ocornut** [comment]
Since 1.71 and in particular commit f95c77eeeae70383b3e278a33b511e0d63ee16ac the behavior of tab-bar was clarified and adjusted to fall in line with Columns. They can stretch and adapt to any size so they are "contained" items and don't feed their width back into the host container window. 

As your window is using the `AlwaysAutoResize` flag the size of other elements dictate the size of your window.

This is analoguous to #1363. Contrary to how columns currently works, tab bar have an ideal width so it may be possible to rework this change, but I'm not totally sure. Let me investigate..

**Comment by Zangetsu38** [comment]
ok thx :)

**Comment by ocornut** [comment]
Pushed a commit where tab bar will feed their desired/ideal (unclipped tabs) width to allow for auto-resize to work.

**Comment by Zangetsu38** [comment]
oh, thx, so i can just update imgui, without change code ?

**Comment by ocornut** [comment]
Yes.
In the future please fill the Issue Template correctly when creating an issue. Thank you!

**Comment by Zangetsu38** [comment]
ah yes sorry, and yes, is so fixed like before confirmed :)
![image](https://user-images.githubusercontent.com/5261759/63942607-5acb5880-ca6e-11e9-87f6-304c6c7e83ad.png)
good works ^^
