### ISSUE TITLE
Question about draw a MSAA Frambuffer?

### ISSUE THREAD

**Issue by kwangsing3** [ocornut/imgui#2773]
**Version/Branch of Dear ImGui:**

Version: 1.72
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp 

Compiler: Visual studio 2017
Operating System: Windows 10

**My Issue/Question:**

First, thank you all read this issue,
   I got a wrong result when I trying to render an Anti Aliasing framebuffer, or call it Off-screen MSAA?
   Normally, I render a scene and sent it to ImGui::Image with GLFW(OpenGL3), that's fine,
then I try to add anti alias to framebuffer, it shows font texture.  (( lol
It shows Chinese, cause I'm Chinese user, and load the font with below
(Just so you know)
````C++
io.Fonts->AddFontFromFileTTF("C:/Windows/Fonts/msyh.ttc", 15.0f, &font_config, io.Fonts->GetGlyphRangesChineseFull());
io.Fonts->Build();
````
The example also show the basic way I use to render a MSAA framebuffer on the bottom (bind texture and draw triangles)
  These pictures are the example I made for explain what's happening. If you need code or the project, plz let me know.     Thank You.

**Screenshots/Video**

![withoutanti](https://user-images.githubusercontent.com/18378969/64070700-c2192080-cc99-11e9-99a7-bc8401a98fd3.PNG)
![withanti](https://user-images.githubusercontent.com/18378969/64070701-c5aca780-cc99-11e9-8ef4-2eaa1052767e.PNG)

**Comment by ocornut** [comment]
That question probably has nothing to do with dear imgui, but how you create the framebuffer/texture on OpenGL side.

I imagine if you bind an incorrect texture maybe your OpenGL driver will keep the last texture (which will be the imgui atlas texture) that's why you are seeing those character.

I think you will get a better answer from OpenGL development forums rather than here.
