### ISSUE TITLE
SetItemDefaultFocus scroll improvement suggestions

### ISSUE THREAD

**Issue by DomGries** [ocornut/imgui#2812]
Hey, I think SetItemDefaultFocus scrolling could be improved due to the following minor issues:
- An item which is barely visible (1px) is not being visibly focused
- Scrolling to an invisible item could be improved to fix the jump between barely visible and completely centered

I think the best behavior would be to copy what the .NET ListView `EnsureVisible` method does: https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listview.ensurevisible?view=netframework-4.8

> If the item that you want to ensure is visible is located above the viewable region, calling the `EnsureVisible` method will scroll the contents until it is the first item in the viewable area. If the item is below the viewable region, calling the `EnsureVisible` method will scroll the contents until the item is the last item in the viewable area.

Dear ImGui 1.73

**Comment by ocornut** [comment]
Hello,

Could you provide concrete example/screenshots of both of your case?

If `SetItemDefaultFocus()` is called on a frame where the window is appearing, I can think of cases where it would be preferable that the be centered. e.g. for a list of items in a combo box. 
Perhaps the behavior should differ depending on whether the window is appearing? Would need some more thought..

**Comment by domgho** [comment]
### Case 1
Popup window does not visibly select 1280x720 button because 1px is already visible (the black line at bottom under 1024x768) when calling `SetItemDefaultFocus()`. I think the logic should be changed so that it should also scroll when the item is not **fully** visible:

![Capture](https://user-images.githubusercontent.com/341158/65895647-1227f780-e3ac-11e9-93a3-3cbf7ec9b5e1.JPG)

### Case 2
Only centering the view on the item when it is not visible is weird especially combined with suggested fix of case 1.

Assume that the focused item is just barely fully visible then it would be at the very bottom (or top). But if the focused item is just the one below that then it results in it being completely centered which is a jump in behaviour.

I just tested default comboboxes on Windows and they actually simply try to scroll so that the item is at the top or as much as possible at the top. So in `SetItemDefaultFocus` that would be `SetScrollHereY(0.f)` without the `IsItemVisible()` check.

**Comment by ocornut** [comment]
Case 1: Totally agreeing.

Case 2: I don't think your answer refers to the same idea that I suggested? I suggested using the "IsWindowAppearing" test. Typically behave different on the frame a __window__ is appearing vs if function is called while the window is already up. This is unrelated to the visibility of items within a given window.

Scrolling to the center or to the top is another decision to do. I agree that the behavior of `ScrollToBringRectIntoView()` is more desirable in some situation. This is also what I asked for a usage scenario here where that behavior is the most desirable (scrolling to make item appear at edge vs centering).

**Comment by domgho** [comment]
Thank you for your response.

Not sure if I understand but personally I am only interested in the case when the window is appearing since I want the currently selected item to be focused when the popup window is opened. Focusing an item while it is already visible should probably use a different function and possibly behavior (such as `EnsureVisible` mentioned in the first post) but I currently would not need that functionality.

Anyway case 2 is really nitpicky but I thought it was worth challenging the status quo. Thanks!

**Comment by ocornut** [comment]
Closing as per #2814, both cases should be solved. Thanks for your patience!
