### ISSUE TITLE
Backspace has no effect on Mac

### ISSUE THREAD

**Issue by DiligentGraphics** [ocornut/imgui#2817]
Version: 1.73.

There appears to be a bug in handling of backspace on Mac: the event handling function reads `127` [here](https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_osx.mm#L252) and then [adds this as an input character](https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_osx.mm#L254).

The key down flag [is also set](https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_osx.mm#L261), but this only deletes previously added `127`, having as a result no effect .

**Comment by ocornut** [comment]
Please fill the issue template.

**Comment by DiligentGraphics** [comment]
Version: 1.73 (WIP)
Branch: master

Back-ends: imgui_impl_osx.mm + custom Vulkan (via MoltenVK)
Operating System: MacOS

The issue:
Apparently there is an issue in handling of backspace by `ImGui_ImplOSX_HandleEvent` function:

```cpp
if (event.type == NSEventTypeKeyDown)
{
    NSString* str = [event characters];
    int len = (int)[str length];
    for (int i = 0; i < len; i++)
    {
        int c = [str characterAtIndex:i]; // Reads 127 when backspace is pressed
        if (!io.KeyCtrl && !(c >= 0xF700 && c <= 0xFFFF))
            io.AddInputCharacter((unsigned int)c); // 127 is added as input character here

        int key = mapCharacterToKey(c);
        if (key != -1 && key < 256 && !io.KeyCtrl)
            resetKeys();
        if (key != -1)
            io.KeysDown[key] = true; // o.KeysDown[127] is set to true which has the effect
                                     // deleting previously added '127' character 
    }
    return io.WantCaptureKeyboard;
}
```

**Comment by bootzin** [comment]
I'm actually facing a similar issue on Windows, although in the docking branch. 

Backspace has no effect, but also, Enter has the effect of backspace, and the 'up arrow' key has the effect of the enter key.. Looking at my custom key codes, the "UpArrow" code is **45**, the "Enter" key is **49** and the BackSpace key is **53** (Also, key code 57 is pageDown, which I believe is the action that is being mapped to the backspace key, that's why it has no effect for me)

For some reason, it looks like it's being mapped to the key code + 4. When looking at the result of IsKeyDown when I press the Enter key, it returns _0 for 49_ and _1 for 53_, which means it really recognized enter as backspace (for me, due to my keycodes)

This behaviour started happening after updating to 1.73, haven't tried reverting to 1.72 to see if it fixes the problem yet

**Comment by ocornut** [comment]
@bootzin 
> I'm actually facing a similar issue on Windows, although in the docking branch.
> Backspace has no effect, but also, Enter has the effect of backspace, a

Your issue is unrelated, my guess is you have a mismatch between compiled code and header file, perhaps code version mismatch, or a layer above imgui that hasn't been synchronized with latest ABI/enum values. If you are using ImGui.Net please refer to the repository for that project.

**Comment by ocornut** [comment]
Merged PR, thank you @DiligentGraphics !
