### ISSUE TITLE
Subtraction ImVec2

### ISSUE THREAD

**Issue by Cesar1986BR** [ocornut/imgui#2832]
Hi, i get problem when i tried  subtract two ImVec2.
i saw a source that this operator work, but i think that somethings has ben  changed, since the code that i using  as base use old version of imgui.

`ImVec2 center = ImVec2(pos1.x + screen.x / 2, pos1.y + screen.y / 2);
ImGui::GetWindowDrawList()->AddCircleFilled(center + ImVec2(x_1, y_1), 2, ImColor(255, 0, 0));`

https://imgur.com/GOvKWCP

**Comment by ocornut** [comment]
Hello,

Please carefully read and fill the Issue Template next time you ask a question.

Operators for ImVec2 are not declared by default, because the expectation for custom engine is to setup cast operators in `imconfig.h` and let the user use their own math types and operators.
If you want to use ImVec2 maths operator you can use:

```
#define IMGUI_DEFINE_MATH_OPERATORS
#include "imgui_internal.h"
```

**Comment by Cesar1986BR** [comment]
sorry, thx its working now

**Comment by divital-coder** [comment]
nice thing figuring it out ,
