### ISSUE TITLE
ComboBoxes' Popup is movable and crash the application when combined with docking

### ISSUE THREAD

**Issue by Folling** [ocornut/imgui#2835]
**Version/Branch of Dear ImGui:** 

Version: 1.73
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw3.cpp
Compiler: clang 8.0
Operating System: arch linux 64 bit

**My Issue/Question:**
Similar to [this issue](https://github.com/ocornut/imgui/issues/2763), the popups for combo-boxes respond to being dragged on the small outline at the top, when dragged to a position, the app crashes with: 

> void ImGui::TabBarAddTab(ImGuiTabBar *, ImGuiTabItemFlags, ImGuiWindow *): Assertion `g.CurrentTabBar == __null' failed.

**Screenshots/Video**
![gif](https://im5.ezgif.com/tmp/ezgif-5-1875f6ed4f1c.gif)

**Standalone, minimal, complete and verifiable example:** 
```cpp
ImGui::Begin("Dockable Combo Popup Bug");
if(ImGui::BeginCombo("test", "hello")) {
    ImGui::Text("1");
    ImGui::Text("2");
    ImGui::Text("3");
    ImGui::EndCombo();
}
ImGui::End();
```

**Comment by ocornut** [comment]
Curiously I can't seem to repro the assert/crash though, but I'll push a fix.

**Comment by ocornut** [comment]
Nice catch @folling. It should be fixed now!
It should have been added to #2763. Was not noticeable in master branch because even though the window was not marked with _NoMove, the Combo code overrode the window position every frame (hence the odd  effect in docking branch where the docking overlays appears but window doesn't appear to move).
