### ISSUE TITLE
Using font atlas glyphs for custom MouseCursor(ImGuiMouseCursor type)

### ISSUE THREAD

**Issue by pixtur** [ocornut/imgui#2854]
**Version/Branch of Dear ImGui:**

Version: 1.72
Branch: Master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui.net
Operating System: win10

**My Issue/Question:**
I'm working on a timeline editing feature that demands a lot of special operations (like stretching, extending or slicing clips). These are enabled by various modifier keys. To make this more intuitive, it would be great to have more custom mouse pointers.

Since we already add custom icons to the font atlas, would it be possible to set mouse pointers via glyph ids, e.g. `SetMouseCursor(int glyphIndex);`?

**Comment by ocornut** [comment]
Hello Thomas,

Since your backend controls the mouse cursor and you would have to add them in your backend anyway, I don’t think there’s anything preventing you from already doing that.

You could decide to pass arbitrary value over ImGuiMouseCursor_COUNT and have your backend interpret them as either cursors from a known set, or decide to pull a glyph and upload it into a hardware cursor.

Since we don’t abstract the creation of arbitrary hardware cursor from pixels it would be a job for your custom backend and I am not sure what dear imgui can do to facilitate this more.

**Comment by pixtur** [comment]
Hi Omar,

thank you for this quick answer. I didn't realize that pointer rendering is controlled in the backend. I noticed the different pointers as part of the default font atlas texture and somehow assumed that imgui would  "hide" (e.g. replace) the system pointer and then render a quad with a section of the that texture.
I will look into the impl part and explore some more.

**Comment by ocornut** [comment]
Dear ImGui has a path triggered by `io.MouseDrawCursor` where it draws the mouse cursors in the 3d scene, and in turn the back-ends hide the HW cursor. 

This is mostly useful on e.g. platforms that don't traditionally have mouse cursors, but in a desktop OS normally you would want to use the HW cursor because it is wired in a way more optimal way that regular polygon drawing + framebuffer blitting. A cursor drawn at 60 fps using 3D api will always feel more sluggish that a HW one.
