### ISSUE TITLE
Win7 VS2017 imgui SDL2 opengl3 example High CPU cost?

### ISSUE THREAD

**Issue by mindoff6502** [ocornut/imgui#2898]
Quite strange CPU problem.
Using imgui 1.73.
Try DX9, DX11 example with %2 CPU cost.
Try GLFW OpenGL3 with %3 CPU cost.
Try SDL OpenGL3 with %13 CPU cost.
What's going on here?
Using SDL 2.0.10.

I'm using mainly because I need it's audio processing.
Other SDL2 framework I don't really need,I can switch to GLFW.
I just think don't need to using too many 3rd party libraries.

Anyway before I move to GLFW if I have to,
I want to ask and figure out why SDL2 opengl3 imgui example cost so many CPU?

**Comment by ocornut** [comment]
Try to remove the imgui code and see if it makes any difference. If it doesn’t, this is a SDL question, not a dear imgui question.

**Comment by darkcharmander** [comment]
I would like to re-open this since there are no open issues about CPU usage.

Since I've started with ImGui I've had this problem as well: SDL2 + OpenGL 3 always eats up one core entirely.
It should be an ImGui problem: If you open the example and remove this line
`ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());`
then CPU usage will go down with like 90% (On a one core basis). Obviously ImGui is not drawn when you remove that line, but it means that that line causes the high CPU usage.

It tested this on multiple computers (three, all wih nvidia cards), and it's always the same result. Other samples do not have this problem.

I really hope that there is a solution for this, since this is preventing me from using ImGui.

**Comment by darkcharmander** [comment]
I am afraid that this is a driver issue. The NVIDIA control panel doesn't work on the Windows 10 2004 update, and there may be other problems.

That is also precisely what the machines I've tested it on all have in common. I just tested it on Kubuntu, through Wine, and it works just as it should, and does not hog the CPU.

I will uninstall the NVIDIA driver in favor for an older one, and see if the same issue arises. It could be that it doesn't help if Microsoft has messed up Windows 10 with that update, but we will see.

**Comment by darkcharmander** [comment]
Yup, despite three computers showing the same symptoms, it is indeed a driver issue.
The Intel HD driver runs it like normal.

**Comment by ArktisDev** [comment]
I've ran into the same issue just today in the SDL2 + OpenGL3 example.

When I remove the line `ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());`, my CPU usage for this process goes from 12% to about 3%. 12% is about 3/4 of one of my cores. Keeping that removed, but adding back a call to `ImGui::GetDrawData()`, CPU usage stays at 3%, confirming to me that the `ImGui_ImplOpenGL3_RenderDrawData()` function is causing the problems. 

I'd love to use the imgui library for the gui, as it doesn't seem there are a lot of other great libraries like it, but the CPU usage hit is quite bad.
