### ISSUE TITLE
opengl3 fails in v1.74

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#2907]
After cimgui generation from v1.74, LuaJIT-ImGui fails in opengl3 implementations, either with glfw or sdl

glfw and opengl2
![opengl2](https://user-images.githubusercontent.com/1795930/69617350-5e07bd80-1038-11ea-9146-6b8e9322b4fa.gif)

glfw and opengl3
![opengl3](https://user-images.githubusercontent.com/1795930/69617379-6d870680-1038-11ea-9188-d855c746da0c.gif)

The same happens building example_glfw_opengl3 from ImGui
![opengl3impl](https://user-images.githubusercontent.com/1795930/69618414-2437b680-103a-11ea-9118-9a11f7df4bc4.gif)

**Comment by ocornut** [comment]
I can't really repro.
- Can you first verify if this is happening with e.g master 1.73 or earlier versions ?
- Apart from better detection of GL context version to avoid calling `glDrawElementsBaseVertex ()` pre 3.2, nothing has nothing since May.
- Update your video card drivers. OpenGL drivers are a minefield.

**Comment by sonoro1234** [comment]
When I checked that it was happening with earlier imgui versions, I realized that my double video card(ATI and Radeon) was setted to the less performant one. Changing it to Radeon all got solved.

What I still dont understand is that previously, when setting the less performant video card there was a complain about not being able to create gl context but now it did not happened!!
