### ISSUE TITLE
ImGuiTabItemFlags_NoCloseButton has no effect

### ISSUE THREAD

**Issue by elect86** [ocornut/imgui#2923]
It looks like `ImGuiTabItemFlags_NoCloseButton` has no effect

At the moment, you can hide the close button only by setting `p_open` to `null`

**Comment by ocornut** [comment]
1) Please fill the issue template as requested when opening an issue.

2) That's an internal flag that tracks whether TabItem() was called with `p_open != NULL` and not meant to be used when calling TabItem() yourself (that's why it's not in the publci API). As such, it behave as documented, but I agree the name can be misleading to someone browsing the code.

**Comment by ocornut** [comment]
As per the issue you linked to, https://github.com/kotlin-graphics/imgui/issues/105 it seems to be a bug that this sort of internal flag is exposed to your public API.

I'll probably rename the flag for clarify.

**Comment by ocornut** [comment]
I made a change to honor this (since it was two lines) and changed the specs/docs accordingly.
That said, your port probably shouldn't expose all those internal flags... your users are going to stumble on lots of confusion and forward-compatibility issues if they use them.

**Comment by elect86** [comment]
Ok, sorry for the issue template and thanks for the commit about it, Omar

I was keeping already an eye trying to addressing this issue (internal enums public exposure) and since I'd like to keep them as enum for programming convenience, I think I'm gonna use a leading underscore to make this obvious for the end user (and they will be listed also all the end in case of code completion)
