### ISSUE TITLE
GUI is not rendered on the first frame

### ISSUE THREAD

**Issue by DiligentGraphics** [ocornut/imgui#2949]
**Version/Branch of Dear ImGui:**

Version: 1.75 WIP 
Branch: XXX master (https://github.com/ocornut/imgui/commit/dc66f83db8462e7837aec60fef86c025ac4c485b)

**Back-end/Renderer/Compiler/OS**

Back-ends: example_win32_directx11, example_win32_directx10, example_win32_directx9
Compiler: MSVC (Visual Studio 2017)
Operating System: Windows

**My Issue/Question:**

The UI only appears on the second frame, but nothing is rendered on the first. I guess the easiest way to see the issue is to set the breakpoint at `g_pSwapChain->Present(1, 0);` at line 145, step over the call and look at the window.
The behavior depends on the presence of imgui.ini: on the first run (as well as if `io.IniFilename == nullptr`), only one window out of two appears on the first frame. On the second and subsequent runs, no windows appear on the first frame.

Can't figure out if this is by design, looking through issues or searching google does not give the answer.

**Comment by ocornut** [comment]
Hello,

Windows that don't have an initial size needs to be processed once to get one, so that's a known thing with no expected solution. 

The windows that are visible on their first frame that usually those with a `SetNextWindowSize()` call or sizing data coming from the .ini file.

If this is particularly troublesome for your app, one possible suggestion would be to completely skip the first call to `g_pSwapChain->Present(1, 0);`

**Comment by DiligentGraphics** [comment]
Thanks! The app is a unit test that renders only a single frame.
Skipping the first present works fine. In fact I found that same workaround, but just wanted to be sure that there isn't anything obviously wrong here.
