### ISSUE TITLE
Can I use Dear ImGui with no main window?

### ISSUE THREAD

**Issue by KarimIO** [ocornut/imgui#2974]
Version/Branch of Dear ImGui:

Version: v1.75
Branch: docking

Back-end/Renderer/Compiler/OS

Back-ends: imgui_impl_opengl3.cpp + Custom window implementation
Compiler: MS Visual Studio 2019
Operating System: Windows 10

Can I use Imgui with no main window? I'm trying to make an editor interface and have imgui create its own windows (bec there will be no main window, only imgui windows). Can this be done?

**Comment by ocornut** [comment]
It's not currently possible (will be in the future) but if your app needs to have a main imgui window then you can simply create a OS window and have the imgui window fit it entirely.

**Comment by KarimIO** [comment]
Can I create an invisible window as the main window? What exactly is its purpose?

**Comment by ocornut** [comment]
You can if you want. This is under your control.

> What exactly is its purpose?

This is mostly legacy since Dear ImGui started (and is still mostly used) as a regular overlay.
However many parts of the multi-viewports system currently rely on a "main viewport". Same as discussed in https://github.com/ocornut/imgui/issues/1542#issuecomment-570889808. Lifting that limit and refactoring this will take some time. Someone once submitted a patch to start that work but it's been dropped in a folder without source control and some of the technical choices were unexplained or problematic. TL;DR; need some work, not happening tomorrow.

**Comment by ocornut** [comment]
I'll close this as answered. Will post here again if we ever get to support that feature in the future (we should, but I don't know when).

**Comment by p0358** [comment]
+1 for this, could make ImGui a nice library for desktop GUI programs

**Comment by GuoZiyangTYUST** [comment]
+1 need this. i tried hide main window by :
    SDL_HideWindow(window);
but imgui window disappeared  after a drag.
