### ISSUE TITLE
Additional cursors added in GLFW are optional and can fail

### ISSUE THREAD

**Issue by Crunkle** [ocornut/imgui#2980]
If the additional cursors used by the GLFW 3.4+ implementation (b5cad20) are not found then GLFW will return an error `GLFW_CURSOR_UNAVAILABLE` with no pointer. See [this fail condition](https://github.com/glfw/glfw/blob/aa5e31356178de43d42f43f48914a62c25033f4b/src/x11_window.c#L2964) and the supporting [GLFW compat docs](https://github.com/glfw/glfw/blob/aa5e31356178de43d42f43f48914a62c25033f4b/docs/compat.dox#L88).

We are using the following three which are not always guaranteed: `GLFW_RESIZE_NESW_CURSOR`, `GLFW_RESIZE_NWSE_CURSOR`, and `GLFW_NOT_ALLOWED_CURSOR`. Similar outcome for Wayland.

I believe there is no current way to request which cursors are available beforehand? I can only think to ignore the error and fallback to the old cursor on failure.

**Comment by ocornut** [comment]
Fixed by aa34681652c557ce7cbeb6b9e9067d7af3062454
I initially felt that error report was pretty agressive on GLFW's part, but it's mostly that the behavior isn't ideal in our specific use case (providing a piece of reusable GLFW software). In most real software the user can catch it. I would expect any GLFW application eventually ignoring those because of X11 configurability.
