### ISSUE TITLE
Proper way to implement a custom widget?

### ISSUE THREAD

**Issue by AllenDang** [ocornut/imgui#2992]
This is not an issue but rather a question to ask.

What's the proper way to implement a custom widget?
Says I want to create a rotating progress indicator, using drawing methods like AddArcTo etc...

After the widget is drawn, invoke SetCursorPos to move the drawing cursor to next line.

Everything works fine but when I tried to use the progress indicator with ImGui::SameLine, the X value of position of the indicator will become 0.

After read the imgui_widgets.cpp, I noticed there is a method called ImGui::ItemSize will do the trick by setting the CursorPosPrevLine, but it is not exposed to outside.

Should I not use it but to set the window->DC.CursorPosPrevLine manually ?

**Comment by rokups** [comment]
1. Give an ID to your widget using `PushID()`/`PopID()`. This will solve your widget affecting other widgets.
2. Use `ItemAdd()`/`ItemSize()`.
3. If your widget is interactable use `SetActiveID()`/`ClearActiveID()`.

**Comment by ocornut** [comment]
Hello Allen,

That's a good question, there's two ways to go.

1. You can use the public API entirely. In this case, `InvisibleButton()` is often your best friend. It is will perform all layout/navigation functions and then from then you can query the information you want (e.g. `IsItemActive()`) and perform the drawing your need. Refer to `Demo>Widgets>Querying Status` to get more details on the `IsItemXXX` functions.

2. You can use the internal API (in `imgui_internal.h`) for finer control and slightly better performances. In this case can modal your widgets over the ones in imgui_widgets.cpp, using `ItemAdd`, `ItemSize`, `ButtonBehavior()` (the lower-level equivalent of InvisibleButton()). You'll rarely ever need to call function like SetActiveID, ClearActiveID as most behaviors can be modeled over the button behavior.

I would suggest go for (1) to make your first widget and because you will only rely on forward-compatible API .
There is a arguably a lack of demo for (1) which is why this question is popping from time to time but you may find it very easy once you dig a little. I think we could aim to add more demo for that.

**Comment by AllenDang** [comment]
@ocornut Thanks a lot for your instruction! InvisibleButton it is.

**Comment by AllenDang** [comment]
@rokups Thanks!

**Comment by codecat** [comment]
Sorry to bump this as I'm not sure if there's been any further developments in terms of examples and such. Is there a way to make it so that I can still drag the window when clicking & dragging an InvisibleButton?

**Comment by PathogenDavid** [comment]
@codecat It depends on your exact use-case.

The second method cannot affect that particular behavior because it still sets the active widget (which is what is preventing the background move.)

If you just need to reserve an area for your widget, you can use [`ImGui::Dummy`](https://github.com/ocornut/imgui/blob/9c77734447e4e2977ecb10d081383ba889dc643c/imgui.h#L429). However do note that it does not react to mouse clicks. (IE: It does not return a bool, `IsItemActive` will always return false.)

---------

If `Dummy` isn't enough for you, you can keep using `InvisibleButton` by manually enabling the window movement like this:

```cpp
ImGui::InvisibleButton("TestButton", ImVec2(100, 100));
if (ImGui::IsItemActive() && ImGui::IsMouseDragging(ImGuiMouseButton_Left))
    ImGui::StartMouseMovingWindow(ImGui::GetCurrentWindow());
```

(This is based on [what `CollapseButton` does internally](https://github.com/ocornut/imgui/blob/9c77734447e4e2977ecb10d081383ba889dc643c/imgui_widgets.cpp#L839-L841) to achieve the same effect.)

**Comment by codecat** [comment]
`ImGui::Dummy` is exactly what I needed, thank you!

**Comment by ocornut** [comment]
(FYI `StartMouseMovingWindow()` is not currently exposed because in docking branch the status of whether we are moving or undocking is inferred every frame from the relative position to test "if dragged from title bar" and that needs to be moved into a stored boolean. I have a wip stash for that change.)

**Comment by FallowWing** [comment]
Is there a way to combine two widgets for the purpose of IsItemActive and IsItemHovered?

After declaring a "compound widget" like this:
```
void myCompoundWidget(char *widgetLabel, ...) {
	ImGui::PushID(widgetLabel);
	ImGui::InputFloat(...);
	ImGui::InputFloat(...);
	ImGui::PopID(widgetLabel);
}
```

I'd like another piece of code to be able to use IsItemHovered to detect if either is hovered, ofc this only works if you're hovering the last one:
```
myCompoundWidget("First widget", ...);
if (ImGui::IsItemHovered()) printf("You're hovering one of the two widgets!\n");
```

I've tried to hack it like this:
```
void myCompoundWidget(char *widgetLabel, ...) {
	bool hovered = false;
	ImGui::PushID(widgetLabel);
	ImGui::InputFloat(...);
	if (ImGui.IsItemHovered()) hovered = true;
	ImGui::InputFloat(...);
	if (ImGui.IsItemHovered()) hovered = true;
	ImGui::PopID(widgetLabel);

	if (hovered) ImGui::SetHoveredID(ImGui::GetID(widgetLabel), ImGui::GetCurrentWindow());
}
```

Feels like that could work, like I'm setting the hovered on the label that comes from widgetLabel.
But that prevents interaction in general it seems. Maybe I could do more hacking with ImGui::SetLastItemData?
Is there a path to do something like this?

**Comment by ocornut** [comment]
@FallowWing This is what BeginGroup()/EndGroup() is for.
