### ISSUE TITLE
How does the default font look so well at size 13?

### ISSUE THREAD

**Issue by tuket** [ocornut/imgui#3001]
Hi,

I was trying to get bold text in my app. I went find a bold version of the default font (ProggyClean) but couldn't find one. So I though I could just use the same font with slightly bigger size (the default size is 13). However, with other sizes, the font doesn't look as good. The default font at 13pt is so crisp and pixel perfect. I tried other fonts such as RobotoMono it looks nicer than the default font at different sizes but still looks quite blurry.
How can I get a font to look as good as ProggyClean at 13pt?

I'm pasting my code here, just in case I'm missing something, but I think it should be alright.
```cpp
const int fontSize = 18;
ImFontConfig font_cfg = ImFontConfig();
font_cfg.OversampleH = font_cfg.OversampleV = 1; // I have tried higher values here but I can't see any difference
font_cfg.PixelSnapH = true;
const int size = 18;
font_cfg.SizePixels = size;
const char* file = "RobotoMono-Regular.ttf";
tl::toStringBuffer(font_cfg.Name, file, ", ", fontSize, "px");
font_cfg.EllipsisChar = (ImWchar)0x0085;
fonts::roboto = io.Fonts->AddFontFromFileTTF(file, fontSize, &font_cfg);
fonts::roboto->DisplayOffset.y = -1.0f;
```

Thanks!

**Comment by ocornut** [comment]
The font was designed to be rendered at exactly this size. I'm not sure exactly how it is done (if it is use bitmap components, if they even exist in TTF, I don't think so tbh? or vector shape perfectly aligned with that assumption). Also see http://upperbounds.net/

That font was choosen because it is is small (can be embedded in the source code) and bypass limitations of our font rendering system. Rendering of font is a really complex science and by default we don't provide a quality on-par with what most OS provide today.

What you can do:
- Turning oversampling on + bilinear filtering on the texture could help a little.
- Some fonts are naturally going to look better than other (bolder strokes in general probably do).
- Switching to use imgui_freetype (in misc/) folder along with Freetype and using correct blending is going to make the most difference. Freetype support various hinting techniques which helps, while stb_truetype doesn't seem to expect to ever support something like that, possibly because 4K resolutions are making this slightly less of a problem now.

If you want to dig and learn more about this, also see those two work in progress pull-requests which ultimately would improve the quality of font rendering:

https://github.com/ocornut/imgui/issues/2468
https://github.com/ocornut/imgui/pull/2986

**Comment by tuket** [comment]
Thanks for your reply, I might try with freetype then
