### ISSUE TITLE
Help with idea implementation

### ISSUE THREAD

**Issue by saucesaft** [ocornut/imgui#3010]
Hey, this library is amazing, thanks for everything.

I have an idea, how could I have a main program, with no windows just the main imgui/os  window. But have another program/executable that when I run it will launch an Imgui-window in the main window. I don't know if I'm explaining myself but how could one solve this implementation problem? Thanks :smile:

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post with the Issue Template shown in "New Issue" and reply here when edited (don't create a new issue) .

Closing.

I am not even sure what your question is about since your post is ambiguous.
Also see https://github.com/ocornut/imgui/issues/1542#issuecomment-570889808, #2974.
