### ISSUE TITLE
What is the lifetime of ImDrawLists?

### ISSUE THREAD

**Issue by Alloyed** [ocornut/imgui#3021]
**Version/Branch of Dear ImGui:**
Branch: docking

**My Issue/Question:**
Hey, so for context I'm building a binding library between a garbage collected language and imgui, and ideally I don't want to write an API that can cause a user to dereference bad memory, ever, for any reason.

I recognize the GetXDrawList() functions as implying non-ownership, ie. you get the drawlist once, add your stuff, and then next time you need it you should just call GetDrawList() again. but how long is that pointer valid for, and are there any actions that I should treat as "invalidating" the pointer? is it safe until the context is destroyed? until the frame is rendered? etc.

**Comment by ocornut** [comment]
Hello,

You can treat `NewFrame()` as invalidating ImDrawList pointers.
In reality, _presently_ we never destroy windows so they will always be valid, but I have the project to do so so better treat NewFrame as invalidating.

Since 1.73 and #2636 we have a GC-like mecanism to free large buffers inside windows, so one things that happens is that drawlist buffers are freed. We don't free the ImDrawList instance themselves as they are stored inside ImGuiWindow and their lifetime is the same as the ImGuiWindow.

**Comment by Alloyed** [comment]
Thank you~
