### ISSUE TITLE
Integrating with OSS-Fuzz

### ISSUE THREAD

**Issue by Google-Autofuzz** [ocornut/imgui#3042]
Greetings imgui developers and contributors,

We’re reaching out because your project is an important part of the open source ecosystem, and we’d like to invite you to integrate with our [fuzzing](https://www.owasp.org/index.php/Fuzzing) service, [OSS-Fuzz]( https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html ). OSS-Fuzz is a free fuzzing infrastructure you can use to identify security vulnerabilities and stability bugs in your project. OSS-Fuzz will:

- Continuously run at scale all the fuzzers you write.
- Alert you when it finds issues.
- Automatically close issues after they’ve been fixed by a commit.

Many widely used [open source projects]( https://github.com/google/oss-fuzz/tree/master/projects ) like OpenSSL, FFmpeg, LibreOffice, and ImageMagick are fuzzing via OSS-Fuzz, which helps them find and remediate [critical issues]( https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=status%3AFixed%2CVerified+Type%3ABug%2CBug-Security+-component%3AInfra+ ). 

Even though typical integrations can be done in < 100 LoC, we have a [reward program]( https://www.google.com/about/appsecurity/patch-rewards/ ) in place which aims to recognize folks who are not just contributing to open source, but are also working hard to make it more secure.

We want to stress that anyone who meets the eligibility criteria and integrates a project with OSS-Fuzz is eligible for a reward.

To help you getting started, we can attach our internal fuzzer for your project that you are welcome to use directly, or to use it as a starting point.

If you're not interested in integrating with OSS-Fuzz, it would be helpful for us to understand why—lack of interest, lack of time, or something else—so we can better support projects like yours in the future.

If we’ve missed your question in our [FAQ]( https://google.github.io/oss-fuzz/faq/ ), feel free to reply or reach out to us at oss-fuzz-outreach@googlegroups.com.

Thanks!

Tommy
OSS-Fuzz Team

**Comment by ocornut** [comment]
Hello,

Thanks for reaching out.

Dear ImGui is designed to be used internally, and on generally trusted inputs. There are plenty of ways to make it rightfully crash on incorrect uses. So my gut feeling is that typical fuzzing would not be adequate here. For a start its reliance on cheap 32-bit hashing functions makes it prone to collisions and maliciously crafted user data could be used to activate other UI items, etc. There are no foreseable desire or plan to steer the project into a direction where that sorts of things would get fixed, mostly because they would have an impact on performances and project complexity.

However, I am not very familiar with fuzzing and I guess there might some good uses for techniques like that that could help sturdy certain API. To be meaningful they would need to be carefully designed by people well acquainted with Dear ImGui overarching goals and values. It is unlikely that I would be able to spent time on this in the near term. If you or someone else wants to investigate this further I am not against it but I really feel it would only make senses for someone who "gets" Dear ImGui, because it is such an unusual project compared to the typical OSS (most dear imgui code never even gets shipped to the public).

Cheers.

**Comment by Google-Autofuzz** [comment]
Hi, 

Thanks for the quick response. If Dear ImGui uses trusted inputs, then I think it is fine without upstreaming to OSS-Fuzz.

Thanks.
