### ISSUE TITLE
Need help with glfw and shared contexts

### ISSUE THREAD

**Issue by bagobor** [ocornut/imgui#308]
I created 2 windows with shared context. 
Render to both windows. But imgui renders only to 1st window.

reference code:
https://gist.github.com/bagobor/024bc37c12bb70791171

**Comment by ocornut** [comment]
Do you want the same imgui context in 2 windows, or 2 different imgui contexts?

Well at first if you want to interact with multiple you'll probably want to modify imgui_impl_glfw_gl3.cpp
You only pass a single window to it `ImGui_ImplGlfwGL3_Init(windows[0], true);` and it manages the inputs with this assumption.

Otherwise this isn't really an ImGui specific question. All the GL/GLFW code is in imgui_impl_glfw*.cpp file and under your control. I don't know how multiple GL contexts work.

**Comment by bagobor** [comment]
I dont care about input at that moment. So it's Ok to pass 'main' window.

**Comment by ocornut** [comment]
If you want to render the same ImGui output twice, only call NewFrame 1 time and call Render twice with your different GL context. Or call Render once and inside the render function render twice.

When you call NewFrame it delete all the output.

If you want to render two different ImGui you need two ImGui context.

**Comment by ocornut** [comment]
I don't know why your game doesn't work but it's not really an ImGui issue.

**Comment by bagobor** [comment]
It's not game. small app with basic UI stuff. 
Currently I want to render _same_ UI twice.

I'm not profound with shared context, so ... after investigations ... it seems that all VAO object are not shared. 
Look like that's the reason of my black screen on second context.

**Comment by bagobor** [comment]
Thanks replies.
I made dirty fixes to base code to work with shared contexts.

**Comment by ocornut** [comment]
Cool :)
