### ISSUE TITLE
Modal dialog, why is it with ImGuiWindowFlags_NoSavedSettings ?

### ISSUE THREAD

**Issue by aiekick** [ocornut/imgui#3091]
Hello,

Version: 1.76
Branch: docking

i would like to know what is the reason where modal dialog are declared with flag ImGuiWindowFlags_NoSavedSettings.

i have a file diallog im using with modal dialog, and at start its always in defualt size who is small and i need to resize it.
but if i reactivate by disabling ImGuiWindowFlags_NoSavedSettings in ImGui::BeginPopupModal
i can have the filedialog with custom size after loading.

its annoying to do that at each app start.

can we remove ImGuiWindowFlags_NoSavedSettings at line 8456 of imgui.cpp in function ImGui::BeginPopupModal, ?

**Comment by ocornut** [comment]
Hello,

I have a task to evaluate this in my short list, it’s probable that we will make this change happen soon.

**Comment by aiekick** [comment]
cool, thanks

**Comment by ocornut** [comment]
FYI I was tracking the source for it been there since the initial commit:
bce495c5813898a4eae503ac02fe8a2d353bdc19

(Perhaps modal windows probably should not need to follow the popup api, it's just getting in the way for many reasons.)

**Comment by ocornut** [comment]
Implemented that change now.

Some very tangential thoughts (copying same message in #3091)

(
Generally speaking, modals tends to be closer to regular windows than they are to popups, and I imagine a revamp where we could fully use `Begin()` with `ImGuiWindowFlags_Modal` (as suggested by #402) and keep control of visibility. The `BeginPopupModal()` api could still work. 

Centering a modal window is surprisingly unobvious in a multi-viewport context, there are just many desirable scenarios. Considering an hypothetical `GetFocusedViewport()` returning ~~g.NavWindow->Viewport

```
SetNextWindowPos(GetFocusedViewport()->GetCenter(), ImGuiCond_Appearing, ImVec2(0.5f, 0.5f));
```

Won't work as expected due to how `ImGuiCond_Appearing` is set and because the focused/nav window tends to evolve across appearing frames. We probably need variety of access to monitors and viewports tagged with semantic (e.g. access to "focused (last interacted with?) monitor", access to "viewport from where popup was activated", access to "monitor mouse is in") and let the user choose. And I guess we may need to create more continuity between viewports and monitors down the line. Finishing work on the "there are no main viewport" task will probably help enforce this.

Currently the code and demo code uses `io.DisplaySize * 0.5f` in `master` branch and selectively CurrentWindow->Viewport's center or GetMainViewport()'s center in `docking`  branch, which are ALL arbitrary, we ought to design standards and have them integrated in master asap.
)
