### ISSUE TITLE
Assertion always fails in a new session when a window has a tab dockspace DockId written in the ini file

### ISSUE THREAD

**Issue by Lin20** [ocornut/imgui#3101]
**Version/Branch of Dear ImGui:** 

Version: 1.76 WIP (17502)
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Compiler: MSVC 2019
Operating System: Windows 10

**My Issue:**

The assertion
```CPP
IM_ASSERT(g.CurrentTabBar == NULL);
```
inside the function
```CPP
void ImGui::TabBarAddTab(ImGuiTabBar* tab_bar, ImGuiTabItemFlags tab_flags, ImGuiWindow* window)
```
always fails if the user docks a window inside of a tab with a dockspace, that dock id is written to the ini file, and then the application runs in a new session. It's only if the window is docked. Removing the assertion makes the application run as expected, with no issues across sessions.

The line inside the ini file causing the problem is
```CPP
DockId=0x00000001,0
```
and removing that makes the assertion pass.

**Standalone, minimal, complete and verifiable example:**
```CPP
ImGui_ImplOpenGL3_NewFrame();
ImGui_ImplGlfw_NewFrame();
ImGui::NewFrame();

static ImGuiID tab_space_id = 0;
tab_space_id = ImGui::GetID("TabDockSpace");

auto viewport = ImGui::GetMainViewport();
ImGui::SetNextWindowPos(viewport->GetWorkPos());
ImGui::SetNextWindowSize(viewport->GetWorkSize());
ImGui::SetNextWindowViewport(viewport->ID);
ImGui::Begin("Main backwindow", 0, ImGuiWindowFlags_NoBackground | ImGuiWindowFlags_NoBringToFrontOnFocus | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoTitleBar);
{
	if (ImGui::BeginTabBar("This is a tab bar"))
	{
		if (ImGui::BeginTabItem("This is a tab", 0))
		{
			ImGui::DockSpace(tab_space_id);

			if (ImGui::Begin("This is a window"))
			{
			}
			ImGui::End();


			ImGui::EndTabItem();
		}

		ImGui::EndTabBar();
	}
}
ImGui::End();

ImGui::Render();
ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
```

**Comment by ocornut** [comment]
Hello @Lin20,

Thanks for the repro.

I confirm this is a bug and pushed a fix for it (thanks to @rokups who helped me investigate that).

The assert is a little more loose now, I think it's not ideal and I'd like to turn it into a stricter ~ `tab_bar->CurrFrameActive < g.FrameCount` type of test but that requires solving another hard to repro case with multiple calls to DockNodeUpdate leading to multiple BeginTabBar submission, we can investigate that later.

Important note!
Your code works because luckily "This is a window" is submitted in the same scope as when the host tab is active. Now imagine this more common scenario where you'd dock a window submitted elsewhere:

```
            if (ImGui::BeginTabBar("This is a tab bar"))
            {
                if (ImGui::BeginTabItem("This is a tab", 0))
                {
                    ImGui::DockSpace(tab_space_id);

                    ImGui::EndTabItem();
                }
                if (ImGui::BeginTabItem("BBB"))
                {
                    ImGui::EndTabItem();
                }
                ImGui::EndTabBar();
            }

                if (ImGui::Begin("This is a window you may dock into that dockspace"))
                {
                }
                ImGui::End();
```

If you dock the window into that dockspace and select the "BBB" tab, **the dockspace will cease to exist and the window will be undocked**. The solution here is to always submit the dockspace with the KeepAlive flag:

```
if (dockspace_submitted == false)
   ImGui::DockSpace(tab_space_id, ImGuiDockNodeFlags_KeepAliveOnly);
```

If someone the window you'd want to dock into that dockspace can have the same lifetime as the dockspace, then you won't have the problem, and to prevent other windows from docking into that dockspace you may use ImGuiWindowClass's ClassId mechanism.

**Comment by ocornut** [comment]
(You may want to delete your 2 messages in the docking thread, as it is already very cluttered and github issue viewer unfortunately hide even more central messages based on total message count, already sent feedback to github I hope it gets fixed and they can turn their system into a multipage thing instead)
