### ISSUE TITLE
Viewports via example impl files without main window rendering

### ISSUE THREAD

**Issue by prime31** [ocornut/imgui#3112]
I have a situation where my main window graphics backend gets decided at runtime and could be GL, Metal, Vulkan, software, etc. I've got Dear ImGui rendering well in all of them but I would like to use viewports via the OpenGL3 + SDL example files since all of the viewport windows that get generated can be OpenGL. Is there a recommended way to use the imgui_impl_* files _only_ for extra windows generated via viewports? Some specific calling order or pointers on how to pull something like this off would be greatly appreciated. Thanks!

**Comment by ocornut** [comment]
It would probably work with some hacking, I can't say specifically what needs to be tweaked in the backends but it sounds possible.

You wouldn't be able to share textures betweeen non GL and GL of course, it may be an ok restriction, and you'd need to figure a way for the GL backends to update its own atlas. A trick which might render this easier may be to also maintain the "main viewport" on the GL backend side, so that's were you'd be uploading the atlas texture, and other viewports can use this GL context to share data, but not actually render/swap this GL context.

I still imagine it would be simpler and more natural to have secondary viewports be handled using the same graphics API at the main viewport.

**Comment by prime31** [comment]
Thanks for the tips!
