### ISSUE TITLE
Adding border on hover

### ISSUE THREAD

**Issue by blakat360** [ocornut/imgui#3132]
**Version/Branch of Dear ImGui:**

Version: https://github.com/ocornut/imgui/commit/9f9ff84ba145d30b21641deca34055b18b183cf3
Branch: Master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp

**My Issue/Question:**

I want to add a border to a button only when I hover over it. I'm finding this hard as I've only found ways to read whether I am hovering over a something once I have drawn it (which means all styling choices have already been applied).

**Screenshots/Video**

This is the look I am going for:
![WhatsApp Image 2020-04-16 at 20 32 59](https://user-images.githubusercontent.com/37976322/79498671-9c226f80-8021-11ea-90df-cd75b8666f92.jpeg)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

Ideally I'd like an interface of:
```
ImGui::PushStyleVar( ImGuiStyleVar_ChildBorderSizeHovered, someFloat );
ImGui::PushStyleColor(ImGuiCol_BorderHovered, someImVec4 );
```
Failing that, supporting rendering different textures into a component when it is hovered would let me solve my issue.

**Comment by ocornut** [comment]
This is not possible currently, but it is aimed that styling v2 (no timeframe) will support that.

**Comment by blakat360** [comment]
Thanks - I have a decent amount of time on my hands so would be happy to help implement this. Would just need a clear spec.

**Comment by ocornut** [comment]
I don’t have detailed specs, its a wide topic.  if you browse styling topics you may get a glimpse at some of the needed things.

Right now what we are working is slowly reworking low-level primitives (texture based round corners, cheaper thick lines, shadows, gradients, text functions) as they will be the backbone of empowering style v2.

What you can do now which will both solve your issue faster and give both you and us more useful data about styling, is you can try to rewrite your own widgets. Writing a button function using ButtonBehavior is very easy and you can do its rendering with your own colors. So instead of relying on standardized styling storage just draw whichever border/shape you need with the color you need. You’ll be surprised to find you can probably achieve result fast.

From there your problem will be that you have a button looking like the one above but other widgets won’t follow so you’ll rewrite more widgets.

This exercice can get you surprisingly good results and if you post your results here we’ll be better equipped for style v2 as every custom widgets sets will help into the final design.

**Comment by blakat360** [comment]
Do you have any examples of these implementations I could see?

**Comment by ocornut** [comment]
The Button()/ButtonEx() function.

**Comment by blakat360** [comment]
Thanks - done this. Currently I'm using the following pattern:

in global scope:
```
bool button1Clicked, button1Hovered;
```

in render function:
```
auto [clicked, hovered] = button1Hovered ?
            ImGui::CustomButton(
            "foo", ImVec2(100,100), 0) :
                    ImGui::CustomButton(
            "bar", ImVec2(100,100), 0);
    button1Clicked = clicked; button1Hovered = hovered;
```

Going to do something similar for the ImageButton now. That way I can render buttons with different textures based on button state with a 1 frame delay.

As you're considering a serious rewrite, I'd strongly urge towards supporting the standard template library.

**Comment by blakat360** [comment]
Here is the interface we're going with.

```
    ImGui::Begin( "Window" );

    ImGui::Button( "banter", ImVec2( 50, 50 ),
                         0xff0000ff, 0x00ff00ff, 0x0000ffff );

    ImGui::ImageButton( "lol",
            textures.getTextureForImGui( "water2" ),
            textures.getTextureForImGui( "water" ),
            ImVec2( 300, 300 ),
            0xff0000ff, 0x00ff00ff, 0x0000ffff );

    ImGui::End();
```

This way hex codes allow explicit styling and can be copied and pasted out of colour pickers.

We have gone with changing texture on hover to customise the buttons exactly to our taste. 

It would be ace if you could add border size on hover as well as border colour and style when you push style v2.

**Comment by ocornut** [comment]
Please note that for the new functions you created, never modify imgui files and functions, but rather just add the functions in your own files. Because ImGui:: is a namespace to add can extra functions to it from any of your source files.

Closing this issue now.
