### ISSUE TITLE
Tables: ItemWidth is not setup or adjusted per-column

### ISSUE THREAD

**Issue by Kodokuna** [ocornut/imgui#3156]
```
Dear ImGui 1.77 WIP (17601)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201703
define: _WIN32
define: _WIN64
define: _MSC_VER=1925
define: __clang_version__=10.0.0 
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_dx11
io.ConfigFlags: 0x0000C441
 NavEnableKeyboard
 DockingEnable
 ViewportsEnable
 DpiEnableScaleViewports
 DpiEnableScaleFonts
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigWindowsMemoryCompactTimer = 60.0f
io.BackendFlags: 0x00001C0E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1264.00,761.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Version/Branch of Dear ImGui:**

Version: 1.77 WIP
Branch: Tables merged into docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx11.cpp 
Compiler: clang 10
Operating System: Windows 10

**My Issue/Question:**

InputScalar with a step value inside a Table only shows the step '-' and '+' if the column is very small otherwise they are not shown at all.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/4653051/80129108-eada8700-8596-11ea-9848-5305b4c33ccd.png)
![image](https://user-images.githubusercontent.com/4653051/80129161-f9c13980-8596-11ea-9ca8-c991d8b34cfa.png)
![image](https://user-images.githubusercontent.com/4653051/80129168-ff1e8400-8596-11ea-9049-24998b10df8c.png)

**Standalone, minimal, complete and verifiable example:** 
```
ImGui::Begin("Bug Report");

static unsigned short value = 1;
static unsigned short step = 1;

// Correct
ImGui::InputScalar("##Value", ImGuiDataType_U16, &value, &step);

if(ImGui::BeginTable("Test", 2)) {
    ImGui::TableSetupColumn("Header1");
    ImGui::TableSetupColumn("Header2");
    ImGui::TableAutoHeaders();
    
    ImGui::TableNextRow();
    
    ImGui::TableSetColumnIndex(0);
    // Wrong
    ImGui::InputScalar("##Value", ImGuiDataType_U16, &value, &step);
    
    ImGui::TableSetColumnIndex(1);
    ImGui::Text("Test");
    
    ImGui::EndTable();
}

ImGui::End();

**Comment by ocornut** [comment]
Hello,

I believe the issue is not related specifically to `InputText()`, but to the fact that the Tables api currently doesn't do any alteration of ItemWidth on a per-column basis, so you are inheriting the last value of ItemWidth set in the window.

The old Columns API did this weird thing were _every_ call to NextColumn() would reset ItemWidth to an arbitrary factor:
`PushItemWidth(width * 0.65f);`

Obviously, it's not right that the Tables api doesn't do anything, but when it does something it's likely to be not the same as what Columns did. Maybe we should have a per-column default and preserve the per-column default across rows?

Right now, the work-around for you is simply to set an ItemWidth value, the same way you would likely want to do to override the default one set by columns.

```
SetNextItemWidth(-1.0f); // right align
InputScalar(...)
```

```
PushItemWidth(-1.0f);
InputScalar(...)
PopItemWidth()
```

I'm adding note to come up for a suitalbe default-behavior design!

**Comment by ocornut** [comment]
Hello,

With a31ce5b ItemWidth is now preserved for each columns.
Also added a simple demo to explain it:

![image](https://user-images.githubusercontent.com/8225057/99826257-65cd4580-2b58-11eb-815c-03dab207ffc5.png)

And improved the `Demo>Layouts->Widgets Width` section of the demo too.
