### ISSUE TITLE
Support for unsigned, double and 64bit int types

### ISSUE THREAD

**Issue by kylawl** [ocornut/imgui#320]
Right now everything eventually becomes the 32bit float editor. We'd love to also see uint64_t, int64_t, uint32_t, and double in there.

Thanks!

**Comment by ocornut** [comment]
Which widgets are you thinking about exactly?
Input, Drag, Slider, something else?
Inputs you can easily wrap them around yourself using InputText()  Do you *actually* need all those types? Can't imagine someone wanting to use a slider that requires an unsigned int 32 when you can just cast the pointer to signed int and have a 2 billion range available.

**Comment by kylawl** [comment]
Basically we have a pretty complete c++ reflection system and want to be able to inspect and modify all the data types for debugging. But you're right for our usage, it probably makes the most sense to just use InputText() and sort it out, obviously we don't need drag/sliders for this stuff.

**Comment by ocornut** [comment]
Good! 
In theory it would be convenient to have all types available but I believe the use cases would be abnormally rare (e.g. using a Drag on an actual int64 value will all the range available, If you don't access all the range the function can be wrapped). Right now I don't have an easy way to implement that without messing up the code so I decided on skipping it.

InputFloat() / InputInt() have some extra features compared to what you'd typically do yourself with InputText()+scanf: buttons and arithmetic ops (you can type e.g. *100 in an InputFloat() box to multiply the value by 100). You should be able to replicate those features in your own versions if you really fancy them. Otherwise InputText()+scanf should work.

**Comment by ocornut** [comment]
FYI, I have added functions in a branch to work with float, double, 32/64 bits, signed and unsigned (and in a proper lossless manner, as previously some functions didn't work great with big integers).
See #643 for details.
