### ISSUE TITLE
Add lambda overloads for functions with callbacks

### ISSUE THREAD

**Issue by PazerOP** [ocornut/imgui#3235]
This is a feature request for support for C++11 lambdas in callbacks. I find that having a capturing lambda is much easier than manually making a struct with the data I need in my callback and casting to/from `void*`. I created this issue because I seem to remember seeing somewhere that a C++11 requirement for ImGui was coming soon. However if that's not the case, this issue can be closed (for now?).

Consider the following function: 
```C++
bool Combo(const char* label, int* current_item, bool(*items_getter)(void* data, int idx, const char** out_text), void* data, int items_count, int popup_max_height_in_items = -1);
```

A wrapper function can be added around the existing Combo function that uses the void pointer to support lambdas. There is a small performance impact from doing this because of the extra function call, but I'd imagine that would be mostly irrelevant.
```C++
template<typename TFunc>
inline void Combo(const char* label, int* current_item, TFunc items_getter, int items_count, int popup_max_height_in_items = -1)
{
	const auto patch = [](void* data, int idx, const char** out_text)
	{
		return (*reinterpret_cast<TFunc*>(data))(idx, out_text);
	};

	return ImGui::Combo(label, current_item, patch, const_cast<void*>(&items_getter),
		items_count, popup_max_height_in_items);
	}
```

I'm willing to make a pull request for this, but I wanted to get feedback on the idea first.

**Comment by ocornut** [comment]
Hello,

You can add those functions in your code in the ImGui:: namespace, there’s no need to add them to core imgui.

In addition, please note that using the BeginCombo/EndCombo is much more flexible and doesn’t present the same constraints at all, so thats generally recommended.

(We don’t have C++11 as minimum requirement yet but I wouldn’t rule out offering C++11 features behind ifdef if it made sense!)

-omar

**Comment by PazerOP** [comment]
Hello, thanks for your reply.

I realize I can add these functions in my own code, but I usually end up rewriting them every single time I need them. I am proposing adding them to core imgui, since IMO the less time people have to spend casting stuff to void* and back, the better.

I also realize that for this specific example, BeginCombo/EndCombo is available. However, there are other functions that have callbacks like this, such as ListBox, PlotLines, and PlotHistogram. Anecdotally, I usually don't need the flexibility that BeginCombo/EndCombo offers, and I prefer avoiding Begin/End functions when possible, since it reduces the likelihood of bugs in my code.

Perhaps you would consider a separate header/cpp file for C++11 features, like is done with imgui_stdlib?

**Comment by PazerOP** [comment]
Hello again,

If you're not convinced by my above messages and/or you don't think this should be added to imgui core, feel free to close this issue.

**Comment by ocornut** [comment]
> However, there are other functions that have callbacks like this, such as ListBox, PlotLines, and PlotHistogram
> If you're not convinced by my above messages and/or you don't think this should be added to imgui core, feel free to close this issue.

All those api are somehow unperfect and old, ListBox is better replaced with ListBoxHeader/Footer similar to BeginCombo/EndCombo and PlotLines/PlotHistogram are stagnant from 1.0 better replaced with something like https://github.com/epezent/implot. So while in theory I wouldn't mind adding stuff to imgui_stdlib here specifically we are talking about adding extra entry points to potentially already obsolete functions so I'm not sure that's a good idea right now, in particular since you can add a 5 lines function in a header file of your own and reduce it.

So yeah, thinking a little more about it I think it's best to not merge this in core imgui presently.
Whenever I get around to redesign the ListBox stuff with proper Begin/End function it may make more sense then, I'll tag this issue again!

Thanks a lot!
