### ISSUE TITLE
How to disable Ctrl-tab menu ?

### ISSUE THREAD

**Issue by DaveInDev** [ocornut/imgui#3255]
Version: Dear ImGui 1.77 WIP (17601)
Branch: master
Back-ends: SFML
Compiler: VS2019 c++
Operating System: win10x64

Hi,

How do I disable the Ctrl-tab menu ? 
Because I would like to use ctrl-tab to manage my own window navigation logic, including other Non-Imgui windows.

**Comment by ocornut** [comment]
Hello,

Ctrl+Tab handling is currently enabled with keyboard navigation, aka setting the `ImGuiConfigFlags_NavEnableKeyboard` configuration flag.

In theory we could add detailed flags to enable/disable subfeatures of keyboard navigation but I'd be interested in figuring out a more general way of dispatching inputs where you would somehow mark the ctrl+tab as handled and nav system won't handle that.

Pragmatically it may be faster to expose those enable/disable flags sooner (I can think of situation where e.g. it would also be good to selectively enable/disable page up/page down).

**Comment by DaveInDev** [comment]
Thanks. Reading the comments in the main code, I did not figure out what was covered by the term "navigation" : now I understand better (I just found in the demo code the explanation that I missed ). 

Alas, the other features of navigation (esc, space, enter) were useful to me. But infact I am stupid : I just can steal this precise ctrl-tab event just before the call to ImGui::ProcessEvent... It should not be a problem, is it ?

For your suggestions, indead, a way to handle these inputs separately, or maybe to reaffect theses naviguation keys would be great. By the way, what do you mean by "expose flags sooner" ? I read this expression a lot of time in the issues, but I do not understand what it means.

**Comment by ocornut** [comment]
> I just can steal this precise ctrl-tab event just before the call to ImGui::ProcessEvent

You can't really steal or claim to handle inputs, that's my point. The only think you can do is to clear inputs manually before passing them to `NewFrame()` but that's not going to work for operations that rely on more context (Ctrl+Tab doesn't rely on much context, but say, PageUp depends on the active widget). Additionally there's no `ProcessEvent` function in dear imgui so I'm not sure what you are referring to. Inputs are exposed and available thorough the frame.

"Expose flags" = "add flags"
"Sooner" as is, not "later" ??

I'm saying we could always add flags to select which feature to enable, but this is ultimately not the right solution (the right solution is to have a way to dispatch inputs, and it's going to be complex considering how dear imgui work), but the right solution being complex maybe it's ok to add the flags soon instead of waiting forever for the right solution..

**Comment by DaveInDev** [comment]
Sorry, the ProcessEvent function is from the SFML backend, to send an event to ImGui from the event polling loop of my app :  ImGui::SFML::ProcessEvent(event) . 

So, by stealing, I really mean not sending this particular ctrl-tab event to ImGui at all. I agree that it cannot be a solution for more complex keys that works only on some precise widgets. 

> "Sooner" as is, not "later" ??

:-D    I was more interested in the meaning you were giving to "expose".

For the perfect solution of "dispatching inputs", as ImGui is always working "one frame later" (or is not aware of its full state until the end of the frame due to its inherent immediate mode), I cannot figure out how you could dispatch inputs ahead. 

Imho, a few flags could definitely do the job.

**Comment by caxapexac** [comment]
Ctrl+tab changes tab in browser

Proof: https://stackoverflow.com/questions/56835762/how-to-disable-ctrltab-in-javascript
Proof: https://stackoverflow.com/questions/8195175/javascript-code-to-press-ctrltab

So I need to be able to change combo from Alt+Tab to something else
i.e. IntelliJ uses Shift+Shift for this
i.e. IDE's uses Shift+Space for intellisense so it shoud be conveniently too

**Comment by ocornut** [comment]
Moving followup to #4828

**Comment by ocornut** [comment]
Pushed a few new features and you can now do:

```cpp
#include "imgui_internal.h"

// Disable CTRL+Tab shortcuts (global): assign a "None" route to steal the route to our two shortcuts
ImGui::SetShortcutRouting(ImGuiMod_Ctrl | ImGuiKey_Tab, ImGuiKeyOwner_None);
ImGui::SetShortcutRouting(ImGuiMod_Ctrl | ImGuiMod_Shift | ImGuiKey_Tab, ImGuiKeyOwner_None);
```
or
```cpp
// Disable CTRL+Tab shortcuts (if focused): assign a "None" route to steal the route to our two shortcuts, applies focus testing so will only apply if window is in focus chain
ImGui::SetShortcutRouting(ImGuiMod_Ctrl | ImGuiKey_Tab, ImGuiKeyOwner_None, ImGuiInputFlags_RouteFocused);
ImGui::SetShortcutRouting(ImGuiMod_Ctrl | ImGuiMod_Shift | ImGuiKey_Tab, ImGuiKeyOwner_None, ImGuiInputFlags_RouteFocused);
```

However, as per #4828 we made the exception to allow remapping CTRL+Tab windowing system. Therefore technically the right shortcut needs to be pulled:

```cpp
if (g.ConfigNavWindowingKeyNext)
    ImGui::SetShortcutRouting(g.ConfigNavWindowingKeyNext, ImGuiKeyOwner_None);
if (g.ConfigNavWindowingKeyPrev)
    ImGui::SetShortcutRouting(g.ConfigNavWindowingKeyPrev, ImGuiKeyOwner_None);
```
But this is only if you want to both allow remapping AND disabling of the shortcuts.

(cross posted to #3255 and #5641)

**Comment by liamwhan** [comment]
Can I ask where this is supposed to happen? When I try to call the first (global) example I hit this IM_ASSERT in `imgui.cpp` L8604 in commit 6ccc561:
```cpp
 IM_ASSERT(owner_id != ImGuiKeyOwner_Any && owner_id != ImGuiKeyOwner_None);
```


> Pushed a few new features and you can now do:
> 
> ```c++
> #include "imgui_internal.h"
> 
> // Disable CTRL+Tab shortcuts (global): assign a "None" route to steal the route to our two shortcuts
> ImGui::SetShortcutRouting(ImGuiMod_Ctrl | ImGuiKey_Tab, ImGuiKeyOwner_None);
> ImGui::SetShortcutRouting(ImGuiMod_Ctrl | ImGuiMod_Shift | ImGuiKey_Tab, ImGuiKeyOwner_None);
> ```
> 
> or
> 
> ```c++
> // Disable CTRL+Tab shortcuts (if focused): assign a "None" route to steal the route to our two shortcuts, applies focus testing so will only apply if window is in focus chain
> ImGui::SetShortcutRouting(ImGuiMod_Ctrl | ImGuiKey_Tab, ImGuiKeyOwner_None, ImGuiInputFlags_RouteFocused);
> ImGui::SetShortcutRouting(ImGuiMod_Ctrl | ImGuiMod_Shift | ImGuiKey_Tab, ImGuiKeyOwner_None, ImGuiInputFlags_RouteFocused);
> ```
> 
> However, as per #4828 we made the exception to allow remapping CTRL+Tab windowing system. Therefore technically the right shortcut needs to be pulled:
> 
> ```c++
> if (g.ConfigNavWindowingKeyNext)
>     ImGui::SetShortcutRouting(g.ConfigNavWindowingKeyNext, ImGuiKeyOwner_None);
> if (g.ConfigNavWindowingKeyPrev)
>     ImGui::SetShortcutRouting(g.ConfigNavWindowingKeyPrev, ImGuiKeyOwner_None);
> ```
> 
> But this is only if you want to both allow remapping AND disabling of the shortcuts.
> 
> (cross posted to #3255 and #5641)

**Comment by ocornut** [comment]
@liamwhan 
> Can I ask where this is supposed to happen? When I try to call the first (global) example I hit this IM_ASSERT in imgui.cpp [L8583](https://github.com/ocornut/imgui/blob/6ccc561a2ab497ad4ae6ee1dbd3b992ffada35cb/imgui.cpp#L8583C5-L8583C80) in commit https://github.com/ocornut/imgui/commit/6ccc561a2ab497ad4ae6ee1dbd3b992ffada35cb:

Sorry for my late answer.
The instructions in this thread for generic rerouting are obsolete. 

----

**About specifically disabling CTRL+TAB ONLY**
However as pushed by 6ccc561a2 and mentioned above if you specifically only want to disable CTRL+Tab you can do:

```cpp
g.ConfigNavWindowingKeyNext = 0; // replace the default which is `ImGuiMod_Ctrl | ImGuiKey_Tab`
g.ConfigNavWindowingKeyPrev = 0; // replace the default which is `ImGuiMod_Ctrl | ImGuiMod_Shift | ImGuiKey_Tab`.
```
Full details there: https://github.com/ocornut/imgui/issues/4828#issuecomment-1307755722

---

**About GENERIC shortcut routing (which can be leverage for everything, not just CTRL+Tab).**
Since I posted this thread, those API have been reworked and some have been moving to public space.

- (1) Parameters 2 and 3 have been swapped since the prototype.
So `ImGui::SetShortcutRouting(ImGuiMod_Ctrl | ImGuiKey_Tab, ImGuiKeyOwner_None);`
Should be `ImGui::SetShortcutRouting(ImGuiMod_Ctrl | ImGuiKey_Tab, ImGuiInputFlags_None, ImGuiKeyOwner_NoOwner);`
- (2) `ImGuiKeyOwner_None` was previously accepted by `SetShortcutRouting()` was a shortcut to use the current focus scope, but it's been disallowed because it is error prone. However the higher level `Shortcut()` accept this.
- (As for `ImGuiInputFlags_None`, it is guaranteed to be 0 like every other value called `_None` value in dear imgui. I have  renamed `ImGuiKeyOwner_None` to `ImGuiKeyOwner_NoOwner` partly to keep that distinction.)

So effectively now you can do:

```cpp
ImGui::Shortcut(ImGuiMod_Ctrl | ImGuiKey_Tab, ImGuiInputFlags_RouteGlobal);
ImGui::Shortcut(ImGuiMod_Ctrl | ImGuiMod_Shift | ImGuiKey_Tab, ImGuiInputFlags_RouteGlobal);
```

Some examples have been added in the demo:
![image](https://github.com/user-attachments/assets/a9c9b321-eab2-431f-98ec-816dc3d67588)

And there are more examples in a temporary "demo_input_owner_and_routing" branch:
https://github.com/ocornut/imgui/compare/master...features/demo_input_owner_and_routing
The reason those examples are currently in a branch is because the third parameter "owner_id" wasn't added to the public API yet, so any example that uses them is still in this branch, but you can refer to it for more ways to take advantage of those features.

**Comment by ocornut** [comment]
Strangely I have replied to Liam _before_ seeing Diego answer, which says basically the same thing. Both answers complement each others and are going in the same direction.
