### ISSUE TITLE
Docking and cleaning up ini file

### ISSUE THREAD

**Issue by timeinpixels** [ocornut/imgui#3271]
Hey guys!

I'm exploring the docking possibilities if ImGui and love it so far.
I have one question thought - my application creates dynamic windows (each instance is a new window with a new ID - say, GUID). It means tat the number of stored settings in the ini file constantly grows. 

Is there a way to "clean up" the ini file each time the specific window is closed (so that its settings are no longer saved in the ini file)? This means also to remove it from the docking tree stored in the ini file.

**Comment by ocornut** [comment]
> Is there a way to "clean up" the ini file each time the specific window is closed
> This means also to remove it from the docking tree stored in the ini file

Unreferenced dock nodes are garbage collected during initialization (when loading .ini data).

> It means tat the number of stored settings in the ini file constantly grows.

You'll still probably get into this because I don't imagine `ImGuiWindowFlags_NoSavedSettings` is what you want. My recommendation would be to not sure raw GUID as your window ID but allocate/recycle from a pool which will only grow with the maximum number of windows open. You would then need to store the GUID>NumberedID map yourself.

**Comment by timeinpixels** [comment]
Reusing window ID's sounds like a good plan - I just need to make sure that when I have a window "A" and I dock it, it should be "undocked" when closed so that when it is reused it will open as "floating", not docked in its old position.

**Comment by ocornut** [comment]
You could maybe also set `SetNextWindowDockId(0, ImGuiCond_Appearing)` to reset dock state when a window reappear.

**Comment by timeinpixels** [comment]
For now, as a dirty solution, I used `ImGui::DockContextQueueUndockWindow` from the internal header and it seems to be working. But will definitely look into `SetNextWindowDockId`!

**Comment by ocornut** [comment]
Closing this as solved, let me know if not the case.
