### ISSUE TITLE
Is ImGuiStyle.WindowFillAlphaDefault necessary?

### ISSUE THREAD

**Issue by ApoorvaJ** [ocornut/imgui#337]
Is there a specific use case for `WindowFillAlphaDefault`, or is it a remnant of the evolution of the API?

You can already control the window background alpha on a per-window basis using `ImGui::PushStyleColor(ImGuiCol_WindowBg, ...)` and globally using `ImGui::GetStyle().Colors[ImGuiCol_WindowBg] = ...`.

`WindowFillAlphaDefault` makes things confusing, because unlike all other colors, there is this "secret" additional variable that controls window background alpha.

Can we just remove `WindowFillAlphaDefault`?

**Comment by ocornut** [comment]
You are right it is just a remnant of pre-1.0 version. I'll look into removing it.

-omar

**Comment by ocornut** [comment]
There are a few side effects to just removing that but I will work on sorting them out.
For now while I was working on some styling tweaks I have made the value more visible, and the ImGui Demo window also uses this value by default (instead of an hardcoded 0.65).

![style_fill_alpha](https://cloud.githubusercontent.com/assets/8225057/11767345/8161ad08-a1a2-11e5-94ac-7dbff6a35b59.png)

**Comment by ApoorvaJ** [comment]
Thanks. The added visibility in the demo window will help a lot in terms of self-documentation.

Loving the red color theme, btw. :)

**Comment by ocornut** [comment]
So, I could remove it and flatten in into the WindowBg values. Default value for WindowFillAlphaDefault is 0.7f and default value for Colors[ImGuiCol_WindowBg].a = 1.0f; so that alpha would become 0.7f.

If I change Colors[ImGuiCol_WindowBg].a to 0.7f then what do we do with the "historical" bg_alpha parameter of Begin() ?
- If it is a multiplier to xxxxBg.a then how can the user specify an opaque window using this bg_alpha parameter? (they cannot, or have to use 1.0f / xxxxBg.a which is awkward)
- If it is a override to xxxxxBg.a then I can keep the default to -1.0f (don't override), and that value will merely be a shortcut to modifying alpha of the appropriate WindowBg* before Begin(), which is fine by me. So I will likely go for that.

**Comment by ocornut** [comment]
So, I could remove it and flatten in into the WindowBg values. Default value for WindowFillAlphaDefault is 0.7f and default value for Colors[ImGuiCol_WindowBg].a = 1.0f; so that alpha would become 0.7f.

If I change Colors[ImGuiCol_WindowBg].a to 0.7f then what do we do with the "historical" bg_alpha parameter of Begin() ?

- If it is a multiplier to xxxxBg.a then how can the user specify an opaque window using this bg_alpha parameter? (they cannot, or have to use 1.0f / xxxxBg.a which is awkward)
- If it is a override to xxxxxBg.a then I can keep the default to -1.0f (don't override), and that value will merely be a shortcut to modifying alpha of the appropriate WindowBg* before Begin(), which is fine by me.
- But I am actually sort of tempted to actually KEEP the value because it makes bulk edition of WindowBg* parameter easier, and add the corresponding enum for PushStyleVar().

**Comment by ocornut** [comment]
Done, removed `WindowFillAlphaDefault`.
Note:

```
API BREAKING CHANGES
 - 2016/04/03 (1.48) - removed style.WindowFillAlphaDefault setting which was redundant. Bake default BG alpha inside style.Colors[ImGuiCol_WindowBg] and all other Bg color values. (ref github issue #337).
 - 2016/04/03 (1.48) - renamed ImGuiCol_TooltipBg to ImGuiCol_PopupBg, used by popups/menus and tooltips. popups/menus were previously using ImGuiCol_WindowBg. (ref github issue #337)
```
