### ISSUE TITLE
Mouse interaction in multi-viewport

### ISSUE THREAD

**Issue by SamGit1122** [ocornut/imgui#3404]
I have a multiple viewport ImGui application using docking branch. Two of these viewports display OpenGl content from different angles and are interacting with mouse. So as suggested by many, I use frame buffers and display them using ImGui::Image.

`ImGui::Image((void *) textureID, pannelSize, ImVec2{0, 1}, ImVec2{1, 0});`

The challenge is finding best way to handle mouse interaction (figure out the position of click in each viewport). All these options provide different results, and none of them are relative to corner of view port. I display them using ImGui::Text.

1. glfwGetCursorPos(_GLFWwindow, &x, &y);
2. _screenXY_ImGui = ImGui::GetCursorScreenPos();
3. _mouseXY_ImGui = ImGui::GetMousePos();

So what I am doing now is to find the relative values (value starting at 0) by subtracting **ImGui::GetWindowContentRegionMin().x + ImGui::GetWindowPos().x** from x obtained from glfwGetCursorPos. It works more or less but has very small shift.

I have 2 questions and 1 suggestion:
1) Is there an ImGui built-in function to provide local and relative mouse position?
2) Is it better to use GLFW to interact with window or ImGui? 
3) It would be great if you can add a minimal multi-viewport basic OpenGL interactive example to the demo. I think it would help many who are developing their own engine and cannot use DrawList. Many of existing projects on github is too complex.

**Comment by ocornut** [comment]
(1) 
The position of your `ImGui::Image()` call can be obtained by using `GetCursorScreenPos()` before the Image call, so it a matter of using `mouse_pos - image_pos` to obtain a relative position. We don't and won't provide a function to perform a subtraction.

(2)
Whatever works for you depending on the context.
glfwGetCursorPos() will provide window-local coordinate, whereas with multi-viewport enabled `ImGui::GetMousePos()` uses global/imgui coordinates. Because most other positions such as `ImGui::GetCursorScreenPos()` are also in that same space it is easier to use GetMousePos and GetCursorScreenPos together.
For a GIVEN window, `GetWindowViewport()->Pos + glfwGetCursorPos()` will give the global/imgui coordinate.

(3)
We unfortunately don't have resources to provide examples for everything.
The "Image Loading and Displaying Examples" already shows how to display/load OpenGL textures in DearImGui: https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples
I suggest you talk with people on Discord to get help there.
