### ISSUE TITLE
Missing font

### ISSUE THREAD

**Issue by irenekaea** [ocornut/imgui#341]
Hello, I am trying to create a game using ImGUI and currently I am using OpenGL core profile to render the graphics. For the rendering functions, I am currently following opengl3 example. However, I have some missing font, does anyone know what is causing this issue?

![untitled](https://cloud.githubusercontent.com/assets/14138066/9976211/70fb4d50-5f0f-11e5-8718-1cc99d6c6a90.png)
![untitled1](https://cloud.githubusercontent.com/assets/14138066/9976212/74e061f8-5f0f-11e5-992f-07bbd376b646.png)

Thank you :)

**Comment by ocornut** [comment]
Your clipping rectangles are handled incorrectly.
The demo code uses
`glScissor((int)pcmd->ClipRect.x, (int)(fb_height - pcmd->ClipRect.w), (int)(pcmd->ClipRect.z - pcmd->ClipRect.x), (int)(pcmd->ClipRect.w - pcmd->ClipRect.y));`

You likely have treated ClipRect.z as width instead of x2 and w as height instead of y2.

**Comment by irenekaea** [comment]
It was actually caused by a miscalculation in the framebuffer height above that resulted in this. Your suggestion gave me a better idea as to where things could have possibly gone wrong. 
Thank you so much!!

**Comment by ocornut** [comment]
Welcome :) 
I have added FAQ entries because it is a common problem. Also mismatched dimensions are common especially because of Windows behavior with WindowSize != ClientSize.
