### ISSUE TITLE
Redundant space in TabBar

### ISSUE THREAD

**Issue by skaarj1989** [ocornut/imgui#3414]
**Version/Branch of Dear ImGui:**

Version: 1.77 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: custom engine (but same behaviour in `imgui_examples` backends)
Compiler: Visual Studio 2019 16.7.1
Operating System: Windows 10

**My Issue/Question:**

Redundant blank space in (after) tab bar (shows with mouse horizontal scroll)

I know that I could use `ImGuiWindowFlags_NoScrollWithMouse` in `BeginChild` but I need vertical scrolling

Here is something similar: https://github.com/ocornut/imgui/issues/2915

**Screenshots/Video**

![tab_bar2](https://user-images.githubusercontent.com/34756939/90511407-b188e100-e15c-11ea-9508-2e4bd29a873e.gif)
Same behaviour withou `ImGuiTabBarFlags_FittingPolicyScroll`

**Standalone, minimal, complete and verifiable example:**
```cpp
ImGui::Begin("Tab test", nullptr);
ImGui::BeginChild("##child", ImVec2(350, 100), true);
ImGui::BeginTabBar("##tab_bar", ImGuiTabBarFlags_FittingPolicyScroll);
for (int i = 0; i < 10; ++i) {
  char label[32]{ '\0' };
  sprintf_s(label, "tab #%d", i);
  if (ImGui::BeginTabItem(label)) {
    ImGui::Text("Lorem ipsum ...");
    ImGui::EndTabItem();
  }
}
ImGui::EndTabBar();
ImGui::EndChild();
ImGui::End();
```

**Comment by ocornut** [comment]
Hello,

I knew of variations on this issue for a while but - and that was surprising - no one ever reported it before, so it naturally went low in the priority queue.

In order to fix we would need to dissociate actual `ContentsSize` from (yet to be introduced) `DesiredSize`. It shouldn't be too hard to work on. 

Some widgets will need to alter DesiredSize after calling ItemSize, and as we have a planned refactor of the internal's ItemSize/ItemAdd idiom it will be a good occasion to incorporate this information in whatever comes to replace it.

**Comment by ocornut** [comment]
Should be fixed now by the 3 commits linked above.
