### ISSUE TITLE
TextWrapped cannot display string larger than 3072 chars excluding null terminator

### ISSUE THREAD

**Issue by jpbrault** [ocornut/imgui#3466]
**Version/Branch of Dear ImGui:**

Version: 1.78 WIP
Branch: table

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_SDL.cpp + imgui_impl_opengl2.cpp 
Compiler: GCC 9 / Clang 10
Operating System: Linux / Mac

**My Issue/Question:**

String larger than 3072 characters excluding null terminator are silently truncated when displayed by ImGui::TextWrapped.
In the following example, the last * character will no longer be displayed when the string size is increase past 3072.

```
#include <imgui.h>

#include <string>
#include <algorithm>

void showWindow()
{
  if ( ImGui::Begin( "Window", nullptr ) )
  {
    static int len = 3072;
    static std::string text;
    if ( ImGui::SliderInt("len", & len, 1, 4096 ) || text.empty() )
    {
      text.clear();
      text.reserve( len );
      for ( int i = 0; i < ( len - 1 ); ++ i )
      {
        text += 'A' + static_cast< char > ( i % 26 );
      }
      text += "*";
    }

    ImGui::TextWrapped( "%s", text.c_str() );
  }
  ImGui::End();
}
```

**Comment by ocornut** [comment]
Hello @jpbrault ,

Look at the code of `TextWrapped()` and do the same but use `TextUnformatted()` instead of `Text()`/`TextV()`.

The TextWrapped/TextColored wrappers assuming a format string, I'm wondering if we should have them specialize and call `TextUnformatted()` instead of `TextV()` if they notice that the format string is `%s`...

**Comment by ocornut** [comment]
Since the `TextWrapped()`, TextColored()` and `TextDisabled()` don't allow disabling format-string, I added a simple code-path in them to automatically bypass the formatting with the format-string is `%s` which as a side-effect fixes the issue you mention.

I initially put it in `TextV()` but could measure a small different in my stress test in debug builds, until we do some work to attenuate certain aggressive debug settings I think it's a good compromise to leave it this way.

Note that this expose the issue that if the format string is anything but exactly `"%s"` it will fall-back and use that buffer.

**Comment by jpbrault** [comment]
Thanks for the fix.
