### ISSUE TITLE
Remove window and dockspace settings from memory?

### ISSUE THREAD

**Issue by markitus18** [ocornut/imgui#3468]
**Version/Branch of Dear ImGui:**

Version: dear imgui, v1.77 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_SDL.cpp
Operating System: Windows 10 (running the program in x86)

**My Issue/Question:**
Hi there! Is there a way to safely remove all data associated with an ImGuiWindow? I would also like to do the same for a DockSpace and all the DockNodes associated with it. I don't mind manually removing the windows from the vectors (Windows, WindowFocusOrder, CurrentWindowStack, ...) but I would need some guidance.

**The context**:
I have a docking system where I can have multiple windows of the same type (i.e: two particle editor windows, each for a different particle system) which is working with the following logic:

1. When the user opens a new window, I load a default layout using DockBuilder. 
2. If the engine is opened, I am keeping the same layout from when it was last closed.
3. When a single window is closed, the layout of that specific window is never going to be used again

This generates an Imgui.ini file that never stops growing. Once I close a window, I have managed to edit the file and remove the data associated with the window and the dockspace, but since that data still exist in ImGui's memory, it will be saved again into the file later.

Here is a screenshot of the window system, where you can see two "Particle Editor" windows opened, which dont necessarily share the same layout at any given time.
![image](https://user-images.githubusercontent.com/10940413/93001055-9a0b0100-f52c-11ea-93b0-29ba51938912.png)

**Thanks for your time!**

**Comment by ocornut** [comment]
Hello,

Sorry for late answer. I've encountered this question a few times over the time but didn't recall there was an open question for it.

I have renamed your topic to focus on the persistent setting data which is the crux of your problem here.
Runtime window data will be held during the session (with some automatic GC for large buffers such as the ImDrawList buffers) but cease to exist on next session and I don't think it is the issue here. However your problem here is to clear the persisting data.

There's a `ClearWindowSettings()` function in imgui_internal.h since 1.89.3 which you can use for this purpose.
Similar you can use `DockBuilderRemoveNode()` to clear the docking data.

So in essence you would need to detect a document closure and proactively delete settings and dock nodes at this point.

However you are left with an issue: if your application crashes while multiple documents are reopened, and if your own persistent data doesn't make those document automatically reopen on the next session, you will accumulate settings garbage over time. 

Either you need to make sure documents are reopened, so you can clear settings on their explicit closure. Either my suggestion would be that you track some "document instance id" for open document and encode them in your window name. In your situation you are already using `###` to dissociate window title from actual ID, so you must be doing something along those lines already. And then on boot or anytime you like (could be an explicit "forgot old layout" action), you can read settings data, find the ID encoded in them, and compare that with your knowledge of open documents so you can clear that settings data.

Also see the comment and code for "imgui_unreal_style_mdi_v55.zip" here:
https://github.com/ocornut/imgui/issues/6487#issuecomment-1618241284
I believe it would be best moving further discussions to #6487
