### ISSUE TITLE
SelectableTextAlign breaks Selectables which have a negative width/height

### ISSUE THREAD

**Issue by hiddenhare** [ocornut/imgui#3493]
**Version/Branch of Dear ImGui:**

Version: 1.78
Branch: imgui-rs (Rust binding), version 0.5
Back-end: Custom

**My Issue/Question:**

Assigning non-zero values to either axis of the `SelectableTextAlign` style var will cause the `Selectable`'s label to disappear if the `Selectable` has been assigned a negative width/height in that axis.

**Example:**

    let style_token = ui.push_style_var(StyleVar::SelectableTextAlign([0.5, 0.5]));

    Window::new(&im_str!("Example 1"))
        .size([400.0, 300.0], Condition::Once)
        .build(&ui, || {
            Selectable::new(&im_str!("Selectable 1"))
                .size([-f32::MIN, -f32::MIN])
                .selected(true)
                .build(&ui);
        });

    Window::new(&im_str!("Example 2"))
        .size([400.0, 300.0], Condition::Once)
        .build(&ui, || {
            Selectable::new(&im_str!("Selectable 2"))
                .size([300.0, 200.0])
                .selected(true)
                .build(&ui);
        });

    style_token.pop(&ui);

**Comment by ocornut** [comment]
Hello,

Looking at the code for `Selectable()`, it seems like negative values for size are and were never supported in the first place, regardless of the value of `SelectableTextAlign`.

I'm tempted to look into adding that support but I'm then confused by your bug report since you are suggesting that it works when `SelectableTextAlign` is zero. Could you clarify?

**Comment by hiddenhare** [comment]
`Selectable`s with negative dimensions seem to work for me, as long as `SelectableTextAlign` is set to `0.0` in the corresponding axis.

If `SelectableTextAlign` is set to a different value, the `Selectable` fills its container as expected, but its label disappears.

**Comment by ocornut** [comment]
> Selectables with negative dimensions seem to work for me

Well, it doesn't here and it doesn't seem to be supported in the code, and I don't see anything specific in `imgui-rs` so I'm not sure how to move forward there. As, a Selectable with (-FLT_MIN, -FLT_MIN) shows with a very small size (because it adds ItemSpacing*0.5f on each axis).

NB: The reason `Selectable()` don't do it is because the half ItemSpacing extend which would make a Selectable with eg. (-10, 0.0f) size not visibility right-align at the same spot as a Button with the same spot. I'm not sure how to solve that inconsistency yet (been thinking of removing that half ItemSpacing thing from Selectable).

**Comment by hiddenhare** [comment]
Looks like the bug was mine... in Rust, `-f32::MIN` is a huge positive number. I was thrown off by the fact that `imgui_demo.cpp` sometimes assigns a width of `-FLT_MIN` to buttons. The equivalent Rust code is actually `-f32::MIN_POSITIVE`, which does behave as you describe.

I also missed the fact that `Selectable`'s `size` parameter has special handling for width, so that a width of `0.0` (or leaving the size unspecified) will consume all available space.

Sorry for the trouble!

**Comment by ocornut** [comment]
> Looks like the bug was mine... in Rust, -f32::MIN is a huge positive number. I was thrown off by the fact that imgui_demo.cpp sometimes assigns a width of -FLT_MIN to buttons. The equivalent Rust code is actually -f32::MIN_POSITIVE, which does behave as you describe.

I see. FLT_MIN is quite misleading/confusing in libc because INT_MIN is negative whereas FLT_MIN is very-small-positive. So I assume Rust's `f32::MIN == -FLT_MAX` (yay...) and `f32::MIN_POSITIVE == FLT_MIN` hence the mistake.

I've added a note about potentially supporting right-alignment in `Selectable()` later.
