### ISSUE TITLE
Set dimensions of tabs.

### ISSUE THREAD

**Issue by MartinClementson** [ocornut/imgui#3497]
Hello, Thank you for the great work you put into this addon.

Version:  v1.77 WIP
Branch: from latest master of [ofxImGui](https://github.com/jvcleave/ofxImGui)

I am trying to figure out a way to scale up the tabs in my app without sizing up the font.

**My Issue/Question:**
I have two tabs that looks like this 
![image](https://user-images.githubusercontent.com/16565946/94582557-4874ad00-0274-11eb-9c3a-1ae365db9e78.png)

I have mocked a design where the tabs are larger, whereas the font size is the same as it currently is.
![image](https://user-images.githubusercontent.com/16565946/94584182-35fb7300-0276-11eb-9bae-4768dc0c1b98.png)

Is it possible to adjust the width and height somehow?

I tried setting the frame padding

```
ImGui::Begin("Example ");
    if (ImGui::BeginTabBar("##tabbar"), ImGuiTabBarFlags_::ImGuiTabBarFlags_NoTooltip) {
        ImGuiStyle& style = ImGui::GetStyle();
        auto FramePadding = style.FramePadding;
        style.FramePadding = ImVec2(100, 123); //exaggerated test values

        if (ImGui::BeginTabItem(("   Controls   "))) {
            style.FramePadding = FramePadding;
            ImGui::Button("TestButton", ImVec2(200.0f, 50.0f));
            ImGui::EndTabItem();
        }
        style.FramePadding = ImVec2(100, 123);
        if (ImGui::BeginTabItem(("   Settings   "))) {
            style.FramePadding = FramePadding;
            ImGui::Button("TestButton2", ImVec2(200.0f, 50.0f));
            ImGui::EndTabItem();
        }
        style.FramePadding = FramePadding;
        ImGui::EndTabBar();
    }
 
ImGui::End();
```
Which did enlarge the tab. But it came with two issues:
1. The rest of the UI does not take the size into consideration, so the GUI elements that come after are rendered above the tab.
2. The text is not centered. ( _I had a look at the code and tried to figure out if there was something I've missed, I couldn't find much that would help me, I saw that imgui.cpp: RenderTextClippedEx(), the draw_list->AddText adds the text to the position of the pos_min variable. I changed that to draw in the middle of the bounding box, which worked for the tabs, but was no solution because it broke every other widget that renders text_)

Result with some high values:
![image](https://user-images.githubusercontent.com/16565946/94584661-d782c480-0276-11eb-900d-75e5ed548112.png)

The border or the rest of the UI does not seem to play nice with changing the frame padding for this, so it does not seem like a viable solution.

Is there an obvious way to do this that I might have missed? 

Thank you for any help.
Regards
Martin

**Comment by frink** [comment]
I've come up with a few similar issues. I wonder if there actually needs to be a TabPadding rather than the general FramePadding. LOL - Because everyone knows we don't have enough style variables...

@ocornut is there a simpler way?

**Comment by ocornut** [comment]
Hello,

> The rest of the UI does not take the size into consideration, so the GUI elements that come after are rendered above the tab.

I am not sure I understand this statement, and your repro code wasn't tested/is incorrect (missing `EndTabBar()` for a start) so I don't know what to make of it.

One thing you may be missing is that `BeginTabBar()` remember the value of FramePadding and use it for every of it tabs, so try surrounding the call to BeginTabBar with Push/Pop of FramePadding.

Now there are two issues:
- When resizing down, the ellipsis may currently be misplaced. That's something we could fix, but it's also extremely odd to be clipping text when there's so much space available, so we need a policy for deciding how to render that text when there's not enough room.
- We need to use FramePadding to position the `CloseButton()` (when passing a bool* to BeginTabItem).

So using FramePadding is likely not the good approach here.

We could use `SetNextItemWidth()` as also requested for other widgets but it would make that function dangerously inconsistent with the behavior of `PushItemWidth()`/`PopItemWidth()`.

Also since this is a styling thing, if you were to do that you would likely want your Docking Tab Bars (automatically created by docking system) to follow on that style and therefore using either PushStyleVar of SetNextItemWidth wouldn't work.

For now my answer is that we are best avoiding to support infinite number of styling parameters at it is getting out of hands, so I would rather say this is not possible.

**Comment by MartinClementson** [comment]
Hi Omar, Thanks for your reply.

You're right, the example code was totally incomplete, I lost some important code there when removing the unrelated UI code after pasting, sorry about that. I have updated it now and tested so it should work. It will create large tabs and a button where you can see the button still being rendered as if the tab was in the original size (i.e without the FramePadding). 

What I meant with the line you quoted was that the rest of the UI in the tab was not offset by the size of the tabs, which made them being rendered on top. As in this Image 
![image](https://user-images.githubusercontent.com/16565946/94670624-b66bb380-030a-11eb-9fe2-bbe6af29be46.png)

**Comment by MartinClementson** [comment]
I'm happy to say that your tip on push/pop the FramePadding before/after BeginTabBar helped to solve this.

The solution I found is that you need to Push/Pop the FramePadding when calling BeginTabBar, **and** you need to do it before each individual TabItem as well. 

Here is my working code:
```
ImGui::Begin("Example ");
ImGuiStyle& style = ImGui::GetStyle();
    auto FramePadding = style.FramePadding;
    style.FramePadding = ImVec2(100, 123);
    if (ImGui::BeginTabBar("##tabbar"), ImGuiTabBarFlags_::ImGuiTabBarFlags_NoTooltip) {

        if (ImGui::BeginTabItem(("   Controls   "))) {
            style.FramePadding = FramePadding;
            ImGui::Button("TestButton", ImVec2(200.0f, 50.0f));
            ImGui::EndTabItem();
        }
        style.FramePadding = ImVec2(100, 123);
        if (ImGui::BeginTabItem(("   Settings   "))) {
            style.FramePadding = FramePadding;
            ImGui::Button("TestButton2", ImVec2(200.0f, 50.0f));
            ImGui::EndTabItem();
        }
        style.FramePadding = FramePadding;
        ImGui::EndTabBar();
    }
ImGui::End();
```

Result:
![image](https://user-images.githubusercontent.com/16565946/94677663-36971680-0315-11eb-989e-4eff82a6f62f.png)


Thanks for your help, I hope this can be of help to anyone else as well.

**Comment by frink** [comment]
> Also since this is a styling thing, if you were to do that you would likely want your Docking Tab Bars (automatically created by docking system) to follow on that style and therefore using either `PushStyleVar()` of `SetNextItemWidth()` wouldn't work.

@ocornut Can you elaborate on this a bit more? I'm considering doing unorthodox things with Docking Tab Bars and would like to know what I can and can't do with the current iteration.

_BACKSTORY:_ In a Docking Tab Bar for palette type windows I'm considering making a `⛭` Settings Button in place of the usual `X` and also thinking of changing the styles for these tab bars so that the Active Tab follows the Window Background Color etc...

- For the style changes I though `PushStyleVar()` would work... 
- But for the positioning, I'm not sure when or where to move the cursor... 

Based on your above statement it sounds like neither of these will work correctly.
Thus, I'm confused and afraid to dive-in for fear of chasing my tail...

**Comment by ocornut** [comment]
Docking Tabs Bars are not submitted by you, so you don't have flexibility in altering the surrounding code.

**Comment by frink** [comment]
So are we going to end up with a whole slew of StyleVars for them or what's the long-term plan?

**Comment by ocornut** [comment]
> what's the long-term plan?

My current plan is to not solve this problem because it's so minor and we have much more useful priorities ahead.
The long term plan is that styles should be consistent so perhaps more style settings, and less push/pop.

> Now I understand why the Docking System is taking so long to release. Lots of hidden gotchas...

You are seeing a fraction of the tip of the iceberg....
