### ISSUE TITLE
Viewport windows framebuffer do not flush every frame  if io.ConfigViewportsNoDecoration is false

### ISSUE THREAD

**Issue by GdLinkLock** [ocornut/imgui#3498]
**Version/Branch of Dear ImGui:**

Version: v1.79 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp 
Compiler: vs2019
Operating System: win10

**My Issue/Question:**
 If io.ConfigViewportsNoDecoration is true, _when draging window non client area_, viewport windows framebuffer do not flush every frame.

**Screenshots/Video**

![configviewportdecoration-flush-problem](https://user-images.githubusercontent.com/4956809/94639009-ca64e480-030d-11eb-9f55-c6c833c97c68.gif)

**Standalone, minimal, complete and verifiable example:** 
```
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO(); (void)io;
    io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;       // Enable Keyboard Controls
    //io.ConfigFlags |= ImGuiConfigFlags_NavEnableGamepad;      // Enable Gamepad Controls
    io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;           // Enable Docking
    io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;         // Enable Multi-Viewport / Platform Windows
    //io.ConfigViewportsNoAutoMerge = true;
    //io.ConfigViewportsNoTaskBarIcon = true;
    io.ConfigViewportsNoDecoration = false;
```

**Comment by ocornut** [comment]
Hello,

That's not a Dear ImGui issue and it's not a multi-viewports issue either.
In Win32 API by default when you drag or resize using platform decoration (title bar, resize corner) it goes in a modal loop and doesn't give control to your application while doing so, so your application doesn't run at all during this time.

There are solution for this problem, I think some people use a WM_TIMER event to force a refresh while in the modal loop, but it's something to solve on your application side rather than Dear ImGui.
