### ISSUE TITLE
How to detect when an item is in text input mode?

### ISSUE THREAD

**Issue by lfnoise** [ocornut/imgui#3556]
Version: 1.80 WIP (17905)
Branch: master
Back-ends: imgui_impl_metal.mm + imgui_impl_osx.mm
Compiler: clang/Xcode
Operating System: macos 10.15.4

If I am using SliderFloat and I want to have my app ignore the value while it is being text edited, how do I do that? That is, I want to detect when the widget is in text input mode and not pass the value along to my app while it is being edited. I do want to track the value while the slider is being moved by the mouse. I had thought that IsItemFocused() was the way to do this. But IsItemFocused() does not return true when SliderFloat is in text input mode. Nor does it return true when InputText or InputFloat are in edit mode. 

```
static float f = 0.0f;
float copy_of_f = f;
bool changed = ImGui::SliderFloat("float", &copy_of_f, 0.0f, 1.0f);
bool focused = ImGui::IsItemFocused();
bool active = ImGui::IsItemActive();
if (changed && !focused) {
    // I expected this to only happen when not in text input mode.
    f = copy_of_f;
}
printf("f changed %d focused %d active %d %f\n", changed, focused, active, f);
```

**Comment by ocornut** [comment]
You may use `ImGui::IsItemActive() && ImGui::TempInputIsActive(ImGui::GetActiveID())` from imgui_internal.h
However I would strongly advise to consider that:
- Maybe your underlying problem can be better solved by using `ImGuiSliderFlags_AlwaysClamp` (input value will never be out of bounds)
- Maybe your underlying problem can be better solved by `IsItemDeactivated()` or `IsItemDeactivatedAfterEdit()` ?

(linking to #701 for future ref for when we implement it.)

> printf("f changed %d focused %d active %d %f\n", changed, focused, active, f);

`IsItemFocused()` is the keyboard/gamepad navigation focus.
When you want to debug that sorts of things, consider using `ImGui::Text()` calls instead of printf. A stable display is easier to read than a log. Also see Demo>Widgets>Querying Status.

**Comment by lfnoise** [comment]
Thanks for the response.

ImGuiSliderFlags_AlwaysClamp is not a solution for my case. The slider is used as a parameter for a real time audio synthesis process, and jumping to a value which only represents the first two digits typed of a frequency which might be in the range of 20-20000 for example would cause an unwanted glitching of the audio.

I will investigate IsItemDeactivated and IsItemDeactivatedAfterEdit. Thanks also for the debugging tip.

**Comment by ocornut** [comment]
My gut feeling is that applying your value on IsItemDeactivatedAfterEdit() would be adequate but when dragging the slider it would only apply on mouse release.

**Comment by lfnoise** [comment]
No, I want it live while dragging the slider, but not while typing.
Full disclosure: I am writing my own slider widgets for imgui. I found I can add my own state variable and query it and so far it seems to work. 
![sapf_sliders_for_imgui](https://user-images.githubusercontent.com/8428751/97201355-97c4d500-176f-11eb-854e-6defa5cfd76e.gif)

**Comment by ocornut** [comment]
Very nice!
