### ISSUE TITLE
Cleaner separation of ImDrawList from the rest of ImGui

### ISSUE THREAD

**Issue by oviano** [ocornut/imgui#3557]
I am only calling ImDrawList and related functions, essentially using ImGui as a vector graphics library, without a ImGui context etc, but I still end up with these link errors if I don't include imgui.cpp:

ImFormatString
ImAlphaBlendColors
ImFileLoadToMemory
ImTextCharFromUtf8

ImGui::GetColorU32
ImGui::MemFree()
ImGui::GetStyle()
ImGui::MemAlloc()

Perhaps we can have an imgui_util.cpp with any shared functions like some of the above that are needed by both imgui_draw.cpp and elsewhere. The only one above that might not fit into that would be ImGui::GetStyle() which is needed by StyleColorsDark(), StyleColorsClassic() StyleColorsLight(), defined in imgui_draw.cpp, but I would tentatively suggest that these latter three belong in imgui.cpp anyway, as what business is it of a vector graphics library to define appearances?

At the moment, it feels wrong to be bringing the whole 10k+ line behemoth that is imgui.cpp for a handful of functions needed to support ImDrawList.

Just a few thoughts after messing about for the first time with ImDrawList these past few days.

**Comment by ocornut** [comment]
﻿The linker will strip out unused functions so compiling with imgui.cpp etc shouldn’t be an issue.

Otherwise, you can essentially asking for me to be putting extra work at caring/maintaining for an extremely unusual case so from maintainer pov it’s not worth it, even less so that linker stripping can do that job.

**Comment by ocornut** [comment]
I must clarify that in essence I wholly agree with the idea of that separation, but in practice it is too much work and adding up various constraints to maintain it.

**Comment by lfnoise** [comment]
As a means of avoiding some more difficult coding problems on my plate, I took a first stab at this and was able to separate them. 

At the lowest level, there is a layering order problem because ```ImGui::MemAlloc/MemFree``` modify the ImGuiContext metrics variable ```ctx->IO.MetricsActiveAllocations```. Not sure how to address this. For now, I commented out the metrics inc/dec code. (!)

ImGui::RenderColorRectWithAlphaCheckerboard was evacuated from imgui_draw.cpp to imgui.cpp because of ```// FIXME: uses ImGui::GetColorU32```

Added imgui_draw.h include which has all the draw interfaces.

Added imgui_util.h, imgui_util_internal.h, imgui_util.cpp to contain common utilities that were in imgui.h or imgui_internal.h but are needed by draw.

I think it makes more sense to have a separate #include to define the ImVec math ops rather than setting a #define before inclusion. So, I created imgui_math_ops.h.

In imgui_internal.h there is this:
```
#ifndef IMGUI_VERSION
#error Must include imgui.h before imgui_internal.h
#endif
```
Why not just do the ```#include "imgui.h"``` here instead? That makes this error impossible.

So now, imgui_draw.cpp does not depend on imgui_internal.h or imgui.h.
imgui_draw.h only depends on imgui_util.h
imgui_util.h only contains a few things needed by both imgui.h and imgui_draw.h
imgui_util_internal.h contains those things needed by both draw.cpp and imgui.cpp


Include file dependency chains:
```
imgui_internal.h -> imgui_util_internal.h -> imgui_draw.h -> imgui_util.h
imgui_internal.h -> imgui.h -> imgui_util.h

imgui_draw.cpp -> imgui_util_internal.h -> ... as above
imgui.cpp -> imgui_internal.h -> ... as above
```

**Comment by oviano** [comment]
Nice to know it can be done, and I would have thought that after the initial split then it shouldn’t be too hard to maintain if the build system always builds standalone ImDraw too?

Up to @ocornut I guess and I’m assuming from his comments above it’s a non starter (and understandable as I guess it’s not the priority).

**Comment by ocornut** [comment]
I guess my comments was ambiguous. Of course it is possible and trivial to separate the code. But it’s not a satisfactory result to add 3-4 new files. Moreover it isn’t necessary a desirable outcome to promote ImDrawList as a possible standalone feature, it’ll only widen the user base and therefore the cost of maintaining this. I think you are underestimating the number of problems that every layer of abstraction or layer of separation brings, with each of them people will come up with infinite ways to make new requests and we need to scope that somehow because its consuming attention which is dear imgui most valuable asset.

**Comment by lfnoise** [comment]
I could either put it up as a fork or as PR. But there's no point in a PR if it's a going nowhere. It was useful for me to understand where the layering is and how the drawing works. I'm even tempted in going as far as separating out the event handling and host windowing system from the imgui part. This would provide something like glfw + drawing but with all imgui's backends.

**Comment by ocornut** [comment]
If you wanted to fork to create a ImDrawList-only thing it may be simpler to write a script to extract all ImDrawList block out of a specific commit + custom add/tweak some of the glue required.

**Comment by lfnoise** [comment]
After having done it, I think any such script would be very fragile.

**Comment by lfnoise** [comment]
So, I've taken this to its logical conclusion. I separated draw, io and as much of the font api as could be separated out. It was a good learning experience for me, but I think that now I agree with ocornut: better just to leave it as is and let the linker strip it out. There just isn't much to be gained by doing it.
