### ISSUE TITLE
multiviewport  layout issue

### ISSUE THREAD

**Issue by continue567** [ocornut/imgui#3564]
hi, sorry to bother you~
Could you know how to locate the problem when an ui widget in window A  appear in window B like this
![image](https://user-images.githubusercontent.com/20896273/97525674-5425d180-19e2-11eb-9e99-055bd625b72d.png)

![image](https://user-images.githubusercontent.com/20896273/97525622-32c4e580-19e2-11eb-90b4-c5546f81bf69.png)

**Comment by ocornut** [comment]
Hello,

(1) You did not follow requested guidelines and issue template.
- Please make sure you have read the guidelines.
**- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.**

(2) I don't think your problem has anything to do with Multi-Viewports.
For information, this is Multi-viewports: (see [Glossary](https://github.com/ocornut/imgui/wiki/Glossary))
![MultiViewports](https://user-images.githubusercontent.com/8225057/97542423-fe8ffb80-19c6-11eb-9bf5-e26d86364e55.png)

Without more information we cannot help you. Please follow (1) carefully, provide information about back-end, repro code and we can reopen this and try to help. Otherwise please consider asking on Discord.
