### ISSUE TITLE
Font atlas not built error

### ISSUE THREAD

**Issue by yanickrochon** [ocornut/imgui#3630]
Executing `ImGui_ImplGlfw_NewFrame();` I get the following run-time error :

```
 Assertion `io.Fonts->IsBuilt() && "Font atlas not built! It is generally built by the renderer backend. Missing call to renderer _NewFrame() function? e.g. ImGui_ImplOpenGL3_NewFrame()."' failed.
```

What is this error and how can it be resolved?

**Comment by ocornut** [comment]
The text you pasted answers your question.

I am closing this as you didn't make the effort of reading guidelines or following issue template.

**Comment by yanickrochon** [comment]
The text I pasted answers nothing. Thank you for helping someone in need.

**Comment by yanickrochon** [comment]
![image](https://user-images.githubusercontent.com/78461/100634677-99992f80-32fd-11eb-8cb6-d66a70c2fe11.png)

**Comment by ocornut** [comment]
Are you telling me that the words "Glfw" and "OpenGL3" read the same to you?

**Comment by yanickrochon** [comment]
The error states `e.g.` (i.e. "for example")

**Comment by ocornut** [comment]
It also says "renderer backend" and Glfw is a platform backend.

**Comment by Pacheco95** [comment]
@yanickrochon It's late but you need to do this:

```c++
ImGuiIO &io = ImGui::GetIO();
io.Fonts->AddFontDefault();
io.Fonts->Build();
```

**Comment by monarchwadia** [comment]
Many thanks to the dev team for the great open source project that is imgui

@Pacheco95 thank you! This was not in the documentation, would have never tried this. I'm using SDL2 and was calling `ImGui_ImplSDL2_NewFrame()` to no avail.

**Comment by ocornut** [comment]
> @Pacheco95 thank you! This was not in the documentation, at least not the one I was reading. I would have never tried this. I'm using SDL2 and was calling `ImGui_ImplSDL2_NewFrame()` to no avail.

Calling ImGui_ImplSDL2_NewFrame() is the correct solution. You should not need to call AddFontDefault()/Build() in a normal situation.

I believe we may be missing some information related to the issue, what’s your full program structure like?

Similarly it’s possible than original poster had another issue but since they never attempted to provide the useful information needed to diagnose their problems i could only guess :(

**Comment by monarchwadia** [comment]
@ocornut thakns for that tip! You are correct, I was able to fix my issue thanks to your comment. Thank you!

I am using SDLRenderer2 as the backend.

Turns out that I was calling `ImGui_ImplSDL2_NewFrame();` but I was not calling `ImGui_ImplSDLRenderer2_NewFrame();`

Here are examples from my code. The first one is broken, the rest are working.

# Example 1: Broken

```cpp
// ....

IMGUI_CHECKVERSION();
ImGui::CreateContext();
ImGui_ImplSDL2_InitForSDLRenderer(window, renderer);
ImGui_ImplSDLRenderer2_Init(renderer);
// ImGuiIO &io = ImGui::GetIO();
// io.Fonts->AddFontDefault();
// io.Fonts->Build();

//...

// ImGui_ImplSDLRenderer2_NewFrame();
ImGui_ImplSDL2_NewFrame();
ImGui::NewFrame();

// void ImGui::ErrorCheckNewFrameSanityChecks(): Assertion `g.IO.Fonts->IsBuilt() && "Font Atlas not built! Make sure you called ImGui_ImplXXXX_NewFrame() function for renderer backend, which should call io.Fonts->GetTexDataAsRGBA32() / GetTexDataAsAlpha8()"' failed.
```

# Example 2: Works


```cpp
// ....

IMGUI_CHECKVERSION();
ImGui::CreateContext();
ImGui_ImplSDL2_InitForSDLRenderer(window, renderer);
ImGui_ImplSDLRenderer2_Init(renderer);
ImGuiIO &io = ImGui::GetIO();
io.Fonts->AddFontDefault();
io.Fonts->Build();

//...

// ImGui_ImplSDLRenderer2_NewFrame();
ImGui_ImplSDL2_NewFrame();
ImGui::NewFrame();
```

# Example 3: Also works

```cpp
// ....

IMGUI_CHECKVERSION();
ImGui::CreateContext();
ImGui_ImplSDL2_InitForSDLRenderer(window, renderer);
ImGui_ImplSDLRenderer2_Init(renderer);
// ImGuiIO &io = ImGui::GetIO();
// io.Fonts->AddFontDefault();
// io.Fonts->Build();

//...

ImGui_ImplSDLRenderer2_NewFrame();
ImGui_ImplSDL2_NewFrame();
ImGui::NewFrame();
```

**Comment by ocornut** [comment]
Example 2 is incorrect it’s only a lucky accident that it appears to work.
