### ISSUE TITLE
Suggestion to update it like a .lib

### ISSUE THREAD

**Issue by HideakiAtsuyo** [ocornut/imgui#3667]
You can update it like a .lib it will be easier to use.. No ?

**Comment by IronicallySerious** [comment]
Dear ImGui has a pretty no nonsense integration process. Having a .lib is easier for use but then you have to take measures so that all the different compilers can use it to link against it, maintaining the binaries for every different platform you'd want to support and much more things that I am forgetting. 

It is an extra commitment and its worth is lowered by how easy it is to compile Dear ImGui

**Comment by ocornut** [comment]
Hello,

The question of "being like a .lib" or not does not make sense in the context of how we ship dear imgui.
Making a .lib vs integrating source files in a project is a question handled by your build system.

We are not depending on any build system. 
We are not shipping binaries because the objective is you compile from sources and then you have zero issues of compiler or runtime compatibilities.

Feel free to create a library project in your build system and create a .lib out of the dear imgui source files. Nothing prevents you from doing that.

At the core of the topic, the question is probably that you are not familiar with your build system.
But if we "provided a .lib" it would essentially mean we provide build files for a given build system and if it's not the exact same as the one you are already using you are back at square one. It is just more sane, but less standard, to not provide it and let the user use their build system already in place.
