### ISSUE TITLE
Cannot create window in Remote Desktop, works fine on home PC

### ISSUE THREAD

**Issue by UncleDad** [ocornut/imgui#3709]
Digging in a bit, this pixel format creation fails, and fails the rest of the process. 
![image](https://user-images.githubusercontent.com/37358652/104228493-cc0b7180-53ff-11eb-91f5-631b55a55d5e.png)

Like the title says, there is no issue whatsoever if I run the same code on my home PC, its just when running over remote desktop that window creation fails.

**Comment by thedmd** [comment]
Bummer. Creating OpenGL context is not supported via Remote Desktop. There is nothing that ImGui can do with that.

As a workaround you may:
- switch to Direct3D 11
- drop Mesa3D software OpenGL32.dll next to your app until working on Remote Desktop
- launch application using VNC (annoying, because close RD, launch VPN, launch app, close VPN, launch RD)

**Comment by ocornut** [comment]
Closing as answered. 
Not sure there's something we can do on our side, if you think there is let us know.
