### ISSUE TITLE
CollapsingHeader is not visible when not opened

### ISSUE THREAD

**Issue by attilaz** [ocornut/imgui#3715]
**Version/Branch of Dear ImGui:**

Version: v1.80
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp
Compiler: MSVC 2017
Operating System: Windows 10

**My Issue/Question:**

bool ImGui::CollapsingHeader(const char* label, bool* p_open, ImGuiTreeNodeFlags flags)
When I am using this version of CollapsingHeader with false o_open parameter the CollapsingHeader is not visible.

In older version this was an open parameter. In this version it seems like it means visible?

**Screenshots/Video**

![imgui_collapsing_header](https://user-images.githubusercontent.com/4198194/104424360-9097b100-557f-11eb-8d49-11a07d98b0a1.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
//   if (ImGui::CollapsingHeader("Help"))
//   I have replaced this line in imgui_demo.cpp with the lines below and the "Help" CollapsingHeader disappeared. 
     bool open = false;
     if (ImGui::CollapsingHeader("Help", &open))


```

**Comment by ocornut** [comment]
> In older version this was an open parameter. In this version it seems like it means visible?

This code never changed since it was added.

There's something misleading using the term `p_open` (was named this way to match with Begin()'s `p_open`), I think it should be renamed `p_visible`.

When you pass a bool* to this variant of `CollapsingHeader()` and its value is not zero, it shows a Close button on it:

![image](https://user-images.githubusercontent.com/8225057/104429580-0f8fe800-5586-11eb-9522-57adf6ca2056.png)

When it is zero the `CollapsingHeader()` doesn't display, but that behavior is not technically well defined and not exactly matching how `Begin()` behave. The point being that if you own visibility state and that visibility is false you shouldn't be calling `CollapsingHeader()` anyway.

----

If you want to alter the OPEN state (not the VISIBILITY state) you can use `SetNextItemOpen()` before `CollapsingHeader()`.

I'm going to rename this parameter `p_open` maybe to `p_visible` and tweak the comments.
