### ISSUE TITLE
Help with keyboard handling and catching some keys

### ISSUE THREAD

**Issue by friol** [ocornut/imgui#3724]
**Version/Branch of Dear ImGui:**

Version: 1.79
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: iimgui_impl_glfw.cpp
Compiler: Visual C++ 2019
Operating System: Windows 10

**My Issue/Question:**

Hello,
I have a couple of questions; I've searched the documentation/examples, but couldn't find the answer.

**1)** how do you handle pressing some "special" keys like F1 (function keys) or "+" (plus key)? They seem to be missing from io.KeyMap[ImGuiKey_*] 

**2)** which is the proper way of handling keyboard on windows? Currently I'm polling the keyboard with ImGui::IsKeyPressed, but doesn't seem the best way (some keys are retriggered too often).

Thanks

**Comment by thedmd** [comment]
Ad. 1) Please see [extra-keys](https://github.com/ocornut/imgui/pull/2625) PR, where I added support for all keys present on US keyboard layout.

Ad. 2) At the moment pooling is the only way. Solution to this problem is in the works. In the mean time what you can do is to record input events and on each frame feed ImGuiIO as much of them as possible without hitting a conflict (down/up).

**Comment by ocornut** [comment]
(1) is now handled by #4921
(2) duplicate/moving to #456 (progress soon, see https://github.com/ocornut/imgui/issues/2637#issuecomment-1083387898)
