### ISSUE TITLE
Color Edit Tips

### ISSUE THREAD

**Issue by Ghost-yc** [ocornut/imgui#373]
Alpha value of the color space prompt edit the display seems to always be 1
![color](https://cloud.githubusercontent.com/assets/8528210/10480929/da4993e0-729f-11e5-9561-3113d10ba172.png)

**Comment by ocornut** [comment]
Thanks. I'm setting alpha to 1.0 when calling ColorButton() so that the color gets displayed here without alpha. I'd have to decide if we want to make ColorButton() ignore alpha (but display the right value) or not, or perhaps via an extra flag. There are case where you'd want the alpha of the color to be used for the square, some not.

I may defer fixing that until I can have a look at color pickers in general.

If you need a quick fix search for this:
```
    const ImVec4 col_display(col[0], col[1], col[2], 1.0f);
    if (ImGui::ColorButton(col_display))
```

**Comment by Ghost-yc** [comment]
Ok Thanks
