### ISSUE TITLE
Mouse capture issue while using the "DockSpaceOverViewport()" function

### ISSUE THREAD

**Issue by amir-120** [ocornut/imgui#3733]
Using the docking branch I tried making a dock space over the view port using the "ImGuiDockNodeFlags_PassthruCentralNode" flag but I'm having an issue, I block mouse inputs from going to the application when ImGui's "WantCaptureMouse" is set to true so the inputs won't register to both the program and the ImGui window at the same time now the problem I have is that when the mouse is right on the edge of the screen (no matter up, down, right or left edge) WantCaptureMouse gets set to "true" even tho there's no ImGui window rendering on those areas.
Here's an example:

`
{
        ImGui::DockSpaceOverViewport(ImGui::GetMainViewport(), ImGuiDockNodeFlags_PassthruCentralNode);
        ImGui::Begin("Test");
        ImGui::Text("Want M input: %d", ImGui::GetIO().WantCaptureMouse);
        ImGui::End();
}
`

![Example](https://user-images.githubusercontent.com/18630540/105075841-899d0100-5a9f-11eb-90bf-bfdeb92bb12b.png)

**Comment by ocornut** [comment]
Hello @amir-120,
Thanks for the report.
This is now fixed by 22d9a61

There is a padding added to the sides of that hole to allow easily grabbing separating borders, I have no remove this padding when there's nothing on the other side. This is a debug view of the mouse-hovering hole now created:
![image](https://user-images.githubusercontent.com/8225057/106612364-53fd1b00-6569-11eb-9377-bc6eabc21983.png)
