### ISSUE TITLE
Loosing tooltip when using ImGuiDragDropFlags_SourceExtern

### ISSUE THREAD

**Issue by dgregorius** [ocornut/imgui#3741]
**Version/Branch of Dear ImGui:**

Version: 1.79
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp 
Compiler: VS 2019
Operating System: Windows 10

**My Issue/Question:**

I am loosing the tooltip when using ImGuiDragDropFlags_SourceExtern. Instead of the provided tooltip I only get the mystical "...". Besides this everything works like expected.
```
if ( ImGui::IsItemClicked( ) )
		{
		if ( ImGui::BeginDragDropSource( ImGuiDragDropFlags_SourceExtern ) )
			{
			ImGui::SetDragDropPayload( Z_TREE_NODE_PAYLOAD, &Transform, sizeof( ZTransform* ) );
			ImGui::Text( "Transform" );
			ImGui::EndDragDropSource();
			}
		}
```

**Comment by ocornut** [comment]
Hello,

The tooltip needs to be submitted, here it isn't since you only submit it on the click.
From there I think the issue is similar as described in second part of #1725 so I'll move the conversation there.

If you look at this specific comment: https://github.com/ocornut/imgui/issues/1725#issuecomment-408634674
- Item (1) was implemented (payload is kept even if source stops being submitted).
- Item (2) wasn't implemented but should be possible to do at the user level. Essentially we should provide an idiomatic way to encourage people to submit description tooltip not at the source but somewhere in the main-loop. User code can can peak at the payload and generate the tooltip for it. This would fix the more general problem described by #1725.
