### ISSUE TITLE
ImBezierClosestPointCasteljau not keeped

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#3746]
After cimgui generation with 1.80 I was able to compile imnodes skipping `IMGUI_DISABLE_OBSOLETE_FUNCTIONS` for `addBezierCurve` but not ImNodes with `ImBezierClosestPointCasteljau` which definition was dropped even without  `IMGUI_DISABLE_OBSOLETE_FUNCTIONS`.

**Comment by aiekick** [comment]
we have added quadratic version and renamed the old one with Cubic.

so you can found it under name ImBezierCubicClosestPointCasteljau

**Comment by sonoro1234** [comment]
> we have added quadratic version and renamed the old one with Cubic.
> 
> so you can found it under name ImBezierCubicClosestPointCasteljau

I know that. 
The issue is not being able to compile ImNodes (without modification and without IMGUI_DISABLE_OBSOLETE_FUNCTIONS ) because ImBezierClosestPointCasteljau definition does not exist even if IMGUI_DISABLE_OBSOLETE_FUNCTIONS is undefined

**Comment by aiekick** [comment]
ah ok sorry, not understood that haha :)

**Comment by ocornut** [comment]
We don't guarantee forward/backward compatibility for `imgui_internal.h` functions, which is why it's called internal. So IHMO this is a non-issue

We occasionally do it for functions/symbols that we know are very frequently used by custom widgets, but generally trying to avoid it. What we should improve, and been working toward that, is to increase IMGUI_VERSION_NUM more frequently to facilitate that code sharing.

I think your fix: https://github.com/rokups/ImNodes/issues/25 is good and should be adopted by ImNodes.
