### ISSUE TITLE
Why ImGui Demo application loads CPU by 8%? How to optimize?

### ISSUE THREAD

**Issue by Vine1** [ocornut/imgui#3749]
Hi! I have compiled the ImGui demo application with maximum optimization in Release mode.
OS: Linux
Compiler: GCC
CPU: Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
Implementation: GLFW  OpenGL3 (GLEW loader).

And it loads my CPU by 6-8 percent.
I assume that this is due to the frequent updating of frames, isn't it?
If it is, then maybe there is a way to optimize it?
For example, update the frame only when something changed (window moved, animation updated, button clicked, etc.)?
Optimization like that used in Chrome browser, at least.
Is it possible to optimize this saving graphics quality (without removing the rounding, anti-aliasing, etc.)?

EDIT:
I checked CPU loading without ImGui rendering, only with an empty blue OpenGL screen. It loads CPU by 2%, but with ImGui 5-6%.

**Comment by IronicallySerious** [comment]
You can probably implement this in your application. Most backends have some way of detecting events. So you can run your loop iterations only as long as you are receiving events i.e. the event list is not empty.

However, there is a reason why apps like games don't do this because they may have the rendering depend on the current time. E.g. animations like particles, characters, and even UI animations (which are also not specific to just games).

**Comment by rationalcoder** [comment]
I currently handle this in my application by updating imgui on events and when animations are running. Really, to avoid a little complexity, I set a minimum frame-rate of 24 fps, and update the UI on every input event. That way, UI responsiveness stays high during things like mouse movements. Note that you don't have to render on every event. You can cap event updating FPS at like 144, render at a max of 60 FPS, and not render at all unless there are input events or animations that need to be processed. It's all up to your application.

**Comment by ocornut** [comment]
#2749 is a possible answer for this problem. We will adopt it in the future.

**Comment by Folling** [comment]
> For example, update the frame only when something changed (window moved, animation updated, button clicked, etc.)?
> Optimization like that used in Chrome browser, at least.
This inherently goes against the idea of the IMGUI paradigm and you're probably better off just using a retained GUI library (qt, wxwidgets, gtk, whatever) if you care about that

**Comment by ocornut** [comment]
> This inherently goes against the idea of the IMGUI paradigm and you're probably better off just using a retained GUI library (qt, wxwidgets, gtk, whatever) if you care about that

I disagree with that statement.
The proposition is to enforce updates or raise update frequently on user inputs, this is a perfectly valid proposition. User may also requests updates on known data change to compensate for a default slower refresh rate.

**Comment by Folling** [comment]
The optimisation they were playing at works by only partially updating the frame and only doing so when necessary, which is only possible if you retain previous frames, which is the antithesis of the immediate mode paradigm as far as I'm concerned as you do not retain any information in that case.
I do agree that simply updating less frequently is not orthogonal to the IMGUI paradigm however.

**Comment by rationalcoder** [comment]
@Folling From what the op mentions, it doesn't seem like they are talking about actually retaining frame-buffer information to do things like dirty-rects, which still isn't done by any modern RMGUI that I'm aware of. They seem to just be talking about having event-based instead of frame-based applications.

That being said, Casey Muratori (The IMGUI popularizer) for example, often says that while IMGUI generally allows you to retain less state, that's an implementation detail. According to him, IMGUI is simply about API design. A good example of caching widget state while still being immediate-mode would be... Dear ImGui, since it has to know something about widgets that exist between frames to report events like buttons being released. This is more clear in the case of an immediate-mode rendering API. New GPU drivers are free to come in and cache all they want to speed up rendering, and none of that changes the fact that you are using an immediate-mode API when you call something like `glVertex3f()`, for example.

**Comment by Folling** [comment]
I did not argue against retaining information within an IMGUI based system. I argued against retaining the framebuffer in an IMGUI based system. But omar and I have had a lengthy discussion about this particular subject and have come to the conclusion that "immediate mode" is simply a misleading term in a lot of cases. Omar's (and nowadays my) point of view was that the IMGUI paradigm has a lot more to do with the proximity of state and logic as well as the overall API design. I argued that "CohesiveGUI" or "CoupledGUI" might make more sense as a terminology, since nothing about IMGUI actually needs to be immediate. You can defer rendering, defer state evaluation, retain as much or as little information as you want, etc.

That being said I do partially retract the sentiment in my previous messages, even though I still believe it isn't very useful to add a retained frame buffer in an IMGUI system, although I now see that it doesn't prohibit it from technically still being an IMGUI system.
