### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by NullifiedMistake** [ocornut/imgui#3769]
![image](https://user-images.githubusercontent.com/45947295/106338339-d64cbd00-6293-11eb-98c2-1d581908ece2.png)

How to fix this

Im using dear imgui, OpenGL 3 (gl3w)

**Comment by PathogenDavid** [comment]
Next time you submit an issue you should read the issue template, which requests you do not open issues for linker errors and instead seek help on [the ImGui Discord](http://discord.dearimgui.org/).

Those errors are not caused by Dear ImGui, they are caused by GLFW. You can find guidance setting up your project to build with GLFW here: https://www.glfw.org/docs/latest/build.html

**Comment by NullifiedMistake** [comment]
> Next time you submit an issue you should read the issue template, which requests you do not open issues for linker errors and instead seek help on [the ImGui Discord](http://discord.dearimgui.org/).
> 
> Those errors are not caused by Dear ImGui, they are caused by GLFW. You can find guidance setting up your project to build with GLFW here: https://www.glfw.org/docs/latest/build.html

ok stfu

**Comment by ocornut** [comment]
Blocked and also sorry but #1586 
Hopefully the answer may be of use to others.
