### ISSUE TITLE
Retrieving opengl texture of each Single-Window Viewport help

### ISSUE THREAD

**Issue by YabbaTroll** [ocornut/imgui#3771]
**Version/Branch of Dear ImGui:**

Version: 1.80
Branch: (docking)

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp 
Compiler: VS19
Operating System: Windows 10

**My Issue/Question:**

I'm currently writing an application that shows ImGui windows in two ways: 

1. [The main page, that is shown both on the desktop and as a SteamVR Dashboard Overlay ](https://user-images.githubusercontent.com/14651640/106367442-b60f1380-6310-11eb-83fa-6b2dd590aae3.png)
2. [A variable amount of "panels" that shouldn't be visible on the desktop, but be visible in SteamVR Overlays](https://user-images.githubusercontent.com/14651640/106367443-b8716d80-6310-11eb-859f-4de2251d7cf4.png) 

SteamVR overlays display opengl textures using the textures GLuint, which is why I’m trying to retrieve the GLuint used in each Single-Window Viewport in my application.

While using the master branch, I managed to show the 800x800 main page + a single  400x800 panel by rendering them both side by side on the same 1200x800 framebuffer, using glBlitFramebuffer to split the first 2/3s of the framebuffer into what's used for the desktop window and the steamvr dashboard overlay, and the last ⅓ as a different steamvr overlay. 

This hacky solution works when only one “panel” is needed but I need to be able to dynamically create multiple different “panels” of different shapes and sizes. I switched to the docking / multiple viewport branch in order to do this better. 

For more context, I’m making a program that allows users to use VR controllers to emulate input peripherals such as flight sticks, throttle quadrants, steering wheels, etc. 

The [main window](https://user-images.githubusercontent.com/14651640/106367442-b60f1380-6310-11eb-83fa-6b2dd590aae3.png) is supposed to support the creation / manipulation / destruction of these virtual devices and their properties. It should be accessible from both inside and outside of VR. 

[Panels](https://user-images.githubusercontent.com/14651640/106367443-b8716d80-6310-11eb-859f-4de2251d7cf4.png) are going to be added by the user similar to the virtual devices above. They are made from a very simple Dear ImGui GUI shown on a VR overlay, and are used to simulate a sort of button panel for use with any sort of flight/racing/whatever sim. (screenshot shown is used for WarThunder)

Is there some sort of method I can call between each ImGui::Begin() and ImGui::End() to get whatever the GLuint that the Single-Window Viewport is associated with? If not how would I go about editing imgui_impl_opengl3/glfw to make imgui render into a fbo instead of a glfwWindow (if that's even possible) and be able to retrieve the needed information from that framebuffer.

Apologies if this is hard to understand, I can write much worse than I can code and my code isn't even that good. 

**Screenshots/Video**

![2021-01-30 15_22_41-VR View](https://user-images.githubusercontent.com/14651640/106367442-b60f1380-6310-11eb-83fa-6b2dd590aae3.png)

![2021-01-30 15_25_52-VR View](https://user-images.githubusercontent.com/14651640/106367443-b8716d80-6310-11eb-859f-4de2251d7cf4.png)

**Comment by YabbaTroll** [comment]
I'm looking through imgui.h some more and I'm looking at ImDrawCallback and the snippet that says  

// NB: You most likely do NOT need to use draw callbacks just to create your own widget or customized UI rendering,
// you can poke into the draw list for that!

This seems like a cleaner way of doing what I want if I understand what its saying correctly, how do I go about doing this? what does "poking" into the draw list mean in this context?

**Comment by ocornut** [comment]
Hello,

I am afraid your question don't make sense to me.

> Is there some sort of method I can call between each ImGui::Begin() and ImGui::End() to get whatever the GLuint that the Single-Window Viewport is associated with? 

There's no GLuint/texture associated to a viewport.

> If not how would I go about editing imgui_impl_opengl3/glfw to make imgui render into a fbo instead of a glfwWindow (if that's even possible) and be able to retrieve the needed information from that framebuffer.

You can call the renderer `XXX_RenderDrawData` function already it'll render to the bound framebuffer or FBO. The renderer has nothing to do with the glfwWindow.

1) One possible answer to your problem is you should create 2 dear imgui context, have each of them be independent and then render each of them in the appropriate target. In this scheme, you would have two identical "main window" on each side (since the data reflected in the window is supposedly shared they'll be mostly synced anyway).

2) Another answer is to use the `const char* _OwnerName` field of ImDrawList to perform some filtering of the ImDrawList to render( some of it omitted on one target and not on the other target). I think that's close to what you asked but I cannot see it working properly as e.g. pointer inputs will not match what's displayed if one of the window is not drawn.

**Comment by YabbaTroll** [comment]
> There's no GLuint/texture associated to a viewport.

>You can call the renderer XXX_RenderDrawData function already it'll render to the bound framebuffer or FBO. The renderer has nothing to do with the glfwWindow.

Ah, It seems I misunderstood how dear imgui handled multiple viewports. Multiple contexts seems like it might actually be the most "correct" way to do what I want.  Thanks for the help.

**Comment by ocornut** [comment]
It wasn't clear in your original description if you were actually using dear imgui's Multi-viewports mode (most people use the word "viewport" to signify variety of things). If you did that, then I suppose your "main" window was ALREADY being submitted twice from dear imgui pov ? Each ImGuiViewport has its own GetDrawData() output and you can redirect them on multiple screens. However my assumption is that in its current iteration, multi-viewports is "too flexible" for what you want to do since you'd want to isolate VR windows from Desktop windows?

**Comment by YabbaTroll** [comment]
When I wrote the issue I was using dear Imgui's multi-viewport mode but I temporarily removed my framebuffer copying code as it didn't seem to be compatible with how GLFW windows were being automatically made. (I should have mentioned that instead of just copying and pasting from the glossary, my bad) 

Multi-viewports might be too flexible for my current needs right now, I think I'll hold off on using them until I can spend more time to better understand how they function.
