### ISSUE TITLE
ImGui::IsWindowFocused() traversing docking boundaries

### ISSUE THREAD

**Issue by dgregorius** [ocornut/imgui#3777]
**Version/Branch of Dear ImGui:**

Version: 1.80
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp 
Compiler: VS 2019
Operating System: Windows 10

**My Issue/Question:**

In my application I have a main dockspace which defines the basic window layout of my application and one of the windows in this  main dockspace uses another nested dockspace to split itself. If I call ImGui::IsWindowFocused() on the window which hosts the nested dockspace it always returns false. This seems to be indented as the code of ImGui::IsWindowFocused() is not descending into the dockspace. How can I properly query if any of the dockspace windows has focus? Ideally ImGui::IsWindowFocused() should descend here into the dockspace I think - in particular if the ImGuiFocusedFlags_ChildWindows is passed in.

Thanks,
-Dirk

**Comment by ocornut** [comment]
Hello Dirk,

I would need two things:
- An explanation about why you need to query this. We almost always get better answers and changes when armed with the context and being sure we are not solving a [XY Problem](http://xyproblem.info/).
- A pastable minimum repro because I am going to need one to look into that anyway. This would also clarify if both times you used the term Dockspace you are actually referring to explicit Dockspace() calls and not dock node created via an interactive dock split operation (nested explicit Dockspace seems unusual to me). Also the behavior of `IsWindowFocused()` would differ depending on whether you also used `ImGuiFocusedFlags_RootWindow`.

Docked window don't behave as child from the POV of the user, as this would create too many undesirable side-effects. This is why e.g. `ImGuiFocusedFlags_RootWindow` or many concept using "RootWindow" stops at the `Begin()` boundary (internally we have `RootWindow` and `RootWindowDockStop` the later being closer to what the user generally perceive via public API).

Similarly in the other direction if you wanted to query `ImGuiFocusedFlags_ChildWindows` for it to be symmetrical we need it to not get into Docked window from the parent. 

Most certainly we could add an additional flag to traverse docking boundaries in both directions, but it would be helpful to first get more context about the use.

**Comment by dgregorius** [comment]
Makes sense. 

I am at the point now where my editor will operate on several assets simultaneously. E.g. a scene, an animgraph and a ragdoll. Each of these assets has an associated undo system. I need to keep track of the active asset so I can trigger the correct undo operation if requested by the user. Basically I think it would be weird if the scene window is in the front (has focus) and I would perform an undo on a different asset which is eventually hidden. So the idea was to keep track of what the user is doing by observing the currently active top window.

**Comment by dgregorius** [comment]
I just checked this in Unity and it seems they are just maintaining a single undo stack for all assets. This will make the original problem much easier I think. So in terms of XY I might be addressing my original problem incorrectly. Still I think it would be useful to be able to track the user focus consistently.

On a side note when I was debugging this (drawing a red rect around the window with focus) I got strange behavior when pressing menu items. It seemed as if I one of my top windows received focus for every second menu entry I clicked.

**Comment by PathogenDavid** [comment]
> I just checked this in Unity and it seems they are just maintaining a single undo stack for all assets.

(Kind of off topic, but for what it's worth I thought your idea of how to do it sounded interesting and you had me curious if it'd feel intuitive to use.)

**Comment by ocornut** [comment]
> So the idea was to keep track of what the user is doing by observing the currently active top window.
> I just checked this in Unity and it seems they are just maintaining a single undo stack for all assets.

I think those ideas are combinable and should be combined.
You want to maintain a most-recently-used ordered list of editors/assets.
And you can maintain it without doing focus tests that are crossing the docking boundaries.
If some or all of your window are associated to a given editor/asset, when that window (or its children) is focused you can move that editor/asset at the top of the MRU list.
I don't believe doing focus test crossing the docking boundaries is going to be very meaningfully useful (tho we certainly can add that additional flag if there's a need).

**Comment by dgregorius** [comment]
MRU asset list is fine, but there might be a difference between the last edited asset and what the user is currently looking at. The latter is a change in the UI. Either way, I think I cannot produce an answer for this right now and will start with the simplest working solution and see how it works in practice. 

Thanks for the input!
