### ISSUE TITLE
How to implement animation on item release? (LastActiveIdTimer for item active)

### ISSUE THREAD

**Issue by mooko-dev** [ocornut/imgui#3785]
Hello!
I want to implement an animation that will start when an item is released. I know how to do that for item activation, I can use LastActiveIdTimer, but is there a solution for an item release?
Is there something like item data custom storage where I could save my data for specific ImGuiID? I could save the release timer for a specific item, set it to null when the item is active otherwise add g.IO.DeltaTime.
Hope for your help! I will be glad to any suggestions on how to implement this in the best way!
Thanks in advance!

**Comment by ocornut** [comment]
Hello,

> Is there something like item data custom storage where I could save my data for specific ImGuiID? 

You can use a ImGuiStorage (your own or one inside a window) or use your own storage.

I haven't experimented with this since I wrote https://github.com/ocornut/imgui/issues/1537 but I think down the line we'll want to provide dedicated timer storage helpers for facilitate this sort of things while handling >1 simultaneous timer.
