### ISSUE TITLE
Issues with multi-threading: using std::async with imgui 

### ISSUE THREAD

**Issue by varung2** [ocornut/imgui#3794]
**Version/Branch of Dear ImGui:**

Version: v1.80
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_opengl2.cpp
Compiler: g++
Operating System: Ubuntu 20.04.2 LTS (Using WSL)

**My Issue/Question:**

Hello, I am trying to add imgui to my application, however, I am running into some issues when I try to render the gui in an async lambda function. I am really new to the OpenGL SDL2 paradigm so apologies if this has already been answered or asked somewhere else (please redirect me if it has). The easiest way to show this problem is the minimum reproducible example below. I am using the "example_sdl_opengl2" example and I added a couple of simple additions in the main.cpp. 

Here are the modified files:
[example_sdl_opengl2.zip](https://github.com/ocornut/imgui/files/5948823/example_sdl_opengl2.zip)

Minimum Reproducible Example:
```
// example_sdl_opengl2/main.cpp file
... //Other Includes
#include <thread>
#include <future>

int main(int, char**) {
    ... // setup code - etc.

    std::future<void> main_thread;
    main_thread = std::async(std::launch::async, [&](){
        // Main loop
        bool done = false;
        while (!done) {
            ... // rest of the imgui context code
        }
    });
    main_thread.get();

    // Cleanup
    ...
    return 0;
}
```
Hopefully, this is relatively simple; I just wrapped the main loop in an async lambda function. If I do this, my screen doesn't render anything and instead, it shows a black screen. If I remove the async wrapper, the black screen is gone and the demo shows normally. I can show pictures if it is needed but I feel like it's sort of self-explanatory. 

So is this a problem with my setup (i.e. a result of using WSL) or could it be something wrong with how I am using SDL/OpenGL? Or is it an issue with imgui?

Any help is appreciated, thank you~

**Comment by rationalcoder** [comment]
OpenGL contexts are thread-local. You've set everything up for rendering in the main thread. You need to move some of the initialization code into the other thread for this to work.

**Comment by rokups** [comment]
Besides using multiple threads is a mistake.
1. Your chosen graphics API is inherently single-threaded
2. Dear ImGui is inherently single-threaded

You may think that rendering in a separate thread will somehow make things fast, but things are not that simple in practice. Short answer to your problem is: run application main loop in a main thread, when you get performance issues you may try _processing_ your data in multiple parallel threads, wait for them to finish and only then continue _rendering in the main thread_. This is called fork-join pattern. Anything else is vastly more complicated and in general this is not a problem with Dear ImGui but a general programming question.

**Comment by varung2** [comment]
Thank you for the helpful responses, would you guys have some helpful resources where I can learn more about this?

**Comment by ocornut** [comment]
Closing as answered by @rationalcoder.
Anyone feel free to share/post helpful resources if you can think of any.
