### ISSUE TITLE
Possible Push/Pop StyleColor bug with Selectable

### ISSUE THREAD

**Issue by kolyden** [ocornut/imgui#382]
Hi.

Thank you for great gui library, but i have some troubles with it.
When i wrap Selectable with Push/Pop StyleColor for text there is always throw an error in 
CheckStacksSize for g.ColorModifiers.Size imgui.cpp:3355
last version from SVN

you can easily reproduce this in demo.cpp go to line 394 and replace with this

```c++
ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(0, 1, 0, 1));
if (ImGui::Selectable("Me", &selected[i], 0, ImVec2(50,50)))
{
    int x = i % 4, y = i / 4;
    if (x > 0) selected[i - 1] ^= 1;
    if (x < 3) selected[i + 1] ^= 1;
    if (y > 0) selected[i - 4] ^= 1;
    if (y < 3) selected[i + 4] ^= 1;
 }
ImGui::PopStyleColor(ImGuiCol_Text);
```

is this a bug or i am misunderstood something?

**Comment by ocornut** [comment]
PopStyleColor() parameter is a count which you generally leave to its default (1) meaning pop 1 element.

Unfortunately there's no enum type safety with the way I declare enum so that sort of error can happen. When you have an issue the best thing is to grep for the function name in the codebase and see how it is being used.

**Comment by kolyden** [comment]
Oh. Stupid mistake, sorry.

**Comment by ocornut** [comment]
No problem. I'll have to reconsider how I can declare those enum in a way that is more likely to trigger warnings.
