### ISSUE TITLE
Any reason why u did not make use of std::string?

### ISSUE THREAD

**Issue by fourtytwo** [ocornut/imgui#387]
Basically what the title says. I was wondering if anyone would intervene if someone would create a few function overloads using std::string instead of char*

**Comment by ocornut** [comment]
You are free to create any function in your codebase. ImGui is all in a namespace so you can add helpers functions in the same namespace without touching the original files if that makes sense for your project.

I don't use std::string because they it is a rather bloated library, it does heap allocations like there's no tomorrow, making them very very inefficient for the amount of string manipulation a typical complex ui would require. In addition it makes interaction with other languages harder.

So to answer your question, ImGui itself will not include any code using those.
