### ISSUE TITLE
Examples: DX9, DX10, DX11, DX12: ImGui_ImplDX?_NewFrame might called in the wrong place?

### ISSUE THREAD

**Issue by Demonese** [ocornut/imgui#3880]
**Version/Branch of Dear ImGui:**

Version: 1.81
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx?.cpp
Compiler: aby
Operating System: any

**My Issue/Question:**

In examples, ImGui_ImplDX?_NewFrame are called in this way:
```c++
// Start the Dear ImGui frame
ImGui_ImplDX?_NewFrame();
ImGui_ImplWin32_NewFrame();
ImGui::NewFrame();
```
But I think ImGui_ImplDX?_NewFrame should called before ImGui_ImplDX?_RenderDrawData.
```c++
ImGui_ImplWin32_NewFrame();
ImGui::NewFrame();

...

ImGui::Render();
ImGui_ImplDX?_NewFrame();
ImGui_ImplDX?_RenderDrawData(ImGui::GetDrawData()...);
```

Why?
* Some applications resize swapchain (might using Dear ImGui widget) during updating but failed and cause device lose.
* Some applications support device event callback and device lose will happend at any time.
* Device lose might happend beteen ImGui_ImplWin32_NewFrame and ImGui::Render, and might not recover in time. if this happend, ImGui_ImplDX?_RenderDrawData will crash the application.

Call ImGui_ImplDX?_NewFrame before ImGui_ImplDX?_RenderDrawData ensure that all objects (textures, buffers) are created before rendering.

In fact, this problem occurred in our application. Although it was my fault, I think the example is still somewhat misleading. According to examples, I thought ImGui_ImplDX?_NewFrame, ImGui_ImplWin32_NewFrame, ImGui::NewFrame should always called together. But it shouldn't.

Although this problem seems not happend in examples, I still suggest to call ImGui_ImplDX?_NewFrame before ImGui_ImplDX?_RenderDrawData. This will reduce the chance of crash and misleading developers.

Thanks!

**Comment by ocornut** [comment]
The texture needs to be created at the beginning of the frame since TexID is stored in all draw commands.

I cannot do much with your issue without more specific details. At a glance it feels all of the topics you are discussing can/should be handled by application, and anyway it's not possible because of the TexID.

To be honest any discussions about backends is draining lots of energy and taking time away from actual core dear imgui development to the point where backends are almost nefarious to the progress of dear imgui. So let's keep those backend discussions focused to the most important requirements.

(We are working on some rework of backend infrastructure which will change some of the timing - moving texture upload to after EndFrame).
