### ISSUE TITLE
Drag & Drop with other mouse button than LMB

### ISSUE THREAD

**Issue by dgregorius** [ocornut/imgui#3885]
**Version/Branch of Dear ImGui:**

Version: 1.82 WIP
Branch: Docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp 
Compiler: VS 2019
Operating System: Windows 10

**My Issue/Question:**

I am implementing to move bones inside the hierarchy via drag & drop. In Maya this happens by dragging with the middle mouse button and I like to follow the established UI rules from there. I noticed that ImGui is hard coded to use the LMB. Can we make the desired mouse button optional?

**Comment by rokups** [comment]
Since you may be waiting for a response, i will explain this a bit. I took a look at `BeginDragDropSource()` and it has a hint of attempt to support arbitrary buttons. However it is not that simple. Drag operation is started when `BeginDragDropSource()` call appears after _active_ item, and items are activated by left mouse button only. Extending this functionality to other mouse buttons will definitely have other side effects and will not be trivial to implement. I also do not see any possible workaround. Unfortunately you will have to stick with left mouse button for foreseeable future.

**Comment by ocornut** [comment]
As hinted above there's are two sides to this.

(A.1) The first is that `BeginDragDropSource()` relies on ActiveID and most existing widgets only react to LMB only. In 1.78 we started exposing flags to allow using `InvisibleButton()` as a building-block for multi-buttons widgets. However it would seem tedious if somehow every widgets would need to be modified with adhoc flags. I presume in your case you care about a TreeNode?

(A.2)
Here's come the magic, this appears to works.... (but haven't been thoroughly tested)

```cpp
// Regular button
ImGui::Button("Button");

// Extend to react middle and right mouse buttons.
ImGuiWindow* window = ImGui::GetCurrentWindow();
ImGui::ButtonBehavior(window->DC.LastItemRect, window->DC.LastItemId, NULL, NULL, 
 ImGuiButtonFlags_MouseButtonMiddle | ImGuiButtonFlags_MouseButtonRight);
```

(B)
But `BeginDragDropSource()` currently hard-coded for LMB.
The reasons the drag cares about mouse buttons at all are:
- it needs to check on drag threshold of mouse movement (rather than _just_ ActiveId)
- the drag payload and associated interaction can live outside the scope and life expectancy of the drag source.

Since drag and drop was added, active buttons now record the mouse button that activated them so we should be able to link those two now...

**Comment by ocornut** [comment]
Pushed 954b06afe2a95d04d85b8f4a7339f975c7a1c45c which now works with it:

```cpp
ImGui::Button("Button");
ImGuiWindow* window = ImGui::GetCurrentWindow();
ImGui::ButtonBehavior(window->DC.LastItemRect, window->DC.LastItemId, NULL, NULL, ImGuiButtonFlags_MouseButtonMiddle | ImGuiButtonFlags_MouseButtonRight);

if (ImGui::BeginDragDropSource())
{
    ImGui::Text("dragged button");
    ImGui::EndDragDropSource();
}
```

I think down the line we will need to explicit mouse button choice/mask in ImGuiDragDropFlags but for items with ID we can detect it, so that should solve the issue.

(cc same issue #1637)
