### ISSUE TITLE
Unable to use ## as part of the visible string

### ISSUE THREAD

**Issue by jimgbuck** [ocornut/imgui#3928]
**Version/Branch of Dear ImGui:**

Version: 1.82 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Operating System: Ubuntu 20.04

**My Issue/Question:**

Since ## is treated special, and there is no escape-coding it, there is no way to actually be able to have this as part of the string.. as near as I can tell reading through the code when using my example below. Specifically `ImGui::FindRenderedTextEnd` finds the first occurrence of ##. If it instead found the last occurrence, I think it would be ok. (If one doesn't want an ID at the end of their string with ## in it, they can just put ## at the very end to avoid the wrong ## getting "found".)

```
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::BeginListBox("blah");
ImGui::Selectable("##I really want to show all of this string##now maybe the ID"); // this prints an empty string
ImGui::EndListBox();
```

**Comment by ocornut** [comment]
We are not going to look for “last one” since it would mean every string would need to be scanned to the end.

I think an easier general solution is to use an empty glyph with zero horizontal advance.

In your example here you could use Selectable() with an empty string + TextUnformatted() with your full string

**Comment by jimgbuck** [comment]
I did play around with escaping, but it caused more headaches than it solved. I finally just inserted \r in between ## pairs in our strings.

I did also implement, but deleted, something that does do the 'find last ##' thing. It worked, and I think that overall it still wouldn't be too bad. I'm not sure how often ids are used (not often by us), and when they are used, they are probably rather short side, so I think the CPU hit would be quite minimal overall. But it does have the downside of not allowing ## to be a part of the id itself (such as "sometext##id0##more_id_stuff"), though I would guess that is super-rare compared to the possibility of one needing to legitimately use ## as renderable text (with hashtags being a common way of annotating thing).

**Comment by ocornut** [comment]
Using \r will indeed work...

My initial idea of inserting an empty character is also possible but it's currently quite ill-defined and fragile how to do it. 
This currently work:
```
    ImFont* font = io.Fonts->AddFontDefault();
    io.Fonts->Build();
    font->AddGlyph(NULL, '\x7E', 0, 0, 0, 0, 0, 0, 0, 0, 0.0f);
    font->BuildLookupTable();
```
But it's bizarre (AddGlyph currently needs Build because it uses the font->ContainerAtlas), Build() itself would clear the new glyph etc.. So it's currently fragile.

>  I'm not sure how often ids are used (not often by us)

99% of the string passed to API are also ID so I'm not sure I understand the "not often by us".
On very large UI with lots of clipped items, laying out the non-visible items is one of the bottleneck requiring text size calculation, and the suggested change would largely increase that cost. 

While we aim to eventually add support for some kind of markup mechanism (for e.g. changing colors) I don't have visibility on that and its purpose would be to alter things at a slightly different level of the stack. But I suppose adding stuff like support for "\##" may be possible. Standardizing a dummy character guaranteed to be not visible would be useful there. Essentially this is exactly what \r does currently and I suggest using that. If we ever standardize another (more explicit) character for that purpose I'll let you know but using \r is fine.

**Comment by ocornut** [comment]
I'll close this at current workaround is to use `\r` but I'm hoping to provide a more standard workaround eventually. Will post when I do.

Bonus ref since i was curious and digged into ascii 0..31:
https://superuser.com/questions/634854/what-do-the-first-32-characters-of-the-ascii-table-do

**Comment by jimgbuck** [comment]
Hah, yeah, good times with the characters that actually used to do things in older times (tty machines, DOS, etc.).

"used by us" - I mean by my current team and the previous two teams I was on that used ImGui. We would only use ##tagging when we needed to, meaning when we had the same widget repeated multiple times in a particular scope (a bunch of buttons to play different sound clips, for example).

Yeah, \r is just the ticket for us now, works fine, and I'm creating a utility function so that the team can share using this wherever they need to. I did look into the invisible glyph, but didn't realize I could actually create one of my own (and am glad I didn't realize that since it looks a bit nasty based on your code :) ).. it looked more like I was to guess an invisible character and hope it worked the same in all fonts we may use. :)

Anyway, thanks for pointing out potentials leading us to the \r (found from digging into the render code and was relieved when I saw that early-out based on \r! :) )

**Comment by rokups** [comment]
[Zero width space](https://unicode-table.com/en/200B/) could also be used if your font has that.

**Comment by jimgbuck** [comment]
Yeah, true. I was going for a font-less solution, ideally at the string parsing level, which the \r ends up nicely working with. We now have a util function in our library that goes through and adds \r as-needed.

**Comment by PathogenDavid** [comment]
> We are not going to look for “last one” since it would mean every string would need to be scanned to the end.

I'm a little late to the party, but wouldn't string span support make this a non-issue since we already have the end of the string?
