### ISSUE TITLE
AddImageQuad with perspective rendering

### ISSUE THREAD

**Issue by leryss** [ocornut/imgui#3994]
**Version/Branch of Dear ImGui:**

Version: 1.82
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp 
Operating System: Windows 10

**My Issue/Question:**

Im trying to draw an image using the AddImageQuad primitive. Image vertices are very similar to the ones in the screenshot below, my problem is that the image gets rendered as the one above "Affine" instead of the one above "Correct". Is it possible to achieve that directly though ImGui without having to modify imgui_impl_dx9.cpp backend ?

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/8768822/113310681-2a663300-9311-11eb-82dd-a9f68268371c.png)

```
	Vector2 p1 = state->renderer.WorldToScreen(origin.add(Vector3(-size.x, 0.f, size.y)));
	Vector2 p2 = state->renderer.WorldToScreen(origin.add(Vector3(size.x, 0.f, size.y)));
	Vector2 p3 = state->renderer.WorldToScreen(origin.add(Vector3(size.x, 0.f, -size.y)));
	Vector2 p4 = state->renderer.WorldToScreen(origin.add(Vector3(-size.x, 0.f, -size.y)));

	drawList->AddImageQuad(
		GetImage(imageName), 
		(ImVec2&)p1, (ImVec2&)p2, (ImVec2&)p3, (ImVec2&)p4, 
		(ImVec2&)uv1, (ImVec2&)uv2, (ImVec2&)uv3, (ImVec2&)uv4, // These are the default UVs
		ImColor(color));
```

**Comment by ocornut** [comment]
I don't think it is possible of pre-transforming to screen coordinates since ImDrawVert would lose Z coordinate and therefore mess with the projection.
https://stackoverflow.com/questions/24441631/how-exactly-does-opengl-do-perspectively-correct-linear-interpolation

Some possibility:
- If your mesh are flat (as this one appears to be), you can use `ImDrawList->AddCallback()` to pass a projection matrix to your renderer, then submit to ImDrawList in world space and let the renderer do the projection (this is the approach I used to render the entirely of game contents for thedragonstrap.com)
- Or you can you use ImDrawList's callback to completely perform the rendering within the callback (and not use other ImDrawList primitives) and bypass ImDrawList rendering completely.
