### ISSUE TITLE
InputTextMultiline copy paste buffer overflow bug

### ISSUE THREAD

**Issue by LPVOIDDev** [ocornut/imgui#4038]
**Version/Branch of Dear ImGui:**

Version: Dear ImGui 1.83 WIP (18203)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx10.cpp
Compiler: Visual Studio 2015 (v140)
Operating System: Windows 10 (1809)

**My Issue/Question:**

The whole program hangs when copy-pasting a text in a InputTextMultiline with buffer size 1024

**Steps to reproduce:**

1. In the **imgui_demo.cpp** edit the line `static char text[1024 * 16] =` to `static char text[1024 * 1] =`
2. Start demo and go to `Demo > Widgets > Text Input > Multi-line Text Input`
3. Put mouse cursor inside InputTextMultiline
4. Ctrl+A
5. Ctrl+C
6. Ctrl+V (x5)
7. Ctrl+A
8. Ctrl+V
9. **\*Program hangs\***

![image](https://user-images.githubusercontent.com/24913148/114366480-ec7cd080-9b94-11eb-8338-f8a5625294e6.png)

**Some insight:**
Unfortunately, I was not able to debug the issue directly from VS2015 because the debugger doesn't work on this version of VS.
But I've gone through manually debugging with CE
I found out that it never goes out of this loop because `state->undo_char_point + numchars` is always `1050` whereas `STB_TEXTEDIT_UNDOCHARCOUNT` is set to `999`

![image](https://user-images.githubusercontent.com/24913148/114366964-6614be80-9b95-11eb-8c9a-49f192b95086.png)

ECX value never changes and is stuck with value 1050 (0x41a)

![image](https://user-images.githubusercontent.com/24913148/114366929-5ac19300-9b95-11eb-80d7-b95a79cd29ce.png)

**Comment by PathogenDavid** [comment]
Thanks for the repro, @LPVOIDDev! I can reproduce this now.

It looks like that loop is expecting `stb_textedit_discard_undo` to clean up `undo_char_point`, which it will:

https://github.com/ocornut/imgui/blob/d6a5cc7934b4f4f9d5effffc4f1acee151247f51/imstb_textedit.h#L1134

But it isn't doing that because `undo_point` is 0. I suspect that `undo_char_point` isn't expected to be non-zero when `undo_point` is 0, but I'm not particularly familiar with the `stb_textedit` stuff.

This external issue appears to be the root cause: https://github.com/nothings/stb/issues/734

I agree with Unit2Ed here. Unless I'm missing something, removing the undo point seems unnecessary because it was never even created. I removed the decrement like they mentioned and the problem goes away for me. It seems to me like a failed insert has the potential to corrupt `stb_textedit`'s undo stack.

I'd need more time to investigate for sure though, I didn't dig into things very much.

**Comment by v71** [comment]
If state->undo_char_point is an unsigned integer then the value is set to 255 , which eventulally will lead to a loop.

**Comment by ocornut** [comment]
Fixed by d9b606672ae145457d12dacdc82b82c6ce9ebd79 and submitting PR to nothings/stb
Thanks you!
