### ISSUE TITLE
Have a border only around active widgets

### ISSUE THREAD

**Issue by OverShifted** [ocornut/imgui#4050]
I am using Dear ImGui in my engine for about a year now and today I was spending some time with styles.
I made my UI look like this:
![image](https://user-images.githubusercontent.com/53635046/115106747-b6b45f00-9f7b-11eb-96d7-cc21bdde49ec.png)
That border looks like macOS and IntelliJ's dark theme.

But it looks very bad when all widgets have that border.
I want the border to be only enabled (visible)  around "active" (focused) widgets.
Can anyone help me with that?

Thanks for the awesome library btw.

**Comment by PathogenDavid** [comment]
I do not believe this is something you can easily do today.

If you're willing to modify Dear ImGui slightly, you can get something close to this using the navigation highlights by removing these two lines from `ImGui::RenderNavHighlight`:

https://github.com/ocornut/imgui/blob/936f53229db4d45b445a3c26795718523262654e/imgui.cpp#L2858-L2859

(That `ImGuiNavHighlightFlags_AlwaysDraw` flag is not something you can specify anywhere externally. It's meant to support the [range_select feature](https://github.com/ocornut/imgui/tree/features/range_select) - https://github.com/ocornut/imgui/issues/1861)

Here it is with the filter colors box active and a red highlight border:

![image](https://user-images.githubusercontent.com/278957/115114027-c53a5080-9f52-11eb-980f-05c478fc02f1.png)

If you want to eliminate that padding or change the thickness, you'd have to further modify `ImGui::RenderNavHighlight` since those distances are hard-coded.

-----------

Worth noting though that depending on how picky you are, the widget with navigation focus may not always match your expectation. For example, when you expect a dropdown the hovered item has navigation focus and the dropdown does not:

![image](https://user-images.githubusercontent.com/278957/115114173-70e3a080-9f53-11eb-921c-d63ac86c6a97.png)

**Comment by ocornut** [comment]
Hello,

Note that "Active" and "Focused" are very different concepts in dear imgui terminology. 
Active = being clicked/held or being edited.
Focused = is closer to what is interesting to you.

`NavHighlight` color seems to be doing what you are looking for, but:
- Exact thickness/sizing/rounding are not yet configurable (will likely be in Styling v2).
- As pointed above, you might want to hack `RenderNavHighlight()` if you really want this soon.
- Using the mouse currently disable the highlight (again, as pointed above).

For that later thing: the navigation system was originally introduced with the expectation that dear imgui is used as an overlay over an application that already has input going on. so there was a bias toward being able to relinguish keyboard capture (using ESC). Nowadays we have application types that may want to never disable navigation/capture keyboard and never lose that highlight, so those are options we should be adding provided the right design. I suspect it will still be crucial to allow people to unfocus a window and give inputs back to underlying application, but maybe the nav highlight will stay displayed just with a different "unfocused" color.

Ref #3200 #2048 #2009

**Comment by OverShifted** [comment]
Thanks, @ocornut, and @PathogenDavid for your help.
I think the best option for me is to wait for "Styling v2" because I don't like making a mess in my code.
Closing this for now.
