### ISSUE TITLE
Cant get multi viewports work. Assertion fails with "Platform init didn't install handlers?"

### ISSUE THREAD

**Issue by SeveriSuominen** [ocornut/imgui#4052]
**Version/Branch of Dear ImGui:**

Version: 1.83
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_opengl3.cpp 
Operating System: Windows 10

**My Issue/Question:**

I cant get multi viewports work. Assertion fails with "Platform init didn't install handlers?". My all imgui files are from docking branch, and I have checked the example multiple times, and dont really see any differences. Am I still missing something or can this be bug?

My current code:

```
gladLoadGLLoader(SDL_GL_GetProcAddress);

// GL 3.0 + GLSL 130
const char* glsl_version = "#version 130";
SDL_GL_SetAttribute(SDL_GL_CONTEXT_FLAGS, 0);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);

SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 24);
SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, 8);

SDL_GLContext gl_context = SDL_GL_CreateContext(window);
SDL_GL_MakeCurrent(window, gl_context);
SDL_GL_SetSwapInterval(1); // Enable vsync

// Imgui
IMGUI_CHECKVERSION();
ImGui::CreateContext();
ImGuiIO& io = ImGui::GetIO(); (void)io;

ImGui::StyleColorsDark(); // Style

ImGui_ImplSDL2_InitForOpenGL(window, gl_context);
ImGui_ImplOpenGL3_Init(glsl_version);

//auto font = io.Fonts->AddFontDefault(50);
//ImFont* pFont = io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\Ruda-Bold.ttf", 50);
//ImGui::PushFont(font);
//io.Fonts->GetTexDataAsRGBA32(io.Fonts->AddFontDefault());

//io.Fonts->Build();

io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;       // Enable Keyboard Controls
//io.ConfigFlags |= ImGuiConfigFlags_NavEnableGamepad;      // Enable Gamepad Controls
io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;           // Enable Docking
io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;       // Enable Multi-Viewport / Platform Windows
//io.ConfigViewportsNoAutoMerge = true;
//io.ConfigViewportsNoTaskBarIcon = true;

ImGuiStyle& style = ImGui::GetStyle();
if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable)
{
style.WindowRounding = 0.0f;
style.Colors[ImGuiCol_WindowBg].w = 1.0f;
}

target_window = window;

ImGui_ImplOpenGL3_NewFrame();
ImGui_ImplSDL2_NewFrame(target_window);
ImGui::NewFrame();

ImGui::ShowDemoWindow();

auto io = ImGui::GetIO();
ImVec4 clear_color = ImVec4(0.45f, 0.55f, 0.60f, 1.00f);

ImGui::Render();

glViewport(0, 0, (int)io.DisplaySize.x, (int)io.DisplaySize.y);
glClearColor(clear_color.x * clear_color.w, clear_color.y * clear_color.w, clear_color.z * clear_color.w, clear_color.w);
glClear(GL_COLOR_BUFFER_BIT);
ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

// Multi viewport
if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable)
{
SDL_Window* backup_current_window = SDL_GL_GetCurrentWindow();
SDL_GLContext backup_current_context = SDL_GL_GetCurrentContext();
ImGui::UpdatePlatformWindows();
ImGui::RenderPlatformWindowsDefault();
SDL_GL_MakeCurrent(backup_current_window, backup_current_context);
}
SDL_GL_SwapWindow(target_window);
```

**Comment by PathogenDavid** [comment]
The SDL backend only initializes the platform interface if `ImGuiConfigFlags_ViewportsEnable` is enabled:

https://github.com/ocornut/imgui/blob/34d4bc620d8316f8a69ce25a75fce493fdddef5d/backends/imgui_impl_sdl.cpp#L241-L242

You're populating `ConfigFlags` after the backend is already initialized, so the platform interface is never initialized.

Move your calls to `ImGui_ImplSDL2_InitForOpenGL` and `ImGui_ImplOpenGL3_Init` later [like they are in `example_sdl_opengl3`](https://github.com/ocornut/imgui/blob/34d4bc620d8316f8a69ce25a75fce493fdddef5d/examples/example_sdl_opengl3/main.cpp#L134-L136).

**Comment by SeveriSuominen** [comment]
Now its working after populating the flags before backend initialization. Thank you very much!

**Comment by PathogenDavid** [comment]
No problem!

**Comment by ocornut** [comment]
I added those conditional checks, e.g.
```cpp
if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable)
    ImGui_ImplDX11_InitPlatformInterface();
```

Initially solely as a way to draw a clear line in the sand in term of:
- signifying to the casual reader and own-backend people that all that stuff is only necessary if you want multi-viewports.
- guarantying that none of the multi-viewport code in the backend will be used/exercised if disabled

What it means is that I think we could remove that `if ()` tests and it'll allow this to be toggled at runtime in this direction (off to on), at the minor cost of dropping the intent above.

We could in theory add a boolean and perform that initialization the _NewFrame() function of each backend, which would allow setting the flags after backend init. Easy change and would catch this case, but need someone to validate that late init (after already running) works nicely as well. IHMO it's not super important and can be revised maybe when we make "application owned window registration" an explicit thing, as that part is contained within the init code.

**Comment by PathogenDavid** [comment]
> * signifying to the casual reader and own-backend people that all that stuff is only necessary if you want multi-viewports.

As someone who uses Dear ImGui with a custom backend, I've definitely appreciated this! 😁

> We could in theory add a boolean and perform that initialization the _NewFrame() function of each backend, which would allow setting the flags after backend init

This sounds like it'd be opening Pandora's box of whacky edge cases. I think a different approach could be used to guide people towards correct API usage:

* Only set `ImGuiBackendFlags_PlatformHasViewports` in `ImGui_ImplWin32_InitPlatformInterface` instead of `ImGui_ImplWin32_Init`. (IE: Only indicate support when support is actually initialized.)
* Add an assert to `ImGui_ImplWin32_NewFrame` to check if `ImGuiConfigFlags_ViewportsEnable` is set but `ImGuiBackendFlags_PlatformHasViewports` is not.

That assert can mention that the backend was initialized without viewports and they were enabled after the fact, which I think would be clearer than the backend developer-oriented "Platform init didn't install handlers?" message.

**Comment by ocornut** [comment]
> This sounds like it'd be opening Pandora's box of whacky edge cases.

Yes and no, when viewports are disabled by definition there's only one, and we can already toggle off/on/off once enabled at first. And we can initially support it on frame 0 (to allow config flags after backend init) and assert on frame>N if we are unsure, But I think it would work. I just don't feel like bothering to make that change just right now.

> Only set ImGuiBackendFlags_PlatformHasViewports in ImGui_ImplWin32_InitPlatformInterface instead of ImGui_ImplWin32_Init. (IE: Only indicate support when support is actually initialized.)

Assuming this means `ImGui_ImplWin32_InitPlatformInterface()` is only called if the _Enable flags are already set, that would push us further toward the opposite direction of what those BackendFlags usually stand for. The BackendFlags should not depend on the Config/Enable Flags. I realize this is currently already a little broken because of that order constraint, but let's not push it further in that direction :)

> Add an assert to ImGui_ImplWin32_NewFrame to check if ImGuiConfigFlags_ViewportsEnable is set but ImGuiBackendFlags_PlatformHasViewports is not.

We currently silently disable `ImGuiConfigFlags_ViewportsEnable` in NewFrame() when that happens:
```cpp
    if (g.IO.ConfigFlags & ImGuiConfigFlags_ViewportsEnable)
    {
        if ((g.IO.BackendFlags & ImGuiBackendFlags_PlatformHasViewports) && (g.IO.BackendFlags & ImGuiBackendFlags_RendererHasViewports))
        {
             ....
        }
        else
        {
            // Disable feature, our backends do not support it
            g.IO.ConfigFlags &= ~ImGuiConfigFlags_ViewportsEnable;
        }
    }
```
Which is AFAIK more like an exception in the sense that we rarely disable config flags (insert of e.g. asserting) but since viewports may not be able on all targets even with a same backend, to requires the user to only be allowed set it when available would mean querying the BackendFlags and would mean that ConfigFlags would need to be setup AFTER backend init, which is similar to the issue we're trying to fix here.
