### ISSUE TITLE
ID and name problem

### ISSUE THREAD

**Issue by warm-dawn** [ocornut/imgui#4070]
I encountered such a problem:
There are many ImGui::Checkboxes with the same name, but for some reason, I can't rely on ImGui::PushID to solve this problem.
Is there any other solution?

**Comment by jimgbuck** [comment]
Can you post code as to why the id won't work? With the text you pass to Checkbox, you can tag the text with "your checkbox text##some unique id per checkbox".. if you use "###", it will only use the text after the "###" as the id, but it otherwise uses the whole string as the id.. but the important point is that none of the text starting with the "##" or "###" will print on-screen. It's just used for id purposes only.

**Comment by warm-dawn** [comment]
解决了:ImGui::PushID(&flag);
直接以地址作为id, 哈哈

**Comment by warm-dawn** [comment]
@jimgbuck thanks a lot!

**Comment by jimgbuck** [comment]
Hah, no problem, yeah, using a pointer can sometimes work, but I hope that `flag` persists per-checkbox. :)
