### ISSUE TITLE
Menu shows immediately upon hover after previously opening and hovering a popup.

### ISSUE THREAD

**Issue by Phongy** [ocornut/imgui#409]
I found this after downloading the latest version:

- Build and run d3d11 example.
- Expand Popups & Modal windows group.
- Click on Select.. button, this shows the fish menu.
- Move the mouse off the bottom of the popup menu directly on to "Menu" (which should be immediately below).
- Notice how the menu shows and the previous popup hides (seemingly incorrectly) whereas hovering "Menu" on its own does nothing.

**Comment by ocornut** [comment]
Thanks. Yes I had noticed this bug in the past. With the current scheme it is because the menu opened from "Select.." is a sibling of the "Menu" one. 

A parallel would be the "Menu", "Examples", "Help" items at the top in the menu bar, once one is opened with a click, other siblings can be opened by just hovering.

I'll look into fixing that eventually. Out of curiosity it is causing you a problem in a real application or have you just noticed it from browsing the example? Because this specific "Menu" item within the Window itself is a bit of an oddity itself that I assume would be rarely used in real application.

**Comment by ocornut** [comment]
Well it turns out that the fix is obvious and trivial, that is to make have different parents. I used that workaround and added a comment. It is really a weird use rare in the first place.

**Comment by Phongy** [comment]
I just noticed it in the sample, thanks for fixing.
