### ISSUE TITLE
InputDouble know which button is pressed

### ISSUE THREAD

**Issue by peterwilson136** [ocornut/imgui#4090]
I have a simulation speed button, which I want to increase by `1` when you click the `+` provided the value is `> 1` but if it is `<= 1` I want it to go down by `1/2` , `1/3`... I need to be able to do this at least by starting with knowing what button is pressed each time (either  `+` or `-`).

Also (extension), is there a way to count the times that it has been modified by only the buttons of `+` and `-`? Ie, if it's `+`, add `1` to a counter, if it is negative, subtract `1` from a counter?

**Comment by ocornut** [comment]
Hello,

> Which I want to increase by 1 when you click the + provided the value is > 1 but if it is <= 1 I want it to go down by 1/2 , 1/3... 
>  I need to be able to do this at least by starting with knowing what button is pressed each time (either + or -).

Those two statements are contradicting each others. You shouldn't need to care about which button is pressed, since you only care about the actual value being e.g. `<= 1` and you own that value therefore you can alter the step based on the value.

Also note that `DragScalar()` and `SliderScalar()` can be used with Double type and support the `ImGuiSliderFlags_Logarithmic` which also may solve your issue.

**Comment by peterwilson136** [comment]
Oh, I see what you are saying, yes it will change the sign to be positive or negative, so it doesn't matter about which button okay. I guess the issue is though, that if the value is at 1, if the `+` button is pressed, I want it to move to 2, but if the `-` button is pressed, I want it to move to 0.5 and then 0.33333 etc, I supposed logarithmic could work if i were in base 2 for some certain cases, but i'm not just multiplying by 2 or dividing by 2 each time. It is conditional on which button is pressed, that the increment value changes by, is the issue. If that makes sense?

**Comment by ocornut** [comment]
`InputScalar()` is a simple helper calling `InputText()` + 2 buttons, you can easily create your own helper widget and change the behavior of the buttons however you like.

Note that `InputScalar()` calls `DataTypeApplyOpFromText()` and `DataTypeApplyOp()` with + and - operators, because it is a generic function working on many data types, but your own functions may specialized for double and simply use normal `+` and `-` operators, or even use templates.
