### ISSUE TITLE
Docking: making sure node stays open after last window undocked?

### ISSUE THREAD

**Issue by invrainbow** [ocornut/imgui#4120]
I've created a default layout:

```c++
ImGuiID dockspace_id = ImGui::GetID("main_dockspace");

// set up dock layout
if (!dock_initialized) {
    ImGui::DockBuilderRemoveNode(dockspace_id);
    ImGui::DockBuilderAddNode(dockspace_id, ImGuiDockNodeFlags_DockSpace);
    ImGui::DockBuilderSetNodeSize(dockspace_id, ImGui::GetMainViewport()->WorkSize);

    dock_main_id = dockspace_id;
    dock_bottom_id = ImGui::DockBuilderSplitNode(dock_main_id, ImGuiDir_Down, 0.20f, NULL, &dock_main_id);
    dock_sidebar_id = ImGui::DockBuilderSplitNode(dock_main_id, ImGuiDir_Left, 0.20f, NULL, &dock_main_id);

    // ...
    // calls to ImGui::DockBuilderDockWindow()

    ImGui::DockBuilderFinish(dockspace_id);
    dock_initialized = true;
}

ImGui::DockSpace(dockspace_id, ImVec2(0.0f, 0.0f), ImGuiDockNodeFlags_NoDockingInCentralNode);
```

I've divided my dockspace into a central node, sidebar, and bottom panel. Each of these nodes has a significance in my app. For example, I have a hotkey that hides/shows the sidebar. So I'd like to ensure these nodes stay alive and retain their identity (which I will access through `dock_bottom_id`, `dock_sidebar_id`, etc.).

Currently, if I undock the last tab in the sidebar, `SetNextWindowDockID(dock_sidebar_id)` no longer docks the window, as if the node no longer exists. How can I prevent that?

**Comment by 1aam2am1** [comment]
You can read how root node is split. In example left right up or down. Then how are these nodes split. And so on.

In my program I have programmed a function that will go by these split nodes in search of the node i want. In example if i want right node and i get split right and left. Then go to right node. If up and down go to up node. And so on. So that i will get the is of top most right, up node. 

Nodes can have different lifetime and can be created in different ways so that it is simply impossible to track and maintain.
