### ISSUE TITLE
the main window stop render when the mouse click the menu bar on macosx

### ISSUE THREAD

**Issue by iOSPrincekin** [ocornut/imgui#4150]
I run the "example_apple_opengl2" imgui example on macosx 10.15.7, when I click the Apple Icon on the left top of menu bar, the main window of example app stop render, how to solve this problem? thanks very much!!!

**Comment by ocornut** [comment]
Please provide more information and a screen recording at least.

**Comment by iOSPrincekin** [comment]
https://user-images.githubusercontent.com/40560744/118454385-e4332a80-b72a-11eb-9db6-6891dcc1c9eb.mp4

**Comment by rokups** [comment]
GLFW/SDL block main loop when menu is open. I could not find any explanation why this is, but regardless of the answer it is out of our control. Metal sample that uses cocoa directly does not have this issue. If this issue is a dealbreaker for you i suggest contacting GLFW/SDL people, they might have an answer.

**Comment by ocornut** [comment]
I suppose this is analogous to how Win32 app resizing/moving is modal and blocks the application from running.
There's most surely a way out for OSX, but not really our priority to dig into solving that. If there is a solution and somehow our example can support them without too much cruft it'd be a nice bonus.
