### ISSUE TITLE
Align buttons to the right?

### ISSUE THREAD

**Issue by invrainbow** [ocornut/imgui#4157]
![image](https://user-images.githubusercontent.com/77120437/118581703-ec995e80-b746-11eb-9eef-cff12c37f380.png)

Is it possible to move a couple buttons
```
ImGui::Button();
ImGui::SameLine();
ImGui::Button();
```
to the right? I know about `ImGui::PushItemWidth(-x)` but that appears to only work for input elements.

**Comment by PathogenDavid** [comment]
As far as I'm aware there's nothing built-in to do this easily due to the fact that the position of the save button is already fully laid out before the cancel button is even added. (To put it another way: The save button doesn't know anything about the cancel button, so its position can't be based on it.)

The easiest solution today is to use fixed-width buttons and manual add the appropriate offset:

```cpp
ImVec2 buttonSize(100.f, 0.f);
float widthNeeded = buttonSize.x + style.ItemSpacing.x + buttonSize.x;
ImGui::SetCursorPosX(ImGui::GetCursorPosX() + ImGui::GetContentRegionAvail().x - widthNeeded);
ImGui::Button("Save", buttonSize);
ImGui::SameLine();
ImGui::Button("Cancel", buttonSize);
```

If you really want the automatically-sized buttons, you can manually calculate their size and offset based on that:

```cpp
float buttonWidth1 = ImGui::CalcTextSize("Save").x + style.FramePadding.x * 2.f;
float buttonWidth2 = ImGui::CalcTextSize("Cancel").x + style.FramePadding.x * 2.f;
float widthNeeded = buttonWidth1 + style.ItemSpacing.x + buttonWidth2;
ImGui::SetCursorPosX(ImGui::GetCursorPosX() + ImGui::GetContentRegionAvail().x - widthNeeded);
ImGui::Button("Save");
ImGui::SameLine();
ImGui::Button("Cancel");
```

![image](https://user-images.githubusercontent.com/278957/118663086-248bba80-b7b6-11eb-9d8c-a8602e09278f.png)

**Comment by invrainbow** [comment]
That solves my problem, thanks!
