### ISSUE TITLE
Proper setup of Dear ImGUI on Visual Studio?

### ISSUE THREAD

**Issue by RogueCOMObject** [ocornut/imgui#4235]
So usually I just use the project provided in the examples directory when I start a new project and it compiles with no problems, but this time I wanted to start it all over again. I created a new console application on Visual Studio, copied the WHOLE imgui folder, added the paths to the .h, .cpp and the .lib files accordingly and tried a simple sample code like the one provided in the wiki:

```

ImGui::Text("Hello, world %d", 123);
if (ImGui::Button("Save"))
    MySaveFunction();
ImGui::InputText("string", buf, IM_ARRAYSIZE(buf));
ImGui::SliderFloat("float", &f, 0.0f, 1.0f);
```

However I'm getting a LNK1120 linking error for ImGui::Text.  I've already included all the possible paths on the IDE. What gives?

**Comment by PathogenDavid** [comment]
Please don't ignore the issue template, it's there for a reason. For example, it would've been helpful to know what backend you're planning to use because how you set things up depends on that. (For example, using SDL, GLFW, and OpenGL all take slightly more effort than Win32/DirectX.)

> added the paths to the .h, .cpp and the .lib files accordingly

This is likely your problem but it's worded too ambiguously to know what you're doing wrong.

At a glance though, it sounds like you aren't telling Visual Studio to build Dear ImGui. In your case, you need to add the relevant `.cpp` files to your project too:

Right-click your project, select "Add > Existing Item..." and add:

* `imgui.cpp`
* `imgui_demo.cpp`
* `imgui_draw.cpp`
* `imgui_tables.cpp`
* `imgui_widgets.cpp`
* The `.cpp` files for any backends you plan to use.
* It's also probably a good idea to add the header files so you can browse them more easily, but that's completely optional.
