### ISSUE TITLE
Listbox and ImGui::Selectable reacts to user input despite passing window flag ImGuiWindowFlags_NoInputs.

### ISSUE THREAD

**Issue by EhWhoAmI** [ocornut/imgui#4256]
**Version/Branch of Dear ImGui:**

Version: 1.84 WIP, commit f0c4d609a6186b0b6db5022eb07a75656b8f399d (latest of master as of this issue)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_GLFW.cpp + imgui_impl_opengl3.cpp
Compiler: MSVC 2019
Operating System: Windows 10

**My Issue/Question:**

When the window flag ImGuiWindowFlag_NoInputs is passed to a window, buttons, sliders, and most other widgets do not react, as expected. However, with a listbox along with a ImGui::Selectable, this expected behavior does not occur. They are clickable and interactable as if no window flags are used. 

**Standalone, minimal, complete and verifiable example:** 
```c++
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example", NULL, ImGuiWindowFlags_NoInputs);
const char* items[] = { "AAAA", "BBBB", "CCCC", "DDDD", "EEEE", "FFFF", "GGGG", "HHHH", "IIII", "JJJJ", "KKKK", "LLLLLLL", "MMMM", "OOOOOOO" };
        static int item_current_idx = 0;
        if (ImGui::BeginListBox("listbox"))
        {
            for (int n = 0; n < IM_ARRAYSIZE(items); n++)
            {
                const bool is_selected = (item_current_idx == n);
                // Will react to user input, is clickable
                if (ImGui::Selectable(items[n], is_selected))
                    item_current_idx = n;

                if (is_selected)
                    ImGui::SetItemDefaultFocus();
            }
            ImGui::EndListBox();
        }
// Will not react to user input
if(ImGui::Button("Test button")) {
       ImGui::Text("Button Pressed");
}
ImGui::End();
```

**Comment by ocornut** [comment]
`ImGuiWindowFlag_NoInputs` flag is not inherited by child window because it can be useful to selectively omit some inputs from a parent.
However I must ask because I am not sure I not sure you are using the right flag. Among other things **`_NoInputs` will make mouse inputs pass-through the window and "reach" the window behind it if there's any** Is that actually what you want?

I am wondering if instead you are not looking for something like `PushDisabled()`/`PopDisabled()` ? 
See https://github.com/ocornut/imgui/issues/211#issuecomment-857704649

![image](https://user-images.githubusercontent.com/8225057/123090944-0bb39c00-d429-11eb-9208-3bc8c36641de.png)

**Comment by EhWhoAmI** [comment]
Alright, good to know, thank you for your time!
