### ISSUE TITLE
menu in titlebar

### ISSUE THREAD

**Issue by keszegh** [ocornut/imgui#4258]
it seems to me that it is not possible to put menu in the titlebar. recently in many apps this is how it works, so it does not seem to be a too exotic feature. it just saves a lot of space in many cases.
after searching for a good example i've found this: https://reactjsexample.com/customizable-titlebar-for-frameless-windows-built-with-react/
but there are many apps, e.g. affinity designer but already the windows file manager does work like this.

one can workaround by hiding the titlebar and adding a menu only but this way it is impossible e.g. to drag the window only by grabbing the titlebar, which i need too. also a 'main menu bar' is not good enough as i don't want a menu that spans the whole screen, it just needs to be at the top of my (smaller) window.

so please consider adding this feature or let me know if i missed how to do it. thanks

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.

Closing.

**Comment by keszegh** [comment]
i did read and try to follow the guidelines, sorry if my comment seemed freeflowing. it is not really an issue but a feature request, so the guidelines did not seem to be easily applicable. in any case i'm not sure which detail made you close the issue without reacting to its content. if by not reading you mean that in the readme/demo etc. there is a way of doing what i asked for, then please direct me in the right direction.
thanks

**Comment by ocornut** [comment]
I don’t always read issues if it appears the person has made little effort filling the template or clarifying the vocabulary used. 

Unfortunately its not humanely possible for me to be taking care of everyone’s requests so as i require high standards for requests.

**Comment by keszegh** [comment]
i tried to be clear and brief in defining my problem.  then i explained briefly how i did try to solve the issue with the given toolset of imgui but i did not succeed. 
overall i can accept that for a project of this size you don't have time to consider every feature request. however, i think what i posed is a valid and interesting feature request (which i tried to illustrate with some examples where this design choice is followed) and i hoped that it will raise your interest too.

**Comment by ocornut** [comment]
I first suggest to read the Glossary first to clarify your request, because we can’t tell if you are refering to platform/os title bar or imgui title bar, platform windows or imgui window. 
There are lots of details in your later paragraph that are also ambiguous. 
Do you have ConfigWindowsMoveOnlyFromTitleBar set?

**Comment by keszegh** [comment]
sorry if i was not clear.
i refer to the title bar of an imgui window. what i want to achieve is that the title bar of an imgui window contains dropdown menus instead of (or next to) the title text. and the window should be draggable only with the title bar (i mentioned this only to point out that while one can mostly imitate what i want by having no title bar and having a menu bar at the top of the window, it won't behave exactly like i want, e.g. it will be draggable everywhere, it won't be possible to minimize the window by double clicking on the menu bar etc. a menu bar is not exactly a title bar, in short.)

**Comment by ocornut** [comment]
Thanks for the clarification.

It's a reasonable request. Since we layout the title bar in Begin() we could technically decide at this point where the menu bar would be and move it in the remaining space. However out of experience this sort of stuff generally carries dozens of tricky/ever-ongoing issues so I'm not fond of going in that direction right now. 

I gave it a 15 minutes attempt in this hack/experiment: 27e6aff2cba96366425c98acc24becdbb6e96033

Right now I can see:
- [ ] Prevent title text from being realigned (not so bad)
- [ ] Unsaved document flag would move the menu bar
- [ ] Less space for menu bar puts more pressure on the fact that overflowing items can't be seen/used
- [ ] Can't display menu bar items while collapsed (inconsistent with Begin/End return value mechanism)
- [ ] Current hack has a minor clipping rect lag issue (fixable)

Pretty sure we would discover 5-10 more issues including some more difficult one if we dig further.

![image](https://user-images.githubusercontent.com/8225057/123409970-1304b200-d5af-11eb-9b45-663a5793aadc.png)

![image](https://user-images.githubusercontent.com/8225057/123410043-26b01880-d5af-11eb-8910-944ea3b61854.png)

Mostly, the big problem I can see it that this would be completely invalidated by the use of docking. As it is likely people will increasingly move toward docking, there will be a tendency for window title to be displaying within a tab among other tabs, making that sort of layout inadequate. So I'm not sure it is worth investing in doing this.

**Comment by keszegh** [comment]
first, thanks for changing the title of the issue and considering the request.

second, i really like how it looks on the screenshots and i'd be happy to be able to use this feature. ideally in your place i'd poll how many of the users like this feature and then decide if it's worth the effort to add it while handling all issues. i think it would be useful in many scenarios.

among the issues you mention the docking seems to be most problematic, but perhaps this title-type could be allowed only for non-dockable windows.

**Comment by ferencKx** [comment]
+1
Also looking for this feature/code for it
