### ISSUE TITLE
How IDs persist state?

### ISSUE THREAD

**Issue by Josef-Vonasek** [ocornut/imgui#4282]
After reading trough FAQ, I still don't understand how IDs work, precisely:

1. What happens if I assign new GUI element to ID that was previously used by different GUI element, and thus have an incompatible state.
2. What happens if I create 100+ new IDs in each frame (60x per s). Will unused IDs get garbage collected or will I get OOM. How do you detect unused ID?

**Comment by ocornut** [comment]
> and thus have an incompatible state.

Majority of widgets have zero custom state. 
There are exceptions e.g. `InputText()` state, custom sub-precision accumulator for `DragFloat()` dragging etc but they are typed data associated to a type of widgets so there shouldn't be any problem.

> What happens if I create 100+ new IDs in each frame (60x per s). 

There's nothing to garbage collect because nothing is stored.

If you create 1000 buttons other than outputting 1000x the vertex data (at least for visible ones), but we won't store anything else.

In `Demo>Metrics/Debugger` you can see the number of active allocations (calls to malloc that we are holding on). In most usage of dear imgui this number is extremely low (100-200), and dear imgui is designed to make zero allocations on frames when nothing has changed.

**Comment by ocornut** [comment]
Clarification:

The things we store are designed to sustain scale.
So instead of e.g. "storing every object and each of them has 'I am hovered?' state" (with growing number of objects) we store "which object ID is hovered?" (that's a single field).

Many more complex things in dear imgui are designed around the same idea. Of course we use arrays and maps and growing buffers but all allocations are designed to be amortized . We also have garbage collections for certain "large" types and those are also designed for scalability. For example the GC process for Tables (which nowadays is not super important as most buffers are shared) is designed to iterate over contiguous compact data (we touch a single contiguous buffer that hold 4 bytes per table and is enough to let us decide whether we need GC, so if you have 200 tables we'll iterate a single time every frame over 800 bytes aka 13 cache lines on most setups).

The only thing that doesn't scale to my liking presently if we have several iterations over all windows that existed within a session. So if you created 100000 windows and stopped to submit them, currently this may have a noticeable effect on performance during the session even after they stopped appeared. If you create 100-200 windows this is going to be absolutely negligible. (There is a relatively easy workaround for the edge case of having created 100000 windows which is that you can simply shutdown and recreate the imgui context.). 

As a rough indication, creating and keeping 1000 simple windows open every frame takes 2 ms on my PC:

![image](https://user-images.githubusercontent.com/8225057/123836793-5e4df600-d90a-11eb-9ff7-d4a08fd897e3.png)

As another rough indication, to submit 5000 buttons every frame I get an average of 0.8 ms:
![image](https://user-images.githubusercontent.com/8225057/123837122-c43a7d80-d90a-11eb-9943-b7229d2af1a0.png)
