### ISSUE TITLE
Upload alpha8 font texture to GPU ?

### ISSUE THREAD

**Issue by jpfphil** [ocornut/imgui#4283]
**Version/Branch of Dear ImGui:**

Version: 1.83WIP
Branch: Unknown (Dear ImGui version provided by https://github.com/eliasdaler/imgui-sfml)

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx10.cpp + imgui_impl_win32.cpp
Compiler: MSVC 192930038
Operating System: Windows 10 Family VERSION(20H2) BUILD(19042.1052) EXPERIENCE(120.2212.2020.0)

**My Question:**

Hello, currently implementing a "resize/zoom GUI" feature, the Chinese font texture exceeds the GPU maximum size.
I'm using the solution given [here](https://github.com/ocornut/imgui/issues/1434#issuecomment-344205472) talking about decreasing the oversampling.

But I'm also interested in the second solution:
> You can request the Alpha (not RGBA) texture and upload that to your GPU. This is the recommended thing and will divide your GPU memory consumption by 4 and CPU ram by 5.

I searched in the examples and the man, but didn't found anything — I maybe miss the good keyword.
How am I supposed to manage this?

**Comment by ocornut** [comment]
For DX10/DX11:

- Have your backend call `GetTexDataAsAlpha8()` instead of `GetTexDataAsRGBA32()`
- Use a texture and view format of `DXGI_FORMAT_R8_UNORM` instead of `DXGI_FORMAT_R8G8B8A8_UNORM`
- Modify `subResource.SysMemPitch = desc.Width * 4;` to `subResource.SysMemPitch = desc.Width * 1;` to reflect the format change.
- In the shader, you can change e.g. `float4 out_col = input.col * texture0.Sample(sampler0, input.uv)` to `float4 out_col = input.col * float4(1,1,1,texture0.Sample(sampler0, input.uv).x)`.
