### ISSUE TITLE
Focus textbox whenever window is re-focused?

### ISSUE THREAD

**Issue by invrainbow** [ocornut/imgui#4293]
I know it's possible to focus a textbox when a window first *appears*, using `IsWindowAppearing()`:

```c
if (ImGui::IsWindowAppearing())
    ImGui::SetKeyboardFocusHere();
```

Is it possible to set keyboard focus when the window is refocused, something like this?

```c
if (ImGui::IsWindowFocusing())
    ImGui::SetKeyboardFocusHere();
```

There's `IsWindowFocused()`, but that doesn't tell me if the window gained focus this frame. Do I need to hack this together using custom state?

**Comment by invrainbow** [comment]
All I can think of doing right now is:

```c
// in my state somewhere
bool focused = false;

bool imgui_is_window_focusing(bool *focused) {
    auto old = *focused;
    *focused = ImGui::IsWindowFocused();
    return !old && *focused;
}

ImGui::Begin(...);

bool is_focusing = imgui_is_window_focusing(&focused);
if (is_focusing)
    ImGui::SeteyboardFocusHere();

ImGuI::End(...);
```

It's pretty messy/hacky though so I'm wondering if there's a better way.

**Comment by ocornut** [comment]
It is a little tricky to provide a `IsWindowFocusing()` function for the current frame, because:
- multiple windows reappearing during the frame will all see themselves as focusing (except later one will override it)
- we will need to defer that focus decision until end of the frame (#2304)

So technically is you should be testing for `IsWindowFocused()` to return false, then true twice in a row to run your code.
