### ISSUE TITLE
How to display table data using DrawList?

### ISSUE THREAD

**Issue by IvaOsi** [ocornut/imgui#4299]
Hi all! I have tabular data (which is updated as new information comes in) I would like to know how you can display it on a graph

We have great methods like AddRectFilled AddLine and so on, but what if I need to draw a table?

If anything, my table looks pretty simple:

![image](https://user-images.githubusercontent.com/17671542/124836900-7833ac80-df8c-11eb-8610-5a87a066d66c.png)

Of course I can write something like drawtext then draw down on the y coordinate and drawtext again, but working with tables would be much more convenient because I could update the data in the whole table at once

Thank you in advance!

**Comment by PathogenDavid** [comment]
`ImDrawList` is only meant for low level drawing routines, I feel like drawing tabular data falls outside of its responsibilities.

Is there a reason you aren't using `ImDrawList` to draw your graph and the [new tables API](https://github.com/ocornut/imgui/issues/3740) for your table?

------------

As an aside, have you looked into [ImPlot](https://github.com/epezent/implot) at all? It may already provide the capabilities you need.

**Comment by ocornut** [comment]
Personally I don’t even understand what the question is about :(

**Comment by IvaOsi** [comment]
> Is there a reason you aren't using `ImDrawList` to draw your graph and the [new tables API](https://github.com/ocornut/imgui/issues/3740) for your table?
> 
> As an aside, have you looked into [ImPlot](https://github.com/epezent/implot) at all? It may already provide the capabilities you need.

I don't know how to use these two things. There is no AddDrawTable function
I looked at the api tables but there is nothing there to render them 

Also, I was watching implot (one of the project participants advised me to use tables) so now the project does not provide this option


>ImDrawList is only meant for low level drawing routines, I feel like drawing tabular data falls outside of its responsibilities.

I understand that, but drawing multiple times DrawText is very inconvenient (plus there are difficulties with updating)

It would be very convenient to have something like AddDrawTable 

Perhaps you can advise how to solve this problem

>Personally I don’t even understand what the question is about :(

How to draw tabular data (tables) using ImDrawList

**Comment by ocornut** [comment]
> How to draw tabular data (tables) using ImDrawList

I'm sorry this make little sense and is probably a [XY Problem](https://xyproblem.info/).
Your question suggests one specific solution to a problem you haven't probably explained. It's unclear why you are focusing on ImDrawList API and not using `BeginTable()`.

**Comment by IvaOsi** [comment]
> > How to draw tabular data (tables) using ImDrawList
> 
> I'm sorry this make little sense and is probably a [XY Problem](https://xyproblem.info/).
> Your question suggests one specific solution to a problem you haven't probably explained. It's unclear why you are focusing on ImDrawList API and not using `BeginTable()`.
I'm sorry, I should have added
I use Implot and this library draws everything via DrawList 
I intend to continue to use this library so I'm focusing on DrawList 
I need to not just show a table but draw it on a graph
Or we'll figure out some other way.

**Comment by PathogenDavid** [comment]
I think it'd help a lot if you showed us what you've already accomplished along with a sketch of what you're trying to accomplish.

**Comment by IvaOsi** [comment]
So I will begin, perhaps the question should be made more general. How do I draw tabular data?

My solution right now is this:
(for some reason I think it's VERY sub-optimal and maybe we could do it better)


```
struct MyDataInTableRow
{
    int x1;
    int x2;
};


namespace MyImPlot {

    void PlotTable() 
    {
        // get implot draw list
        // ImGui window DrawList
        ImDrawList* DrawList = ImPlot::GetPlotDrawList();


        // my table data
        std::vector<MyDataInTableRow> table = {
            {10, 20},
            {21 , 32},
        };
         
        std::string str = "";

        float x = ImPlot::PlotToPixels({ 1,1 }).x;
        float y = ImPlot::PlotToPixels({ 1,1 }).y;

        for (auto& element : table) {

            str = std::to_string(element.x1) + " " + std::to_string(element.x2);

            DrawList->AddText( ImVec2(x, y) , ImColor(253.0f, 1.0f, 255.0f, 1.0f), str.c_str());

            y = ImPlot::PlotToPixels({ 1 , 1 + 0.1 }).y;
        }
    }
}
```

Thanks to this solution, I get something like this:

![image](https://user-images.githubusercontent.com/17671542/124964847-26d9fa80-e02a-11eb-9250-57c7d625df40.png)


I have the feeling that this is a very bad solution (note that when you scale the rows begin to stick together)

Maybe we could draw the table itself somehow 
I just need to display two columns of numbers...

**Comment by ClaasJG** [comment]
Hi, I stumbled upon https://github.com/epezent/implot/issues/253 and think it provides some background and motivation for this question.

**Comment by ocornut** [comment]
> (for some reason I think it's VERY sub-optimal and maybe we could do it better)

For what reason do you think so? Have you been hurt by performances?

> (note that when you scale the rows begin to stick together)

What do you expect should be the correct result when zooming out? Maybe your +0.1f offset needs to be adjusted to compensate for zooming..

It seems to me like you have all necessary understanding and tools are your disposal to do what you need, but the exact interaction between the plot display and your "tabular data" are ambiguous so we don't know exactly what you need or what's not enough with your existing solution.

Technically speaking you could use Begin()/BeginChild() with same ID used by the child created by ImPlot to "append" into that window, then use SetCursorScreenPos() + BeginTable() and draw a table overlay over it.
Or you could yourself create an invisible "no input, no background, no decoration" window, position it over the plot, and draw the table in there too. There are countless variations of things you could do.

**Comment by IvaOsi** [comment]
> Maybe your +0.1f offset needs to be adjusted to compensate for zooming..

Thank you for your support!


Can you tell me how to do it? I'm not too well versed in the whole API yet

**Comment by PathogenDavid** [comment]
The screenshots and the graph names in the thread @ClaasJG linked are exactly what I was asking for. We can't help you if you're really vague about your needs, there's huge differences between rendering a 10,000 column Excel sheet and a handful of numbers on a graph for stock trading. We can't read your mind on what your exact needs are.

> I have the feeling that this is a very bad solution

That looks just fine to me. The string concatenation might add up over time with a complex graph, but that could be fixed by tweaking that aspect if and **when** it becomes a problem.

I second Omar: Don't worry so much about perceived performance issues if you aren't having any performance issues.

Based on what you're trying to accomplish in https://github.com/epezent/implot/issues/253, I think using Dear ImGui's table API is probably actually the harder/less performant route because your tables are so simple. (I'd go as far as to say they can barely even be considered tables in the first place.)

> (note that when you scale the rows begin to stick together)

Your text is inevitably going to end up squishing together since you aren't changing the size or (as Omar mentioned) the offset.

We can't guess which makes the most sense in your scenario. Looking at pictures of other footprint trading charts, I'm guessing text scaling is what you'd want.

> Can you tell me how to do it?

If you want to go the text scaling route, there's an [`AddText` overload which allows for size adjustement](https://github.com/ocornut/imgui/blob/cc40ae2101acd1fb4e0585a46198e6fd12960617/imgui.h#L2417) that you can use. (You can specify `nullptr` for `font` to use the default font.)

As for the scaling the offset or text size based on the plot scale, that is more of a ImPlot question. However I'm pretty sure the expected method is to use `PlotToPixels` twice with two different offsets (IE: the top and bottom of the text) and use the difference.
