### ISSUE TITLE
 ImGui errors : undefined reference to `ImmGetContext'

### ISSUE THREAD

**Issue by techGuyAj** [ocornut/imgui#4301]
Hi. I am doing Imgui setup on DevC++. I took all the header and CPP files in imGui and added them to my Dev c++ project. Assigned the path to find them in the include directories.

When I try to compile i am getting following errors:
undefined reference to `ImmGetContext'
imgui.cpp:(.text+0x22d7b): undefined reference to `ImmSetCompositionWindow'
imgui.cpp:(.text+0x22d8b): undefined reference to `ImmReleaseContext'

Please help me with the setup.

Thank you.

**Comment by ocornut** [comment]
If you are compiling for windows but not using Visual Studio, you should link with `imm32.lib` (`-limm32` on command-line).
If you search "undefined reference to `ImmGetContext' " on Google you'd find many answers to that same question.

**Comment by ocornut** [comment]
I pushed 30d164eb2 to undo the change made in 1.82 to enable IME support by default with non-Visual Studio compilers, since in master this is part of the core library rather than the win32 backend it seems reasonable to require explicit enable.
Non Visual Studio users who want IME support in their app need to compile with `#define IMGUI_ENABLE_WIN32_DEFAULT_IME_FUNCTIONS`.
