### ISSUE TITLE
Issue with ImGui::InputText speed

### ISSUE THREAD

**Issue by Kbz-8** [ocornut/imgui#4315]
Hi everyone. I have an issue with InputText speed. When I press a key on the keyboard, it is entered with incredible speed into the ImGui tag. The BackSpace key works fine, but it's the only one. This doesn't happen in the ImGui demo so it's probably my code but I have no idea why. I do have one call to ImGui::NewFrame per loop so it's probably not from that. If anyone can help me I would be very grateful. 
Thank you.

**Comment by ocornut** [comment]
Your delta time and therefore dear imgui’s understanding of time elapsed may be wrong, but because you ignored the requested issue template we have no idea which backends nor version you are using so I am not sure how you expect to get magical help.

cheers.

**Comment by Kbz-8** [comment]
Sorry. I use ImGui from master branch with SDL2 and Vulkan 1.2, on Linux Ubuntu and I'm compiling with GCC-G++ 9.3.0

The arrows are completely drunk. Sometimes they work just fine with the right speed and suddenly they decide to press indefinitely and all the controls start to fail.
The characters displayed are the right ones but are far too fast.

**Comment by Kbz-8** [comment]
Here you can find my code [https://github.com/Kbz-8/Akel/blob/dev/Editor/src/Panels/console.cpp#L86](url).
And here my ImGui implementation (this is for a game engine but it is just the begenning) [https://github.com/Kbz-8/Akel/tree/dev/Akel/src/Modules/ImGui](url)

**Comment by PathogenDavid** [comment]
Working permalinks:

https://github.com/Kbz-8/Akel/blob/51681f701e0c39b03d6a8a9bbb5890b0cb329921/Editor/src/Panels/console.cpp#L86

https://github.com/Kbz-8/Akel/tree/51681f701e0c39b03d6a8a9bbb5890b0cb329921/Akel/src/Modules/ImGui

-------------

Your [event processing](https://github.com/Kbz-8/Akel/blob/1cfd921a052913ef763d5d49bb869fe6f3ce9b7e/Akel/src/Core/application.cpp#L23-L28) does not look right at all. You call `_in.update()` which processes all SDL events that occurred that frame and only saves the most recent one. Later you call `elem->onEvent` which presumably calls [`ImGuiComponent::onEvent`](https://github.com/Kbz-8/Akel/blob/51681f701e0c39b03d6a8a9bbb5890b0cb329921/Akel/src/Modules/ImGui/imgui_component.cpp#L169-L172) which will only process that most recent event.

Additionally you aren't handling the scenario where `SDL_PollEvent` does not return an event, which means you're re-processing the most recent event every frame until a new one comes in (which is likely the direct cause of your issue.)

------------

As an aside, it's really lame to label your project as using the MIT license but have it not actually be the MIT license (and to put jokes in a legal document.) Also if you want a license which explicitly prohibits endorsement you should probably just use 3-clause BSD instead of trying to play lawyer.

**Comment by Kbz-8** [comment]
Problem solved ! Thank you !
