### ISSUE TITLE
Modal closes when window regains mouse focus

### ISSUE THREAD

**Issue by mattrberry** [ocornut/imgui#4317]
**Version/Branch of Dear ImGui:**

Version: 1.84 WIP (18302)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_opengl3.cpp
Operating System: Ubuntu 20.04

**My Issue/Question:**

In my example below, I render the main menu bar only when the SDL window has focus. In the menu bar, I have a single menu and menu item to open a modal. This modal opens and behaves as expected until the window loses and regains focus, at which point the modal closes. Ideally, the modal would remain open until I call `ImGui::CloseCurrentPopup()`. I'm wondering if I'm misusing modals or if this is possible a bug. Is there a preferred way to implement this behavior?

Apologies if this is a redundant question. I see https://github.com/ocornut/imgui/issues/331, but my question is more of a tangent from the discussion in that issue.

Thank you for taking a look!

**Screenshots/Video**

https://user-images.githubusercontent.com/22065329/125569342-c79ffdb5-ee7c-4405-abf6-ba575dcbc731.mp4

**Standalone, minimal, complete and verifiable example:**

```
bool open_modal = false;
if (SDL_GetMouseFocus()) {
    if (ImGui::BeginMainMenuBar()) {
        if (ImGui::BeginMenu("File")) {
            open_modal = ImGui::MenuItem("Open Modal");
            ImGui::EndMenu();
        }
        ImGui::EndMainMenuBar();
    }
}
if (open_modal) {
    ImGui::OpenPopup("Modal");
}
ImVec2 center = ImGui::GetMainViewport()->GetCenter();
ImGui::SetNextWindowPos(center, ImGuiCond_Appearing, ImVec2(0.5f, 0.5f));
if (ImGui::BeginPopupModal("Modal", NULL, ImGuiWindowFlags_AlwaysAutoResize)) {
    if (ImGui::Button("Close")) {
        ImGui::CloseCurrentPopup();
    }
    ImGui::EndPopup();
}
```

**Comment by ocornut** [comment]
Thanks, I could easily confirm the bug by changing `if (SDL_GetMouseFocus()) {` to `if (!ImGui::GetIO().KeyShift`. In fact, it would work with any type of window:

```
if (!ImGui::GetIO().KeyShift)
{
    ImGui::Begin("stealing focus");
    ImGui::End();
}
```
It seems peculiar that we haven't stumbled on this issue before, but I guess the majority of code written wouldn't spawn new window under a modal while a modal is active.

Not strictly the same as #4308 but I guess we may look into fixing both at the same time.

**Comment by PathogenDavid** [comment]
@mattrberry If you want a temporary workaround while Omar works on a proper fix, you can add `ImGuiWindowFlags_NoFocusOnAppearing` to this line in `imgui_widgets.cpp`:

https://github.com/ocornut/imgui/blob/17ec4f1f6fa64a08892d8dcfa61ace684bae53fc/imgui_widgets.cpp#L6754

**Comment by ocornut** [comment]
I looked at it a little bit and Rokups will investigate further but I think the fix is not going to be super easy to implement, focusing is a little complex right now.

May not directly related (unsure), but I'm aiming to move the FocusWindow() call done in Begin() to the end of level in order to solve #2304, but doing so required lots of yak-shaving already and some more (I'm nearly done with making NavInitWindow usable in parallel on multiple windows which is one of the immediate blocking thing).

**Comment by mattrberry** [comment]
Thanks so much for taking a look! I'm looking forward to the solution :)

Thanks @PathogenDavid for the temporary workaround!

**Comment by ocornut** [comment]
Hello @mattrberry, 

For the specific problem of modal closing we have a potential fix by @rokups coming but as i'm hoping to tag 1.84 I think that may be too risky for a merge right now, so we'll probably merge that between 1.84 and 1.85.

Generally speaking if your modal was a regular popup you would have a similar problem and the fix for modal wouldn't apply the same way. Considering how you are hiding/showing that menu-bar the proper fix may be to simply add the `ImGuiWindowFlags_NoFocusOnAppearing` flag to the window hosting your main menu bar, as suggested above. 

The way to do that would be to copy `BeginMainMenuBar()` in your own code (with a different name).
That function has a little extra cruft because it tries to handle safe display area, which is almost never something you'd care for nowadays, so if you strip that safe area code off your function becomes a simple:

```cpp
bool BeginMyMainMenuBar()
{
    using namespace ImGui;
    bool is_open = 
        BeginViewportSideBar("##MainMenuBar", viewport, ImGuiDir_Up, 
            GetFrameHeight(), 
            ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_MenuBar | ImGuiWindowFlags_NoFocusOnAppearing);
    if (is_open)
        BeginMenuBar();
    else
        End();
    return is_open;
}
```

**Comment by mattrberry** [comment]
Hi Omar, that makes sense that you want to tag 1.84. That sounds good. Thank you both for the workaround for the time being! I appreciate the help with this issue :)

**Comment by ocornut** [comment]
We have pushed a bunch of commit related to solving this.
Changelog says:
```
- Modals, Popups, Windows: changes how appearing windows are interrupting popups and modals. (#4317) [@rokups]
  - appearing windows created from within the begin stack of a popup/modal will no longer close it.
  - appearing windows created not within the begin stack of a modal will no longer close the modal,
    and automatically appear behind it.
```

AFAIK it should now be solved, however it is has been a really long road full of issues, bugs and other requires changes (we had to rewrite how the dimming system worked). Not ruling out the possibility that there might be other issues.. we'll keep this open for a while.

**Comment by ocornut** [comment]
Trail of commits leading to this:

1ab3007
f087a5b
5b1a70a
8733ca4
657073a
b38af0f
c80e8b9
a19815d
270d4d0
b16f738
c122c0e
1dc3af3
fc198fe
e03383d
0647cf4
747f7fd

**Comment by mattrberry** [comment]
Thank you so much for the detailed followup on this! Looking forward to trying it out :)

**Comment by mattrberry** [comment]
Looks to me like it's working as intended! Thanks again for this!
