### ISSUE TITLE
An endian issue when pack RGBA32 data

### ISSUE THREAD

**Issue by letidealsfly** [ocornut/imgui#4318]
Hi,

I think there is an endian issue in function GetTexDataAsRGBA32():
https://github.com/ocornut/imgui/blob/17ec4f1f6fa64a08892d8dcfa61ace684bae53fc/imgui_draw.cpp#L2061

If you want to use IM_COL32 to pack R,G,B,A channel to a 32bit data as format type RGBA32, it is OK in little-endian.
But on big-endian, to pack to RGBA32 data format I think should reverse channel shift.

For example: 
In little-endian, a RGBA32 data is 0x04030201, R is 0x01, G is 0x02, B is 0x03, A is 0x04.
In big-endian, a same RGBA32 data should be 0x01020304, R is 0x01, G is 0x02, B is 0x03, A is 0x04.

Could you check this issue? Thanks.

**Comment by ocornut** [comment]
Which big-endian CPU are you building for?
I don’t remember testing for big-endian.
As you are on that platform if you want to make a changes please research it and make a convincing PR, we can’t do it for you presently.

**Comment by letidealsfly** [comment]
It is a mips arch big-endian CPU.
OK, I can fix it if necessary.

**Comment by ocornut** [comment]
> I can fix it if necessary.

Whether it is necessary is up to you.
Right now we didn't explicitly support big-endian because I assume those arch were mostly dead in gaming-adjacent hardware land, and I personally don't know enough about it. But I think things should mostly if not already work in big-endian.

I'm not totally sure the encoding of a RGBA32 packed color matters all. Why did you come up with this issue? Which problem are you trying to solve?
That encoding that usually  be adjusted in the texture format or shader anyway.

If you have specific issue happy to see details and pull request.
