### ISSUE TITLE
Difference between std::vector and ImVector?

### ISSUE THREAD

**Issue by t0mke** [ocornut/imgui#4326]
I'm using the log app example and I tried to add a warning level in AddLog() where the values color code the text. I first tried using std::vector and once the program called push_back a few times I get access violation which does not happen when I use ImVector. This is too technical for my level and I don't really have the the time to understand what's going on but could anyone briefly explain why this happens. Below is a snippet of the code, i've just added a few lines from the original. 

```   
struct GUILog{
     ImGuiTextBuffer     Buf;
     ImGuiTextFilter     Filter;
     ImVector<int>       LineOffsets; // Index to lines offset. We maintain this with AddLog() calls.
     bool                AutoScroll;  // Keep scrolling if already at the bottom.
     ImVector<int> warnLine;
     GUILog()
     {
         AutoScroll = true;
         Clear();
      }

     void    Clear()
     {
        Buf.clear();
        LineOffsets.clear();
        LineOffsets.push_back(0);
      }

    void    AddLog(int warningLevel, const char* fmt, ...) IM_FMTARGS(2)
    {
        int old_size = Buf.size();
        va_list args;
        va_start(args, fmt);
        Buf.appendfv(fmt, args);
        va_end(args);
        for (int new_size = Buf.size(); old_size < new_size; old_size++) 
            if (Buf[old_size] == '\n') {
                LineOffsets.push_back(old_size + 1);
            }
        warnLine.push_back(warningLevel);
    }
```

**Comment by ocornut** [comment]
Sorry this is not a place to help you debug your code or teach people C/C++ we don’t have resources for that.

**Comment by PathogenDavid** [comment]
I agree with Omar, but I will note:

> This is too technical for my level and I don't really have the the time to understand what's going on

You cannot get away with this attitude with C++. It will not be nice to you when you're just fumbling around trying to get something to work without really understanding it.

The code you've provided is not logically sound. If I had to give a wild guess, your issue probably stems from indexing off the end of `warnLine` because you're not actually updating it per-line. (Why it happens with `std::vector` and not `ImVector` is anyone's guess.)
