### ISSUE TITLE
Imgui source code editor with node editor

### ISSUE THREAD

**Issue by aabilityuk** [ocornut/imgui#4345]
Hi, i am trying to find a proper approach to make a program that has both text source code and node editor, i need to generate code from nodes and vise versa.

Could anybody give me a direction please? Maybe there is a library with that functionality based on imgui ? 

If there is no library what is the approach should be?

thank you very much

**Comment by PathogenDavid** [comment]
The [Useful Extensions](https://github.com/ocornut/imgui/wiki/Useful-Extensions) wiki page has several third-party widgets for text and node editors.

> i need to generate code from nodes and vise versa.

As far as this aspect goes I'm pretty sure you're on your own. This is a pretty complex problem to solve and is definitely outside the realm of Dear ImGui. I think you'll end up quickly discovering why many tools tend to prefer one route or the other.

**Comment by meshula** [comment]
FWIW, I wrote my own graph editor, because none of the alternatives on the Useful Extensions page behaved exactly as I wanted. They're excellent and great to learn from, but I found, as many people do, that they are more specific to your application than you expect at first. For a text editor, I'm using zep ~ https://github.com/Rezonality/zep ~ because I like vim, and the code is easy to work with and integrate.

**Comment by aabilityuk** [comment]
> FWIW, I wrote my own graph editor, because none of the alternatives on the Useful Extensions page behaved exactly as I wanted. They're excellent and great to learn from, but I found, as many people do, that they are more specific to your application than you expect at first. For a text editor, I'm using zep ~ https://github.com/Rezonality/zep ~ because I like vim, and the code is easy to work with and integrate.

Thank you very much for reply! I ‘ll take a deep look on zep! If you already went through this way of programming source code generator based on nodes., could you please describe the problems you have on the way? I am afraid of that don’t have enough experience to write my own node editor and I am going to use an imgui-node-editor + zep as a start point. If you think that it is not a good bunch, could you please explain why and advice me to choose any other open source imgui node editor to start in combination with zep? 

Also it is very interesting to take a look on your own generator if it is not vip...

**Comment by meshula** [comment]
My graph editor is here.

https://github.com/LabSound/LabSoundGraphToy

LabNoodle is the base class, you have to declare a provider which binds the graph to the data it represents. The repo shows it specialized for my audio engine.

The specific issues I ran into, that set me on the path of writing my own, were 

- control over rendering, when it happens, what individual elements look like, special highlighting
- specific behaviors for navigating the map, such as scroll wheel zooms centered at the mouse. 
- Embedding Dear ImGui controls in nodes was not a requirement, because I wanted the graph to be usable at all zoom levels, and Dear ImGui isn't set up for arbitrary coordinate manipulations or pushing and popping a coordinate transform stack (correct me if I'm missed something here)
- I needed widgets in columns in nodes, there are various issues around widgets in columns in nodes in the various samples I experimented with before writing my own minimal widgets, most of which pop up an actual Dear ImGui widget, instead of embedding the widget in the node
- my graph editor is more "retained" and less "immediate". Embedding a fully Dear ImGui based retained graph in a large application can get extremely complex if the application has special rules about grouping, selection, focus, and so on, as the needs of the graph start conflicting with basic operations of Dear ImGui. 
- I wanted to experiment with a more data driven approach to the graph, borrowing some ideas from Sequentity's ECS driven architecture to decouple the UI from the data.
- I wanted to keep the graph manipulation code separate from the GUI code to make it easier to reuse between applications, and I didn't want to spent time carefully interleaving all the interactions with the graph with every application that uses it. Things like, if you click and drag on something Dear ImGui doesn't know about, such as a wire (or noodle ;)) you need to write special logic to make sure the click doesn't also go to some other Dear ImGui widget, and that the drag stays focused on your wire, and doesn't transfer to an official widget, and so on.

This isn't a knock on the other libraries, they all work well, they just didn't suit what I wanted to do, the way I wanted to do it ;)
