### ISSUE TITLE
AddrectFilled doesn't Render round Corners on dx11

### ISSUE THREAD

**Issue by swisscheez2** [ocornut/imgui#4363]
----

**Version/Branch of Dear ImGui:**

Version: Imgui 18.3
Branch: master

**Back-end/Renderer/Compiler/OS**
Vs2019

Back-ends: imgui_impl_dx11.cpp + imgui_impl_w32.cpp _(or specify if using a custom engine/back-end)_
Compiler: VS2019_(if the question is related to building or platform-specific features)_
Operating System: win10

I tried rendering a green bean on the screen using the dx11 example show demo implementation as you can see on the screenshot instead of having somewhat of a bean-shaped form I get some weird shape. I added my min example below so you can reproduce it. 

**Screenshots/Video**

![example_win32_directx11_pw1ZxDsoES](https://user-images.githubusercontent.com/31104685/126897287-49e96681-e3f8-4a83-862a-6fec4b2c7c40.png)

![example_win32_directx11_yUyDX0PIqA](https://user-images.githubusercontent.com/31104685/126897342-083ed834-117b-4010-be60-72a2df026204.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```

`ImGuiIO& io = ImGui::GetIO();
    ImGui::PushStyleColor(ImGuiCol_WindowBg, { 0.0f, 0.0f, 0.0f, 0.0f });
   ImGui::Begin("##Backbuffer", nullptr, ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoInputs);
    ImGui::SetWindowPos(ImVec2(0, 0), ImGuiCond_Always);
    ImGui::SetWindowSize(ImVec2(io.DisplaySize.x, io.DisplaySize.y), ImGuiCond_Always);`

` static ImColor greencol(0.f, 1.f, 0.f, 1.f);
    ImGuiWindow* window = ImGui::GetCurrentWindow();
    window->DrawList->AddRectFilled(ImVec2(100, 20), ImVec2(50, 50), greencol, 3.f, ImDrawFlags_RoundCornersAll );`

`  ImGuiWindow* window = ImGui::GetCurrentWindow();
    window->DrawList->PushClipRectFullScreen();
    ImGui::End();
    ImGui::PopStyleColor();`
```
the code was placed right after the showdemowindow part in the demo example 

one thing to note. the dx9 implementation gives me the correct bean-shaped form.

**Comment by PathogenDavid** [comment]
Not sure whether this should be considered a bug or not. This is happening because you're passing invalid coordinates to `AddRectFilled`.

https://github.com/ocornut/imgui/blob/9c77734447e4e2977ecb10d081383ba889dc643c/imgui.h#L2400

You're passing 100 for the minimum X coordinate and 50 for the maximum X coordinate, which gives you a negative width.

If you put them in the correct order it renders as expected:

```cpp
window->DrawList->AddRectFilled(ImVec2(50, 20), ImVec2(100, 50), greencol, 3.f, ImDrawFlags_RoundCornersAll);
```

![image](https://user-images.githubusercontent.com/278957/126902704-d7002647-a8cf-4d88-9bb1-d1dffa1f5cef.png)

-----------

>one thing to note. the dx9 implementation gives me the correct bean-shaped form.

I think you must've tried it with different coordinates with DX9 because it's broken there too:

![image](https://user-images.githubusercontent.com/278957/126902632-db0509c7-8994-44eb-a9f9-d90603ab3bdd.png)

**Comment by swisscheez2** [comment]
Oh wow how dumb of me, thanks a lot for clarifying this. That indeed fixes the issue. I'm really sorry for the useless Issue I oppened.
