### ISSUE TITLE
Display Dingbats Unicode

### ISSUE THREAD

**Issue by kensam94** [ocornut/imgui#4374]
Hi, I am trying to display Dingbats on button. I already use 32-bit for ImWchar and also add the dingbats unicode range to glyph. However, I am still seeing ? instead of  ➔.

#define IMGUI_USE_WCHAR32 in imconfig.h

   	ImGuiIO& io = ImGui::GetIO();
	ImFont* font1 = io.Fonts->AddFontDefault();
	static const ImWchar ranges[] =
	{
		0x0020, 0x00FF, // Basic Latin + Latin Supplement
		0x2700, 0x27BF, 
		0,
	};
	ImFontGlyphRangesBuilder range;
	ImVector<ImWchar> gr;
	gr.clear();
	range.AddRanges(ranges);
	range.BuildRanges(&gr);
	ImFont* pFont = io.Fonts->AddFontFromFileTTF(".\\arial-unicode-ms.ttf", 15, NULL, gr.Data);

	ImGui::PushFont(pFont);
	if (ImGui::Button("Copy to Left <<"))
		std::cout;
	ImGui::SameLine();
	if (ImGui::Button("➔"))
		std::cout;
	ImGui::PopFont();

**Comment by PathogenDavid** [comment]
You don't need `IMGUI_USE_WCHAR32` for that glyph since it's on plane 0.

As [stated in the FAQ](https://github.com/ocornut/imgui/blob/3d4d1b85538006fc9770774d3449ce1f23087341/docs/FAQ.md#q-how-can-i-display-and-input-non-latin-characters-such-as-chinese-japanese-korean-cyrillic), you need to either tell the C++ compiler that your string is UTF-8 or you need to manually encode it:

```cpp
ImGui::TextUnformatted(u8"➔ Hello, world!");
ImGui::TextUnformatted(u8"\u2794 Hello, world!");
ImGui::TextUnformatted("\xe2\x9e\x94 Hello, world!");
```

![Screenshot of the previous code](https://user-images.githubusercontent.com/278957/127330537-21716deb-15a2-4992-b0bd-ace027e1e9cb.png)

**Comment by kensam94** [comment]
I see. I missed it. Thanks a lot!
