### ISSUE TITLE
A Color Picker with Depth?

### ISSUE THREAD

**Issue by Garmichael** [ocornut/imgui#4392]
I am building a map editing tool for a retro game. The game's color depth only allows 32 colors per R, G, and B (instead of 256).

Would would I go about making the color picker show only values within that color depth?

**Comment by ocornut** [comment]
It may be simpler to create your own color picker.

**Comment by ocornut** [comment]
Note that you could also decide to use `ColorPicker()` and quantize color output value to 5 bpp instead 8 bpp, but the picker will still display a smooth gradient because it relies on vertex color interpolation.
Depending on the nature of your tool if may be enough.

(Unfortunately you cannot naively replace the `ImGuiColorEditFlags_PickerHueBar` or `ImGuiColorEditFlags_PickerHueWheel` sections and hue bar of `ColorPicker4()` with e.g. a 32x32 grid or 32x1 grid because HSV space doesn't map linearly to your 5 bpp RGB space. It may be easier to rewrite a simpler picker. Or just display smooth picker and quantize output down.)
