### ISSUE TITLE
CPU racing when app minimized

### ISSUE THREAD

**Issue by jvcleave** [ocornut/imgui#440]
Hey @ocornut 

I had this issue pop up with ofxImGui. The app's CPU escalates when the app is minimized.
https://github.com/jvcleave/ofxImGui/issues/4

I've seen this happen on a Mac a long time ago but apparently it's happening on Linux as well.

Here is a screenshot of my Mac (10.10.5) with the app up and then minimized. (edit: This is the opengl app from imgui examples)

![image](https://cloud.githubusercontent.com/assets/150037/11795235/a3e9d1ac-a283-11e5-8d19-e2a12c33b4e7.png)

**Comment by mmozeiko** [comment]
I don't think this is a problem with imgui. I'm guessing this is issue with OS doesn't do vsync for OPenGL when window is not visible. I suggest handling window minimize/restore events and simply don't do any rendering when app is minimized. With glfw that is used in opengl_example you can check if window is minimized with glfwGetWindowAttrib(window, GLFW_ICONIFIED) call (or handle glfwSetWindowIconifyCallback callback) and then use glfwWaitEvents function instead of glfwPollEvents function.

**Comment by jvcleave** [comment]
ok - this really helped the opengl_example

```
// Main loop
    while (!glfwWindowShouldClose(window))
    {
    if(!glfwGetWindowAttrib(window, GLFW_ICONIFIED))
    {
    	glfwPollEvents();
        ImGui_ImplGlfw_NewFrame();

        // 1. Show a simple window
        ...
    }else
    {
    	glfwWaitEvents();
    }
...

```

Thanks!

**Comment by jvcleave** [comment]
ok - this really helped the opengl_example

```
// Main loop
    while (!glfwWindowShouldClose(window))
    {
    if(!glfwGetWindowAttrib(window, GLFW_ICONIFIED))
    {
    	glfwPollEvents();
        ImGui_ImplGlfw_NewFrame();

        // 1. Show a simple window
        ...
    }else
    {
    	glfwWaitEvents();
    }
...

```

Thanks!

**Comment by ocornut** [comment]
By default the example app don't request vsync (though it is generally the default) because I use them to measure performances and run at max speed. So on any situation where vsync is off by default you would get a processing hogging one CPU.

I'll see about adding something like this to the OpenGL examples.

**Comment by hsandt** [comment]
Thanks for the fix. I still had issues with windows that are not minimized but hidden below other windows, so I ended up using `if(glfwGetWindowAttrib(window, GLFW_FOCUSED))` instead of `GLFW_ICONIFIED` (note the condition is now positive). Note that the app would be refreshed when it is visible but not focused.

There is also some OSX-specific things going on here (AppNap it seems), see:
- http://stackoverflow.com/questions/23550423/high-cpu-usage-when-glfw-opengl-window-isnt-visible
- https://github.com/glfw/glfw/issues/680

**Comment by audioplastic** [comment]
Filthy hack of the century for anyone looking here with a similar issue they want a bandaid for

```
if (ImGui::GetIO().Framerate > 61.f) {
    std::this_thread::sleep_for(std::chrono::milliseconds(200)); // drop to 5 FPS when invisible
}
```
