### ISSUE TITLE
Exception thrown at 0x00E67CE5

### ISSUE THREAD

**Issue by AnnoyingB** [ocornut/imgui#4406]
I have some code and when running, get an Exception thrown at 0x00E67CE5. It shows the line:
``` cpp
253  g_PrevUserCallbackMousebutton = glfwSetMouseButtonCallback(window, ImGui_ImplGlfw_MouseButtonCallback);
```

I am not sure if it has something to do with the window hints I have set:

``` cpp
glfwWindowHint(GLFW_VERSION_MAJOR, 3);
glfwWindowHint(GLFW_VERSION_MINOR, 3);
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
```

**Comment by PathogenDavid** [comment]
There's not really enough information here for us to be able to help you. What type of exception are you getting?

Make sure the window pointer you're passing to the backend isn't null.

**Comment by AnnoyingB** [comment]
0xC0000005: Access violation reading location 0x00000284.

**Comment by AnnoyingB** [comment]
Also, it is in the file imgui opengl glfw file

**Comment by PathogenDavid** [comment]
A crash in a Dear ImGui file does not necessarily make it Dear ImGui's fault. You're almost certainly passing an invalid window pointer to `ImGui_ImplGlfw_InitForOpenGL`.

**Comment by AnnoyingB** [comment]
Hmm, it is null. odd. How would I fix it because it only works when I remove the hints.

**Comment by AidanSun05** [comment]
Your GLFW window hints are differing from what's shown in the example (which is proven to work). Try replacing your hints with:

https://github.com/ocornut/imgui/blob/f99fe72c42bd5d578c2443409192b139b1c6623d/examples/example_glfw_opengl3/main.cpp#L62-L82

If this still doesn't work, check out these StackOverflow questions:
https://stackoverflow.com/q/25903855 (TL;DR: Check your window hints - related to the above fix.)
https://stackoverflow.com/q/30148989 (TL;DR: Update your graphics driver.)

If this STILL doesn't work, it's because you're not giving enough information to debug this issue - submit a screenshot and a call stack to investigate further.

**Comment by AnnoyingB** [comment]
Thanks!

**Comment by FrankRuben** [comment]
Whoever comes here, searching for this error when trying to run `example_glfw_opengl3` in WSL2: In my case that error went away when starting the test using:

``` shell
LIBGL_ALWAYS_INDIRECT=0 ./example_glfw_opengl3
```

More details here: https://stackoverflow.com/a/66506098
