### ISSUE TITLE
Mac os x.  Some problem with opengl_example and opengl3_example.

### ISSUE THREAD

**Issue by GarryDvaraza** [ocornut/imgui#441]
Hello. I clone master branch of your imgui project, and I tried to make exmaple program "opengl_example"  but I got this.
Best regards.
<img width="844" alt="2015-12-15 19 51 21" src="https://cloud.githubusercontent.com/assets/9413534/11819297/256896ea-a370-11e5-900e-fbfb51d86698.png">

**Comment by ocornut** [comment]
Looks like a problem with the clipping rectangles. What happens when you move the windows? What is the FramebufferScale value in the IO structure?

**Comment by GarryDvaraza** [comment]
I print FramebufferScale.x and FramebufferScale.y:  402 and -113424224.....
<img width="181" alt="2015-12-15 22 59 27" src="https://cloud.githubusercontent.com/assets/9413534/11822446/8e35e8e4-a37f-11e5-8693-16e56fde1b4a.png">

Debug window is cut, when i move it right.

Best regards and sorry for my english.

**Comment by GarryDvaraza** [comment]
OMAR! I downloaded version 1.43 from release and it work fine %)
<img width="650" alt="2015-12-15 23 11 02" src="https://cloud.githubusercontent.com/assets/9413534/11822735/25cc3900-a381-11e5-899a-72a8fdc78455.png">

**Comment by GarryDvaraza** [comment]
Omar, I test one thing. I copy opengl_example folder from 1.46 version release to master, I compile it and it work fine. Maybe opengl_example project from master have error?

**Comment by ocornut** [comment]
Can you step in your debugger in those lines of ImGui_ImplGlfw_NewFrame() and check what are they values and what is wrong?

```
    int w, h;
    int display_w, display_h;
    glfwGetWindowSize(g_Window, &w, &h);
    glfwGetFramebufferSize(g_Window, &display_w, &display_h);
    io.DisplaySize = ImVec2((float)w, (float)h);
    io.DisplayFramebufferScale = ImVec2((float)display_w / w, (float)display_h / h);
```

**Comment by GarryDvaraza** [comment]
values: 
w h dispaly_w display_h : 1244 720 2488 1440
i dont know how to use gdb in mac os :( sorry Omar.  Maybe late, I'll can write good answer.

**Comment by Erkaman** [comment]
I also encountered this issue, and I have been able to fix it. 

To fix it, open the file `imgui_impl_glfw_gl3.cpp`, and find the function `ImGui_ImplGlfwGL3_RenderDrawLists`. In this function, locate the lines 

```C++
    // Handle cases of screen coordinates != from framebuffer coordinates (e.g. retina displays)
    ImGuiIO& io = ImGui::GetIO();
    float fb_height = io.DisplaySize.y * io.DisplayFramebufferScale.y;
    draw_data->ScaleClipRects(io.DisplayFramebufferScale);

    // Setup viewport, orthographic projection matrix
    glViewport(0, 0, (GLsizei)io.DisplaySize.x, (GLsizei)io.DisplaySize.y);
```

and simply replace this with this

```C++
    // Handle cases of screen coordinates != from framebuffer coordinates (e.g. retina displays)
    ImGuiIO& io = ImGui::GetIO();
    float fb_height = io.DisplaySize.y * io.DisplayFramebufferScale.y;
    float fb_width = io.DisplaySize.x * io.DisplayFramebufferScale.x ;

    draw_data->ScaleClipRects(io.DisplayFramebufferScale);

    // Setup viewport, orthographic projection matrix
    glViewport(0, 0, (GLsizei)fb_width, (GLsizei)fb_height);

```

and this solves the problem:

<img width="1272" alt="screen shot 2015-12-17 at 20 44 19" src="https://cloud.githubusercontent.com/assets/602313/11880025/06fd7b18-a4ff-11e5-910b-82e3db511742.png">

The issue with the original code was that the viewport was set to the size of the window. But the viewport should have been set to the size of the framebuffer, clearly. Otherwise, it would not work on a retina display, since in the case of a retina display the framebuffer is twice the size of the window.

**Comment by GarryDvaraza** [comment]
Erkaman, ty very much!

**Comment by ocornut** [comment]
Thanks for the fix. I made that change fairly recently in https://github.com/ocornut/imgui/commit/980ca286fe3a01ea9c66918f6d51eaaf6dee2dd6 and that broke it for high-DPI screens which I hadn't tested. Fixing now.

**Comment by ocornut** [comment]
I am a little confused at the screenshot @GarryDvaraza provided at the top of this thread. It doesn't appear to be strictly a glViewport issue since you can see windows background where there is missing text, but rather an issue with the position of the clipping rectangle.

Garry can you confirm that the latest master fixes it for you?

Thanks again @Erkaman !

**Comment by Erkaman** [comment]
The latest fixes works for me.

**Comment by GarryDvaraza** [comment]
@ocornut yes:) it is fixes.
ty very much @Erkaman  and @ocornut
