### ISSUE TITLE
Attempting to add new style type.

### ISSUE THREAD

**Issue by Stanlyhalo** [ocornut/imgui#4429]
Version: 1.83
Branch: docking

**My Issue/Question:** How can I add a new style type to the ImGui::PushStyleVar?

So I change how borders are styled for a button using an ImVec4 for each side size, and it works, so then I wanted to make it so the ImVec4 border size is defined via the push style var, I went ahead and added a new item to the `struct ImGuiStyle` using the type ImVec4, I then added a new item to the `enum ImGuiStyleVar_` called the same thing. After that, I added a new method to `imgui.h`, which is: `IMGUI_API void          PushStyleVar(ImGuiStyleVar idx, const ImVec4& val);`, and this is the code for that function:
```cpp
void ImGui::PushStyleVar(ImGuiStyleVar idx, const ImVec4& val)
{
    const ImGuiStyleVarInfo* var_info = GetStyleVarInfo(idx);
    if (var_info->Type == ImGuiDataType_Float && var_info->Count == 2)
    {
        ImGuiContext& g = *GImGui;
        ImVec4* pvar = (ImVec4*)var_info->GetVarPtr(&g.Style);
        g.StyleVarStack.push_back(ImGuiStyleMod(idx, *pvar));
        *pvar = val;
        return;
    }
    IM_ASSERT(0 && "Called PushStyleVar() ImVec4 variant but variable is not a ImVec2!");
}
```
And so after all that, I thought it would work, but I ended up getting a compiler error (I think) that just stated:
`The program '[16556] engine.exe' has exited with code -1073741502 (0xc0000142) 'DLL Initialization Failed'.`

Edit*: Also forgot to mention I added this to the `imgui_internal.h` file:
```hpp
ImGuiStyleMod(ImGuiStyleVar idx, ImVec4 v) { VarIdx = idx; BackupFloat[0] = v.x; BackupFloat[1] = v.y; BackupFloat[2] = v.z; BackupFloat[3] = v.w; }
```
And yes, I did update the BackFloat to take 4 in the array instead of 2 as the default.

**Comment by thedmd** [comment]
Yours `ImGui::PushStyleVar` has at least two bugs. `var_info->Count == 2` should compare to `4.`. Assert incorrectly mention `ImVec2` instead of `ImVec4`.

After adding variable to `enum ImGuiStyleVar_`, you also need to add appropriate entry to `GStyleVarInfo` array in `imgui.cpp`.

Next thing to do is to patch implementation of the button widget to use your new style variable.

Crash is probably caused, because your program (or DLL ImGui is in) didn't compiled and old version was used. Part of your program compiled with new imgui.h header, part did not. Compilation should fail on `IM_ASSERT(IM_ARRAYSIZE(GStyleVarInfo) == ImGuiStyleVar_COUNT);` which guards you from making a mistake of not patching `GStyleVarInfo` in the first place.

**Comment by Stanlyhalo** [comment]
So I fixed the 2 to a 4, and this it it:
```cpp
void ImGui::PushStyleVar(ImGuiStyleVar idx, const ImVec4& val)
{
    const ImGuiStyleVarInfo* var_info = GetStyleVarInfo(idx);
    if (var_info->Type == ImGuiDataType_Float && var_info->Count == 4)
    {
        ImGuiContext& g = *GImGui;
        ImVec4* pvar = (ImVec4*)var_info->GetVarPtr(&g.Style);
        g.StyleVarStack.push_back(ImGuiStyleMod(idx, *pvar));
        *pvar = val;
        return;
    }
    IM_ASSERT(0 && "Called PushStyleVar() ImVec4 variant but variable is not a ImVec4!");
}
```
I also added the appropriate entry into `GStyleVarInfo`, and it still causes that error. I also did a rebuild of my code to see if that was the issue, the same error still happens.

**Comment by thedmd** [comment]
You can try to narrow down the scope by commenting out the use of new feature you added and see if your DLL will load correctly. If that do not help you may try to apply your changes gradually. I mean get back to the state from before the changes, verify if that works ok, and apply your diff in small but consistent bites checking between every change.

These are usual suspects for DLL failing to load:
1. DLL dependencies were not found (wrong working directory, missing dll, etc.)
2. statically initialized objects caused segmentation fault (plain bug in the code, which cause app to crash but since it is a dynamically loaded dll, just dll failed)
3. DllMain returned by error

**Comment by Stanlyhalo** [comment]
Okay I think I just found the problem xD. When I went to open notepad, a lot of text was messed up, so was taskmanager, so I restarted my laptop, and re-opened the project, and bam, it works lol, I just messed something up on my system and it needed a restart, that's all xD.
