### ISSUE TITLE
You can use GDI to draw texts on the windows

### ISSUE THREAD

**Issue by KnIfER** [ocornut/imgui#4448]
On the windows, instead of using the fallback-glyph `?`, you can use GDI to draw the texts that are not supported by the imgui-font. 

Chinese? Korean? Japaness? Russian? No Problem!
 
![image](https://user-images.githubusercontent.com/11593903/130214716-7f4f163b-64b8-49d7-8cbf-13b546574494.png)

**Comment by PathogenDavid** [comment]
Using GDI to draw over a DXGI swap chain is a bad idea, it forces Windows to use a slower legacy presentation path for your app. If you really want to do this you should at least use DirectWrite, which is designed for text rendering within DirectX apps.

Either way neither solution is going to be suitable for Dear ImGui because they're Windows-centric.

The current long-term plan is to make it so Dear ImGui can update the font atlas dynamically as new characters are needed.

**Comment by ocornut** [comment]
It looks like an interesting trick to be honest. As David said I don't imagine it would be a candidate for merging in master, but I'd be curious to see how it is implemented and actual performances.

**Comment by KnIfER** [comment]
It's very simple...

1. I modified the message loop to put paint-things under the WM_PAINT message. ( so that the CPU rate could drop to 0% when the mouse don't move or when the main window is minimized. )
2. replace 
```
// Decode and advance source
unsigned int c = (unsigned int)*s;
...
vtx_write[0].pos.x = x1; ...
vtx_write[1].pos.x = x2; ...
...
```
 with 

```
// Decode and advance source
unsigned int c = (unsigned int)*s;

TCHAR tmp[]{c, '\0'};
::TextOut(hdc, x, y, tmp, 1);
```

drawbacks:
- It will comsume more CPU with the lame double-buffering
- , and will still flicker sometimes.
- and the clipping is not right when you have two overlapping imgui windows.




[mix_hdc_text_out ( source ).zip](https://github.com/ocornut/imgui/files/7021189/mix_hdc_text_out.source.zip)

**Comment by ocornut** [comment]
I didn't realize GDI was usable so easily "from anywhere" I admit this is quite cool.

**Comment by ocornut** [comment]
While I think this is quite a cool feat, I'm not really sure what we can do with it presently (due to issues mentioned above) so I'm going to close this. If you can think of a way to make production-quality use of this let us know!

It reminded me that I saw someone drive a color picker by simply calling `::GetPixel()` the same way, and it'll just work.
