### ISSUE TITLE
Text color of disabled menu item is incorrect

### ISSUE THREAD

**Issue by paladin-t** [ocornut/imgui#4478]
**Version/Branch of Dear ImGui:**

Version: 1.84.2
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: any
Compiler: any
Operating System: any

**My Issue/Question:**

```c++
bool ImGui::MenuItemEx(const char* label, const char* icon, const char* shortcut, bool selected, bool enabled)
{
	...
	if (!enabled)
		BeginDisabled(true);
	...
	RenderText(...);
	...
	if (!enabled)
		EndDisabled();
	...
}

void ImGui::RenderText(ImVec2 pos, const char* text, const char* text_end, bool hide_text_after_hash)
{
	...
	window->DrawList->AddText(g.Font, g.FontSize, pos, GetColorU32(ImGuiCol_Text), text, text_display_end);
	...
}
```

It always uses `ImGuiCol_Text`.

**Comment by ocornut** [comment]
As per #211 we introduced a general purpose "Disabled" mode and this introduced a little inconsistency.
`MenuItem()` are using `ImGuiCol_Text` + the Disabled modifier (`style.DisabledAlpha`).

This makes the existence of `ImGuiCol_TextDisabled` a little odd and maybe to be reworked/removed/redesigned.

I presume you are having an issue because your value for `ImGuiCol_TextDisabled` was e.g. using a different Hue than your value for `ImGuiCol_Text` ? How do things look in your style?
