### ISSUE TITLE
Assertion failed: remaining >= 0 && remaining < g.OpenPopupStack.Size, ......\imgui-sys-0.7.0\./third-party/imgui/imgui.cpp, line 8026

### ISSUE THREAD

**Issue by selassje** [ocornut/imgui#4510]
**Version/Branch of Dear ImGui:**

Version: 1.80

**Back-end/Renderer/Compiler/OS**

Back-ends: openGL + sdl2
Compiler: msvc/emscripten
Operating System: win10/wasm32

**My Issue/Question:**

I am getting this assertion when KEYBOARD NAVIGATION is enabled, tab is selected and left arrow is pressed. I am using imgui-rs. Not sure if the problem is in imgui-rs or in the imgui itself.

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
go to https://selassje.github.io/nes-rs/
click controllers -> setup
click on one of the tabs
press left arrow

There should be an exception in the developer tools visible

**Comment by PathogenDavid** [comment]
C++ repro: (I used the `v1.84.2` tag)

```cpp
static void GH4510()
{
    static bool controllers_setup = false;

    ImGui::SetNextWindowSize(ImVec2(600, 600));
    ImGui::Begin("GH-4510", nullptr, ImGuiWindowFlags_MenuBar);

    if (ImGui::BeginMenuBar())
    {
        if (ImGui::BeginMenu("Controllers"))
        {
            if (ImGui::BeginMenu("Setup"))
            {
                if (ImGui::BeginChild("Controllers Setup", ImVec2(230.f, 230.f), true))
                {
                    if (ImGui::BeginTabBar("Players"))
                    {
                        if (ImGui::BeginTabItem("Player 1"))
                        {
                            ImGui::EndTabItem();
                        }

                        if (ImGui::BeginTabItem("Player 2"))
                        {
                            ImGui::EndTabItem();
                        }

                        ImGui::EndTabBar();
                    }
                }
                ImGui::EndChild();

                ImGui::EndMenu(); // <-- Crashing call
            }

            ImGui::EndMenu();
        }

        ImGui::EndMenuBar();
    }

    ImGui::End();
}
```

The child window within the menu seems to be the exasperating factor here. (Although without it, the navigation unexpectedly closes the menu instead of moving between tabs.)

I'm not super familiar with the navigation system internals, but it seems like it's trying to handle the left navigation as a menu close even though it should be handled as navigating left in the tab bar. It only happens sometimes, if something else was navigated to before moving to the tabs it works fine.

The navigation works as expected if I comment out these two lines:

https://github.com/ocornut/imgui/blob/e3e1fbcf025cf83413815751f7c33500e1314d57/imgui_widgets.cpp#L6974-L6975

(Obviously that breaks the `left-to-close-menu` feature though.)

When the assert would've failed, the navigation is handled by `NavUpdateInitResult` (called from `NavUpdate`). In cases where the assert doesn't fail (and the menu doesn't close unexpectedly), the navigation change is handled by `NavUpdateMoveResult` instead.

It seems to me like there's some interaction between the initial navigation request and that `EndMenu` logic which is not being accounted for.

**Comment by ocornut** [comment]
The idea is that _first_ menu normally request the _second_ menu (the one with the child) to close if a LEFT keypress in the _second_ menu failed to find a match. 

Since LEFT inside a child doesn't exit the child (unless `ImGuiWindowFlags_NavFlattened` is set), the "correct" fix would make that LEFT keypress do nothing in this situation. It wouldn't be correct nor consistent to close the menu. Imagine if that menu had two childs layed horizontally and you press LEFT inside the right-most child it would be incorrect that it closed the menu. So I'm going to fix this (it'll be a no-op in this situation)

But this leaves us with the question: **why creating a child** inside the here?! It doesn't seem meaningful?
@selassje did you code ressemble the repro that @PathogenDavid created? Or would your repro be different?
I can't find that code at https://github.com/selassje/nes-rs

**Comment by ocornut** [comment]
Pushed fix 17a7084b57f9713ec6538881079d6c5a1b6b3598
Thanks @PathogenDavid and @rokups for further inspections.

@selassje Even if this is fixed would be worth clarifying why you had a BeginChild/EndChild couple in here?

**Comment by selassje** [comment]
Thanks @ocornut 

The code which builds the tabs:

https://github.com/selassje/nes-rs/blob/ab2e22dcabd3c8dc40f1c1b2fbab411848059959/src/io/io_sdl2_imgui_opengl/gui_builder.rs#L405

Are you saying I don't need the child window here?

**Comment by ocornut** [comment]
I don't really understand the purpose of a child window here. A child window is designed to created a scrolling region.

I can only imagine that you added it as a way to enforce a fixed and minimum size for the menu, because the auto-sizing of the tab-bar and this contents wasn't satisfactory?

In this case you can call `SetNextWindowSize()` (or `SetNextWindowSizeConstraints()`) before `BeginMenu()`,
or inside `BeginMenu()` you can move the cursor to a dummy position and that will also affect the minimum size of the menu, e.g. 
```
ImVec2 p = GetCursorPos()
SetCursorPos(p + my_size);
SetCursorPos(p)
```

**Comment by ocornut** [comment]
> In this case you can call `SetNextWindowSize()` (or `SetNextWindowSizeConstraints()`) before `BeginMenu()`, or inside `BeginMenu()` you can move the cursor to a dummy position and that will also affect the minimum size of the menu, e.g.
> ```
> ImVec2 p = GetCursorPos()
> SetCursorPos(p + my_size);
> SetCursorPos(p)
> ```

The message above (2021/09/10) suggested an incorrect usage pattern which we had to obsolete in 1.89. An item (even a `Dummy()` needs to be submitted to extend boundaries). See #5548 for details.
