### ISSUE TITLE
Contrast style ( colors )

### ISSUE THREAD

**Issue by green-zone** [ocornut/imgui#453]
When i create Contrast color for Title, Header, Button, It makes the text unreadable.
Light coloured style - Dark coloured elements. And vice versa.
May be need easy way setup separate colors (instead default color) for text in elements
Like SetTextColor for them.

![contrast style](http://i.piccy.info/i9/ba82272ba4712f1f5f92f0770755c591/1450983539/64727/912050/contrast.jpg)

**Comment by green-zone** [comment]
On this screenshot text so far readable. But, if i do headers more dark ...

**Comment by ocornut** [comment]
The problem if we added text color entries for all those sort of background it would make theme editing much more tedious, if we consider the Hovered/Active variants of all Bg colors that would that ~12 extra colors, double that if we want to add entries for TextDisabled. Ignoring Hovered/Active variant would make more sane, maybe around 5-7 extra colors.

Also consider that ImGuiCol_Header is used for those collapsing headers, but ImGuiCol_HeaderHovered/ImGuiCol_HeaderActive is also used for tree nodes, and it would be too distracting if the text color changed while you hovered tree nodes.

The solution is probably that we want to converge toward exposing something like the simplified styling helper in #438. For now and because I expect to slowly evolve the visual style over the next year I would suggest not trying to use theme with such variety of contrast.

**Comment by green-zone** [comment]
OK, thanks for answer.

**Comment by itamago** [comment]
I partially agree with the explanation.
It's true that multiplying text colours would be a mess :)

But, there is a middle solution which would be to add only 2 text colours : Text, TextDisabled, TextHovered (NEW), and TextActive (NEW).
With that, it would become possible to use high contrast GUIs.

It relies on 2 new colours only, and it would be consistent with the widget states.

My 2 cents..

**Comment by ocornut** [comment]
I'm open to anything but this work has to be done holistically. More an anything I'm open to somebody just submitting improving style settings that works. Considerate of use of transparency. Possibly considerate of finding a way to express simplified styling as well. Considerate of desirable missing features (many of which have a thread here).

I have added a new Style tag https://github.com/ocornut/imgui/issues?q=is%3Aopen+is%3Aissue+label%3Astyle

**Comment by itamago** [comment]
I'm new to ImGui, and I spent few hours building test GUIs in order to feel the limitations. 
In my use-cases (mainly debug purpose), I found only two limitations which irritate me a little bit : text alignment which must be done manually, and text color. The second one could be handled pretty easily with basic styling. The first one seems more complex..

I'll look into the text colors during the weekend.

You're right, styling is a very complicated topic..

**Comment by ocornut** [comment]
What sort of text alignment were you thinking about exactly? I agree we need to add more options for that but usually there's also a way to create things without, if you don't let style dictate your layout too much. 

I'd like better styling but to be frank without the developing force I also feel it will be the little death of ImGui if more people start using it just because it looks cool, while the millions to-do items aren't done and I can't contain the growth. Each new minor styling thing has a side-effect somewhere. Each new user is a bit of overhead so I'm less and less inclined to attract users at all. Secretly considering making it look worse sometimes. :)
