### ISSUE TITLE
ImGui Docking Resize Issue

### ISSUE THREAD

**Issue by argon-projects** [ocornut/imgui#4530]
Hey, I have a problem with the ImGui Docking Branch:

When I change the size / position of a window all docked windows are simply kicked out of the window where they were docked. is there a way to fix this?

to change the size / pos of my window i use this code:
![image](https://user-images.githubusercontent.com/89998024/132961509-49d5463f-3e6b-4f44-abba-aa82681c9dc2.png)

**Comment by ocornut** [comment]
Changing the position of a window undocks it.
It makes sense otherwise multiple docked windows requesting their position would conflict.

It's not clear by you are forcing a window to fill a viewport while simultaneously allowing that window to be docked with others.

Perhaps you want an immovable host window carrying a dockspace? This is what `DockspaceOverViewport()` does.

**Comment by argon-projects** [comment]
Thanks for the fast Reply 👍 

I want my "Main" imgui window to fit with the correct windows window size and position. so i set it to the Main Viewport, when you can give me a better method for this, this can maybe fix it

**Comment by ocornut** [comment]
I don’t understand your message it is too ambiguous. Please read the Glossary and stick to correct terminology to reduce ambiguities.
If your dockspace cover the viewport then it shouldn’t be resizable?
