### ISSUE TITLE
[question] How to properly linear interpolate using time

### ISSUE THREAD

**Issue by AbbyIOM** [ocornut/imgui#4555]
----

**Version/Branch of Dear ImGui:**

Version: 18416
Branch: master

Operating System: Win 10

**My Issue/Question:**

How do i properly lerp using time, my current method doesn't work so well and it's the best one i came up with.

It works "fine" when i wait till it gets to the final value but if i press the button before that it gets weird.
My goal is to get from point A to point B at a given time using lerp.

**Screenshots/Video**

https://user-images.githubusercontent.com/89664487/133931392-71e88ac8-7fa3-4fdc-b833-e55d9acf94cd.mp4

```
// Here is the code 

            static bool move;
            static float moveTo, elapsedTime;
            const float duration = 1.0f;



            if (ImGui::Button("Lerp circle"))
                move = !move;


            draw_list->AddRectFilled(ImVec2(p.x + 10 + moveTo, p.y + 30), ImVec2(p.x + 60 + moveTo, p.y + 80), IM_COL32(255, 255, 255, 220), 50);


            if (move) {

                if (elapsedTime <= duration && moveTo <= 98) {

                    moveTo = lerp(0, 100, elapsedTime / duration);
                    elapsedTime += io.DeltaTime;

                }
                else
                    elapsedTime = 0;

            }

            if (!move) {

                if (elapsedTime <= duration && moveTo >= 2) {
                    moveTo = lerp(100, 0, elapsedTime / duration);
                    elapsedTime += io.DeltaTime;

                }
                else 
                    elapsedTime = 0;

            }
```

**Comment by PathogenDavid** [comment]
This is more of a general programming/math question than a Dear ImGui question, but thanks for filling out the issue template!

I think you're overthinking things here. The crux of the issue is that you use `elapsedTime` as as an ever-increasing value for both movement directions. However `elapsedTime` == 0.25 when moving right (`move` is `true`) and 0.25 when moving right (`move` is `false`) do not represent the same position, so when `move` changes the circle suddenly jumps.

I think you're focusing too much on the `t` parameter to `lerp` representing time rather than an abstract value representing the interval along the line you're interpolating across.

(As an aside, it's worth knowing there's a dedicated `AddCircleFilled` function for drawing circles.)

------------

I would write it like this:

```cpp
ImDrawList* draw_list = ImGui::GetWindowDrawList();
ImGuiIO& io = ImGui::GetIO();

static float moveDirection = -1.f;
static float moveT = 0.f;
const float speed = 1.f;

if (ImGui::Button("Reverse direction"))
    moveDirection = -moveDirection;

// Animate t
moveT += moveDirection * io.DeltaTime * speed;
if (moveT < 0.f)
    moveT = 0.f;
else if (moveT > 1.f)
    moveT = 1.f;

// Draw the circle
ImVec2 offset = ImGui::GetCursorScreenPos();
const float radius = 25.f;
draw_list->AddCircleFilled(ImVec2(offset.x + radius + lerp(0.f, 100.f, moveT), offset.y + radius), radius, IM_COL32(255, 255, 255, 220));
```

**Comment by AbbyIOM** [comment]
Thank you! My brain started sizzling before, but as im looking at it now it makes much more sense, i really appreciate your help!
