### ISSUE TITLE
Aspect Ratio

### ISSUE THREAD

**Issue by nvinci** [ocornut/imgui#4556]
Version: v1.85
Branch: master

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Operating System: Windows

I was wondering if it's possible to get the same aspect ratio as before when resizing the host window, and how?

Notice that the example window is still at the same position as before, I'd like the example window to reposition itself according to the host window's size.
https://streamable.com/b4dfj1

**Comment by ocornut** [comment]
In your app when you detect a host window change you could technically loop over all imgui windows (using `imgui_internal.h`) and alter their position and size:

```
for (int window_n = 0; window_n < g.Windows.Size; window_n++)
{
   ImGuiWindow* window = g.Windows[window];
   ImGui::SetWindowPos(window, window.Pos * scale_factor);
   ImGui::SetWindowSize(window, window.Size * scale_factor);
}
```

**Comment by ocornut** [comment]
In docking branch there is a function `ScaleWindowsInViewport()` which does exactly that and which is used on DPI change. We could backport this function to master easily.

However, in your specific case it is quite ambiguous how you would want things to react considering the fact that the host window can be resized in a non-uniform manner, therefore there's no "right" way to move/rescale windows, and each resize is a lossy operation because of the pos/size rounding involved, so it wouldn't work with all form of host window resize implementation.

**Comment by nvinci** [comment]
Hey, I'm sorry for the late response.
I figured out a hacky way to do this
there it is
at ImGui::Begin()
```CPP
static auto last_display_size = g.IO.DisplaySize;
	{
		if(last_display_size.x != g.IO.DisplaySize.x || last_display_size.y != g.IO.DisplaySize.y)
		{
			for(auto &w : g.Windows)
			{
				const auto size = w->Size;
				auto pos = w->Pos;
				const auto diff_bottom = (pos.y + size.y) - g.IO.DisplaySize.y;
				const auto diff_right = (pos.x + size.x) - g.IO.DisplaySize.x;
				if(diff_right > 0.f) pos.x -= diff_right;
				if(pos.x < 0.f) pos.x = 0.f;
				if(pos.y != 0.f && diff_bottom > 0.f) pos.y -= diff_bottom;
				if(pos.y < 0.f) pos.y = 0.f;
				ImGui::SetWindowPos( w, pos );
			}
			last_display_size = g.IO.DisplaySize;
		}
	}
```
but I'll take a look at your solution anyway, thank you so much.
