### ISSUE TITLE
Question : TreeNode + colums

### ISSUE THREAD

**Issue by krys-spectralpixel** [ocornut/imgui#460]
Hi,

I try to have a multi-colums tree, and here is what I got for now :+1: 
![tree](https://cloud.githubusercontent.com/assets/6149696/12026033/2e719558-adb5-11e5-80b7-0cd2b6abec74.png)

There are 3 problems:
- all the "locked" icons are not aligned on the same colums
- The column only appear for the last node
- how can I set the default column position for the lock icon ?

Here is my code :
```
ImGui::Columns(2, "tree items");

ImGui::TreeNode(...);

ImGui::NextColumn();

ImGui::PushFont(GetIconFont());
ImGui::TextUnformatted(UIStyle::Icon_Lock.c_str());
ImGui::PopFont();
```

Thanks

**Comment by ocornut** [comment]
This was fixed a few weeks ago, afaik. Are you using latest?

1.47
> Columns: Fixed bug with indentation within columns,

**Comment by ocornut** [comment]
> The column only appear for the last node

Hard to tell why, the code you posted is incomplete. Maybe you are calling `Columns(2)` multiple time and that reset the start Y position of the columns set?

> how can I set the default column position for the lock icon ?

You can use `SetColumnOffset()`. However if the only thing you are doing here is displaying an Icon Lock and you don't aim to resize the column much, using `SameLine(xxx);` instead of columns may just be simpler and faster.

**Comment by krys-spectralpixel** [comment]
Right, same line do the trick. Thanks Omar !
