### ISSUE TITLE
Assertion error "Need a positive DeltaTime!" and freezing bugs when hooking QueryPerformanceCounter()

### ISSUE THREAD

**Issue by BullyWiiPlaza** [ocornut/imgui#4680]
**Version/Branch of Dear ImGui:**

Version: 1.84.2 installed via vcpkg

**Back-end/Renderer/Compiler/OS**

Back-ends: `imgui_impl_win32.cpp` + `imgui_impl_win32.cpp`
Compiler: MSVC
Operating System: Windows 11

**My Issue/Question:**

Hi, I made an option which hooks `QueryPerformanceCounter()` via e.g. Microsoft Detours to provide a time speed multiplier. In ImGui I'm using a `SliderFloat()` to supply the value:
`ImGui::SliderFloat("Speed Hack", &time_speed_multiplier, 0.1f, 10.f);`

When I increase the speed up, it's all good. However, when I decrease the speed up, I either get a temporary freeze of the process or I get an assertion error saying `Need a positive DeltaTime!`.

Now the question arises why this happens exactly and whether the freeze or assertion can be fixed so that I can use this hook without any issues to provide a speed up? What would be a good way to deal with this?

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/7620135/139476839-c3e338d8-7593-431c-bf33-add6e48a40fd.png)

**Comment by ocornut** [comment]
I guess you would need to make the backend pass in a minimum `io.DeltaTime` value when the calculation gets a zero:

`io.DeltaTime = (float)(current_time - bd->Time) / bd->TicksPerSecond;`

So something like:
`if (io.DeltaTime <= 0.0f) io.DeltaTime = 0.00001f`
Or technically speaking I suppose it could be based on `bd->TicksPerSecond`, eg. using `1.0f / bd->TicksPerSecond`
Which you can either do in the backend or in your code, just before calling `ImGui::NewFrame()`.

This is perhaps going to makes dear imgui's perception of time slightly incorrect but it's unlikely going to matter.

**Comment by rokups** [comment]
Correct answer is: sorry, but #1586 :)

**Comment by IoIxD** [comment]
This comment potentially has nothing to do with QueryPerformanceCounter, but this happens to be the first result on Google for the "Need a positive DeltaTime!" error, and because this was asked by a cheater it never got a real response. So I want to give my two cents for how I solved this for anyone who might be here.

If you're in the situation I am, there's a really good chance that you can just check if DeltaTime is 0 and set it to something above 0 (in my case, I was still getting an error so I set FrameCount to 0 and FrameCountEnded to -1, an abominable solution but one that did in fact work).

```cxx
auto io = igGetCurrentContext();
auto ctx = igGetIO();
if io.DeltaTime <= 0.0 {
    ctx.FrameCount = 0;
    ctx.FrameCountEnded = -1;
}
```
