### ISSUE TITLE
Metal C++ Backend/Examples

### ISSUE THREAD

**Issue by timmg** [ocornut/imgui#4746]
Feature request: 

Develop backend/examples for Metal over C++.

https://developer.apple.com/metal/cpp/

**Comment by ocornut** [comment]
What would be the added value and why not using the existing backend that is already provided, since Apple toolchains supports both languages?

**Comment by thedmd** [comment]
@timmg 
FYI: Wrapper is available here <https://github.com/bkaradzic/metal-cpp>.

**Comment by metarutaiga** [comment]
Metal use C++ is bad idea, it lost ARC feature and make codes dirty.
If you want write C++ files only (ex: cc or cpp), you can add compiler flag to enable Objective-C.
```
COMPILER_FLAGS = "-x objective-c++ -fobjc-arc -fobjc-weak -fmodules"
```
Unreal is using mtlpp, but it's difficult to add new features without Objective-C.
Finally, it can't pass Objective-C because Metal is Objective-C.

**Comment by ocornut** [comment]
I'm closing this until there's an argument for why we would need that additional back-end.
I understand it is good move for Apple to provide that as many apps/engines are purely C++ based and the interop can require extra work, but AFAIK once we do have an Objective-C version we don't need a second one.
