### ISSUE TITLE
Q: Mandantory to cast to intptr_t?

### ISSUE THREAD

**Issue by vexe** [ocornut/imgui#477]
Greetings!

First many thanks for this awesome library! I never use 3rd party libraries. But this is just a no-brainer, huge bang for the buck, tons of awesome features, small overhead, single-header files, examples that _actually works_, etc. Great job sir!

This is more a question than an issue, so we have this code:

glGenTextures(1, &g_FontTexture);
// glBindTexture, glTexParameter, etc
io.Fonts->TexID = (void *)(intptr_t)g_FontTexture;

My question is about the cast to intptr_t. If I remove that and do (void *)&g_FontTexture all my GUI goes black. I tried to look what intptr_t is mapped to, in some locations it seems it's 'int', in others it's 'long int' - so it's long enough to hold a pointer. But the cast (void *)(int)g_FontTexture (or long int for that matter) is obviously invalid. 

Must I cast to intptr_t? What's wrong with the cast (void *)&g_FontTexture?

Thanks!
vexe

EDIT: I guess another question, why store the TexID as a void*? why not unsigned int?

**Comment by ocornut** [comment]
ImTextureId is a void* because a void* can always hold a pointer whereas on a 64-bit system an int can't. It's just arbitrary user storage. Some engine/users will commonly want to store pointers to their own types. As it happens with OpenGL textures are identified with an int so in the OpenGL examples we store this int within the void* but it's probably an exception.

`(void *)&g_FontTexture` would take a pointer to said int, it would work if the pointer stays valid and the code in the render loop assume a pointer to int instead of an int. But it's just more practical to pass the int directly. The code in the `ImGui_ImplGlfw_RenderDrawLists` function matching the `ImGui_ImplGlfw_CreateDeviceObjects` assume that ImTextureId is an int.

`TexId = (void*)g_FontTexture;` would work as well but some C++ compilers with crazy warnings levels enable will warn that it is untypical to cast an int to a pointer and requires casting through a intptr_t just to explicitely tell the compiler you know what you are doing. So that extraneous cast is to ensure no warning with those compilers/settings.

`TexId = (void*)(int)g_FontTexture` wouldn't be invalid and in fact be the same as `(void*)g_FontTexture` since g_FontTexture is already an int. But it may trigger said warning on some settings.

**Comment by vexe** [comment]
Thanks for the quick reply. But it's still not clear to me what intptr_t is defined as. If I wanted to replace it, what would the replacement be? (assuming we're dealing with a 64-bit machine)

**Comment by ocornut** [comment]
It is defined as __int64 for visual studio 2010 in 64-bit.
It is part of c++ standard so you aren't supposed to replace it.
