### ISSUE TITLE
InputTextMultiline clear buffer

### ISSUE THREAD

**Issue by pp9999** [ocornut/imgui#4820]
Version/Branch of Dear ImGui:
Version: 1.83
Branch: docking
Visual studio 2022 +windows.

![buffer](https://user-images.githubusercontent.com/38459022/147067455-aaef8fc9-85fe-43b1-a557-5c0fc74e63ca.png)

So how can I clear that private buffer on command? So when program has accepted text it clears it. Is there any ImGui API commands or something.
Some code:
`char str_hold[2048];
ImGui::InputTextMultiline("list2", str_hold, 2048, ImVec2(150, 400));`

**Comment by pp9999** [comment]
I was looking around there and after looking demo. This should work right?
`
							struct Funcs
							{
								static int MyCallbacklist(ImGuiInputTextCallbackData* data)
								{
									cout << (int)data->EventFlag << endl;
									if (data->EventFlag == ImGuiInputTextFlags_EnterReturnsTrue) {
										cout << "Pressed Enter" << endl;
										data->DeleteChars(0, data->BufTextLen);
										data->InsertChars(0, "Pressed Enter!");
										data->SelectAll();
									}
									return 0;
								}
							};

							ImGui::InputTextMultiline("list2", str_hold, 2048, ImVec2(150, 400), ImGuiInputTextFlags_EnterReturnsTrue | ImGuiKey_DownArrow, Funcs::MyCallbacklist);` It doesn't

**Comment by AidanSun05** [comment]
You have a few misunderstandings, so be sure to read this comment in its entirety to understand what should be changed.

If you want to execute code when [Enter] is pressed, you have the right idea by setting `ImGuiInputTextFlags_EnterReturnsTrue`. However, with a multiline InputText, [Enter] is used to insert a new line, so you'll actually need to press [Ctrl+Enter] to trigger your callback code. *If you don't want this behavior, you should also set `ImGuiInputTextFlags_CtrlEnterForNewLine` which will swap the functionalities of [Enter] and [Ctrl+Enter]* (i.e. [Enter] triggers your callback, [Ctrl+Enter] inserts a new line).

In addition, note the return value of `InputTextMultiline` - it returns a `bool`. If you have the appropriate flags set, `InputTextMultiline` returns true on the frame that [Enter] is pressed. (For completeness, without `EnterReturnsTrue`, the textbox returns true every time its contents are modified.) Therefore, if you want a callback for the [Enter] key, *your callback should not be passed as a function pointer - instead, use the return value of the textbox as the condition for an if-statement, and put your callback in there.*

To clear the buffer, use a `memset` or `strcpy`/`strncpy` call with your char buffer as the target and an empty string as the source. You won't need `DeleteChars` since the callback for [Enter] doesn't need a dedicated function taking callback data. (Note: By the time you enter the if-statement or continue past the `InputTextMultiline` function call, the widget will no longer be active, so you're free to do whatever you want with the buffer.)

(Another note: `str_hold` should be `static` so your textbox contents aren't cleared when the user de-focuses from it. You should also initialize it, since it'll most likely contain garbage values without proper initialization.)

**Complete Code:**

```cpp
static char str_hold[2048] = "";

// The textbox flags. This will make `InputTextMultiline` return true when [Enter] is pressed.
ImGuiInputTextFlags flags = ImGuiInputTextFlags_EnterReturnsTrue | ImGuiInputTextFlags_CtrlEnterForNewLine;

if (ImGui::InputTextMultiline("list2", str_hold, 2048, ImVec2(150, 400), flags)) {
    // The code in this if-statement only executes when [Enter] is pressed.
    cout << "Pressed Enter" << endl;

    // Clear the buffer
    strncpy(str_hold, "", 2048);
}
```

**Comment by pp9999** [comment]
Thank you for help. That `ImGuiInputTextFlags_CtrlEnterForNewLine` was a thing I was looking for. With it `InputTextMultiline` clears internal buffer and returns true when enter is pressed. That `strncpy(str_hold, "", 2048);` is not needed as it is flushed every time my code exits this scope.

**Comment by AidanSun05** [comment]
> With it `InputTextMultiline` clears internal buffer and returns true when enter is pressed. That `strncpy(str_hold, "", 2048);` is not needed as it is flushed every time my code exits this scope.

That's because `str_hold` isn't `static`. There's a big comment at the top of the demo code explaining static variables:

https://github.com/ocornut/imgui/blob/512c54bbc062c41c74f8a8bd8ff1fd6bebd1e6d0/imgui_demo.cpp#L23-L29

In short, without `static`, your text buffer's lifetime is bounded to the current main loop iteration (or in other words, a single frame). This means that your buffer will effectively be erased each frame. With a static variable, your buffer's lifetime is expanded to the entire execution of your process.

You'll want to preserve your data across frames with `static`, even if your code doesn't require it. For example, if the user de-focuses from an `InputTextMultiline` to do something else like click a button, the text they entered will be lost because of the buffer's short lifetime. This is also why the buffer clears when you press [Enter], since pressing [Enter] de-focuses the textbox. (The reason why it doesn't clear every single frame is because the `InputText` functions hold onto a copy of the buffer until the user's done editing it.)

With a static buffer variable, you now need to clear (and make other modifications) when necessary. This is where the `strncpy` call comes in.

**Comment by pp9999** [comment]
Lets agree to disagree.
