### ISSUE TITLE
Change Ctrl+Tab combo

### ISSUE THREAD

**Issue by caxapexac** [ocornut/imgui#4828]
Based on https://github.com/ocornut/imgui/issues/3255, can't reopen issue so I've created the new one:

**Version/Branch of Dear ImGui:**

Version: 1.86
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: webGL
Compiler: em++
Operating System: V8

**My Issue/Question:**

Ctrl+tab changes tab in browser

Proof: https://stackoverflow.com/questions/56835762/how-to-disable-ctrltab-in-javascript
Proof: https://stackoverflow.com/questions/8195175/javascript-code-to-press-ctrltab

So I need to be able to **change combo from Ctrl+Tab to something else**
i.e. IntelliJ uses Shift+Shift for this
i.e. IDE's uses Shift+Space for intellisense so it shoud be conveniently too

**Comment by caxapexac** [comment]
@ocornut sorry you've opened it too late >_<

**Comment by ocornut** [comment]
Are you talking about Ctrl-Tab and not Alt-tab ? Your description keeps going back and forth between both..
(Docking has nothing to do with this, editing this out the title)

**Comment by caxapexac** [comment]
I'm about Ctrl+tab
![image](https://user-images.githubusercontent.com/33996246/147385883-7cd8f2be-4333-4101-a2ed-78b429df12b3.png)
This one

**Comment by caxapexac** [comment]
Maybe leave Ctrl and add option to config to choose between default Tab and other keys? Or hardcode 2-keys combo, something like:
```cpp
io.ConfigDockingShortcutFirstKey = Key::Ctrl;
io.ConfigDockingShortcutSecondKey = Key::Q;
```

If you wanna single-key tab opening then something like:
```cpp
io.ConfigDockingShortcutFirstKey = Key::Shift;
io.ConfigDockingShortcutSecondKey = Key::Shift;
```

Or maybe use array for it...

(I know it lead to huge issue of https://github.com/ocornut/imgui/issues/456 but anyway could be discussed (maybe temporary solution until shortcut api))

**Comment by Asphel-i** [comment]
imgui.cpp

**Comment by keszegh** [comment]
perhaps this is a proper thread to ask. 
is there any way to disable the ctrl+tab functionality without disabling keyboard input on sliders etc.?
i have set nonavfocus for each window, but still ctrl+tab makes the window list to popup (which is containing only 'main menu bar' in it). this is not good for me, especially as i used so far ctrl+tab for something else.

**Comment by rokups** [comment]
There is no way to disable this at the moment. It would also be better if you created a new issue. Answering new issues is no bother, scattering useful information in mostly unrelated issues does not help information discoverability later on.

**Comment by keszegh** [comment]
thanks @rokups . and next time i make a new thread, at least my issue is almost the same as of the thread title (or at least the solution to that would solve mine too up to some level).

**Comment by ocornut** [comment]
I think it's fine in the same issue since doing the earlier would likely allow the later.

Tho by the look of it, the later (disable) may be doable soon. I'll post when I have updates.

**Comment by keszegh** [comment]
@ocornut , thanks, disabling would be great and enough for me.

**Comment by DubbleClick** [comment]
Wouldn't it be enough to check if keyboard/gamepad navigation is even enabled before showing the window?

imgui.cpp line 10857:
```cpp
const bool start_windowing_with_gamepad = allow_windowing && !g.NavWindowingTarget &&
                                          IsNavInputTest(ImGuiNavInput_Menu, ImGuiNavReadMode_Pressed) **&&
                                          io.ConfigFlags & ImGuiConfigFlags_NavEnableGamepad**;
const bool start_windowing_with_keyboard = allow_windowing && !g.NavWindowingTarget &&
                                           io.KeyCtrl && IsKeyPressed(ImGuiKey_Tab) **&&
                                           io.ConfigFlags & ImGuiConfigFlags_NavEnableKeyboard**;
```

**Comment by ocornut** [comment]
We now have a more unified chord/shortcut systems and a solution for this.

While having discussions with other people I was also asked about remapping and specifically for the CTRL+Tab system.
While generic remapping is too difficult to reasonably achieve without adding extra burden for both library and user code, I realized that CTRL+Tab shortcuts are specific for two reasons:
- There is the web-browsing hooking issue you pointed out.
- It is also the only shortcut which intentionally reacts even is no imgui window is focused (e.g. if game in background is focused, what we refer as "void" in dear imgui).

For this reason it is reasonable to allow remapping this shortcut and now that it is easier to do, I've added an experimental/internal way to do it.

```cpp
// Note this is in the Dear ImGui context, NOT in ImGuiIO yet
g.ConfigNavWindowingKeyNext = ImGuiMod_Ctrl | ImGuiKey_Tab;
g.ConfigNavWindowingKeyPrev = ImGuiMod_Ctrl | ImGuiMod_Shift | ImGuiKey_Tab;
```

This works:
```
g.ConfigNavWindowingKeyNext = ImGuiMod_Shift | ImGuiKey_Space;
g.ConfigNavWindowingKeyPrev = 0;
```

If both are setup, it is currently required that they share a same modifier for "holding".
Because of the way CTRL+Shift+Tab work it is designed to iterate in a sequence before applying focus.
If you do this:
```
g.ConfigNavWindowingKeyNext = ImGuiKey_F11;
g.ConfigNavWindowingKeyPrev = ImGuiKey_F10;
```
The "prev" shortcut doesn't work correctly as it will cycle between two windows.
Fixing it would require a different mode of operation were e.g. the UI stays open until validating (with Enter) or after a timeout.
We can consider implementing this later, just as I would consider changing the default in Emscripten context.

Closing this for now but curious about your feedback and I expect to improve it once we have users.
