### ISSUE TITLE
Remove dependency on C++ headers?

### ISSUE THREAD

**Issue by yngccc** [ocornut/imgui#484]
Failed to compile with `-nostdinc++` because `#include <new>`, how about replace all replacement news with memcpy?

**Comment by ocornut** [comment]
There are 4 calls to placement new,  Not sure how you would do that tho. Have a static instance filled with all default values and memcpy? Sounds rather awkward and unpleasant to maintain.

**Comment by yngccc** [comment]
hmm, how about add a member function that mirror the constructor, call that on the pointer return from malloc instead of replacement new?

**Comment by ocornut** [comment]
I'm not sure it is possible with the syntax of the call to new. If you can find a way to do it feel free to try.

**Comment by nem0** [comment]
it is possible to have placement new without including new:

```
struct NewPlaceholder {};
inline void* operator new(size_t, NewPlaceholder, void* where)
{
	return where;
}
#define NEW_MACRO(allocator, ...) new (NewPlaceholder(), (allocator).allocate(sizeof(__VA_ARGS__))) __VA_ARGS__

```

**Comment by ocornut** [comment]
@nem0 could you clarify the code above? Not sure to understand how it would work.
It may also possibly help with https://github.com/ocornut/imgui/issues/504

**Comment by nem0** [comment]
I also wanted to get rid of new include in my engine, you can see it here https://github.com/nem0/LumixEngine/blob/master/src/engine/core/iallocator.h

The NewPlaceholder is there just because it is not possible to redefine the default placement new (at least according to standard), however it is [legal to define your own](http://en.cppreference.com/w/cpp/memory/new/operator_new). 

__VA_ARGS__ is there because of template:

```
NEW_MACRO(allocator, T<int, int>)(arg1, arg2)
```

Usage should be something along these lines:

```
DefaultAllocator allocator;
...
T* value = NEW_MACRO(allocator, T)(arg);
```

or without allocator:

```
#define NEW_MACRO2(allocator, ptr) new (NewPlaceholder(), ptr) 
...
char buf[64]
T* value = NEW_MACRO2(buf) T(arg);
```

Note: all the examples are just from my head, there might be some errors in them.

**Comment by ocornut** [comment]
Thanks! I understand and will experiment with that.

**Comment by ocornut** [comment]
@yngccc  I have removed the dependency on the `<new>` header now.

**Comment by yngccc** [comment]
@ocornut This is great, thanks!
