### ISSUE TITLE
How can I pass a shared pointer to ImTextureId?

### ISSUE THREAD

**Issue by GasimGasimzada** [ocornut/imgui#4847]
**Version/Branch of Dear ImGui:**

Version: 1.83
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + Custom graphics backend
Compiler: Visual Studio and Xcode
Operating System: macOS and Windows

**My Issue/Question:**

ImTextureId is a void pointer; however, I am using shared pointer in all places of my application. Is there a way that I can pass a shared pointer to ImTextureId.

I want to be able to something like this:

```cpp
SharedPtr<Texture> texture = loadFromFile("myImage.png");
ImGui::Image(texture, ...);
```

My goal is to pass the shared pointer directly to Imgui instead of passing the raw pointer because I do not want to lose access to the shared pointer reference in my custom backend.

**Comment by ocornut** [comment]
You cannot but in your wrapper to create a ImTextureID from your type you can push the shared pointer in a container of yours that you will clear after rendering, ensuring that reference are counted.

**Comment by GasimGasimzada** [comment]
Thank you for the idea! I a bit further and found a way to do it using `std::enable_shared_from_this`, which worked for my use-case.

**Comment by tksuoran** [comment]
> You cannot but in your wrapper to create a ImTextureID from your type you can push the shared pointer in a container of yours that you will clear after rendering, ensuring that reference are counted.

I was able put `shared_ptr<>` into `ImTextureID` with

```
#include <memory>

namespace erhe::graphics {
    class Texture;
}

#define ImTextureID std::shared_ptr<erhe::graphics::Texture>

namespace ImGui
{
    inline auto GetTextureVoidPtr(const ImTextureID& id) -> void*
    {
        return id.get();
    }
}
```

and fixing the two cases where cast was used in `imgui.cpp`, replacing casts with `GetTextureVoidPtr()`.

But you say this cannot be done, is there something wrong in my solution? Would using a wrapper type be superior in some way?

**Comment by ocornut** [comment]
Your solution doesn’t keep a reference on the shared pointer, therefore if there are no other left the underlying data may be destroyed too earlier. To fullfil this properly you would need to store a shared pointer somewhere (hence my suggestion to add it to an array and clear the array after rendering)

**Comment by GasimGasimzada** [comment]
@tksuoran I personally don't like changing any third party library's defined types using preprocessor directives. Since it is only for textures, my personal suggestion is to use `enable_shared_from_this`, which allows for reference counter to keep going when wrapping raw pointers with shared ones, especially when they are created with shared pointers. Example: https://godbolt.org/z/cd7aj4ncx

**Comment by tksuoran** [comment]
Yes, I know `enable_shared_from_this` and it can be a good solution in some cases. Using `#define ImTextureID` is documented in ImGui.

In my case, I need to keep the textures from being deleted, but only as long as the texture id exists in `ImDrawCmd` / `ImDrawList`. Otherwise the texture could be free in mid-frame before ImGui is rendered. After the draw commands are done, and no-one else uses the texture, the texture can get deleted.

Now that I examined ImGui more carefully, it turns out that `ImDrawList` uses `ImVector<ImDrawCmd>`. And ImVector has this notice:

> Important: our implementation does NOT call C++ constructors/destructors, we treat everything as raw data! This is intentional but be extra mindful of that, Do NOT use this class as a std::vector replacement in your own code! Many of the structures used by dear imgui can be safely initialized by a zero-memset.

This means that putting `shared_ptr<>` into `ImDrawCmd` is not going to work correctly. The destructor will never be called, so the texture could leak. I will need to implement the list of used textures as suggested by @ocornut. I will do this when I implement bindless textures so `ImTextureID` can become `uint64_t`.

**Comment by maxime-modulopi** [comment]
@ocornut Is there any plan to support this usage?

Using an indirect array that is reset every frame + ImTextureID as an index in this array is unpractical with the `ImGuiBackendFlags_RendererHasTextures` feature because of the instability of the index between frames (I believe `ImTextureData::SetTexID` is supposed to be called once when processing `ImTextureStatus_WantCreate` and the ID is expected to stay valid for the lifetime of the texture)

**Comment by ocornut** [comment]
@maxime-modulopi Could you open a new issue for this? (and perhaps expand a little on your paragraph)

**Comment by maxime-modulopi** [comment]
I was able to work around the ID instability by using `ImTextureData::BackendUserData` (that I initially missed) to manage the lifetime of the underlying ref-counted texture and then iterating + updating the ImTextureID of all ImGui internal textures in my backend's `NewFrame`
