### ISSUE TITLE
How to implement Auto-scroll for ImGui Tables.

### ISSUE THREAD

**Issue by FoxMaccloud** [ocornut/imgui#4868]
I'm trying to sort some packet data and I'm using tables to sort. I'm also working off the terminal "template" from the demo file.
I was wondering if there was a way to implement auto-scrolling for imgui tables.
The examples I found in the demo uses Child windows for this, but I couldn't figure out how to use these with tables (if possible...).
```cpp
if (scroll_to_bottom || (auto_scroll && ImGui::GetScrollY() >= ImGui::GetScrollMaxY()))
		ImGui::SetScrollHereY(1.0f);
scroll_to_bottom = false;
```

As it is now, every time a new item gets added to the table, I need to scroll down to view the new entries.
my relevant code looks something like;
```cpp
		const float footer_height_to_reserve = ImGui::GetStyle().ItemSpacing.y + (ImGui::GetFrameHeightWithSpacing() * 2);
		ImGui::BeginChild("ScrollingRegion", ImVec2(0, -footer_height_to_reserve), false, ImGuiWindowFlags_NoScrollbar /*ImGuiWindowFlags_HorizontalScrollbar*/ | ImGuiWindowFlags_NoScrollWithMouse);
		{
			if (ImGui::BeginPopupContextWindow())
			{
				if (ImGui::Selectable("Clear")) clear_log();
				ImGui::EndPopup();
			}
			ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(4, 1)); // Tighten spacing
			if (copy_to_clipboard)
				ImGui::LogToClipboard();

			ImGui::BeginTable("Packets", 5, ImGuiTableFlags_BordersOuter | ImGuiTableFlags_BordersInner | ImGuiTableFlags_RowBg | ImGuiTableFlags_ScrollY);
			{
				ImGui::TableSetupScrollFreeze(0, 1); // Make top row always visible
				ImGui::TableSetupColumn("Name", ImGuiTableColumnFlags_None, 0.08f);
				ImGui::TableSetupColumn("Opcode", ImGuiTableColumnFlags_None, 0.08f);
				ImGui::TableSetupColumn("Packet", ImGuiTableColumnFlags_None);
				ImGui::TableSetupColumn("Size", ImGuiTableColumnFlags_None, 0.05f);
				ImGui::TableSetupColumn("Time", ImGuiTableColumnFlags_None, 0.04f);
				ImGui::TableHeadersRow();

				for (int i = 0; i < items.Size; i++)
				{

					const char* item = items[i];
					if (!filter.PassFilter(item))
						continue;

					ImGui::TableNextRow();

					ImGui::TableSetColumnIndex(0);

					if (strstr(item, "00"))
					{
						ImGui::TextWrapped("Unknown"); // TEMP
					}
					else
					{
						ImGui::TextWrapped("Unknown");
					}
					
					ImGui::TableSetColumnIndex(1);

					ImGui::TextWrapped("0x1234");

					ImGui::TableSetColumnIndex(2);

					ImVec4 color;
					bool has_color = false;
					if (strstr(item, "[error]")) { color = ImVec4(1.0f, 0.4f, 0.4f, 1.0f); has_color = true; }
					else if (strncmp(item, "# ", 2) == 0) { color = ImVec4(1.0f, 0.8f, 0.6f, 1.0f); has_color = true; }
					if (has_color)
						ImGui::PushStyleColor(ImGuiCol_Text, color);
					ImGui::TextWrapped(item);
					if (has_color)
						ImGui::PopStyleColor();

					ImGui::TableSetColumnIndex(3);

					int packet_length = strlen(item);
					ImGui::TextWrapped(std::to_string(packet_length/2).c_str());

					ImGui::TableSetColumnIndex(4);

					ImGui::TextWrapped(timestamps[i]);

					// TODO: Fix autoscroll for Table.

				}
				if (copy_to_clipboard)
					ImGui::LogFinish();
				if (scroll_to_bottom || (auto_scroll && ImGui::GetScrollY() >= ImGui::GetScrollMaxY()))
					ImGui::SetScrollHereY(1.0f);
				scroll_to_bottom = false;
			}
			ImGui::EndTable();
		}
		ImGui::EndChild();

		ImGui::Separator();
```

Some tips would be much appreciated!

**Comment by ocornut** [comment]
I think there's a known bug with frozen row but otherwise you are not specifying what's wrong.. at first glance the code looks good.

Also note your filtering code:
```
if (!filter.PassFilter(item))
    continue;
```
Should probably run before executing `TableNextRow()` otherwise you'll have empty rows..

**Comment by FoxMaccloud** [comment]
What's wrong is that when I add new entries to the tables, it does not scroll. Expected behavior is that it scrolls to the bottom :)
I noticed when I write a new command in my console, the output of that gets added to the table (which is expected), it then also auto-scrolls to the bottom like expected. But if the scrolling issue is due to a bug, there isn't much I think I can do.

Also thanks for the tips on the filtering!

**Comment by ocornut** [comment]
> What's wrong is that when I add new entries to the tables, it does not scroll

Then I guess something is wrong in your code that we don't know about.

Unrelated but aside from the filtering thing
- I'm struggling to understand why you have a `BeginChild()` scrolling region with only a Table inside it, that BeginChild/EndChild seems unnecessary and a little bizarre.
- You are supposed to test the return value of `BeginTable()`.

>  But if the scrolling issue is due to a bug, there isn't much I think I can do.

The bug I was referring out if you might get a slight vertical offset due to the frozen row, but that's not the bug you are seeing.

**Comment by FoxMaccloud** [comment]
>I'm struggling to understand why you have a BeginChild() scrolling region with only a Table inside it, that BeginChild/EndChild seems unnecessary and a little bizarre.

Yeah, that's because it's based upon the demo console 😅 
The data I'm working with just made more sense to put into a table as it looked easier on the eyes, but having to scroll to see the latest entries in the list is a bit of a pain.

> but that's not the bug you are seeing.

That's nice to hear 😄 

> You are supposed to test the return value of BeginTable().

I'm not sure what you meant with this. What am I supposed to test?

**Comment by ocornut** [comment]
I went through and got the piece of code above to compile and confirmed this to work with no issue.
For lack of an actual repro there's nothing to fix, must be an issue in code that you omitted, as suggested in previous posts.

(I mistakenly marked 16cee3d00942d5394ab495bfec6f56e52d8b14bf and fd0b3734d364ff8c4cf6884491d38b36d4af0966 as fixing this, as it was mislabeled in our DB, but afaik the fixed bugs is unrelated to this thread).

> The data I'm working with just made more sense to put into a table as it looked easier on the eyes

I agree but then you don't need the child window, since the tables already provide a scrolling region.

> but having to scroll to see the latest entries in the list is a bit of a pain.

I agree. Demo/examples should solve that. As I run your code now it works (would have run it earlier if was a pastable repro).

>> You are supposed to test the return value of BeginTable().

> I'm not sure what you meant with this. What am I supposed to test?

There are exactly 43 uses of `BeginTable()` in imgui_demo.cpp and everyone of them are testing the return value of `BeginTable()` and only submitting contents + EndTable() when it returned true. You are not doing this, so your code will break if the table is clipped.
