### ISSUE TITLE
Can I somehow disable docking tab tablist popup and tab bar close buttons?

### ISSUE THREAD

**Issue by tksuoran** [ocornut/imgui#4880]
**Version/Branch of Dear ImGui:**

Version: 1.86
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: custom (erhe) and glfw
Compiler: Visual Studio 2022
Operating System: Windows 10

**My Issue/Question:**

Is there some way to hide docked windows tab bar tablist popup and close buttons?
Thanks!

**Screenshots/Video**

I have pointed buttons I would like to hide with yellow arrows below:
![unwanted_buttons](https://user-images.githubusercontent.com/994606/148649226-93ce4357-a937-4c57-b731-08b87a6835b9.png)

**Comment by PathogenDavid** [comment]
You can hide the menu button globally by setting `ImGuiStyle::WindowMenuButtonPosition` to `ImGuiDir_None`.

Not exactly what you want since this will remove the close button from individual tabs as well, but you can hide the close button by passing null to `p_open` for `ImGui::Begin`. (All windows docked together must have a null `p_open` in order for this to work.)

----------

If you're willing to use internal/alpha APIs:

If you want the close button to appear on individual tabs without the common one you highlighted, you apply `ImGuiDockNodeFlags_NoCloseButton` flag via `ImGuiWindowClass::DockNodeFlagsOverrideSet` and `SetNextWindowClass`.

Similarly if you want to hide the menu button for only some windows, you use `ImGuiDockNodeFlags_NoWindowMenuButton`.

(I'm unsure why these two flags are internal-only. I know some of the `ImGuiDockNodeFlagsPrivate` flags are internal because they're still experimental, but neither of these are labeled as such. There may be unintended consequences if you use these flags.)

**Comment by ocornut** [comment]
Closing this old issue as answered, thanks David!
