### ISSUE TITLE
Is using ImGui for game UI a good idea?

### ISSUE THREAD

**Issue by Riser777** [ocornut/imgui#4913]
Not sure where else to ask this since the Discussions category is reserved for people who can't build the library.
Also I've seen other people ask this on line but got no definitive answer.

I'm working on a cellular-automata-based game engine in SFML, and I'm planning on using ImGui for debugging, but I'm thinking of going a step further and using it for the game's UI itself, it has all the features I might need and I honestly like the way it looks and I think it might fit with the game's aesthetic.

I'm still on the fence about it, but I just wanted to know to if it's a good idea to use it in the final/release build of the game?
Or is it simply not designed for that?

**Comment by PathogenDavid** [comment]
>  it has all the features I might need and I honestly like the way it looks and I think it might fit with the game's aesthetic.

In this situation I'd say it's a reasonable idea. Why deal with two UI frameworks if you don't have to?

I might hesitate if your game is going to be heavy on text input and you plan to translate to non-Latin script languages since Dear ImGui's IME support isn't the best. (Although that could be said of most non-native UI frameworks.)

IMO, develop with Dear ImGui to start off and if you find yourself fighting with some aspect of the library revaluate and decide if you need to pivot.

**Comment by Riser777** [comment]
@PathogenDavid I have no plans to translate it to other languages, let alone ones that doesn't use the Latin alphabet, so I have nothing to worry about in that regard.
I guess I'll just go with it and see how it turns out, thank you.
