### ISSUE TITLE
Mathematical Notation Rendering and Input

### ISSUE THREAD

**Issue by debater-coder** [ocornut/imgui#4959]
**Version/Branch of Dear ImGui:**

Version: 1.87
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp 
Compiler: MSVC
Operating System: Windows

**My Issue/Question:**

Hi, I'm trying to display mathematical notation in Dear ImGui, and also allow the user to input this mathematical notation with an in-app keyboard. I have tried using a font with mathematical symbols in them with `IMGUI_USE_WCHAR32` enabled, and a custom glyph range but that does not seem to work. I also eventually want to display notation that cannot be displayed in normal unicode such as the type of notation shown in the screenshot below, with notation on multiple lines. In the example below I show my attempt at including these symbols from a math font.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/52619668/151639348-3fc47ca1-7465-4088-9206-6d0332d226b3.png)

**Standalone, minimal, complete and verifiable example:**
```c++
// Before first frame
ImVector<ImWchar> ranges;
ImFontGlyphRangesBuilder builder;
builder.AddRanges(io.Fonts->GetGlyphRangesDefault()); // Add one of the default ranges
builder.AddText("∀(x, y ∈ A ∪ B; x ≠ y) x² − y² ≥ 0");
builder.BuildRanges(&ranges);                          // Build the final result (ordered ranges with all the unique characters submitted)
io.Fonts->AddFontFromFileTTF("NotoSansMath-Regular.ttf", 16.0f, NULL, ranges.Data);
```

**Comment by PathogenDavid** [comment]
You need a `u8` prefix or to change the default charset in order for MSVC to encode the string correctly.

The more advanced layout in your screenshot would have to be done with custom rendering.

**Comment by debater-coder** [comment]
Thank you, that fixed the issues with the fonts. I will look into custom rendering.

**Comment by debater-coder** [comment]
Just a quick question: Is there any way to draw subscripts and superscripts without using custom rendering?

**Comment by PathogenDavid** [comment]
Depending on your needs you might be able to use [the superscript/subscript Unicode symbols](https://unicode-table.com/en/sets/superscript-and-subscript-letters/), otherwise you're stuck with custom rendering.

**Comment by debater-coder** [comment]
I have been looking into using ` ImDrawList->AddText()` API and I do not understand the purpose of the `col` and `cpu_fine_clip_rect` arguments. Could you please clarify the meaning of these arguments?

**Comment by PathogenDavid** [comment]
`col` is the color as encoded using `IM_COL32` or `ImColor`.

-------------------

You probably do not need to use `cpu_fine_clip_rect`, but the short version is clipping rectangles prevent drawing outside of a given area. (For example, they prevent a large amount of text from drawing outside of a window when that window is smaller than the text.)

If you're curious as to why it's the "**CPU fine** clipping rectangle":

Dear ImGui has a few different levels of clipping for text, off the top of my head:

1. Fine-grained GPU clipping rectangle (this is what is controlled by `ImDrawList::PushClipRect`. It also happens implicitly when you submit new windows or child windows.) This type of clipping is pixel-precise and is very fast, but has the downside of increasing your GPU draw call count when you change it.
2. Coarse-grained CPU clipping. This happens automatically, you don't control it. When rendering multiple lines of text, Dear ImGui will try to avoid submitting or allocating unnecessary vertices for text which is definitely outside of the current fine-grained GPU clipping rectangle. (For shorter text it's less aggressive about performing this clipping.)
3. Fine-grained CPU clipping. (This is what `cpu_fine_clip_rect` is for.) It does pixel-precise fine-grained clipping on the CPU. This comes at an added cost on the CPU side but it has the benefit of not increasing your draw call count. It is mostly useful when you find yourself drawing lots of short text fragments with different clipping rectangles where the overhead of the additional draw calls outweighs the cost of doing clipping on the CPU.

To give an example, here's an example window with a large body of text inserted into it with the raw mesh data overlayed on the right half:

![Dear ImGui Screenshot](https://user-images.githubusercontent.com/278957/151686429-d7b2ac21-879e-4af7-a880-793c6bf6abd8.png)

As you can see, the little yellow rectangles representing each letter go beyond the boundaries of the window, but only by one line. (In actuality [this text goes on for quite a bit longer past that one line](https://user-images.githubusercontent.com/278957/151686572-6ec8f74e-34a9-4e6c-a53d-75afd5b78bf9.png).) The fact that you don't see it go outside of the window is thanks to fine-grained GPU clipping. The fact that there's only one "unnecessary" line is thanks to coarse-grained CPU clipping.

If I enable fine-grained CPU clipping you'll see all but the visible tops of letters is clipped from that last line:

![Dear ImGui Screenshot](https://user-images.githubusercontent.com/278957/151686555-9ffd580b-0b00-47ce-a684-7cecb323b316.png)

(In this case fine-grained CPU clipping is completely pointless since the GPU clipping rectangle matches the CPU clipping rectangle, this is just for illustration purposes.)

**Comment by debater-coder** [comment]
Thanks, I think I will be able to implement everything myself now.
