### ISSUE TITLE
Need help with Docking builder

### ISSUE THREAD

**Issue by aabilityuk** [ocornut/imgui#4982]
Hi, dear community! this is not an issue question but help request. Help me please to find out with ImGui::DockingBuilder how to programmatically build a docking layout during the first load of my GUI.

Here is my structure:

```
void CImGuiSettings::Application_Frame()// main loop
{
   if (ImGui::Begin("One"))
    {
        ImGui::End();
    }

    if (ImGui::Begin("Two"))
    {
        ImGui::End();
    }

    if (ImGui::Begin("Three"))
    {
        ImGui::End();
    }
}
```

I need the "One" to be docked on the left of the Two" and "Three" to be docked on the bottom of the "Two" and finally i need the whole stuff to be docked to the main window center (on full screen). I find some explanation here: https://github.com/ocornut/imgui/issues/2109
But i can't make it work like that, i am using dear imgui, v1.76 with docking support. Help me please!!! thank you

**Comment by AidanSun05** [comment]
Here's some example code with explanations:
https://gist.github.com/AidanSun05/953f1048ffe5699800d2c92b88c36d9f

The layout it creates is as follows:

![image](https://user-images.githubusercontent.com/61399657/152620330-01e9e3dd-9d6f-4d7d-adb2-1752f83c68f6.png)

(Note: The example code I provided only centers the dock node in the window on startup - in other words, the node won't automatically center itself if you resize the window or make it full screen. However, with the information provided in the file, you should at least understand how to change the dock node's position if you wanted to implement this yourself.)

(Note 2: Your Begin/End pairs caused assertion failures because of the if statements. You should always call `End()` for each `Begin()`, no matter what `Begin()` returns.)

**Comment by aabilityuk** [comment]
> Here's some example code with explanations: https://gist.github.com/AidanSun05/953f1048ffe5699800d2c92b88c36d9f
> 
> The layout it creates is as follows:
> 
> ![image](https://user-images.githubusercontent.com/61399657/152620330-01e9e3dd-9d6f-4d7d-adb2-1752f83c68f6.png)
> 
> (Note: The example code I provided only centers the dock node in the window on startup - in other words, the node won't automatically center itself if you resize the window or make it full screen. However, with the information provided in the file, you should at least understand how to change the dock node's position if you wanted to implement this yourself.)
> 
> (Note 2: Your Begin/End pairs caused assertion failures because of the if statements. You should always call `End()` for each `Begin()`, no matter what `Begin()` returns.)


@AidanSun05 

Hi, first of all thank you very much for a code sharing and clear example!!! It's great!!! from the first try i've got a working layout!!! I didn't clear explained sorry, but finally i need that docked construction (consist of: one,two,three) to be docked to the main window on the full screen, is it possible to achieve that?

Something like:

![изображение](https://user-images.githubusercontent.com/78211227/152816600-87ee1be8-f945-4587-b858-ed19003f38dd.png)

**Comment by aabilityuk** [comment]
> Instead of your `desktop.Width`, `desktop.Height`.
> 
> You can use
> 
> ```
> ImGuiViewport* viewport = GetMainViewport();
> ```
> 
> then `viewport->Pos`, `viewport->Size`. or `viewport->WorkPos`, `viewport->WorkSize` to avoid main menu bar.

Thank you very much!!! tested.... that's working great too
