### ISSUE TITLE
Change question mark ('?') symbol for invalid unicode

### ISSUE THREAD

**Issue by caxapexac** [ocornut/imgui#5015]
Version/Branch of Dear ImGui:

Version: 1.86
Branch: docking

Back-end/Renderer/Compiler/OS

Back-ends: webGL
Compiler: em++
Operating System: V8

My Issue/Question:
I have optional FontAwesome in my gui. So it renders as '?' if you disabled FontAwesome. Wanna to see spaces or zero-width-spaces instead

I suppose it could be something like `io.Fonts.InvalidKeyCode = (int)(' ')` for replacing to space, for example

Sorry if it is already exist and Im just blind :)

**Comment by thedmd** [comment]
### Solution
If you set `ImFont::FallbackChar` before atlas is generated (first frame or manual call to `io.Fonts->Build()`) ImGui will use this as a fallback character for this particular font. You need to specify it for every font you are adding.
```cpp
    auto font = io.Fonts->AddFontFromFileTTF("../../misc/fonts/Roboto-Medium.ttf", 16.0f);
    font->FallbackChar = '#';
```

### How does it work
If character you choose does not exists in font charset ImGui will try to find default substitute characters (in this order): `�`, `?`, and ` ` (space). If that fails last character from the charset will be used as `FallbackChar`. And if by chance font does not have any glyphs you may find yourself reporting another bug, because ImGui will probably assert or crash. : )

**Comment by ocornut** [comment]
Thank you @thedmd for answering. Closing as answered!
