### ISSUE TITLE
How to scale an ImGui image using Nearest filtering?

### ISSUE THREAD

**Issue by abyssalEnvoye** [ocornut/imgui#5118]
Version: 1.87
Branch: docking

Back-ends: ImGui.Net + FNA (C#)
Operating System: Windows

**My Issue/Question:**

Hello,

I am trying to make a pixel art game and have written my game scene to a render texture. I am then drawing that texture to an ImGui window but the image scales using bilinear filtering and looks super blurry. 

I found out in #2973 that you should be able to filter using nearest neighbour but have failed to find out how...

Any help is appreciated!

**Screenshots/Video**

How it looks:

![BilinearScalingLarge](https://user-images.githubusercontent.com/98768402/159056712-04cd1151-c2fa-42ac-b465-1d0469a04fd1.png)

How it should look:

![SnakeExample](https://user-images.githubusercontent.com/98768402/159060376-961946e2-62a3-4186-8bcd-29ae6bd6d8d8.png)

**Windowing code**

```
ImGui.Begin("Game");

// Scale target to fit window
Num.Vector2 screenSize = ImGui.GetContentRegionAvail();
float scale = Math.Min(screenSize.X / renderTarget.Width, screenSize.Y / renderTarget.Height);

ImGui.Image(imGuiTarget, new Num.Vector2(renderTarget.Width * scale, renderTarget.Height * scale));
ImGui.End();
```

I have tried using drawList to do the same thing but there is not an option to filter using Nearest Neighbour doing that either...

PS. This is written in C# but feel free to reply in C++ and I will convert it on my end — Thanks

**Comment by PathogenDavid** [comment]
You can't change the texture filtering for `ImGui::Image`. I believe that issue is mainly talking about custom backends or people reconfiguring the sampler on their own.

How you change the texture filtering depends on the backend, so I can't give advice specific to how things work with FNA since I assume you're using a FNA-specific backend.

At a high level there are two strategies:

A) Use `ImGuiDrawList::AddCallback` to insert a callback to change the texture filtering to nearest neighbor, draw your image, and then call `AddCallback(ImDrawCallback_ResetRenderState)` to reset the state.
B) Use `ImGuiDrawList::AddCallback` to manually draw your image with nearest neighbor. (Being sure not to affect global state or use `ImDrawCallback_ResetRenderState` again to reset it.)

**Comment by abyssalEnvoye** [comment]
🙄 Was being stupid... nothing to do with ImGui. I was drawing to my render texture with my SamplerState set to LinearClamp (FNA specific). I've got it working now but thank you anyway.

**Comment by abyssalEnvoye** [comment]
I am closing this now... Thank you.

**Comment by PathogenDavid** [comment]
No worries, we've all been there!

**Comment by ocornut** [comment]
In the latest version it is now possible to switch to Point/Nearest sampling in a backend-agnostic way:

```cpp
draw_list->AddCallback(ImGui::GetPlatformIO().DrawCallback_SetSamplerNearest);
draw_list->AddImage(...);
```

See #9378 for details.
