### ISSUE TITLE
Windows Blinking On OpenGL3 Problem

### ISSUE THREAD

**Issue by another-ghasem** [ocornut/imgui#5127]
**Version/Branch of Dear ImGui:**
Version: `1.87 (18700)`
Tag: `v1.87`
Cloning Command: `git clone https://github.com/ocornut/imgui -b v1.87 --depth 1`

**Backend/Compiler/OS:**
Compiler: `GCC 8.3.0`
Operating System: `Debian Buster` <sub>(Kernel: 4.19.0-19-amd)</sub>
Compositor/Windows Manager: `KWin 5.14.5`
Graphic Card: `NVIDIA Corporation GT218M [NVS 3100M] (rev a2)`
OpenGL Version: <sub>[full output](https://gist.githubusercontent.com/another-ghasem/76c4e32e1117eb2fb0d66869f4e95eb1/raw/074a0762e926973b2becc235753d6b5024aee37c/glxinfo.txt) </sub>
```bash
$ glxinfo | grep -i version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Version: 18.3.6
    Max core profile version: 3.3
    Max compat profile version: 3.3
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL core profile version string: 3.3 (Core Profile) Mesa 18.3.6
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.3 (Compatibility Profile) Mesa 18.3.6
OpenGL shading language version string: 3.30
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 18.3.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

```

**My Issue**
Windows blink on OpenGL3 when moving the cursor.

**Screenshots/Video**

https://user-images.githubusercontent.com/38757443/159179356-af23bb5e-1abe-4571-b0cf-bfd2ed601f47.mp4

**Standalone, minimal, complete and verifiable example:** 
I just run the examples:
- `example_glfw_opengl2`
- `example_glfw_opengl3`
- `example_glut_opengl2`
- `example_sdl_opengl2`
- `example_sdl_opengl3`

All the OpenGL2 versions are fine and the problem only appears with the OpenGL3. I also tried to disable the desktop compositor and change the compositor OpenGL backend version to OpenGL2, but neither changed the problem.

**Comment by PathogenDavid** [comment]
Did older versions of Dear ImGui work on this machine?

I'm wondering if this is an issue with Nouveau. It's not exactly common and my understanding it it's mostly experimental quality due to lack of cooperation from Nvidia.

Your video gives me the vibe that vertex offsets aren't being honored properly. Can you try commenting out [`IMGUI_IMPL_OPENGL_MAY_HAVE_VTX_OFFSET` in `imgui_impl_opengl3.cpp`](https://github.com/ocornut/imgui/blob/1ba2905017ea81545b2fd1d45fee093a4982d9b1/backends/imgui_impl_opengl3.cpp#L161)?

**Comment by another-ghasem** [comment]
I tried:
- `v1.87` with/without `IMGUI_IMPL_OPENGL_MAY_HAVE_VTX_OFFSET`
  - With nVidia Legacy Driver 340xx [**OK**]
  - With nouveau Driver [**FAILED**]
- `v1.86` with/without `IMGUI_IMPL_OPENGL_MAY_HAVE_VTX_OFFSET`
  - With nVidia Legacy Driver 340xx [**OK**]
  - With nouveau Driver [**FAILED**]

But everything is fine in `v1.85` until `v1.80` as far as I checked.

**Comment by PathogenDavid** [comment]
The fact that it works fine on the Nvidia driver definitely points towards this being a Nouveau issue.

The only changes to the OpenGL 3 backend between v1.85 and v1.86 are:

* [Early out when the clipping rectangle is empty](https://github.com/ocornut/imgui/commit/440824d4314b59049a196e9e6964d8e72aed25bd#diff-518fceee829a7e5d6551f48feb3080c081c00b4a153b9ee07905c58f8a854136)
* [Using `glBufferSubData` to fix issues on Intel GPUs](https://github.com/ocornut/imgui/commit/389982eb5afbb9f93873d87f1201842ccbc82dec#diff-518fceee829a7e5d6551f48feb3080c081c00b4a153b9ee07905c58f8a854136)

I would suspect the second one is the source of your issue.

It might be worth checking `glGetError` around the affected calls to see if they're complaining when the glitches happen.

Either way it'd probably be worth [reporting the bug to the Nouveau devs](https://nouveau.freedesktop.org/Bugs.html) (unless someone discovers we're using one of these APIs incorrectly, but I don't think we are.)

**Comment by another-ghasem** [comment]
`glGetError` return value always is `0`, and it's properly is the Nouveau problem with my graphic, because I found out that Nvidia no longer supports my graphic's driver.

**Comment by piernov** [comment]
Been facing a similar issue introduced by https://github.com/ocornut/imgui/commit/389982eb5afbb9f93873d87f1201842ccbc82dec . Specifically, the issue has been reproduced on ArchLinux32 with a 8800 GTS (G80), ArchLinux with a GT120 and Lubuntu 21.10 with a 8600M GS, all using nouveau. The issue is not present when using the proprietary NVidia driver 340 on the GT120 with ArchLinux. The issue is also not present on Windows or macOS, or with an Intel GPU on Linux or an AMD GPU (200-series) on both Linux and Windows. I don't know about newer NVidia GPUs.

Messed up menu bar text:
![Bug1](https://user-images.githubusercontent.com/8332263/160051326-8b5606b8-dca3-4b9d-aa5c-6b9d22884fe7.png)
![Bug2](https://user-images.githubusercontent.com/8332263/160051419-40976fce-6699-4fd8-b06f-8964794d640c.png)

 Release 8.95.1 of OpenBoardView uses ImGui v1.79 and is not affected. Release 8.95.2 uses ImGui v1.87 and is affected. ( https://github.com/OpenBoardView/OpenBoardView/releases )

**Comment by PathogenDavid** [comment]
One thing that stands out to me is that all 4 of the GPUs tested by both of you are Tesla cards.

In the [Nouveau documentation](https://nouveau.freedesktop.org/CodeNames.html#nv50familytesla) they describe Tesla as being quite a bit different from its predecessors, and Fermi (the next generation) being even different still. That would seemingly make Tesla cards the black sheep of Nvidia's historical lineup, so it wouldn't surprise me if Nouveau's support for them is less exercised than others.

**Comment by piernov** [comment]
The issue does not seem to show up on a GT620 (GF119). I don't have any other Fermi or newer GPU to confirm, and Geforce 7000-series and older do not support OpenGL 3. However it may indeed be a nouveau bug with Tesla only.

**Comment by CarlkD** [comment]
I'm having the same issue on OpenGL3 and not having on OpenGL2. But get ready, cause my configuration will confuse minds. I'm having the issue on:

Mac mini 2018 Intel i5, Intel UHD graphics 630, MacOS v.12 Monterey

**Comment by ocornut** [comment]
Sorry this has been open for long. 
Based on reports like now I eventually settled on using varying codepath based on GPU vendors :(
In most cases the changes added in 389982eb have been undoed. The codepath of 1.86 now only runs on Intel HD Gpu Windows.
Pushed: ca222d30c8ca3e469c56dd981f3a348ea83b829f

This sucks a bit, but hopefully it settles the problem :(
