### ISSUE TITLE
SetCapture/ReleaseCapture opt-out?

### ISSUE THREAD

**Issue by Friendly0Fire** [ocornut/imgui#5157]
**Version/Branch of Dear ImGui:**

Version: 377b864bb4a9ed9a25674b04f64f63baf221060d
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: `imgui_impl_win32.cpp`
Compiler: VS2022
Operating System: Windows 11

**My Issue/Question:**

I'm writing a plugin which injects itself into an existing application, which means I can't modify its input handling, and ever since updating to the latest commit of imgui in the docking branch, dragging the mouse no longer works in the app itself, but is still fine within imgui (e.g. scrollbars work fine). I've narrowed it down to the use of `SetCapture` and `ReleaseCapture`, which appears to interfere with the app's mouse handling.

I would be very interested in having a flag or define to disable the use of these functions if necessary, since in my case I'd rather have some input glitches when the mouse exits the window than entirely non-functional dragging everywhere else. I can modify the code myself, but being able to stay on the official backend would be preferrable.

**Comment by ocornut** [comment]
Maybe capturing could be dependant on io.WantCaptureMouse being set.

But simply you could take control of the WndProc function and duplicate a customized functions of the buttondown/up msg, and forward every other to the default function.

If you multi-viewports you’ll need to hook yourself after viewport window creation to install that WndProc redirection.

**Comment by ocornut** [comment]
> Maybe capturing could be dependant on io.WantCaptureMouse being set.

Changing
```cpp
if (bd->MouseButtonsDown == 0 && ::GetCapture() == NULL)
    ::SetCapture(hwnd);
```
to
```cpp
if (bd->MouseButtonsDown == 0 && ::GetCapture() == NULL && io.WantCaptureMouse)
    ::SetCapture(hwnd);
```
Would get us 99% of the way but unfortunately introduce a race condition which is difficult to test and repro but will occasionally happen: When on frame N `WantCaptureMouse==false`, frame N+1 move mouse over dear imgui window and click, frame N+1 output `WantCaptureMouse==true`, we'd have a drag ongoing that is not captured and fail to follow outside the platform window boundaries, bad user experience.

Another solution would be to claim `SetCapture()` _AFTER_ `ImGui::NewFrame()`, which is tricky with our general backend API and would introduce another race condition but one that's much less problematic/acceptable from a user point of view.

In YOUR SITUATION however, it might work if you simply manually release capture after the `ImGui::NewFrame()` call:
```cpp
if (::GetCapture() == hwnd) 
   ::ReleaseCapture(hwnd);
```
And if it works (but it's difficult to tell because we don't know why your underlying applications doesn't have access to inputs) here you can safely add the `WantCaptureMouse` here to it:
```cpp
if (::GetCapture() == hwnd && !io.WantCaptureMouse) 
   ::ReleaseCapture(hwnd);`
```

Does that work for you?

**Comment by Friendly0Fire** [comment]
Thanks for the detailed analysis! I've given the workaround a shot, but unfortunately just enabling the capture seems to break the drag - I'm really not sure what's going on with it. Releasing immediately after the `WndProc` handler doesn't seem to help.

I know it's inelegant and just hides the issue instead of fixing it, but would something like
```cpp
#ifndef IMGUI_GET_CAPTURE
#define IMGUI_GET_CAPTURE ::GetCapture()
#endif
```
be acceptable? I could override the define in `imconfig.h` to be e.g. `1` and bypass the checks (at no runtime cost, even).
