### ISSUE TITLE
Detect mouse over any ImGUI window

### ISSUE THREAD

**Issue by mattiasljungstrom** [ocornut/imgui#52]
This is more of a question. How do I detect if the mouse is currently over any ImGui window? Is this supported? Also, how do I detect if any input box currently has focus?

**Comment by Bonkt** [comment]
I want to do something similar to this. (using sfml) i render my main application to a sf::RenderTexture that i then display on ImGui::Image(). So basically my dockspace and my whole window is at all times completely covered by ImGui windows.

So when i try to dispatch mouse clicks to my application i want to check if io.WantCaptureMouse.
The problem is that i also want to be able to move my "application" window around. So setting the flag ImGuiWindowFlags_NoMouseInputs does not work. 

I read at many places that io.WantCaptureMouse is prefered over IsWindowHovered(). 
Is this still the case for my use case? Or would a new flag with a name like
 ImGuiWindowFlags_OnlyMouseInputsOnTitlebar be a useful addition to the API?
