### ISSUE TITLE
ImGui DX11 backend not rendering anything

### ISSUE THREAD

**Issue by ItsSunnyMonster** [ocornut/imgui#5223]
I know that this has been asked everywhere, but all of them seem to have made some careless mistakes like forgetting to call `ImGui_Implxxx_RenderDrawData` etc. but I've checked my code against the example code and did not find any missing functions. 

I am using Win32+D3D11 backends. 

This seems to be a problem with the rendering only as if I drag on where the imgui window should be, it will get popped out of the win32 window (i have multiviewport on). I broke into the debugger and looked at `ImGui::GetDrawData`, and it does not seem to be empty. 

My clear color is showing correctly and D3D11 does seem to be swapping the buffers every frame. 

I have one more piece of information, and that is I did not call `m_D3D11Context->OMSetRenderTargets(1, &m_D3D11Target, nullptr);` before clearing like it does in the example code, but if I do call this function, my clear color will not show correctly and the rendering issue is still not resolved. 

I have attached a video showing the problem. 

Any ideas on how I might approach debugging this problem?

https://user-images.githubusercontent.com/100400733/164343738-3b36d130-9a6a-4fa9-9289-973ed677a96b.mp4

_Originally posted by @ItsSunnyMonster in https://github.com/ocornut/imgui/discussions/5222_

**Comment by PathogenDavid** [comment]
> I know that this has been asked everywhere, but all of them seem to have made some careless mistakes like forgetting to call `ImGui_Implxxx_RenderDrawData` etc. but I've checked my code against the example code and did not find any missing functions.

This was my first thought upon hearing the problem. Are you 100% sure execution is hitting your call to `ImGui_ImplDX11_RenderDrawData`? (It's not totally clear from how you worded your `GetDrawData` check.)

> I have one more piece of information, and that is I did not call `m_D3D11Context->OMSetRenderTargets(1, &m_D3D11Target, nullptr);` before clearing like it does in the example code, but if I do call this function, my clear color will not show correctly and the rendering issue is still not resolved.

This is extremely suspect. The order of `OMSetRenderTargets` and `ClearRenderTargetView` should not matter since they don't affect each other.

I would check that you aren't presenting more than once per frame.

> Any ideas on how I might approach debugging this problem?

Since you've checked that you're calling `ImGui_ImplDX11_RenderDrawData` this is starting to sound like a Direct3D usage error somewhere in your app so I'd focus my attention there.

* [Enable the debug layer](https://docs.microsoft.com/en-us/windows/win32/direct3d11/using-the-debug-layer-to-test-apps) and make sure you don't have any messages coming from it.
* It's usually helpful if you can test rendering something that *isn't* Dear ImGui. (IE: Does rendering a Hello Triangle work?)
* [Debug your app using PIX](https://devblogs.microsoft.com/pix/download/)
  * You're going to want to do a GPU capture, [see the detailed documentation here](https://devblogs.microsoft.com/pix/documentation/).
  * (PIX is primarily designed for D3D12, but it does work with D3D11 too. I can't say I've ever used them together though, so if you run into issues with it you might try the older [Visual Studio Graphics Diagnostics tools](https://docs.microsoft.com/en-us/visualstudio/debugger/graphics/visual-studio-graphics-diagnostics) instead.)

**Comment by ItsSunnyMonster** [comment]
Thank you for the response! 

> This was my first thought upon hearing the problem. Are you 100% sure execution is hitting your call to ImGui_ImplDX11_RenderDrawData? (It's not totally clear from how you worded your GetDrawData check.)

I stored the result from `ImGui::GetDrawData` in a variable and used a breakpoint to see its value, and it does seem to contain a lot of vertices. 

> This is extremely suspect. The order of OMSetRenderTargets and ClearRenderTargetView should not matter since they don't affect each other.

I did not call `OMSetRenderTargets` at all because calling it makes the clear color disappear and it does not render anything still

> I would check that you aren't presenting more than once per frame.
 
I have checked that I did not present more than once per frame

> Since you've checked that you're calling ImGui_ImplDX11_RenderDrawData this is starting to sound like a Direct3D usage error somewhere in your app so I'd focus my attention there.

This is the most probable reason why this wouldn't work. The debug layer did not output anything. 

I've also checked my code line by line with the example main file and I've found a few differences that i think is unrelated to the problem but since im incredibly new to directx and win32 api i would put them here in case im wrong about one of them. 

1. The style field in the window class configuration struct is set to `CS_OWNDC` instead of `CS_CLASSDC` as in the example file.
2. The window styles that I used when creating the window are `WS_MAXIMIZEBOX | WS_MINIMIZEBOX | WS_SYSMENU | WS_CAPTION | WS_SIZEBOX | WS_OVERLAPPED` instead of `WS_OVERLAPPEDWINDOW` as in the example file.
3. I used `AdjustWindowRect` to resize the window so that the client area of the window is the size that gets passed in to my window creation function
4. I initialized D3D11 device and swapchain and render targets etc after calling `ShowWindow` and `UpdateWindow`
5. The buffer count of the swapchain description is set to `1` (supposedly `1` means double buffering) instead of `2` 
6. I did not specify a feature level when creating the device and the swapchain
7. I did not handle the `WM_SIZE`, `WM_SYSCOMMAND`, `WM_DESTROY`, and `WM_DPICHANGED` window events like they did in the wndproc of the example file

I think the the most suspect thing that might be causing the problem is the fact that when `OMSetRenderTargets` gets called not even the clear color shows.

**Comment by ItsSunnyMonster** [comment]
Thank you for your help! I eventually found the problem I was having from `OMSetRenderTargets`. I was using COM pointers to hold the `ID3D11RenderTargetView`. And the `&` operator of `ComPtr` Releases what was held at the pointer before returning the address. But `OMSetRenderTargets` doesn't output the render target, instead it just takes it in. So the render target end up getting released every frame and thats why i was getting a black screen. 

Closing the issue.
