### ISSUE TITLE
Keyboard input for iOS

### ISSUE THREAD

**Issue by jvcleave** [ocornut/imgui#526]
I am trying to implement Keyboard input for iOS. I have things somewhat working but with a slight quirk

The quirk is that when the keyboard first opens the input is not transmitted to the ImGui::InputText unless I tap the active window again and go back to typing. 

The implementation works with an additional Objective-C class that uses a dummy UITextfield in order to enable the keyboard and transfer the text to ImGui::InputText

https://github.com/jvcleave/ofxImGui/blob/master/example-ios/src/EditableText.h

(the above class is using my addon for openFrameworks but it shouldn't have any effect really)

Here are the basic steps I am doing

Create an `UITextField`
look for `ImGui::GetIO().WantTextInput`
if yes, open the iOS Keyboard
Capture the Key input into the UITextField and give it to ImGui::InputText
Set the UITextField text back (needed for editing/backspace)

I saw some things in the source like `SetKeyboardFocusHere` so I thought maybe there is something available that would allow me to use a workaround with a programmatic "click" the first time the Keyboard is opened

here is an Annotated video showing what I am doing
https://www.youtube.com/watch?v=l9rbqsoVifc

**Comment by ocornut** [comment]
If the cursor is showing blinking it means the widget should be active (which you may confirm by showing the Metrics window `ShowMetricsWindow()`.

> Capture the Key input into the UITextField and give it to ImGui::InputText

This is where you problem lies. Text input should be communicated / fed via io.AddInputCharacter()? When the input text is active and not read-only it carries/own the edited copy of the data, you can't just edit the source data under the hood, else it wouldn't be able to adjust the cursor correctly (it would need to do some magical diff between previous frame and current frame data?).

Notice in your video that focus has been LOST the second time, so you are editing your own buffer and the InputText widget is displaying your input because it isn't active.

So given the scheme that your code should feed characters via io.AddInputCharacter() it should be general code that runs and not tied to any specific widget.

It may be tricky however if you want to obtain the initial string value because your input system requires it. But your input method doesn't seem to use that value. Why are you doing `inputTextValue = [textField.text UTF8String];` ?

**Comment by jvcleave** [comment]
Thanks! I'll take a look at `AddInputCharacter`

I was saving inputTextValue mostly for the later `getText` convenience method. It may not be necessary in the end.

```char* getText()
    {
        return (char *)inputTextValue.c_str();
    }
```

**Comment by ocornut** [comment]
I added a comment to clarify that changing the input buffer under the hood while editing is active will be ignored. It is intentional and rather practical / rational (not doing that would requires a full compare, may add it as an option if someone needs it?) but I appreciate it may be a mismatch with what you'd expect for simpler data structures.

Also not everybody will see that comment (until we have better documentation).

**Comment by jvcleave** [comment]
I'm wondering if an easier route would be just to use `ImGui::Text` with some sort of click detection event.  UITextField could then just take the responsibility of editing the data.

**Comment by ocornut** [comment]
That's also a possibility, if your IME style wants to display it (rather than just trigger keys/characters), though features that rely on InputText such as Ctrl+clicking a drag/slider won't work.

In your situation I'm not sure to understand why you can't just forward the input via io.AddInputCharacter().

**Comment by ratchetfreak** [comment]
in draw you can start by doing 

```
ImGui::GetIO().AddInputCharactersUTF8(editableText.getInput());
editableText.clearInput();
```

That will forward the text input of the frame to the textedit box.the actual text should be saved in another buffer.

**Comment by jvcleave** [comment]
I have a version with `AddInputCharacter` working however Backspace yields "x". This might be tricky if the iOS UITextfield is passing Backspace as x

**Comment by ocornut** [comment]
Well surely backspace isn't x so you ought to figure out if you can obtain the correct data with osx.

**Comment by jvcleave** [comment]
As a test, should this work to make any key delete the previous character?

`    ImGui::GetIO().AddInputCharacter(ImGui::GetIO().KeyMap[ImGuiKey_Backspace]);`

**Comment by ocornut** [comment]
No. Keypresses != Character Input, you'd have to feed backspace in the KeysDown[] array at the KeyMap[ImGuiKey_Backspace] index which is under your control.

( Note that the current input design of imgui is flawed because character vs keypresses can't be ordered so within a same frame there's potential confusion if you typed very fast using both characters and keys. I hope to fix that with a redesign of the input system but for now it shouldn't be much of a dealbreaker problem if your application runs at decent framerate. At least, nobody has reported the issue so far even with keyboard input, presumably because there is a natural pause when user toggles between letters and backspace)

**Comment by jvcleave** [comment]
Ok, I am mainly trying to figure out what needs to be passed to `ImGui::GetIO().AddInputCharacter` in order for Backspace to work. I have an alternative way that I am able to detect if Backspace was pressed on the iOS Keyboard.

**Comment by ratchetfreak** [comment]
make sure the 0 <= KeyMap[ImGuiKey_Backspace]  < 512 and then do

```
ImGui::GetIO().keysDown[KeyMap[ImGuiKey_Backspace]] = true;
```

when backspace is down

**Comment by jvcleave** [comment]
Thanks @ratchetfreak, that got me closer. I'm not liking what I have to do iOS-wise so I think for this implementation I am going to go back to the idea of just using a `ImGui::Button`

Thanks everyone's help! It has helped me understand a bit more about the internals

**Comment by ukelady** [comment]
Hi @jvcleave , I would like to add an imgui textfield to my ios app and realize the keyboard doesn't show up. Is this what you've solved? Do you plan to share your solution? Thanks!

**Comment by jvcleave** [comment]
@ukelady here is what I did:
https://github.com/jvcleave/ofxImGui/tree/master/example-ios/src

**Comment by ukelady** [comment]
thanks!

**Comment by timprepscius** [comment]
Has there been any updates on ios with imgui regarding inputs (after 2017)

I've read his @jvcleave's code and it seems he bypasses all of the input mechanisms, by having an ios textfield and then copy pasting into ImGui::Text

are there any known working examples of using the AddInputCharacter?  Or a hidden UITextField?  I would like selectability if possible.

I'm thinking of either:
1. having hidden UITextField, whenever something changes, pushing the entire text field contents into imgui (somehow)
2. having hidden UITextField, getting the changes requested from the ios (character/backspace/whatnot) and forwarding to imgui (somehow)

3. making a virtual keyboard (hard with foreign languages)

Does anyone have any suggestions?

Thanks in advance!
