### ISSUE TITLE
Detecting mouse hovering ImDrawList primitives

### ISSUE THREAD

**Issue by davidalmarinho** [ocornut/imgui#5286]
**Version/Branch of Dear ImGui:**

Version: 1.86v
Branch: master

**My Issue/Question:**

Hi! I hope you are going great!
I am rendering lines and squares using ImDrawLists, but I am facing a problem since I started learning imgui some time ago.
Is there an imgui feature to know if the mouse is hovering over these squares or these lines from ImDrawList?
If not, is there some suggestion on how to do it?
Thanks!

**Comment by ocornut** [comment]
Those are geometrical question, you want to look at collision/intersection resources on the web.
Search for "distance from point to segment", "distance from point to rectangle" etc.
e.g. calculate distance from one point (mouse pos) to a segment, and when that distance is below a threshold you may consider a primitive as hovered.

Internally in imgui_internal.h we have one primitive that can be helpful for segment.

```cpp
ImVec2     ImLineClosestPoint(const ImVec2& a, const ImVec2& b, const ImVec2& p);
```
```cpp
// use with:
ImVec2 mouse_pos_projected_on_segment = ImLineClosestPoint(segment_a, segment_b, mouse_pos);
ImVec2 mouse_pos_delta_to_segment = mouse_pos_projected_on_segment - mouse_pos;
bool is_segment_hovered = (ImLengthSqr(mouse_pos_delta_to_segment ) <= max_distance * max_distance);
```

(note: In game programming we traditionally compare squared values `ImLengthSqr(xxx) <= dist* dist)` instead of non-squared values `ImLength(xxx) <= dist` solely because the earlier saves a square root calculation, but result is otherwise the same)

Generally this is a math/geometry question for which we don't provide solutions for low-level DrawList primitives, but you can find those functions on the internet.

**Comment by davidalmarinho** [comment]
> Those are geometrical question, you want to look at collision/intersection resources on the web.
Search for "distance from point to segment", "distance from point to rectangle" etc.

I didn't know that was the name of that. Now I can look for it better.

> Internally in imgui_internal.h we have one primitive that can be helpful for segment.
ImVec2     ImLineClosestPoint(const ImVec2& a, const ImVec2& b, const ImVec2& p);
// use with:
ImVec2 mouse_pos_projected_on_segment = ImLineClosestPoint(segment_a, segment_b, mouse_pos);
ImVec2 mouse_pos_delta_to_segment = mouse_pos_projected_on_segment - mouse_pos;
bool is_segment_hovered = (ImLengthSqr(mouse_pos_delta_to_segment ) <= max_distance * max_distance);

Nice. Yeah, I think that will be helpful.

> (note: In game programming we traditionally compare squared values ImLengthSqr(xxx) <= dist* dist) instead of non-squared values ImLength(xxx) <= dist solely because the earlier saves a square root calculation, but result is otherwise the same)

Makes sense, thanks for the insight.

> Generally this is a math/geometry question for which we don't provide solutions for low-level DrawList primitives, but you can find those functions on the internet.

Well, at least you have a helpful method and now I know what to look for.
Thanks :)
