### ISSUE TITLE
STL collections widgets

### ISSUE THREAD

**Issue by caxapexac** [ocornut/imgui#5313]
Version/Branch of Dear ImGui:

Version: 1.86
Branch: docking

Back-end/Renderer/Compiler/OS

Back-ends: webGL
Compiler: em++
Operating System: V8

My Issue/Question:
Haven't found any of abstract std::vector/map widgets in the wiki or anywhere (support of add/remove, move and maybe drag/drop). Do they exist? I thought it could be done with templates/macro to highly reduce amount of code needed to render simple collections

**Comment by rokups** [comment]
No idea what "std::vector/map widgets" are. Dear ImGui does not use STL containers. If you need to display contents of such container, you should iterate this container yourself and represent contents using imgui widgets however you like. It is impossible to provide such widgets displaying contents of container in the library, because these collections contain an undefined types of data which can be represented in infinite number of ways, and everyone would need a different form representation.

**Comment by ocornut** [comment]
The Wiki has inspectors to view contents:
https://github.com/ocornut/imgui/wiki/Useful-Extensions#inspectors-serialization

But they are generic systems. It’s often better to fine tune those based on your use case and data formats.

**Comment by caxapexac** [comment]
@rokups I meant at least unity-like collections inspectors for primitive data types
![image](https://user-images.githubusercontent.com/33996246/168739450-a073438f-bd8d-4758-ac7d-0388595e08b4.png)

Just in case anybody had already made this boilerplate, and of course I know this is pretty easy to implement. Anyway thanks
