### ISSUE TITLE
Add contribute page, CONTRIBUTING file and CODE_OF_CONDUCT file to the project 

### ISSUE THREAD

**Issue by monicaafilip** [ocornut/imgui#5337]
We should add the page and files mentioned in the title, as those files are good documentation to have as it is mantioned in the https://opensource.guide/how-to-contribute/#why-contribute-to-open-source page.

The contribute page should have some issues/bugs where every new contributor should start on, so there might be easy to fix bugs or issues not that hard to work on.

The CONDTRIBUTING.md file should contain basic information about the project as links to must-read files before contributing and how to contribute on it.

The CODE_OF_CONDUCT.md file should establish a way of communicating and maintaining good relationships between the member of the community created around this project.

**Comment by ocornut** [comment]
Hello,

Thanks for those suggestion.

We already have a Contributing Document at #2261, first pinned here and linked from both Issues and PR template.
I agree that for consistency we might move it to a CONTRIBUTING file, but it would make it less accessible for people browsing issues (one more indirection/click than currently), so I am not sure it would be a net win. Anyone interested in contributing would naturally find #2261. Perhaps CONTRIBUTING.md can instead contains a link to #2261 as well as other infos (copyright assignment).

Rather unfortunately, I nowadays tend to disagree about encouraging people to contribute. We have too many incomplete and low quality contributions already, people tend to do "drive by" pull requests and don't have the time, energy or skills to do things right (e.g. often, people are way off in dealing with performances requirements). Pull Requests are often a burden, the person does 50% of the work and needs us to review and do the other 50%. It's annoying to state but it is a reality. 

( Tangential, interesting read: https://press.stripe.com/working-in-public.  )

I'd rather keep people focused on fixing the problem they actually encounter doing real-world-use rather than encourage tourist-contributors to browse a random list of issues to find work. We don't often have "easy to fix bugs", people already underestimate side-effects of their fix attempts and don't put on the work to think about them. I think once we release the ImGuiTestEngine and tests database (in a few months) this may help a lot so I'm optimistic for that.

A short code of conduct would be good! I believe they are more meaningful in larger organizations. On small projects mostly represented by a single person there's always be an issue with that person (me) being potentially the person causing the issue and there's no one to report to. I think effectively the best effect of a code of conduct file is that it demonstrates some sort of goodwill, so I'm open to it but I don't think it would contains anything more that GitHub own CoC.

**Comment by monicaafilip** [comment]
I got it. 
Thank you for your time explaining these issues. I agree with all that you said, and I think at this moment we should close this issue, as it doesn't have any sense to solve it now.

Looking forward to help this opensource as I already used it and enjoyed working with it.

**Comment by ocornut** [comment]
I went ahead and actually created [CONTRIBUTING.md](https://github.com/ocornut/imgui/blob/master/CONTRIBUTING.md) because it seems sane to go on with that standard, and it is surfaced in GitHub UI on the right when opening an Issue/PR, and the Issue Template itself has the link (which I have just updated, see 814eced and b2c1310). The only drawback is missing Pinned link.

I noted GitHub has new/better template features which we are not using them and I will look into them.

Thanks for the suggestions!
