### ISSUE TITLE
Custom tab bar, and button in front of tabs.

### ISSUE THREAD

**Issue by Luci404** [ocornut/imgui#5342]
Version/Branch of Dear ImGui:
Version: 1.88
Branch: docking

Back-end/Renderer/Compiler/OS:
Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: Microsoft C++ compiler (CL.exe)
Operating System: Windows 10

My Issue/Question:
We are doing a UI overhaul on our internal game engine. The UI design folks came up with some pretty nice looking workspace tab bar design, but I have no idea how to implement it? We really like the default docking behavior of ImGui but we need a way to separate workspace. So what we want to do is, like unreal, having main workspace windows facilitating one workflow made up of multiple smaller tool windows.

My main question is how i style and draw this kind of menu bars, specifically, how do i get the red button in at the start of the bar and offset the tabs to make space for it?
I believe the rest of the style can be obtained with setting imgui style setting, but where should this be done?

![](https://i.gyazo.com/e1a6cce94d8034cb10b614421a8b58b0.png)
![](https://i.gyazo.com/f77283d3d3d4f3d125ffd33e8c8000b8.png)

**Comment by PathogenDavid** [comment]
You can't currently customize the docking tab bar in this way.

What I'd probably do is modify `DockNodeUpdateTabBar` to replace the default dock menu button (pictured below) with your special button.

![Screenshot of Dear ImGui's default dock menu button.](https://user-images.githubusercontent.com/278957/169907921-84c5a019-b6d7-4216-89a3-07af6885fd82.png)

The button is specifically submitted here:

https://github.com/ocornut/imgui/blob/250333d895b1067533533dcfab137512745b9689/imgui.cpp#L15291-L15298

Given your mockup I'm assuming you'd be disabling this button either way. It'd be easier to replace the button rather than disable it and add your own since disabling it entirely means you have to fiddle with the layout stuff in `DockNodeUpdateTabBar`.

(If you want your logo button to appear *everywhere* you probably want to edit `RenderWindowTitleBarContents` too since it's still used for free-floating windows. Or hijack to `CollapseButton` submit your button instead and always return false.)

If you plan to disable the dock menu/collapse button everywhere else, set `ImGuiStyle::WindowMenuButtonPosition` to `ImGuiDir_Left` when you submit your `ImGui::DockSpace` and `ImGuiDir_None` otherwise.

**Comment by ocornut** [comment]
We have two mecanisms which could be eventually toward that:
- It is possible to append to an existing tab bar using `BeginTabBar()`
- `BeginTabItem()` has support for `ImGuiTabItemFlags_Leading` and `ImGuiTabItemFlags_Trailing` flag has well as there is a `TabItemButton()` function. I believe the later could be reworked into a way to request leading/trailing space.

**Comment by Luci404** [comment]
This is interesting, I haven't tough of hijacking the collapseable button - that might actually be the play here. It could properly be done with some #define overrides on include, I'll have to look into that.

**Comment by ocornut** [comment]
> Would you be able to provide an example on how this would work in the context of a dockspace tab bar?

FYI I think you figured this out as per your post #5515 but to answer this: `DockNodeBeginAmendTabBar()`/``DockNodeEndAmendTabBar()` can be used.
