### ISSUE TITLE
ImGui::IsMouseXXX not working when called from user callback except for IsMouseDown

### ISSUE THREAD

**Issue by ahmidou** [ocornut/imgui#5384]
```
Dear ImGui 1.88 WIP (18724)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: IMGUI_DISABLE_OBSOLETE_FUNCTIONS
define: _WIN32
define: _WIN64
define: _MSC_VER=1932
define: _MSVC_LANG=201402
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000441
 NavEnableKeyboard
 DockingEnable
 ViewportsEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000140E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

Version:1.88
Branch: docking

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp _(or specify if using a custom engine/back-end)_
Compiler: visual studio 202
Operating System: windows 11

I'm not sure if this is by design or just missing, but in the following example, only ImGui::IsMouseDown is true.
example:
```
    // Setup Platform/Renderer backends
    ImGui_ImplGlfw_InitForOpenGL(window, false);
    ImGui_ImplOpenGL3_Init(glsl_version);

    glfwSetMouseButtonCallback(window, [](GLFWwindow* window, int button, int action, int mods)
    {
        ImGui_ImplGlfw_MouseButtonCallback(window, button, action, mods);

        std::cout << "callback called" << std::endl;
        if(ImGui::IsMouseClicked(0))
             std::cout << "mouse clicked in callback" <<std::endl;
        if(ImGui::IsMouseReleased(0))
            std::cout << "mouse released in callback" <<std::endl;
        if(ImGui::IsMouseDown(0))
            std::cout << "mouse down in callback" <<std::endl;
    });

    // Main loop
    while (!glfwWindowShouldClose(window))
    {
          ...
    }
```

**Comment by PathogenDavid** [comment]
This is sort-of by design. Short version: You should not use Dear ImGui's input functions in GLFW callbacks like this.

---------------

In the new queue-based IO API, input events are not processed until `ImGui::NewFrame` is called. (Additionally when `ConfigInputTrickleEventQueue` is enabled--which is the default--it might take multiple frames for the queue to processed.)

Basically what is happening in your scenario is that `ImGui_ImplGlfw_MouseButtonCallback` is queuing mouse button events, but Dear ImGui has not processed them. So `IsMouseClicked`/`IsMouseReleased`/`IsMouseDown` are returning the outdated mouse state as it was processed during the previous frame.

`IsMouseDown` appears to work is because you're reacting to the mouse being down during the previous frame during GLFW's mouse released event. (You can see this if you add `action` to your printout.) So you're actually reading the mouse as being down when physically it's been released.

Is there a reason you're using Dear ImGui's API to read the mouse button state when you have access to it from GLFW by virtue of being in the mouse callback function?

**Comment by ocornut** [comment]
Note this wouldn't even have worked with pre input-queue GLFW backend, since the `ImGui_ImplGlfw_MouseButtonCallback()` was merely setting an internal pressed flag: `MouseDown[]` wouldn't be updated. And `IsMouseClicked/IsMouseReleased()` always required a `NewFrame()` to function.

I cannot think of a good reason for using those functions in the GLFW callback indeed.

**Comment by ahmidou** [comment]
Thanks for the info, this was related to this workflow:
https://github.com/ocornut/imgui/issues/4937

I was confused as `IsMouseDown` was working.
Anyway, it all fine I'll make my own  Mouse/Keyboard handling then.
