### ISSUE TITLE
Using font icons in label with string variable?

### ISSUE THREAD

**Issue by jakerieger** [ocornut/imgui#5388]
**Version/Branch of Dear ImGui:**

Version: 1.87
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: MSVC 17
Operating System: Windows 10

**My Issue/Question:**

I was reading the doc on using icon fonts like Font Awesome in component labels like this example:
```cpp
ImGui::Begin(ICON_FA_FOLDER " Project");
...
ImGui::End();
```

This works great, but doesn't work if you want to use a variable for the string portion like this:
```cpp
const char* myStr = " Project";
ImGui::Begin(ICON_FA_FOLDER myStr);
...
ImGui::End();
```

I'm wondering if there's a way to do this or a workaround I can implement. Thanks!

**Comment by ocornut** [comment]
Using `"aaa" "bbb"` is compile-time string concatenation which only works on constant literals.
Otherwise you need to construct a string, e.g. 

```cpp
char buf[128];
snprintf(buf, IM_ARRAYSIZE(128), "ICON_FA_FOLDER %s", myStr);
ImGui::Begin(buf);
```

I would personally use my little Str helper (https://github.com/ocornut/Str) for that:

```cpp
ImGui::Begin(Str64f(ICON_FA_FOLDER " %s", myStr).c_str());
```

Most people nowadays are likely to use `std::string`:
```cpp
ImGui::Begin(std::string(ICON_FA_FOLDER " ") + myStr).c_str());
```
I personally dislike std::string because it tends to be much heavier allocation-wise, but that's probably only me and for most uses it is fine.

**Comment by jakerieger** [comment]
[https://github.com/ocornut/Str](https://github.com/ocornut/Str) is exactly what I'm looking for. Thanks!
