### ISSUE TITLE
Incorrect layout/clipping of autofitted child

### ISSUE THREAD

**Issue by nem0** [ocornut/imgui#540]
![imgui_clipping_bug](https://cloud.githubusercontent.com/assets/153526/13430830/00c9e7e2-dfc7-11e5-9900-8284fc816e77.png)

Steps to reproduce: 

1. add a child before a combobox in the demo 
2. fill the child with some text
3. observe incorrect clipping

```cpp
        if (ImGui::Button("Button")) { printf("Clicked\n"); a ^= 1; }
        if (a)
        {
            ImGui::SameLine();
            ImGui::Text("Thanks for clicking me!");
        }

        ImGui::BeginChild("abc");
        ImGui::Text("a");
        ImGui::Text("a");
        ImGui::Text("a");
        ImGui::Text("a");
        ImGui::Text("a");
        ImGui::Text("a");
        ImGui::EndChild();

        static bool check = true;
        ImGui::Checkbox("checkbox", &check);
```

Note: explicit size is clipped correctly  ``` ImGui::BeginChild("abc", ImVec2(0, 150))
Note: If I change 

```cpp
        if (window->Flags & ImGuiWindowFlags_ChildWindowAutoFitY)
            sz.y = ImMax(4.0f, sz.y - g.Style.WindowPadding.y);
```

to 

```cpp
        if (window->Flags & ImGuiWindowFlags_ChildWindowAutoFitY)
            sz.y = ImMax(4.0f, sz.y);
```

in ``` void ImGui::EndChild() ```, autofitted child is clipped correctly

**Comment by ocornut** [comment]
Thanks! Will look into it shortly. I recall make a small change to the child clipping test a month ago so it might be related.

**Comment by ocornut** [comment]
So it's not really a clipping problem but a layout problem.
EndChild() intentionally pass a little less to avoid growing an auto-sized parent and I think it also had the beneficial side-effect of making any (undesirable) further items visible to help identify issues. Normally it wouldn't make sense to use auto-fit on one axis and then add further items since they would always be past the visible limit.

It is fixable, however out of curiosity I wonder what is your actual use case where you noticed this, if you wanted to add widget after using size=y to a child and what you expect it should do.

**Comment by nem0** [comment]
![imgui_clipping_bug2](https://cloud.githubusercontent.com/assets/153526/13463103/f868d0f8-e08a-11e5-86f9-a499f933961d.png)
The checkboxes under "Brush type". At first I tried autofit, but fixed size is ok too. In fact it is probably better.

Edit: 
![imgui_clipping_bug3](https://cloud.githubusercontent.com/assets/153526/13463215/8f582748-e08b-11e5-94f8-f0d69288c9c0.png)
Found another place I am using it, in this case autofit is probably better.

Anyway, it is really questionable whether this is useful and I am absolutely fine with using fixed size.

**Comment by ocornut** [comment]
> The checkboxes under "Brush type". At first I tried autofit, but fixed size is ok too. In fact it is probably better.

Just to clarify, the auto-fitting in BeginChild() means the size of the child is derived from the available space within its parent window, it doesn't take account of any contents within the child window. So by this definition (which itself could be confusing or could be discussed) if you used size.y==0 in BeginChild() there's no meaning in submitting anything after EndChild().

> Found another place I am using it, in this case autofit is probably better.
> Anyway, it is really questionable whether this is useful and I am absolutely fine with using fixed size.

Second example, I assume the sequence is:
- "Profiler" pane is fixed height (using your docking system)
- Regular stuff up the "Clear" button
- BeginChild(..., ImVec2(0,0));  // consume space down to the bottom of the "Profiler pane"
- (list)
- EndChild()
- CollapsingHeader()

So there's a "Resources" section below the child. I'm not sure what you would expect to happens if you opened that section (assuming it output more stuff) and with the Child holding the list of models set to autofit. So I don't understand how autofit would work or be better.

With your fix above if I understand the situation correctly, your "Resource" collapsingheader would be invisible as it would exist below the bottom limit of the "Profiler" pane. It may create some odd feedback loop with the scrollbar, trying to use the scrollbar would extend the Child window further. So part of my intent with the code in EndChild() was to make those items slightly visible at the bottom at least to help identify that sort of bug a little more easily.

(I am genuinely interested in clarifying this, though, there is maybe a misunderstanding and if that is the case there is an improvement to make somewhere!)

**Comment by nem0** [comment]
> Just to clarify, the auto-fitting in BeginChild() means ...

That's exactly the way I thought

> So by this definition (which itself could be confusing or could be discussed) if you used size.y==0 in BeginChild() there's no meaning in submitting anything after EndChild().

If you submit anything after EndChild, a scollbar in the parent is created, exactly as I expect. 

> Second example, I assume the sequence is: ...

The sequence is correct

> So there's a "Resources" section below the child. I'm not sure what you would expect to happens if you opened that section (assuming it output more stuff) and with the Child holding the list of models set to autofit. So I don't understand how autofit would work or be better.

You can see it in action here 

![imgui_clipping_bug](https://cloud.githubusercontent.com/assets/153526/13471836/974ac4de-e0b2-11e5-920c-7e973ecc2796.gif)

This is exactly what I expect it to do, except for the layout bug. That being said I am completely fine with using fixed height if autofit is not intended to be used this way.

**Comment by ocornut** [comment]
> If you submit anything after EndChild, a scollbar in the parent is created, exactly as I expect. 
> This is exactly what I expect it to do, except for the layout bug. That being said I am completely fine with using fixed height if autofit is not intended to be used this way.

Hmm, OK I think I understand the issue better, thanks for clarifying.
It is a bit of an awkward situation, the height is derived from (window_height - current_pos_y) regardless of scrolling. I think I'm using the window height instead of ContentsSize.y because it would more frequently lead to feedback loop. So it works only once (if there was a second child auto-fitting it wouldn't get any space, or the minimum 4 pixels). So I guess there is a use for adding widgets after an auto-fitting child window if you don't use any auto-resizing (or double click corner) on the window.

I'll look into fixing it, I think the fix may be slightly different from what you posted to not affect parent auto-resizing in a simple auto-fitting-child-window case.

**Comment by ocornut** [comment]
OK this was much simpler than I expected (and so sorry for taking this long in discussions).
As it happens the `sz.y - g.Style.WindowPadding.y` which was once necessary not only wasn't needed anymore but was causing problems to auto-fitting of outer windows since the compensating code has been moved elsewhere.

**Comment by nem0** [comment]
:+1:
