### ISSUE TITLE
IRC channel

### ISSUE THREAD

**Issue by tambry** [ocornut/imgui#542]
Is there an IRC channel for (dear) ImGui, where users of the library could ask for help/discuss the usage/etc?

**Comment by ocornut** [comment]
No there isn't. I feel it wouldn't be constructive. The community is small and sparse and it would be better to conduct discussions on a medium that everyone can refer to and search in the future. 
In the absence of a forum treating this place as discussion place is also totally fine.

**Comment by tambry** [comment]
I see. I guess this make sense for such a project. I guess I'll be opening quite a few issues then.

**Comment by traw** [comment]
I think gitter or IRC would be better option for people who have some doubt about usage and may require immediate help. This in tern will keep Issues purely related to bugs and shortcomings. Just my two cents. 
I see currently there are 6,971 stars, So I don't think only few people are using it.

**Comment by ocornut** [comment]
IMHO this is treating symptoms rather than providing solutions. If someone doesn't understand how to use imgui, imgui needs to be improved (better code, docs, exemples, wiki). Everytime I explain something to someone I try to make a change to the library comments or example accordingly, or take note of doing so. I think anyone having doubt about usage IS a bug or shortcoming of the projsct :)

Answering on a medium with little visibility, i don't see a benefit when the exact same "immediate help" could be handled here, in a centralized place (easy to search for) and close to development (easy to turn feedback into action rather than just fix symptoms). 

I mean, feel free to spend time on that existing IRC channel if you guys like it, i just personnally currently have doubt of it doing a good job. I'd be happy to be proven wrong, but I don't think such a small community needs to be fragmented. 

The number of users is small, stars are merely bookmarks of people seeing the link on reddit or hackernews and casually thinking "this is interesting".
