### ISSUE TITLE
OpenGL/GLFW - Large performance decrease when bringing ImGui windows outside of GLFW window.

### ISSUE THREAD

**Issue by JensenJ** [ocornut/imgui#5430]
**Version/Branch of Dear ImGui:**

Version: 1.88
Branch: docking

```
Dear ImGui 1.88 (18800)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1930
define: _MSVC_LANG=201402
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000441
 NavEnableKeyboard
 DockingEnable
 ViewportsEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000140E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp 
Compiler: Visual Studio 2022 (CL)
Operating System: Windows 10 21H2

**My Issue/Question:**

I wanted to create a basic user interface for an application I am working on so I began experimenting with ImGui and noticed that whenever I dragged a viewport outside of the main GLFW window, the framerate of the entire application drastically decreased and locks to certain framerates, depending on the number of viewports outside the main window. The framerate seemed to be split evenly between all the windows if the maximum was 60fps. Dragging the ImGui viewport back into the bounds of the GLFW window allows the normal performance to continue immediately. 

I experimented around with settings such as changing the glfwSwapInterval to 0 to disable the framerate limit. When the ImGui viewport is running inside the GLFW window the framerate is around 1000-2000 fps as expected, but as soon as I drag an ImGui window out of the GLFW window it drops to 30fps (locked), with another window it drops to 20 (locked). At this point if another window is loaded inside the main GLFW window the framerate will stay locked at 20, but dragging it out drops the framerate to 15.

To confirm if this was something I had messed up on or was an issue caused by something else I loaded up the examples included with 
ImGui and in both OpenGL examples (openGL 2 and 3) the issue was here. The examples were unchanged except for a std::cout printing the framerate from ```io.Framerate``` inside the main loop. I decided to try using the directx12 example to see if this issue was unique to OpenGL and it was. The directx12 example works as expected, there is a slight drop in performance when the ImGui window crosses between the bounds of the main window but it quickly returned to how it was before. 

I have made sure I have the most recent versions of everything used in this test (to my knowledge) and have updated my graphics drivers also just to rule that out. I didn't see any other issues on the GitHub listed about this, and I'd imagine it would have been found by others by now, so I'm wondering if it is somehow something specific to my setup, even though it is about as basic as it can get.

**Screenshots/Video**

This gif only shows the framerate (shown in terminal window on left) decreasing not locking, this behaviour only occurs when recording the screen for some reason so I have provided screenshots to show the way it locks. All of these take place in the opengl3 example with glfwSwapInterval set to 0, this behaviour also occurs with it set to 1 however.
![imguiwindows](https://user-images.githubusercontent.com/13812018/176234830-b49a8e3c-bc6c-4e57-ba5e-a3850308c238.gif)
1 Window outside the GLFW window (30 fps):
<img width="1121" alt="imgui1window" src="https://user-images.githubusercontent.com/13812018/176234850-59f93c37-7931-4032-a96e-114339ad7e55.png">
2 Windows outside the GLFW window (20 fps):
<img width="1098" alt="imgui2windows" src="https://user-images.githubusercontent.com/13812018/176234855-8be69b98-858f-4bac-929e-5156dbb5ff6e.png">

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

This issue happens for me in the openGL examples provided with no modification.

**Comment by PathogenDavid** [comment]
I unfortunately can't really repro this. With vsync disabled in `example_glfw_opengl3` I get ~1400 FPS with everything in the main viewport, ~600 with one window outside the viewport, ~400 FPS with two, ~300 with three. With vsync enabled I get a consistent 60 FPS (other than the small hitch when the new OpenGL context is created.)

It is maybe worth noting that if I add writing the FPS with `std::cout` I do get a pretty significantly reduced (although still acceptable) framerate because writing to the console in Windows isn't super efficient. Do you still get sub-60 FPS you remove the console output and go off of the FPS listed in the example window instead?

**Comment by Fangjun-Zhou** [comment]
> It’s probably a driver feature or option or another application leading to forced vsync?

Apparently, this issue is not solved completely. My project run with GLFW + OpenGL3 on Windows.

I had a similar issue with my own project and I debugged it for over 5 hours and I finally got some clue.

To make sure it is not something related to my own code, I cloned the official repo and made some changes to the glfw + opengl3 example. Here's the result.

The only change I made is `glfwSwapInterval(1)` in the example. The original code is enabling the vsync. When I set it to `glfwSwapInterval(0)`, this should disable the vsync.

# 1. When `glfwSwapInterval(1)`(GLFW vsync enabled)

In this situation, when the second viewport is drawn in the original window, I got 100FPS, which is my display refresh rate. But when I dragged it out, it decreased to 50FPS(Sometimes it decreased to 25FPS). I think it's because some logic is executed twice a frame.

![glfw_vsync_on](https://user-images.githubusercontent.com/79500078/211751283-6a4437f2-3578-4e1d-bb0d-0289b97d85f2.gif)

# 2. When `glfwSwapInterval(0)`(GLFW vsync disabled)

In this situation, when the second viewport is drawn in the original window, I got over 2000FPS. But when I dragged it out, **it still decreased to 50FPS!!**. I think this is because the second window is still created with vsync on.

![glfw_vsync_off](https://user-images.githubusercontent.com/79500078/211751602-7e30d049-d180-4b2c-b83b-ec1d36c55b64.gif)

In `imgui_impl_glfw.cpp`, I saw that vsync is disabled when a new window is created:

![image](https://user-images.githubusercontent.com/79500078/211751778-8c1958da-2ef2-4f90-b47b-6366c2b92f89.png)

I even tried to force disable vsync in `ImGui_ImplGlfw_RenderWindow` and `ImGui_ImplGlfw_SwapBuffers`(I believe I don't need to do that), but it still doesn't work.

![image](https://user-images.githubusercontent.com/79500078/211752235-85656cf3-c855-4da6-ad14-196c62ef09e4.png)

# 3. When force disables vsync in the NVidia control panel

I finally decide to disable vsync in NV control panel.

![image](https://user-images.githubusercontent.com/79500078/211751835-e6fc029c-b0b1-45a6-9d6b-c825366378e8.png)

![image](https://user-images.githubusercontent.com/79500078/211751844-82dd7905-e658-420b-b79f-890cc5887ee3.png)

This time, every time a new window is created, the framerate dropped to 1/2(As mentioned in https://github.com/ocornut/imgui/issues/5430#issuecomment-1169032999). But it's still higher than my display refresh rate so it's not obvious enough for users to notice.

![nvidia_vsync_off](https://user-images.githubusercontent.com/79500078/211752605-aa93e9cc-cecf-40dc-b005-303cdfef4a10.gif)

This somehow solves the problem by completely disabling the vsync. But every time a new window is created, the framerate still dropped by one-half. Even if it's not a problem with my machine, I'm worrying that it can be an issue when users don't have a powerful graphic card.

**The most important thing is users need to disable vsync specifically in the NVidia control panel to avoid the unacceptable frame drop. I don't think that's an elegant solution.**

I really hope you can provide some support. If it's possible to fix this bug from the source (not letting the framerate drop when a new window is created), it will be the best. But at least, I'm really looking for a way to disable vsync at runtime, instead of asking users to disable it.

BTW, this is not an issue with the DirectX backend. But I'm using OpenGL for cross-platform support, so it's still a huge issue for me.

@ocornut Maybe you should reopen this issue.
