### ISSUE TITLE
Close button on title bar "X" stops function without if statement

### ISSUE THREAD

**Issue by efweber999** [ocornut/imgui#5431]
Version of Dear ImGui: 1.88 (18800)
Back-end: opengl3
Compiler: emscripten 3.1.14 (clang version 15.0.0)
Operating System: Linux Ubuntu 20.04.1
Browser: Firefox 101.0.1 (64-bit)

First, thank you for making Dear ImGui available. This is an awesome library!

This is a question, not an issue. I want to enable the close button "X" on the title bar. I had no trouble getting the X to appear, but it had no function. So I went back to main.cpp in examples/example_emscripten_opengl3 since it works in the demo. It turns out that it doesn't function if the "if (show_demo_window)" line is commented out. Functionally this should make no difference since show_demo_window is true. But since it does make a difference I'm obviously not understanding something. The attached file which demonstrates the lack function is main.txt is main.cpp from the examples/example_emscripten_opengl3 directory with the "if (show_demo_window)" line  commented out. 

Thanks,

Gene
![image](https://user-images.githubusercontent.com/81587911/176271350-ebda716a-1336-4140-8b06-f38618739376.png)

[main.txt](https://github.com/ocornut/imgui/files/9004295/main.txt)

**Comment by ocornut** [comment]
Program flow drives the UI everywhere in Dear ImGui so this is typical of Dear ImGui.

> but it had no function

It does has a function, it sets the bool to false when the X is clicked.

What's "surprising" in our design is that if you accidentally pass a pointer to a bool that is false to `Begin()` (which you should not) it still process normally. 

For that specific case, this is by design. Otherwise it would be more likely for users to submit everything regardless of that bool being false, and waste CPU on slower coarse-clipping. If we transition to a new Begin()/End() API where user will NEED to not submit when Begin() returns false we could  then optimally accept a a false value in `*p_open` as a way to force clippng.

**Comment by efweber999** [comment]
@ocornut thank you for getting back to me so quickly. Ahhh, that makes sense now. While I read that that it is looping and updating frames, my eyes see  a non-moving screen image and my brain forgets it is a loop. I was think of that if statement as a one time decision point when in fact it's being evaluated in a continuous look. Graphics programming is new to me.

Many Thanks!

Gene
