### ISSUE TITLE
Controller navigation: can't swap to Menu Layer when there's only generic decorations (e.g. no menu)

### ISSUE THREAD

**Issue by sacchin-conffx** [ocornut/imgui#5463]
**Version/Branch of Dear ImGui:**
Version: 1.88
Branch: docking (based on 9cd9c2eff99877a3f10a7f9c2a3a5b9c15ea36c6)

**Back-end/Renderer/Compiler/OS**
Back-ends: Custom
Operating System / Platform: PS4/PS5

**My Issue/Question:**
On console platforms (testing on PS4/PS5), pressing Square to toggle between the Main and Menu navigation layers does not work. Instead, it stays on the Main layer and can't swap to the Menu layer. After looking into it, I found that NavLayersActiveMaskNext is reset after RenderWindowTitleBarContents is called (collapse button) which clears the ImGuiNavLayer_Menu flag. My solution was to just move the below code (in the screenshot) to before RenderWindowTitleBarContents and it worked again.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/78611794/178356526-433ba3cd-3445-46ea-9fd0-e9e3b49b5d80.png)

**Comment by ocornut** [comment]
I can confirm there this is a regression in 37958ca1b5ecabeba1636a3d2e80661bf011a31d only affecting docking branch (commit was expected to merge back into master but didn't).

Specifically it happens when the only items on the menu layer are the generic Collapse and Close buttons. When there's an actual menu it works.

Will look into a fix.

**Comment by ocornut** [comment]
Pushed a fix 77637fd now. Thank you for reporting !
