### ISSUE TITLE
InputText + Unicode chars

### ISSUE THREAD

**Issue by ukenjutsu** [ocornut/imgui#5466]
`static char test[20 + 1];`
`ImGui::InputText("##Test", test, IM_ARRAYSIZE(test));`

Do you see the buffer size? It's exactly 20 characters
When I type normal characters like a-z, 1-9 (maybe some brackets or dots) everything works fine, I can type exactly 20 characters
But when I type some not ordinary unicode characters like § ™ » «, I can type only 10 characters (half of the buffer size)

So why do these characters take 2 bytes? I tested in imgui demo, same result

![unicode](https://user-images.githubusercontent.com/34518153/178801273-0f3b90ad-9354-46fc-a174-effe1b003294.png)

**Comment by PathogenDavid** [comment]
> So why do these characters take 2 bytes? I tested in imgui demo, same result

Because these characters inherently take multiple bytes when encoded as UTF-8. For instance, `§` is `0xC2 0xA7`.

The metrics window has a tool for viewing the raw encoding. In the examples, go to Tools > Metrics/Debugger > Tools > UTF-8 Encoding Viewer.

> It's exactly 20 characters

The name `char` in C/C++ is from an era when language-specific 8 bit encodings reigned supreme, in modern software you should think of it only as "an 8-bit value" rather than a specific character.

UTF-8 can use up to 4 bytes to represent a single Unicode codepoint. Some characters are represented by more than one codepoint. (This is especially true of emojis, 👩🏻‍🏫 "Woman Teacher: Light Skin Tone" is 15 bytes in UTF-8 because internally it's represented as `👩 🏻 [ZWJ] 🏫`.)

If you want to limit an input to exactly 20 characters, the size of the buffer is not the correct mechanism to do so unless you also want to restrict the characters which can be entered.

**Comment by ocornut** [comment]
Thank you @PathogenDavid for your detailed answer. Instead `char` in C/C++ is 1 byte whereas UTF-8 encoding takes a variable number of bytes (1 to 3 bytes most often) to represent codepoints.

I'm closing this topic, but:

> If you want to limit an input to exactly 20 characters, the size of the buffer is not the correct mechanism to do so unless you also want to restrict the characters which can be entered.

That's interesting. I think once we had template-based editing (for e.g. IP addresses) we may want to include a mechanism for specifying limits in number codepoints. That's for another day tho :)
