### ISSUE TITLE
Colors in logging example

### ISSUE THREAD

**Issue by etaZetaKaTheta** [ocornut/imgui#5470]
Version: 1.88
Branch: docking

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Operating System: Windows 10

Hello,
I have a question. In the log example (in the demo file), is it possible to colorize the found expression, because i can't find a way to do that without taking over some low level parts of this library.

Is there an easy way to do this?

Best regards,
etaZetaKaTheta

**Comment by elimerl** [comment]
Something like

```c++
for (int line_no = 0; line_no < LineOffsets.Size; line_no++)
{
	const char *line_start = buf + LineOffsets[line_no];
	const char *line_end = (line_no + 1 < LineOffsets.Size) ? (buf + LineOffsets[line_no + 1] - 1) : buf_end;
	if (Filter.PassFilter(line_start, line_end))
	{
		ImVec4 color;
		color = /* whatever */;
		ImGui::PushStyleColor(ImGuiCol_Text, color);
		ImGui::TextUnformatted(line_start, line_end);
		ImGui::PopStyleColor();
	}
}
```

replacing the for loop in the log demo?

**Comment by etaZetaKaTheta** [comment]
Thank you for your answer, to clarify,
I only want to colorize the expression that is getting searched, not the whole line.
Best regards,
etaZetaKaTheta

**Comment by rokups** [comment]
If you want to change color of the text then you would have to split up rendered text in substrings of different color and use a separate `TextUnformatted()` call for each substring, pushing your desired `ImGuiCol_Text` with `PushStyleColor()`/`PopStyleColor()`.

Another approach would be manually rendering rectangles behind or on top of the highlighted substring. Since log lines do not wrap it should be pretty simple to calculate positions for highlight rectangles by using `ImGui::CalcTextSize()`.

Note that `ImGuiTextFilter` is a little bit smarter than a plain substring search and it would be more difficult to support all it's expressions and you probably should use your own filter matching solution.

**Comment by ocornut** [comment]
For text coloring there are also discussions e.g. #3130 #902

For your crash it's likely an issue on your side, that class is simple and well supported.

**Comment by etaZetaKaTheta** [comment]
Hello, 

TextUnformatted works but this does not, so I am kind of confused.

Best regards,
etaZetaKaTheta

**Comment by etaZetaKaTheta** [comment]
Hello, 

I fixed it, caused by non-null-terminated string. I am retarded.
Thank you for your answers, I really appreciate it.

Best regards,
etaZetaKaTheta
