### ISSUE TITLE
Custom font loading making game run at 1FPS

### ISSUE THREAD

**Issue by TooFast4ya** [ocornut/imgui#5499]
Hello,
I've been trying to add a font with some Custom Icon's with directx11
It seems to be working but it slows my game down to 1 frame per second, I've trying to research this issue and can't 
seems to have a answer,  I'm hoping someone could answer this thanks,

This is how I'm implementing my font's and icon's,

`
---------

ImGui::CreateContext();
	ImGuiIO& io = ImGui::GetIO(); (void)io;

	io.Fonts->Clear(); // clear fonts if you loaded some before (even if only default one was loaded)

	ImFontConfig font_cfg;
	font_cfg.FontDataOwnedByAtlas = false; // if true it will try to free memory and fail
	io.Fonts->AddFontFromMemoryTTF((void*)poppinsFont, sizeof(poppinsFont), 18, &font_cfg);

	static const ImWchar icons_ranges[] = { ICON_MIN_FA, ICON_MAX_FA, 0 };
	ImFontConfig icons_config;
	icons_config.MergeMode = true; 
	icons_config.PixelSnapH = true; //
	icons_config.FontDataOwnedByAtlas = false;
	io.Fonts->AddFontFromMemoryTTF((void*)fontAwesome, sizeof(fontAwesome), 18, &icons_config, icons_ranges);

	ImFontConfig bigFontCfg;
	bigFontCfg.FontDataOwnedByAtlas = false; // if true it will try to free memory and fail
	io.Fonts->AddFontFromMemoryTTF((void*)fontAwesome, sizeof(fontAwesome), 18, &icons_config, icons_ranges);

	io.Fonts->Build();
	ImGui_ImplDX11_InvalidateDeviceObjects();

`

**Comment by PathogenDavid** [comment]
Make sure you aren't reloading the fonts every single frame. Rasterizing the fonts takes quite a while, especially when you load all of Font Awesome (which is over 6,000 glyphs -- double that since you're loading it twice.)

Ideally you should only load fonts once during initialization [like in the official examples](https://github.com/ocornut/imgui/blob/2d38bc99b3b0013952d3d390397297083b767972/examples/example_win32_directx11/main.cpp#L60-L73).

**Comment by TooFast4ya** [comment]
Perfect, I figured it out.
Thanks allot, looks like I had it at wrong place,
