### ISSUE TITLE
Setting ImGui viewport for VR.

### ISSUE THREAD

**Issue by blitz-research** [ocornut/imgui#5522]
Hi,

How do I get ImGui to restrict rendering to an arbitrary viewport within the framebuffer (I'm using opengl3 backend)?

I need to do this for stereoscopic rendering, where left half of frame buffer is what left eye can see, and right hand is right eye etc. Basically, I just want to draw the same thing twice for left/right eyes to start with.

I've just noticed SetNextWindow pos/size, is this the way to go? I could do that to set 'main' window same is left/right eye glViewport, and then always use 'BeginChild' everywhere - would this work?

Any other ideas?

Bye!
Mark

**Comment by PathogenDavid** [comment]
Are you trying to draw your Dear ImGui UI so that it's visible in the VR world or are you just wanting a UI that's only visible on your normal monitor outside of the headset?

----

It sounds like the former, but I'm not sure rendering the UI right onto the eye textures is going to result in a great experience for the user. I think most people draw their UI onto a render target texture and then render that onto a plan in VR space so that it's easier for the UI plane make physical sense. They're all a little dated, but see [this section on the wiki](https://github.com/ocornut/imgui/wiki/Useful-Extensions#virtual-reality-vr--reprojected-ui-plane) for references.

> I've just noticed SetNextWindow pos/size, is this the way to go? I could do that to set 'main' window same is left/right eye glViewport, and then always use 'BeginChild' everywhere - would this work?

You can't really get the same thing twice this way because as far as Dear ImGui is concerned the two windows will be different. So you'll only be able to interact with one or the other. IE: If you hovered a button it would only be highlighted in one of the eyes.

If you really want to try rendering a "flat" UI twice to get spectroscopy, the easiest way without modifying `imgui_impl_opengl3` would be to override `ImGuiIO::DisplaySize` right before you call `ImGui::NewFrame` (but after you call the `ImGui_ImplXYZ_NewFrame` functions for each backend), rendering to a render texture (rather than the framebuffer) and then render that texture to the screen twice.

**Comment by blitz-research** [comment]
Yes, I'm really just trying to some debug info up in VR space for now, more ambitious stuff later.

Thanks to your help, I did get it working although I had to hack the backend a bit,. But you're right, the user experience is not 'great' (it's bloody awful!) so rendering to texture is up next.

But I'm also curious to know what a properly 3d projected UI could look like - the fonts'd still be as crappy as scaling a texture, but the borders and other 'vector' stuff would look nice and sharp.

**Comment by blitz-research** [comment]
Closing this...

**Comment by PathogenDavid** [comment]
No problem, glad I could help! Thanks for making Blitz Basic, it was one of the first programming languages I learned back in the day 😁

And yeah, I can't imagine it looks great in the headset.

> the fonts'd still be as crappy as scaling a texture

If the text ends up being unacceptably rough you might check out the SDF fonts fork: https://github.com/ocornut/imgui/pull/4056
