### ISSUE TITLE
How to create overlay movable items ?

### ISSUE THREAD

**Issue by kevreco** [ocornut/imgui#553]
Hi Omar,

I'm currently playing with you library in my toy engine, thanks for this great library.

So, I have written a custom item to easily change the positions of any objects on a screen (just change values of a float[2]). See the .gif below (t represents a ray/ray intersection viewer)

![handle](https://cloud.githubusercontent.com/assets/6670943/13781360/f9fe8540-eaba-11e5-8040-ef422f345430.gif)

I called it an handle, I wrote a HandleLayerBegin/End function which contains a invisible window in the background then draw little draggable square items.

Then, just for the challenge I wanted to display handles on the top of any other items and windows. Actually if an handle is put on another window, it goes back to it and we can't catch it unless we move the window.
I tried to put the invisble window always on the top but in this case all inputs are catched by it. I didn't found a solution to forward inputs through it.

So the **question**: I am just wondering if there is any solution to draw and move "overlay" items not attached by a visible windows.

#### feedback and little demand

I tried to implement a new type of window by cloning ImGuiWindow, and cut all unnecessary stuff (I managed to find a uggly and overkill solution)
Two very little details distrubed me while I was browsing the source code.

First,for a long time when I always mixed up Begin() and End() with NewFrame() and EndFrame(). Oddely it took me a lot of time to get used to it.
It's not a big deal at all but BeginWindow and EndWindow will be clearer.

Second  the RenderDrawLists layer system, I came across:
```cpp
// FIXME: Generalize this with a proper layering system so e.g. user can draw in specific layers, below text, ..
```

Yeah, do it! :D
Not a big deal either, but I spent a certain time to know that sometimes RenderDrawLists [0] reffered to the standard window layer and sometimes it referrered to the first layer (to flatten the others).

Btw, the library is very well written, thanks again for that.
___

Here is the source code for interested people, be careful, it's not very well tested:

Handle Layer
```cpp
void ImGui::BeginHandleLayer()
{
    ImGuiState& g = *GImGui;
    ImGuiWindowFlags flags =
            ImGuiWindowFlags_NoBringToFrontOnFocus |
            ImGuiWindowFlags_NoTitleBar |
            ImGuiWindowFlags_NoMove |
            ImGuiWindowFlags_NoResize |
            ImGuiWindowFlags_NoSavedSettings;
    ImGui::SetNextWindowPos(ImVec2(0,0));
    ImGui::SetNextWindowSize(g.IO.DisplaySize);

    ImColor color(0, 0, 0, 0);
    ImGui::Begin("##HandleLayer", NULL, ImVec2(0,0), color, flags);
}

void ImGui::EndHandleLayer()
{
    ImGui::End();
}
```
Handle:

```cpp
bool ImGui::Handle(float pos[2], const ImVec2& size, bool centered)
{

    ImGuiWindow* window = GetCurrentWindow();
    const ImGuiID id = window->GetID(pos); // use the pointer address as identifier
    ImGuiButtonFlags flags = 0;

    ImGuiState& g = *GImGui;
    const ImGuiStyle& style = g.Style;

    ImVec2 handle_pos(pos[0], pos[1]);

    // Rect

    ImRect rect;
    if (centered) {
        const float half_y = (size.y / 2.0f);
        const float half_x = (size.x / 2.0f);
        rect = ImRect(handle_pos.x - half_x,
                      handle_pos.y - half_y,
                      handle_pos.x + half_x,
                      handle_pos.y + half_y);
    } else {
        rect = ImRect(handle_pos.x,
                      handle_pos.y,
                      handle_pos.x + size.x,
                      handle_pos.y + size.y);
    }

    ItemSize(rect, style.FramePadding.y);
    if (!ItemAdd(rect, &id))
        return false;

    bool hovered, held;
    bool pressed = ButtonBehavior(rect, id, &hovered, &held, flags);
    bool is_active = ImGui::IsItemActive();

    const ImGuiCol_ color_enum = (hovered
                                  || is_active
                                  || pressed
                                  || held) ? ImGuiCol_ButtonHovered : ImGuiCol_Button;

    ImGuiCol handle_color = ImColor(ImGui::GetStyle().Colors[color_enum]);

    ImDrawList* draw_list = ImGui::GetWindowDrawList();

    draw_list->AddRectFilled(rect.Min, rect.Max, handle_color, 4.0f);


    if (is_active && ImGui::IsMouseDragging(0)) {
        pos[0] += ImGui::GetIO().MouseDelta.x;
        pos[1] += ImGui::GetIO().MouseDelta.y;
    }

    return true;
}
```
Dumb example of use

```cpp

static ImVec2 pos_handle_a(100, 30);
static ImVec2 pos_handle_b(30, 100);
ImVec2 size(20, 20);

ImGui::BeginHandleLayer();

if (ImGui::Handle(&pos_handle_a.x, size, true)) {
    // Do something like show a tooltip when moving
}

if (ImGui::Handle(&pos_handle_b.x, size, true)) {
    // Do something like show a tooltip when moving
}

ImGui::EndHandleLayer();
```

**Comment by ocornut** [comment]
Hello and sorry to my late answer. It's often easier to answer for me if your post has a clear set of questions, here your post is going in many directions, but of course every situation is unique :)

It is quite unclear that you are trying to do without knowing more context. 

> So the question: I am just wondering if there is any solution to draw and move "overlay" items not attached by a visible windows.

Things that may be of use
- There is a `ImGuiWindowFlags_NoInputs` flag which may be useful in that sort of situation.
- With this and other flags it's generally easy to create a no-background window for the purpose of mostly drawing and not interacting.
- You may create and use ImDrawList directly provided you can manage to feed them to your renderer (e.g. add them to a separate list for your rendering function, or call the rendering function multiple times with a custom ImDrawData).

Also see some of those discussions:
https://github.com/ocornut/imgui/issues/545
https://github.com/ocornut/imgui/issues/530
https://github.com/ocornut/imgui/issues/566

For now you can use `GImGui->OverlayDrawList` declared imgui_internal.h as a convenience but I would like to implement something akin to what's requested #545

> I tried to implement a new type of window by cloning ImGuiWindow, and cut all unnecessary stuff (I managed to find a uggly and overkill solution)

Probably a very bad idea, unless you are willing to pay the cost of endless maintenance.

> First,for a long time when I always mixed up Begin() and End() with NewFrame() and EndFrame(). Oddely it took me a lot of time to get used to it. It's not a big deal at all but BeginWindow and EndWindow will be clearer.

That would be more correct indeed, however at this point we aren't going to change it. Also it is nice that one of the most commonly used function has a short name. As far as I know you are the first person to comment on it so I guess not many people got confused by it?

Interestingly I have just very recently exposed `EndFrame()` in imgui.h, it was previously in imgui_internal.h and I long hesitated to put in imgui.h because it is rarely used by the end user.
I just have undoed that change ( https://github.com/ocornut/imgui/commit/d53c308852bf15237987111a9f33cc507a08a3fa ) because it is very misleading. If you need to call EndFrame() without Render() it means you are throwing CPU at the window. So I'm moving it back to imgui_internal.h to reduce the possibility of confusion.

> Yeah, do it! :D
> Not a big deal either, but I spent a certain time to know that sometimes RenderDrawLists [0] reffered to the standard window layer and sometimes it referrered to the first layer (to flatten the others).

Playing with any of those internal data is totally unsupported and bound to break as a introduce more features. I would like to add those layers managements but I don't yet know how to parametrize the layering in a way that make good sense.

> bool ImGui::Handle(float pos[2], const ImVec2& size, bool centered)

Why not using ImVec2& pos?

> const ImGuiID id = window->GetID(pos); // use the pointer address as identifier

A bit weird! Totally ok if the user knows that otherwise if they pass local variable it'll break badly. Depending on your use case may want the user to pass an explicit `void*` id or let the user push into the ID stack.

Hope those answers help!
I am not really sure if you actually still need something so I am closing this but let me know if something is unclear.
