### ISSUE TITLE
Submenus not closing when hovering something else in the menu

### ISSUE THREAD

**Issue by BluTree** [ocornut/imgui#5546]
**Version/Branch of Dear ImGui:**

Version: 1.89 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Operating System: W11

**My Issue:**

When menu have submenus, the submenu is not always closed when moving from the submenu item to another item.
This often happens when we move the cursor slowly from the submenu item to the other item.

**Screenshots/Video**
![imgui](https://user-images.githubusercontent.com/11920536/183048703-618744d4-1b7a-4aa8-a301-2fa7d07ea13e.gif)

**Comment by ocornut** [comment]
We have intentionally logic in place that doesn't close a child-menu if you are moving toward it.

![image](https://user-images.githubusercontent.com/8225057/183054633-494a9769-47c9-4ca2-aed9-774ae9df1752.png)

This allows for menus to open/close without delay.

The way this logic works is currently not perfect.
- First of all, I just found a bug with it where in some cases it didn't enable at all (will try to fix soon): but that's not your problem since in your case it is enabled.
- When enabled it's a bit too flaky right now and I think we should improve it and use a sort of decay timer.

But I have to ask you if you reported that as a curiosity you noticed but if you genuinely felt the interaction was problematic in your daily usage?

**Comment by BluTree** [comment]
Thanks for your response !

I understand the purpose of the logic, but in the case I am, it is more a problem.
To explain quickly what I wanted to do, I wanted to create a delay before a submenu shows when hovering the item (by having a MenuItem, and replacing it by a submenu when the timer is finished).
With the logic of not closing the submenu while the mouse goes closer to it, my timer cannot reset if the mouse is still in the triangle (since the IsHovered of the other item will be false), and I find this problematic.

Right now the BeginMenu doesn't take any other parameters than its label and its enablement, so an alternative could be to add a flag when we want to disable this behaviour ?

**Comment by ocornut** [comment]
> To explain quickly what I wanted to do, I wanted to create a delay

Why ? Always explain why otherwise I'll assume this is a [XY Problem](https://xyproblem.info/) question.

**Comment by BluTree** [comment]
The menus I'm working on is to preview windows as submenus, that will open as real windows when clicking on the submenu item. We wanted to create that delay to avoid previewing the window at the first frame, but after the user keep the mouse during that delay.

**Comment by ocornut** [comment]
I don't think you need to use `MenuItem()` or `BeginMenu()` at all. Use e.g. a `Selectable()` and you can show your preview in a tooltip which you can position with `SetNextWindowPos()`.

**Comment by BluTree** [comment]
Oh yes, a selectable can totally do the work indeed, I just need to see how the submenu position is computed to recreate this for my tooltip. Thanks for the advice.
