### ISSUE TITLE
Help wanted: Making SetScreenPos() not extend parent boundaries?

### ISSUE THREAD

**Issue by ocornut** [ocornut/imgui#5548]
## Context 

For a while calling `SetCursorPos()` or `SetCursorScreenPos()` (respectively since since 1.31 and 1.50, aka centuries ago), also had the side-effect property of automatically "extending" the contents boundaries. So it would feed that info for auto sizing of parent window, parent column, group etc:

```cpp
Begin("Test", NULL, ImGuiWindowFlags_AlwaysAutoResize);
SetCursorPos(GetCursorPos() + ImVec2(100, 100));
End();
```
Would make the window roughly (100,100) + padding. Ditto for e.g. auto-resizing a column without submitting items or specifying an actual width.

For some reasons I think it would be more sane if this behavior changed so only item would extend those boundaries. E.g. requiring least a dummy item:
```cpp
Begin("Test", NULL, ImGuiWindowFlags_AlwaysAutoResize);
SetCursorPos(GetCursorPos() + ImVec2(100, 100));
Dummy(ImVec2(0, 0));
End();
```
or simply
```cpp
Begin("Test", NULL, ImGuiWindowFlags_AlwaysAutoResize);
Dummy(ImVec2(100, 100));
End();
```

Basically the change would consist in removing the `CursorMaxPos` assignment in four functions:
```cpp
void ImGui::SetCursorScreenPos(const ImVec2& pos)
{
    ImGuiWindow* window = GetCurrentWindow();
    window->DC.CursorPos = pos;
    //window->DC.CursorMaxPos = ImMax(window->DC.CursorMaxPos, window->DC.CursorPos);
}

void ImGui::SetCursorPos(const ImVec2& local_pos)
{
    ImGuiWindow* window = GetCurrentWindow();
    window->DC.CursorPos = window->Pos - window->Scroll + local_pos;
    //window->DC.CursorMaxPos = ImMax(window->DC.CursorMaxPos, window->DC.CursorPos);
}

void ImGui::SetCursorPosX(float x)
{
    ImGuiWindow* window = GetCurrentWindow();
    window->DC.CursorPos.x = window->Pos.x - window->Scroll.x + x;
    //window->DC.CursorMaxPos.x = ImMax(window->DC.CursorMaxPos.x, window->DC.CursorPos.x);
}

void ImGui::SetCursorPosY(float y)
{
    ImGuiWindow* window = GetCurrentWindow();
    window->DC.CursorPos.y = window->Pos.y - window->Scroll.y + y;
    //window->DC.CursorMaxPos.y = ImMax(window->DC.CursorMaxPos.y, window->DC.CursorPos.y);
}
```

But it may be difficult to immediately notice if this changes break something, so I've added code to detect if it makes a change....

## Help Wanted

Could some of you with non-trivial codebase try some code to find those one?

I am interested in hearing side effects of changing that existing property (I  think there are good reasons for changing it).

**I have prepared a branch you can use:**
https://github.com/ocornut/imgui/tree/features/check_for_setcursorpos_extending_boundaries

**Or a simple commit you can cherry-pick:**
https://github.com/ocornut/imgui/commit/9423e42712683ecc9e8436597df9fff1563a9704

You can set a breakpoint of the debug log in `CheckUsedSetCursorPosWithSideEffect()`, or open `Demo->Tools->Debug Log` and see if it triggers in your application.. interested in feedback.

Thank you!

**Comment by thedmd** [comment]
There are some differences. I might need to use `ImGui::Dummy()`.

![image](https://user-images.githubusercontent.com/1197433/186736809-e6591e13-be24-4d11-85b7-4cfa71e0a756.png)

**Comment by ocornut** [comment]
Did the `CheckUsedSetCursorPosWithSideEffect()` function detect them in your case?

**Comment by thedmd** [comment]
Actually yes, it found some problems. I didn't saw debug message.
![image](https://user-images.githubusercontent.com/1197433/186738691-c8108aeb-c1f8-4c21-abd0-5a6661bfe38c.png)

**Comment by thedmd** [comment]
Identified and fixed.
I had to use two ImGui::Dummy() calls. First one was used to 'touch' cursor at the end of the line, second apply padding.

In case this variant is worth mentioning there is a change I had to made:
```cpp
// ✅
ImGui::SameLine(0, editorStyle.NodePadding.z);
ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(0.0f, 0.0f));
ImGui::Dummy(ImVec2(0, 0)); // bump cursor at the end of the line and move to next one
ImGui::Dummy(ImVec2(0, editorStyle.NodePadding.w)); // apply padding
ImGui::PopStyleVar();
```
from
```cpp
// ❌
ImGui::SameLine(0, editorStyle.NodePadding.z);
ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(0.0f, 0.0f));
ImGui::Dummy(ImVec2(0, 0));
ImGui::PopStyleVar();
ImGui::SetCursorPosY(ImGui::GetCursorPosY() + editorStyle.NodePadding.w);
```

**Comment by ocornut** [comment]
Thank you!
I went ahead and applied edcd5b11 (assert with `IMGUI_DISABLE_OBSOLETE_FUNCTIONS`, silently fix without, will obsolete later).

I went and searched 100+ threads for keyboard, and found that the incorrect pattern has been mentioned or suggested in: #4510, #3355, #1760, #1490, #4152, #150. I will now amend the threads/posts to refer to this.

Changelog says:
- Obsoleted using SetCursorPos()/SetCursorScreenPos() to extend parent window/cell boundaries.
   This relates to when moving the cursor position beyond current boundaries WITHOUT submitting an item.
   - Previously this would make the window content size ~200x200:
       `Begin(...) + SetCursorScreenPos(GetCursorScreenPos() + ImVec2(200,200)) + End();`
   - Instead, please submit an item:
       `Begin(...) + SetCursorScreenPos(GetCursorScreenPos() + ImVec2(200,200)) + Dummy(ImVec2(0,0)) + End();`
   - Alternative:
       `Begin(...) + Dummy(ImVec2(200,200)) + End();`
   - Content size is now only extended when submitting an item.
   - With '#define IMGUI_DISABLE_OBSOLETE_FUNCTIONS' this will now be detected and assert.
   - Without '#define IMGUI_DISABLE_OBSOLETE_FUNCTIONS' this will silently be fixed until we obsolete it.

For reference this is the issue what we aim to fix with this change:
`BeginGroup() + SomeItem("foobar") + SetCursorScreenPos(GetCursorScreenPos()) + EndGroup()`

The previous logic made SetCursorScreenPos(GetCursorScreenPos()) have a side-effect! It would erroneously incorporate ItemSpacing.y after the item into content size, making the group taller!  While this code is a little twisted, no-one would expect SetXXX(GetXXX()) to have a side-effect. Using vertical alignment patterns could trigger this issue.

(I am also copying part of this to the message on top of this thread)

**Comment by bartico6** [comment]
Hey, I know I'm a little late but I only recently updated from a centuries-old version to the newest one and this change seems to impact the usecase of optimised scrollable child windows really hard:

Take this example: A replacement chatbox for a game
![image](https://github.com/ocornut/imgui/assets/3310937/5d1736e1-9873-4e8e-a19b-9f77a73d6743)
And this corresponding render code
![image](https://github.com/ocornut/imgui/assets/3310937/524dc3c0-099f-4be9-af6f-181163c292ad)

In versions before this change, the "is message visible" call was used to optimise the chatbox by not rendering things that aren't visible to the user - as the act of rendering the color codes, processing the game's chat formatting etc. was pretty expensive.

So, we precompute the line's size in the chatbox, store it alongside the chat entry, and if `ImGui.IsRectVisible` of that message returns false, we just advance the cursor position as if we rendered the message...

... right, and this doesn't work anymore :p

So now, the chat with hundreds of entries only has a MaxScrollY of 23.0, seen here:
![image](https://github.com/ocornut/imgui/assets/3310937/4ff61c99-19a4-40ae-a2fd-26e08de9fc07)

... trying to scroll down very slowly uncovers parts of the rects of other messages, thus making for a very painful scrolling experience, and it also fails to scroll down to the newest entry because SetCursorPosY doesn't actually resize the child view anymore.

I can/will probably make it push an invisible button or a dummy object instead of SetCursorPosY like you mentioned, so it's not a big problem, but I just wanted to answer the call to "test on a non-trivial codebase", albeit very late.

Great idea to embed this in the code-changelog by the way - that was the first place for me to consult what changed and by searching for SetCursorPos I found this :heart:

**Comment by v-ein** [comment]
Hi there - here's one more user late to the train 😁

I've just found this issue (yes, by updating from an older version of Dear ImGui 😂), but in my case SetCursorPos is used for a different purpose: not to specify the content size but to restore the cursor pos from a saved position.

This actually happens inside of DearPyGui. For many items, you can pull them out of "normal flow" by specifying an absolute position - in this case, DearPyGui saves cursor position before rendering the item and restores it afterwards. Something like this:

```cpp
// cache old cursor position
ImVec2 previousCursorPos = ImGui::GetCursorPos();
// set cursor position if user set
if (item.info.dirtyPos)
    ImGui::SetCursorPos(item.state.pos);

activated = ImGui::Button(...);

// set cursor position to cached position
if (item.info.dirtyPos)
    ImGui::SetCursorPos(previousCursorPos);
```

No wonder this triggers an assert on the most recent version of ImGui. I'm not trying to specify the contents size, all I want is to go back to the state that I had before rendering that button - so that any new items would follow the normal flow as if there was no button at all, and if there are no other items, the window or group would just end right there, at the position before the button was added.

The question is, what is the proper way of saving and restoring cursor position in this case? I can add a `Dummy` - but this requires zeroing out the vertical item spacing as well, which makes the code restoring cursor position look somewhat bulky, so I'll put it into a separate function... and I just thought maybe there's a more elegant way. Any suggestions? Does or will ImGui have any other functions to save/restore cursor position?

**Comment by redpartizan** [comment]
I'm not sure if it is related but I see the assert is triggered when I'm trying to put a table inside a popup. I had to uncomment the following lines in SetCursorPos*() methods to fix that:

```
void ImGui::SetCursorPos(const ImVec2& local_pos)
{
    ImGuiWindow* window = GetCurrentWindow();
    window->DC.CursorPos = window->Pos - window->Scroll + local_pos;
// CO-> The next line was commented out.
    window->DC.CursorMaxPos = ImMax(window->DC.CursorMaxPos, window->DC.CursorPos);
// <-CO
    window->DC.IsSetPos = true;
}

void ImGui::SetCursorPosX(float x)
{
    ImGuiWindow* window = GetCurrentWindow();
    window->DC.CursorPos.x = window->Pos.x - window->Scroll.x + x;
// CO-> The next line was commented out.
    window->DC.CursorMaxPos.x = ImMax(window->DC.CursorMaxPos.x, window->DC.CursorPos.x);
// <-CO
    window->DC.IsSetPos = true;
}

void ImGui::SetCursorPosY(float y)
{
    ImGuiWindow* window = GetCurrentWindow();
    window->DC.CursorPos.y = window->Pos.y - window->Scroll.y + y;
// CO-> The next line was commented out.
    window->DC.CursorMaxPos.y = ImMax(window->DC.CursorMaxPos.y, window->DC.CursorPos.y);
// <-CO
    window->DC.IsSetPos = true;
}
```

**Comment by ocornut** [comment]
@v-ein @redpartizan Would you mind both opening new issues for this to not fly under the radar? Will look into them.

**Comment by v-ein** [comment]
Yep, will do!
