### ISSUE TITLE
Support for 64-bits Windows?

### ISSUE THREAD

**Issue by ArkAngeL43** [ocornut/imgui#5594]
Not a bug rather a question, is there any support for 64 bit windows systems? i only see windows 32 bit examples not 64

**Comment by PathogenDavid** [comment]
Yes, Dear ImGui supports x64. It's not totally clear what you're looking at that implies otherwise.

If you're referring to the example/backend names: ["Win32" is just the name of the Windows API](https://docs.microsoft.com/en-us/windows/win32/desktop-programming). It can be used in modern Windows regardless of architecture.

**Comment by ArkAngeL43** [comment]
thank you
