### ISSUE TITLE
Window is slightly off when application is closed and restored back from imgui.ini file

### ISSUE THREAD

**Issue by 0xbeefeed** [ocornut/imgui#5669]
**Version/Branch of Dear ImGui:**

Version: latest, downloaded like a hour ago
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Operating System: Lİnux

**My Issue/Question:**

When application is quit and reopened again, window position is not restored correctly, window gets centerized while what would be expected window would be at position last time before application was quit.

**Screenshots/Video**

https://user-images.githubusercontent.com/109395331/189468976-68e934ff-81b5-4d56-810d-2782dbc4d411.mp4

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Window");
// just the window
ImGui::End();
```

**Comment by ocornut** [comment]
This won’t repro in the main application. So clearly you have something in your application that is interfering which you omitted you mention. This is why we need a VERIFIABLE example. Please do the work of making one otherwise we can’t magically guess what else is running in your application. We can re-open this once more infos are provided.
