### ISSUE TITLE
sdl1.2  

### ISSUE THREAD

**Issue by codz01** [ocornut/imgui#576]
Hi
is it possible to use imgui with sdl 1.2 ?

**Comment by ocornut** [comment]
As long as you have a way to render hardware accelerated textured triangles you can use it.

**Comment by codz01** [comment]
i didn't mean the rendering ,but the input 
there is some events like SDL_TEXTINPUT , SDL_MOUSEWHEEL  which exists in sdl2 but not in sdl1.2  
i was trying to port sdl2 example to sdl1.2 but i stuck in this issue

**Comment by ocornut** [comment]
Well you'd have to figure out how to get the information from SDL 1.2 then. It's not really an ImGui issue at this point.

**Comment by jarikomppa** [comment]
There are ways to get the same effect in sdl 1.2.. mousewheel was (as far
as I recall) bound to further mouse buttons, and text input is some other
event, and you need to enable unicode input through a separate call.

However, you don't technically need either of these for imgui to work; you
can just leave them unimplemented. (Of course text input and mouse wheel
won't work, but you can get going otherwise..)

**Comment by codz01** [comment]
@ocornut  It's not really an ImGui issue at this point.
thats true , sorry for the noise ;) 
@jarikomppa  : many thanks ,  you already did it  in this project : [proctree](https://github.com/jarikomppa/proctree/blob/master/happytree/main.cpp) .
