### ISSUE TITLE
full screen support

### ISSUE THREAD

**Issue by Bob-F** [ocornut/imgui#583]
It seems that there is no full screen support at least in the demo app running on Windows. In some cases (e.g., game, video player) full screen without windows frame is needed. It's better to have a way to go into and exit from full screen.

**Comment by ocornut** [comment]
Hello Bob,
Sorry but that doesn't seem to relate in any to ImGui. 
ImGui isn't a game or application framework, the demo app are trying to be as simple as possible so you can copy and paste bits of the sources in your own application. It is hard enough to keep those demo working and in sync I don't see the point in adding superfluous features to them.

**Comment by Bob-F** [comment]
Hi Omar,

When ImGui is used to develop an application which needs full screen in some cases, how to go to full screen with ImGui ?

Also minimizing and maximizing window seems to be a standard feature, but the windows in the demo app seems not be able to do that.

Thanks!

**Comment by ocornut** [comment]
> When ImGui is used to develop an application which needs full screen in some cases, how to go to full screen with ImGui ?

That question has nothing to do with ImGui, since it doesn't manage your OS window. ImGui generate vertex buffers that your application renders. Being fullscreen or not doesn't affect that. DisplaySize can be be adjusted every frame so it is possible to change resolution at runtime.

> Also minimizing and maximizing window seems to be a standard feature, but the windows in the demo app seems not be able to do that.

It would be extra work to support it across all examples and not have benefits in term of demonstrating ImGui. I wouldn't mind a patch for some of the example if it doesn't add too much noise to the code, but it certainly isn't a requirement.

I am sorry I have to close that issue. If you want to submit a pull request to fix the maximize button in example apps, I'll take it. I have noted a line in the todo list with a reference to this issue number so it may happen eventually :)

**Comment by caelwithcats** [comment]
OPEN THIS ISSUE, NOW! I need full-screen in my application
