### ISSUE TITLE
Checking if window has focus doesn't take into consideration other OS windows

### ISSUE THREAD

**Issue by meemknight** [ocornut/imgui#5882]
```cpp
ImGui::IsWindowFocused(); 
```
Returns if the window is the current ImGui window that has focus but doesn't take into consideration if it is focus in regard to other running apps. I don't have a problem with the way it is made but is there a way to check if that window is also the current focused os window?

Is there a way to do something like this?

```cpp
ImGui::IsWindowFocused() &&  IsWindowFocused(GetCurrentOsWindowFromCurrentImguiWindow());
```

**Comment by PathogenDavid** [comment]
Correct, `IsWindowFocused` is checking if a window is focused from the perspective of Dear ImGui. It doesn't take anything else into consideration.

Checking whether your app has focus is platform-specific and since you didn't fill out the issue template we can't know what platform you're on. (Either way it's outside the scope of what's relevant on this repo.)

That being said, if you're on Windows you can check if any of your app's windows have focus using `GetActiveWindow() != NULL` on the UI thread.

**Comment by ocornut** [comment]
As an undocumented thing, we maintain io.AppFocusLost on modern backends, we could probably rename it to io.AppHasFocus which is digest to digest and make it a documented ?

**Comment by PathogenDavid** [comment]
I stand corrected! Totally forgot backends handled focus events.

**Comment by meemknight** [comment]
will appFocusLost be true for all uncoused windows?
Changing it to io.AppHasFocus seems like a usefull feature

**Comment by ocornut** [comment]
This will be focus of the whole app aka the main window or any secondary dear imgui viewport.

To check OS focus for one specific viewport you may obtain the `ImGuiViewport*` and call `bool GetPlatformIO().Platform_GetWindowFocus(viewport);`

**Comment by ocornut** [comment]
> but it seems to crash when moving the window outside the main window

Happens on the first frame of a new viewport, as `Platform_CreateWindow()` hasn't been called yet. Internally we prefix our calls with this check:
```
if (viewport->PlatformWindowCreated)
    if (g.PlatformIO.Platform_GetWindowFocus(viewport))
        ....
```
- I pushed d2f9c5d to move `PlatformWindowCreated` from private `ImGuiViewportP` to public `ImGuiViewport`
- Or instead `if (viewport->PlatformUserData != NULL && g.PlatformIO.Platform_GetWindowFocus(viewport))`

Right now it's not reasonable to move that responsibility from caller to backend because it would encourage "silently fail" behavior which I dislike.

**Comment by ocornut** [comment]
I have now tried to add `io.AppFocused` but:

- `io.AppFocusLost` is still needed as a trigger to allow app/engine to do custom clearing/cancelling operation. That's fine we can keep it!
- `io.AddFocused` (== current state) cannot be reliably implemented as we don't have the INITIAL app state sent: neither Win32 nor SDL backends are generating an initial `io.AddFocusEvent()` event on window creating. Defaulting to `true` would be technically incorrect. I'd prefer to not add it and instead let you do the polling for now.

**Comment by ocornut** [comment]
Closing this for now as I believe calling `Platform_GetWindowFocus()` answers the question.

I believe there are possibilities that:
- We add a bool Focused flag to `ImGuiViewport` eventually.
- We add an additional flag to `IsWindowFocused()` to check the platform/native state.

If this change we'll post here.

**Comment by meemknight** [comment]
thank you, I'll look into it.

**Comment by OneArb** [comment]
> calling `Platform_GetWindowFocus()` answers the question.

Could you please provide an example. I am trying to run with no succes:
```
    ImGuiPlatformIO& platformIO = ImGui::GetPlatformIO();
    ImGuiViewport* viewport = ImGui::GetMainViewport();

    if (viewport->PlatformWindowCreated)
        if (platformIO.Platform_GetWindowFocus(viewport))
            ImGui::Text("platformIO.Platform_GetWindowFocus(viewport) %d",
                         platformIO.Platform_GetWindowFocus(viewport));
                         
```

**Comment by PathogenDavid** [comment]
@OneArb The platform IO functions are provided by the backend.

If `ImGuiConfigFlags_ViewportsEnable` is not set during backend initialization those functions will not be provided.

**Comment by PathogenDavid** [comment]
@OneArb Yeah, the backend must support viewports. (It's odd you got core dumped, but maybe your backend is barfing on something with viewports enabled.)

`ImGuiIO::AppFocusLost` does sound like what you want, but keep in mind it requires support from the backend as well.

> I'd need an example on how to pull that event from the queue.

Calling `AddFocusEvent` is what drives the value of `AppFocusLost`. Ut's meant to be called from the backend.

If you're using [thegwydd/ImGuiOrx](https://github.com/thegwydd/ImGuiOrx), it does not appear that it supports focus events. (Or the modern input queue at all -- it's quite dated.)

----------

You might be better off approaching this from an Orx angle rather than a Dear ImGui one. Dear ImGui doesn't *really* know anything about operating system windows, apps, or app focus. Those responsibilities fall on the backend.

If you have access to the `GLFWwindow*` used by your app, you should be able to install a focus callback with `glfwSetWindowFocusCallback`.

You might need to chain-call the original callback if Orx installed one of its own. You can see examples of how to do this by searching for `PrevUserCallbackWindowFocus` in [`imgui_impl_glfw.cpp`](https://github.com/ocornut/imgui/blob/5a2b1e84828f192d30c91cdd210db41de8ad3236/backends/imgui_impl_glfw.cpp#L453).
