### ISSUE TITLE
Mouse and keyboard events at the same time

### ISSUE THREAD

**Issue by jzubizarreta** [ocornut/imgui#5888]
**Version/Branch of Dear ImGui:**

Version: 1.89
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_vulkan.cpp
Compiler: MSC_VER=1933
Operating System: Windows 10

**My Issue/Question:**

Hey, I'm trying to obtain mouse and keyboard events when the mouse is hovering a specific window. More specifically, I'm trying to check if both the left mouse button and the ctrl key are down/pressed. However, I'm only getting events from one of them at the same time, even when both are pressed. If I remember well, having both at the same time was possible before so I'm wondering if something changed with the recent version 1.89 that I'm missing. Here is some example code in case it helps:

```
ImGui::Begin("MyWindow");
if (ImGui::IsItemHovered())
{
  // record events
  const bool isCtrlPressed = ImGui::IsKeyDown(ImGuiKey_LeftCtrl) || ImGui::IsKeyDown(ImGuiKey_RightCtrl);
  const bool isLeftPressed = ImGui::IsMouseClicked(ImGuiMouseButton_Left) || ImGui::IsMouseDragging(ImGuiMouseButton_Left);

  // only one of them is true, even when both are pressed
  std::cerr << isCtrlPressed << ", " << isLeftPressed << std::endl;
}
ImGui::End();
```

Thanks in advance!

**Comment by ocornut** [comment]
Hello,

I can confirm there is "kind of" a bug related to the key ownership system, specifically when CLICKING on a window to move it, as the moving-window operation is preventing keys from having other actions.

Simpler repro:
```cpp
const bool isCtrlDown = ImGui::IsKeyDown(ImGuiKey_LeftCtrl) || ImGui::IsKeyDown(ImGuiKey_RightCtrl);
const bool isLeftPressed = ImGui::IsMouseClicked(ImGuiMouseButton_Left) || ImGui::IsMouseDragging(ImGuiMouseButton_Left);
ImGui::Text("isCtrlDown = %s, isLeftPressed = %s", isCtrlDown ? "Ctrl" : "----", isLeftPressed ? "Left" : "----");
```
Also note that you are likely to want to use the Mod and not keys:
```cpp
const bool isCtrlDown = ImGui::IsKeyDown(ImGuiMod_Ctrl);
const bool isLeftPressed = ImGui::IsMouseClicked(ImGuiMouseButton_Left) || ImGui::IsMouseDragging(ImGuiMouseButton_Left);
ImGui::Text("isCtrlDown = %s, isLeftPressed = %s", isCtrlDown ? "Ctrl" : "----", isLeftPressed ? "Left" : "----");
```
(same issue will appear here but this is simpler)

**However note that it doesn't seem regular/wise to react while simultaneously moving a window which is what you are doing here.**

> Hey, I'm trying to obtain mouse and keyboard events when the mouse is hovering a specific window. 

Why? Can you explain the context?
Generally if you'd want to catch a click or drag you'll want an item to drag it (an `InvisibleButton()` is enough most of the time), otherwise the click will also moving the window.

Right now if you use `io.KeyCtrl` you'll be able to get the unfiltered input for this, but:
- It'd be more correct to submit an item to get those inputs.
- I would still want to specifically get mods to not appear filtered while moving a window.

**Comment by ocornut** [comment]
I've pushed another fix 7bee9a8 to make the behavior more consistent with pre-4448d97 logic.

**Comment by jzubizarreta** [comment]
Wow that was fast! I tried with your fixes and it's working :)

My intention is to use the mouse and keyboard to provide navigation in a 3D viewport. Like, for example, rotation with mouse left click and translation with left + Ctrl. For that, I also made it so each window can only be moved using the tittle bar.

Thanks again @ocornut !

**Comment by ocornut** [comment]
Then you should indeed use InvisibleButton() to grab inputs at that location.

**Comment by jzubizarreta** [comment]
What is the difference of using an InvisibleButton? Not sure how to use it, do you have any link I could look at?

**Comment by ocornut** [comment]
Then call `ImageButton()`.

**Comment by jzubizarreta** [comment]
It worked! Thanks @ocornut :)
