### ISSUE TITLE
Detecting ENTER being pressed on InputText

### ISSUE THREAD

**Issue by Cthutu** [ocornut/imgui#589]
Is it possible to detect that?  Right now I have a input text on a context menu, and I would like to be able to know that the enter key has been pressed while editing the input field and then close the menu.  I am not sure how this is done.  Any pointers?  

The code I have so far is similar to this:

```
if (ImGui::BeginPopupContextItem("..."))
{
    if (ImGui::InputText("...", buffer, size))
    {
        OnBufferChanged();
    }
    ImGui::EndPopup();
}
```

**Comment by ocornut** [comment]
Check the flags for InputText, there's one to do exactly that.

**Comment by Cthutu** [comment]
Don't know how I missed that!  Thanks Omar!.  And I've just discovered
CloseCurrentPopup() which solves the other part of my problem.

**Comment by ocornut** [comment]
Cool!
I much prefer it when a feature is Already done :)

**Comment by WheezardX** [comment]
I'm doing something similar where I show a pop-up with a text field.  I would like to close it on Enter so the flag works.  But I'd also like to close it on Escape (and know to throw away the changes), I tried using the callback but using ImGuiInputTextFlags_CallbackAlways I never see data->EventKey or data->EventChar be anything useful.

**Comment by ocornut** [comment]
Hmm, yeah the Escape key isn't passed there. 
Possible solutions:
- If you can afford it an easy workaround is just to hash/strcmp your content if you want to catch the cancel.
- Or we could improve the code to pass all keys down the callback (but that requires more rafactoring)
- Or don't use `ImGuiInputTextFlags_EnterReturnsTrue` and instead detect enter keypress yourself. Tricky because pressing Enter loses ActiveId so you don't have trace of it and `IsItemActive()` will return false after Enter was pressed. Going through `imgui_internal.h` you can compare `GImGui->ActiveId == GetId("label")` to check in advance and then test for Enter key, or we could add `WasItemActive()/IsItemActivePreviousFrame()` (name??) which you can implement as:
```
bool ImGui::IsItemActivePreviousFrame()
{
    ImGuiContext& g = *GImGui;
    if (g.ActiveIdPreviousFrame)
        return g.ActiveIdPreviousFrame== GImGui->CurrentWindow->DC.LastItemId;
    return false;
}
```
Bit fishy but it'll works.
```
bool modified = InputText(...);
bool pressed_enter = IsItemActivePreviousFrame() && !IsItemActive() && IsKeyPressed(io.KeyMap[ImGuiKey_Enter]);
```

**Comment by BruceAndyLee** [comment]
I feel a bit awkward and sorry to say that (because I'm way too far from your level of coding skill), but have you tried compiling your projects using address sanitizer? it gives a ton of warnings which is ... idk

**Comment by ocornut** [comment]
@BruceAndyLee I'm sometimes using static compilation tools such as Coverity.

As for address sanitizer I could never got it to work under Windows. It's barely documented and unclear if it even works with Visual Studio 2015 + LLVM 5.0.1 for Windows. I just spent an hour trying again right now, and the best I could come with was to create a new null_example/ to avoid linking with OpenGL/DirectX/GLFW to make it easier to port, so I can now do:

```
#examples\null_example>clang++ -fsanitize=address -o1 -g *.cpp ../../*.cpp -I../..
Creating library 1.lib and object 1.exp
#a.exe
Normal print output, no message from sanitizer.
```

What do you get and how do you set it up? If you more information (and I would appreciate a log), please open a new issue (not sure why you commented on this issue).
