### ISSUE TITLE
Drag and drop error with glfw drop callback function 

### ISSUE THREAD

**Issue by CBS5181** [ocornut/imgui#5909]
```
Dear ImGui 1.89 WIP (18804)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1929
define: _MSVC_LANG=201703
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000441
 NavEnableKeyboard
 DockingEnable
 ViewportsEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C0E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 2 fonts, Flags: 0x00000000, TexSize: 512,512
io.DisplaySize: 1600.00,1100.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```
**Version/Branch of Dear ImGui:**

Version: 1.89 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Operating System: WIN10

**My Issue/Question:**

I use glfw drop_callback function with ImGui::BeginDragDropSource(ImGuiDragDropFlags_SourceExtern) in order to drag file from window filesystem.
However, it reported `Assertion failed: g.WithinFrameScope` which means "forgot to call ImGui::NewFrame()" when I drag and drop the file where the`ImGui::BeginDragDropTarget()` accepted payload.

**Screenshots/Video**
- Demo
![motion](https://user-images.githubusercontent.com/35103220/203370552-e4e6444b-6119-4aba-9b4e-8186b790a2f3.gif)
- Console Output
![image](https://user-images.githubusercontent.com/35103220/203373294-968d2e54-a398-4554-af13-be9858974c10.png)

**Standalone, minimal, complete and verifiable example:**
- **DragDropTarget**
```cpp
ImGui::InputTextWithHint("Pano01", "open / drag and drop folder here...", buffer[0], sizeof(buffer[0]), ImGuiInputTextFlags_ReadOnly);
if (ImGui::BeginDragDropTarget())
{
	if (const ImGuiPayload* payload = ImGui::AcceptDragDropPayload("FILES"))
	{
		fs::path filepath((const char*)payload->Data);
		if (fs::is_directory(filepath)) // only accept folder
		{
			s_FileManager.SetPano01Filepath(filepath);
			s_MatchPoints.ClearPixel();
		}
	}
	ImGui::EndDragDropTarget();
}
```
- **DragDropSource (glfw drop callback)**
```cpp
void Application::drop_callback(GLFWwindow* window, int count, const char** paths)
{
	for (int i = 0; i < count; ++i)
	{
		if (ImGui::BeginDragDropSource(ImGuiDragDropFlags_SourceExtern))
		{
			ImGui::SetDragDropPayload("FILES", paths[i], strlen(paths[i]) + 1);
			ImGui::EndDragDropSource();
		}
	}
}
```

Thanks.

**Comment by ocornut** [comment]
Hello,

Thanks for providing details and a repro.
The asserts informs you on what the issue it.
You currently cannot submit that DragDrop source outside of `NewFrame/EndFrame` scope.
You need to change your drop callback to record the event and submit it after calling `NewFrame()`.

**Comment by CBS5181** [comment]
Hi, @ocornut . Thanks for your reply.
I move the DragDropSource code before the ImGui::EndFrame() and the error has been fixed.
But I wonder if there is a better way to deal with the DragDropSource from outside of the imgui?
And How can I display preview with external source?

**Comment by PathogenDavid** [comment]
@CBS5181 If you submit widgets (IE: using `ImGui::Text` or `ImGui::Image`) between `BeginDragDropSource` and `EndDragDropSource`, they will show in the preview.

You can find an example of this in the demo under `Widgets` > `Drag and Drop` > `Drag and drop to copy/swap items`:

https://github.com/ocornut/imgui/blob/16476f99fdd70f05228f0260aa2cfe98a3d46df9/imgui_demo.cpp#L2233-L2245

Just as an example, here's what it looks like with an image added:

![image](https://user-images.githubusercontent.com/278957/203483850-741e4f43-3b5b-4508-b667-4bee52abbee1.png)

---------------

As an aside, you can only have one drag-drop payload active at once, so you probably don't want to call `BeginDragDropSource` in a loop like that. (Right now I believe only the first file would actually be accepted.)

**Comment by CBS5181** [comment]
Hi, @PathogenDavid. Thanks for your reply.
I know this method, but it didn't display preview when I use `ImGuiDragDropFlags_SourceExtern` flag with `BeginDragDropSource`.

**Comment by PathogenDavid** [comment]
There's two unrelated issues preventing previews for external drag & drop sources.

The first one is that GLFW only actually calls your callback when the file is dropped. As far as I can find, GLFW does not provide an API to react to files being dragged over your window.

------------

For anyone using another API which doesn't have that limitation: The other issue is that like most things in Dear ImGui, the preview relies on you continuously submitting your widgets. So if you stop calling `BeginDragDropSource`, `ImGui::Text`, etc the preview will disappear.

Turns out this is actually slightly tricky to handle properly in the context of `ImGuiDragDropFlags_SourceExtern` though since [an external source is always active](https://github.com/ocornut/imgui/blob/ffe0abbfc2672b1d44a51f7f7b36c9075e4409f4/imgui.cpp#L11816) from Dear ImGui's perspective.

I tinkered around for a bit and came up with this example. You'll likely want to handle memory management slightly differently, but this should get you headed in the right direction.

```cpp
// Variables for storing state about external drag-drop data
const char* newExternalData = nullptr;
size_t newExternalDataLength = 0;
```

```cpp
// Example of setting these variables in a callback
// (In your case you'd pick a single file from the callback to copy or something like that.)
const char path[] = "hello_world.txt";
newExternalData = strdup(path);
newExternalDataLength = sizeof(path);
```

```cpp
// This handles providing the source
// BeginDragDropSource will always return true so whether or not we submit preview text
// is determined by whether the user is currently dragging old FILES data (userIsDraggingExternalData)
// or if there is new data to being dragged (newExternalData != nullptr)
#define EXTERNAL_PAYLOAD_TYPE "FILES"
const ImGuiPayload* payload = ImGui::GetDragDropPayload();
bool userIsDraggingExternalData = payload != nullptr && payload->IsDataType(EXTERNAL_PAYLOAD_TYPE);

if ((userIsDraggingExternalData || newExternalData != nullptr) && ImGui::BeginDragDropSource(ImGuiDragDropFlags_SourceExtern))
{
    if (newExternalData)
    {
        ImGui::SetDragDropPayload(EXTERNAL_PAYLOAD_TYPE, newExternalData, newExternalDataLength, ImGuiCond_Once);
        free((void*)newExternalData);
        newExternalData = nullptr;
        newExternalDataLength = 0;
    }

    ImGui::Text("This is the preview text!");
    ImGui::EndDragDropSource();
}
```

If you'd prefer to see this in the context of a full application, I've pushed [a modified version of `example_glfw_opengl3`](https://github.com/PathogenDavid/imgui/commit/75dd4a036c7de3a9f8ec2ef4497c8ffe60558dee) demonstrating the above code. (Do note though that due to the previously mentioned GLFW limitation, the preview won't show for actual file drag-drop operations. I included a button that simulates an external file being dragged to demonstrate it properly.)

Note that this assumes that there are no other `FILES` drag-drop sources in your app. (If there are, it will steal them and mess with their preview tooltip.)

If expect to have non-external `FILES` sources, you'd have to add a check that `payload->SourceId == ImHashStr("#SourceExtern")` -- however do note that this is relying on internal implementation details that could change at any time.

**Comment by CBS5181** [comment]
Hi, @PathogenDavid.
Thanks for providing detailed explanation and demo code. 
Really helpful! :smile:
