### ISSUE TITLE
Segmentation fault when loading default font

### ISSUE THREAD

**Issue by arnokret** [ocornut/imgui#5957]
In a project of mine I upgraded from Imgui version 1.85 to the newest version (which currently is 1.89.1). 

My problem is that when loading fonts (via io.Fonts-> AddFontFromFileTTF(...) ), my program now crashes with a segfault. 

After searching around I found that many new people (of which I am one too) make mistakes with the filenames (slashes, relative vs absolute path). So I tried changing the command to io.Fonts->AddFontDefault(), which also crashes with a segfault. 

Going into the debugger it crashes on line 2160 of imgui_draw.cpp, which is the first line of the function AddFontFromMemoryTTF. This line reads "IM_ASSERT(!Locked && "Cannot modify a locked ImFontAtlas between NewFrame() and EndFrame/Render()!");"

I am a bit surprised that it crashes with a segfault, I thought crashing on an assert is different. In any case, if the problem is indeed that I cannot change the font atlas when I am between NewFrame and EndFrame, it suggests I should call AddFontDefault in another place of my code. I tried searching the documentation where it is explained when to do this exactly, but couldn't find it. I tried putting the io.Fonts -> AddFontDefault() in a couple of different places, also after running the main loop at least once. But I get consistently the same error. (Let me emphasise that in version 1.85 my code compiled and seemed to work correctly)

I use sfml together with imgui. Below I produced a minimal example (essentially from the template provided by https://eliasdaler.github.io/using-imgui-with-sfml-pt1/): 

```
#include "inc/imgui.h"
#include "inc/imgui-SFML.h"

#include <SFML/Graphics/RenderWindow.hpp>
#include <SFML/System/Clock.hpp>
#include <SFML/Window/Event.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode(3840, 2160), "");
    window.setVerticalSyncEnabled(true);

    ImGui::CreateContext();
    
    ImGuiIO& io = ImGui::GetIO(); (void)io;
    io.Fonts->AddFontDefault();
    
    ImGui::StyleColorsDark();

    ImGui::SFML::Init(window);

    sf::Color bgColor;

    float color[3] = { 0.f, 0.f, 0.f };
    char windowTitle[255] = "ImGui + SFML = <3";

    window.setTitle(windowTitle);
    window.resetGLStates(); // call it if you only draw ImGui. Otherwise not needed.
    sf::Clock deltaClock;

    while (window.isOpen()) {
        sf::Event event;
        while (window.pollEvent(event)) {
            ImGui::SFML::ProcessEvent(event);

            if (event.type == sf::Event::Closed) {
                window.close();
            }
        }

        ImGui::SFML::Update(window, deltaClock.restart());

        ImGui::Begin("Sample window"); // begin window

                                       // Background color edit
        if (ImGui::ColorEdit3("Background color", color)) {
            // this code gets called if color value changes, so
            // the background color is upgraded automatically!
            bgColor.r = static_cast<sf::Uint8>(color[0] * 255.f);
            bgColor.g = static_cast<sf::Uint8>(color[1] * 255.f);
            bgColor.b = static_cast<sf::Uint8>(color[2] * 255.f);
        }

        // Window title text edit
        ImGui::InputText("Window title", windowTitle, 255);

        if (ImGui::Button("Update window title")) {
            // this code gets if user clicks on the button
            // yes, you could have written if(ImGui::InputText(...))
            // but I do this to show how buttons work :)
            window.setTitle(windowTitle);
        }
        ImGui::End(); // end window

        window.clear(bgColor); // fill background with color
        ImGui::SFML::Render(window);
        window.display();
    }

    ImGui::SFML::Shutdown();
}
```

**Comment by jdoubleu** [comment]
I had the exact same issue. I was using *ImGui-SFML* v2.5.1 with the latest *imgui* (v1.89.2). \
Internally, `ImGui::SFML::Init()` just calls `ImGui::CreateContext();` and registers some key bindings (compare https://github.com/eliasdaler/imgui-sfml/blob/v2.5/imgui-SFML.cpp#L270-L291).

And that's where the issue was: The key bindings enum changed in *imgui* v1.87 (see https://github.com/ocornut/imgui/commit/3b669293019af511008654e2a8da059f3e51f8b4#diff-cbc47f9fc55eb2c19b4be92d1c1e137bb8b72d072588ab3cb4bcba88576d14cbR1369). The integer representing the enum key `ImGuiKey_Enter` is `520` which exceeds `ImGuiKey_COUNT`. Thus a write to [`int ImGuiIO::KeyMap[ImGuiKey_COUNT = 512]`](https://github.com/ocornut/imgui/blob/v1.89.2/imgui.h#L2007) causes sort of a buffer override. In my case, it changed the [`ImFontAtlas* ImGuiIO::Fonts`](https://github.com/ocornut/imgui/blob/v1.89.2/imgui.h#L1918) ptr to point to an invalid location. When *ImGui-SFML* later tried to call `io.Fonts->GetTexDataAsRGBA32()`, it access an invalid memory location, thus causing the segfault.

There are effectively two ways to fix that:
1. Downgrade to *imgui* v1.86 when using *ImGui-SFML* v2.5.1
2. Use latest version of *ImGui-SFML* from master. I believe they fixed it with https://github.com/eliasdaler/imgui-sfml/commit/9c545ad9905999fc40cfc946fbff013173bc23ba.

**Comment by ocornut** [comment]
> ImGuiKey_Enter is 520 which exceeds ImGuiKey_COUNT

I am not sure I follow this explanation. Before of after 1.87, ImGuiKey_Enter never exceeded ImGuiKey_COUNT.
The change in 1.87 was engineered so that `io.KeyMap[ImGuiKey_XXX]` would never crash.

**Comment by ocornut** [comment]
Amend to previous post:
- issues could happens if compilation unit have mismatching compile-time flags (e.g. `IMGUI_DISABLE_OBSOLETE_KEYIO`)
- issues could happens if objects files (e.g. pre-compiled librairies) are relying on different version.

But unless i am mistaken, the explanation you posted does not seem correct.
