### ISSUE TITLE
Troubles properly sorting in a table

### ISSUE THREAD

**Issue by EvanDyson** [ocornut/imgui#5960]
(Click "Preview" above ^ to turn URL into clickable links)

**Version/Branch of Dear ImGui:**

Version: 1.89.1
Branch: master/viewport/docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.h + imgui_impl_opengl3.h
Operating System: Windows 10

**My Issue/Question:**

Hello, I am currently creating my own project and for the project I needed to implement a GUI which I chose Dear ImGui for. Currently I have everything working up until the table I have created. My table uses the demo created implementation but I have modified it to suit what I need it to do. My issue right now is that my table is not sorting correctly. All the data is displaying but when I click on the header all the data in the table does not properly sort. Please see my video below for all the code and I will walk through what is going on.
Thank you!

**Screenshots/Video**

https://youtu.be/G09VUgCvWIo

Link to my repository and to the main that is shown in the video: https://github.com/EvanDyson/COP-project-3/blob/main/Evan/V3.1/main.cpp

**Comment by ocornut** [comment]
Your vector is storing `City*` entries:
```cpp
vector<City*> mergeVector
```

And when we casting in the sort function you are using an unrelated `MyItem` type:
```cpp
qsort(&mergeVector[0], mergeVector.size(), sizeof(mergeVector[0]), MyItem::CompareWithSortSpecs);
[...]
static int IMGUI_CDECL CompareWithSortSpecs(const void* lhs, const void* rhs)
{
   const MyItem* a = (const MyItem*)lhs;
   const MyItem* b = (const MyItem*)rhs;
   [...]
```

`MyItem` and `City` layout and unlikely to be the same.

Stepping into a debugger you can probably confirm the pointed structures inside the `CompareWithSortSpecs()` functions hold garbage values.

Compare
https://github.com/EvanDyson/COP-project-3/blob/main/Evan/V3.1/main.cpp#L53
to
https://github.com/EvanDyson/COP-project-3/blob/main/Evan/V3.1/City.h#L7
Different but similar struct. Float and double are not the same size and all your addressing will fail as they don't have same size.
Use a single struct, not two.

Note that we use `qsort()` in imgui_demo.cpp because we have an explicit stance to not use C++ headers, but you may be better off using `std::sort()` or another type-safe-friendly function which allows you defining comparing operators in a less awkward manner.
