### ISSUE TITLE
What is a correct way to filter out some items while working with ImGuiListClipper?

### ISSUE THREAD

**Issue by MichaelKv** [ocornut/imgui#5962]
Hello,
From imgui.h:
#define IMGUI_VERSION               "1.89 WIP"
#define IMGUI_VERSION_NUM           18814
#define IMGUI_CHECKVERSION()        ImGui::DebugCheckVersionAndDataLayout(IMGUI_VERSION, sizeof(ImGuiIO), sizeof(ImGuiStyle), sizeof(ImVec2), sizeof(ImVec4), sizeof(ImDrawVert), sizeof(ImDrawIdx))
#define IMGUI_HAS_TABLE
#define IMGUI_HAS_VIEWPORT          // Viewport WIP branch
#define IMGUI_HAS_DOCK              // Docking WIP branch

OS: Windows 2016 Server, x64
Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30146 for x64

What is a correct way to filter out some items while working with ImGuiListClipper? I.e.
clipper.Begin(amount);
while (clipper.Step()) {
	for (int i = clipper.DisplayStart; i < clipper.DisplayEnd; ++i) {
		if (needToDraw(array[i])) {
			ImGui::Text(...);
		}
	}
}
I am almost happy with the result unless it crashes in the second clipper.Step() if the very first item has been filtered out. Please, notice that if the very first item is not skipped it works as expected.
For example, if I have a log and need to filter out all warnings and infos.
Thank you.

**Comment by GamingMinds-DanielC** [comment]
Your problem lies in `needToDraw()`. You can't just filter out items that the list clipper requests, you need to submit them. Filtering out is the clippers job. If you don't supply an explicit item height, the list clipper requests the very first item in the first step and calculates the height from what is submitted.

**Comment by MichaelKv** [comment]
> Filtering out is the clippers job.
Sorry, I do not see a way to send my needToDraw code to the clipper.

> If you don't supply an explicit item height, the list clipper requests the very first item in the first step and calculates the height from what is submitted.
Right. And the cursor position was not changed. I expect a retry at the next .Step call. I.e. I expect the clipper to start from the very beginning at the same window position and next item and repeat such retries until my code draws something. It does allow me this trick afterwards indeed.
And anyway -- it shall not crash.

**Comment by ocornut** [comment]
The crash is likely an assert designed to help you understand a mistaken.

Think of clipper.DisplayStart and clipper.DisplayEnd as indices in the filtered set. Likewise, the value passed to clipper.Begin() should be a count of the filtered set.

The easier way is to prefilter and store filtered lines/indices in a vector. You may keep the vector around between frames and call resize(0) to reuse it without neeeding for alloc/copy.

**Comment by GamingMinds-DanielC** [comment]
> Sorry, I do not see a way to send my needToDraw code to the clipper.

You don't. Let the clipper do its own clipping, don't try to force yours into it. If you need to filter out items, you rebuild a list that only contains the items that should be displayed and send that to the clipper. You give the clipper the number of those filtered items and submit every single one that is requested. And they need to be continuous. Index 0 is then the first of the remaining items, but it must be submitted.

> And anyway -- it shall not crash.

It is perfectly valid if it crashes when you do something wrong, as long as it is properly asserted. That's what debug configurations are for. I just tested it myself. In a debug build, ImGui doesn't crash if you skip the first item, it asserts and tells exactly what is wrong and how to fix it, that's all that is needed. Handling incorrect inputs anyway would needlessly complicate the code, slow down processing and potentially break other things.

**Comment by MichaelKv** [comment]
> Think of clipper.DisplayStart and clipper.DisplayEnd as indices in the filtered set. Likewise, the value passed to clipper.Begin() should be a count of the filtered set.
> 
> The easier way is to prefilter and store filtered lines/indices in a vector. You may keep the vector around between frames and call resize(0) to reuse it without neeeding for alloc/copy.

I have a million of log messages that are of different types: errors, infos, warnings. All I need is to have three checkboxes that control their visibility. If I do not need warnings, I want to press the proper checkbox, and my needToDraw will return false for all warnings and I will not draw them. ImGuiListClipper does exactly this except for the first item. I expect it to ignore the very first missing draw call absolutely the same way it does for second and so on items. This will allow me to have just one pass on my one million lines log.
I believe such a behavior would cost to ImGuiListClipper nearly nothing. At least I see how I could hack it myself but I needed to be sure I understood if filtering out (NOT clipping out) was really supported. At least this https://github.com/Flix01/imgui/blob/imgui_with_addons/addons/imguilistview/imguilistview.cpp claims “Prefer using ImGuiListClipper which can returns non-contiguous ranges.” If it does not – no problem.

**Comment by ocornut** [comment]
> This will allow me to have just one pass on my one million lines log. I believe such a behavior would cost to ImGuiListClipper nearly nothing.

It is not possible and you are misunderstanding how the clipper works and what it does. From its pov the clipper doesn’t care nor know about your filtering therefore it should be fed an after-filter count and answering you with after-filter indices. 

If you indeed have a million item, it will be in your advantage and faster to maintain a filtered list. Bare minimum you need to maintain count for each item type you can submit this to clipper.Begin() and then you technically could use the output indices to fast-forward and seek while filtering, but you’d always be filtering a million item every frame. If you build the filtered index when setting changes and append when new log entries appears, you only build all on checkbox click and then optimal clipping is done on render.

**Comment by GamingMinds-DanielC** [comment]
You expect the clipper to work a certain way it doesn't because it seems to work that way for other items. But it doesn't work that way for those other items as well. It may look like it does because it doesn't "crash", but it is still wrong to not submit every single item that is requested. They should be continuous, every filtering on top is your responsibility and not part of the clipper.

If you have 100k log messages... lets say 60k infos, 35k warnings and 5k errors. If you only want the errors, you need to tell the clipper that you have 5k items and submit the very first error (whichever index that is in you log messages) when item 0 is requested. That is easy to accomplish. You need to have a second array with just the indices for remapping (f.e. a `std::vector<size_t>` if you use C++). Whenever your filter settings change, you detect that before submitting anything and rebuild your remapped indices. Then, when items are requested, use the remapping to look up which item to actually submit (but definitely submit it).

You can extend the remapping when new logs come in according to the filter settings and rebuild it only when filter settings change. If you want, you can keep and extend multiple remappings for some common or even all of your filter configurations. The one thing you can't do is expect the clipper to respect any filtering, that't not how it is intended to work.

**Comment by MichaelKv** [comment]
> but you’d always be filtering a million item every frame.

Why? I need window height items up and down from current position in the list. And I can count the amounts of each messages' types for the slider to be accurate (it is bigger now).

> This likely means you don’t yet understand how it works. By all means try and maybe you’ll have the “click” to understand what clipper does and why.


> Edit: few minutes slower, but basically the same approach. :D

I will try to write a clipper that steps forward and backward from the current list position until it fills the window height. As a minimum I will just remove the assert and ignore failed step 0. It will continue to work perfectly forwards and I will invent a dirty approximate temporary hack for backwards.
Or return to the solution of the guy I have quoted above -- it does have filtering https://rawgit.com/Flix01/imgui/imgui_with_addons/examples/addons_examples/html/main.html  Examples-->log. I stopped considering him because of his remark above. I will need to replace his filtering with my much simpler types and vu a la.

**Comment by GamingMinds-DanielC** [comment]
> I will try to write a clipper that steps forward and backward from the current list position until it fills the window height.

That could actually work for the kind of data you have, or rather seem to work. But consider these as test cases...

Test case 1: all of the items you want to show are in the second half of the list. If you base your count and indices on the complete list, your scroll bar will not work as expected.

Test case 2: you have a list with 100 items, room to display 20 but only 10 remain after filtering. The problem should be quite obvious.

**Comment by ocornut** [comment]
> I will try to write a clipper that steps forward and backward from the current list position until it fills the window height.

This is how I suggested you could use the clipper (see “fast forward / seeking” suggestion if you insist on using the slower solution of filtering one million element every frame instead of pre-filtering + appending. You need to know the COUNT of filtered element in order to have a scrolling range (scrollbar), and considering the common case of having the scrollbar be at the bottom you’d often need to run your filter over a million element every frame, which is going to be a performance problem which pre-filtering wouldn’t have.

**Comment by GamingMinds-DanielC** [comment]
> And considering the common case of having the scrollbar be at the bottom you’d often need to run your filter over a million element every frame,

I do believe his approach is a bit different:
- tell the clipper the amount of unfiltered messages
- locally search around the requested ranges to get enough items

That would result in a wonky scrollbar if the filtered items are not evenly distributed and obvious problems if there are not enough left after filtering. But if they are evenly distributed and if there are enough items, it should work well enough and the local search should not impact the performance too much.

But I see another problem on the horizon. With default styles, a single text line is already 17 pixels high. With 1 million entries, the total height exceeds 16777216 pixels, resulting in lost precision (32 bit floats can only increment in steps of 2 from that point). The scrolling behavior gets a bit strange due to that.

**Comment by ocornut** [comment]
> But I see another problem on the horizon. With default styles, a single text line is already 17 pixels high. With 1 million entries, the total height exceeds 16777216 pixels, resulting in lost precision (32 bit floats can only increment in steps of 2 from that point). The scrolling behavior gets a bit strange due to that.

At least we have a mitigation system in place for this case, which works if a window is only filled by items going through clipper. Since the visible area use “small” float values it works decently. Since a few versions it works better.

**Comment by MichaelKv** [comment]
Sorry, I do not understand one million entries. I am going to render only the amount necessary to fit the window. I do the same trick for signal samples. I select, decimate and resample according to the window size and X axis. On 3000 pixels wide monitor I select 1000 points whether my file is 20Kb or 20Gb (this is the real case for me). So, I already know I will not be able to use the standard window scroller. I will use a slider and not-scrolling window (the content will fit). A kind of weird but this is my first GUI application (VBA does not count).
You are right about the selection problem -- it will be hard to find the proper place in the list. And in case of two valid items which are the first and the last ones I will need to walk through the whole million. But it will not be rendering! And I might probably give up and make some indices. 
It would be nice if imgui windows had a virtual scroller. It would show that window is very big but it shall not have a scroller indeed. A kind of when you have a huge text but you render windowed part only so the window does not need a scroller indeed but it draws it as if it were very big. I use slider for such a trick now.

**Comment by ocornut** [comment]
> Sorry, I do not understand one million entries. 

You said "I have a million of log messages that are of different types" which is the assumption we operated on.
Walking over a million entry (even without rendering) is likely to have a measurable cost you want to avoid.

> I am going to render only the amount necessary to fit the window.

Yes, this is exactly why ImGuiListClipper does and what we often do in Dear ImGui land.
**The problem here is that you need filtering and the way you do the filtering on the fly means you don't have random access to your entries anymore, only sequential access.** If you have a mixed list of 1000 warning+error+log entries (not filtered), you have no way to tell in constant time where is the the 100th **warning**.

The optimal solution to this is exactly what we answered: prefilter.

```cpp
Vector<Entries*> Entries;  // All entries
Vector<Entries*> EntriesFiltered;  // Entries after filtering

// Call when 1) appending to log
void AddNewEntries(Entry* entries, int count)
{
   Entries.reserve(Entries.size() + count);
   for (auto Entry entry : entries)
       Entries.push_back(entry);
}

// Call when 1) appending to log + call when 2) changing filter
void AddNewEntriesToFilter(Entry* entries, int count)
{
   for (auto Entry entry : entries)
       if (needToDraw(entry)
            EntriesFiltered.push_back(entry);
}

void DrawUI()
{
   bool settings_modified = false;
   settings_modified |= ImGui::Checkbox("Errors", ...);
   settings_modified |= ImGui::Checkbox("Warnings", ...);
   settings_modified |= ImGui::Checkbox("Log", ...);

   // Rebuild filter?
   if (settings_modified)
   {
      EntriesFiltered.resize(0);
      AddNewEntriesToFilter(Entries.data(), Entries.size();
   }

   // Show contents
   // now you have full random access to your filtered set, use ImGuiListClipper with EntriesFiltered
}
```

Notes:
- This can now easily be extended to any form of filtering including heavy searches (regexp) etc.
- The slower part is when needing to rebuild the filter, but appending new entries only filter new elements.
- As a storage optimization you might store indices inside Vector<> EntriesFiltered.

**Comment by MichaelKv** [comment]
> Yes, this is exactly why ImGuiListClipper does and what we often do in Dear ImGui land.

Hm...

> But I see another problem on the horizon. With default styles, a single text line is already 17 pixels high. With 1 million entries, the total height exceeds 16777216 pixels, resulting in lost precision (32 bit floats can only increment in steps of 2 from that point).

They were not your words indeed. But OK, I believe you. So, I do not need a slider instead of the scroller. But I do not think your solution will work for me as it is

> Entries.reserve(Entries.size() + count);

This will kill me. I allocate the whole buffer once and make it a ring buffer.

> void AddNewEntriesToFilter(Entry* entries, int count)
> for (auto Entry entry : entries)
I supposed to search up or down from the current position in 1 million list. I did not want to examine the whole list. As if Page-UP -- search up from the current position, and Page-down -- >down. Scroller clicks will be very approximate without helper indices. 

> if (settings_modified)

The log is written asynchronously my a multithreaded application. But Ok, I will be able to handle this properly.

> // now you have full random access to your filtered set, use ImGuiListClipper with EntriesFiltered

Ok, I see it now. My version EntriesFiltered would contain only the amount of items needed to fit the window height (say, 20). This would save me in the case when there are 999'999 _yours_ EntriesFiltered.

So far I believe I will prefer my version of window sized EntriesFiltered (say, 20) and a slider. I do feel that I need EntriesFiltered to be of the size of the window height. I can draw the slider either for TotalCurrentAmountOfEntitiesByFilters (I can count types in my ring buffer individually) or entries.size().

**Comment by ocornut** [comment]
I’ll close this as we have given you the answer you asked.
You may optimize filter storage by storing intervals, if it makes any sense, which may be a good balance for speed vs storage.

**Comment by pegvin** [comment]
i didn't go through the whole thread but i was using `ImGuiTextFilter` & `ImGuiListClipper` at same place and i had my program to crash when the filter caused zero output, i.e. no result.

this was my fix:

```c++
static ImGuiTextFilter filter;
filter.Draw("Filter");

bool ResultFound = false;
static ImGuiListClipper clipper;

ImGui::BeginChild("###ListChild");
	clipper.Begin(FontItems.size());
	while (clipper.Step()) {
		for (int i = clipper.DisplayStart; i < clipper.DisplayEnd; i++) {
			auto fItem = FontItems[i];
			if (filter.PassFilter((const char*)fItem.name)) {
				ImGui::TextUnformatted((const char*)fItem.name, NULL);
				if (ImGui::IsItemHovered()) {
					ImGui::SetTooltip("%s", fItem.path);
				}
				ResultFound = true;
			}
		}
		if (!ResultFound) {
			ImGui::TextUnformatted("No Result Found");
			clipper.End();
			ResultFound = false;
			break;
		}
	}
ImGui::EndChild();
```

basically i added some logic that ensured atleast 1 item was being outputted, which was "No Result Found" in my case.

but you can also pass the item's height to `clipper.Begin(...)` which in return doesn't calculate the first item's height thus it doesn't crash even if no elements are outputted into it.

**Comment by pegvin** [comment]
oh wait i think i already understand that, the `i` is always equal to or less & greater than the first & last elements displayed on the screen.

Which means the `PassFilter` only ever filters the text that is displayed on the screen, and not anything that is out of the view, i.e. the scroll-content, right?

**Comment by pegvin** [comment]
never mind, i am an idiot for passing the `clipSize` to be equal to the max number of elements, it should've been instead the max number of items that will be actually "displayed" on the screen, and whether to render them or not is the job of the clipper.

so i just need a create a new array that is a subset of my Initial array and only contains the filtered items.

i just can't help but fall in love with ImGui the more i use it.

**Comment by ocornut** [comment]
The value passed to `clipper.Begin(XXX);` should be the number of elements that will pass the filter.

> so i just need a create a new array that is a subset of my Initial array and only contains the filtered items.

Yes, this will scale better if you want to introduce some fancy filtering (e.g. regexp).
That subset can probably stores index into the first array.

**Comment by pegvin** [comment]
luckily i am working on a font viewer so i just need some basic text filtering, and i ended up with this solution:

```c++
// Init

std::vector<FontItem*> FontItems;
std::vector<FontItem*> FilteredFontItems;
FontItems.clear();
FilteredFontItems.clear();

bool didFilter = false;
bool didFilterFind = false;

// Fill `FontItems` Vector Here
```

```c++
// Main Loop -> Begin Window

bool didChange = ImGui::InputTextWithHint("Filter", "(Case Sensitive)", QBuff, Q_BUFF_SIZE);
if (QBuff[0] == 0) {
	didFilter = false;
} else if (didChange) {
	FilteredFontItems.clear();
	didFilter = true;
	for (unsigned int i = 0; i < FontItems.size(); ++i) {
		auto fItem = FontItems[i];
		if (strstr((const char*)fItem->name, QBuff) != NULL) {
			FilteredFontItems.push_back(fItem);
			didFilterFind = true;
		}
	}
	if (FilteredFontItems.size() == 0) {
		didFilterFind = false;
	}
}

ImGui::BeginChild("###ListChild");
auto clipperSize = didFilter ? FilteredFontItems.size() : FontItems.size();
if (didFilter && !didFilterFind) {
	ImGui::TextUnformatted("No Result Found");
} else if (clipperSize > 0) {
	static ImGuiListClipper clipper;
	clipper.Begin(clipperSize);
	while (clipper.Step()) {
		for (int i = clipper.DisplayStart; i < clipper.DisplayEnd; i++) {
			auto fItem = didFilter ? FilteredFontItems[i] : FontItems[i];
			ImGui::TextUnformatted(fItem->name, NULL);
		}
	}
} else {
	ImGui::TextUnformatted("No Font Entry Found");
}
ImGui::EndChild();
```

the code is a bit more long than before but it's wayyyyyyyy more optimized, not only because the clipper is now working as it should but the filtering is only being done when the text changes and not every single frame.

**Comment by ocornut** [comment]
Looks like you can remove `didFilterFind` alltogether since it is always the same as `!FilteredFontItems.empty()`

**Comment by pegvin** [comment]
lol thanks alot!!! but the "not" operator is wrong since it will show "No Result Found" if filtered items is not empty.

have a great day!!!
