### ISSUE TITLE
Is ImGui::ScrollToItem supposed to work with ImGuiListClipper?

### ISSUE THREAD

**Issue by MichaelKv** [ocornut/imgui#5995]
Hello,
From imgui.h:
#define IMGUI_VERSION "1.89 WIP"
#define IMGUI_VERSION_NUM 18814
#define IMGUI_CHECKVERSION() ImGui::DebugCheckVersionAndDataLayout(IMGUI_VERSION, sizeof(ImGuiIO), sizeof(ImGuiStyle), sizeof(ImVec2), sizeof(ImVec4), sizeof(ImDrawVert), sizeof(ImDrawIdx))
#define IMGUI_HAS_TABLE
#define IMGUI_HAS_VIEWPORT // Viewport WIP branch
#define IMGUI_HAS_DOCK // Docking WIP branch
Dx12

Is ImGui::ScrollToItem supposed to work with ImGuiListClipper? ImGui::Selectable and ImGui::SetItemDefaultFocus do work. ImGui::ScrollToItem does not.
Thanks.

**Comment by ocornut** [comment]
Question is too ambiguous to be answered.

**Comment by GamingMinds-DanielC** [comment]
It would be far easier to see what's wrong if you posted the code that's not working as you want it to. "If you add ImGuiListClipper into this scheme" doesn't say how you add it, the mistake could be many things. Also, please format code as code (you can select the text and press the <> button if you don't know the text version), that would make it a lot easier to read.

Just as a hunch, could it be that `ImGui::ScrollToItem()` never gets called because the item you want to scroll to doesn't get requested by the list clipper and you never submit it? Or that you scroll to the wrong item (last submitted, possibly not the one you intended)?

**Comment by MichaelKv** [comment]
The code is formatted. I do not use github at all so I am not very good with its rules and quirks. If I use the standard formatting from the menu, it gets formatted into a single line. I usually copy/paste such things into Visual Studio editor and it makes the code look good. I really tried to make the result look formatted but all in vain, sorry.
The code with clipper is as the following:
with_ListBox("##EventList", ImVec2(-FLT_MIN, -FLT_MIN)) {
	ImGuiListClipper clipper;
	clipper.Begin(eventsSize);
	while (clipper.Step()) {
		for (int i = clipper.DisplayStart; i < clipper.DisplayEnd; ++i) {
			const bool isSelected = (selected == i);
			if (ImGui::Selectable(events_[i], isSelected)) {
				selected = i;
			}
			if (isSelected) {
				ImGui::SetItemDefaultFocus();
			}
			if (selected == i && selected != oldSelected) {
				ImGui::ScrollToItem();
			}
		}
	}
}
If you have [0; 10] active window, secected = 0 and you change selected to 1000 programmably the original BeginListBox/EndListBox scheme shows [1000,1010] range, the code above continues to show [0; 10]. 
To be absolutely exact, I do the following: in current [0; 10] active window I use slider to go to approximately [1000,1010] range (it is way out of current [0; 10]) and press the ArrowDown key. It makes selected to be equal to 1 and BeginListBox/EndListBox draws [0; 10] region and the scheme above with the clipper continues to draw [1000,1010] range because ImGui::ScrollToItem() call does nothing.
Such a behavior is either a bug and I shall wait for a fix or I need to use the same method with a slider instead of scroller that I have invented for containers that do not have random access to their elements. I have decided to use standard ImGuiListClipper to work with randomly accessible containers so far.

**Comment by ocornut** [comment]
I gave the answer above.

**Comment by MichaelKv** [comment]
> I gave the answer above.

I do not have a clue how to realize what you have suggested. If the variable “selected” is modified with the keyboard I need to somehow set clipper’s DisplayStart and DisplayEnd. Clipper is stateless that in terms of ImGui means it keeps its state somewhere in global variables I do not have access to. I have tried several approaches with ForceDisplayRangeByIndices and ImGui::SetScrollY and was unable to get a desirable behavior.

> Use three backward apostrophes on an empty line to open a code-block, same for closing. If you add “cpp” after the ``` it will colorize for C++.

When I use apostrophes I see all the code in one line. These are supposed to be three ones.
`
for (size_t i = 0; i < length; ++i) {
	asdf();
}
`

**Comment by GamingMinds-DanielC** [comment]
> I have tried several approaches with ForceDisplayRangeByIndices and ImGui::SetScrollY and was unable to get a desirable behavior.

What were these approaches? `ForceDisplayRangeByIndices` will not scroll. It is used to include the desired item range in the items that get requested by the clipper, so that you can then submit those items. And when you submit your items, then you should be able to scroll to them with `ScrollToItem`. Your problem was not that `ScrollToItem` didn't work, but that you didn't call it in the first place because the item you want to scroll to got clipped out.

> When I use apostrophes I see all the code in one line.

If you write this:
```
'''c++
for (size_t i = 0; i < length; ++i)
{
    asdf();
}
'''
```
... but with the backward apostrophes instead of single quotes, you get this:
```c++
for (size_t i = 0; i < length; ++i)
{
    asdf();
}
```

**Comment by ocornut** [comment]
> It does not matter. 

It does matter. Michael this is not the first thrrad were you are asking questions, receiving generously detailed answers (thank you Daniel here!) and yet you are refusing to cooperate and being obtuse in your interactions. The reason we are asking for details and pastable minimal repro is that they help both sides in a discussion. Please don’t make it make it harder for us to help you.

**Comment by MichaelKv** [comment]
> It does matter. Michael this is not the first thrrad were you are asking questions, receiving generously detailed answers (thank you Daniel here!) and yet you are refusing to cooperate and being obtuse in your interactions.

I do not refuse to cooperate. I had five or six variants, they did not work as far as they were unable to set clipper’s DisplayStart and DisplayEnd and I did not save them. And I am absolutely direct and clear: I need a methodology to this:
with_ListBox("##EventList", ImVec2(-FLT_MIN, -FLT_MIN)) {
for (int n = 0; n < eventsSize; ++n) {
const bool isSelected = (selected == n);
if (ImGui::Selectable(events_[n], isSelected)) {
selected = n;
}
if (isSelected) {
ImGui::SetItemDefaultFocus();
}
if (selected == n && selected != oldSelected) {
ImGui::ScrollToItem();
}
}
}
with ImGuiListClipper.
Ok, this is a full example for you:
ImGui::SetNextWindowSize(ImVec2(520, 600), ImGuiCond_FirstUseEver);
with_Window("EventWindow") {
	static std::vector<std::string> events_;
	static bool init = false;
	if (!init) {
		events_.reserve(1000);
		for (size_t i = 0; i < 1000; ++i) {
			events_.push_back("Row " + std::to_string(i));
		}
		init = true;
	}
	if (const size_t eventsSize = events_.size()) {
		static int selected = 0;
		const int oldSelected = selected;
		if (ImGui::IsWindowFocused(ImGuiFocusedFlags_ChildWindows)) {
			if (ImGui::IsKeyPressed(ImGuiKey_UpArrow)) {
				if (selected != 0) {
					--selected;
				}
			}
			else if (ImGui::IsKeyPressed(ImGuiKey_DownArrow)) {
				if (selected < eventsSize - 1) {
					++selected;
				}
			}
			else if (ImGui::IsKeyPressed(ImGuiKey_Home)) {
				selected = 0;
			}
			else if (ImGui::IsKeyPressed(ImGuiKey_End)) {
				selected = eventsSize - 1;
			}
		}

		with_ListBox("##EventList", ImVec2(-FLT_MIN, -FLT_MIN)) {
			for (int n = 0; n < eventsSize; ++n) {
				const bool isSelected = (selected == n);
				if (ImGui::Selectable(events_[n].c_str(), isSelected)) {
					selected = n;
				}
				if (isSelected) {
					ImGui::SetItemDefaultFocus();
				}
				if (selected == n && selected != oldSelected) {
					ImGui::ScrollToItem();
				}
			}
		}
	}
}
I need the same functionality but with the ImGuiListClipper.

**Comment by ocornut** [comment]
I already gave you the answer and your example doesn’t seems to do anything with this information (eg: calling clipper.ForceDisplayRangeByIndices(selected, selected + 1); after clipper.Begin() as suggested above). 

Unrelated but are you aware that keyboard navigation is supported using the ImGuiConfigFlags_NavEnableKeyboard ? You seem to be trying to replicate it manually.

**Comment by ocornut** [comment]
I already gave you the answer and your example doesn’t seems to do anything with this (eg: calling clipper.ForceDisplayRangeByIndices(selected, selected + 1); after clipper.Begin() as suggested above).

We also explained you how to format code and you keep mentioning that doing something else - which is not the thing we said to do - doesn’t work. This is following the same pattern.

Unrelated but are you aware that keyboard navigation is supported using the ImGuiConfigFlags_NavEnableKeyboard ?

**Comment by GamingMinds-DanielC** [comment]
It's getting more and more difficult to assume the best. The triple backward apostrophes work with multiple lines between them, they are not intended for formatting within a single line. The input field here handles multiple line ending formats as well (just tested CR LF, LF only and CR only), I don't see how you could paste code with multiple lines into a single line. So if you are seriously trying, something must be really messed up with your browser or computer.

> Ok, this is a full example for you:

It's not quite full (you seem to use wrapper functions that are not defined) and you don't even have a list clipper in that code. Anyways, "full" examples are not as good as minimal examples. Here is what a minimal example looks like:

```c++
	if ( ImGui::Begin( "Clipper Test" ) )
	{
		const int  count = 1000;
		static int index = 0;

		ImGui::SliderInt( "Index", &index, 0, count - 1, "%d", ImGuiSliderFlags_AlwaysClamp );

		const bool scrollTo = ImGui::IsItemDeactivatedAfterEdit();

		if ( ImGui::BeginChild( "clipped_list" ) )
		{
			ImGuiListClipper clipper;

			clipper.Begin( count );
			if ( scrollTo )
				clipper.ForceDisplayRangeByIndices( index, index + 1 );

			while ( clipper.Step() )
			{
				for ( int i = clipper.DisplayStart; i < clipper.DisplayEnd; ++i )
				{
					ImGui::Text( "Item #%d", i );
					if ( scrollTo && ( i == index ) )
						ImGui::ScrollToItem();
				}
			}
		}
		ImGui::EndChild();
	}
	ImGui::End();
```

This is code that can be pasted as is (into the correct place in your test app of course) and just works, no undefined functions or variables anywhere. This example does exactly what you want (scrolling to a given index in a clipped list) by following the steps outlined a few times already. It won't get any more explicit than that.

> I need the same functionality but with the ImGuiListClipper.

Haven't checked your functionality in detail since it is hard to read, but you should be able to get that easily by incorporating the list clipper as I have just shown you.

**Comment by MichaelKv** [comment]
> Unrelated but are you aware that keyboard navigation is supported using the ImGuiConfigFlags_NavEnableKeyboard ?

No. How come? Ctrl-Tab and Ctrl-Shift-Tab work, the application is controlled with the keyboard and I could not have imagined I need something more to get list controlled with the keyboard.
Ok, I got back my very first version with ListBox and tried it. I switched to the EventWindow window with Ctrl-Tab, ListBox got selected instead of EventWindow and keyboard did not work. My approach handles this with ImGuiFocusedFlags_ChildWindows flag. So, I clicked the window to make it focused to see how keyboard navigation works. It is not the same as with my code, I will never get used to the concept of two cursors and necessity to navigate with arrows and select with the space. Probably, it may be hacked – I will have a look at.

> It's not quite full (you seem to use wrapper functions that are not defined) and you don't even have a list clipper in that code.

Sorry, I do not understand you. I have just copy/pasted literally the code from this very message thread into \examples\example_win32_directx12\main.cpp, commented out the ImGuiConfigFlags_NavEnableKeyboard  and added 
```
#include <imgui_sugar.hpp>
#include <imgui_internal.h>
#include <vector>
#include <string>
```
And vu a la – you get absolutely working ideal solution for me.
And sorry again, but your example has nothing to do with the original task. It is absolutely different functionality and there is the same problem with that I need to click inside after Ctrl-Tab to make the keyboard navigation working.

And who could imagine that I need THREE apostrophes to make the code tag working! They shall probably fix the editor’s <> button.

**Comment by MichaelKv** [comment]
Ok, thank you all for your efforts. I still have no clue how to achieve the functionality I want with ImGuiListClipper but I feel the discussion got stuck.

**Comment by ocornut** [comment]
Thanks Daniel for your help.
I’ll apply your suggestion to use begin/end instead of _min/_max. I am also ensure the “ForceDisplayRangeByIndices” is a great name, could have called it “RequestXXX”?
Hopefully this gets useful for others.

At this point even with best of intent I am unsure if op solved their problem or not, since they go from “absolutely working ideal solution!” to “example has nothing to do with original task” in the same sentence. I’ll close this.

*EDIT*

> still have no clue how to achieve the functionality I want with ImGuiListClipper

!!?
Daniel’s example shows it clearly with the call to ForceDisplayRangeByIndices().

> And who could imagine that I need THREE apostrophes

My first answer said “Use three backward apostrophe” and Daniel’s later answer spelled them out.

**Comment by ike695** [comment]
> > It does not matter.
> 
> It does matter. Michael this is not the first thrrad were you are asking questions, receiving generously detailed answers (thank you Daniel here!) and yet you are refusing to cooperate and being obtuse in your interactions. The reason we are asking for details and pastable minimal repro is that they help both sides in a discussion. Please don’t make it make it harder for us to help you.





https://lnkr.fun/dcd0de0
