### ISSUE TITLE
Mouse cursor

### ISSUE THREAD

**Issue by ebriney** [ocornut/imgui#60]
Hi Omar,

I bound uSynergy on imgui but I need to manually draw a mouse cursor on top of imgui on platform that lacks "hardware" one, typically, smartphone and consoles.

I tried to implement it in imgui but it' s a bit tricky. I need to create a fake window with tooltip flag set to be put at the end of the draw list and as method in ImGuiWindow are not virtual i must set a custom GUIStyle...
 
So, It can be convenient to add a method to display a cursor (ImGui::DisplayMouseCursor()) on demand, don't you think ?

**Comment by paulsapps** [comment]
Maybe supply a call back for rendering it?

**Comment by ocornut** [comment]
The new version supports textures so this is easy to do now. Will try to do it shortly. Callback will be added as well as part of another change.

**Comment by ocornut** [comment]
Added mouse cursor using the new texture atlas:

    io.MouseDrawCursor = true;

https://github.com/ocornut/imgui/commit/ca10c49e27700dfba5d1b6703b21e42ca94cefb0#diff-e5e00627776ba59572e7d1d86554aee6R6810

I also added callbacks today which I am using to render 3d scenes inside ImGui widgets.

**Comment by giladreich** [comment]
Hi @ocornut, sorry for bringing this old issue up again (perhaps it should be on a separate issue). I stumbled upon this problem myself, while setting cursor using the Qt framework (`setOverrideCursor()`). It took me few minutes to realize that ImGui takes over the cursor behavior and I actually wanted to suggest if possible a more flexible API to this, i.e the way Qt does it:
```cpp
    enum CursorShape {
        ArrowCursor,
        UpArrowCursor,
        CrossCursor,
        WaitCursor,
        IBeamCursor,
        SizeVerCursor,
        SizeHorCursor,
        SizeBDiagCursor,
        SizeFDiagCursor,
        SizeAllCursor,
        BlankCursor,
        SplitVCursor,
        SplitHCursor,
        PointingHandCursor,
        ForbiddenCursor,
        WhatsThisCursor,
        BusyCursor,
        OpenHandCursor,
        ClosedHandCursor,
        DragCopyCursor,
        DragMoveCursor,
        DragLinkCursor,
        LastCursor = DragLinkCursor,
        BitmapCursor = 24,
        CustomCursor = 25
    };
```

> Application cursors are stored on an internal stack. setOverrideCursor() pushes the cursor onto the stack, and restoreOverrideCursor() pops the active cursor off the stack. changeOverrideCursor() changes the curently active application override cursor. Every setOverrideCursor() must eventually be followed by a corresponding restoreOverrideCursor(), otherwise the stack will never be emptied.

Because of storing cursor in a stack (push/pop), gives you basically the flexibility set custom cursors and easily pop them with `restoreOverrideCursor()`.
It's also super convenient setting cursors on the widget level in the Qt framework, i.e:
```cpp
    QPixmap cursor = QPixmap(":/cursors/cursor_normal.cur");
    setCursor(QCursor(cursor, 0, 0));
```

We could maybe set something similar in ImGui, i.e:
```cpp
enum ImGuiMouseCursor_
{
    ImGuiMouseCursor_None  = -1,
    ImGuiMouseCursor_Arrow = 0,
    ImGuiMouseCursor_TextInput,
    ImGuiMouseCursor_ResizeAll,
    ImGuiMouseCursor_ResizeNS,
    ImGuiMouseCursor_ResizeEW,
    ImGuiMouseCursor_ResizeNESW,
    ImGuiMouseCursor_ResizeNWSE,
    ImGuiMouseCursor_Hand,
    ImGuiMouseCursor_Custom,
    ImGuiMouseCursor_COUNT
};
```
And then, just like:
```cpp
void ImGui::SetMouseCursor(ImGuiMouseCursor cursor_type);
```
We can pass it a texture:
```cpp
ImGui::SetMouseCursorCustom(ImTextureID data)
{
    GImGui->MouseCursor = ImGuiMouseCursor_Custom;
    // and data will be used in similar way to ImGui::Image
}
```
My apologies if it's too much of a confusion, but something like this could really make the interaction with cursors better and platform independent.
