### ISSUE TITLE
InputText() Failing

### ISSUE THREAD

**Issue by BradleyTesting** [ocornut/imgui#6008]
Hello, 

I'm sure this has been asked before so even if you can link me to that issue it would help. I can't figure out how to input text and numbers without the programme crashing. This is including just running the example_win32_directx12 example and trying to input text on the demo window. I'm using the code in Visual Studio 2022 with C++. 

Regards

**Comment by BradleyTesting** [comment]
So it is fixed by removing IM_ASSERT(apply_new_text_length >= 0); and IM_ASSERT(apply_new_text_length <= buf_size); , but will this break anything down the line?

**Comment by GamingMinds-DanielC** [comment]
The assert is there to test for errors in debug builds, is doesn't actively change the behavior. Removing it will not fix your problem, but obfuscate it. Your problem sounds like a buffer overrun due to wrong parameters. Without the assert, this will still happen and potentially corrupt your memory for unpredictable behavior elsewhere. So please don't remove asserts, they are there for a good reason.

Also it would be much easier to help if you post the code in question, specifically your call to `InputText()` and the variables involved. Otherwise it's just guesswork. If text input in the demo window already fails for you, that's bad. Did you modify the ImGui sources in any other way or does it already happen with clean sources from this repository?

**Comment by ocornut** [comment]
Any news @BradleyTesting ?
It seems pretty unusual that this would not work with vanilla code and exemple, we would need more details to confirm this. Could you make a video recording?

Happy new year!

**Comment by BradleyTesting** [comment]
I fixed it by removing IM_ASSERT(apply_new_text_length >= 0); and IM_ASSERT(apply_new_text_length <= buf_size)

**Comment by ocornut** [comment]
This is not an appropriate thing to do.

We need you to provide more details, e.g. a video and a repro, because " This is including just running the example_win32_directx12 example and trying to input text on the demo window. " doesn't seem to happen here.

**Comment by ocornut** [comment]
I'm closing this since OP is not helping and issue is incredibly suspicious in the first place. If you have more data let us know and we'll try to help
.
