### ISSUE TITLE
Blank white screen when resizing hwnd

### ISSUE THREAD

**Issue by huyluongme** [ocornut/imgui#6010]
I setup my menu pos is viewport->WorkPos and size is viewport->WorkSize.
But when i resize hwnd then my menu not resize, and have a black space, when i release mouse my menu fix size.
How can i make my menu resize when hwnd resize ?
So sorry for my English. Thanks to everyone for the help.

https://user-images.githubusercontent.com/48280785/208662353-0cbad42a-2497-422c-bad6-e87080955745.mp4

**Comment by PathogenDavid** [comment]
This is a Windows issue and not a Dear ImGui one. The window's message pump is blocked when the user is resizing the window. This is a problem with the many apps using accelerated graphics APIs.

You own the main viewport so fixing it is your responsibility. We don't handle it in the examples because there's many different solutions for handling it and they all come with their own set of tradeoffs.

See related issues: https://github.com/ocornut/imgui/issues/3672 https://github.com/ocornut/imgui/issues/5728 https://github.com/ocornut/imgui/issues/5076

**Comment by GamingMinds-DanielC** [comment]
The solution I used for this was to handle the per frame updates in `WM_PAINT` instead of right after the message pump in the update loop. There are a few extra steps involved to avoid some problems, here is a reduced excerpt from my window function:

```c++
	// statics for this example, members of a class bound to GWLP_USERDATA in my code
	static int  paintDepth      = 0;
	static bool useDefaultPaint = false; // set to true while a file dialog is open

	// ...

	case WM_PAINT:
		// no BeginPaint() + EndPaint(), no ValidateRect() / ValidateRgn(),
		// handle external update and keep window invalidated so that WM_PAINT is generated continuously

		// if any modal loop comes from within the frame update, skip to default handling
		if ( paintDepth > 0 )
			break;

		paintDepth++;

		// your frame update goes here

		paintDepth--;

		// invalidate in case of validation by any modal loop
		InvalidateRect( hWnd, NULL, FALSE );

		// let DefWindowProc handle WM_PAINT if file dialogs are open, otherwise modal prompts are suppressed
		if ( !useDefaultPaint )
			return 0;

		break;
```

If you want to use this approach and also default file dialogs, don't open them directly from within your frame update. Instead, post a user message for a delayed call and handle the result in f.e. a lambda. Set the flag for default painting before the call, reset it afterwards and don't forget to invalidate your window again.

**Comment by huyluongme** [comment]
> ```c++
> InvalidateRect
> ```



> This is a Windows issue and not a Dear ImGui one. The window's message pump is blocked when the user is resizing the window. This is a problem with the many apps using accelerated graphics APIs.
> 
> You own the main viewport so fixing it is your responsibility. We don't handle it in the examples because there's many different solutions for handling it and they all come with their own set of tradeoffs.
> 
> See related issues: #3672 #5728 #5076

thanks for your help <3. it useful for me

**Comment by huyluongme** [comment]
> As David said, this is a Windows issue, but there are multiple solutions. The solution I used for this was to handle the per frame updates in `WM_PAINT` instead of right after the message pump in the update loop. There are a few extra steps involved to avoid some problems, here is a reduced excerpt from my window function:
> 
> ```c++
> 	// statics for this example, members of a class bound to GWLP_USERDATA in my code
> 	static int  paintDepth      = 0;
> 	static bool useDefaultPaint = false; // set to true while a file dialog is open
> 
> 	// ...
> 
> 	case WM_PAINT:
> 		// no BeginPaint() + EndPaint(), no ValidateRect() / ValidateRgn(),
> 		// handle external update and keep window invalidated so that WM_PAINT is generated continuously
> 
> 		// if any modal loop comes from within the frame update, skip to default handling
> 		if ( paintDepth > 0 )
> 			break;
> 
> 		paintDepth++;
> 
> 		// your frame update goes here
> 
> 		paintDepth--;
> 
> 		// invalidate in case of validation by any modal loop
> 		InvalidateRect( hWnd, NULL, FALSE );
> 
> 		// let DefWindowProc handle WM_PAINT if file dialogs are open, otherwise modal prompts are suppressed
> 		if ( !useDefaultPaint )
> 			return 0;
> 
> 		break;
> ```
> 
> If you want to use this approach and also default file dialogs, don't open them directly from within your frame update. Instead, post a user message for a delayed call and handle the result in f.e. a lambda. Set the flag for default painting before the call, reset it afterwards and don't forget to invalidate your window again.

thanks for your help <3. it useful for me

**Comment by huyluongme** [comment]
> This is a Windows issue and not a Dear ImGui one. The window's message pump is blocked when the user is resizing the window. This is a problem with the many apps using accelerated graphics APIs.
> 
> You own the main viewport so fixing it is your responsibility. We don't handle it in the examples because there's many different solutions for handling it and they all come with their own set of tradeoffs.
> 
> See related issues: #3672 #5728 #5076

thanks for your help <3. it useful for me
