### ISSUE TITLE
How to be informed about Font Packing failure?

### ISSUE THREAD

**Issue by pthom** [ocornut/imgui#6089]
**Version/Branch of Dear ImGui:**

Version: v1.89.2
Branch: docking/

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: clang / msvc / emscripten
Operating System: Win/Mac/Linux/emscripten

**My Issue/Question:**

Is there a way to be informed when font build fails (because of too many fonts or too big font sizes)? 

In  my application, I need to load a lot of fonts, and sometimes with big sizes. My issue is that sometimes the font fails to build, and I see no way to be informed of this failure. My aim would be able to be informed, and in this case reduce the number of loaded fonts.

This failure is very much GPU and OS dependent, i.e. it may or may not happen depending on the configuration.

**Minimal example:**

````cpp
void LoadFonts()
{
    // load a lot of fonts, to trigger the issue
    for (float fontSize = 14.f; fontSize < 150.f; fontSize += 1.f)
    {
        ImGui::GetIO().Fonts->AddFontFromFileTTF("fonts/DroidSans.ttf", fontSize); // any font file will do
    }
}

void Gui()
{
    bool b = ImGui::GetIO().Fonts->IsBuilt(); // will return true even if the fonts build failed!

    // This will not render correctly when the build failed
    // (However CalcTextSize still returns coherent values)
    ImGui::Text("Hello, world!");
}


````

**Comment by ocornut** [comment]
> This failure is very much GPU and OS dependent, i.e. it may or may not happen depending on the configuration.

I am not sure building/packing would actually fail in this condition.
What makes you think so?

If I run this code, what happens if that building/packing works, but we request a texture that is too big and the backend fails to create the texture. In the case of e..g imgui_impl_dx11 this leads to an assert.

So if I understand this right, what we could do is design a way for backend to fail more gracefully and report that upload failure so the app can process it.

**Comment by pthom** [comment]
> I am not sure building/packing would actually fail in this condition.

Sorry, I made a wrong assumption! This is because the bug happened to me only on emscripten, where debugging is not that friendly.

> What makes you think so?

This comment inside imgui_draw.cpp:ImFontAtlasBuildWithStbTruetype() made me think it might have been the issue:
````
// FIXME: We are not handling packing failure here (would happen if we got off TEX_HEIGHT_MAX or if a single if larger than TexWidth?)
````

> If I run this code, what happens if that building/packing works, but we request a texture that is too big and the backend fails to create the texture. In the case of e..g imgui_impl_dx11 this leads to an assert.

In my case, this was happening inside ImGui_ImplOpenGL3_CreateFontsTexture, inside     GL_CALL(glTexImage2D(...)); and the error is silently ignored.

> what we could do is design a way for backend to fail more gracefully and report that upload failure so the app can process it.

Actually thanks to your answer I now have a way to detect by calling `glGetError()` so I think this issue can be closed.

**Comment by ocornut** [comment]
> This comment inside imgui_draw.cpp:ImFontAtlasBuildWithStbTruetype() made me think it might have been the issue:

There are perhaps paths and conditions leading to undetected packing failures, but to keep us focused i’d prefer to wait until it happens to someone rather than manufacture a failing case.

Happy to close this if you can use glGetError().
As we rework the backends to allow for texture updates, we may want or need to consider providing extra feedback of that sort in a backend-agnostic way. If that happens i’ll mention it here.
