### ISSUE TITLE
Warning about field using anonymous namespace with imgui_freetype

### ISSUE THREAD

**Issue by dbr** [ocornut/imgui#6104]
**Version/Branch of Dear ImGui:**

Version: 1.89.2 (via imgui-rs)
Branch: master with freetype enabled

**Back-end/Renderer/Compiler/OS**

Compiler: `g++ (Debian 10.2.1-6) 10.2.1 20210110`
Operating System: Linux

**My Issue/Question:**

When building imgui with the freetype feature enabled, we get the following warnings:

```
warning: <command-line>: note: this is the location of the previous definition
warning: In file included from include_imgui_master_freetype.cpp:12:
warning: ./third-party/imgui-master-freetype/imgui/misc/freetype/imgui_freetype.cpp:366:8: warning: ‘ImFontBuildSrcGlyphFT’ has a field ‘ImFontBuildSrcGlyphFT::Info’ whose type uses the anonymous namespace [-Wsubobject-linkage]
warning:   366 | struct ImFontBuildSrcGlyphFT
warning:       |        ^~~~~~~~~~~~~~~~~~~~~
warning: ./third-party/imgui-master-freetype/imgui/misc/freetype/imgui_freetype.cpp:375:8: warning: ‘ImFontBuildSrcDataFT’ has a field ‘ImFontBuildSrcDataFT::Font’ whose type uses the anonymous namespace [-Wsubobject-linkage]
warning:   375 | struct ImFontBuildSrcDataFT
warning:       |        ^~~~~~~~~~~~~~~~~~~~
```

Doesn't cause any noticable problems for us, only noticed the warnings

Let me know if any further details are required!

**Comment by ocornut** [comment]
Thank you for reporting.

It seems like this would cause a problem if multiple compilation unit used a different version of the type.
One possible fix would be to use fully qualified names for every type in the field, which would lose the benefit of using an anonymous namespace in order to reduce symbol leakage to other compilation units. I feel the current solution is nice so I've disabled the warning locally in 8f907bc and also add push/pop in case this gets used in a jumbo/unity builds.

Btw:
> In file included from include_imgui_master_freetype.cpp:12:

In case this is useful, we provide `misc/single_file/imgui_single_file.h` which may be used as a helper, and with e8421de I made sure it included imgui_freetype if enabled via `IMGUI_ENABLE_FREETYPE`.

Some references about the warning:
https://stackoverflow.com/questions/37722850/how-to-silence-whose-type-uses-the-anonymous-namespace-werror-gcc-version-4
https://www.reddit.com/r/cpp_questions/comments/8im3h4/warning_class_has_a_field_whose_type_uses_the/
