### ISSUE TITLE
How to animate draw_list?

### ISSUE THREAD

**Issue by hh02** [ocornut/imgui#6122]
For example, I want to animate drawing a cubic bezier curve, how can I draw it from 0% to 100%?
I didn't find any api to draw a  specific proportion of a shape.

**Comment by ocornut** [comment]
Our function e.g. `ImDrawList::AddBezierCubic()` are stroking an entire curve.
If you only want to stroke partially you may want to implement your own function to create a path based on range of a bezier curve, then call `PathStroke()`. See `PathBezierQuadraticCurveTo()` for reference of what the "num_segments" path does:

```cpp
        float t_step = 1.0f / (float)num_segments;
        for (int i_step = 1; i_step <= num_segments; i_step++)
            _Path.push_back(ImBezierQuadraticCalc(p1, p2, p3, t_step * i_step));
```

Using this you could stroke a given "range" of the curve. However note that 50% of a bezier curve doesn't correspond to exactly the center of its linear length. The more twisted the curve is the more incorrect the approximation will be. Depending on how fast and what your animation is for it might matter or not matter at all. If you want to animate that stroke with a constant movement you need more maths.

You can refer to this great video by Freya Holmer if you want to learn about bezier curves:
https://www.youtube.com/watch?v=aVwxzDHniEw

I have to close this because at heart none of this is Dear ImGui related.
Dear ImGui's ImDrawList allow you to stroke a path, creating the path is done on your side.

**Comment by hh02** [comment]
OK, I got it. Thank you for your detailed answer! Thank you for your time!
