### ISSUE TITLE
Internal Roundings

### ISSUE THREAD

**Issue by TTommyGTR** [ocornut/imgui#6133]
**Version/Branch of Dear ImGui:**

Version: v1.89.3 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: dx9 + win32
Compiler: MSVC
Operating System: Win11

**My Issue/Question:**

So basically whenever i try to round the corners of Rects it just wont work, but only in internal use case, if i use it externally it works as expected. So when i try to use this in a .dll file the rounding of these Rect functions just completely wont work.
Thanks for any help!

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/122651273/215785432-fa9bd013-a84c-487b-b45d-55349ce1b62c.png)

// Here's some code anyone can copy and paste to reproduce your issue
```
// Only internal
auto draw = ImGui::GetWindowDrawList();
auto pos = ImGui::GetWindowPos();
auto size = ImGui::GetWindowSize();
ImGuiStyle style = ImGui::GetStyle();
draw->AddRectFilled(ImVec2(pos.x = 0, pos.y = 0), ImVec2(pos.x + size.x, pos.y + 50), ImColor(11, 6, 42, 255), 5, 
ImDrawFlags_RoundCornersTop);
```

**Comment by ocornut** [comment]
I don't understand the question/repro and it seems like a case of being confused and not submitting enough information.
I am sorry but we don't have resources to provide that kind of support.

**Comment by GamingMinds-DanielC** [comment]
Spotted your mistake: you are drawing from `ImVec2(pos.x = 0, pos.y = 0)` to `ImVec2(pos.x + size.x, pos.y + 50)`, so effectively starting at `ImVec2(0, 0)`. I assume you wanted `+` instead of `=`. Just in case that is not just a typo or copy & paste error and you actually write code like that, please get rid of that habit since it is dangerous.

The order of parameter evaluation in C++ is unspecified, so the second parameter can be evaluated before you zero out the position during evaluation of the first. That will give you a lower right corner at the expected location, but the rectangle will extend far out of the window to the top and left. The rounded corners may very well be there, but you won't see them since they are clipped out by the window.
