### ISSUE TITLE
imgui plugin management 

### ISSUE THREAD

**Issue by Half-People** [ocornut/imgui#6139]
Hello, I am a developer from Hong Kong, maybe my English is not good
I am now developing an imgui editor, and I need to use the Plugin system to do it with dll. If I don’t import the cpp file of imgui, I can’t package it. If I import it, I will run my main porject again. error This error problem should be that the variables in imgui.cpp are not synchronized, so there is a problem. I don’t know if there is any way to solve it.

![image](https://user-images.githubusercontent.com/56476339/216467515-3eea46c3-87c2-430c-be84-e795da48be2d.png)

(What I want is to create and draw windows in the main porject and draw separate imguiWindow or items in the plugin)

**Comment by ocornut** [comment]
Dear ImGui use 1 global variable GImGui to store the current context pointer. This global needs to be synced for each unique DLL boundaries, so code from each unique DLL needs to call ImGui::SetCurrentContext(…) at least once to fill this variable for the DLL. Otherwise the variable will be perceived as NULL from some DLL.
