### ISSUE TITLE
Multi-viewports: intercepting viewport input events

### ISSUE THREAD

**Issue by Casqade** [ocornut/imgui#6142]
**Version/Branch of Dear ImGui:**

Version: v1.89.2
Branch: docking (d822c65317ba881798bed8fce9ffba267d27dada)

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: gcc 12.2.1
Operating System: Windows 10 (MSYS2) & archlinux 6.1.9

**My Issue/Question:**

Is there any way to intercept input events in viewports ?

At this moment, GLFW input callbacks are registered for the main imgui window only. For instance, debugging [`ImGui_ImplGlfw_MouseButtonCallback`](https://github.com/ocornut/imgui/blob/d822c65317ba881798bed8fce9ffba267d27dada/backends/imgui_impl_glfw.cpp#L301) shows that `ImGui_ImplGlfw_Data::PrevUserCallbackMousebutton` is empty when clicking over any external viewport (created by imgui side via `ImGui_ImplGlfw_CreateWindow`). 

Thus, I lose control over event processing in viewports and there's nowhere I can check for `WantCaptureMouse` or `WantCaptureKeyboard` flags since user callbacks don't get executed.

```
// auto window = glfwCreateWindow(...);

glfwSetMouseButtonCallback(window,
[] ( GLFWwindow*, int, int, int )
{
  printf("click callback");
});

ImGui_ImplGlfw_InitForOpenGL(window, true); 
// User callback is forwarded to main viewport only. 
// External viewports don't get the pointer
```

**Comment by ocornut** [comment]
Hello,

> Is there any way to intercept input events in viewports ?

Why?
I'm not sure to understand for what purpose you would use those callback for?
Why not using dear imgui's state in `ImGuiIO` ?

**Comment by Casqade** [comment]
> Hello,
> 
> > Is there any way to intercept input events in viewports ?
> 
> Why? I'm not sure to understand for what purpose you would use those callback for? Why not using dear imgui's state in `ImGuiIO` ?

I have variable number of level editor viewports where I use `ImDrawList::AddImage` to render from selected camera framebuffer onto window background draw list. Clicking on a viewport grabs the mouse and enables manual camera controls. Since my input event processing flow is initiated by glfw user callbacks (as well as imgui's, right?), I can ignore these events based on imgui state (e.g. `WantCaptureMouse`). Then these events are processed by imgui's callback implementation. 

In my opinion, it's a very convenient design! And it worked flawlessly until I docked viewport out of the main window: my callbacks are completely ignored by new imgui viewports (main viewport still works, obviously). I understand why this happens, I'm not sure whether it is a bug or an intentional limitation.

**Comment by Casqade** [comment]
> Why not using dear imgui's state in `ImGuiIO` ?

I don't think caching ImGuiIO every frame to detect changes in input state is a good idea when there's already a good system in place built around GLFW callback chaining. I'm afraid it will also introduce inconsistency with existing system: differentiating input event uniqueness from both GLFW and ImGuiIO simultaneously would be impossible when they both fire.

**Comment by ocornut** [comment]
Thanks for your explanation, it makes sense. (I always prefer to gather context/intent).

> shows that ImGui_ImplGlfw_Data::PrevUserCallbackMousebutton is empty when clicking over any external viewport (created by imgui side via ImGui_ImplGlfw_CreateWindow).

I may be wrong but I think this is incorrect: assuming you called `ImGui_ImplGlfw_Init()` with `install_callbacks = true`, or manually called, `ImGui_ImplGlfw_InstallCallbacks()`, I guess`PrevUserCallbackMousebutton` is actually non NULL since this is shared for the whole imgui context. BUT the callback is not chained because of the subsequent `window == bd->Window` test (at this point `bd->Window` is the "main window". This may be the only thing stopping you from getting that callback.

Removing that test means we would put the burden on users app to check the `window` pointer, which is a simple burden but would be a breaking change. It may be a reasonable breaking change. That, or we make this opt-in via a config option.

**Comment by GamingMinds-DanielC** [comment]
I had a similar problem some time (and IO interface changes) ago. I didn't check if my solution is still required with the changes to the API since then, but it still works as expected. It's not platform independent, but here is a shortened version with the relevant parts:

```c++
static void ( *WindowImGui::ImGui_Platform_CreateWindow )( ImGuiViewport* vp ) = nullptr;

void Replacement_Platform_CreateWindow( ImGuiViewport* vp )
{
	if ( ImGui_Platform_CreateWindow != nullptr )
		ImGui_Platform_CreateWindow( vp );

	if ( vp->PlatformHandle != nullptr )
	{
		// platform dependent manipulation of viewport window, f.e. in Win32:
		// SetWindowLongPtr( (HWND)vp->PlatformHandle, GWLP_WNDPROC, (LONG_PTR)CustomWindowProcPlatform );
	}
}

void HijackImGuiPlatformWindows()
{
	ImGuiPlatformIO& platform_io = ImGui::GetPlatformIO();

	ImGui_Platform_CreateWindow       = platform_io.Platform_CreateWindow;
	platform_io.Platform_CreateWindow = Replacement_Platform_CreateWindow;
}
```

The idea is to use the default backends untouched to avoid problems with future updates, but hijack specific parts as needed from the outside. In this case replacing the platform window creation with a custom one that calls the original and then manipulates the resulting window. Instead of calling the original you could also copy the original and manipulate accordingly, but my suggestion is to reuse as much as you can.

**Comment by ocornut** [comment]
FYI
That `window == bd->Window` test was merged in master via 2ad912bb but its origin is actually a3d6554e8 which TL;DR when merged master which recently added callback chaining in my WIP viewport branch I added that test which seemed decent at the time, but it wasn't trying to solve a problem (and in fact it created this problem).

**Comment by Casqade** [comment]
> I guess`PrevUserCallbackMousebutton` is actually non NULL

Hmm, you're right. False alarm: another debugging session proved `PrevUserCallbackMousebutton` is a valid pointer indeed. Probably looked at the wrong variable last time. Should have double-checked, my bad ( 

Anyway, the window check is a real barrier here. 

> put the burden on users app to check the `window` pointer

Just clarifying: you mean checking the `window` pointer inside user callback, right ? I had a thought that even if viewports would call user callbacks, they would pass different `window` pointers. I'm sure omitting pointer check would definitely be a breaking change so I agree with you in regards of it being an opt-in solution. 

By the way, ignoring window pointer check IS actually a breaking change in my code! Since I rely on `glfwSetWindowUserPointer` for storing a pointer to my class instance in main window, that pointer is not being passed to imgui viewport windows. Hence, my callbacks as well don't get that pointer so I still can't process the events properly) So that's another problem I guess... Can be temporarily fixed on my side with something dirty like a static pointer to my class. 

Some thoughts: 
I suppose forcing imgui to copy main window user pointer to viewport windows wouldn't break anything since opted-in users know what they're doing and what to expect. However, it can introduce dangling pointer when users destroy their object and change GLFW user pointer without notifying imgui (no API for that currently). What do you think ?

**Comment by Casqade** [comment]
> The idea is to use the default backends untouched to avoid problems with future updates, but hijack specific parts as needed from the outside

Interesting, thanks for the idea & example! I'm not sure I'll come this way, but it would be a great fallback solution.

**Comment by ocornut** [comment]
Daniel's answer is also a solution: hi-jack `ImGui_Platform_CreateWindow`, call the original and immediately after a window creation redirect the callbacks to your code. This would be the logical conclusion of if you installed the GLFW backend without installing callbacks automatically.

But this means chaining many callbacks, which is cumbersome, and may feel brittle in case we decide to register more (same issue as when initializing backend with install_callbacks=false). Also it includes some that you might want to use for which our function handlers are private because they are only used for secondary viewports.

However:
> suppose forcing imgui to copy main window user pointer to viewport windows wouldn't break anything since opted-in users know what they're doing and what to expect. However, it can introduce dangling pointer when users destroy their object and change GLFW user pointer without notifying imgui (no API for that currently). What do you think ?

You can use that idea above for setting the user pointer on secondary viewports.
I think it would be over-reaching and potentially incorrect if we did so automatically.

Back to main topic, I can add:
```cpp
IMGUI_IMPL_API void     ImGui_ImplGlfw_SetCallbacksChainForAllWindows(bool chain_for_all_windows);  // Set to true to chain callbacks to all windows (including user's created ones and secondary viewports).
```
cpp
```cpp
// Set to 'true' to chain installed callbacks for ALL windows (including user's created ones and secondary viewports created by the backends)
// This is 'false' by default meaning we only chain callbacks for the main viewport.
// We cannot set this to 'true' by default because user's callbacks may be not testing the 'window' parameter of their callback.
// If you set this to 'true' your user callback code will need to make sure you are testing the 'window' parameter.
void ImGui_ImplGlfw_SetCallbacksChainForAllWindows(bool chain_for_all_windows)
{
    ImGui_ImplGlfw_Data* bd = ImGui_ImplGlfw_GetBackendData();
    bd->CallbacksChainForAllWindows = chain_for_all_windows;
}
```

(Technically speaking the filter is actually BREAKING the case were user creates multiple windows themselves and expect the backends to setup their callback and chain to setup. But because this could never work before, the rare users who created multiple-windows themselves would have already installed the callbacks themselves, so we're not changing their experience, merely improving the experience of future users.)

**Comment by Casqade** [comment]
> Back to main topic, I can add

Wow, that was fast! Thanks, I'll try that asap. 

>You can use that idea above for setting the user pointer on secondary viewports.
I think it would be over-reaching and potentially incorrect if we did so automatically.

Yes, totally agree. I'll post the 'hijacking' code when I get it to work

**Comment by Casqade** [comment]
So, with a085581057ae89491be86782920981b5d0b3f969 in place, chaining works perfectly well !

As for the user pointer setting, Daniel's solution actually doesn't help in solving this particular problem: assigning user pointer from a callback requires accessing some global state anyway: 
```
void HijackImGuiPlatformGlfw()
{
  ImGuiPlatformIO& platformIO = ImGui::GetPlatformIO();

  static auto ImGuiCreateWindow = platformIO.Platform_CreateWindow;

  platformIO.Platform_CreateWindow =
  [] ( ImGuiViewport* vp )
  {
    if ( ImGuiCreateWindow != nullptr )
        ImGuiCreateWindow(vp);

    if ( vp->PlatformHandle == nullptr )
      return;

    const auto window = static_cast <GLFWwindow*> (vp->PlatformHandle);

    void* instancePtr = nullptr; // where to get it ?
    glfwSetWindowUserPointer(window, instancePtr);
  };
}
```

Since I wasn't using `ImGuiPlatformIO::UserData` for something else, putting my instance there was IMO the only way to avoid introducing another global state (ImGui context itself is already a global state!). 
So that's what I came up with: 
```
// somewhere inside my class
ImGui::GetIO().UserData = this;

// just adding a pointer check and reassignment to my original callback code
glfwSetMouseButtonCallback(mainWindow,
[] ( GLFWwindow* window, int button, int action, int mods )
{
  auto instancePtr = glfwGetWindowUserPointer(window); // main window
  if ( instancePtr == nullptr )
    instancePtr = ImGui::GetIO().UserData; // imgui viewport window

  const auto instance = static_cast <MyClass*> (instancePtr);

  instance->mouseButtonEvent(window, button, action, mods);
});
```

In my situation it works safe because the class instance is the one calling ImGui init/shutdown routines and I don't even have to reset the user data pointer on instance destruction. Although, programmers already utilizing `ImGuiPlatformIO::UserData` for other purposes would probably have to be more creative if they want to avoid global state access.
