### ISSUE TITLE
Issue when trying to maximize window

### ISSUE THREAD

**Issue by Vin789** [ocornut/imgui#6179]
**Version/Branch of Dear ImGui:**

Version: 1.89.4 WIP (18931)
Branch: https://github.com/ocornut/imgui/tree/docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui.impl_sdl2.cpp
Operating System: Windows 10
SDL Version: SDL2-2.24.0

**My Issue/Question:**

Hi / Bonjour !
Context: For my custom video game editor I need to be able to minimize/maximize external window for user confort. Minimize works fine (handle by SDL_MinimizeWindow and the fact that ImGui check this state i.e. Platform_GetWindowMinimized). Now for Maximize there is no prebuild function inside the backend implementation. So I decided to simply use SetNextWindowPos/SetNextWindowSize.

Using these 2 functions before the ImGui::Begin indeed place and size the window correctly but after that if I try to move the resized window I have graphic issues on the other screen. The issue itself is a full redraw of the resize window to the other screen. Unfortunately it's not capturable by screenshot or video. Still on the video you can see that the display become a fully black screen.
Probably an issue with the backend rendering pipeline unless I missed a flag or something else.

**Screenshots/Video**

https://user-images.githubusercontent.com/13332569/219874043-54a4644f-db68-4d49-adea-2a4bf0f8f36c.mp4

To reproduce it move the second window (hello world) to an other screen, click the maximize button then try to drag the window to the other screen from the the title bar.

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

To test this we need to add minors code modification to the main.cpp of example_sdl2_opengl3 project.

```
// Before the main loop add a Maximize bool
    bool Maximize = false;
    
// Inside the main loop before ImGui::Begin("Hello, world!");
    if (Maximize)
    {
        ImGui::SetNextWindowPos(ImVec2(-1920.0f, 0.0f)); // Use values that make sense with your display monitors
        ImGui::SetNextWindowSize(ImVec2(1920.0f, 1080.0f));
        Maximize = false;
    }

// Finally add a Maximize button to test after the counter button (if (ImGui::Button("Button")) ) for example
    if (ImGui::Button("Maximize me"))
    {
        Maximize = true;
    }
```
If the code example is not enough I can provide the full .cpp file code.

Thx you for your help.

**Comment by PathogenDavid** [comment]
The exact behavior is slightly different, but I can basically repro this.

What I think is happening is the graphics driver is seeing a borderless OpenGL window that's the exact size of a monitor and it's using that to heuristically determine that you're trying to make it fullscreen. Unfortunately this heuristic is wrong in Dear ImGui's case and causes *strange* things to happen. (EG: I had my test window duplicated to multiple monitors if I tried to move it.)

I'm blaming driver heuristics since the issue does not happen with `example_sdl2_directx11` and I don't see any logic in SDL to try and "handle" this.

It would be interesting to know what driver vendor you're using. I'm on Nvidia.

-------------------

I don't know what the fix would be here. If I'm right that it's a driver heuristic it might be pretty painful to find a non-hacky workaround.

As far as fixing it in your app goes, the slightly jank solution that works on my machine is to set the height to be 1px too tall when the working area matches the overall monitor size.

FYI in case you haven't noticed yet, the docking branch can tell you about the monitor topology:

```cpp
// Fill the working area of the 0th monitor
ImGuiPlatformMonitor monitor = ImGui::GetPlatformIO().Monitors[0];
ImGui::SetNextWindowPos(monitor.WorkPos);
ImGui::SetNextWindowSize(monitor.WorkSize);
```

**Comment by Vin789** [comment]
Hi David !

Thx for the explanation. Maybe there is a way to disable this driver "behavior". I'm on Nvidia too, good old GeForce GTX 1060. 

My first way of dealing with Maximize/Minimize/Close was to remove the ImGui window border and put back the OS one (works fine for all this) but the issue with this is the lost of the Docking feature as docking is ofc not detected when moving the window from the OS header (it also freeze the program, probably because the input polling is in the main thread unless it's a window behavior). So that's why I was going back to ImGui header with a borderless window.

I will try your option with the 1px diff. And yeah I know about the Display monitor (saw them in the demo) inside ImGui but I was going as fast as possible to test the issue, thx anyway :)

**Comment by Vin789** [comment]
Hi @PathogenDavid.

The 1 pixel hack works fine for me. Closing this thread.

Thx again for your help.
