### ISSUE TITLE
Color Edit Flag: `ImGuiColorEditFlags_NoSidePreview` Still Takes The Same Space

### ISSUE THREAD

**Issue by pegvin** [ocornut/imgui#6194]
**Version/Branch of Dear ImGui:**

Version: v1.89.1
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_sdlrenderer.cpp
Compiler: Clang + Clang++
Operating System: Manjaro

**My Issue/Question:**
sorry it's my second issue today but i've been working on my project actively again.

i'm trying to create a `ColorPicker4` with `ImGuiColorEditFlags_NoSidePreview` flag, the side preview as intended does hide but it still takes the space amount of space as it did with side preview enabled

**Screenshots/Video**

https://user-images.githubusercontent.com/75035219/221153553-d3f94488-1fe6-4cb4-b05f-7796b3c5f491.mp4

**Standalone, minimal, complete and verifiable example:**
```c++
...
bool sidePreviewEnabled = true;
ImGui::Checkbox("Side Preview Enabled", &sidePreviewEnabled);

float color[4] = { 1.0f, 0.0f, 0.0f, 1.0f };
ImGuiColorEditFlags flags = ImGuiColorEditFlags_NoInputs | ImGuiColorEditFlags_NoLabel;
if (sidePreviewEnabled) flags |= ImGuiColorEditFlags_NoSidePreview;
ImGui::ColorPicker4("##ColorPickerWidget", (float*)&color, flags);
...
```

**Comment by ocornut** [comment]
The side preview is displayed on the "right side" of the framed widget, in the same same location where a Label would appear if visible. So it doesn't matter if ImGuiColorEditFlags_NoSidePreview is set of not: cConsider the possibility that you may have used a visible label (e.g. `"ColorPickerWidget"` instead of `"##ColorPickerWidget"`)).

You can do:
```cpp
ImGui::SetNextItemWidth(-FLT_MIN); // right align
ImGui::ColorPicker4("##ColorPickerWidget", (float*)&color, flags);
```

Or you can use `PushItemWidth() / PopItemWidth()` to apply this to multiple widgets.
