### ISSUE TITLE
Hotkeycontrol ?

### ISSUE THREAD

**Issue by oPhadee** [ocornut/imgui#620]
I love using this gui, but do you think you can add a control that lets you click inside a box, then click any key, and it will bind a integer to whatever key you pressed?

**Comment by ocornut** [comment]
I am not sure to understand the request, could you clarify? It sounds like something you could do at user level.

**Comment by Qazwar** [comment]
I think TC is due to the possibility of appointing a hot, directly by the user keys.
Something like that:

`bool clicked = false;
	IMGUI_API void BindKey(const char* label, int &Id)
	{
		if (Button("Press Me"))
			clicked = true;

		SameLine();
		Text(label);

		if (clicked)
		{
			for (size_t i = 0; i < 256; i++)
			{
				if (GetIO().KeysDown[i])
				{
					Id = i;
					clicked = false;
				}			
			}
		}
	}`

`int OutKeyID;
/*......................*/

ImGui::BindKey("KeySelect", OutKeyID);
	ImGui::Text("Key: %d", OutKeyID);
	if (GetAsyncKeyState(OutKeyID) & 0x8000)
		     ImGui::Text("Good");
`
![dcmtl7h](https://cloud.githubusercontent.com/assets/18671550/14923162/643fe71c-0e5d-11e6-9feb-720d01411074.png)

OutKeyID = 75 = 'K'


Sorry for my bad english (using Google translator)

**Comment by ocornut** [comment]
Something along the line of Qazwar said. 
The concept of keyboard identifiers are totally application side as well.

Tips: You can use `IsItemActive()` to test if a widget (e.g. Button) is being clicked and held.
