### ISSUE TITLE
ImGuiKey_4 registers as ImGuiKey_Apostrophe

### ISSUE THREAD

**Issue by sidmostefaoui** [ocornut/imgui#6200]
When I press 4 on the keyboard my app registers it as ImGuiKey_Apostrophe and not ImGuiKey_4. I tried with capslock on and off and with the windows on screen keyboard. Im using glfw as a backend. It works correctly with the glfw/opengl example project in /examples.

**Comment by PathogenDavid** [comment]
For the sake of clarity: Are you saying that it works as expected in `example_glfw_opengl3` but not in your own app?

The [translation from `GLFW_KEY_*` to `ImGuiKey_*`](https://github.com/ocornut/imgui/blob/bfce7750b168b5a857b4379596236dda7b58bd39/backends/imgui_impl_glfw.cpp#L154-L265) is pretty simple, so I'd suspect the root cause is something further upstream.

What version of GLFW are you using? (The example apps use 3.2.0)

------------

This might be an issue of virtual keys not mapping cleanly to Algerian keyboards. From what I was able to find it sounds like you all use the [Tamazight International keyboard](https://en.wikipedia.org/wiki/File:KB_Tamazight_International.svg), which has 4 and apostrophe on the same key. Is that correct?

**Comment by sidmostefaoui** [comment]
Yes, it works as expected in `example_glfw_opengl3` but not in my own app. I'm using GLFW 3.3. As for the keyboard, I use a french azerty layout, and yes it has a 4 and apostrophe on the same key, but also 3 and ", 2 and é, 1 and & on the same keys and the latter do work as expected.

**Comment by sidmostefaoui** [comment]
I just test keys 0 through 9 and discovered that 6 also doesn't work, it registers as `ImGuiKey_Minus`. 1, 2, 3, 5, 7, 8, 9 and 0 work as expected.

**Comment by ocornut** [comment]
If it works in our example try to find the difference between that and your application.

**Comment by ocornut** [comment]
@sidmostefaoui Any update on this?
Have you been able to find out why it works in our example and not in your codebase?
