### ISSUE TITLE
Main viewport does not come to top when focused

### ISSUE THREAD

**Issue by xpsa0421** [ocornut/imgui#6230]
**Version/Branch of Dear ImGui:**
Version: 1.89.3
Branch: docking

**Back-end/Renderer/Compiler/OS**
Back-ends: imgui_impl_dx11cpp + imgui_impl_win32.cpp 
Operating System: Windows 10

**My Issue/Question:**
I have a dockspace over the main viewport, and one floating window. Clicking on any part (menu bar, title bar of the Windows window, dockspace, window docked to main dockspace, etc...) of the main window does not bring the main window to the top. The floating windows are still on the top. How can I bring the main window to the top when it is focused?

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/71711432/223340556-6878b9a7-20a4-466f-aa80-ee553be87f98.png)

**Standalone, minimal, complete and verifiable example:**
```
ImGui::DockSpaceOverViewport();
ImGui::Begin("Floating window");
ImGui::End();
```

**Comment by ocornut** [comment]
As the terms can be tricky, please refer to Glossary (https://github.com/ocornut/imgui/wiki/Glossary) :)

Not every backend support platform-side parent/child relationship directives. 
By default, secondary viewports are created as child platform window of the main viewport, which creates this Z-ordering constraint.

The Win32 backend does support parenting directive, and therefore if you set `io.ConfigViewportNoDefaultParent = true` it becomes possible for the main viewport to come in front of a secondary viewport.

Assuming `io.ConfigViewportNoDefaultParent = true` + win32 backend it almost most:

There's however a niggle: 
- moving to front only happens when a viewport is focused when it wasn't previously focused. 
- when extracting B away from A with a single drag, B is created without being focused.
- as a result, if following that single drag extraction you click back on A, it won't come to front.
- if you click on B first, then click on A it will come to front.

The reason for "B is created without being focused." is a little tricky. We set `ImGuiViewportFlags_NoFocusOnAppearing` which is  honored by `ImGui_ImplWin32_ShowWindow()` and creates this situation. We set `ImGuiViewportFlags_NoFocusOnAppearing` for several reasons which I won't go on detailing right now, but I believe it is something I should investigate again.
