### ISSUE TITLE
Docking and tabs... must be a feature in imgui.

### ISSUE THREAD

**Issue by volcoma** [ocornut/imgui#627]
Ya i know, i can implement it myself or find someone who has already done it like the LumixEngine one, but i cant imagine a case where someone wouldnt want that feature to be built in. It makes imgui so much easier to use and layout. Trying to build good tools without docking and tabs is just a pain in the ass.
P.S: I love imgui regardless :+1:

**Comment by emoon** [comment]
I wouldn't want this in because it bloats the library. It's of course @ocornut that gets to decide this but I rather keep code like this outside of imgui and try to keep the base clean.

**Comment by Cthutu** [comment]
I've started work on this, but I've done a hybrid approach, where the tabs
are controlled by the Win32 API and the contents are created using ImGui.
I don't think ImGui could do a proper tab and docking facility since those
features interact outside the OpenGL context.  For example, imagine
dragging a tab from one frame to another monitor (on a multi-monitor
setup).  You'd want to create a new frame to contain the dragged tab and
it's contents.  What about creating a tool window from a tab like you would
in Visual Studio?  The only solution ImGui could do is something that was
locked inside a single window.  The multi-frame/multi-window management
would need to be done outside ImGui.  If you're happy with that then fine,
but you couldn't do a Visual Studio-style docking environment.  Either way,
it could be a library that can sit on top of ImGui - it doesn't have to be
integrated itself.

**Comment by ocornut** [comment]
Moving this discussion to #351
