### ISSUE TITLE
Multi-viewports don't work with Wayland on linux.

### ISSUE THREAD

**Issue by MubinMuhammad** [ocornut/imgui#6281]
Hi, I'm using Arch Linux, and when I tried to use the imgui docking branch, I got this error:

`GLFW Error 65544: Wayland: Window position retrieval not supported`

Over and over.

And the window that are not inside the GLFW window are not movable.
I am using the OpenGL3 version of imGui.

Why It doesn't work?
expecting to see the fix soon.

**Comment by ocornut** [comment]
It is the [Multi-viewports](https://github.com/ocornut/imgui/wiki/Multi-Viewports) feature which doesn't work on Wayland, because Wayland doesn't allow user application to change window pos/size.

See https://github.com/ocornut/imgui/wiki/Multi-Viewports#issues

If you disable the `ImGuiConfigFlags_ViewportsEnable` flag it should work and you can still benefit from [Docking features](https://github.com/ocornut/imgui/wiki/Docking).

This is unlikely to be fixed soon in the current incarnation of viewports code.
