### ISSUE TITLE
NoCollapse  and NoTitleBar in docking

### ISSUE THREAD

**Issue by thewoz** [ocornut/imgui#6282]
Branch: docking

Sorry for the stupid question but I couldn't find the solution.
I'm trying not to render the elements circled in red and I can't do it.

![Screenshot 2023-03-30 at 11 55 36](https://user-images.githubusercontent.com/907951/228824792-aba05923-2c51-424b-9722-145b9ce2bbba.png)

I tried to do it this way but it doesn't work

`ImGui::Begin("MainWindow", NULL, ImGuiWindowFlags_MenuBar | ImGuiWindowFlags_NoTitleBar);

ImGui::Begin("Left", NULL, ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoTitleBar);
ImGui::Begin("Right", NULL, ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoTitleBar);
ImGui::Begin("Down", NULL, ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoTitleBar);
`

**Comment by ocornut** [comment]
This and similar questions have been discussed in #5597 #4880 #3521 #3335

Essentially, the problem is that as multiple windows can be hosted by a docking-node, it isn't a correct default behavior that window apply their settings to parent node, as it would conflict if multiple windows were in that same node.

You can use this:
```cpp
ImGuiWindowClass window_class;
window_class.DockNodeFlagsOverrideSet = ImGuiDockNodeFlags_NoTabBar;

ImGui::SetNextWindowClass(&window_class);
ImGui::Begin("Left", NULL, ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoTitleBar); ImGui::End();

ImGui::SetNextWindowClass(&window_class);
ImGui::Begin("Right", NULL, ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoTitleBar); ImGui::End();

ImGui::SetNextWindowClass(&window_class);
ImGui::Begin("Down", NULL, ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoTitleBar); ImGui::End();
```

However if you dock both of those windows together you won't see the tab bar...

Maybe a better solution for you is to use `ImGuiDockNodeFlags_AutoHideTabBar` instead of `ImGuiDockNodeFlags_NoTabBar`.

**Comment by thewoz** [comment]
Amazing it works perfectly!
