### ISSUE TITLE
Understand if something has changed in the interface

### ISSUE THREAD

**Issue by thewoz** [ocornut/imgui#6289]
Hi everyone,
I was trying to figure out if there was a way (a function) that would tell if any widgets have changed their value.
I have read a lot of issues related to this topic, some of them very old, but I didn't understand what could be a solution.

**Comment by ocornut** [comment]
Your question is ambiguous so I am not sure I understand it. Please clarify your question.
But all widgets return `true` when the underlying value has been edited.

**Comment by thewoz** [comment]
Sorry so much my fault.
What I meant was if there was a function that would return true if any of the widgets were changed without having to check one by one.
Maybe it is similar to #1049
I was looking for function like ImGui::hasChanged()

**Comment by GamingMinds-DanielC** [comment]
Any widget in the entire UI? The current window? Child window? Table row or group? Too many options to clutter the API with and entirely unnecessary. You can just combine the individual results into a single result that you can then check at the end. Or you can make wrapper functions that add additional housekeeping.

**Comment by ocornut** [comment]
We can’t answer your question correctly without you explaining why you need this. But yes, Daniel’s answer generally applies.

**Comment by thewoz** [comment]
I am making an interface for a computer vision program that makes extensive use of OpenCV. The interface has three windows. One to display the result, one used as a log, and the last one with various widgets that control different parameters of the program. Every time I change one of these parameters I have to perform a whole series of operations. In the case where no parameters are changed, I would like to avoid performing a whole series of calculations. As I understand it, there is no function that returns true or false if one of the window widgets is modified.

**Comment by ocornut** [comment]
That's correct, Daniel answer should apply. 

Also see #614 which has been stall. I haven't closed it because I don't find the idea uninteresting per-se.
We could imagine a begin/end-like interface to capture "any" edits.
The problem is that it would be too tricky to specs what your app consider as "edition" for this specific state 
Would clicking a button led to code that you consider would make your state dirty? 
What if your UI show widgets e.g. Checkbox("Show Grid") that don't affect your dirty state?

I believe this problem doesn't have a good solution, and if we implement one arbitrary design we create a situation where any drifting from that design creates a gap where you suddenly have to switch from the "easy" api to the "manual" one.

I believe it makes more sense to handle it yourself in a flexible manner using, e.g.
```
bool modified = false;
modified |= ImGui::SliderFloat(....);
modified |= ImGui::SliderFloat(....);
modified |= ImGui::SliderFloat(....);
if (ImGui::Button(...) { ;do some action; modified = true; }
if (ImGui::Button("Save") { do some other action; don't modify flag; }
if (modified)
{
}
```

**Comment by thewoz** [comment]
thank you very much for the answers.
indeed one solution for all cases does not exist.
For now I have implemented something similar to what @ocornut  suggested.
But for the future I will also consider the solution proposed by @kaitabuchi314

**Comment by bradphelan** [comment]
It's relatively simple with a small overhead. Create yourself a data model class with default comparison

```cpp
struct Model {
   int x;
   int y;
   auto operator<=>(const Point&) const = default;
}
```

The in your imgui code for your input boxes

```cpp
ImGUI::InputDouble("x", current.x);
ImGUI::InputDouble("y", current.y);
```

At the end of the frame.

```cpp
if(current!=old){
    dirtyFlag = true;
    old = current;
}

if(dirtyFlag){
   /// Do some expensive operation
}
```

Thus you explicity declare what a change in model is rather than expecting IMGui to understand what a model change is. And you also don't clutter up your declarative UI with dirty flag setting like some other comments above suggest you should do.
