### ISSUE TITLE
"ImGuiColumnsFlags_NoResize" is undefined 

### ISSUE THREAD

**Issue by Isanes** [ocornut/imgui#6329]
how is ImGuiColumnsFlags_NoResize undefined 

im new to imgui

**Comment by ocornut** [comment]
This symbol is part of an internal set of flags (from imgui_internal.h) associated to the legacy Columns API.
Since we were never public flags, we renamed them to `ImGuiOldColumnFlags_NoResize` for the purpose of avoiding confusion with the newer and better Tables api. That feature in legacy Columns was also always partially broken.

- You can include `imgui_internal.h` and use `ImGuiOldColumnFlags_NoResize`
- Or you can use the BeginTable/EndTable api which is neater.
