### ISSUE TITLE
ImGui::IsMouseHoveringAnyWindow() frame mismatch

### ISSUE THREAD

**Issue by josiahmanson** [ocornut/imgui#635]
I am testing out adding ImGui to an existing program. In that program, dragging the mouse with a button pressed rotates the view. I am trying to restrict my event processing to only happen when the mouse is not over an ImGui windows. To do so, I tried using the handy function ImGui::IsMouseHoveringAnyWindow(). This mostly works, but if I drag a window near the edge quickly, the function returns false and rotates my view. There appears to be a mismatch between the mouse position that IsMouseHoveringAnyWindow() checks and the actual window position. In this case, it appears that the window position is behind. This could be solved by storing the mouse position during the previous frame and checking against that in IsMouseHoveringAnyWindow().

**Comment by ocornut** [comment]
You should be using `io.WantCaptureMouse` here. Have you read the documentation in the header of imgui.cpp ? `IsMouseHoveringAnyWindow` isn't what you want as it won't handle many dragging cases. Going to add the io.WantCaptureXXX flags in the FAQ right now.

However from the point of view `IsMouseHoveringAnyWindow` there is a minor bug here from the point of view of the user. The bug is caused because moving a window is processed the first time Begin() is called for that window during the frame. The fix should probably be to copy `HoveredWindow = MovedWindow` when the later isn't NULL. Looking into it.

**Comment by ocornut** [comment]
This is due to a bug in FindHoveredWindow() which is subject to a lag introduced when a added the `WindowRectClipped` field (just renamed from `ClippedWindowRect` which was mislabelled and misdocumented) which is synchronized to window Pos/Size in Begin(), so after FindHoveredWindow() is called. The lag has minor side-effects. I have documented it for now and fixed it in the case of MovingWindow, also reorganized the MovingWindow code.

**Comment by ocornut** [comment]
Reopening as commit 313d388bba42e0634a02b976dcdbae238d25eddc caused an issue (#1337).
Also note that `IsPosHoveringAnyWindow` was completely removed, as it was both misleading and buggy, so we can reassert what to do considering that.

**Comment by ocornut** [comment]
Fixed the bug introduced by this change.
The specific bug initially reported here is also still fixed.S
So closing again :)
