### ISSUE TITLE
ImGuiSyntaxColored 

### ISSUE THREAD

**Issue by TurboCoder022618** [ocornut/imgui#6396]
https://github.com/TurboCoder022618/ImGuiSyntaxColored 
This code represents the SyntaxHighlightCPP() function, which is responsible for syntax highlighting in C++ code. The function utilizes the ImGui library to render text with different colors for keywords, data types, preprocessor directives, special characters, escape characters, and comments.

Syntax highlighting in source code can help programmers in easier understanding and debugging of code, which in turn speeds up the software development process.

The SyntaxHighlightCPP() function is an example of good programming practice and can be useful for any programmer creating tools for working with C++ source code.

**Comment by ocornut** [comment]
Hello,
Thanks for posting this. A screenshot would be nice!

> The SyntaxHighlightCPP() function is an example of good programming practice 

Unfortunately as written it seems very inefficient as you are doing hundreds of string compare for every character in the buffer. This would likely be redhibitory for a code buffer of non-trivial size. 
I haven't thought how an optimal way of doing this would work, but I imagine you may want to flatten the logic so that a switch is done on the first character to narrow down further searches/logic.

It's not an easy problem to solve properly and ideally would work within e.g. `InputTextMultiline()`.
I've been experimenting with ways to provide support for this externally aka #3130, will post in those topics when I make progress on this.
