### ISSUE TITLE
How to make glow circle ?

### ISSUE THREAD

**Issue by vinacf001** [ocornut/imgui#6420]
How to make glow circle like picture ??? Thanks !

![111](https://github.com/ocornut/imgui/assets/12063920/5135af69-a518-47b2-88d0-a47395b33f27)

**Comment by GamingMinds-DanielC** [comment]
The circle needs to be rendered into the 3D scene, glow then is a post processing effect. None of this has anything to do with ImGui.

**Comment by ocornut** [comment]
As mentioned this is a basically a graphics programming question.

Technically speaking you can use ImDrawList to create a poor-looking glow by positioning polygons and manipulating vertex alpha.

Amusingly, you can manipulate `draw_list->_FringeScale` to as hack to reuse the line drawing code:

```cpp
ImDrawList* draw_list = ImGui::GetForegroundDrawList();
draw_list->_FringeScale = 10.0f;
ImVec2 p = ImGui::GetMainViewport()->GetCenter();
draw_list->AddCircle(p, 100.0f, IM_COL32(255, 0, 0, 255), 0, 10.0f);
draw_list->AddCircle(ImVec2(p.x+50, p.y+30), 100.0f, IM_COL32(255, 0, 255, 255), 0, 10.0f);
draw_list->_FringeScale = 1.0f;
```
![image](https://github.com/ocornut/imgui/assets/8225057/c602a9d3-b06e-4be1-9921-b0b3d1265d34)

But this is pretty much a misuse of the feature and puts you in a dead-end since you will have little to no-way of customizing the output. It would be better submitting the polygons yourself, which is out of scope of this forum.
