### ISSUE TITLE
Hiding the main window

### ISSUE THREAD

**Issue by ShamaIow** [ocornut/imgui#6531]
**Version/Branch of Dear ImGui:**
Master branch, dear imgui, v1.89.2

**Back-end/Renderer/Compiler/OS**
Windows, Visual Studio, DX11 / Win32

**My Issue/Question:**
So after search for like 2 days i can't even find a project detailing how to delete this main window or hide it and only display the ImGui in it, like a docking without the main window.

**Screenshots/Video**
[The screenshot](https://prnt.sc/113tqi1) show a DX9 project but mine is DX11, i only want to keep the **TEST OVERLAY** without the **Dear Imgui DirectX9 Example** window

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

Step 1: Download the master branch
Step 2: In your project, create a folder named "imgui" and then extract everything from the zip you downloaded into the imgui folder you created
Step 3: Now you have all the files, go into the "examples" folder and delete everything else then the following files / folders:

- example_win32_directx11 (foler)
- libs (folder)
- imgui_examples.sln (file)

Step 4: launch the imgui_examples.sln file, ignore the popup telling 99% of the example disappear magically and start the project by pressing F5

---------------
The goal: Once you got the blue window with the 2 test gui inside it, the goal is to get the 2 gui (or at least 1 of them) without having the blue background window, be sure you can move your gui(s) everywhere on your desktop.

**Comment by ocornut** [comment]
Hello,

Please note that the area you are trying to remove is not created nor maintained by dear imgui.

This is the same as #3680. 
It's not currently supported, I suppose it eventually will be.
My main problem with this feature is that it'll attract a lots more users coming from a making-desktop-app background (rather than in-game/engine overlay background) and I'm not looking forward to the support requests, especially since multi-viewports support has too many subtle issues and more people reporting issues than putting work into fixing things. So I wouldn't be in a hurry trying to cover the "no user-created main viewport" case.
