### ISSUE TITLE
Small error in TreeNodeBehavior

### ISSUE THREAD

**Issue by BobbyAnguelov** [ocornut/imgui#6549]
Tiny typo on line 6257 (in docking branch) dealing with the rendering of leaf text without a bullet in a framed item does not take the padding into account:

```c++
else // Leaf without bullet, left-adjusted text
    text_pos.x -= text_offset_x;
``` 

should probably read:

```c++
else // Leaf without bullet, left-adjusted text
    text_pos.x -= text_offset_x - padding.x;
``` 

This would be consistent with all the other rendering positions in that function

**Comment by ocornut** [comment]
Right, I pushed the change as 0a53b45.

Out of curiosity did you notice this because have WindowPadding.x == 0?
`CollapsingHeader()` have this legacy-ish behavior where they extend themselves by WindowPadding.x*0.5f on left and right side. So normally you would see this padding and under default settings it looks ok.

I'm however considering to make changes to this (see #3312, #6170) which should involve removing the code that pads InnerClipRect, and maybe alter the code in TreeNodeBehavior() to use another source for the outer-padding value.

**Comment by BobbyAnguelov** [comment]
I actually had window padding set to 8, but noticed that the "header" text was not respecting the frame padding and was stuck to the left edge of the header frame. It was for a custom widget using the TreeViewEx functions so maybe that's the difference?
