### ISSUE TITLE
Cannot plot more than 16274 values with ImPlot

### ISSUE THREAD

**Issue by DanielMartensson** [ocornut/imgui#6563]
When I plot more than 16274 values with ImPlot, it causes trouble.
When I uncomment this one

```
//---- Use 32-bit vertex indices (default is 16-bit) is one way to allow large meshes with more than 64K vertices.
// Your renderer backend will need to support it (most example renderer backends support both 16/32-bit indices).
// Another way to allow large meshes while keeping 16-bit indices is to handle ImDrawCmd::VtxOffset in your renderer.
// Read about ImGuiBackendFlags_RendererHasVtxOffset for details.
//#define ImDrawIdx unsigned int
```
It's working for me.

**Question**
So my question is, if it is a bug in ImGui or ImPlot? I mean, 16274 is not the maximum 16-bit value.

**How to reproduce this issue:**

1. Head over to [GoobySoft](https://github.com/DanielMartensson/GoobySoft) and download the repository
2. Compile or just run the 64-bit binaries. Compile with the `Release` mode. `Debug mode` will only halt the program.
3. Go to File -> Select File -> Select `GoobySoft/Logfiles/test2.csv`
4. Go to Measurement -> View measurement and press `Load file`
5. Tune in the numbers as this

![image](https://github.com/ocornut/imgui/assets/28505229/e5dddd3b-6d0a-4559-a19f-0d850f3d6417)

6. Increase this number and see what's happening with the plot
![image](https://github.com/ocornut/imgui/assets/28505229/cad8f042-9653-4c44-851c-99fb43eb6d93)

**The code**

The code is quite simple. Inside `ViewMeasurements.cpp` you can find the process how I plot.

```cpp
static void addMeasurementPlot(const char titleId[], bool selectedColumns[], std::vector<std::string>& columnNames, size_t from, size_t to, size_t withStep) {
	if (ImPlot::BeginPlot(titleId)) {
		for (size_t i = 0; i < columnCount; i++) {
			if (selectedColumns[i]) {
				// Get column data
				std::vector<float> column = doc.GetColumn<float>(columnNames.at(i));

				// Cut yData between from and to with step
				std::vector<float> yData;
				std::vector<float> xData;
				size_t j;
				for ( j = from - 1; j < to; j += withStep) {
					yData.emplace_back(column.at(j));
					xData.emplace_back(((float)j) + 1.0f);
				}

				// Plot
				int s = yData.size();
				ImPlot::PlotLine(columnNames.at(i).c_str(), xData.data(), yData.data(), s);

			}
		}
		ImPlot::EndPlot();
	}
}
```

**Comment by inobelar** [comment]
@DanielMartensson Its not and `Dear ImGui` issue, but [implot](https://github.com/epezent/implot/tree/master)-related.

I **dont** tried to build & run your program, so I can't tell what exactly is your problem, but your issue is similar to something what I found few years ago: https://github.com/epezent/implot/issues/228 (after that issue was added [exremely important note](https://github.com/epezent/implot#extremely-important-note) about indexes type).

According to what you wrote, you found that cannot draw huge dataset, when `ImDrawIdx` is default (16-bit), and problems are solved when you use 32-bit indexing, but you still wandering about `16274` number :) 

That may be, because some widgets drawn before your plot, next you draw chart with 16274 points, and after it - rest of the widgets, popups, etc; and all of widgets needs free indexes to draw. You may check, that this value (16274) is **not constant**, simply by opening 'ImPlot Demo' window, and in it open sections with complex plots - drawing of such heavy things in case of 16-bit indexing may leave even less 'free indexes' for your plots. I hope my assumptions are correct :)

<details>
  <summary>P.S.</summary>
  
  **P.S.**: Next (after switching into non-16-bit indexes), if you found, that `ImPlot::PlotLine` have restriction too (`int` as cout, not `size_t`):
```cpp
IMPLOT_TMP void PlotLine(const char* label_id, const T* values, int count, double xscale=1, double xstart=0, ImPlotLineFlags flags=0, int offset=0, int stride=sizeof(T));
IMPLOT_TMP void PlotLine(const char* label_id, const T* xs, const T* ys, int count, ImPlotLineFlags flags=0, int offset=0, int stride=sizeof(T));
IMPLOT_API void PlotLineG(const char* label_id, ImPlotGetter getter, void* data, int count, ImPlotLineFlags flags=0);
```
and even in [`PlotLineEx`](https://github.com/epezent/implot/blob/cc5e1daa5c7f2335a9460ae79c829011dc5cef2d/implot_items.cpp#L1565-L1622) used [`Fitter1`](https://github.com/epezent/implot/blob/cc5e1daa5c7f2335a9460ae79c829011dc5cef2d/implot_items.cpp#L651-L662), that uses inside `for(int i = 0, ...)` `int`-based loop (not `size_t`), you found, that for really-huge complex drawing you need something custom like function from [PlotCandleStick](https://github.com/epezent/implot/blob/cc5e1daa5c7f2335a9460ae79c829011dc5cef2d/implot_demo.cpp#L2389-L2448C2) demo, that uses raw ImPlot::DrawList.
  
</details>

**Comment by ocornut** [comment]
Looking at the chart type you used each data point would draw a rectangle and therefore use 4 vertices. So that’s normal.

Note that nowadays your rendering backend should also support VtxOffset but I don’t know how ImPlot behave with it.

I may be tempted in the future to make 32-bits index the default.

**Comment by DanielMartensson** [comment]
> Looking at the chart type you used each data point would draw a rectangle and therefore use 4 vertices. So that’s normal.
> 
> Note that nowadays your rendering backend should also support VtxOffset but I don’t know how ImPlot behave with it.
> 
> I may be tempted in the future to make 32-bits index the default.

Thank you. I will enable the 32-bit index.
ImPlot is a really good library! 

I have some other issues with ImPlot too. If the plot stay constant for a few 30 minutes, then the whole application will freeze and the graphics will run very slow. I don't know why this is happening. But it as to do with the `ViewMeasurements.cpp`
