### ISSUE TITLE
Vertical scrollbar glitch

### ISSUE THREAD

**Issue by cosmy1** [ocornut/imgui#660]
Hello,

I'm facing an issue with the vertical scrollbar using mouse wheel.
![prova](https://cloud.githubusercontent.com/assets/1329119/15274477/b41a33b2-1ab2-11e6-84c0-3a2d3dcd827b.gif)

I checked the value passed to ```SetWindowScrollY(...)``` and doesn't have decimals.

I don't know if this is relevant but I'm using ```ImGuiListClipper```

**Comment by ocornut** [comment]
It's probably related to your use of ImGuiListClipper. Could you post your code?
You can first try to remove it and loop through all items to compare.

**Comment by cosmy1** [comment]
```cpp
    ImGuiListClipper clipper(rows.Size(), ImGui::GetTextLineHeight());
    ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(4.0f, 2.0f));

    for (int i = clipper.DisplayStart; i < clipper.DisplayEnd; ++i)
        ImGui::TextUnformatted(rows[i].second_.CString());

    clipper.End();
    ImGui::PopStyleVar();
    ImGui::EndChild();
```

Without works.

**Comment by ocornut** [comment]
You should replace
-- GetTextLineHeight
++ GetTextLineHeightWithSpacing
And move the PushStyleVar above the clipper code so that the value is correct.

This pattern is quite error prone indeed. May look in a way to rework it where item 0 would always be submitted by the user and then item height inferred from that.

**Comment by cosmy1** [comment]
Seems to work now, thank you!
Closing this :smiley:
