### ISSUE TITLE
Changing window name results in erroneous GetContentregionAvail() evaluation

### ISSUE THREAD

**Issue by LightShade12** [ocornut/imgui#6600]
Version/Branch of Dear ImGui:
Version: 1.89.7 WIP (18967)
Branch: docking

Back-end/Renderer/Compiler/OS:
Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Operating System: Windows 10

My Issue/Question:
Changing Window name results in erroneous GetContentregionAvail() evaluation:
Case 1: A very specific window name that was created very early on:
```
        ImGui::Begin("Viewport");
	m_viewportWidth = ImGui::GetContentRegionAvail().x;
	m_viewportHeight = ImGui::GetContentRegionAvail().y - 22;
	std::cerr << m_viewportWidth << " x " << m_viewportHeight<<"\n";
```
results in:
![image](https://github.com/ocornut/imgui/assets/102753608/5da8d413-0eb7-48a0-baa3-7161460900c8)
Case2: An arbitrary window name:
```
         ImGui::Begin("erViewport");
	m_viewportWidth = ImGui::GetContentRegionAvail().x;
	m_viewportHeight = ImGui::GetContentRegionAvail().y - 22;
	std::cerr << m_viewportWidth << " x " << m_viewportHeight<<"\n";
```
results in:
![image](https://github.com/ocornut/imgui/assets/102753608/df391561-7b58-4dd7-97e9-42e6f2cfc5d8)
(rest of code is untouched except for the windowname)
consequently causing a bad_memory_alloc error when i pass the dimensions to framebuffer vector resizing(possibly unrelated to the problem):
![image](https://github.com/ocornut/imgui/assets/102753608/2a544ffe-1d09-4602-b8a2-a6950884832f)

**Comment by PathogenDavid** [comment]
> ```cpp
> m_viewportHeight = ImGui::GetContentRegionAvail().y - 22;
> ```

You're [overflowing](https://en.wikipedia.org/wiki/Integer_overflow) the value of `m_ViewportHeight` when `GetContentRegionAvail().y` is less than 22.

(IE: The result of your calculation would be below 0. `m_ViewportHeight` appears to be a `uint32_t` which cannot represent negative numbers so it wraps around to the maximum value instead--that's why the number is so big.)

You should've gotten a warning similar to the following, so make sure you're paying attention to your build output.

```
warning C4244: 'initializing': conversion from 'float' to 'uint32_t', possible loss of data
```

> (rest of code is untouched except for the windowname)

The reason you didn't encounter this issue earlier is that by changing the window's name you also changed its ID.

Dear ImGui saves your window layout in `imgui.ini`. Chances are you resized the `Viewport` window at some point before you wrote this code, so it was tall enough it did not trigger your bug.

You can set `ImGuiIO::IniFilename` to `nullptr` to disable this feature. (I sometimes disable it during development to avoid issues like this.)

------

As an aside, if you ran into this because your window title is dynamic, you should establish a static ID with the `###ID` syntax. See [the FAQ entry on IDs](https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-about-the-id-stack-system) for details.

**Comment by ocornut** [comment]
Thanks David for the detailed and right answer!

If you need to store the avail content size consider using floats or ImVec2 which matches the way we store them and make them available.

**Comment by LightShade12** [comment]
> > ```c++
> > m_viewportHeight = ImGui::GetContentRegionAvail().y - 22;
> > ```
> 
> You're [overflowing](https://en.wikipedia.org/wiki/Integer_overflow) the value of `m_ViewportHeight` when `GetContentRegionAvail().y` is less than 22.
> 
> (IE: The result of your calculation would be below 0. `m_ViewportHeight` appears to be a `uint32_t` which cannot represent negative numbers so it wraps around to the maximum value instead--that's why the number is so big.)
> 
> You should've gotten a warning similar to the following, so make sure you're paying attention to your build output.
> 
> ```
> warning C4244: 'initializing': conversion from 'float' to 'uint32_t', possible loss of data
> ```
> 
> (If you want to force yourself to pay attention to warnings, consider enabling [treat warnings as errors](https://learn.microsoft.com/en-us/cpp/build/reference/compiler-option-warning-level?view=msvc-170#to-set-the-compiler-options-in-the-visual-studio-development-environment).)
> 
> > (rest of code is untouched except for the windowname)
> 
> The reason you didn't encounter this issue earlier is that by changing the window's name you also changed its ID.
> 
> Dear ImGui saves your window layout in `imgui.ini`. Chances are you resized the `Viewport` window at some point before you wrote this code, so it was tall enough it did not trigger your bug.
> 
> You can set `ImGuiIO::IniFilename` to `nullptr` to disable this feature. (I sometimes disable it during development to avoid issues like this.)
> 
> As an aside, if you ran into this because your window title is dynamic, you should establish a static ID with the `###ID` syntax. See [the FAQ entry on IDs](https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-about-the-id-stack-system) for details.

Thank you so much David! I tweaked it a bit and now it works:
`m_viewportHeight = ImGui::GetContentRegionAvail().y - ((ImGui::GetContentRegionAvail().y < 22) ? 0 : 22);`
