### ISSUE TITLE
The AllowItemOverlap is not behaving as expected.

### ISSUE THREAD

**Issue by cr545l** [ocornut/imgui#6613]
**Version/Branch of Dear ImGui:**

v1.89.6
Branch : docking 6b011140576d5b7f94a6716235fc287ffb34ae34

**Back-end/Renderer/Compiler/OS**

Custom

**Issuee**

I have added an X button on top of ImGui::InputText, following the instructions provided in [this issue](https://github.com/ocornut/imgui/issues/3149#issuecomment-617687033), but the button click is not working.

``` cpp
static char buf[512] = {0,};
ImGui::InputText("###text", buf, 512l, ImGuiButtonFlags_AllowItemOverlap);

ImGui::SetItemAllowOverlap();
auto min = ImGui::GetItemRectMin();
auto max = ImGui::GetItemRectMax();
float x = max.x - ImGui::GetFontSize() - ImGui::GetStyle().FramePadding.x * 2;

const auto buttonId = ImGui::GetID("button");
const bool clicked = ImGui::CloseButton(buttonId, ImVec2(x, min.y));
if (clicked) // ← NOT WORK
{
	ImGui::SetActiveID(buttonId, ImGui::GetCurrentWindow());
	strcpy(buf, "");
}
if (ImGui::IsItemHovered() && ImGui::IsMouseClicked(ImGuiMouseButton_Left)) // ← WORK
{
	ImGui::SetActiveID(buttonId, ImGui::GetCurrentWindow());
	strcpy(buf, ""); 
}
```

Although manually checking IsItemHovered and IsMouseClicked can make it work, is it the best approach?

**Comment by ocornut** [comment]
Hello,
We made a large series of changes in 1.89.7 exactly related to this, and while I thought I had tagged and updated all relevant issue it looks like I missed #3149.

See this release note:
https://github.com/ocornut/imgui/releases/tag/v1.89.7

TL;DR;
- This way of using `SetItemAllowOverlap()` (without imgui_internal.h) use has been broken since 1.89.0
- In 1.89.7 we introduced `SetNextItemAllowOverlap()` which is to be called BEFORE the item and it should work.

I will also update the issue you linked to.
