### ISSUE TITLE
Registry specification file

### ISSUE THREAD

**Issue by tiawl** [ocornut/imgui#6615]
Hi,

I am currently writing an Imgui binding generator for Zig programing language based on the cimgui/cimgui generator. Because I am stucked in an incomfortable situation I rencently opened [this issue](https://github.com/cimgui/cimgui/issues/246). However the cimgui/cimgui maintainer is not enthusiastic about a potential evolution of its tool if it is involving too much work without real advantage for its own usage (it is an understandable point of view).

My first intent was not to make an ambitious feature request here. But writing a binding to Imgui is not comfortable when using a modern programing language.

Currently binding developers have 2 options when starting their development:
- Relying on the cimgui/cimgui repository.
- Parsing your C++ header files to search needed data,

However these solutions are not the best. As a binding developer I prefer:
1. not depending on the cimgui/cimgui repository. Even if:
  - its tool is a robust C interface to the Imgui API for most of programing languages,
  - the maintainer is available and ready to answer,
  
&emsp; The main problems with its solution are:
  - its goal is to share its generator without making too much evolution. Its goal does not match with binding developers needs: we need a specification whatever the programing language we decided to use to write an accurate interface to Imgui. So this specification needs to evolve when needed.
  - it provides a C specification. C specifications are limited for modern programing languages (see the mentioned issue for an example of those limitations),
2. not parse your header files to search data because, again, we will depend on a C/C++ specification.

Because none of these solutions satisfies my needs, I come here with a third one:
Would you consider to provide a registry file on this repository for your API ?

The main advantages of the implementation of this new file would be:
- no dependency to another tool to write a binding: we will only depend on this repository and the registry file inside to build a binding,
- a specification not based on the C/C++ programing languages:
  - a better quality code for current bindings,
  - a generic and accurate specification that can be used by modern (and older) programing languages,

As a suggestion, you can look at the [Vulkan registry XML file](https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/main/xml/vk.xml) which provides an accurate specification.

Thank you for reading.

**Comment by ocornut** [comment]
Have you looked at our project Dear Bindings ?
https://github.com/dearimgui/dear_bindings

I think it provide enough metadata output to generate a registry file and/or any bidding, and if it would be great if you worked on improving Dear Bindings for that purpose.

**Comment by tiawl** [comment]
Wow. That is what I was searching: thank you. Sorry to bother you with this issue because I did not searched correctly. I close this one and I will open a new one to the mentioned repository if something is missing for the binding I am working on.

**Comment by ocornut** [comment]
The overarching answer is: I likely don't have the bandwidth to maintain such specifications/registry because at core it means thinking from the POV of a wider variety of languages and thinking of forward/backward compatibility in an even more abstract manner. But if people wanted to maintain it I wouldn't mind of course.

However I argue that both cimgui and dear_bindings are aiming to solve the same problem, as their aim is to generate the metadata making that registry generation possible. Assuming that parsing works and is maintained your problem is equally solved.

cimgui already generates a .json file. The reason we started creating dear_bindings is that I also felt cimgui became stagnant in the quality of its output. Lack of comments, seemingly no interest to separate cimgui.h and cimgui_internal.h (right now it's all in the same file) which to be was essential etc. So I asked my friend Ben to try building an alternative.  But cimgui did provide a great service to many people for a long time, and it might keep evolving, otherwise dear_bindings will aim to fill its gaps.
