### ISSUE TITLE
PushFont/PopFont mismatch only in debug configuration

### ISSUE THREAD

**Issue by Lester702** [ocornut/imgui#6617]
ImGui Version: 1.82 master (I'm aware this needs to be updated)
**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_sdl.cpp
Compiler: Visual Studio 2022
Operating System: Win 10

**My Issue/Question:**
I've been working on a game for awhile now and I just moved over to a new computer and a fresh install of Windows and when I compiled my project and ran it for the first time I was met with this
![image](https://github.com/ocornut/imgui/assets/63370028/22e0f4aa-7675-4a63-8aab-73ac4d6317ff)
When I switch to build for release instead of debug everything works as it should

When debugging the issue the breakpoint is at line 7252 in imgui.cpp which is a PushFont/PopFont mismatch

I'm confused as to what could cause this since everything works as expected in a release configuration. 
I also wanted to clarify that this is for a game that I'm developing myself. I know last time I needed help I was banned for trying to ask for help with a cheat. Totally understandable, but I just wanted to clarify this time

**Comment by ocornut** [comment]
While there could be many reasons, a different behavior between Debug and Release build is often attributed to difference in stack data initialization.

In particular, could be that you have uninitialized variables somewhere in your code.
On typical debug settings with Visual Studio, every uninitialized data will be cleared with a fixed non-zero pattern (eg all bytes being 0xCC) everytime, while in a Release build previous left-over data may be reused and it’s more likely to be 0x00.

I would assume this is a bug in your code and use a debugger to understand why you are not calling PushFont/PopFont correctly. Note this specific set currently needs to be called in same function.

**Comment by GamingMinds-DanielC** [comment]
Also never forget what assertions are. They are macros that get expanded to expression checking and error reporting code in debug builds and to no-ops in release builds. Assertions cannot trigger in release builds because the preprocessor effectively removes them from the code as one of the early build steps. Not every error results in a crash, so it can still be there while just seeming to work properly.

Errors that happen only in debug builds are possible, but far less likely than errors that only get caught in debug builds.

**Comment by PathogenDavid** [comment]
Omar and Daniel beat me and provided their own good advice. I'm awake in the middle of the night unable to sleep and I'm in a "teach a person to fish" sort of mood so here's my different/more detailed response.

I know it's long. Read all of it, it'll make you a better developer.

> I also wanted to clarify that this is for a game that I'm developing myself. I know last time I needed help I was banned for trying to ask for help with a cheat. Totally understandable, but I just wanted to clarify this time

Looking at your older issues, I think the main problem here is that you have a tendency to reach out for help too quickly without investigating issues yourself.

Reaching out for help is a good thing, but it's important to find a balance between it and investigating things yourself.

So let's focus on how you might've investigated this further yourself.

(This mini guide will assume you're using MSVC and Visual Studio since...well, that's what it looks like you're using. But everything here applies to using other toolchains/runtimes/debuggers too.)

----------------------

## Why the assert doesn't fail in release builds

> When I switch to build for release instead of debug everything works as it should

An important thing to know here is that by default in MSVC projects, `NDEBUG` is defined in release builds. `NDEBUG` disables asserts entirely.

This is good from a performance perspective, but it means your mistakes are potentially being ignored.

Your code probably isn't "working", it's just wrong in a way that isn't causing it to crash or corrupt state in an immediately obvious way.

Let's assume you didn't already know this though, how might you have found this out?

Your first hint was the wording in the assert dialog "Debug Error!". (*Technically* asserts can happen in non-debug builds too, but as mentioned earlier that's the default behavior.)

Let's assume though that you didn't take that at face value.

The MSVC runtime gave you three options:

* `Abort`: Ends your program immediately
* `Retry`: As stated at the end of the message, will pause your game in the debugger.
* `Ignore`: Somewhat unintuitively this also ends your program immediately. (This is a quirk of how asserts are implemtned by the runtime. If your app wasn't a command line app it will actually ignore the assert and keep going, but it'd generally just fail the assert again on the next frame.)

Out of those options, only `Retry` does anything useful, so let's click that!

This will bring you to [`ImGuiStackSizes::CompareWithContextState`](https://github.com/ocornut/imgui/blob/e5977f05d832a6b2381ef682b0e961a5a697a127/imgui.cpp#L9370-L9391) in your debugger, which you'll find is just a big collection of asserts.

In C/C++ asserts are typically used for two things: 1) To detect and report invalid API usage. 2) To verify some assumption about the state is correct. (These are sort-of the same thing but the difference lies with who's fault it is when the assert fails. Failed asserts for 1 are your fault, failed asserts for 2 are Omar's fault.)

(In languages other than C/C++, asserts tend to only be used for the second category. In languages that have them, exceptions tend to be used for the first category instead.)

Dear ImGui is used by a lot of people, so you can usually assume failed asserts are going to be in the first category.

Indeed, this function is described to "detect usage errors", which tells us its whole purpose is to collect category 1 asserts.

---------------

## How was I supposed to know that?

Let's assume we aren't super familiar with asserts in C/C++. What *is* `IM_ASSERT`, anyway? Let's check!

If you right-click on `IM_ASSERT` and choose `Go to Definition` you'll find that it is [defined in `imgui.h`](https://github.com/ocornut/imgui/blob/e5977f05d832a6b2381ef682b0e961a5a697a127/imgui.h#L86) simply as an alias to the `assert` macro from the C runtime library.

Let's assume you don't know what `assert` actually is so you look it up. Whether you find it in [the Microsoft Documentation](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/assert-macro-assert-wassert), [Wikipedia](https://en.wikipedia.org/wiki/Assert.h), [cppreference.com](https://en.cppreference.com/w/cpp/error/assert), or [man pages](https://manpages.ubuntu.com/manpages/jammy/en/man3/assert.3.html) you'll find they all tell you something along the lines of:

> Assertion checks can be turned off at compile time by defining the macro `NDEBUG`.

(And as Daniel and I both alluded to, `NDEBUG` is typically defined by default for release builds.)

Of course like most programmers we have trust issues. So we use `Go to Definition` again on `assert` its self and are greeted with its definition:

```
#ifdef NDEBUG

    #define assert(expression) ((void)0)

#else

    _ACRTIMP void __cdecl _wassert(
        _In_z_ wchar_t const* _Message,
        _In_z_ wchar_t const* _File,
        _In_   unsigned       _Line
        );

    #define assert(expression) (void)(                                                       \
            (!!(expression)) ||                                                              \
            (_wassert(_CRT_WIDE(#expression), _CRT_WIDE(__FILE__), (unsigned)(__LINE__)), 0) \
        )

#endif
```

They say seeing is believing, and I do believe I see that `assert` is disabled when `NDEBUG` is defined.

---------------

## OK, but what about *this* failed assert?

Of course that little tangent doesn't get us any closer to solving our problem.

What even was our problem, anyway? Dear ImGui thankfully tells us!

> ```
> PushFont/PopFont Mismatch!
> ```

Since we're using them, we probably already know about `PushFont`/`PopFont`.

When we were originally implementing our custom font loading we most likely read the [helpful note about `PushFont`/PopFont`](https://github.com/ocornut/imgui/blob/e5977f05d832a6b2381ef682b0e961a5a697a127/examples/example_glfw_opengl3/main.cpp#L86) found in the example app:

> ```cpp
> // [...] You can also load multiple fonts and use ImGui::PushFont()/PopFont() to select them.
> ```

Or maybe we [read the fonts documentation](https://github.com/ocornut/imgui/blob/e5977f05d832a6b2381ef682b0e961a5a697a127/docs/FONTS.md#fonts-loading-instructions) which gives a specific example of using `PushFont`/`PopFont`:

```cpp
// In application loop: select font at runtime
ImGui::Text("Hello"); // use the default font (which is the first loaded font)
ImGui::PushFont(font2);
ImGui::Text("Hello with another font");
ImGui::PopFont();
```

Or you found [that FAQ entry on fonts which mentions the API](https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-load-multiple-fonts).

Or maybe we saw [`PushFont`/`PopFont` are defined alongside many other `Push*`/`Pop*` functions](https://github.com/ocornut/imgui/blob/e5977f05d832a6b2381ef682b0e961a5a697a127/imgui.h#L403-L415), and even though the demo doesn't have a specific example for fonts we've seen [specific examples](https://github.com/ocornut/imgui/blob/e5977f05d832a6b2381ef682b0e961a5a697a127/imgui_demo.cpp#L600-L604) for other push/pop functions as we're familiar with push/pop idiom that Dear ImGui uses pervasively.

Or maybe we searched closed GitHub issues for `PushFont` and read [this issue mentioning the API](https://github.com/ocornut/imgui/issues/6547) which shows us that other developers are calling `PushFont` *and* `PopFont` (giving us a hint to its intended usage.)

So in short: We should know already that for every call to `PushFont` we must also have a matching call to `PopFont`.

If you *didn't* know that already, you should at least have gotten the hint that `PushFont`/`PopFont` is related to your problem. So you should realize you don't understand these APIs like you thought you did. This should lead you to specifically investigate them and you should've been able to find one of the above resources.

-----------------

## Finding the mismatched `PushFont`/`PopFont`

OK, so now we know our usage of `PushFont` and/or `PopFont` is likely our problem. An obvious step now is simply to search our entire codebase for uses of these APIs. You might go to them in `imgui.h`, right-click them, and choose `Find All References` or maybe you'll just <kbd>Ctrl+Shift+F</kbd> for `PushFont` and `PopFont`. Then from there go through each usage one by one and make sure you're using them correctly.

Oh, but we're also currently stopped in the debugger. Maybe it can help?

If you look at the call stack window (go to Debug > Windows > Call Stack if you accidentally closed it) you'll see a list of functions that led up to the assert failure you're currently debugging.

```
[ 0] ucrtbased.dll!00007ffab1a22e65()
[ 1] ucrtbased.dll!00007ffab1a23003()
[ 2] ucrtbased.dll!00007ffab1a3ab0d()
[ 3] ucrtbased.dll!00007ffab1a41025()
[ 4] ucrtbased.dll!00007ffab1a408b7()
[ 5] ucrtbased.dll!00007ffab1a3e8a8()
[ 6] ucrtbased.dll!00007ffab1a4158f()
[ 7] example_glfw_opengl3.exe!ImGuiStackSizes::CompareWithContextState(ImGuiContext * ctx) Line 9381
[ 8] example_glfw_opengl3.exe!ImGui::End() Line 6935
[ 9] example_glfw_opengl3.exe!MyCoolWindow() Line 43
[10] example_glfw_opengl3.exe!main(int __formal, char * * __formal) Line 168
...everything below main is runtime and operating system internals...
```

The stack window is ordered from most recently called at the top to least recently called.

In this case we have functions [0] - [6] show some nonsense like `ucrtbased.dll!00007fc0ffeeee3226()`. That's Visual Studio saying "a function in `ucrtbased.dll` was called but I don't know what it's named". In this situation they're internal functions related to asserts failing.

Since these are runtime internals we can just skip them.

<details>
<summary>How do you know they're internals related to asserts failing?</summary>
`ucrtbased.dll` is the main DLL for the Universal C Runtime (which comes up when you search it.) Knowing that we can make a reasonable educated guess that's what we're looking at.

It's not important for this example, but in some situations you right-click these entries and click `Load Symbols` to get their names. You might need to [enable the Microsoft Symbol Servers](https://learn.microsoft.com/en-us/visualstudio/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger?view=vs-2022#configure-location-of-symbol-files-and-loading-options))

Done in this situation, you'll see the names are all assert-failure-related-things:

```
[ 0] ucrtbased.dll!issue_debug_notification(const wchar_t * const message) Line 28
[ 1] ucrtbased.dll!__acrt_report_runtime_error(const wchar_t * message) Line 154
[ 2] ucrtbased.dll!abort() Line 61
[ 3] ucrtbased.dll!common_assert_to_stderr_direct(const wchar_t * const expression, const wchar_t * const file_name, const unsigned int line_number) Line 161
[ 4] ucrtbased.dll!common_assert_to_stderr<wchar_t>(const wchar_t * const expression, const wchar_t * const file_name, const unsigned int line_number) Line 179
[ 5] ucrtbased.dll!common_assert<wchar_t>(const wchar_t * const expression, const wchar_t * const file_name, const unsigned int line_number, void * const return_address) Line 420
[ 6] ucrtbased.dll!_wassert(const wchar_t * expression, const wchar_t * file_name, unsigned int line_number) Line 444
```
</details>

Lines [7] - [8] are Dear ImGui code. Since we're investigating *our* code we can just skip them.

That leaves us with [9] and [10]. It's best to start with our code which called the Dear ImGui function which failed. IE: Our function nearest to the top of the stack, `[9] MyCoolWindow()`.

Like most libraries, Dear Imgui asserts as soon as it notices the discrepency. In this case it notices at the end of your window.

That means the window being ended in `MyCoolWindow` is likely our culprit, so if we're lucky it'll be as simple as reading it and noticing the missing `PopFont`:

```cpp
void MyCoolWindow()
{
    // Buggy example for GH-6617
    ImGui::Begin("Test window");
    ImGui::PushFont(g_ComicSans);
    ImGui::Text("Hello, world!");
    ImGui::End();
}
```

Using the debugger, we were able to instantly find our missing `PopFont`!

--------------------

## But wait, I ended up at my call to `Render`‽

There's a chance your call stack looks more like this instead:

```
...assert internals skipped...
[0] ucrtbased.dll!_wassert(const wchar_t * expression, const wchar_t * file_name, unsigned int line_number) Line 444
[1] example_glfw_opengl3.exe!ImGuiStackSizes::CompareWithContextState(ImGuiContext * ctx) Line 9381
[2] example_glfw_opengl3.exe!ImGui::End() Line 6935
[3] example_glfw_opengl3.exe!ImGui::EndFrame() Line 5010
[4] example_glfw_opengl3.exe!ImGui::Render() Line 5074
[5] example_glfw_opengl3.exe!main(int __formal, char * * __formal) Line 185
...runtime and Windows internals skipped...
```

This is admittedly a more confusing situation. Dear ImGui didn't complain until the end of the frame!

I can tell you from experience that this means you called `PushFont` outside of a window (IE: outside of a `Begin..End` block), but I do admit it'd be hard to see that's what's happening if you didn't already know.

(The short version is that `ImGui::End` call at [2] is the `End` for the default window. You've maybe seen it if you ever tried to submit a widget without calling `ImGui::Begin` first.)

In this situation you'd likely fall back to auditing your `PushFont`/`PopFont` calls manually.

There's some more advanced debugging strategies you might use here instead, but this ramble has gone on long enough as it is and they're too dependent on the architecture or your app anyway. I *strongly* recommend making a habit of exploring the features of your debugger (whether it be Visual Studio or some other tool you move to in the future.) Even when the situation doesn't necessarily call for it, it's helpful to have familiarity with the tools availble to you when the time comes.

If you want an idea of something you could do though:

* Place a breakpoint in the implementations of `ImGui::Begin`, `PushFont`, `PopFont`, and `End` (click in the left-most margin of the code editor or go to Debug > Toggle Breakpoint. Breakpoints are shown as red circles.)
* Run your app through Visual Studio (IE: Debug > Start Debugging)
* As you step through the calls to the above functions, note which window you're in and what your font stack looks like (I personally write this on a literal piece of apper)

In doing this, you should likely find your issue. You'll either find a `PushFont` after a `Begin` that has no `PopFont` before `End` or you'll find a random `PushFont` that isn't inside a window.

This strategy is more useful over manually auditing `PushFont`/`PopFont` in cases where you have a lot of boilerplate or abstractions. (EG: Maybe you have a class which abstracts windows or helpers for font management.)

-------------------------

## Why didn't I have this problem on my old computer?

> I've been working on a game for awhile now and I just moved over to a new computer and a fresh install of Windows and when I compiled my project and ran it for the first time I was met with this

This is almost certainly a red herring. You either forgot you had unfinished code on your old computer so it didn't work on the new computer, or maybe you had been using the `Release` configuration on your old computer and never noticed.

-------------------------

## Why did you write all this?

It was either this or baking bread at 4 AM and this seemed healthier.

**Comment by Lester702** [comment]
> ## Why did you write all this?
> It was either this or baking bread at 4 AM and this seemed healthier.

I appreciate the very detailed guide for debugging and hunting for my issue. Will definitely reference this when debugging in the future

**Comment by Lester702** [comment]
Closed
