### ISSUE TITLE
Custom Font is loading as white rectangle

### ISSUE THREAD

**Issue by luis605** [ocornut/imgui#6632]
**Version/Branch of Dear ImGui:**

Version: 1.89.2
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: rlImGui
Compiler: g++
Operating System: Linux Mint 21.1 Vera

**My Issue/Question:**

I decided to change dear imgui default font to Poppins Regular as follow:
```cpp
    ImFontConfig fontConfig;
    fontConfig.FontDataOwnedByAtlas = false;

    std::string fontPath = GetWorkingDirectory();
    fontPath += "/assets/fonts/Poppins-Regular.ttf";
    std::cout << fontPath << std::endl;

    ImFont* robotoFont = io.Fonts->AddFontFromFileTTF(fontPath.c_str(), 20.0f, &fontConfig);
    io.FontDefault = robotoFont;
    io.Fonts->Build();
````

The font is added without any error or warning, but in the dear imgui window, every character is represented by a white rectangle. The screenshot below shows my current issue.

**Screenshots/Video**

![imagem](https://github.com/ocornut/imgui/assets/60551627/511843bd-fc93-492b-8e11-5838c926a232)

**Standalone, minimal, complete and verifiable example:**
```cpp
#include "include/raylib.h"

#include "imgui/imgui.h"
#include "imgui/imgui_internal.h"
#include "include/rlImGui.h"

#include <string>
#include <iostream>

using namespace std;


int main() {
    InitWindow(500, 500, "Example");

    // ImGui
    rlImGuiSetup(true);

    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO();

    ImFontConfig fontConfig;
    fontConfig.FontDataOwnedByAtlas = false;

    std::string fontPath = GetWorkingDirectory();
    fontPath += "/assets/fonts/Poppins-Regular.ttf";
    std::cout << fontPath << std::endl;

    ImFont* robotoFont = io.Fonts->AddFontFromFileTTF(fontPath.c_str(), 20.0f, &fontConfig);
    io.FontDefault = robotoFont;
    io.Fonts->Build();


    while (!WindowShouldClose()) {
        BeginDrawing();

            ClearBackground(DARKGRAY);

            rlImGuiBegin();

            ImGui::Begin("Test");
            ImGui::Text("Hello, world!");
            ImGui::End();

            rlImGuiEnd();

        EndDrawing();
    }
}
```
Font Downloaded from here: https://fonts.google.com/specimen/Poppins

**Comment by sakiodre** [comment]
I'm unable to replicate this, both FreeType and TrueType, would you mind showing the font atlas?

![image](https://github.com/ocornut/imgui/assets/136492105/c5b12f9f-c1cf-4761-ade4-ebd84eced1cb)

By the way, only set `FontDataOwnedByAtlas` to `false` if you load the font from memory.

**Comment by sakiodre** [comment]
I'm not familiar with `rlImGui` but looking at the code, maybe you need to call `rlImGuiReloadFonts` after `io.Fonts->Build();`

**Comment by luis605** [comment]
It was it, rlImGuiReloadFonts() fixed the issue. thank you @sakiodre !

**Comment by rfletchr** [comment]
> It was it, rlImGuiReloadFonts() fixed the issue. thank you [@sakiodre](https://github.com/sakiodre) !

also not that this fix only works if the default font has been set.

```cpp
    io.FontDefault = robotoFont;
```

**Comment by JeffM2501** [comment]
rlImGui has two APIs, the high level one and the low level one.
The high level API (the one that all starts with rl), is patterned after the raylib API and not the ImGui API and is very simple and does a lot of automatic things for you. It is not really setup to work with complex custom font setups.  rlImGuiSetup does all the setup and font upload for you in one shot. So yes if you change fonts when using that system you must force a reload, that's why `rlImGuiReloadFonts `exists.
If you want to use the high level API and insert custom fonts, you should use `rlImGuiBeginInitImGui/rlImGuiEndInitImGui` and insert your fonts there (see the AssetBrowser example).

the low level API, is patterned more after the traditional ImGui backend.

I do see that now that we have the ImGuiBackendData that it is easier to auto-upload the font if it's not set, and I can work on implementing that, but if you want a backend API that more closely matches the example backends, you for sure do not want to use the rlImGui high level API, use the low level one (see the imgui_style_example.cpp).

I'm also a little confused why a post here from 2023 was dredged up instead of simply creating an issue on the rlImGui's issue tracker.

**Comment by rfletchr** [comment]
> rlImGui has two APIs, the high level one and the low level one. The high level API (the one that all starts with rl), is patterned after the raylib API and not the ImGui API and is very simple and does a lot of automatic things for you. It is not really setup to work with complex custom font setups. `rlImGuiSetup` does all the setup and font upload for you in one shot. So yes if you change fonts when using that system you must force a reload, that's why `rlImGuiReloadFonts `exists. If you want to use the high level API and insert custom fonts, you should use `rlImGuiBeginInitImGui/rlImGuiEndInitImGui` and insert your fonts there (see the AssetBrowser example).
> 
> the low level API, is patterned more after the traditional ImGui backend.
> 
> I do see that now that we have the ImGuiBackendData that it is easier to auto-upload the font if it's not set, and I can work on implementing that, but if you want a backend API that more closely matches the example backends, you for sure do not want to use the rlImGui high level API, use the low level one (see the imgui_style_example.cpp).
> 
> I'm also a little confused why a post here from 2023 was dredged up instead of simply creating an issue on the rlImGui's issue tracker.

Hi Jeff, Firstly my apologies if I did something wrong, When trying to debug this issue for myself I found this issue was the top hit on google, and the I wanted to make sure the explanation was clearer for the next person to have the same issue.

Secondly thanks for the additional insight, I'd used the GLFW low level api before and it didn't *seem* to have the same Issue, I at mentioned you because I felt you might appreciate knowing something wasn't right. I've found sometimes that long standing issues can go unaddressed because people don't notify the author.

Again, if my procedure was wrong, or you took this as disrespectful I apologise.

**Comment by JeffM2501** [comment]
I have updated rlImGui to lazy load the fonts on NewFrame, so it will work more like the example backends you are used to, all the new platform features in ImGui make it much easier to do now than when rlImGui was first written.

I don't think you did anything wrong, just rlImGui does work differently than other ImGui backends. It is not a 'ImGui First' API, it's a "raylib first" API. It is not something that everyone is used to.
The primary API is designed to be super simple to use to get ImGui into a raylib app, you can do it with just 4 function calls, way less than a traditional ImGui backend that is shown in the examples. This is one reason why it is its own repository and not simply summited as an example to be included in ImGui. The high level API does a lot for you automatically.

The low level API was added to create a more ImGui-like backend API if that is more what you are used to, and it will now work just like the OpenGL3 one does with regards to font loading. This is the API to use for total control over the process. 

There is sill a font reload function, but that is mostly there to force a reload in the case where you add a font after startup.

**Comment by rfletchr** [comment]
> I have updated rlImGui to lazy load the fonts on NewFrame, so it will work more like the example backends you are used to, all the new platform features in ImGui make it much easier to do now than when rlImGui was first written.
> 
> I don't think you did anything wrong, just rlImGui does work differently than other ImGui backends. It is not a 'ImGui First' API, it's a "raylib first" API. It is not something that everyone is used to. The primary API is designed to be super simple to use to get ImGui into a raylib app, you can do it with just 4 function calls, way less than a traditional ImGui backend that is shown in the examples. This is one reason why it is its own repository and not simply summited as an example to be included in ImGui. The high level API does a lot for you automatically.
> 
> The low level API was added to create a more ImGui-like backend API if that is more what you are used to, and it will now work just like the OpenGL3 one does with regards to font loading. This is the API to use for total control over the process.
> 
> There is sill a font reload function, but that is mostly there to force a reload in the case where you add a font after startup.

That sounds fantastic. I know supporting opensource can be a tiring and thankless affair and I'm extremely grateful for your work, and that of Omar.

Cheers!

**Comment by ocornut** [comment]
I should clarify that the upcoming new font system #8465 works differently and fonts are more dynamic.

**Comment by JeffM2501** [comment]
> I should clarify that the upcoming new font system [#8465](https://github.com/ocornut/imgui/issues/8465) works differently and fonts are more dynamic.

![Image](https://github.com/user-attachments/assets/609da247-5fb1-4cb3-ba2f-e9178bdf137a)
