### ISSUE TITLE
Gradient filled rectangle not rounding

### ISSUE THREAD

**Issue by ElectroidDes** [ocornut/imgui#6652]
Imgui Version: 1.89.6

Using the following code to draw a rectangle with a gradient fill in the window:
```

    ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 60);
    ImGui::Begin("Window Rounding");

    ImVec2 top_left_corner = { ImGui::GetWindowPos().x , ImGui::GetWindowPos().y };
    ImVec2 lower_right_corner = { ImGui::GetWindowPos().x + ImGui::GetWindowSize().x, ImGui::GetWindowPos().y + ImGui::GetWindowSize().y };

    ImDrawList* draw_list = ImGui::GetWindowDrawList();    
    (*draw_list).AddRectFilledMultiColor(top_left_corner, lower_right_corner, IM_COL32(50, 100, 0, 255), IM_COL32(40, 255, 50, 255), IM_COL32(100, 0, 255, 255), IM_COL32(0, 0, 0, 0) );

    ImGui::End();
    ImGui::PopStyleVar();
```

As you can see, the top left and right corners and the bottom left corners round the corners correctly.
The lower right corner of the rectangle a gradient fill is not cut and it "climbs out".
Is this the correct behavior of Imgui ? Is that how it should be?

![Imgui_round](https://github.com/ocornut/imgui/assets/140515246/da264ea3-1cf9-4684-a114-a1377ddea617)

**Comment by GamingMinds-DanielC** [comment]
Your assumption that the bottom left corner is rounding correctly is wrong. You just can't see it since it is a transparent black (alpha 0), not a solid one.

So basically, your problem is that you have rather extreme rounding values and rectangular clipping can't accommodate this. Normally rounding is much smaller and a margin ensures that the content doesn't get into those rounded corners. Fixing this the way you want is out of the scope of ImGui, but you can accomplish this if you render into a texture with alpha channel and mask it yourself.

**Comment by ocornut** [comment]
It’s also that AddRectFilledMultiColor() doesn’t even support rounding. In the event your shape could fill the window without requiring clipping (which is always rectangular) you could use AddRectFilled() with rounding and white color + the ShadeVertsLinearColorGradientKeepAlpha() function.

See the code in https://github.com/ocornut/imgui/issues/4722

**Comment by ElectroidDes** [comment]
> It’s also that AddRectFilledMultiColor() doesn’t even support rounding. In the event your shape could fill the window without requiring clipping (which is always rectangular) you could use AddRectFilled() with rounding and white color + the ShadeVertsLinearColorGradientKeepAlpha() function.
> 
> See the code in #4722

Thank you very much! 
Function "ShadeVertsLinearColorGradientKeepAlpha" - works.
