### ISSUE TITLE
Overlapped InputText doesn't take the focus since 1.89.7

### ISSUE THREAD

**Issue by cpichard** [ocornut/imgui#6690]
**Version/Branch of Dear ImGui:**

Version: 1.89.8
Branch: master and docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp 
Operating System: macOS/Windows10

**My Issue/Question:**
Hi,

To edit a tree node value, I used to draw an input text on top of the tree node after double clicking on it. 

https://github.com/ocornut/imgui/assets/300243/043309fc-dd18-4a71-836e-754b6fd521bc

It has been working fine until 1.89.7. 
In 1.89.7 and beyond, the InputText doesn’t show up (just one frame)

https://github.com/ocornut/imgui/assets/300243/c5d2a0ca-470d-4f91-a328-a9216b18ec9a

A code example looks like this (this can be pasted in the imgui_demo.cpp) : 
```
                       auto cursor = ImGui::GetCursorPos();
			ImGui::SetNextItemAllowOverlap() ; // only in 1.89.7
                       ImGui::TreeNodeEx(node->Name, ImGuiTreeNodeFlags_AllowItemOverlap | ImGuiTreeNodeFlags_Leaf | ImGuiTreeNodeFlags_Bullet | ImGuiTreeNodeFlags_NoTreePushOnOpen | ImGuiTreeNodeFlags_OpenOnArrow | ImGuiTreeNodeFlags_SpanFullWidth);
                       if (!ImGui::IsItemToggledOpen() && ImGui::IsItemClicked()&& ImGui::IsMouseDoubleClicked(0)) {
                           edit = node->Name;
                       }
                       if (edit == node->Name) {
                          char stuff[96];
                          ImGui::SameLine();
                          ImGui::SetCursorPos(cursor);
                          ImGui::InputText("##EditStuff", stuff, 96);
                          if (ImGui::IsItemDeactivatedAfterEdit() || !ImGui::IsItemFocused()) {
                               edit = nullptr;
                           }
                       }   
```

I traced the difference to the !ImGui::IsItemFocused() above not behaving the same between 1.89.6 and 1.89.7. In 1.89.7. The InputText is not focused anymore when it is created. I was focused before because the click is “propagated” to the input text which normally takes the focus and allows editing.

After a bit of digging, inside the InputText, ItemHoverable returns false on the ActiveIdAllowOverlap test where it wasn’t in the previous versions.

https://github.com/ocornut/imgui/blob/d4ddc46e7773e9a9b68f965d007968f35ca4e09a/imgui.cpp#L4059

I am not sure if this is a bug, or if my code is incorrect in the first place.

As a workaround I tried removing ImGui::IsItemFocused() but then users have to click again on the InputText to start editing which is not great, the previous behaviour was really convenient, specially focusing on the InputText and start text editing.

Thanks a lot for any help,

Best

Cyril

**Comment by ocornut** [comment]
Hello Cyril,

Thanks for posting a detailed and well researched issue.
This is similar to the reason explained in https://github.com/ocornut/imgui/issues/6610#issuecomment-1639843329, it was generally "incorrect" that AllowOverlap would extend to when the item was active, as it made e.g. dragging from a TreeNode with AllowOverlap able to highlight objects in different locations. But this is the second legit use case that my fix is causing an issue with.

The workaround to get to the same logic as the previous `SetItemAllowOverlap()` would be to call this after the `TreeNode()`:
```cpp
ImGuiContext& g = *GImGui;
if (g.ActiveId == ImGui::GetItemID())
    g.ActiveIdAllowOverlap = true;
```
Because you only need that to be set once to allow the `InputText()` to be activated, you may call it in the same block where you set the `edit` value.

**However for this specific logic you are using, technically you could also just call `ImGui::ClearActiveID()` when setting `edit = ...` and this has the benefit that you are relying on less internals stuff details.** While this is still technically an internal API i would suggest this is the best solution for you now.

Note that this pattern is analogous to what we are using for CTRL+Clicking into Sliders and Drags. 
See our implementation of the `TempInputText()` function. It may be reasonable that you call `TempInputText()` but it's a little more likely to break internal api from time to time, so if just setting `ClearActiveID()` works for you that's enough,

**Comment by cpichard** [comment]
Hi Omar,
Thanks, adding the `ImGui::ClearActiveID();` fixes the issue in my application, this is great !  I can now upgrade to the latest imgui version.
Thanks again for the explanation and the quick support,
Best,
Cyril
