### ISSUE TITLE
Vertical scrollbar does not appear on ImGui::BeginMenuBar

### ISSUE THREAD

**Issue by ElectroidDes** [ocornut/imgui#6706]
If I create a window in this way, then everything is cool, Vertical scrolling adjusts to the specified SetCursorPos along the Y axis.
    
```
    bool bool_;
    ImGui::Begin("Win_name", &bool_, ImGuiWindowFlags_MenuBar);

    if (ImGui::BeginMenuBar() == true)
    {
        ImGui::EndMenuBar();
    }

    ImGui::SetCursorPos({ 10,1000 });

 ImGui::End();
```

But if I call SetCursorPos BEFORE ImGui::BeginMenuBar() the vertical scrollbar doesn't even appear:

```
    bool bool_;
    ImGui::Begin("Win_name", &bool_, ImGuiWindowFlags_MenuBar);


    ImGui::SetCursorPos({ 10,1000 });

    if (ImGui::BeginMenuBar() == true)
    {
        ImGui::EndMenuBar();
    }

 ImGui::End();
```

Is that how it should be?

**Comment by ElectroidDes** [comment]
I seem to understand that ImGui::BeginMenuBar() changes the value of ImGui::SetCursorPos.
I thought ImGui::SetCursorPos should internally store the maximum value that was set per frame.

**Comment by ocornut** [comment]
Hello,

The first behavior is a small bug and the second behavior is correct.

> I thought ImGui::SetCursorPos should internally store the maximum value that was set per frame.

Since 1.89 we have obsoleted and clarified this:
See "Breaking Changes" in https://github.com/ocornut/imgui/releases/tag/v1.89
If you want to extend the window contents size you need to submit an item, even a `Dummy({0,0})`; will work.

**Comment by ocornut** [comment]
> The first behavior is a small bug 

Actually it's not even a bug, it is because when IMGUI_DISABLE_OBSOLETE_FUNCTIONS if not set we currently emulate this behavior, see the comments and code in `ErrorCheckUsingSetCursorPosToExtendParentBoundaries()`:
https://github.com/ocornut/imgui/blob/f7eea6387202f1174fdb7072311156d667a6826c/imgui.cpp#L9160

If you set `IMGUI_DISABLE_OBSOLETE_FUNCTIONS` you will find this to assert since 1.89.
