### ISSUE TITLE
Docking and persistence

### ISSUE THREAD

**Issue by lailoken** [ocornut/imgui#6717]
Version: v1.89.9 WIP
Branch: docking
Backend: Windows (also Emscripten)

I've made a lot of progress and have a mostly working version of docking that persists.

What I do is:
* I create a static singleton dockspace ID. (always the same)
* I use this ID to query if the main dockspace node exists already (as it may have persisted)
* If it doesn't then I create the dockspace, AND split it (left/right).
* I get the ID of the right side (either via the split function, or via the Children of the main dock node.
* I then dock windows that are added periodically with random names/IDs to this right side.

This approach works for me and I have created this sample to show my logic:
(I create 3 windows with the same names, thus they should persist their positions/states (and they do) and I can create others which should add to the right side dock) which they do)

```#include <imgui_internal.h>

static std::vector<std::string> names = {};
void testDocking()
{
    if (names.empty())
    {
        names.emplace_back("persisted_one");
        names.emplace_back("persisted_two");
        names.emplace_back("persisted_three");
    }

    static ImGuiID dock_main = ImGui::GetID("main");
    static ImGuiID dock_left = {};
    static ImGuiID dock_right = {};

    bool reset_layout = false;

    ImGui::SetNextWindowSize({800.f, 200.f}, ImGuiCond_FirstUseEver);
    if (ImGui::Begin("Main view"))
    {
        if (ImGui::Button("Add"))
        {
            std::string const newName = GeneratRandomString(10);
            names.emplace_back(newName);
            if (dock_right)
                ImGui::DockBuilderDockWindow(newName.c_str(), dock_right);
        }
        ImGui::SameLine();
        reset_layout = ImGui::Button("Reset");
    }

    auto main_node = ImGui::DockBuilderGetNode(dock_main);
    if (reset_layout || !main_node)
    {
        // (Re-)create main dockspace
        ImGui::DockBuilderAddNode(dock_main, ImGuiDockNodeFlags_AutoHideTabBar);
        ImGui::DockBuilderSplitNode(dock_main, ImGuiDir_Left, 0.5f, &dock_left, &dock_right);

        // Always Docked on left
        ImGui::DockBuilderDockWindow("Info", dock_left);

        // Set current known windows to be docked on right
        for (auto const& name : names)
            ImGui::DockBuilderDockWindow(name.c_str(), dock_right);

        ImGui::DockBuilderFinish(dock_main); // what is this for?

        main_node = ImGui::DockBuilderGetNode(dock_main);
    }
    ImGui::DockSpace(dock_main);

    // This solves the persistence problem, but stops working all windows are undocked from dock_right
    if (!dock_right)
    {
        if (main_node->ChildNodes[1])
            dock_right = main_node->ChildNodes[1]->ID;
        else
            dock_right = {};
    }
    
    ImGui::End();  // Main view

    ImGui::SetNextWindowSize({400.f, 200.f}, ImGuiCond_FirstUseEver);
    ImGui::Begin("Info");
    ImGui::End();  // Info

    for (auto const& name : names)
    {
        ImGui::SetNextWindowSize({400.f, 200.f}, ImGuiCond_FirstUseEver);
        ImGui::Begin(name.c_str());
        ImGui::End();  // Names
    }
}
```

This seems logical, and works well, and I think I'm beginning to understand how it works.

However, I have noticed that if I undocked all the windows from the right hand side, and then restart the application, this time it finds the main node as usual, but unlike if I had left windows docked the right side, this time the ChildNodes are empty.

My question:
Why is the right side child dockspace non-persisted/destroyed on restart when there are no longer any windows docked?
Is docking space purely persisted as part of window state?
Is it possible to force it to persist somehow? If so how?

Regards,

**Comment by GamingMinds-DanielC** [comment]
Splits are persistent as long as any known window is docked there. If the user undocks all windows, the splits are no longer needed and get removed. This is useful behavior to not clutter the dockspace with any split that has existed once for no matter how short of a time.

You can force the dockspace to keep important splits by adding dummy windows to them. Just don't show those dummy windows, then the user can't undock them. They don't need any content, they just need to exist to keep splits alive. Either that or you can redo the splits whenever needed.

**Comment by lailoken** [comment]
@GamingMinds-DanielC , that's a sweet trick, will try it, thanks.

Related to that, since the left side of the split is still used and docked, what happens to that left dockspace? Where can I find it once I have the main node? (I don't seem to see it in any main node member (sub)property...)

Moreover, I have tried (when I find the main dockspace no longer has children) to just re-split it... but that yields an error, which also confused me.)

**Comment by ocornut** [comment]
Moreover, your approach is actually incorrect:

> then dock windows that are added periodically with random names/IDs to this right side.

Because this approach assume that your "right side" ID always exists.
If you undock that node, or split it again, then the logic doesn't work anymore.

This is one of the difficulty of Docking that people both misunderstand or underestimate. It is for this reason that I initially went with the concept of a "Central node" flag which would get moved from node to node during split/merge actions and which only a single node in a hierarchy could have. The current implementation has some issues and limitations but I think in the future we might expand and generalize this design with perhaps concept of user submitted tags. (The whole situation is actually more complicated than I'm suggesting it here, I think some of those tags ought to be carried by windows and not docking nodes, as the earlier would more reliably matches what the end-user can see, so I guess the operation of "Setting an initial location for this new window" may preferably target a window or a tag carried by a window; TL;DR; I don't have a suitable design for long term settings persistence + setting dock targets).

Note that one property of the CentralNode is to stay alive when it has no window, which I guess it equivalent to docking a dummy window (I had never thought of that before to be honest, but I think it'll work), but similarly it doesn't mean your docking hierarchy can't be altered.

The whole situation is more complicated than was a described and I don't have a suitable design for it. If you try to mix long-term persistent settings.

**Comment by lailoken** [comment]
The more I work with docking the more I appreciate the unexpected complexity. I was naive at the beginning, now I'm only pragmatic in what I can do.

Generally, when I create a docking node explicitly using `DockBuilderAddNode`, I can pass flags like `ImGuiDockNodeFlags_CentralNode`, which is what I assume you mean. However, when I create that node using the split `DockBuilderSplitNode` function there is no obvious way. Instead, I've added this code:
```
// This should help right side nodes persist when no windows docked:
auto conn_node = ImGui::DockBuilderGetNode(dock_book_id);
conn_node->SetLocalFlags(ImGuiDockNodeFlags_CentralNode);
```

And it now functions as I wanted it to, but visually it seems to ignore my 0.5f split (which worked before):
![image](https://github.com/ocornut/imgui/assets/403154/c4be822d-6572-4607-9fda-35ad51c8b33d)

The full creation code looks like this:
```
    auto const conn_node = ImGui::DockBuilderGetNode(dock_main_id);
    if (dock_all || !conn_node)
    {
        ImGui::DockBuilderAddNode(dock_main_id, ImGuiDockNodeFlags_NoCloseButton);
        ImGuiID dock_detail_id = {};
        ImGui::DockBuilderSplitNode(dock_main_id, ImGuiDir_Left, 0.5f, &dock_detail_id, &dock_book_id);

        // Always Docked on left
        ImGui::DockBuilderDockWindow(detail_title.c_str(), dock_detail_id);
        ImGui::DockBuilderDockWindow(threads_title.c_str(), dock_detail_id);

        ImGui::DockBuilderFinish(dock_main_id);

        // This should help right side nodes persist when no windows docked:
        auto conn_node = ImGui::DockBuilderGetNode(dock_book_id);
        conn_node->SetLocalFlags(ImGuiDockNodeFlags_CentralNode);
    }
    else
    {
        if (conn_node->ChildNodes[1])
            dock_book_id = conn_node->ChildNodes[1]->ID;
        else
            dock_book_id = {};
    }
    ImGui::DockSpace(dock_main_id);
```
All of this code is called inside another window Begin/End, which so it should be that Size is known for split to work correctly (and it has in the past). I'm not sure what to do to make sizing work again.

**Comment by lailoken** [comment]
@GamingMinds-DanielC , PS: I tried creating a dummy window that was hidden, but I'm not sure I'm doing it right... I still see a tab for it at the top when docked. Not sure how I can hide it while still docking it...

**Comment by GamingMinds-DanielC** [comment]
You can "hide" windows by not submitting them, basically keep them closed.

**Comment by ocornut** [comment]
> @GamingMinds-DanielC , PS: I tried creating a dummy window that was hidden, but I'm not sure I'm doing it right... I still see a tab for it at the top when docked. Not sure how I can hide it while still docking it...

If you dock it with the DockBuilder API and never submit the window that should be enough.

**Comment by ocornut** [comment]
> Generally, when I create a docking node explicitly using DockBuilderAddNode, I can pass flags like ImGuiDockNodeFlags_CentralNode, which is what I assume you mean. However, when I create that node using the split DockBuilderSplitNode function there is no obvious way. Instead, I've added this code:
> // This should help right side nodes persist when no windows docked:
auto conn_node = ImGui::DockBuilderGetNode(dock_book_id);
conn_node->SetLocalFlags(ImGuiDockNodeFlags_CentralNode);

Please don't do that. 
There can be only 1 central node per hierarchy so you should not mess with it when splitting nodes and let the system do it.

When calling `DockBuilderAddNode()` if you use the `ImGuiDockNodeFlags_DockSpace` flag it'll make it a CentralNode, otherwise they won't be any. This behavior is likely to evolve/change in the future as many Docking issues are related to this.

> But it seems that I need to add the following again to get my layout right:

There's currently a lossy computation which affects nodes with no size in certain circumstances. See comment in dock builder section.

```
    // - If you intend to split the node immediately after creation using DockBuilderSplitNode(), make sure
    //   to call DockBuilderSetNodeSize() beforehand. If you don't, the resulting split sizes may not be reliable.
```
