### ISSUE TITLE
IsMouseClicked - returns the result when the button is pressed

### ISSUE THREAD

**Issue by ElectroidDes** [ocornut/imgui#6725]
IsMouseClicked  - returns the result when the button is pressed, not when the Click occurs, that is, the click-release cycle of the mouse button.

```
if (ImGui::IsMouseClicked(0) == true)
    {
        std::cout << "IsMouseClicked" << std::endl;
    }
```

Is this the correct behavior of the function?

**Comment by GamingMinds-DanielC** [comment]
According to the documentation in the header, `IsMouseClicked()` is supposed to be true when the button changes from not pressed to pressed. As intended basically. Maybe `IsMousePressed()` would have been a better name.

I don't see a function that handles the click cycle as you described it, but you should be able to layer one on top. Might be a bit finicky though since you would need to track a few things per frame (max down duration, max movement, same item id under the mouse cursor).

**Comment by ocornut** [comment]
That tracking requires a shape as it only makes sense within given geometry (otherwise you would use IsMouseReleased) wnd is performed by buttons, which needs a stable identifier. You can use InvisibleButton() or lower-level ButtonBehavior() to do that.
