### ISSUE TITLE
Close/Collapse button interact area is too big

### ISSUE THREAD

**Issue by nem0** [ocornut/imgui#6749]
**Version/Branch of Dear ImGui:**

Version: 18982
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx9.cpp (and others)
Compiler: vs2022
Operating System: Win10

**My Issue/Question:**

With big enough frame padding and collapse button on the same side as close button, close button is impossible to click.
No code necessary, just set frame padding x to 20 in style editor, move the collapse button to the right and try to click on the close button.

Note: interact area too big has other annoying issues, I often accidentally close a tab when I try to select it.

**Screenshots/Video**

![image](https://github.com/ocornut/imgui/assets/153526/18b373b4-5b93-4001-8a37-9b1d23f3f644)

**Comment by ocornut** [comment]
This is indeed a bug because they layout with typical FramePadding around all sides, but calling code (e.g. `RenderWindowTitleBarContents()`) position them manually not taking this into account.

I'll rework but but I am interesting to see your desired spacing/padding settings.
)With sufficiently large value it is expected that the items will be widely spaced out.)

**Comment by ocornut** [comment]
It's a common idiom for widgets of this type to be fit into a square, and in this case we would use FramePadding.y on BOTH axises to create the square, in order to be consistent with other widgets. (It's a little bit ambiguous as those two don't display an actual square frame, but in some situation they are expected to be lined up next to regular framed widgets).

So TL;DR; IHMO the right fix would use FramePadding.y padding on both axises, meaning if you have a large value for that, they would be spaced with large distance, but with fixed code they won't overlap.

**Comment by ocornut** [comment]
I have pushed 4a81424 and 61d3597, using ItemInnerSpacing.x between buttons.
Let me know how that works for you.

I'm thinking for those buttons inside the title bar we might want to hit-test on the entire vertical range?

**Comment by nem0** [comment]
>I have pushed https://github.com/ocornut/imgui/commit/4a8142449252c03e52116689f74a315f7b0100a3 and https://github.com/ocornut/imgui/commit/61d35972e2ee0e2ee473290fcc2e265ea5b7be38, using ItemInnerSpacing.x between buttons.
Let me know how that works for you.

It works well, thank you.

> I am interesting to see your desired spacing/padding settings.

I only used big padding so the issue can be easily reproduced/seen, otherwise I use some reasonable/default values.
