### ISSUE TITLE
I heard that c_str() is bad if used everywhere. What is the proper way to add strings?

### ISSUE THREAD

**Issue by elanhickler** [ocornut/imgui#6778]
```
Dear ImGui 1.89.7 (18971)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=202002
define: _WIN32
define: _WIN64
define: _MSC_VER=1933
define: _MSVC_LANG=202002
define: __clang_version__=15.0.2 
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_vulkan
io.ConfigFlags: 0x00000003
 NavEnableKeyboard
 NavEnableGamepad
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

I heard that c_str() is bad if used everywhere. What is the proper way to add strings?

Example:

Bad?

```cpp
struct TheBadWay {
    TheBadWay(std::string_view label) : label_(label) {}
    
    std::string_view label_;

    void draw() {
        ImGui::Button(fmt::format("##enable%s", label_).c_str());
    }       
};
```

Good?

```cpp
struct TheAnnoyingWay {
    TheAnnoyingWay(const char* label) : label_(label) {}
    
    const char* label_;

    void draw() {
        ImGui::PushID(label_);
        ImGui::Button("##enable");
        ImGui::PopID();
    }       
};
```

**Comment by ocornut** [comment]
`c_str()` is fine.

There is no "good" or "bad" way everything is nuanced and complex, but unfortunately this isn't the place to discuss this, it is a general C/C++ programming question.

In both of your example you are referring to data you don't own, assuming their lifetime will match the lifetime of your class instances. I don't know if this is intended and desirable or accidental.

Then you are doing two completely different thing in each example, which are unrelated to the use of `c_str()` , in one you are appending two strings using format, in the other you aren't. 

I personally use my own helper class https://github.com/ocornut/str because i'm not fond of heap-allocations incurred by use of std::string, and I find the formatting syntax tedious (I prefer printf style), but this is my own peculiar habit. I find it more performant and faster to write.

We cannot be discussing this here further, please use a general programming community, we don't have resources to be discussing this.
