### ISSUE TITLE
Navigation using Tab Key with InputTextMultiline and ImGuiConfigFlags_NavEnableKeyboard, not detecting new line

### ISSUE THREAD

**Issue by alattanzio** [ocornut/imgui#6802]
Hi there,

I've found an issue which happens only with ImGuiConfigFlags_NavEnableKeyboard set.
The navigation happens with Tab Key and focus changes, but somehow the Enter button (New Line) on the InputTextMultiline is not detected, unless Enter is held down. 
Is there any way to fix it ? 

Example:

    static bool p_open = true;
    static char strFeedback[1024];
    if (ImGui::Begin("Feedback", p_open, 0))
    {
        ImGui::InputTextMultiline("##feedback", &strFeedback[0], IM_ARRAYSIZE(strFeedback), ImVec2(0, 120), text_flags);
        if (ImGui::Button("Send!###send"))
        {
            // send message
        }
    }
    ImGui::End();

Thanks, Antonio.

UPDATE:
This issue actually happens when the control InputTextMultiline is focused. Otherwise works all fine.

Focused (not working properly)
![image](https://github.com/ocornut/imgui/assets/38122259/50b25b05-ad83-46bd-8bc4-87f3b9d2bcee)
Not-Focused (WORKING!)
![image](https://github.com/ocornut/imgui/assets/38122259/4f9a9d91-8011-44bf-898b-50bfcbbd57f1)

**Comment by ocornut** [comment]
Thank you for reporting.
I have pushed a fix for this 0e1ce76.
Amusingly we had a comment directly the double activation as "Harmless but bizarre." but it turned out not to be harmless.

Pushed an automated regression test to TestEngine:
https://github.com/ocornut/imgui_test_engine/commit/478329f02f09c38a7c353851c64b3fc4915c2ef3

The fact the the navigation system only emits the `g.NavActivateId` signal (on space or enter) when `g.NavDisableHighlight == false` is probably to be reworked and currently creates some inconsistency. I guess when `ImGuiConfigFlags_NavEnableKeyboard` is set we should always restore the highlight on tabbing.

**Comment by ocornut** [comment]
> The fact the the navigation system only emits the g.NavActivateId signal (on space or enter) when g.NavDisableHighlight == false is probably to be reworked and currently creates some inconsistency. I guess when ImGuiConfigFlags_NavEnableKeyboard is set we should always restore the highlight on tabbing.

Also pushed a change for that: b9ab6e2

**Comment by alattanzio** [comment]
That's great! Thank you so much! It was driving me crazy :) Cheers!
