### ISSUE TITLE
Texture is failed to be rendered

### ISSUE THREAD

**Issue by wecand0** [ocornut/imgui#6808]
Try to render texture from global map, I get texture ID from engine and render it with 
`ImGui::Image((void *)(intptr_t)texture_id, {300, 300}, ImVec2(0, 1), ImVec2(1, 0));`

But I got this, what can be wrong, such lights are aprered only than I add marker on map, and "on the background" of texture I see some rectangles that are changed than I zoom map or change position.
![screen](https://github.com/ocornut/imgui/assets/18683616/7dd049c7-c1f4-4501-95c8-1d8a867524a2)

**Comment by ocornut** [comment]
I don't understand your question and you are not providing enough information.
Please read [Contributing Guidelines](https://github.com/ocornut/imgui/blob/master/docs/CONTRIBUTING.md) carefully and add missing information to your post. Right now we don't even know what your problem is, but it's likely in your code.
