### ISSUE TITLE
InputScalar formatting Issues

### ISSUE THREAD

**Issue by Dannode36** [ocornut/imgui#6829]
Version: 1.89.9
Branch: docking

Back-ends: imgui SFML
Operating System: Windows

I've come across an issue where string formatting is not possible with integer inputs. Scalar inputs, while supporting formats, don't behave as expected. In my case I'm trying to display Height & Width inputs to the user where the formatting looks something like "Height: %u" and "Width: %u". When using InputScalar with those formats, it becomes impossible to edit the value BUT if you flip the format into something like "%u width" it becomes possible to edit the value but "width" does not disappear when editing the input. 

This however isn't the case with DragScalar's as the input goes through a function called "ImParseFormatTrimDecorations" so when the user edits the input, only the value is visible.

I'm mainly wondering if this is intentional and/or how to implement an integer input with "format decoration trimming"

```
ImGui::Begin("Format Bug");
static int* value = 0;
ImGui::InputScalar("Prefix Example", ImGuiDataType_S32, value, 0, 0, "prefix %d"); //Unable to edit value
ImGui::InputScalar("Suffix Example", ImGuiDataType_S32, value, 0, 0, "%d suffix"); //Value editable. Incorrectly displayed when editing
ImGui::End();
```

**Comment by PathogenDavid** [comment]
This appears to be a maybe-bug coming from `ImParseFormatSanitizeForScanning` used by `ImGui::DataTypeApplyFromText` (which is in turn used by `ImGui::InputScalar`.)

In the suffix case, `ImParseFormatSanitizeForScanning` transforms `%d suffix` to `%d` as you'd expect.

In the prefix case it transforms `prefix %d` to an empty string.

Forcing the format string to `%d` works as long as the user clears the prefix, but still doesn't if they don't since the `sscanf` chokes on the prefix. (Using the unchanged format string works in that case, but I can see a user interacting with it in both ways so IMO either behavior is bad.)

-------------------

My first instinct is to say that you shouldn't use prefixes/suffixes in the format string of any `ImGui::Input*` widgets.

Unlike sliders and drags it's not explicitly documented as being supported (although it seems Dear ImGui does try to handle it), but also it's feels just...really unnatural and unusual.

In your case it seems like you should just be labeling the entire control as width/height. Also consider using a `DragInt` instead as they're much more pleasant to interact with (IMO.)

**Comment by ocornut** [comment]
I investigated this a bit and generally agrees with David answer.
It can work on Drag/Slider as there's a clear text transform when activating the widget (ctrl+click or single click with `io.ConfigDragClickToInputText = true`). Performing text selection on an InputScalar which swapped its content on clicking wouldn't work so I don't think it is desirable and I can't even think of a good way to do it.
For SUFFIX I suppose we could devise a scheme where the suffix is displayed separately and not selectable but it wouldn't work for prefixes.

I would suggest using a DragXXX as mentioned.

**Comment by Dannode36** [comment]
TIL that ```io.ConfigDragClickToInputText = true``` exists so I think I'll just roll with that. Definitely seems to be a more flexible way of achieving what I need. As for the SUFFIX, something like _"where the suffix is displayed separately and not selectable"_ is definitely a feature I'd like to see. I'm making my own tile editor based off Tiled and that how their suffix's function. Thanks guys!
