### ISSUE TITLE
Unable to run Imgui in multi-project

### ISSUE THREAD

**Issue by Spyeedy** [ocornut/imgui#6884]
**Version/Branch of Dear ImGui:**
Version: 1.90 WIP (18992)
Branch: docking

**Back-end/Renderer/Compiler/OS**
Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: XXX _(if the question is related to building or platform specific features)_
Operating System: Windows

**My Issue/Question:**
I have 2 projects within a solution, SomeFramework and Editor. SomeFramework as the name implies is a framework to setup the window, basic rendering, detecting input, etc, sort of like an engine. SomeFramework is a dynamic library project, compiles to dll. Editor is an executable project, compiles into an executable. Editor depends on SomeFramework for the window and such and has an additional dependency of Imgui.

I am not too sure why Imgui is unable to run in the [Editor project (latest commit)](https://github.com/Spyeedy/EngineEditorImgui/blob/master/Editor/src/main.cpp), but if I move the Imgui setup & rendering codes into the [Application.cpp (older commit)](https://github.com/Spyeedy/EngineEditorImgui/blob/787a58a4a6e2a1f23ea4b8abc68e89f0b5a453aa/SomeFrameworkProj/src/Core/Application.cpp) of my SomeFramework project, Imgui is able to run fine.

The assert error that Imgui throws out when I setup Imgui in Editor is:
`Assertion failed: bd->GlfwWndProc != nullptr, file C:\...\imgui_impl_glfw.cpp, line 676`

**Screenshots/Video**
None

**Standalone, minimal, complete and verifiable example:**
Um, I don't have a small example, but I do have my project linked here that you can clone to reproduce this issue, Sorry! [Project Link](https://github.com/Spyeedy/EngineEditorImgui)
I have 2 commits in the repository. The first commit is one where SomeFramework runs Imgui (it runs fine), and the second commit is where Editor runs Imgui.

**Comment by sakiodre** [comment]
If you call `glfwGetError()` you'll see that it says: "The GLFW library is not initialized", making `glfwGetWin32Window()` return nullptr and triggering the assertion.

The issue is that you called `glfwInit()` in "SomeFramework" but not in "Editor", so you can fix it by calling `glfwInit()` before `ImGui_ImplGlfw_InitForOpenGL()` in main.cpp L#48:
```cpp
glfwInit();
ImGui_ImplGlfw_InitForOpenGL(SomeFramework::Window::GetNativeWindow(), true);
```

Imho, this design is questionable, if there aren't any clear benefits, you should put it all into one project.

**Comment by zao** [comment]
The root cause is external to Dear ImGui. You're statically linking separate instances of GLFW in each of your DLLs. Initialization in one module is independent from the other module and no such GLFW state will be shared.

In a scenario where you have multiple DLLs, you most probably want everything that crosses DLL boundaries to themselves be dynamically linked so that a single implementation is shared.

See <https://www.glfw.org/docs/3.3/build_guide.html#build_link> for details on linking GLFW properly.

On using Dear ImGui in such a scenario you may have to investigate if it's fine to have two separate implementations from the same sources in each of the modules interacting via context pointers, or if there's local (global) state in the implementation that must be shared explicitly.

**Comment by Spyeedy** [comment]
> Imho, this design is questionable, if there aren't any clear benefits, you should put it all into one project.
It's a pet project, I'm exploring and learning to have a library project and an executable project that depends on the library.

> The root cause is external to Dear ImGui. You're statically linking separate instances of GLFW in each of your DLLs. Initialization in one module is independent from the other module and no such GLFW state will be shared.
So if I understand what you and the glfw documentation you linked are saying, I need to use the glfw dynamic library rather than the static library? Would that resolve the issue entirely or just part of the issue?

> On using Dear ImGui in such a scenario you may have to investigate if it's fine to have two separate implementations from the same sources in each of the modules interacting via context pointers, or if there's local (global) state in the implementation that must be shared explicitly.
Sorry I don't quite understand, what do you mean by "two separate implementations"?

**Comment by Spyeedy** [comment]
Update: By linking with glfw's dynamic library (instead of static library) in my SomeFramework project and defining the `GLFW_DLL` macro before including the glfw header, my issue has been resolved. Thank you so much @zao !!

Detailed steps to my solution:
1. Get glfw's dynamic library files, they are glfw3dll.lib and glfw3.dll
2. Link with glfw3dll.lib
3. Place glfw3.dll in your output folder where your executable would be generated. I copied this dll from my dependencies' bin folder into the output folder with a xcopy command via Post-Build Events
4. define `GLFW_DLL` macro before you include the glfw header.

**Comment by ocornut** [comment]
Closely as seemingly answered.

> or if there's local (global) state in the implementation that must be shared explicitly.

Dear ImGui use a global which will be unique across DLL boundaries and needs to be synchronized into each DLL by calling `ImGui::SetCurrentContext()` with your context pointer.
