### ISSUE TITLE
Impossible to use ImNodes.net

### ISSUE THREAD

**Issue by guillaC** [ocornut/imgui#6888]
Hello, I would like to use the ImNodes library in my project to display the structure of a database. However, integrating the ImNodes.NET library makes it impossible to execute my project, even without using it

Screenshot :
![image](https://github.com/ocornut/imgui/assets/6315083/e2bd4d8d-a4e2-463e-986b-f0fc5ba3bc25)
![image](https://github.com/ocornut/imgui/assets/6315083/e5264533-4ce5-43b0-a08f-8e891a26b4a3)

If you know the origin or the reason for the problem, it would greatly help me.

**Comment by ocornut** [comment]
Hello,
Neither ImNodes nor ImGui.Net are developed by me I cannot provide support for them.

**Comment by PathogenDavid** [comment]
As Omar stated this is the wrong place to ask for help with these libraries.

That being said... Looking at your dependencies it looks like ImNodes.NET uses a fork of ImGui.NET (DasDarki.Fork.ImGui.NET) which comes with its own `cimgui.dll` that is presumably conflicting with the one from vanilla ImGui.NET. (I would be surprised if NuGet isn't complaining about this during build or restore if you check for warnings.)

The easiest fix in your situation is probably to directly use the fork instead of vanilla ImGui.NET.

(Although you should also really consider whether you want to use a wrapper with no license information or source repository in the first place.)
