### ISSUE TITLE
ImGui not displaying OpenGL textures with bit depth 2

### ISSUE THREAD

**Issue by ingvart** [ocornut/imgui#6908]
**Version/Branch of Dear ImGui:**

Version: 1.89.2
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends:
imgui_impl_sdl
Correction, NOT in use: imgui_impl_sdlrenderer
Correction, NOT in use: imgui_impl_opengl2
imgui_impl_opengl3

**My Issue/Question:**

I have a project using SDL and OpenGL.
ImGui is using OpenGL to render.
I use SDL's function IMG_LoadTexture to load textures.

As ImGui is using OpenGL for rendering, I cannot display an image with ImGui::Image using the SDL texture pointer.
As SDL does not give me the OpenGL texture ID, I do the following:
```
SDL_GL_BindTexture(sdl_tex, NULL, NULL);
GLuint id;
glGetIntegerv(GL_TEXTURE_BINDING_2D, reinterpret_cast<GLint*>(&id));
ImGui::Image((ImTextureID)(intptr_t)id);
```
This works great for RGBA PNG images with bit depth 4.
But if the image, according to Windows file properties, has bit depth 2, ImGui will not display the image/texture.

Is this because ImGui internally calls
glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, ........
using RGBA?

Or something else?
Is there a way to fix this, or do I need to convert all images to bit depth 4?

Thanks!

**Comment by PathogenDavid** [comment]
This question is hard to answer because the information you've provided is confusing/misleading and you're probably making things more complicated than they need to be.

In general this feels more like a graphics API question rather than a Dear ImGui one.

> imgui_impl_sdlrenderer
> imgui_impl_opengl2
> imgui_impl_opengl3

You should only actually be using one of these. I assume `imgui_impl_opengl3`, but the ambiguity is not helping here.

> I use SDL's function IMG_LoadTexture to load textures.
> [...]
> As SDL does not give me the OpenGL texture ID, I do the following:

In general if you're making an OpenGL app, I think you'd be far better off learning how to create OpenGL textures properly rather than trying to kludge SDL_Renderer and OpenGL together.

When you have to resort to dirty hacks like this it should be a hint that you're probably doing something wrong.

[The implementation of `SDL_GL_BindTexture`](https://github.com/libsdl-org/SDL/blob/2a9480c81581bb81cb265844d54e7ee16a69c4ec/src/render/opengl/SDL_render_gl.c#L1548-L1596) does a lot more than just `glBindTexture`, chances are your problematic texture is going down one of those paths.

> This works great for RGBA PNG images with bit depth 4.
> But if the image, according to Windows file properties, has bit depth 2

Your terminology here is confusing. Typical bit depths (specifically bits per pixel) are 8, 24, or 32. Bit depths of 2 and 4 exist in the general sense, but as far as I know they don't exist for PNG.

> Is this because ImGui internally calls
> glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, ........
> using RGBA?

No, that only applies to the font texture.

> Is there a way to fix this[...]?

I think you'd be doing yourself a big benefit of ditching any usage of `SDL_Renderer` and instead upload the OpenGL texture on your own. There's [an example of how to do this](https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples#example-for-opengl-users) on the wiki.

That example uses [stb_image](https://github.com/nothings/stb), but if you want to stick to using SDL_image it shouldn't be too hard to adapt. (I've never used SDL_image myself, but at a glance it looks like you'd want to use `IMG_Load` instead of `IMG_LoadTexture` and possibly `SDL_ConvertSurface` to ensure it's in a format that OpenGL can use.)

------------

Alternatively you could instead ditch OpenGL and use SDL_Renderer with the `imgui_impl_sdlrenderer2` backend. This would let you use `SDL_Texture*` with `ImGui::Image` directly.

------------

A more middle-ground alternative would be to investigate using `IMG_Load` -> `SDL_ConvertSurface` -> `SDL_CreateTextureFromSurface` to ensure images are always in a consistent format.

(You could also use `IMG_Load` and inspect the surface properties to see what's different about your problematic texture.)

(This would also mean you're still using SDL_Renderer and OpenGL together which in my opinion is not a good idea.)

------------

The final alternative would be to manually submit your image quad and use `ImDrawList::AddCallback` to use a callback to call `SDL_GL_BindTexture` in the context of the backend's drawing routine. This would be fairly advanced though, and IMO is more trouble than it is worth in your situation. (As with the previous alternative this also involves using SDL_Renderer and OpenGL together.)

**Comment by ingvart** [comment]
First of all, I got rid of imgui_impl_sdlrenderer and imgui_impl_opengl2. They were simply not in use. I wasn’t kludging the two, but incorrectly listed these two in my CMakeLists.txt and also here. But they were never actually in use.
I can see how using two (or three) renderers would be a dirty hack, and I’m sorry for causing this confusion. But this is not the case here. 

 I use opengl3 for rendering and SDL libraries for user interaction, sound, networking, etc.

I also use SDL to load images and generate OpenGL textures.

But I don’t see that using IMG_LoadTexture() to load and generate a texture is a dirty hack, and I don’t see why Dear ImGui should work with some PNG files and not others.

The textures which do not work with Dear ImGui work fine with other OpenGL code (i.e. glBegin(…), etc.), but then in conjunction with SDL_GL_BindTexture. I would think that the texture has been loaded properly.

The PNG “bit depth” of 2 or 4 is how it is reported by Windows file properties, as I explained. I know that this is not the conventional way of 8, 24 or 32 bit, but I’m not going to try to interpret what Microsoft means. In the “Details” section of the file properties window, the “Image” details lists “Bit depth 4” and “Bit depth 2” for these two pictures. The latter file/image/texture does not display in ImGui, and the former does. But both work with GL code. I also know that only the former picture has a transparent section but the latter doesn’t. This "bit depth" is not my terminology, but Windows’, I’m afraid.

GIMP reports both of these pictures as “Indexed color 8-bit gamma integer”. I am thinking that “IMG_LoadTexture()” results in the picture with transparent pixels being turned into a GL texture with RGBA, and the one without transparent pixels being turned into a GL texture with perhaps RGB. But I am only guessing.
Yes, I can use "IMG_Load" and inspect what SDL does differently with the two files, but I still don't understand why only one would work with Dear ImGui.

Out of hundreds of little pictures like this, Dear ImGui displays all the ones with a transparent section, but none of the ones without. So it appears (which could be wrong), that Dear ImGui expects textures with an alpha layer.

As stated, I can use all these textures fine with OpenGL code elsewhere.

Thank you for several suggested “solutions” and many good ideas and thoughts.

As you suggest using stb_image and my own GL code to load textures, does that mean Dear ImGui is not compatible with SDL’s IMG_LoadTexture? If so, I would really like to know why. Just wanting to learn.

I think using only the imgui_impl_sdlrenderer2 would be disappointing, as I expect that to cause other problems if I want to use OpenGL content and code in conjunction with Dear ImGui.
Then, if Dear ImGui isn't compatible with OpenGL textures loaded by SDL, I may have to add the STB library to my project for loading images. I was hoping to not have to add another one...

I did consider using IMG_Load instead, and then converting the surface with SDL_ConvertSurface to RGBA (if necessary) before making the texture, but this seems like a very unnecessary workaround. 

But why does IMG_LoadTexture create a format OpenGL can use, but Dear ImGui cannot?

**Comment by ingvart** [comment]
Adding this:

Using IMG_Load I get this information from a debug output:

sur = IMG_Load(filename);
sur->format->BitsPerPixel 24, sur->format->BytesPerPixel 3
sur->format->BitsPerPixel 32, sur->format->BytesPerPixel 4

The top one is likely what Windows calls "bit depth 2" and the bottom what Windows calls "bit depth 4".
Only the latter is working with Dear ImGui, and I am wondering why.

**Comment by ingvart** [comment]
Update:

Adding this:
```
if (img_sur->format->BitsPerPixel != 32) {
  SDL_Surface* sur2 = SDL_ConvertSurfaceFormat(sur, SDL_PIXELFORMAT_RGBA32, NULL);
}
```
makes Dear ImGui display the texture. 
But I wish I could get Dear Imgui to handle the 24 bit or RGB textures also.

**Comment by PathogenDavid** [comment]
> But I don’t see that using IMG_LoadTexture() to load and generate a texture is a dirty hack

`IMG_LoadTexture` is meant for use with the SDL_Renderer API. It is not meant for direct use with OpenGL. This is the kludge I was talking about.

The dirty hack is the fact that you have to do this odd dance to get at the OpenGL texture ID.

> As you suggest using stb_image and my own GL code to load textures, does that mean Dear ImGui is not compatible with SDL’s IMG_LoadTexture?

You don't necessarily have to use stb_image, but you really should not be using `IMG_LoadTexture`. `IMG_Load` and creating the texture yourself would be fine.

> Using IMG_Load I get this information from a debug output:

The `format` member is also relevant here.

> If so, I would really like to know why. Just wanting to learn.

Unfortunately answering why exactly you're experiencing these problems would involve digging into the guts of SDL and isn't something that's really in the scope of the help we can provide.

I doubled checked and Dear ImGui can render textures with an `internal_format` of `GL_RGB` just fine, so the fact that your problematic textures lack alpha is probably a red herring.

Since you have the texture rendering fine with normal OpenGL calls you might be able to discern what's different about Dear ImGui by using [RenderDoc](https://renderdoc.org/) and comparing what happens between rendering directly and rendering with Dear ImGui.

**Comment by ingvart** [comment]
Thank you!

**Comment by ocornut** [comment]
You can see how the texture is bound in the backend:
```cpp
glBindTexture(GL_TEXTURE_2D, (GLuint)(intptr_t)pcmd->GetTexID());
```
And which vertex and fragments shader are used in `ImGui_ImplOpenGL3_CreateDeviceObjects()`.
It is certainly possible that not all texture formats would be displayed the way you want under those conditions

The official answer has been indeed to use `draw_list->AddCallback()` to modify the render state of the renderer, as mentioned in one of David's answer. In the case of the OpenGL renderer it should works without too much complexity.
You can "practice" finding the render state by trying to display your bit depth 2 texture yourself (outside of using dear imgui) and you'll find it probably need a few extra OpenGL calls.

Since 1.70 we added a special value `ImDrawCallback_ResetRenderState` for `AddCallback()` which instruct the backend to reset its state, which may be a welcome convenience.

```cpp
draw_list->AddCallback(your_function_that_will_alter_gl_state_to_display_2_bit_depth_texture, &some_data_if_you_need_it);
ImGui::Image();
draw_list->AddCallback(ImDrawCallback_ResetRenderState);
```

There are many variants of this "changing the render state" approach, with more or less enlightening answers e.g. #6452 #5999 #5885 #5656 #5118 #4730 #4174 #4022 #4017 #3591 #3590 #2037 #1639 and many more.

In my opinion it is still an "open problem" in the sense that:
- it should be made easier for the user (maybe that's simply a case of providing better doc/examples).
- if there are way we can make some operation more portable and backend agnostic, that'll be good (similarly to how we added `ImDrawCallback_ResetRenderState`).
- it should be made possible for all backends: effectively in the more complex DX12/Vulkan backend, some variables/state are difficult or impossible to access without some non-trivial hoops. we should find a solution to that.
- we may need to come up with a system to facilitate hooking/reconfiguring the texture binding, similar to #2697. maybe this will facilitate the situation.

**Comment by ingvart** [comment]
For anyone looking at this question, I now have it working in this manner:


```
  SDL_Surface* img_sur = IMG_Load(filename.c_str());
  if (!img_sur) { ... }

  if (img_sur->format->BitsPerPixel == 32 && img_sur->format->BytesPerPixel == 4) {
    format = GL_RGBA;
  } else if (img_sur->format->BitsPerPixel == 24 && img_sur->format->BytesPerPixel == 3) {
    format = GL_RGB;
  } else {
    //Texture file of unknown format
    SDL_Surface* img_sur2 = SDL_ConvertSurfaceFormat(img_sur, SDL_PIXELFORMAT_RGBA32, 0);
    if (img_sur2 == NULL) {
        ... deal with problem ...
    } else {
      SDL_FreeSurface(img_sur);
      img_sur = img_sur2;
      format = GL_RGB;
    }
  }
  glGenTextures(1, &texture_id);
  glBindTexture(GL_TEXTURE_2D, texture_id);
  glTexImage2D(GL_TEXTURE_2D, 0, format, img_sur->w, img_sur->h, 0, format, GL_UNSIGNED_BYTE, img_sur->pixels);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
  SDL_FreeSurface(img_sur);
```

**Comment by ocornut** [comment]
That will work as the workaround of converting your textures to RGBA.
I guess my answer above covered the question of not converting the texture but being able to display it.

If you only have a few textures it won't be much overhead to convert. If you are dealing with gigabytes of data you wouldn't want to waste GPU memory this way.

**Comment by PathogenDavid** [comment]
Thanks for coming back to share your solution!

You should probably be checking `img_sur->format->format` as well to ensure you do the right thing with certain formats. For example, `SDL_PIXELFORMAT_RGB888` and `SDL_PIXELFORMAT_BGR888` are both 24 bits per pixel but they use different channel ordering.

**Comment by ingvart** [comment]
Thank you again!
