### ISSUE TITLE
ImGuiColorEditFlags_Uint8 not being used correctly

### ISSUE THREAD

**Issue by gamecoder-nz** [ocornut/imgui#6919]
**Version/Branch of Dear ImGui:**

Version: Current
Branch: master

**Back-end/Renderer/Compiler/OS**

Any

**My Issue/Question:**

According to the documentation ImGuiColorEditFlags_Uint8 should allow you to pass in values that are in the range of 0-255 via a uint8_t data type.  However only floats in the range 0-1 work and the color edit will only accept floats.

**Comment by GamingMinds-DanielC** [comment]
The documentation to that flag even emphasizes that it affects the "display":
`// ColorEdit, ColorPicker, ColorButton: _display_ values formatted as 0..255.`

Where did you read that it was about the type of data passed? I only looked at the documentation in imgui.h just now. If there are contradicting statements anywhere else, please point them out so that they can be corrected.
