### ISSUE TITLE
Question regarding TreeNode

### ISSUE THREAD

**Issue by Lumengine** [ocornut/imgui#6921]
Version/Branch of Dear ImGui:
Version: Dear ImGui 1.90 WIP
Branch : docking

My Issue/Question:

I looked for info but did not find anything about it. Is there a way to write into the same TreeNode from different location.
Do something like 
if (ImGui::TreeNode("Test"))
{
    xxx
} 
and again, in another location (typically a plugin)
if (ImGui::TreeNode("Test"))
{
    xxx
} 

I ensure that it is the same ID stack but obviously, I got 2 tree node and some conflicts.
I think it's not feasible but I want somebody to confirm ?

Thank you.

**Comment by GamingMinds-DanielC** [comment]
To confirm: yes, this way is not possible. Only windows and menus can be appended to by reopening them within the same frame.

If you want to fill the same tree node from different source locations, you need an approach that lets you submit everything one after another while submitting the tree node only once. Maybe a few more hooks for your plugins so that you can ask them for each id if they want to submit anything.

**Comment by ocornut** [comment]
Closing as answered, I confirm this is not possible.

**Comment by Lumengine** [comment]
Thank you for the answer.
