### ISSUE TITLE
API DOCS?

### ISSUE THREAD

**Issue by colesnicov** [ocornut/imgui#693]
Hi Omar. Sorry for my english. Where i can foud API DOCS for your ImGui please? I missing PC and i programming on my Android Phone. I can not generate API DOCS for mi on this. You can generate it or tell mi where i can download it? Thanks and sorry for my english again - I'm Rus from Czech.

**Comment by ocornut** [comment]
Hello,
The documentation are implicit in imgui.h, top of imgui.cpp and all of imgui_demo.cpp (ShowTestWindow() function called by the example application). That's all we have for now, sorry.
Omar

**Comment by RobertoMalatesta** [comment]
Just to have a basic bird's view of the whole IMGUI I've created a small Doxygen conf.
I find it worth for peeking around with IMGUI code while deciding weather to adopt it or not.
Output is here:
[http://exedraos.com/imguidoxy/](http://exedraos.com/imguidoxy/)

The generating Doxyfile to be put inside imgui dir and executed with a simple **doxygen** call is here:
[http://exedraos.com/imguidoxy/Doxyfile](http://exedraos.com/imguidoxy/Doxyfile)

Just my .000002 euro cents.

--R

**Comment by ocornut** [comment]
It doesn't seem to be providing much useful output there? The comments are lost, I can't find any of the naked functions which are 95% of ImGui.

**Comment by RobertoMalatesta** [comment]
- There are some rules that have to be followed while writing comments for achieving that.
https://www.stack.nl/~dimitri/doxygen/manual/docblocks.html
- besides, C functions are not listed if the containing file does not contain the @file directive.

These two points would have implied to modify your source comments, something I did not want/had the time to do.

Besides, you could not be interested in a DoxyGen documentation, so it all would factor into an unsolicited pull request.

I've updated it. Can you tell me the name of some naked function (one is enough) that do not get listed?
(you know, I'm just lurking from outside by now, so I don't have a clear idea of the inners).

--R

**Comment by ocornut** [comment]
I see that you have added a namespace tab now and those functions are now showing!
(Pretty much any useful function is a naked function in the namespace, E.g. `ImGui::DragFloat()` or `ImGui::InputText()` imgui rarely use oop)

You are correct that I am not ready to modify the imgui sources to include doxygen comments, because I think that as-is it would be detrimental and noisy to the project. I'm however very interested in the prospect of developing automated documentation (see e.g. #435), the request is merely to find out the right form for it and finding a suitable process and maybe a maintainer who are accustomed to the library.

Right now if you want to get acquainted to the project the best way is to read the documentation in imgui.cpp comments and run/mess around with the examples and the `ShowTestWindow()`. function.

**Comment by RobertoMalatesta** [comment]
Good.
_BTW: the code change won't be so intrusive since you should only use /// instead of // or /** instead of /*._

I didn't use DoxyGen since 5 years and I did not remember a single damn of it, but it's so simple that I was up and running in matters of minutes.
The script as it is gobs out a lot of errors on glfw -- I don't know if I will ever fix it -- but glfw outputs a neat gob of structured info nevertheless.

ShowTestWindow is OK as a starting point, but I need something more top-down and for now Doxy fits the bill.

--R

**Comment by emoon** [comment]
As @ocornut say I think #435 a better fit and it would make it a bit easier to use for other documentation systems. In my case I would like to use the same documentation for my wrapper but re-generated to fit it. I know others are wrapping Imgui as well so a more generic approach would (imo) be better. That being said I haven't had any time to look it it because of other projects.

**Comment by RobertoMalatesta** [comment]
Thank you, @emoon 
I will reply on #435 as soon as I can figure what #435 depicted system is.
At this moment I find it big and complex and with an ETA like -say- **post-Seveneves**
