### ISSUE TITLE
Customizing position of the drag and drop tooltip

### ISSUE THREAD

**Issue by AspectUnk** [ocornut/imgui#6973]
Hello. I can customize a tooltip using `BeginDragDropSource` with `ImGuiDragDropFlags_SourceNoPreviewTooltip`, but not the position because i cannot [disable the `SetNextWindowPos` call](https://github.com/ocornut/imgui/blob/88fec097158867edf7753fe0d842d23d67e7966d/imgui.cpp#L10264). Previously `SetNextWindowPos` was [called inside `BeginDragDropSource`](https://github.com/ocornut/imgui/blob/b88fbd69cc64ce6330aa6cf1102bfd5359ec6ff5/imgui.cpp#L13210) which disabled its call. Perhaps there is a reason for this. At the moment I see two fixes:

1. Will go back to the old version. Where the tooltip position is set inside `BeginDragDropSource`.
2. Add a flag `ImGuiTooltipFlags_IgnoreDragDrop` which should be [checked here](https://github.com/ocornut/imgui/blob/88fec097158867edf7753fe0d842d23d67e7966d/imgui.cpp#L10255). Something like of this:
```if ((tooltip_flags & ImGuiTooltipFlags_IgnoreDragDrop) == 0 && (g.DragDropWithinSource || g.DragDropWithinTarget))```

**Comment by ocornut** [comment]
Hello, this should now be solved with 1e939fc, it was a pretty simple change. You can now call SetNextWindowPos() before BeginTooltip() while in a drag and drop source or target.

I wonder if we should introduce a new `ImGuiCond_NoOverrideSetExistingValue` flag to formalize this idiom since it is used in various places.
