### ISSUE TITLE
Showing text inputs without a label?

### ISSUE THREAD

**Issue by JC3** [ocornut/imgui#6984]
I'm rendering my own labels as text on the left side of text inputs.

How do I set a text input to not have a label?

I noticed that if I pass the same label (e.g. `""`) to every input text, then all the inputs duplicate eachother. It seems they have to have unique labels.

I couldn't find a text input flag to hide the label.

**Comment by PathogenDavid** [comment]
Please read the [FAQ entry on widget IDs](https://github.com/ocornut/imgui/blob/1ab63d925f21e03be7735661500e5b914dd93c19/docs/FAQ.md#q-about-the-id-stack-system).

To remove the blank space typically used for the labels, use `ImGui::PushItemWidth(-FLT_MIN);`. This setting applies to the current window, so it must be called after `ImGui::Begin`. (Also don't forget to call `ImGui::PopItemWidth()` as well.)

-----------------

Since based on your other questions you seem to be using Python: As far as I'm aware, Python's standard library does not have an equivalent to `FLT_MIN` (everything on `sys.float_info` is for doubles since Python's `float` uses double precision.) You can create your own constant, the value should be `1.175494351e-38F`. (Really it just needs to be a tiny number, but using `-FLT_MIN` for this purpose is idiomatic Dear ImGui usage.)

**Comment by ocornut** [comment]
You may use -1 instead of -FLT_MIN but it’ll create a slight 1 px asymetry on window paddings.

**Comment by JC3** [comment]
Thank you very much! I will try all this on Monday.

**Comment by ocornut** [comment]
Closing as answered.

> How do I set a text input to not have a label?

For future reference, even though this is answered in the FAQ in "How can I have widgets with an empty label?", the general answer is to prefix your identifier with "##" , e..g "##MyInputText", as everything after "##" is hidden.

>  It seems they have to have unique labels.

This is covered in more details in the FAQ section. Most often when you have a loop submitting items you'll want to call ImGui::PushID()/PopID().
