### ISSUE TITLE
Resizing button for small windows

### ISSUE THREAD

**Issue by StArBoY-Works** [ocornut/imgui#6995]
### - window: when window is very small, prioritize resize button over close button.

Hello @ocornut I was going through the TODO.txt, I came across this in it, can you actually explain the problem a little in depth. I am willing to help you with this. Like if I am not wrong this what you are trying to say :-

![1000_F_470681974_6i0TUoUyqXfqARRjqX9YBB07CwuZuYDv](https://github.com/ocornut/imgui/assets/124769416/617b3f84-3b27-4f15-8502-ca949d935e36)

Thanks.

**Comment by ocornut** [comment]
Hello,

I appreciate the sentiment of willing to help. Due to project complexity, note that I am not encouraging contributions not motivated by an explicit need. People who are experienced and long-term committed to dear imgui will naturally find their way to contribute something, but since every problems tends to be more complex that meet the eyes, being productive on this project requires quite some involvement from both contributor and me.

It arise if you lower the value of style.WindowMinSize to a bare minimum and resize down:

![image](https://github.com/ocornut/imgui/assets/8225057/8b6cc19f-2316-41bb-bd6b-d3b702e594d9)
![image](https://github.com/ocornut/imgui/assets/8225057/00c68416-aeb5-40d2-89f7-a3609f333206)

There are situation where both close button and resize grips will overlap and ideally we would ensure that resize grips already get the hit/priority, possibly by hiding the close button. At least we shouldn't prevent case where it is impossible to resize.

However with those condition (very small value of style.WindowMinSize) there are many more glitches, which by definition suggest that no-one is decently using dear imgui with very small values. And even with it if I look at the state of things today it feels always possible to resize, so I would consider this task extra low priority and not warranting effort now. 

(I could have a pass at TODO since this particular problem isn't so meaningful anymore, but generally speaking github issues are better indicators are desirable changes than TODO.txt).

**Comment by StArBoY-Works** [comment]
@ocornut Thanks for the very quick response. Looking forward to develope the possible issues which I can handle, also can you share your email ID if possible??

**Comment by ocornut** [comment]
My e-mail address is in the README.
