### ISSUE TITLE
ARRAY_SIZE may already be defined differently before imgui_impl_opengl3_loader.h

### ISSUE THREAD

**Issue by codefrog2002** [ocornut/imgui#7017]
Version: 1.90
Branch: master

Back-end/Renderer: imgui_impl_opengl3

This is totally minor but...

`#define ARRAY_SIZE` is a fairly standard macro - which means it might have been (and was for me) already defined differently by the time imgui_impl_opengl3_loader.h is preprocessed.  For me it was a matter of formatting `(sizeof(x)/sizeof(x[0]))` not actual function.

Suggestions -

1) bake in a namespace
```
#define IMGUI_ARRAY_SIZE(x)  (sizeof(x) / sizeof((x)[0]))
```

2) Use a terminator NULL at the end of the proc_names[] array
```
  ...
    "glViewport",
   NULL,
};

    for (i = 0; proc_names[i]; i++)
        imgl3wProcs.ptr[i] = proc(proc_names[i]);
```

3) slightly bad idea - assume a previous definition is correct
```
#ifndef ARRAY_SIZE
#define ARRAY_SIZE(x)  (sizeof(x) / sizeof((x)[0]))
#endif
```

4) bad idea - force a redefinition
```
#undef ARRAY_SIZE
#define ARRAY_SIZE(x)  (sizeof(x) / sizeof((x)[0]))
#endif
```

**Comment by ocornut** [comment]
imgui_impl_opengl3_loader.h is generated by https://github.com/dearimgui/gl3w_stripped
We can update it to use its own symbol, a PR would be appreciated for both repos.

Just to confirm: you should never include imgui_impl_opengl3_loader.h  directly. Did this happen because the macro was defined as a compiler option, or because you are compiling imgui_impl_opengl3.cpp in a unity/jumbo build?

**Comment by codefrog2002** [comment]
Yep - imgui_impl_opengl3.cpp was included in an all-in-one like this
```

#include "prefix.h"  // this is where ARRAY_SIZE was defined

#if MOO_SUPPORTS_IMGUI

#define IMGUI_IMPLEMENTATION
#include <misc/single_file/imgui_single_file.h>
#include <misc/cpp/imgui_stdlib.cpp>

#if MOO_RENDER_D3D
#include <backends/imgui_impl_dx11.cpp>
#endif

#if MOO_RENDER_GL_ANY
#include <backends/imgui_impl_opengl3.cpp>
#endif

#if MOO_PLATFORM_SDL
#include <backends/imgui_impl_sdl2.cpp>
	#if MOO_RENDER_SDL_ONLY
		#include <backends/imgui_impl_sdlrenderer2.cpp>
	#endif
#endif

#if MOO_PLATFORM_WINDOWS
#include <backends/imgui_impl_win32.cpp>
#endif

**Comment by codefrog2002** [comment]
Thanks for your attention! I have created pull requests (I think). 
I've never created a pull request before so if it's not right let me know.

**Comment by ocornut** [comment]
Thank you for putting the effort, you did everything right and I've merged them.
I appreciate that you went through it for such a simple change, hopefully you learned something in the process too!

One common mistake with PR, which hasn't affected us here, but I guess you should know:
- A PR is linked to a specific branch. As you created yours from your `codefrog2002:master` branch, if you were later to make other commits to your branch, or merge my update into your branch via a merge-commit, and push that back, it would appear in the PR. The reason is because you can update PRs with subsequent commits. 
- So the common workflow for people is to create 1 branch per PR to avoid this.
- It didn't affect us at all here because I immediately merged, but if you don't know when a PR may be merged you ought to follow that workflow of creating a dedicated branch.

Thanks again!
