### ISSUE TITLE
How to implement Android floating window?

### ISSUE THREAD

**Issue by 18-Xtreme** [ocornut/imgui#7022]
**Version/Branch of Dear ImGui:**
Version: 1.9.0 WIP
Branch: Master

**Back-end/Renderer/Compiler/OS**
Back-ends: imgui_impl_android.cpp, imgui_impl_opengl3.cpp, android_native_app_glue.c
Operating System: Android 11

**My Issue/Question:**
I'm studying floating windows these days. Can you give me some ideas to implement this function, thanks.

![image](https://github.com/ocornut/imgui/assets/57245056/8bb4e4dc-2537-4ca1-951d-305902923d71)

**Comment by ocornut** [comment]
I don't know what you mean by "floating windows". Please be more explicit. 
Maybe consider reading https://github.com/ocornut/imgui/wiki/Glossary

**Comment by thedmd** [comment]
Issue isn't related directly to ImGui. Example for Android does not seem to support resizable activities.

You can try to add support for such feature. Some hints:

Adding support for [multi-window](https://developer.android.com/guide/topics/large-screens/multi-window-support) will allow you to "pop" activity as floating window. Be aware that OS may decide to not support this feature.

To get yourself a fighting chance I recomend you to use [AGDK](https://developer.android.com/games/agdk/overview) instead of NativeActivity. This will make your floating window decorations compose properly with UI. NativeActivity will simply draw over any UI dawn by OS.
