### ISSUE TITLE
Laptop GPUs communication issue (Desktop window manager)

### ISSUE THREAD

**Issue by Exploiter1007** [ocornut/imgui#7026]
**Version/Branch of Dear ImGui:**

Version: 1.90, 1.80, 1.35
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: DirectX12 & 11 & 10 & 9
Operating System: Windows 11 22H2 (Build 22621.2715)

**My Issue/Question:**

Hello dear people, I recently wanted to start using ImGui and after building your example projects, I realised there is a performance hit as soon as starting the project, even on an extremely basic window. Checking task manager it seems like the process itself has normal GPU usage but the problem is, it is triggering another windows process to rise GPU usage.
Desktop window manager (dwm.exe) is taking up to 30% of my laptop integrated GPU (AMD Radeon Graphics - 512MB Vram), this issue appears only when my integrated GPU is running. Forcing ImGui to run on dedicated GPU doesn't fix the issue while integrated GPU is also running on system. My laptop has MUX technology that lets me turn off almost entirely the integrated GPU and when I do this, DWM is has a decent GPU usage.
From my basic knowledge, it seems like it is a communication problem between GPUs through DWM.
I am happy to provide any other details needed, thank you for attention!

Notice: GLFW Vulkan seems to not have this issue.
**Screenshots/Video**

https://github.com/ocornut/imgui/assets/151369864/3128b6cf-bd59-4636-9593-e73b2bdbcc81

**Comment by ocornut** [comment]
Not much of this is specific to dear imgui.
If you were to create a window and open a dx context with same settings, you’d get same results.
Some observations: you seem to be running the app unthrottled at 200+ fps. This is abnormal for those reasons: our example apps are programmed to wait for vsync throlling themselves to refresh rate. Perhaps your gpu driver has option to enforce disable that because clearly that part doesn’t work. But a real game app would probably want to synchronize differently not relying on vsync. Its also abnormal because 4 ms/frame for such setup is abnormally high and i would suggest there’s something interfering.

> Notice: GLFW Vulkan seems to not have this issue

Then use GLFW vulkan !

seriously even tho i sympathize this isn’t really a dear imgui issue, more somethings at the intersection of MUX, DVM, your gpu drivers, settings and other programs influencing this. We cannot be investigating this on our end.
