### ISSUE TITLE
Vulkan Memory Allocator (VMA) Support

### ISSUE THREAD

**Issue by rickyjames35** [ocornut/imgui#7027]
Back-ends: imgui_impl_vulkan.cpp

**My Issue/Question:**
As reported in this issue https://github.com/ocornut/imgui/issues/4238 when enabling Vulkan eBestPractices validation layers the imgui_impl_vulkan backend implementation will cause some warnings. Like so...
```
[warning] Validation Performance Warning: [ UNASSIGNED-BestPractices-vkAllocateMemory-small-allocation ] Object 0: handle = 0x55a52c8b36e0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xdc18ad6b | vkAllocateMemory(): Allocating a VkDeviceMemory of size 77568. This is a very small allocation (current threshold is 262144 bytes). You should make large allocations and sub-allocate from one large VkDeviceMemory.
```
The fix for this would be to use a more sophisticated memory allocator like [VMA](https://gpuopen.com/vulkan-memory-allocator/). I'm wondering if it would be somehow possible to hook it up to the imgui_impl_vulkan.cpp. I haven't found any examples online of how to do this and I'm still new to Vulkan and Dear IMGUI so I'm wondering if anyone else has already looked into doing this?

**Comment by ocornut** [comment]
Moving this conversation to existing topic #4238.

**Comment by ocornut** [comment]
Should be fixed by #7189

**Comment by DexterHaxxor** [comment]
@ocornut
That's not a fix, it's just hiding the issue. The real issue here is what the code is actually doing: allocating one VkDeviceMemory per resource instead of using a proper memory allocator. Since the vast majority of Vulkan users are using VMA, I think the Vulkan backend should support (but not require) supplying a VMA allocator, which it would then use instead of allocating a VkDeviceMemory for every resource.

**Comment by ocornut** [comment]
>  I did not get the impression that it was allocating only 2 VkDeviceMemory objects.

It's allocating 1 font texture (can be shared between contexts and multiple viewports) + 1 vertex buffer + 1 index buffer for each visible viewport. As the buffer are likely to grow in the first few frames it tends to allocate twice in first few frames, and then generally the "contents growth" frames.

I'm open to said PR, but understand that my tolerance level for increased cognitive load in the codebase (for both end-users and backend editors) will be made lower by the fact this is not solving anything important. It would be merely a development to satisfy a niggle that other VMA users will inevitably (and somehow irrationally) have.

**Comment by DexterHaxxor** [comment]
Alright then, probably not worth it.

**Comment by aleksradojkovic** [comment]
I got caught into this issue - if I am using multiple frames in flight, that is higher than swapchain image count - I'm going, in first few frames, due to reallocation, to delete buffers that might be in use. Would be really nice to have a macro like IMGUI_USE_VMA or something simillar.

quick fix is to give imgui information about image count - so force it to be max(swapchainImages, maxFramesInFlight), so it can allocate multiple buffers for each image, but not sure if it's proper fix
