### ISSUE TITLE
Color Mismatch in ImGui

### ISSUE THREAD

**Issue by AshwiniNittur** [ocornut/imgui#7040]
I'm working on a project using ImGui and have encountered a color representation issue. The colors in ImGui do not seem to match what I see in Photoshop, even when using the same RGB values.

I have attached screenshots showing the discrepancy. First screenshot is ImGui created image and second screenshot is Original Photoshop image.

So far, I've tried adjusting my monitor settings and experimenting with different color values in ImGui, but the issue persists.

Thank you!

I'm encountering a color mismatch issue in ImGui (v1.87) on macOS using Visual Studio Code with the OpenGL backend.

My question is:
1. Any recommendations on how to achieve an exact match to Photoshop's color display?

<img width="1031" alt="ImGUI_created_image" src="https://github.com/ocornut/imgui/assets/151610819/5bbfdf7b-f924-4bdc-b549-53b8e44fafb2">
<img width="880" alt="Original_Photoshop_image" src="https://github.com/ocornut/imgui/assets/151610819/705f78a8-c6d9-4aec-a1e8-1443f3936e8a">

**Comment by GamingMinds-DanielC** [comment]
You would have to work with color profiles, something that is not in the scope of ImGui.

Basically, you would need to read the color profiles that are embedded in the images you want to display. A color profile defines the color space colors are stored in. Remember that different images might have different color profiles and that they are optional in most formats. If there is no embedded color profile, you would have to make the same assumptions Photoshop makes. Next, you need to know the color profile of your monitor, or again make the same assumptions Photoshop makes. Then you should have all of the information required to transform the colors into the correct color space for display.

Depending on what you want to do, it might be simpler or harder. If you just want to display the images, you can convert the colors after loading. If you want to adjust them in your app, you will want to avoid that since multiple conversions (with 8 bits per channel) will accumulate rounding errors. In that case you should load your images unchanged, but store the color profile along with the image. Store your adjustments as a chain of transformations with high precision (fp32 should be plenty) and combine everything into a single transformation when you are ready to display your image. You also need to pay attention to the characteristics of the surface format you use for your back buffers.

Here is an example of the math involved in converting between color spaces:
https://en.wikipedia.org/wiki/Adobe_RGB_color_space

**Comment by ocornut** [comment]
Unfortunately this is not really related to dear imgui itself, but to your graphics pipeline setup and is probably quite a wide topic to cover. I hope you find a satisfactory often but we cannot really answer this here.

**Comment by AshwiniNittur** [comment]
Okay.
Thanks for the response.
