### ISSUE TITLE
Immediate application and data access? 

### ISSUE THREAD

**Issue by minozheros** [ocornut/imgui#7046]
So, I don't know if it is an issue really, but I was wondering about the following. Let's say, I have a function that is called from the main loop, and I am using fs::path or something like that to read from disk. Will it read the same bits of information every frame or is there some form of caching. I am not sure, but I don't know whether the file system functions are meant to be used by an immediate app. Have you ever thought about this? 

Regards Klaus

**Comment by cfillion** [comment]
The caching would be yours to implement, not std::filesystem nor dear imgui's job. You'd probably want to build some data structure with the things read from disk then display that over and over rather than query the disk over and over every frame.

(Well technically the OS is likely to do some caching of recently read data, but you're still better off repeating as little work as possible every frame.)

**Comment by ocornut** [comment]
Closing as answered.
