### ISSUE TITLE
How to draw fixed image on the implot widget ?

### ISSUE THREAD

**Issue by ChivenZhang** [ocornut/imgui#7047]
**Version/Branch of Dear ImGui:**

Version: 1.89
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_SDL2.cpp + imgui_impl_Opengl3.cpp
Compiler: msvc2019
Operating System: windows 10

**My Issue/Question:**

I use implot (https://github.com/epezent/implot) in imgui, and I want to draw a fiexed-floating image on the plot. So I make it by using ImDrawListSplitter.
```
ImDrawListSplitter splitter;
splitter.Split(ImGui::GetWindowDrawList(), 2);

splitter.SetCurrentChannel(1);
ImGui::SetCursorPos(ImGui::GetWindowContentRegionMin());
Draw Plot;

splitter.SetCurrentChannel(0);
ImGui::SetCursorPos(ImGui::GetWindowContentRegionMin());
Draw Image;

splitter.Merge(ImGui::GetWindowDrawList());
```

As the code shown above, I split it into 2 layeres, and first draw plot, second draw image. If it works as expectation, there is an image above the plot. But it wouldn't in fact. How can I make this requirement ? Thanks for help.

**Screenshots/Video**

![image](https://github.com/ocornut/imgui/assets/48938612/37124192-4f5f-4401-a854-c5a6ad6d6c62)

**Comment by ocornut** [comment]
Advanced plots with scrolling etc are likely creating a child window, which is drawn above the parent. So you would likely need a way to access the draw list of the plot window, and then you can draw over it after the plot is drawn, and you may not it to use a draw splitter.

**Comment by GamingMinds-DanielC** [comment]
Child windows could be a thing (they can be suppressed with `ImPlotFlags_NoChild`), but your current problem is something far simpler. When you split into 2 channels, channel 0 will be the background and channel 1 will be the foreground. You are drawing your image into the background channel. If you switch channels (plot with child window suppression into 0, image into 1) the image should be on top. In fact, you don't need a splitter at all since you draw back to front.
