### ISSUE TITLE
ImGui Window Transparent Background NVIDIA Bug?

### ISSUE THREAD

**Issue by Juesril** [ocornut/imgui#7059]
I have posted something for help to make ImGui Window outside the window transparent background which was already fixed thank you, now the problem is, when the PC has an NVIDIA I don't know the specifics but what I see is when PC has nvidia ImGui Window that is suppose to be transparent was blackscreen

**Comment by sakiodre** [comment]
Sorry but #1586, I answered your last issue because it might also be helpful for other people, but this one is too ambiguous and lacks effort.

Just to let you know, this issue is not in the scope of Dear ImGui, and you should be asking this somewhere else in the first place, like StackOverflow, although you'd be downvoted to hell with this lack of effort question.
