### ISSUE TITLE
Support custom string formatter/editor

### ISSUE THREAD

**Issue by Nahor** [ocornut/imgui#7072]
It would be nice to have support for custom formatter. Currently, with the format string, one can only format how a number looks like as a sequence of digits/period/signs.

With a custom formatter, one could handle more variety:
- using sub-unit instead of decimals (e.g. `1m80`, `6'2"`, `2 years 4 months ...`)
- or multi-units display (e.g. `20°C (68°F)`)
- or translated unit (e.g. have the data in Kelvin internally, while the UI displays/edits Celsius or Fahrenheit), without having to explicitly convert into temporary variables each time the temperature is shown
- an enum number into the matching enum name (although typically one would use a combo box instead)
- special strings for special values (e.g. 0 => `auto`, >0 => `<number>`)
- singular vs plural (`1 apple`, `12 apples`)
- support non-native data types (e.g. `std::chrono`)

The formatter could also provide a custom editor. A simple/default editor would be what currently exists (inline editing), but a more advance one would provide an overlaid popup with multiple widgets:
- a date field would provide a calendar
- unit+sub-units field would provide a popup with separate fields for the unit and each sub-unit.
- ...
A default editor when custom formatting is used, could be the existing inline editing + a tooltip showing the formatted value

**Comment by GamingMinds-DanielC** [comment]
Changing the internal formatter from the current `printf` to a more advanced one would not only be a lot of work, it would also add dependencies, most likely raise the C++ language requirements and change the formatting syntax, breaking lots of existing code using this library. Seems like a lot of negatives for something most users don't need.

The good news is, you don't "need" it either, you already have it with little effort. Take f.e. the `fmt` library, you can add small wrappers like this:
```c++
namespace ImGuiFmt
{
	template <typename S, typename... Args>
	inline void Text( const S& format_str, Args&&... args )
	{
		::fmt::memory_buffer buffer; // growable, but has a small buffer inside, avoiding frequent small allocations
		::fmt::format_to( ::std::back_inserter( buffer ), format_str, ::std::forward<Args>( args )... );

		::ImGui::TextUnformatted( buffer.begin(), buffer.end() );
	}

	template <typename S, typename... Args>
	inline void SetTooltip( const S& format_str, Args&&... args )
	{
		::fmt::memory_buffer buffer;
		::fmt::format_to( ::std::back_inserter( buffer ), format_str, ::std::forward<Args>( args )... );

		::std::back_inserter( buffer ) = '\0'; // fmt::format_to() doesn't zero-terminate, but ImGui::SetTooltip needs it

		// this function is already a shortcut, could write it out with a few more lines and avoid the need for zero-termination
		::ImGui::SetTooltip( "%s", buffer.begin() );
	}

	// ...
}
```

Then use `ImGuiFmt::Text(...)` instead of `ImGui::Text(...)` and you have a modern formatter where you can plug in custom formatters for your types. You can add similar wrappers to other formatting functions like `ImGui::SetTooltip(...)`. I use this kind of wrapper quite extensively myself.

Custom editors do not come through custom formatters, that's an entirely different thing. But you already have the option to make custom widgets which then can have any overlay you like. Some of those widgets will have a wider usefulness, but many of them are rather special in nature. That's why they are nice to have in additional libraries that extend ImGui, but shouldn't be part of the core library as that would be maintenance hell.

You can take a look here for additional widgets (or for inspiration for your own), search for "date picker" since you mentioned a calendar:
https://github.com/ocornut/imgui/wiki/Useful-Extensions

**Comment by ocornut** [comment]
You may technically also `#define IMGUI_DISABLE_DEFAULT_FORMAT_FUNCTIONS` in your imconfig file and reimplement `ImFormatString()` and `ImFormatStringV()` functions however you want, as long as it is backward compatible with features we use.

I think pretty much all the examples you provide would be better served with custom local functions rather than fed into one single global formatting functions either way, so I can't see any reasonable path where we would want to complexity the core library when those things are better done outside.

**Comment by nicolasnoble** [comment]
That being said, [fmt](https://github.com/fmtlib/fmt) is quite a popular library. I'm wondering if it's worth having a ready-to-use example .h file somewhere in the repository to glue fmt properly with imgui, since this is boilerplate that'd be used many times over different projects, a bit like `misc/cpp/imgui_stdlib.h`.

**Comment by Nahor** [comment]
1. Sorry, I thought I mentioned it but I see that it's not there. The issue is not for tooltips, or simple text. Those are indeed trivial to fix by using a simpler wrapper around the widget like you said @GamingMinds-DanielC . The issue is with input widgets, like `Slider` and `Input`.
Those do their own "format-to-string" conversion. One could pass a regular string anyway (after careful escaping of special characters, like `%` and `\`), but the format string is used for more than just display. It's also used to filter the characters (e.g. general text vs numbers only), or to figure out the min number in a logarithmic slider, ... So using a non-format string is likely to cause issues.

2. I did not imply that ImGui should change the format it accepts or upgrade C++. What's I'd like is for ImGui to provide a framework so a developer could provide an alternative implementation. Something along the line of ImPlotGetter/GetterXY in ImPlot. The ImPlot can still accept the simple "array of value", but it also accept more advance "data providers" such as function pointers and lambdas. C++11 should be fine for that.
So like ImPlotGetter, that new framework would have a default implementation that would still rely on printf/scanf. I believe this could be done in a fully compatible way with the current API using wrapper functions and/or converting constructors.

3. The "editor" would be to provide an alternative to the current `TempInput` in `Slider` and `Drag`. This editor is so that the user can edit the value in way that match the displayed format. For instance, if the display is "<year> <month> <day>", the user ought to be able to edit the value in a matching form. A simple editor would just parse a string in that format. A more advanced editor would use a calendar widget.

All that said, I think there are two levels of option:
- An abstraction layer between the widget and printf/scanf
- A formalization of what an input widget is ("display" + "editor").

The latter is the most complicated and maybe not worthwhile. Maybe it's doable by the app developer using `IsItemActive`,  `AllowOverlap` and such.
I think the former is easy-ish although it would require a bit of refactoring. The printf part is definitely easy: replace the format string with some class and "execute" that class instead of calling printf. The scanf part is more complicated because it's related to the filtering/minimum increment, etc... But I think most, if not all, could be handle having a notion "partial match", or maybe a "partial match without value" (e.g. just "+" for a number), and "partial match with value" (e.g. "0.0" -> "0.001" for a logarithmic slider).

**Comment by ocornut** [comment]
**Do you have a list of specific use case you would very much like to solve?** Rather than general/hypothetical improvements.
It'd be easier to consider and weight a potential feature from this angle.

> A simple editor would just parse a string in that format. A more advanced editor would use a calendar widget.

I am not sure I understand this specific example. If you need a calendar widget you can implement it, add it to the right click of an `InputText()` item, or have the calendar widget code call `InputText()` itself, either direction would be possible. But none of this would have to go through the Slider/Drag->TempInput logic?

**Comment by Nahor** [comment]
> Do you have a list of specific use case you would very much like to solve?

- One of my use cases is that I have a slider to select a duration between 1min and 24h (stored as a number of seconds). Using seconds for the slider is meaningless. Using minutes is not any better (what's "980min"?). Using hours is better but not by much (what's the ".33" in "`16.33h"?). 
Ideally the slider would say `16h 20m`. But that requires the format string to show two numbers and they must be derived/computed from a single duration value.
And then the TempInput widget showing when using tab/ctrl+click would need accept a string in time format ("<hour>h <min>m", "hh:mm", "h:mm <am|pm>", ...).

- Another of my use cases is the temperature. Currently, I'm using a radio button to switch my UI between either Celsius or in Fahrenheit. I would prefer to be able to show both at the same time so that no switching is required.
And for tab/ctrl+click/TempInput, I would have liked to be able to show a °C/°F toggle next to it, something similar to the InputScalar but with the °C/°F toggle instead of the +/- buttons.

- And initially, I had a third use case, which was to use std::chrono instead of Unix timestamps. However, I had the forget about that early on because in my dev environment, timezones don't work with that API (although it works the POSIX API). So I never reach to the point of actually needing to use std::chrono with Sliders. But if it wasn't for that issue, I would have.
(Albeit this is a bit more than just formatting, but it does require a custom formatter before hoping to support more than the ImGuiDataTypes... Or maybe custom types should be the feature request and the formatter is just a piece of that...)

> If you need a calendar widget you can implement it, add it to the right click of an InputText() item, or have the calendar widget code call InputText() itself, either direction would be possible. But none of this would have to go through the Slider/Drag->TempInput logic?

The idea is to be able to provide a different edit widget than `TempInput` when using tab/ctrl-clicking on a Slider/Drag. Something that fits better than a textfield given what the slider value represents.

**Comment by Nahor** [comment]
#6829 could be solved with the "custom scanf/editor" part.

**Comment by ocornut** [comment]
I think down the line the most important missing component is `InputText()` support for templates (#4402), useful for e.g. IP addresses, where text position may be sparse and have gaps and extra decorations. I will most likely want to address that in a v2 of InputText.

On your specific examples:

> A slider to select a duration between 1min and 24h (stored as a number of seconds).

Underlying storage in seconds is not an issue: you can convert back and forth when calling the Slider/Input widget.

I would argue that actual _slider_ behavior on such widget is not super valuable, and you could use an `InputText()` and do back-and-forth parsing for the "16h 20h" part and you would get 80% of the way with little trouble. I don't disagree that it could be better, but if you can get 80% there with a little bit of parsing now it doesn't seem like a high-priority to fully redesign the system. The biggest win would be to have support for those template, and then I believe internals should be managed more so that the Slider->TempInput transition is easy to either hook either trivially rewrite.

> Temperature. [...] Currently, I'm using a radio button to switch my UI between either Celsius or in Fahrenheit. I would prefer to be able to show both at the same time so that no switching is required.

How would you like to show both? You may be better using a right-click context menu rather than a radio button, since it is unlikely to matter for user to have both visible together. You may also display both as those adjacent widgets and get done with it? I am not sure it would make sense to display both inside a same edit box and expect text edition to happen without confusion?

> And initially, I had a third use case, which was to use std::chrono instead of Unix timestamps. 

Why not converting yourself when calling the widget?
```
time_t time = ....from chrono type;
if (DragScalar(....))
     chronotype = ...from time;
```
In term of display/input formatting it becomes the same as your first case.

> The idea is to be able to provide a different edit widget than TempInput when using tab/ctrl-clicking on a Slider/Drag. Something that fits better than a textfield given what the slider value represents.

But I need concrete use cases, and the Calendar one seems not applicable here.

You can already assemble things using internals, I believe the key wins would be made from standardizing and simplifying that code until it become both trivial and future-proof.

**Comment by Nahor** [comment]
>> A slider to select a duration between 1min and 24h (stored as a number of seconds).
>Underlying storage in seconds is not an issue: you can convert back and forth when calling the Slider/Input widget.

The issue is that the display unit does not match the storage, but I give you that it's not the most critical part. The important part that the display is not a single unit (hours vs minutes vs seconds) but multiple (hours AND minutes). 
But fixing the latter would also allow for the former. Moreover having to convert back-and-forth every time is repetitive and error prone, and thus would benefit from custom formatters. That's why I thought it was worth mentioning.

> I would argue that actual slider behavior on such widget is not super valuable

!? I just don't understand how you get to that conclusion. What is your view of my use case? How is `InputText`, which requires a keyboard, 80% equivalent to `Slider`, which allows simple mouse click/drags? 

> How would you like to show both?

It's right there in the list of example in the first post:  `20°C (68°F)`.

https://github.com/ocornut/imgui/assets/1198364/41e4f936-4908-4bb6-83ef-1e700a6762d9

(done using a pre-formatted string)

And with a custom scanf, the user could enter "20C" or "68F" or "20°C". And if the user just enters a number, the app could always show a popup asking for the unit (the latter can be done today sure, but not the former, and the former is a much better UX experience once the user is aware of the option). 
With the option a custom editor, the editor widget could have two components: an `InputScalar` for the number and radio/combobox/someOtherWidget for the units.

> it is unlikely to matter for user to have both visible together

It matters to me because I'm more used to Celsius for low temperature and Fahrenheit for higher ones because I've lived in different countries with different temperature units and weather. So being able to see both at the same time is valuable to me. But yes I'm aware that's an uncommon usage, and that, if this was the only reason for the feature, it wouldn't be worth it. But it is not the only reason, and as such it ought to help  move the needle towards accepting the feature.
Similarly, another reason where both temperatures would be useful, is when the screen is shared with other people (meetings, screenshots, video recordings, ...). Similar my own usage, I'm aware that this doesn't have much value on its own because this is a theoretical example at this stage, but it too ought to help move the balance. Now, is that enough to actually tip it? That for you to answer. Personally I think it does, I do believe that behind my own trees, there is a whole forest of people who could make use of this feature.

For that matter, a couple of examples that exist in other applications:
- In Unreal, drag inputs can do math. One can enter "1+1" and it will become 2.
- In Blender, drag inputs can also do math, and unit conversions as well as. One can enter "50 cm" and it will become "0.5 m" in the field.

> You may also display both as those adjacent widgets and get done with it?

I never said there was no workarounds but they come at a cost. With adjacent widgets, the sliders will be half the size if they are horizontally adjacent, or they will take twice as much height when vertically adjacent. Moreover, the fact that the two widgets actually are the same thing but just with different units would be a unnecessary source of confusion to the user.

>> [std::chrono stuff]
> In term of display/input formatting it becomes the same as your first case.

Yes, that's what was implied with the last sentence of that use case ("Albeit ..."). It's the formatting/first case + a bit of extra (for the conversion). 
But it's a different way of thinking about the  overall issue: is it just about formatting? Or is it about not-necessarily-scalar data types? The former is the easy but somewhat limited option (at the very least, it requires manually converting to and from scalars every time). The latter is more general but arguably more complicated to implement.

> But I need concrete use cases, and the Calendar one seems not applicable here.

It's not concrete in the sense that ***I*** do not need, which is why I didn't not list it with the explicit "use cases".
But I believe it's a valid example of how having the option to create custom editor would be useful to not just me but others a well. (see the needle/balance thing mentioned earlier in this post)

Or if your point is that the calendar is not a good example period, the goal is to be able to to drag a slider to get a rough date that is good enough for what the user wants at that time, and still be able to enter a specific/precise date if need using ctrl-click. It is the same principle as for scalars, just with more appropriate presentation/visuals for dates.


> I believe the key wins would be made from standardizing and simplifying that code until it become both trivial and future-proof.

This issue was never a bug report. This was always a feature request/enhancement to have a unified way of supporting data that could benefit from being shown as more than just a single raw number.

> the most important missing component is InputText() support for templates (https://github.com/ocornut/imgui/issues/4402)

Yes. And my idea of a custom editor is that the InputText is itself a template parameter for the slider
```C++
template <class T>
void Formatter();
template <class T>
void Parser();

template <class T, class FORMATTER = decltype(Formatter<T>), class PARSER= decltype(Parser<T>)>
bool InputText();

template <class T, class FORMATTER = decltype(Formatter<T>), class EDITOR = decltype(InputText<T, FORMATTER>)>
bool Slider();
```
then an app can do:
```C++
// default float slider, 
// aka Slider<float, Formatter<float>, InputText<Formatter<float>, Parser<float>>>
float v;
Slider(&v);

// standard editor but custom formatter/parser
ImU32 time;
Slider(&time, TimeFormatterFunc, InputText<TimeFormatterFunc, TimeParserFunc>);

// custom editor
Date date;
Slider(&date, DateFormatter, CalendarWidgetFunc);
```

**Comment by ocornut** [comment]
I understand you mean well but you don’t seem to be considering that they are hundreds of much higher priority features piling up, and you seem to be in a mood for draining resources for non critical features. You are free to assemble custom widgets from low-level components and achieve any of those transform already. Its much easier to do on your side with 30 lines of code that to formalize it as a forever-and-for-everyone api.

> Moreover having to convert back-and-forth every time is repetitive and error prone, and thus would benefit from custom formatters. 

What will a custom formatter do if not convert back and forth every time??

> Yes. And my idea of a custom editor is that the InputText is itself a template parameter for the slider

I didn’t mean template in the C++ template sense.
It should be evident since you have studied dear imgui codebase that a proposal to increase amount of C++ templates on large functions is not going to be considered.

**Comment by Nahor** [comment]
> you seem to be in a mood for draining resources for non critical features.

I don't know where you got the idea that I'm asking it be a high priority. And FYI, the issue was not flagged low-priority, it was closed period. Heck, #4402 that you mentioned yourself is the same thing but for InputText, and that one is still opened.

But whatever, if everything I say or do is seen as a drain of resources, there is no point in my arguing. Over and out.

**Comment by GamingMinds-DanielC** [comment]
@ocornut: I have an idea of a relatively simple solution for most of these issues with minimal impact on ImGui itself. Just like `ImFormatString()` basically wraps `vsnprintf` if `IMGUI_DISABLE_DEFAULT_FORMAT_FUNCTIONS` is not defined, `sscanf` could be wrapped in a new `ImScanString()` if `IMGUI_DISABLE_DEFAULT_SCAN_FUNCTIONS` is not defined. That is already it, the whole thing.

What that would allow advanced users to do: disable the defaults, provide custom ones that mimic the default formatting/scanning if not locally overridden. For the local override, users could introduce their own stacks (`PushFormatFunc()`, `PopFormatFunc()`, `PushScanFunc()`, `PopScanFunc()`) to set overrides that can format and scan however they like, they don't even have to use the format parameter given to them. Those functions can then be overridden in simple wrappers for the widgets. At least that is what I would do if I needed this, there are lots of other options as well. And all of that outside of the ImGui library.

Well, that would already solve most of these issues. A way to override the default temp input would solve the rest, but I guess that is a bit harder to do correctly.
