### ISSUE TITLE
How to enable auto default tooltips for all items when item is hovering? 

### ISSUE THREAD

**Issue by KarKarKarKarkarkar** [ocornut/imgui#7114]
How to enable by default tooltips for all items when item is hovering? (DragFloat/InputText, and all other)

If not found custom tooltip — show default (full text from item).

**Comment by ocornut** [comment]
You are responsible for showing tooltip.
You may create helper function that calls an existing widget + SetItemTooltip() if you find this more practical but otherwise it may be more practical to just call that yourself.

(When you open new issue please take the time to read issues guidelines and fill issue template in more details, thank you.)

**Comment by KarKarKarKarkarkar** [comment]
> You are responsible for showing tooltip. You may create helper function that calls an existing widget + SetItemTooltip() if you find this more practical but otherwise it may be more practical to just call that yourself.
> 
> (When you open new issue please take the time to read issues guidelines and fill issue template in more details, thank you.)

No template for feature requests, and questions (when no issue)
