### ISSUE TITLE
Option to hide trailing zeros for float inputs

### ISSUE THREAD

**Issue by Enhex** [ocornut/imgui#712]
AFAIK imgui only supports fixed precision display.
That means that the user gets limited precision or long harder to read number.

In some cases an option to remove trailing zeros would reduce the visual noise and make numbers easier to read.

**Comment by ocornut** [comment]
Which function are you talking about?
For things like slider float if you pass a "%.4g" format string you'll get 4 digits with trailing zeros removed.

**Comment by Enhex** [comment]
InputFloat. I see it uses "decimal_precision" while sliders and drags use "display_format".

**Comment by ocornut** [comment]
I'll have to dig in my notes but there was a reason was InputFloat() doesn't take a format string. Perhaps only to disallow adding suffixes/prefixes since unlike SliderFloat/DragFloat they aren't as easily to allow.

If you want to dig into it you can add a version of InputFloat that takes an explicit format string and see how it works first? Then you can use %g in there.

**Comment by ocornut** [comment]
Hello @Enhex,
Forgot to reply on this specific is issue, but this has been solved/supported since 1.61, where `InputFloat()` and other functions can now take a const char* display_format and e.g. `%g` works with them.

**Comment by Fedr** [comment]
The problem with `"%g"` is that even `"%.6g"` prints `0.00001` in exponential format as `1e-5` (online demo: https://godbolt.org/z/KaEKsxYe5), which is good only for scientific software.

Could we have an option to convert numbers in text by some user-defined callback?
