### ISSUE TITLE
F1 menu is not blind accessible.

### ISSUE THREAD

**Issue by Computerfan23** [ocornut/imgui#7131]
Hi!
I have been playing the pc port of ocarina of time, which is called Ship of Harkinian. In the port, one of the features is to press the f1 key on a keyboard to bring up a menubar at the top of the screen where you can add enhancements and customize your experience by using different drop down menus. This uses imgui.
I am a blind player who uses a screen reader software to get text read using text to speech, write text and read menu items. I rely heavily on screen reader software since i cannot read any text or menus. I have noticed that i am not able to use the f1 menubar since if i try pressing the f1 key to open the menubar, i get no text output at all from the screen readers text to speech. It seems screen reader software cannot handle imgui elements and are not compatible at all.
The software i have been using are NVDA and narration. Both fail to get any content read.
So i am wondering if it would be a possibility to allow screen reader software to be compatible? Or make a workaround which would allow me to access the f1 menu without sighted assistance?

**Comment by ocornut** [comment]
Hello and happy new year!

It is a known issue that accessibility systems typically don't work with dear imgui output (although to be honest, I am surprised that screen reader nowadays don't rely more on OCR, as e.g. the web ecosystem tend to obfuscate data to avoid scrapping/automation).

By nature of this project, both in term of design (it is meant to be used for internal tools, its success took everyone by surprise) and and varying technical issues, and also due to lack resources, I think it is unfortunately unlikely that the situation would improve to reach 100% OS standards. 

That said, I believe there are low-hanging fruits - in term of implementation feasibility - which would very meaningfully improve the situation for many users, they are mentioned in #4122 and I think we can move the conversation there.

(also linking to #5833 but above link has more contents).
