### ISSUE TITLE
position mistake after call SameLine()

### ISSUE THREAD

**Issue by 734vin** [ocornut/imgui#7144]
## info

Version: 1.90.0
Branch: docking

Back-ends: imgui_impl_osx.cpp + imgui_impl_metal.cpp
Compiler: xcode(clang)
Operating System: macos 13.5

## screenshot
![tttttttt](https://github.com/ocornut/imgui/assets/56961542/f0aabeb6-b2a8-4aac-b5fa-e33b9d027914)

items after "SameLine()" position is a little low

**Comment by GamingMinds-DanielC** [comment]
Not the following items are too low, but the first ones are too high. That's because ImGui can't know in advance that you will submit framed items in the same line. Those are higher, so you need to adjust the unframed items (those on the red line in your image). You can do that by calling `ImGui::AlignTextToFramePadding()` beforehand.

**Comment by 734vin** [comment]
> Not the following items are too low, but the first ones are too high. That's because ImGui can't know in advance that you will submit framed items in the same line. Those are higher, so you need to adjust the unframed items (those on the red line in your image). You can do that by calling `ImGui::AlignTextToFramePadding()` beforehand.

thanks, that fix it perfectly.

**Comment by 734vin** [comment]
is my fault.
