### ISSUE TITLE
vector<string> use in ImGui

### ISSUE THREAD

**Issue by PadMadoff** [ocornut/imgui#7220]
### Version/Branch of Dear ImGui:

Version 1.XX, Branch: XXX (master/docking/etc.)

### Back-ends:

imgui_impl_XXX.cpp + imgui_impl_XXX.cpp

### Compiler, OS:

Windows 10

### Details:

I have a problem. I'm doing writing the ImGui code for an android game. The code intercepts the name of the in-game shaders, and places them in the string vector. I do not know how to display the names of the shaders from the vector in real time, which are loaded into the game.

**Comment by GamingMinds-DanielC** [comment]
Is your problem that you don't know how to display texts? You can see how to do that everywhere in the ImGui demo window, basically just this:
```c++
const char* name = "...";     // put shader name here
ImGui::Text("%s", name);      // option 1
ImGui::TextUnformatted(name); // option 2
```
Now iterate through your vector, get the names and display them. If your problem is how to access your string vector, well, that's your string vector and part of your code. Since you didn't post any code, nobody can tell you how to do that.

**Comment by emoon** [comment]
https://github.com/ocornut/imgui/issues/1586
