### ISSUE TITLE
Window closed state saving

### ISSUE THREAD

**Issue by myri4** [ocornut/imgui#7223]
### Version/Branch of Dear ImGui:

Version 1.90, Branch: docking

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_vulkan.cpp

### Compiler, OS:

Windows 10 + MSVC

### Details:

Hi. Do the .ini files support window closed/opened state? If not can this functionality be added? Thanks.

**Comment by ocornut** [comment]
> Hi. Do the .ini files support window closed/opened state?

No.

> If not can this functionality be added? Thanks.

Not likely.

Because that data drives your code and we this would lead us toward providing a general purpose serialization system.(#437, #5744), once you add one piece of data people will want ten others. So you'd be best solving this in your own way.

But you can manually extend bits in .ini.
I am surprised no-one has provided a library to facilitate adding data into it yet.
