### ISSUE TITLE
Unable to restore focused windows after dock panel is restored.

### ISSUE THREAD

**Issue by krulci** [ocornut/imgui#7224]
### Version/Branch of Dear ImGui:

Version 1.90, Branch: master (master/docking/etc.)

### Back-ends:

web

### Compiler, OS:

Windows 11

### Full config/build information:

https://pthom.github.io/imgui_manual_online/manual/imgui_manual.html
the behavior can be observed directly here.

### Details:

**My Issue/Question:**

Focus windows may not be preserved when dockspace is hidden and reenabled.
This may be directly observed in the web version of imgui_manual.

1. Select a window
2. Click Hide All
3. Click View All
4. The first frame of the reenabled layout will focus the previous selected window before hidden (frame 464 in the attached video).
5. The next frame of the reenabled layout will focus the last window of a dock node (frame 476 in the attached video).

### Screenshots/Video:

https://github.com/ocornut/imgui/assets/52474054/d0e3dcdb-0b0b-40ab-8c80-0a41e8a6c329

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
https://github.com/pthom/imgui_manual/tree/master/src
```

**Comment by ocornut** [comment]
Hello,
This is a known issue, see #2304
Basically newly appearing windows are all trying to take focus as they appear, so the last submitted one will win it. Due to how the nav system currently work it's not a trivial fix but we made changes over time to fix some cases.

We recently made a fix for the node not holding the final focused window, but for that node the issue is quite noticeable still.
