### ISSUE TITLE
build_win32.bat fatal error C1083: Cannot open include file: 'float.h'

### ISSUE THREAD

**Issue by ParticlePeter** [ocornut/imgui#7241]
### Version/Branch of Dear ImGui:

v1.90.2 WIP master branch

### Back-ends:

example_win32_directx11 + example_win32_directx12

### Compiler, OS:

Windows 10, build_win32.bat calling cl.exe from C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64

### Details:

Hello, I am trying to build and run the example_win32_directx11 and 12 using the included build_win32.bat(s), both give me the error mentioned in the topic. I cannot find any information whether we're supposed to edit the bat file and add path to the required .h, .lib, .dll files ourselves. Just reporting that the pure .bat file does not work out of the box (at least for me not). 
On that note, is there some known, easier fix to my issue, other than adding paths to the required files into the .bat file? 

Peter

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by zao** [comment]
This is typically due to not having your command line session fully set up with all the environment variables the toolchain expects.
For MSVC toolchains it doesn't suffice to have the compiler executable in path or call it with an absolute path; several environment variables are used to point out the locations of headers and libraries; akin to having `CPATH`, `LIBPATH`, `CPPFLAGS`, and `LDFLAGS` on a Linux system.

The easiest way to achieve that on Windows is to ensure that you run the build script from a Developer Command Prompt like `x64 Native Tools Command Prompt for VS 2022`. If you've got more complex requirements, you can invoke something like `"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"`.

From an ImGui perspective, this is pretty much limited to the example batch scripts, as including it in a project of your own would use your own properly configured build system.

**Comment by ocornut** [comment]
I'm closing this as answered, assuming @ParticlePeter's environment wasn't setup properly.
