### ISSUE TITLE
Previous window geometry

### ISSUE THREAD

**Issue by pozemka** [ocornut/imgui#7284]
### Version/Branch of Dear ImGui:

dear imgui, v1.90.2 WIP docking

### Back-ends:

imgui_impl_win32.h + imgui_impl_dx11.h

### Compiler, OS:

Windows 10 + MSVC 2022

### Details:

Hello I am experimenting with docking branch and trying to position one window next to another. Intent is to show window with help text next to related window.

Ideally I want something like this:
```cpp
showTools()
{
  ImGui::Begin("My Tools Window");
  //Displaying all toolls
  ImGui::End();
}
showHelp(const char* help_text)
{
  auto prev_window_geometry = ImGui::GetLastWindowGeometry(); //<--- What should be here?
  // Some positioning calculation
  ImGui::SetNextWindowPos(help_position);
  ImGui::Begin("help_window");
  ImGui::Text(help_text);
  ImGui::End();
}
...
showTools();
showHelp("This is tools window");
```

Question is how to get position and size of the last Begin-End displayed window? Sorry if I've missed something obvious.

For now my workaround is to save **current** window position (`ImGui::GetWindowPos()`) inside Begin-End and then reuse it later to position next window.

**Comment by GamingMinds-DanielC** [comment]
As far as I know there is no intended way to do this. You could add your own wrapper function to get the last window if you don't mind poking around in ImGui internals. If you want to do this, you will find the `CurrentWindowStack` in the context structure. If a window has been ended and no new window has begun yet, you will find the window at the end iterator. You should add a few safeguards as well (check if stack size is smaller than capacity, check the last active frame of the window you find, check its parent against the current window), otherwise your function will give "random" results if used at a time other than between ending a window and beginning a new one.

**Comment by ocornut** [comment]
Answer seems radically too literal.
I think realistically the user shouldn't mind referring to that window identifier, so you can do:

```cpp
ImGuiWindow* tool_window = ImGui::FindWindowByName("My Tools Window");
// then use tool_window->Pos, tool_window->Size.
```

I don't think it would be wise that we recorded the pointer/id of the "last" window:
- last Begin() or last End() ? what happens when the function nests windows?
- that would need you to make further assumptions about `showTools()` tool and break on potential reorganization of said function. 

So querying by identifier/name is better IMHO.
