### ISSUE TITLE
Is the Vulkan impl thread safe?

### ISSUE THREAD

**Issue by MarioSieg** [ocornut/imgui#7294]
### Version/Branch of Dear ImGui:

Latest

### Back-ends:

imgui_impl_Vulkan.cpp 

### Compiler, OS:

Linux

### Details:

Is it safe to call ImGui_ImplVulkan_RenderDrawData() from a different thread and a secondary command buffer?

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by ocornut** [comment]
Question is too ambiguous. From a different thread than what ?

**Comment by MarioSieg** [comment]
Than the main thread. ImGuibuses some static variables to ImGui::Render must be called on the main thread too. I wonder if it's safe to render the DrawData on a different CPU thread? Or does the Vulkan draw impl modify static variables too?

**Comment by ocornut** [comment]
“Main thread” doesn’t mean much if we don’t know what said thread is doing. Assuming your question is: can I call multiple function using the same imgui context in parallel, the answer is no you cannot.

The ImDrawData instance you are passing to RenderDrawData will be modified during the imgui frame from NewFrame() onward so you cannot. But if you made a deep copy of ImDrawData and you know you are not destroying the context, then I think you can.

**Comment by ocornut** [comment]
> But if you made a deep copy of ImDrawData and you know you are not destroying the context, then I think you can.

We don't yet have an optimal official way to handle this, but
- Since 1.89.8 ImDrawData::CmdLists is a ImVector<> which is easier to manipulate. (see https://github.com/ocornut/imgui/issues/6406#issuecomment-1632826410)
- The ImDrawList are owned by context.
- You can call ImDrawList::CloneOutput() to create a copy, it'll work but isn't most optimal.

What would be ideal would be to implement a ImDrawData::Swap()-ish function that optimally swapped all buffers between imgui's owned instance and your own instance, so there would be no copy made. But ideal buffer reuse would mean that you would hold a "double-buffer" ImDrawList for each active draw list, and ditch others, and there's no obvious way to identify a unique draw list (other than say, perhaps put their pointer in a map?).

```cpp
struct ImDrawListDoubleBuffer
{
   ImDrawList*   MainContextDrawList;
   ImDrawList*   LockedDrawList;
   bool               Used;
};

struct ImDrawDataDoubleBuffer
{
   ImDrawData   LockedDrawData;
   ImVector<ImDrawListDoubleBuffer>  DrawLists;

   void Swap(ImDrawData* main_draw_data)
   {
       // implement this:
       // clear used flags
       // for each drawlist in main_draw_data, 
       // - find matching one in our copy, else create one
       // - swap all buffer required for render
       // - resize buffers required for render in the other copy, to avoid unnecessary regrowth
       // - mark as used
       // delete unused drawlists
   } 
};
```

**Comment by ocornut** [comment]
I have now posted an efficient implementation of this idea at:
https://github.com/ocornut/imgui/issues/1860#issuecomment-1927630727
This allow avoiding the `CloneOutput()` call.
Let me know how it works in the other thread please!
