### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by Celtoys** [ocornut/imgui#73]
Have you thought much about adding image widgets? Along with that: buttons as widgets, checkboxes, radio buttons, etc.

I'm adding it to my fork at the moment but it would help you had any thoughts on how you'd approach it.

One option of course is to just add fonts to the glyph.

**Comment by ocornut** [comment]
This should be in now.

We have two functions which should cover most cases.
ImageButton() by default pad the image like a normal button. You can make the padding invisible with frame_padding=0 and a different size e.g. frame_padding=1 one pixel.

    void   Image(ImTextureID user_texture_id, const ImVec2& size, const ImVec2& uv0 = ImVec2(0,0), const ImVec2& uv1 = ImVec2(1,1), const ImVec4& tint_col = ImVec4(1,1,1,1), const ImVec4& border_col = ImVec4(0,0,0,0));
    bool   ImageButton(ImTextureID user_texture_id, const ImVec2& size, const ImVec2& uv0 = ImVec2(0,0),  const ImVec2& uv1 = ImVec2(1,1), int frame_padding = -1, const ImVec4& bg_col = ImVec4(0,0,0,1));    // <0 frame_padding uses default frame padding settings. 0 for no paddnig.

I have NOT added ImageRadioButton() yet. The reason is that I want to introduce a proper concept of what is "selected" and this will affect things in a more general way.

Right now you can mimic a radio button by poking into the button color, e.g.

 PushStyleCol(ImGuiCol_Button, ImColor(255,255,255))

Which should be bearable.
Also note I added a (totally optional) helper called ImColor() which serves to automatically convert to 4 float to 1 bytes.

**Comment by ocornut** [comment]
@dwilliamson Hope it works well for you. A fair amount has changed since November since I added the font atlas / truetype so your patch for texture handling will conflict with the new version.

**Comment by ocornut** [comment]
The demo window shows examples. It is a bit awkward because the example app don't have access to textures other than the font :)

![image buttons](https://cloud.githubusercontent.com/assets/8225057/5988931/e019debc-a96c-11e4-8393-fec62c46dd07.PNG)

Also showing color buttons easy to setup using ImColor::HSV
I may use add a global Hue-offset slider to the style editor.

**Comment by Celtoys** [comment]
Great job! I'm so far away from being able to sync to latest that this won't become an issue for me until around March or so. I'll probably just clobber my changes completely and update the broken user code.

**Comment by dwilliamson** [comment]
Great job! I'm so far away from being able to sync to latest that this won't become an issue for me until around March or so. I'll probably just clobber my changes completely and update the broken user code.
