### ISSUE TITLE
Export/Render ImGui Drawlist to PNG ?

### ISSUE THREAD

**Issue by inflex** [ocornut/imgui#7338]
### Version/Branch of Dear ImGui:

1.90WIP

### Back-ends:

SDL software rendering

### Compiler, OS:

linux

### Full config/build information:

N/A

### Details:

Is it possible to generate a stillshot/screenshot of the current ImGUI app display or  to a PNG or other image format from an ImGui DrawList ?

I would at times like to generate high resolution images of the circuit boards layouts that the program works with, and for now I can just "screenshot" from the OS but it'd often be nicer to be able to do it as an internal process and  allows me to script/customise things more.

**Comment by ocornut** [comment]
Hello,

This is mostly not a dear imgui problem, but here are some pointers.

You can
- (A) Render to texture https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples#rendering-your-game-scene-into-a-texture
- (B) Capture directly from your framebuffer (provided there's nothing obstructing).

Other suggestions:
https://github.com/ocornut/imgui/issues/4809#issuecomment-994236931

Similar discussions:
#4196 #4848 #4809 #7242

However that are a few interesting things to know/work out on Dear ImGui side:
- In July 2023 I have made some slight changes to ImDrawData to make it easier to manipulate them (e.g. to add a manually created draw list to a draw data), and providing an example here: https://github.com/ocornut/imgui/issues/6406#issuecomment-1632826410. This may be used if you want to isolate the data you want to capture into one specific draw data.
- I have recently proposed a helper to facilitate optimally preserving the contents of a full ImDrawData structure: https://github.com/ocornut/imgui/issues/1860#issuecomment-1927630727 which might also be useful.

-----

Finally, note that [Dear ImGui Test Engine](https://github.com/ocornut/imgui_test_engine) capture tool use the (B) approach "Capture directly from framebuffer":

Lowest-level code capturing from framebuffer (MIT licence):
https://github.com/ocornut/imgui_test_engine/blob/main/shared/imgui_app.cpp
Win32+DX11 in `ImGuiApp_ImplWin32DX11_CaptureFramebuffer()`.
SDL+GL in `ImGuiApp_ImplSdlGL2_CaptureFramebuffer()` then `ImGuiApp_ImplGL_CaptureFramebuffer()`.

And this is controlled by the Capture Tool (Test Engine Licence) which you can access in Test Suite->Tools:
![image](https://github.com/ocornut/imgui/assets/8225057/e666d29a-cdc2-44f1-a2a2-339a7cc71346)

The capture tool use approach (B) capture whole framebuffer and it does so by hiding/moving other windows.
(tangent: I have to admit that the code for capture tool is a bit of a disaster. I handed a first version to Rokas that was too complicated, and then for a while we tried to make it work both outside AND inside of test engine which only contributed to make it messier, so dropped the earlier, and IMHO it needs to be rewritten now)

And the Capture Tool itself may be controller by TestEngine high-level API;

```cpp
ctx->CaptureScreenshotWindow("Dear ImGui Demo", ImGuiCaptureFlags_StitchAll | ImGuiCaptureFlags_HideMouseCursor);
```
Which gives you output like (here using stiching of whole scrollable contnets)
[capture_table_demo_0000.png](https://github.com/ocornut/imgui/assets/8225057/3e33b8e2-8c83-417e-a097-2471dc796ea9)

Those screenshots in the README:
![image](https://github.com/ocornut/imgui/assets/8225057/200c03d5-b5a9-48fd-94d7-0e3007dd9016)
Are generated by the "capture_readme_styles" code in there:
https://github.com/ocornut/imgui_test_engine/blob/main/imgui_test_suite/imgui_tests_core.cpp#L6272
(It's quite long because we tried to replicate an exact existing screenshot, so it replicate the setup, in normal use you would capture an existing window)

**Comment by ocornut** [comment]
Addendum, technically someone could also use Approach A combined with a software rasterizer (as suggested in #4809), or e.g. a blink Vulkan context, to implement a library/function where you can could feed it a ImDrawList or ImDrawData and it would get you an image. It would make a convenient library.
