### ISSUE TITLE
What are these bleaches on the window? (After upgrading to v1.90.3)

### ISSUE THREAD

**Issue by abumettleq** [ocornut/imgui#7342]
### Version/Branch of Dear ImGui:

Version 1.90.3, Branch: Release (master)

### Back-ends:

imgui_impl_dx9.cpp + imgui_impl_win32.cpp

### Compiler, OS:

Windows 11, ISO C++ 17 Standard, Platform Toolset VS2022 v143

### Details:

The windows I used to create were having no issues with background and borders, however, after upgrading the .h/.cpp files of ImGui to v1.90.3 and modify some of the windows code to meet the changes done in the current version, the window started to show some bleaches all around the window, for example, the picture attached below:

![AsdaDailyBonus_1](https://github.com/ocornut/imgui/assets/84507882/27cb24cd-66db-4cb6-802a-6a865926f08e)

I use my custom function to draw windows in a game I'm developing extension windows to it, as in the code snippets below:

```
bool ImGui::BeginAsda(const char* name, bool* p_open, ImTextureID user_texture_id, const ImVec2& texture_size, const ImVec4& uv, ImGuiWindowFlags flags)
{
	ImTextureID n_01 = TextureFactory::Instance()->MakeTexture("juidata\\Image\\Texture.btz", "n_01.tex");
	ImTextureID ne_wheeltaget1 = TextureFactory::Instance()->MakeTexture("juidata\\Image\\Texture.btz", "ne_wheeltaget1.tex");
	auto canItDrawAsda = n_01 != NULL && ne_wheeltaget1 != NULL;
	//auto doesCanDrawAsda = false;

	flags |= ImGuiWindowFlags_NoCollapse;
	flags |= ImGuiWindowFlags_NoSavedSettings;

	if (canItDrawAsda)
	{
		flags |= ImGuiWindowFlags_NoTitleBar;
		flags |= ImGuiWindowFlags_NoResize;
		flags |= ImGuiWindowFlags_NoScrollbar;
		flags |= ImGuiWindowFlags_AlwaysAutoResize;
		ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 0);
		ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(10, 10));
		ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 20.0f);
		if (ImGui::GetIO().Fonts->Fonts.size() > 5)
			ImGui::PushFont(ImGui::GetIO().Fonts->Fonts[5]);
	}

	ImGui::SetNextWindowPosCenter(ImGuiCond_Appearing);
	auto result = ImGui::Begin(name, p_open, flags);

	if (canItDrawAsda)
		PopClipRect();

	if (canItDrawAsda && result)
	{
		//                      
		auto pos = GetWindowPos(), size = GetWindowSize();

		if (user_texture_id != NULL)
		{
			//              
			AddImage(n_01, ImVec2(512, 512), pos, pos + ImVec2(48, 37), ImVec4(362, 471, 48, 37));
			AddImage(n_01, ImVec2(512, 512), pos + ImVec2(48, 0), pos + ImVec2(size.x - 86, 37), ImVec4(414, 471, 4, 37));
			AddImage(n_01, ImVec2(512, 512), pos + ImVec2(size.x - 86, 0), pos + ImVec2(size.x, 37), ImVec4(422, 471, 86, 37));

			//              
			AddImage(n_01, ImVec2(512, 512), pos + ImVec2(0, 37), pos + ImVec2(20, size.y - 20), ImVec4(456, 439, 20, 4));
			AddImage(n_01, ImVec2(512, 512), pos + ImVec2(20, 37), pos + ImVec2(size.x - 20, size.y - 20), ImVec4(488, 439, 4, 4));
			AddImage(n_01, ImVec2(512, 512), pos + ImVec2(size.x - 20, 37), pos + ImVec2(size.x, size.y - 20), ImVec4(488, 439, 20, 4));

			//              
			AddImage(n_01, ImVec2(512, 512), pos + ImVec2(0, size.y - 20), pos + ImVec2(20, size.y), ImVec4(456, 447, 20, 20));
			AddImage(n_01, ImVec2(512, 512), pos + ImVec2(20, size.y - 20), pos + ImVec2(size.x - 20, size.y), ImVec4(480, 447, 4, 20));
			AddImage(n_01, ImVec2(512, 512), pos + ImVec2(size.x - 20, size.y - 20), pos + ImVec2(size.x, size.y), ImVec4(488, 447, 20, 20));

			//                   
			AddImage(ne_wheeltaget1, ImVec2(256, 256), pos + ImVec2(0, 0), pos + ImVec2(185, 37), ImVec4(100, 218, 156, 37));

			//            
			GetWindowDrawList()->AddImageRounded(user_texture_id, pos + ImVec2(3, 3), pos + ImVec2(37, 37), ImVec2(uv.x, uv.y) / texture_size, ImVec2(uv.x + uv.z, uv.y + uv.w) / texture_size, 0xFFFFFFFF, (37 - 3) / 2);

			//               
			GetWindowDrawList()->AddText(pos + ImVec2(37 + 3, 37 / 2 - CalcTextSize(name).y / 2), 0xFFFFFFFF, name);
		}
		else
		{
			//              
			AddImage(n_01, ImVec2(512, 512), pos, pos + ImVec2(53, 24), ImVec4(373, 341, 53, 24));
			AddImage(n_01, ImVec2(512, 512), pos + ImVec2(53, 0), pos + ImVec2(size.x - 53, 24), ImVec4(430, 341, 5, 24));
			AddImage(n_01, ImVec2(512, 512), pos + ImVec2(size.x - 53, 0), pos + ImVec2(size.x, 24), ImVec4(439, 341, 53, 24));

			//              
			AddImage(n_01, ImVec2(512, 512), pos + ImVec2(0, 24), pos + ImVec2(20, size.y - 20), ImVec4(456, 439, 20, 4));
			AddImage(n_01, ImVec2(512, 512), pos + ImVec2(20, 24), pos + ImVec2(size.x - 20, size.y - 20), ImVec4(488, 439, 4, 4));
			AddImage(n_01, ImVec2(512, 512), pos + ImVec2(size.x - 20, 24), pos + ImVec2(size.x, size.y - 20), ImVec4(488, 439, 20, 4));

			//              
			AddImage(n_01, ImVec2(512, 512), pos + ImVec2(0, size.y - 20), pos + ImVec2(20, size.y), ImVec4(456, 447, 20, 20));
			AddImage(n_01, ImVec2(512, 512), pos + ImVec2(20, size.y - 20), pos + ImVec2(size.x - 20, size.y), ImVec4(480, 447, 4, 20));
			AddImage(n_01, ImVec2(512, 512), pos + ImVec2(size.x - 20, size.y - 20), pos + ImVec2(size.x, size.y), ImVec4(488, 447, 20, 20));

			//               
			auto titleSize = CalcTextSize(name);
			GetWindowDrawList()->AddText(pos + ImVec2(size.x - titleSize.x, 24 - titleSize.y) / 2, 0xFFFFFFFF, name);
		}

		//                
		if (p_open != NULL)
		{
			auto id = GetCurrentWindow()->GetID("#CLOSE");
			const ImRect bb(
				pos + ImVec2(size.x - 17 - 5, 5 + 0),
				pos + ImVec2(size.x - 0 - 5, 5 + 17));
			bool is_clipped = !ItemAdd(bb, id);
			bool hovered, held;
			bool pressed = ButtonBehavior(bb, id, &hovered, &held);

			if (!is_clipped)
			{
				if (held)
					AddImage(n_01, ImVec2(512, 512), pos + ImVec2(size.x - 17 - 5, 5), pos + ImVec2(size.x - 5, 5 + 17), ImVec4(125, 241, 17, 17));
				else if (hovered)
					AddImage(n_01, ImVec2(512, 512), pos + ImVec2(size.x - 17 - 5, 5), pos + ImVec2(size.x - 5, 5 + 17), ImVec4(103, 241, 17, 17));
				else
					AddImage(n_01, ImVec2(512, 512), pos + ImVec2(size.x - 17 - 5, 5), pos + ImVec2(size.x - 5, 5 + 17), ImVec4(81, 241, 17, 17));
			}

			if (pressed)
				*p_open = false;
		}
	}

	if (canItDrawAsda)
	{
		ImGui::PopStyleVar(3);
		if (ImGui::GetIO().Fonts->Fonts.size() > 3)
			ImGui::PushFont(ImGui::GetIO().Fonts->Fonts[3]);
		ImGui::SetCursorPosY(ImGui::GetCursorPosY() - 5 + 37);
	}

	return result;
}
```

```
void ImGui::SetNextWindowPosCenter(ImGuiCond_ cond)
{
	SetNextWindowPos(ImVec2(GetIO().DisplaySize.x * 0.5f, GetIO().DisplaySize.y * 0.5f), ImGuiCond_Appearing, ImVec2(0.5f, 0.5f));
	ImGui::SetNextWindowBgAlpha(1.0f);
}
```

**Comment by GamingMinds-DanielC** [comment]
Hard to say without more information. Could be an obscure bug in the library or render backend that manifests itself with your custom rendering, could be a mistake in your custom rendering that didn't make a difference until some bug was fixed in the library.

What version did you use before and how did it look then? Can you pinpoint the revision that broke your custom rendering? Should be doable in a small amount of attempts if you use a binary search pattern while switching revisions. F.e., if the current revision -1000 still worked, try -500. If that still works, you limited the break to the range of -500 to 0, try -250 next. If -500 already didn't work, the break is in -1000 to -500, try -750 next. After 10 steps like this, you are down to the exact revision.

Also always a good way to analyze rendering problems: make a frame capture with RenderDoc and look if anything is incorrectly set up.

**Comment by abumettleq** [comment]
@GamingMinds-DanielC 
Answering your questions:
1. I moved from "dear imgui, v1.63 WIP" to "1.90.3"
2. It looked like this ...
![image](https://github.com/ocornut/imgui/assets/84507882/391f8f32-3fb7-46ff-a3ed-32fcd50789cf)
* to note that previously I didn't have to round the window, now I need to round it by '20.0f' to look like the one provided in the image.

3. I don't have this project uploaded to Github to restore/revise the changes, however, I have created do folders of this project, one from before the upgrade, and one after.

Also I had to change some code lines to adapt the deleted functions, e.g. :
```
\\ From
if (window->DC.ItemFlags & ImGuiItemFlags_ButtonRepeat)
	flags |= ImGuiButtonFlags_Repeat;
bool hovered, held;
bool pressed = ButtonBehavior(bb, id, &hovered, &held, flags);
if (pressed)
	MarkItemValueChanged(id);

\\ To
if (window->Flags & ImGuiItemFlags_ButtonRepeat)
	flags |= ImGuiButtonFlags_Repeat;
bool hovered, held;
bool pressed = ButtonBehavior(bb, id, &hovered, &held, flags);
if (pressed)
	MarkItemEdited(id);
```

To note that I'm not experinced at ImGui, I'm still learning and I appreciate the community help, thanks.

**Comment by GamingMinds-DanielC** [comment]
Ah, I figured out what's wrong. The old backend version likely used point sampling while the current one uses a bilinear magnification filter. Your texture doesn't extend its contained images into a small border, that's why stretched images bleed into the background color while filtering. This one f.e.:
```c++
AddImage(n_01, ImVec2(512, 512), pos + ImVec2(48, 0), pos + ImVec2(size.x - 86, 37), ImVec4(414, 471, 4, 37));
```
If you want to stretch a 4 texel wide image across a lot more pixels, you need to add a border in your atlas, so that at least 1 pixel to the left and right are identical. Otherwise, the leftmost pixel is halfway between the leftmost texel of your specified coordinates and the texel to the left of it. Same goes for the right side, also for the top and bottom for vertically stretched textures. In your case 1 texel border should be enough, more are needed if you have mip maps for minification filters.

A proper pre-processing of your texture would mark all pixels as part of a tile or part of the background gaps first. Then, set every texel to the average of all tile texels of the 8 texels around it if there are any. Mark those texels as tiles, repeat the process as many times as your borders need to be thick, or until no texels marked as background remain.

An alternative would be to switch the texture sampler in the backend back to point sampling.

**Comment by ocornut** [comment]
On this specific suggestion by Daniel, also refer to #7230

**Comment by abumettleq** [comment]
Interesting ...

![image](https://github.com/ocornut/imgui/assets/84507882/72eda351-7e23-4a9f-92a1-25f1df4f6ca8)

What could be wrong now? as you see, the window is very dim, also the close button (still clickable).

PS: changes I've done

```
void ImGui::AddImage(ImTextureID user_texture_id, const ImVec2& texture_size, const ImVec2& a, const ImVec2& b, const ImVec4& uv, ImU32 col)
{
	ImVec4 imVec4Clamp(uv.x / 256.0f, uv.y / 256.0f, uv.z / 256.0f, uv.w / 256.0f);

    auto u0 = ImClamp(imVec4Clamp.x / texture_size.x, 0.0f, 1.0f);
    auto v0 = ImClamp(imVec4Clamp.y / texture_size.y, 0.0f, 1.0f);
    auto u1 = ImClamp((imVec4Clamp.x + uv.z) / texture_size.x, 0.0f, 1.0f);
    auto v1 = ImClamp((imVec4Clamp.y + imVec4Clamp.w) / texture_size.y, 0.0f, 1.0f);
    ImGui::GetWindowDrawList()->AddImage(user_texture_id, a, b, ImVec2(u0, v0), ImVec2(u1, v1), col);
}
```

**Comment by GamingMinds-DanielC** [comment]
You divided all coordinates by 256, then still by the texture size which is 512x512. So basically you are only sampling from the top-left 2x2 texels of your texture, which are just the background color between tiles. Everything being black is to be expected in this case.

But why did you add additional clamping in the first place? Clamping is not the problem here, your texture coordinates were correct before. Your problem is either the missing border around tiles in your texture or the sampler setup in the render backend, neither is addressed by this change. Even if clamping was the problem it would be in the wrong place (the correct one would be the sampler setup again).

**Comment by abumettleq** [comment]
Before I proceed to change the sampler setup, I wanna make sure if the function alright?

```
void ImGui::AddImage(ImTextureID user_texture_id, const ImVec2& texture_size, const ImVec2& a, const ImVec2& b, const ImVec4& uv, ImU32 col)
{
    auto u0 = ImClamp(uv.x / texture_size.x, 0.0f, 1.0f);
    auto v0 = ImClamp(uv.y / texture_size.y, 0.0f, 1.0f);
    auto u1 = ImClamp((uv.x + uv.z) / texture_size.x, 0.0f, 1.0f);
    auto v1 = ImClamp((uv.y + uv.w) / texture_size.y, 0.0f, 1.0f);
    ImGui::GetWindowDrawList()->AddImage(user_texture_id, a, b, ImVec2(u0, v0), ImVec2(u1, v1), col);
}
```

and the way to call it is like this?
```
AddImage(n_01, ImVec2(512, 512), pos + ImVec2(size.x - 20, size.y - 20), pos + ImVec2(size.x, size.y), ImVec4(488, 447, 20, 20));
```

**Comment by GamingMinds-DanielC** [comment]
> Before I proceed to change the sampler setup, I wanna make sure if the function alright?

Yes, that looks correct.

**Comment by ocornut** [comment]
Please use latest version and alter sampling state using AddCallback(), similarly to what is suggested there:
https://github.com/ocornut/imgui/issues/7230#issuecomment-1893476566

**Comment by abumettleq** [comment]
Done, thanks.

```
// altered
bd->pd3dDevice->SetSamplerState(0, D3DSAMP_MINFILTER, D3DTEXF_POINT);
bd->pd3dDevice->SetSamplerState(0, D3DSAMP_MAGFILTER, D3DTEXF_POINT);
// default
//bd->pd3dDevice->SetSamplerState(0, D3DSAMP_MINFILTER, D3DTEXF_LINEAR);
//bd->pd3dDevice->SetSamplerState(0, D3DSAMP_MAGFILTER, D3DTEXF_LINEAR);
```
