### ISSUE TITLE
ImDrawVert::col should be 'uint32_t' instead of 'unsigned int' (or 'ImU32')

### ISSUE THREAD

**Issue by powof2** [ocornut/imgui#737]
Hi and thank you for your great job! 

ImDrawVert.col is defined as ImU32 and ImU32 is type defined as unsigned int, which on 64-bits systems becomes 64-bits, this is not really wanted. I think the ImU32 should be type defined as 'uint32_t' instead of 'unsigned int'.
```
typedef unsigned int ImU32;  // <--- line 66 in lmGui.h

struct ImDrawVert
{
    ImVec2  pos;
    ImVec2  uv;
    ImU32   col;  // <--- bug : on 64-bits system, this become 64 bits
};
```

**Comment by ocornut** [comment]
On which system unsigned int is 64-bits? I don't think this is how C++ defines it.

**Comment by emoon** [comment]
macOS (El Captian 64-bit): 4 bytes
Linux (Ubuntu 64-bit): 4 bytes
Windows 10 64-bit (VS 2015): 4 bytes

So I wonder as well

**Comment by powof2** [comment]
Sorry, it looks that i am wrong. i checked again on iOS, Mac and Windows, on these systems sizeof(int) is indeed 32 bits.  I don't remember since when i got a impression that sizeof(int) is not always 4 bytes, sorry.

**Comment by wose** [comment]
Hi,

the size of integral types is not defined in the C++ standard. The standard just states that these types must have at least some size (same for unsigned):
> There are five standard signed integer types: “signed char”, “short int”, “int”, “long int”, and “long long int”. In this list, each type provides at least as much storage as those preceding it in the list.

The size is also not related to the hardware/OS, so it is not determined by the CPU or OS. The compiler decides what size unsigned int actually has.

This has probably no practical impact because unsigned int has usually the size of 4 Byte. At least I don’t know any exception. However, if one wants a guaranteed 32bit integer and not **at least** 32bit one should use types like uint32_t.

Cheers

**Comment by emoon** [comment]
It's possible to have a static assert on this also if wanted.
