### ISSUE TITLE
multiply defined sscanf error in example_glfw_opengl3

### ISSUE THREAD

**Issue by dgm3333** [ocornut/imgui#7407]
### Version/Branch of Dear ImGui:

1.90.5 WIP: direct pull and build of docker branch

### Back-ends:

glfw_opengl3

### Compiler, OS:

win 11

### Full config/build information:

VS 2022

### Details:

Pulled imgui. without making any changes trying to build glfw_opengl3
I'm not sure why libcurl is being included and getting compile error
builds fine with win32_opengl3

1>------ Build started: Project: example_glfw_opengl3, Configuration: Debug x64 ------
1>libcurl-d.lib(libcurl-d.dll) : error LNK2005: sscanf already defined in imgui.obj
1>C:\Repos\imgui\examples\example_glfw_opengl3\Debug\example_glfw_opengl3.exe : fatal error LNK1169: one or more multiply defined symbols found
1>Done building project "example_glfw_opengl3.vcxproj" -- FAILED.

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by PathogenDavid** [comment]
Something is messed up in your build environment.

The first place I'd look is for any environment variables mentioning libcurl.

-----------------

An unlikely yet possible source of ambient environment nonsense would be `Directory.Build.props`, `Directory.Build.targets`, and `Directory.Build.rsp` files. Any of these located in any folder up from the location of `example_glfw_opengl3.vcxproj` would affect the build.

You can rule these out by placing dummy files in the root of the Dear ImGui repo. (For `props/targets` write `<Project></Project>` for the file's contents. For the `rsp` just put an empty file.

(I've seen broken build scripts automatically generate these in the root of the `C:` drive and such before, so it's worth checking.)

-----------------

It might help to look at the linker command being run, seeing where libcurl is coming from or maybe other less fatal linker flags getting injected might job your memory of something you did to mess up your environment.

To view the link command, go to Tools > Options... > Projects and Solutions > Build and Run. Change "MSBuild project build output verbosity" to `Detailed`. (Make sure to change this back when you're done -- the default is `Minimal`.)

Rebuild the project. In the output window Ctrl+F for `link.exe`

For reference, here's the full link command for the Debug x64 build of `example_glfw_opengl3` on my machine. The paths will be different but everything else should generally be the same:

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\link.exe /ERRORREPORT:PROMPT /OUT:"C:\DearImGuiPath\examples\example_glfw_opengl3\Debug\example_glfw_opengl3.exe" /INCREMENTAL /NOLOGO /LIBPATH:"..\libs\glfw\lib-vc2010-64" opengl32.lib glfw3.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /NODEFAULTLIB:msvcrt.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:\DearImGuiPath\examples\example_glfw_opengl3\Debug\example_glfw_opengl3.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:\DearImGuiPath\examples\example_glfw_opengl3\Debug\example_glfw_opengl3.lib" /MACHINE:X64 "C:\DearImGuiPath\examples\example_glfw_opengl3\Debug\imgui.obj"
    "C:\DearImGuiPath\examples\example_glfw_opengl3\Debug\imgui_demo.obj"
    "C:\DearImGuiPath\examples\example_glfw_opengl3\Debug\imgui_draw.obj"
    "C:\DearImGuiPath\examples\example_glfw_opengl3\Debug\imgui_tables.obj"
    "C:\DearImGuiPath\examples\example_glfw_opengl3\Debug\imgui_widgets.obj"
    "C:\DearImGuiPath\examples\example_glfw_opengl3\Debug\imgui_impl_glfw.obj"
    "C:\DearImGuiPath\examples\example_glfw_opengl3\Debug\imgui_impl_opengl3.obj"
    "C:\DearImGuiPath\examples\example_glfw_opengl3\Debug\main.obj"
```

--------------------

I'm not sure if there's any Visual Studio settings that can cause this, but you can launch the [experimental instance of Visual Studio](https://learn.microsoft.com/en-us/visualstudio/extensibility/the-experimental-instance) to rule out that sort of thing. (This basically just launches Visual Studio with a separate profile independent of your default one, it should act like it's the first time you've launched it. It's called the experimental instance because it's typically used for testing Visual Studio extensions. You can actually use anything for `Exp` to have different profiles.)

--------------------

A slightly more aggressive approach would be to use [the MSBuild Structured Log Viewer](https://github.com/KirillOsenkov/MSBuildStructuredLog) to dig into what's happening when your project builds. This should definitively tell you where libcurl is coming from, I'd start by searching `libcurl` and see where it first appears in the build process.

**Comment by ocornut** [comment]
I think vcpkg integration is linking all libs automatically so maybe look in that direction, but i wouldn’t understand why imgui.obj would carry a copy of sscanf().

**Comment by PathogenDavid** [comment]
> I think vcpkg integration is linking all libs automatically so maybe look in that direction

In our official example?

> but i wouldn’t understand why imgui.obj would carry a copy of sscanf().

`sscanf` is optionally inline. If a symbol is inline in one compilation but not in another, they will conflict at link time.

**Comment by ocornut** [comment]
> In our official example?

no i meant i recall this is how vcpkg automatic integration works when enabled.

**Comment by dgm3333** [comment]
@PathogenDavid You were right regarding the broken build environment.
Shortly after getting this imgui error I started to get new errors in other projects. After fully reinstalling vcpkg and all packages they have resolved...

**Comment by hellquister** [comment]
I run in the same issue. All projects with 'GLFW' hit same error.
I solved it by getting last version of GLFW and setting up include/lib directories to particular version (for VisualStudio).
So, there is a problem in precompiled glfw3.lib of this solution.

P.S. Ignoring the problem doesn't help.
