### ISSUE TITLE
Help! Program crashes after ImGui panel is dragged slightly off screen

### ISSUE THREAD

**Issue by kaitabuchi314** [ocornut/imgui#7414]
### Version/Branch of Dear ImGui:

docking

### Back-ends:

imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp

### Compiler, OS:

Windows 10

### Details:

My ImGui app crashes after I drag a panel offscreen. It says Draw_data is nullptr.

### Screenshots/Video:

![Screenshot 2024-03-17 133931](https://github.com/ocornut/imgui/assets/93952418/9bfab5c2-6a4a-4cd1-a303-4ac47f67c61f)

### Minimal, Complete and Verifiable Example code:

```
ImGui_ImplOpenGL3_NewFrame();
        ImGui_ImplGlfw_NewFrame();
        ImGui::NewFrame();
        ImGui::DockSpaceOverViewport(ImGui::GetMainViewport(), ImGuiDockNodeFlags_PassthruCentralNode);
        renderer.ClearScreen(0.3f, 0.6f, 0.2f);

        renderer.DrawImage(img, x, y);

        ImGui::Begin("Settings");
        ImGui::Text("Hello, ImGui!");
        ImGui::End();
        ImGui::EndFrame();
        ImGui::UpdatePlatformWindows();
        ImGui::RenderPlatformWindowsDefault();
        ImGui::Render();
        ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
```

**Comment by PathogenDavid** [comment]
Hello!

In the future you should include a stack trace from the crash, otherwise there usually isn't enough info to help you debug. It's shown in the call stack window of Visual Studio when the debugger stops your program. It'll look something like this:

![image](https://github.com/ocornut/imgui/assets/278957/7ccab237-6243-42a4-bfa3-71b7386f96d7)

(If you don't see this window, go to Debug > Windows > Call Stack)

------------------------

That being said, your render code isn't quite right. `ImGui::UpdatePlatformWindows` and `ImGui::RenderPlatformWindowsDefault` must happen after `ImGui::Render`.

You're getting a crash because you're trying to render platform windows before `ImGui::Render` is called to create the draw data necessary to render them.

Additionally you're missing the logic for backing up and restoring the OpenGL context, see the `example_glfw_opengl3` for reference:

https://github.com/ocornut/imgui/blob/adcc3217c38142e965eae679a299a34ce1c963d5/examples/example_glfw_opengl3/main.cpp#L194-L203

**Comment by ocornut** [comment]
Thank you David for your answer.

This error would normally be caught in `UpdatePlatformWindows()` as there is a corresponding assert which will detect it:
```cpp
IM_ASSERT(g.FrameCountEnded == g.FrameCount && "Forgot to call Render() or EndFrame() before UpdatePlatformWindows()?");
IM_ASSERT(g.FrameCountPlatformEnded < g.FrameCount);
```
So it means @kaitabuchi314 that your assert are disabled, and me adding more checks/asserts won't help.

To facilitate your use of dear imgui you should make sure that failing asserts are visible to do.
E.g. if you call `IM_ASSERT(false);` your app/debugger should stop or show you a message.

By default `IM_ASSERT()` calls `assert()` and I don't exactly know what would make assert disabled but it is generally when `NDEBUG` is defined via the build system. I believe that cmake by default sets `NDEBUG=true` which IMHO is a huge problem, this should be overridden.

Good luck!
