### ISSUE TITLE
Question: PushStyleColor

### ISSUE THREAD

**Issue by grimmier378** [ocornut/imgui#7429]
### Version/Branch of Dear ImGui:

Version 1.90, Branch: XXX (master/docking/etc.)

### Back-ends:

imgui_impl_XXX.cpp + imgui_impl_XXX.cpp

### Compiler, OS:

Windows 11

### Full config/build information:

```
Dear ImGui 1.90.1 WIP (19001)
--------------------------------
sizeof(size_t): 4, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _MSC_VER=1939
define: _MSVC_LANG=201703
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_dx9
io.ConfigFlags: 0x00000040
 DockingEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C0E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 3 fonts, Flags: 0x00000000, TexSize: 1024,1024
io.DisplaySize: 1707.00,996.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 11.00
style.FrameBorderSize: 1.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

**My Issue/Question:**

I have a question concerning PushStyleColor. I have been working on a script in lua for macroquest that uses ImGui windows. MacroQuest allows multiple scripts to run wich can each have their own windows.

I made a color style editor to export the color styles to a table so people can import them into their scripts. I also notice if I push the color styles and don't pop them before ending the window they apply globally.  I think this is kind of neat as i can skin all of the windows to match. 

My Question though is. Is this acceptable as a means of pushing colors globally? Will it break anything? I did notice if I open the style editor before pushing the changes you get the backup copy created in the style editor so you can revert if need be.  Would that be a more acceptable way for applying the colors globally across all windows (not already styled, since local push/pop has higher priority)?

I have included some videos below.

Thank you.

### Screenshots/Video:

https://vimeo.com/925723868/b74bba83c1?share=copy

https://vimeo.com/926169221/44ee6e6838?share=copy

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```
https://github.com/grimmier378/ThemeZ

**Comment by cfillion** [comment]
> I also notice if I push the color styles and don't pop them before ending the window they apply globally.

They must be popped eventually before the frame ends. If you don't & it doesn't assert, perhaps the application is doing `ErrorCheckEndFrameRecover` to automatically do the missing Pops. Or assertions are disabled (bad idea) & then the color stack keeps growing up to multiple GBs.

It's perfectly fine to have many windows between the pushes&pop though. All `PushStyleColor` does is save the current value from the `ImGui::GetStyle().Colors` table into a stack before modifying it. `PopStyleColor` then nicely reverts it back.

You could also write the colors directly to the style color table if the Lua bindings you're using implement that. The guideline is to only do so before frame initialization but the line is a bit blurry with the demo's `ShowStyleEditor` writing mid-frame. (For my own binding's demo I've re-implemented it to use Push/Pop.)

Some elements (eg. docking) may only be styled before the frame starts because they are drawn from `NewFrame`.

**Comment by grimmier378** [comment]
Thank you for explaining that to me. I guess I was hoping that the StyleEditor was acting as the safety net to catch the changes and back up the original for reversion. But I don't want to be bloating the color stack either.
