### ISSUE TITLE
Modal window should set WantCaptureKeyboard / WantCaptureMouse flags

### ISSUE THREAD

**Issue by adcox** [ocornut/imgui#744]
I was playing around with the `io.WantCaptureKeyboard` and `io.WantCaptureMouse` flags today and found that `io.WantCaptureKeyboard` is only true when the mouse is inside an ImGui window. This seems reasonable for regular windows (although it would be nice to detect if an InputText, for example, had focus and was being typed in regardless of the mouse location), but I think modal windows should set `WantCaptureKeyboard` and `WantCaptureMouse` to true. It is easy enough for me to use `CaptureKeyboardFromApp()` and `CaptureMouseFromApp()` to get this behavior, but it seems like it should be part of the default, underlying code. Just a thought. :)

**Comment by ocornut** [comment]
Hello @adcox,
Sorry for taking such a long time to look at this.
It looks like some of the thing you described were either already fixed since your post, either your use cases differs from mine.

> found that io.WantCaptureKeyboard is only true when the mouse is inside an ImGui window [...] detect if an InputText, for example, had focus and was being typed in regardless of the mouse location)

It seems to work here, io.WantCaptureKeyboard stays 1 even if I hover outside the input text and outside an imgui window.

> I think modal windows should set WantCaptureKeyboard and WantCaptureMouse to true.

Modal windows currently set `WantCaptureMouse` to true at all time. 
This was already the case when you posted it?

`WantCaptureKeyboard` however isn't set. 
Does anybody reading this uses popup and modals and expect the application behind to react to keyboard? How about: when opening a color picker, the application may want to use inputs to manipulate objects or sceneries that are affected by the color change?

**Comment by towerpark** [comment]
In my opinion, the current behavior of keyboard part is a little counter-intuitive, and it would be better to always set `WantCaptureKeyboard` to 1 at least when a modal window is being shown.

@adcox's pretty easy workaround works for me, though  :)

**Comment by ocornut** [comment]
Hello,

I have now pushed this change to make MODAL windows always set `WantCaptureKeyboard` to 1. Thanks!

As for the other points raised by @adcox (with the InputText) example I couldn't confirm/repro.

-Omar

**Comment by towerpark** [comment]
Hello Omar,

Thank you for the quick response.
I tried the text input issue in demo application, and couldn't repro it either. If I find any problems in future, I will report it back here.
