### ISSUE TITLE
DualShock4 Gamepad detected on GLFW but not Win32

### ISSUE THREAD

**Issue by luke-moll-itdev** [ocornut/imgui#7479]
### Version/Branch of Dear ImGui:

Version 1.90.1, Branch: master

### Back-ends:

imgui_impl_win32.cpp + imgui_impl_directx9.cpp / imgui_impl_glfw.cpp + imgui_impl_opengl2.cpp

### Compiler, OS:

imgui-demo-binaries-20240105.zip

### Details:

Using a Playstation DualShock 4 controller connected via USB to a Windows 10 PC, and the ImGui pre-built demo binaries (20240105).

When I use `example_glfw_opengl2.exe` or `example_glfw_vulkan.exe`, `io.BackendFlags: HasGamepad` is true under Configuration > Backend Flags. Some of the controller buttons have effects on the GUI, but not quite what I would expect.
When instead I use `example_win32_directx9.exe` or `example_win32_directx11.exe`, the box is unchecked. None of the controller buttons have any effect on the GUI.

Should the Win32 backend be able to detect a USB game controller? And if so, what troubleshooting steps can I take to work out why it is not happening in my case?

Ultimately, I will be integrating a USB game controller with an existing ImGui application, using Win32 and DX11 backends. I am using the ImGui demo to test this functionality before development begins.

**Comment by ocornut** [comment]
The DualShock 4 is not supported via XInput API so requires legacy support or a custom driver like ds4windows.
It’s possible that GLFW maps legacy input with an arbitrary mapping, I don’t know.
I don’t think it is viable for us to aim to support those devices. Most software on Windows don’t support DS4 without a custom driver extension. Steam does it by loading its own custom driver since too many games had this issue.

**Comment by luke-moll-itdev** [comment]
I see - where could I find details of XInput's supported controllers?

My ultimate goal is to support a custom USB HID device that is sending Gamepad keys. Would this be possible with the Win32 backend (with some extension), or would I have to go straight to Windows' RawInput API and intercept the device there?
