### ISSUE TITLE
SDL3 backend text input does not work

### ISSUE THREAD

**Issue by TylerGlaiel** [ocornut/imgui#7492]
### Version/Branch of Dear ImGui:

v1.90.5

### Back-ends:

imgui_impl_sdl3.cpp

### Compiler, OS:

windows 10

### Details:

Text Input does not work with the SDL3 backend (on windows), according to SDL3's migration guide, one change from SDL2 to SDL3 is that "SDL_StartTextInput()" is necessary to be called before it will emit SDL_EVENT_TEXT_INPUT, and the backend does not currently do this

**Comment by ocornut** [comment]
This is possibly fixed by #7452 . I’ll try to get to it early next week.

**Comment by ocornut** [comment]
I have pushed said fix, however, note that IME inputs are currently essentially broken because somehow the keys (e.g. arrows, enter) gets sent to both the IME and the app, and app reacting to it usually means unfocusing the text widget.

**I'm not sure how to fix that, I would appreciate if someone with SDL3 interest could investigate it.**

I'm puzzled by SDL3 messing with system IME, when things would just work by default if didn't mess with it.

I'm also puzzled by the `SDL_StartTextInput()` design. Currently in other backends it is always possible for apps/widgets to access characters. It's not possible with SDL3. I think there are situation where OSD keyboard may be opt-in rather than always on. e.g. if you want to implement a Windows Explorer-style "typing select" feature you need to read characters without an always-visible prompt.
