### ISSUE TITLE
Imgui community 

### ISSUE THREAD

**Issue by KlewyWorle** [ocornut/imgui#7547]
### Version/Branch of Dear ImGui:

Version 1.11,  Branch: XXX (master/docking/etc.)

### Back-ends:

imgui_impl_XXX.cpp + imgui_impl_XXX.cpp

### Compiler, OS:

Gcc

### Details:

Hello 
I wonder if there is a discord server about imgui or something?

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by ocornut** [comment]
Hello, there is none.
There was a discord a few years ago but I closed it because I realized it was detrimental to the quality of answers and their ability to appears in search engines.  Nowadays we focus on having everything here on github, but I don't doubt they must be communities of people talking about dear imgui in other places too.
