### ISSUE TITLE
Unresolved external symbol, all ImGui CPP Files are included

### ISSUE THREAD

**Issue by pogrammerX** [ocornut/imgui#7582]
### Version/Branch of Dear ImGui:

Version 1.90.1

### Back-ends:

imgui_impl_SDL2.cpp + imgui_impl_vulkan.cpp

### Compiler, OS:

Windows 10 + MSVC 2022

### Details:

Hello, I'm trying to use ImGui in my game engine, however im running across an Issue when compiling.
I have included all the ImGui CPP Files in my Project, however for some reason this is happening to me:
``` 1>------ Build started: Project: Test, Configuration: Debug x64 ------
1>neuron.lib(C_NEVulkanRendererSubsystem.obj) : error LNK2019: unresolved external symbol "bool __cdecl ImGui_ImplSDL2_InitForVulkan(class SDL_Window *)" (?ImGui_ImplSDL2_InitForVulkan@@YA_NPEAVSDL_Window@@@Z) referenced in function "public: __cdecl C_NEVulkanRendererSubsystem::C_NEVulkanRendererSubsystem(class C_EngineInstance *)" (??0C_NEVulkanRendererSubsystem@@QEAA@PEAVC_EngineInstance@@@Z)
1>  Hint on symbols that are defined and could potentially match:
1>    "bool __cdecl ImGui_ImplSDL2_InitForVulkan(struct SDL_Window *)" (?ImGui_ImplSDL2_InitForVulkan@@YA_NPEAUSDL_Window@@@Z)
1>C:\Users\pogrammerX\source\repos\NeuronEngine\x64\Debug\Test.exe : fatal error LNK1120: 1 unresolved externals
1>Done building project "Test.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 11:02 AM and took 00,357 seconds ==========
```

I would appreciate any sort of help, Cheers.

### Screenshots/Video:

![image](https://github.com/ocornut/imgui/assets/84614495/dec3e091-589c-477c-a100-ffd01722ff59)

**Comment by PathogenDavid** [comment]
`C_NEVulkanRendererSubsystem.obj` is being built with `SDL_Window` incorrectly forward-declared as a class instead of a struct. This changes the mangled name of `ImGui_ImplSDL2_InitForVulkan`, which causes the linker to fail to resolve the symbol since the definition properly references `struct SDL_Window`.

Note that your error is for <code>ImGui_ImplSDL2_InitForVulkan(<b>class</b> SDL_Window \*)</code>.

The linker tried to alert you to this by noting that the similar (correct) function <code>ImGui_ImplSDL2_InitForVulkan(<b>struct</b> SDL_Window \*)</code> is in fact defined.

Look around in your code for an incorrect forward-declaration (IE: `class SDL_Window;`.) It'll be in `C_NEVulkanRendererSubsystem` or some file included by it.

**Comment by pogrammerX** [comment]
> `C_NEVulkanRendererSubsystem.obj` is being built with `SDL_Window` incorrectly forward-declared as a class instead of a struct. This changes the mangled name of `ImGui_ImplSDL2_InitForVulkan`, which causes the linker to fail to resolve the symbol since the definition properly references `struct SDL_Window`.
> 
> Note that your error is for `ImGui_ImplSDL2_InitForVulkan(class SDL_Window *)`.
> 
> The linker tried to alert you to this by noting that the similar (correct) function `ImGui_ImplSDL2_InitForVulkan(struct SDL_Window *)` is in fact defined.
> 
> Look around in your code for an incorrect forward-declaration (IE: `class SDL_Window;`.) It'll be in `C_NEVulkanRendererSubsystem` or some file included by it.

That fixed it! Thanks a lot!

**Comment by ocornut** [comment]
Both of your posts appeared while I was typing my answer.
This "Hint on symbols that are defined and could potentially match:" thing is quite great!

Note the different mangling:
`?ImGui_ImplSDL2_InitForVulkan@@YA_NPEAVSDL_Window@@@Z)` 
vs
`?ImGui_ImplSDL2_InitForVulkan@@YA_NPEAUSDL_Window@@@Z)`

Based on https://en.wikiversity.org/wiki/Visual_C%2B%2B_name_mangling
The V vs U indeed correspond to class vs struct.
