### ISSUE TITLE
How to programmatically trigger Table column sorting?

### ISSUE THREAD

**Issue by k-poppe** [ocornut/imgui#7626]
### Details:

What is the best way to solve the following use case?

#### Use Case:
When a user interacts with a window containing a table with multiple sortable columns, they might click on a column header to sort the entries. The goal is to save the user's column sorting preference so that the next time the window is opened, the table is already sorted according to their last selection.

Similar question: https://stackoverflow.com/questions/78096342/can-dear-imgui-tables-be-sorted-from-somewhere-else

_Sorry if this was answered previously, but I couldn't find it._

**Comment by ocornut** [comment]
> The goal is to save the user's column sorting preference so that the next time the window is opened, the table is already sorted according to their last selection.

If that's the goal, you have nothing to do as this should already be saved in imgui.ini.
If it's not saved, you have another problem and you should investigate this precise problem, maybe by crafting a repro.

To answer the question, the function to call in imgui_internal.h is `TableSetColumnSortDirection()`:
`void TableSetColumnSortDirection(int column_n, ImGuiSortDirection sort_direction, bool append_to_sort_specs);`
By setting `append_to_sort_specs = false` you can clear existing specs and replace this with the new one.
HOWEVER, as per your statement, I don't think you should call this. You should instead aim to understand why your data isn't saved, because lack of save will come with other issues
.

**Comment by k-poppe** [comment]
Thank you for pointing that out, Omar! The problem was with the ID stack, each time a new table key was being saved in the `imgui.ini` file, at first I tried various things (e.g. adding ##/### id in BeginTable, adding PushID/PushOverrideID), but nothing worked as the issue was with the incorrect value being used in `PushID` way before that table code snippet.
