### ISSUE TITLE
Question: GetCurrentWindow internal function

### ISSUE THREAD

**Issue by ElectroidDes** [ocornut/imgui#7713]
### Version/Branch of Dear ImGui:

1.90.8

### Back-ends:

Raylib

### Compiler, OS:

Windows 10

### Details:

Please tell me how “safe” it is to use the GetCurrentWindow function from “Imgui_internal.h”?

I mean, GetCurrentWindow() and the ImGuiWindow structure are not official external APIs, and what are the chances that the ImGuiWindow structure fields might be renamed or removed in future versions?

**Comment by GamingMinds-DanielC** [comment]
How safe it is depends on the fields you want to access. Some of them are very safe, some not so much. But there are ways to reduce the impact of potential changes. Instead of making heavy use of internals throughout your code, you can wrap access to internals into functions in a small extension library. Add a little bit of documentation so that you know where to look just in case your wrapper ever breaks, then you will be fine.

A small example of such a wrapper...

ImGuiEx.h:
```c++
#include <imgui_internal.h>

namespace ImGuiEx
{
	// use to switch to a window within its dock node without bringing it to the front
	void SelectWindowInDockNodeTab( ImGuiWindow* window );
}
```

ImGuiEx.cpp:
```c++
#include "ImGuiEx.h"

namespace ImGuiEx
{
	void SelectWindowInDockNodeTab( ImGuiWindow* window )
	{
		// see implementation of ImGui::FocusWindow for reference
		if ( window->DockIsActive )
		{
			ImGuiTabBar* tabBar = window->DockNode->TabBar;
			if ( tabBar != nullptr )
				tabBar->SelectedTabId = tabBar->NextSelectedTabId = window->TabId;
		}
	}
}
```

**Comment by ocornut** [comment]
> I mean, GetCurrentWindow() and the ImGuiWindow structure are not official external APIs, and what are the chances that the ImGuiWindow structure fields might be renamed or removed in future versions?

This is the most used internal data type and function, it’s unlikely to change.

**Comment by ElectroidDes** [comment]
> This is the most used internal data type and function, it’s unlikely to change.

Understood. Thank you!
