### ISSUE TITLE
Is Carriage Return usable is window label?

### ISSUE THREAD

**Issue by icyselec** [ocornut/imgui#7776]
### Version/Branch of Dear ImGui:

Version 1.90.8, Branch: docking

### Back-ends:

cimgui-love

### Compiler, OS:

Unknown, Linux

### Full config/build information:

```
Dear ImGui 1.90.8 (19080)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201103
define: IMGUI_DISABLE_OBSOLETE_FUNCTIONS
define: IMGUI_DISABLE_OBSOLETE_KEYIO
define: __linux__
define: __GNUC__=9
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: cimgui-love
io.BackendRendererName: cimgui-love
io.ConfigFlags: 0x00000040
 DockingEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00000007
 HasGamepad
 HasMouseCursors
 HasSetMousePos
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,800.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

**My Issue/Question:**
Is carriage-return valid even if it's between two hash characters?

My goal is to render two consecutive hash characters. I tried several methods, and eventually found a possible one. (That means all the other characters look like blank or question mark characters. Maybe.) Inserting a carriage return between two hash characters. I think this is useful in some cases. But I want to know if this is the expected behavior.

**I using this Language and Library/Wrapper**
LuaJIT, cimgui-love

### Screenshots/Video:

![Screenshot_20240708_005026](https://github.com/ocornut/imgui/assets/32571365/dfcd138a-d81e-4313-acc3-caaa532204da)
### Minimal, Complete and Verifiable Example code:

```lua
local ImGui = require 'cimgui'

ImGui.love.Init()

-- store in local variables to prevent GC.
local title = "Hello#\x0D#World"

function love.draw ()
  if ImGui.Begin(title)
    -- On window is opened
  end

  ImGui.End()

  ImGui.Render()
  ImGui.love.RenderDrawLists()
end
```

**Comment by ocornut** [comment]
> Is carriage-return valid even if it's between two hash characters?

The two hash characters won't be treated any specially since they are not consecutive. The carriage-return will be treated as if anywhere else in the strings.

Is your goal is to display ## within a window title or somewhere else?

The '\r' will be inserted e.g. in .ini file and other locations and may confuse some things.

It is correct that by default only `\r` will have AdvanceX == 0.0f. 
Right now this is technically undefined behavior to to do what you are doing, but if it works for you by all means do it. I just can't guarantee this is never going to change, but if it does it is likely we'd have a workaround.

You can also always use `ImFont::AddGlyph()`, set its AdvancedX property to 0.0f and its Visible property to false. After calling AddGlyph(), `font->Glyphs.back()` will be the last added glyph.
`
