### ISSUE TITLE
Horizontal scrolling demo for tables is broken

### ISSUE THREAD

**Issue by ARibecaJob** [ocornut/imgui#7802]
### Version/Branch of Dear ImGui:

Version 1.90.9, Branch: master

### Back-ends:

DX9 + Win32

### Compiler, OS:

MSVC2019, Win10

### Full config/build information:

```
Dear ImGui 1.90.9 (19090)
--------------------------------
sizeof(size_t): 4, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _MSC_VER=1929
define: _MSVC_LANG=201402
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_dx9
io.ConfigFlags: 0x00000003
 NavEnableKeyboard
 NavEnableGamepad
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1264.00,761.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

Hi,

as per subject, ImGuiTableFlags_ScrollX works only first time in Horizontal scrolling demo.
If related checkbox is disabled and the re-enabled, horizontal scrollbar is not showed.
You can reactivate it if you disabled ImGuiTableFlags_Resizable flag.

### Screenshots/Video:

![bug](https://github.com/user-attachments/assets/9b196847-9771-428b-b946-4f7450ec78e0)

**Comment by ocornut** [comment]
I believe this is correct behavior.

- When you disable _ScrollX the first time the columns default policy change from Fixed to Stretch (which is the desirable default, as explained in "COLUMNS SIZING POLICIES" section), and thus gets smaller as they spread available space based on their previous width relative to each others.
- When you reenable _ScrollX their default policy change back from Stretch to Fixed. Because they are still _Resizable they have no reason to auto-resize. If you manually resize them the horizontal scrollbar will reappear.
- If you disable _Resizable they became auto-resizing and thus take more space, which also makes the horizontal scrollbar reappear.

There is nothing wrong with this situation AFAIK.
