### ISSUE TITLE
Touchpad tap to click not captured when io.ConfigInputTrickleEventQueue is false

### ISSUE THREAD

**Issue by kyle-sylvestre** [ocornut/imgui#7886]
### Version/Branch of Dear ImGui:

Version 1.91.1 WIP, Branch: master

### Back-ends:

imgui_impl_metal.cpp + imgui_impl_osx.cpp

### Compiler, OS:

macOS + Clang 15

### Details:

Tapping to click with a laptop touchpad fails when io.ConfigInputTrickleEventQueue is false. I have replicated this problem on a Windows 10 laptop and a Macbook M3 Air.

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::GetIO().ConfigInputTrickleEventQueue = false;
ImGui::Begin("Touchpad Example");
static bool b;
ImGui::Checkbox("Untappable", &b);
ImGui::End();
```

**Comment by ocornut** [comment]
Yes that’s the point of this feature, it must not be disabled on a touchpad.

**Comment by ocornut** [comment]
I am curious about why you tried to disable it?
I will try to amend comments to clarify its purpose.

**Comment by kyle-sylvestre** [comment]
Typing fast with trickle on feels sluggish when rendering on computers with vsync on at 60Hz, turning trickle off lets me display characters in an InputText() as fast as possible. Ideally I'd only want the mouse down/up trickle since these touchpad taps are not getting captured.

**Comment by ocornut** [comment]
> Turning trickle off lets me display characters in an InputText() as fast as possible. 

You are correct that in the current version, there is a 1 frame delay processing characters because of this code.
This is caused by fa2b318dd
I am surprised that I didn't comment further on this when pushing this. I was eager to "fix" the issue outside of `InputText()` that I didn't fix this well enough, and it may feel different depending on whether your backend submits characters or keys first.

With
```cpp
[03322] [io] Processed: Key "H" Down
[03322] [io] Remaining: Text: h (U+00000068)
[03323] [io] Processed: Text: h (U+00000068) <-- processed by `InputText()`
```
Without
```
[05931] [io] Processed: Key "H" Down
[05931] [io] Processed: Text: h (U+00000068) <-- processed by `InputText()`
```

**I believe an issue should be open for this, ideally we could aim to find a way to disable some of the trickling better for text input.** I don't have the solution yet but I can investigate.

**Comment by kyle-sylvestre** [comment]
I agree, I'll make a new issue referencing this one.
