### ISSUE TITLE
Please add support for std::bitset in CheckboxFlags.

### ISSUE THREAD

**Issue by Mahmoud1205** [ocornut/imgui#7909]
### Version/Branch of Dear ImGui:

Version 1.91.0, Branch: Any

### Back-ends:

Any

### Compiler, OS:

Any

### Details:

**My Issue/Question:**
Just a feature request for std::bitset to be supported using a list of checkboxes. Example usage below
```cpp
const unsigned int kBitsetSize = 8;
std::bitset<kBitsetSize> settings;

void render() {
    ImGui::Begin("Window"); 
    const char* labels[] = {"Render Clouds", "Render Shadows", "Render Particles", /* and so on */};
    // first param would be a pointer to the bitset, second would be the size of the bitset, third would be the labels for each checkbox, fourth would be the size of the labels array
    ImGui::BitsetCheckboxList(&settings, kBitsetSize, IM_ARRAYSIZE(labels));
    // this should render 8 chechboxes each representing a bit in the bitset, and each with their given label
    ImGui::End();
}
```

**Comment by GamingMinds-DanielC** [comment]
That would just be a single loop with a single call in the loop body, you can easily wrap this into a custom function if you need it more often. No need to have this in the core library. Detrimental even since this would add a new dependency while not being very flexible (f.e. adding tool tips for each individual checkbox would not be possible with your proposed function signature).

**Comment by ocornut** [comment]
Yes, the point is a functional UI is that you can easily create your own helpers and widgets.
`ImGui::` is a namespace so you can declare those in the same namespace if you like.
It should be a very small function to write on your end.
