### ISSUE TITLE
ErrorLogCallbackToDebugLog is declared but not implemented

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#8015]
### Version/Branch of Dear ImGui:

Version 1.91.2

### Back-ends:

any

### Compiler, OS:

any

### Details:

This prevents from generating correct cimgui.
Other functions in ` Error Checking, State Recovery` section have the same problem

**Comment by ocornut** [comment]
You may be using mismatched source files? Because the function is in imgui.cpp.

**Comment by sonoro1234** [comment]
In fact it is in imgui.cpp
I got confused because searching imgui repo for `ErrorLogCallbackToDebugLog` only showed it on imgui_internal.h so it seems a github error.

I must investigate a build error in https://github.com/cimgui/cimgui/actions/runs/10991245431/job/30513210944

**Comment by ocornut** [comment]
Oh I see it is because for every function in the format `Log(const char* fmt, ....);` you are automatically assuming a `LogV(const char* fmt, va_list args)` version exist.

Please note that I have _REMOVED_ this use of ... in my work branch (I'm working on something related) so you won't have any problems in 1-2 days.
In the meanwhile can you include a hack to ignore this function?

**Comment by sonoro1234** [comment]
I found that typical pattern neede by cimgui generation

```cpp
void ImGui::DebugLog(const char* fmt, ...);
void ImGui::DebugLogV(const char* fmt, va_list args)
```
is failing because there is `void    ImGui::ErrorLogCallbackToDebugLog(void*, const char* fmt, ...)` but not `void    ImGui::ErrorLogCallbackToDebugLogV(void*, const char* fmt, va_list args)`

Perhaps could be skipped or manual generated but I havent found much info about `ErrorLogCallbackToDebugLog`

**Comment by sonoro1234** [comment]
Ops I didnt saw your message!!

**Comment by ocornut** [comment]
The function has been removed now in latest code anyhow! closing this.
