### ISSUE TITLE
Why is the DRAGDROP_HOLD_TO_OPEN_TIMER variable a constant?

### ISSUE THREAD

**Issue by cr545l** [ocornut/imgui#8097]
### Version/Branch of Dear ImGui:

Version 1.90.9, Branch: docking(master/docking/etc.)

### Back-ends:

Custom

### Compiler, OS:

Windows 11 + MSVC

### Full config/build information:

```
Dear ImGui 1.90.9 (19090)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 4, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1939
define: _MSVC_LANG=201402
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: NULL
io.BackendRendererName: NULL
io.ConfigFlags: 0x0000C480
 DockingEnable
 ViewportsEnable
 DpiEnableScaleViewports
 DpiEnableScaleFonts
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigWindowsMoveFromTitleBarOnly
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000140E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 2048,2048
io.DisplaySize: 2258.00,1264.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

```
static const float          DRAGDROP_HOLD_TO_OPEN_TIMER = 0.70f;    // Time for drag-hold to activate items accepting the ImGuiButtonFlags_PressedOnDragDropHold button behavior.
```
`imgui_widgets.cpp:L91`

I want to reduce the speed at which drag-to-open occurs, but I found that it is defined as an immutable constant in the code. 
While simply modifying this value would allow me to change it easily, would you consider exposing this value externally?

**Comment by ocornut** [comment]
I don't believe that exposing everything is a good idea, so by default I don't expose things.
It tends to make the user experience less consistent, and it also tends to burden the software with extra maintenance (because underlying logic may want to change, those value don't always mean the same thing over time, or altering the logic may means completely changing values).

So you would need to convince me why you need to change this value for your use case. I have tuned it based on experience, and e.g. what Windows does.
