### ISSUE TITLE
multiple ImageButtons with the same image

### ISSUE THREAD

**Issue by septag** [ocornut/imgui#813]
I'm trying to draw multiple image buttons with the same TextureID but only the first one triggers ...
```
if (ImGui::ImageButton(...)) {
   // just triggers for the first button
}
```

When I draw the buttons with different TextureIDs every one of them gets triggered on click.

**Comment by ocornut** [comment]
It was a bit short-sighted of the ImageButton() api that it is inferring the ID from the TextureId.
You can resolve the ID ambiguity by using `PushId / PopId`.

(I have a task to add an updated API with an explicit `const char* id` later on, but for now it didn't seem urgent)

**Comment by septag** [comment]
thanks

**Comment by Vibek** [comment]
Hello,
I just started using imgui. I am wondering, is it possible to visualize the real-time video images from the camera in imgui. We design a program about scene analysis using depth camera. Now I am responsible to design a GUI so that all the plots, graphs, real-time images, depth images and so on can be shown in one window. 

So, let me know, it is possible to design a window which show the real-time images from the camera.

**Comment by ocornut** [comment]
@Vibek You can, read the documentation about `ImTextureId`, `ImGui::Image()` `ImDrawList::AddImage()` etc. and check the demo code. ImGui doesn't care if your image comes from a camera, it's just passing around texture identifier that maps to your low-level renderer, you can display anything with it.

**Comment by Vibek** [comment]
Thanks Omar.
