### ISSUE TITLE
Question about determining hot and active items.

### ISSUE THREAD

**Issue by schell** [ocornut/imgui#834]
Forgive me if this question is misplaced but this project looks the most recent and active imgui implementation. I've started an imgui implementation in haskell and am struggling a bit with the concept of hot and active (which I have not yet added), specifically around the order of rendering. Let's say I have two overlapping buttons and the mouse is over both:
```haskell
btn1State <- renderButton btn1 location
btn2State <- renderButton btn2 location
if btn1State == btn2State
  then putStrLn "both buttons"
  else return ()
```
In this case whichever button is rendered first will become active and hot if clicked, simply because the second button doesn't "exist" at the time the first was rendered. Then the second button becomes active and hot if clicked. What is the general method to reconcile this?

**Comment by schell** [comment]
Sorry, I think I have `hot` and `active` reversed! The question is still the same though.

**Comment by ocornut** [comment]
The general and most common methods is to not reconcile this. Overlapping widgets (e.g. buttons) within a same local context (e.g. same window) rarely make sense from a user from of point of view. It is equivalent to Z fighting in a 3d engine.

What Dear ImGui does is that it decide which window is hovered by the mouse - windows are kept z-sorted and one it can first do a coarse test to determine the window (which include child windows, take care of the some subtleties for popups/modals, etc.) and then the first overlapping widget within that within will receive the hit.

(

In reality there are some more tricky cases that dear imgui tries to handle on a case by case basis to solve some rarer but useful use cases. One of those pattern is that a widget can "allow" an subsequent overlapping widget to steal hovering. This is directly exposed in SetItemAllowOverlap().

Frame N:
- Widget A is overlapped by mouse, set as hovered
- Widget A explicitly allows to be overlapped (`HoveredIdAllowOverlap=true` in dear imgui)
- Widget B is overlapped by mouse, set as hovered (allowed because `HoveredIdAllowOverlap` is set).

With this pattern both widgets will react as being hovered. 
This is sometimes quite desirable, sometimes not.

Another extension of this pattern is to perform a similar check but over two frames.

Frame N:
- Widget A is overlapped by mouse, set as hovered, but do NOT report it to end-user just yet
- Widget A explicitly allows to be overlapped (`HoveredIdAllowOverlap=true` in dear imgui)
- Widget B is overlapped by mouse, set as hovered (allowed because `HoveredIdAllowOverlap` is set).

Frame N+1
- Widget A is overlapped by mouse, check is it was hovered on Frame+N, only report to end-user if so (in this case not)
etc.

With this pattern (which is very rarely used but I found case where it was necessary) there is 1 frame of lag when moving the mouse _TO_ Widget X, it will report hovering one frame late. 

Note that a multi-pass imgui can easily solve all those issues. Dear ImGui is single-pass because I think the pros outweight the cons for the use we are making and the scope of this project. 
But some library may want to be multi-pass.

**Comment by schell** [comment]
I see, okay - those are the child windows you were talking about. Great! Thank you very much for your explanation.
