### ISSUE TITLE
DirectX 9 DLL

### ISSUE THREAD

**Issue by dowit** [ocornut/imgui#888]
Hello i would like to make a simple dll that i will inject into a game that using d3d9
I just want a simple form with few really basic controls in my dll 

I just want to see the menu in the game when i inject the dll
If anyone can provide a source for this it would be really nice :)

**Comment by ocornut** [comment]
Sorry this is out of the scope of what imgui provides for you. All the information pertaining to imgui are included in the examples DirectX9.

Since there is a huge influx of cheaters asking questions here, may I suggest that your community organize itself to share the knowledge/samples you need to perform your deed?

**Comment by Nukem9** [comment]
@ocornut dear imgui has been linked on a forum where the majority of the users only know how to copy/paste code, so you'll continue to get these for a while.

**Comment by ocornut** [comment]
I suppose everyone has to learn somewhere - it's just that I can't be spending my time giving programming tips and answering mildly off-topic questions, so I have to be more harsh with closing issues.
