### ISSUE TITLE
Multiple Scrolling Region

### ISSUE THREAD

**Issue by vivienneanthony** [ocornut/imgui#894]
Hello,

I'm trying to implement multiple scrolling regions.

**Visually**
[Career]     [Tier1]
............      [Tier2]
............      [Tier3]

I tried the following code 
```

 // Set four columns for tiers


                    ImGui::Columns(2);

                    ImGui::PushItemWidth(100.0f);

                    ImGui::Text("Career");

                    ImGui::NextColumn();

                    ImGui::Text("Tiers");

                    for(unsigned int idx=0; idx<4; idx++)
                    {

                        static const char * label= "###label"+idx;
                       
                        ImGui::BeginChild(label,ImVec2(0,100),true);
                        ImGui::Spacing();
                        ImGui::Text("test");

                        ImGui::EndChild();
                        ImGui::Separator();
                    }

```

I'm not sure what is wrong. It's nothing major but I am wondering if anyone tried it before.

Vivienne

**Comment by ocornut** [comment]
Vivienne,

The problem here is that your 4 calls to BeginChild use the same identifier, so it is appending 4 times to the same child.

In C++ when you assign to a static variable when declaring it, the assignment is only done the first time.
Furthermore, `"label"+idx` isn't doing what you think it is doing here. Raw `char*` are pointers so by doing `pointer_to_literal_string + offset` you are offsetting the pointer.

So ` "###label" + 1` with return the pointer to `"##label`, here.
You may want to read about C string, or use std::string if you are unconfortable with it, or use sprintf() to generate a temporary string into a buffer.

```
char buf[32];
sprintf(buf, "label%d", idx);
```

The other less obvious and tricky issue here is that when passing a string identifier to BeginChild(), the identifier isn't being hashed using the ID stack of imgui. That might change in the future.

So you can do:

```
char buf[32];
sprintf(buf, "label%d", idx);
BeginChild(buf,...)
```

or


```
PushId(idx);
BeginChild(GetId("anything")); // Unique id made of idx+anything, read docs in imgui.cpp about id stack
...
PopId()
```

```
ImGui::Begin("Bug #894");
ImGui::Columns(2);
//ImGui::PushItemWidth(100.0f);
ImGui::Text("Career");
ImGui::NextColumn();
ImGui::Text("Tiers");
for (int idx=0; idx<4; idx++)
{
    ImGui::PushID(idx);
    ImGui::BeginChild(ImGui::GetID("child"),ImVec2(0,100),true);
    ImGui::Spacing();
    ImGui::Text("test");
    ImGui::EndChild();
    ImGui::PopID();
    ImGui::Separator();
}
ImGui::End();
```

![capture](https://cloud.githubusercontent.com/assets/8225057/20031935/5ef62cfe-a380-11e6-9767-45f75a4f74ca.JPG)

PS: the PushItemWidth() call appears to be useless here.

**Comment by vivienneanthony** [comment]
Thank you for the clarification.

**Comment by ocornut** [comment]
No problem. By the way I applied the change to BeginChild() that I wanted to do already, which is that the stack-id is applied over the string child label.

So in the example above:
```
    ImGui::PushID(idx);
    ImGui::BeginChild(ImGui::GetID("child"),ImVec2(0,100),true);
    ImGui::Spacing();
    ImGui::Text("test");
    ImGui::EndChild();
    ImGui::PopID();
```
It is now possible to just pass a string to BeginChild():
```
    ImGui::PushID(idx);
    ImGui::BeginChild("child", ImVec2(0,100),true);
    ImGui::Spacing();
    ImGui::Text("test");
    ImGui::EndChild();
    ImGui::PopID();
```
Which is the common pattern.
