### ISSUE TITLE
Image is giving weird results on Direct3D 11

### ISSUE THREAD

**Issue by citruslee** [ocornut/imgui#903]
Hey there, I am creating a "realtime art studio" (demoscene) and I took the liberty of using ImGui as my windowing framework. It works quite well, except I see my shader resource views (textures/samplers) like this http://pasteboard.co/q7h9BDu9O.png . As you can see, the color is completely desaturated. I am using vanilla D3D 11 code from the samples directory but with a small modification, and that I use linear space rendering with SRGB textures (so I need the color with pow(col, 2.0)) but I don't think that's the problem. I am quite helpless, I've tried to fix this the last 3 days without a success.
![image](https://cloud.githubusercontent.com/assets/4135686/20234359/486d7916-a87a-11e6-89a0-fca1d471ddff.png)

**Comment by ocornut** [comment]
Could be that the currently active blending state and texture sampler state are not a match for rendering your texture as expected.

If your engine supports variety of texture formats and rendering parameters, you may want to store a higher level primitive, say `MyMaterial*`, in ImTextureId instead of just `ID3D11ShaderResourceView*`, and modify the renderer to apply whatever render state makes sense accordingly.

You can use e.g. RenderDoc to debug your rendering.

**Comment by citruslee** [comment]
you are right, it is because of the blending set in the imgui impl. I seriously should integrate imgui as a part of my engine fully and not use the sample code, but rather my frameworks code to draw the rendercmds. I turned it off and it looks like this now so I might be on a right track, just figure out how to get the text back. Thank you!


![image](https://cloud.githubusercontent.com/assets/4135686/20237826/7695f7ce-a8dd-11e6-804d-7968ab002fe4.png)

**Comment by ocornut** [comment]
Nice! Let me know if you have further problems, and please post final results in the screenshot thread =)

**Comment by citruslee** [comment]
I still have a ton of work on this framework (called Minerva) but until then, you can see what have been done with it :) http://www.pouet.net/prod.php?which=68178
