### ISSUE TITLE
Hi! setting ImGui on Playstation4

### ISSUE THREAD

**Issue by snbmm** [ocornut/imgui#975]
Hi, I am working on a cross-platforms project using ImGui. The platforms include Mac OSX, windows and playstation 4. I could find all the information and tutorials for Mac with OpenGL and Windows with DX, but not the PS4 (with PSSL?). So I am wondering is there a PS4 introduction for beginner? 

Thanks! ImGui is an amazing platform!

**Comment by Roflraging** [comment]
I imagine that NDAs prevent the release of such code.

If you are familiar with graphics programming and the graphics API provided on the PS4, it should not be too difficult to write your own code to use dear ImGui.

**Comment by ocornut** [comment]
As Dale pointed out, if you already have rendering/input code functional for the PS4. wrapping imgui (following the examples of the other wrappers) should be trivial. Your engine should have a way to upload a texture, a way to render triangles from a vertex buffer with a basic shader, etc. If you aren't familiar with your custom graphic engine maybe ask someone in the team who does.

It wouldn't be mega useful to provide a PS4 example (that we could release on devnet) using GNM etc. because 95% of people working on PS4 already have their own layer over GNM.

**Comment by snbmm** [comment]
Thanks very much for the responses, because it is the first time we are working on PlayStation 4, we haven't decided which engine or graphic library will be used in this project. GNM or OpenGL ES can be the development tools for now as I think. It will be great if I can see how does it work with GNM on devnet. If there will be a post on DevNet of GNM based ImGui, please kindly let me know.

**Comment by ocornut** [comment]
There's no much thread afaik. Maybe just ask there. If you look at any imgui example and understand OpenGL or DirectX you'll easily understand what to do (upload texture, render triangles). How to perform those with GNM is another exercise left to the passionate reader :) but there are regular GNM examples to do similar things, the extrapolation shouldn't be very hard. I don't think I can help more and unfortunately have no time right now to invest to write standalone examples for proprietary API.

**Comment by snbmm** [comment]
Thanks ocornut, that helps a lot already:)

**Comment by ocornut** [comment]
Cool - Closing this for now.
