### ISSUE TITLE
Use of struct ExampleAppLog from ImGUI_demo.cpp

### ISSUE THREAD

**Issue by Darenn** [ocornut/imgui#999]
Hi !
First, thank you for this great library, I am developing a 2D game engine and I use it for debug purposes.

I have seen the **struct ExampleAppLog** in your demo, and I tried to use it in my own project.
No problem with the **standard usage**, where you mention to create an ExampleAppLog as a **static** variable. But I have some when I try to have **multiple ExampleAppLog stored in a member attribute.**

I am searching in my code why I have theses problems (it seems that the AppLog write on other objects memory, but i'm not sure).

**So I just want to know if your implementation of ExampleAppLog allow us to create one non static.**

Thanks ! 
PS: Sorry for my poor english level.

**Comment by ocornut** [comment]
I'm just using static in the examples to move what's essentially a global inside the host function for locality and convenience and avoiding any form of storage that gets in the way of the example, but you can perfectly instantiate it in any other way you see fit.

I might just move it to be a global because some people are confused by the meaning and use of static.

If you have problems when storing it please state the problem and the repro.

-Omar

**Comment by Darenn** [comment]
Thanks for the anwser, I keep digging.

**Comment by Darenn** [comment]
Hi ! Problem resolved, my fault. ;) The AppLog works perfectly. Thanks for the help.
